### ISSUE TITLE
Specify container-runtime in CR without creating custom launch template

### ISSUE THREAD

**Issue by Noksa** [aws/karpenter#1002]
**Tell us about your request**
Currently as I can see in the code https://github.com/aws/karpenter/blob/acbf53f403db09397e788760953f2723f66d6d79/pkg/cloudprovider/aws/launchtemplate.go#L161
container-runtime is containerd by default for almost all nodes.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently we use EKS 1.21 and we don't want to use containerd as runtime by default.
At the same time we don't want to create custom launch template

So I suggest to add a new field in `Provisioner` resource that will be responsible for what we pass to kubelet's `--container-runtime` flag. And by default it should be as now - `containerd`

**Are you currently working around this issue?**
I haven't tried it yet but it looks like I have to create custom launch template with custom userData to override default bevaiour.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Noksa** [comment]
Also maybe it is valuable to add a field with custom `kubelet` flags or custom `userData`.
So if we only want to change `userData` or set custom flags for `kubelet` it would be convenient to do it without custom launch template.
If it is okay for you please consider this as well

**Comment by Noksa** [comment]
In addition it would be very convenient if  we were able to specify AMI in `CR` as well... ^_^

**Comment by ellistarn** [comment]
Docker will eventually be deprecated in kubernetes.
> Currently we use EKS 1.21 and we don't want to use containerd as runtime by default.

Can you explain this?

**Comment by Noksa** [comment]
>     Can you explain this?

I mean we use docker as runtime until 1.22 EKS. And there is no option to specify to use `docker` as runtime with default launch template in Karpenter

**Comment by ellistarn** [comment]
Given the deprecation path for the docker runtime and the fact that karpenter is new, we chose to not implement support for this, opting for best practices instead. By adopting the docker runtime, this would be a feature we would eventually need to deprecate.

**Comment by Noksa** [comment]
Okay, thanks
