### ISSUE TITLE
Provisioner API - limits are missing in the docs

### ISSUE THREAD

**Issue by tsahiduek** [aws/karpenter#1003]
Limits are described in [getting started guide](https://karpenter.sh/docs/getting-started/#provisioner), but not exists in [Provisioner APIs](https://karpenter.sh/docs/provisioner/)
It would be great to understand what options a user can configure on Limits and what does that means

**Comment by chrisnegus** [comment]
There is an example of setting limits within a Pod spec in [Running pods](https://karpenter.sh/docs/tasks/running-pods/). I'll add a section on that to the [Provisioner API](https://karpenter.sh/docs/provisioner/) page as well.
/assign @chrisnegus

**Comment by chrisnegus** [comment]
This was documented in [PR #1117](https://github.com/aws/karpenter/pull/1117).
I'm closing this issue.
