### ISSUE TITLE
An ability to specify AMI in Provisioner spec

### ISSUE THREAD

**Issue by Noksa** [aws/karpenter#1008]
**Tell us about your request**

It would be convenient if we were able to specify custom `AMI` in the `Provisioner` spec instead of creating a lot of custom launch templates just to change the AMI in them.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Currently I should create a lot of launch templates and change only `AMI` in them.
It is annoying because `Karpenter` already creates launch templates using taints/labels from the `Provisioner` spec.
Why can't we add `AMI` as well?

Thanks!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by suket22** [comment]
The AMI and the UserData in the EC2 LaunchTemplate are tightly coupled. We'd have to expose both of them in some form in the provisionerSpec to address this.

**Comment by Noksa** [comment]
@suket22 
Definitely, `UserData` is also very important!

**Comment by JohnMops** [comment]
Praying for this aswell. Karpenter is the dream come true to get rid of managing infra in IAC completely.

**Comment by stevehipwell** [comment]
I've opened #1495 which might cover part of the use case for this?

> The AMI and the UserData in the EC2 LaunchTemplate are tightly coupled. We'd have to expose both of them in some form in the provisionerSpec to address this

A MVP solution for this might be to only support custom AMIs where there are based on an existing family and retain the bootstrapping logic of that family?

**Comment by JohnMops** [comment]
Hi @stevehipwell how are you? Is there an ETA on this FR?

**Comment by stevehipwell** [comment]
@JohnMops I think there are some changes due, but I'm not sure if they cover this.

**Comment by ellistarn** [comment]
Support coming in v0.14
