### ISSUE TITLE
AWS CDK Construct for Karpenter

### ISSUE THREAD

**Issue by abierbaum** [aws/karpenter#1038]
**Tell us about your request**

A construct that wraps the installation and setup of Karpenter for use with the AWS CDK along side aws_eks.Cluster.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

The AWS CDK is awesome for installing and configuring EKS Clusters and nodegroups.  There are constructs for setting up a cluster autoscaler as well.  I think it would make it much easier for people to setup Karpenter if there was a CDK construct that would support this for them through the CDK.

**Are you currently working around this issue?**

I am currently patching together my own CDK code to try to get all the pieces of Karpenter into place.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Can you cut this issue over at the CDK repo?

**Comment by gbvanrenswoude** [comment]
@abierbaum this might help:

https://gist.github.com/gbvanrenswoude/b5363d78d39ff32ace9899942110184d

**Comment by abierbaum** [comment]
Looks like a great start.

**Comment by kayh-sportsbet** [comment]
This might help https://github.com/aws-samples/cdk-eks-karpenter

**Comment by kyhau** [comment]
This might help https://github.com/aws-samples/cdk-eks-karpenter
