### ISSUE TITLE
Documentation - overly permissive IAM policy for ssm:GetParameter

### ISSUE THREAD

**Issue by zswanson** [aws/karpenter#1040]
The suggested/sample IAM policy for karpenter is over permissive for ssm:GetParameter, allowing all resources with `"*"`. As far as I can tell this is only used to access the public AWS paramstore item for the EKS optimized image ID. The sample policy should be updated to use a minimal IAM permission for this action.

**Comment by ellistarn** [comment]
Closing as dup of https://github.com/aws/karpenter/issues/507
