### ISSUE TITLE
Testing should include RBAC

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#1041]
**Tell us about your request**
What do you want us to build?

Tests do not cover RBAC profiles, which represents a huge surface for regression. See discussion here: https://github.com/aws/karpenter/pull/1035. This should be included with overall testing improvements.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Done, our E2E tests install Karpenter from the helm release
