### ISSUE TITLE
Allow other opinions on which instance types are filtered

### ISSUE THREAD

**Issue by asimshankar** [aws/karpenter#1053]
**Tell us about your request**

It seems that many instances types (i3* in particular) are disallowed by the opinionated filter at:
https://github.com/aws/karpenter/blob/2ea8ed43fb96fe02e027aac9b135e7cbd839dd68/pkg/cloudprovider/aws/instancetypes.go#L165

Is that something that can be relaxed? Either by including `i3` in the filters above, or by allowing some sort of customization of the filter? (e.g., don't filter out any instance types explicitly specified in the provisioner's `node.kubernetes.io/instance-type` requirements?)

Thanks!

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

We have been running i3 instances (i3.2xlarge, i3en.3xlarge etc.) in our kubernetes cluster successfully, using the locally attached NVMes in our kubernetes jobs/statefulsets. 

However, it seems that the filter alluded to above makes karpenter unsuitable for provisioning such nodes, which makes the just-in-time provisioning experience much less smooth than it could be if karpenter did support them.

**Are you currently working around this issue?**

Working around this for now by using the [kubernetes cluster autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) to initiate scale ups/downs of the node group and/or manually messing with the autoscaling group / managed node group settings.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
We wanted to reduce the scope to known families to avoid any surprises with new instances types that weren't compatible on release. I want to get @bwagner5's go ahead on this, but I'm supportive of allowing the i3 prefix.

**Comment by suket22** [comment]
I like the idea of ignoring the instanceType filtering if there's an explicit ask to use a particular type via `node.kubernetes.io/instance-type`. 

The only issue I see is that for new instanceTypes, we may not choose the right AMI to go with it. For example, g5g's are ARM + GPU and there's no EKS-optimized AMI to use with that. Similar issues [with g5s too](https://aws.amazon.com/ec2/instance-types/g5/). So maybe we make the check a little more stringent where if it's an instanceType unknown to Karpenter, tell us what AMI to use and only then does Karpenter accept it (i.e you have to use launch templates until we inline more launch template fields like the AMI).

**Comment by bwagner5** [comment]
Apologies, I missed this issue!  I think allow i3's are fine in the hardcoded filters. I also agree that if the user specifies an instance type in the provisioner we shouldn't filter it out.
