### ISSUE TITLE
public doc correction

### ISSUE THREAD

**Issue by StrongNitPicker** [aws/karpenter#1066]
some parts in public doc say like
- provision Pod
- schedule Node
need to replace with
- provision Node
- schedule Pod

**Comment by ellistarn** [comment]
Hey @StrongNitPicker , thanks for the report. Can you provide some references to what you mean or perhaps a PR? The docs are here: https://github.com/aws/karpenter/tree/main/website/content/en/docs.

**Comment by bwagner5** [comment]
https://github.com/aws/karpenter/pull/1094 this PR took care of this. Let us know if there are other places where it is incorrect and we'll keep an eye on this wording as well. Thanks!
