### ISSUE TITLE
Limit number of nodes that can be scheduled simultanioulsly

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [aws/karpenter#1077]
**Tell us about your request**
I would like to set the max number of nodes that can run simultaniously using karpenter.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
With cluster autoscaler, you can define a max number of nodes, as it is based on AWS ASG. I would like to put contraints on how many nodes are scheduled by karpenter.

**Are you currently working around this issue?**
Currently I am using cluster autoscaler, but karpenter is a great enhancement to manage unscheduled pods.

**Comment by ellistarn** [comment]
Have you seen https://github.com/aws/karpenter/issues/1003

**Comment by marcportabellaclotet-mt** [comment]
Maybe I am missing some part of the #1003 , but I can't find how to limit the max number of nodes that can be provisioned via karpenter.
Let's say that I have a deployment with multiple replicas with anti-affinity rules to avoid node sharing. If by accident, I put 100 replicas, karpenter will start 100 eks workers. I would like to have a mechanism to limit that. Is this possible using some kind of limits?

**Comment by marcportabellaclotet-mt** [comment]
I think that I misunderstood the limits configuration in #1003. If I understand it well now, this means, that if you set : 
```
  limits:
    resources:
      cpu: 1000
```
It will only allow to start new nodes until capacity sum is not higher that 1 vcpu.

Thanks for the information. Great project!!
