### ISSUE TITLE
Add launchTemplateVersion to AWS Provider and default to $Latest

### ISSUE THREAD

**Issue by suket22** [aws/karpenter#1089]
**Tell us about your request**
Add ability to specify version of the EC2 launch template that should be used with Karpenter. Should support a number or `$Default` or `$Latest`. It should default to `$Latest` if no version is specified. It currently defaults to `$Default`. 

Maybe something like - 
```
spec:
  provider:
    launchTemplate: 
       name: myLaunchTemplate
       version: 24
```

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Karpenter always uses the [`$Default`](https://github.com/aws/karpenter/blob/main/pkg/cloudprovider/aws/instance.go#L165) version of the EC2 launch template being used with the AWS provider. 

This doesn't work great with IaC tools like CloudFormation because you cannot update $Default with that.  From [CFn docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html) - 
```
The default version of a launch template cannot be specified in AWS CloudFormation. The default version can be set in the Amazon EC2 Console or by using the modify-launch-template AWS CLI command.
```

**Are you currently working around this issue?**
After creating and updating the LaunchTemplate in CFn, I'd have to reset the $Default version by calling an EC2 API via the CLI or the console.

**Additional context**
N/A

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Just to add more details to this issue:

We previously supported specifying Launch Template version, but ended up removing it. There's a design on it here (Karpenter has changed quite a bit since then, so some of the problems listed in this doc may no longer apply, but wanted to link for context anyways): https://github.com/aws/karpenter/blob/main/designs/aws-launch-templates-options.md

**Comment by ellistarn** [comment]
The key difference is we're using strongly typed cloud providers instead of provider specific labels. In the recommendation (https://github.com/aws/karpenter/blob/main/designs/aws-launch-templates-options.md#recommendation), you can see a proposal to support version :P

**Comment by gbvanrenswoude** [comment]
:rocket:

**Comment by ellistarn** [comment]
Closing since it's not clear anyone is asking to control version. Please reopen if so.
