### ISSUE TITLE
Helm Chart Upgrade Tests

### ISSUE THREAD

**Issue by bwagner5** [aws/karpenter#1093]
**Tell us about your request**

There should be Helm upgrade tests on chart changes to ensure that charts can be cleanly upgraded when we do releases. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

The helm charts are currently not tested very extensively.  For example, in PR #1001 a seemingly innocent change introduced a backwards incompatible change to the chart that would cause chart upgrades to fail on some resources. 

**Are you currently working around this issue?**
Manual testing caught this specific issue.

**Additional context**
Anything else we should know?

N/A

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Completed now as part of the E2E tests
