### ISSUE TITLE
deleting all nodes causes karpenter to be pending forever

### ISSUE THREAD

**Issue by matti** [aws/karpenter#1099]
## Version
**Karpenter**: v0.5.3

**Kubernetes**: v1.0.0
```
kubectl version | grep Server                
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

## Expected Behavior

Deleting all nodes should not stop karpenter from working

## Actual Behavior
Deleting all nodes makes karpenter controller be pending forever and ironically the pods that karpenter got running are running.

## Steps to Reproduce the Problem

0. create test cluster with karpenter eksctl instructions
1. using the test deployment from karpenter docs
2. kubectl scale deployment inflate --replicas 200
3. wait until all running
4. delete all nodes with kubectl delete
5. some "inflate" pods are running, but karpenter pods are stuck

## Resource Specs and Logs

karpenter controller stuck with:
```
0/4 nodes are available: 2 node(s) had taint {karpenter.sh/not-ready: }, that the pod didn't tolerate, 2 node(s) had taint {node.kubernetes.io/unreachable: }, that the pod didn't tolerate.
0/4 nodes are available: 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate, 2 node(s) had taint {karpenter.sh/not-ready: }, that the pod didn't tolerate.
```

**Comment by matti** [comment]
karpenter-controller refuses to shedule on karpenter managed nodes:

```
nodeSelectorTerms:
  - matchExpressions:
    - key: karpenter.sh/provisioner-name
       operator: DoesNotExist
```

If I remove this affinity, karpenter schedules itself on a karpenter managed node and launches new instances.

So what happens is that when I remove the EKS managed node with kubectl delete, then EKS autoscaler does not start a new node to replace the node. If I manually add a new in the EC2 autoscaling group, I'm able to restore everything.

The EKS nodes are not being replaced because they are still "healthy" and "running" from EC2 point of view.

**Comment by matti** [comment]
Could karpenter prevent deletion of a EKS managed node?

**Comment by ellistarn** [comment]
>Could karpenter prevent deletion of a EKS managed node?

This is a great feature request to have in a separate issue. It requires changes to managed nodes, IIUC. @suket22 is a great point of contact for this.

**Comment by ellistarn** [comment]
We have guidance on the website to not run karpenter on karpenter capacity.

**Comment by gotchipete** [comment]
> > Could karpenter prevent deletion of a EKS managed node?
> 
> This is a great feature request to have in a separate issue. It requires changes to managed nodes, IIUC. @suket22 is a great point of contact for this.

I just did this myself.  Was there in fact a feature request made for this?

**Comment by matti** [comment]
no
