### ISSUE TITLE
Document Multiple Provisioner settings

### ISSUE THREAD

**Issue by matti** [aws/karpenter#1101]
**Tell us about your request**
I want some of my nodes to have labels "hello: world" and some "beer: bar" - currently karpenter only allows me to create one kind:Provider so all of my nodes will have all of the labels.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I want some nodes to have different machines than others. Requesting those machines via node labels is handy.

**Are you currently working around this issue?**
none

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by adefrasne** [comment]
Hi,
> currently karpenter only allows me to create one kind:Provider so all of my nodes will have all of the labels.

No, I have 3 Providers on a cluster with different requirements and labels.
You can create as much Providers as needed.

**Comment by matti** [comment]
ok, this wasnt clear from the docs

**Comment by ellistarn** [comment]
@geoffcline can you take a pass at the docs and make sure this is covered?

**Comment by geoffcline** [comment]
👀 sure

**Comment by chrisnegus** [comment]
The ability to create multiple provisioners is covered in the [FAQs](https://karpenter.sh/v0.6.3/faq/#can-i-create-multiple-team-based-provisioners-on-a-cluster).
Please reopen this issue if you think it belongs in other places in the docs.
