### ISSUE TITLE
Alpha/Beta/GA release channels

### ISSUE THREAD

**Issue by Noksa** [aws/karpenter#1112]
I would like to try and test new features before they are released.

Benefits what I see:
* New functionality will be tested by volunteers
* Probably, most bugs/limitations will be found before they are included in a release
* Some of features can be improved from a release to release and sometimes it means there can be breaking changes and so on.

As example it can be implemented like:
* FG in k8s https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
* `stability channels` from here: https://werf.io/installation.html?version=1.2&channel=stable&os=macos&arch=amd64&method=installer#all-changes-in-werf-go-through-all-release-channels
* Or maybe just nightly builds or something like that

**Comment by felix-zhe-huang** [comment]
This is a great feature request. Having nightly builds sounds like a great starting point. @njtran is a great point of contact for this.

**Comment by ellistarn** [comment]
@spring1843 can you link your updates?

**Comment by spring1843** [comment]
https://karpenter.sh/preview/upgrade-guide/#release-types

**Comment by spring1843** [comment]
@Noksa we now have snapshot and nightly releases
