### ISSUE TITLE
multiple securityGroupSelectors

### ISSUE THREAD

**Issue by bwmetcalf** [aws/karpenter#1118]
The documentation for securityGroupSelector seems to imply that multiple criteria are OR'd together:  https://karpenter.sh/docs/aws/provisioning/#securitygroupselector.  Specifically,
```
Select security groups by name, or another tag:

 securityGroupSelector:
   Name: sg-01077157b7cf4f5a8
   MySecurityTag: '' # matches all resources with the tag
```
However, the logs indicate that the criteria are AND'd as we are getting the following error:
```
2022-01-10T20:37:35.302Z	ERROR	controller.provisioning	Could not launch node, launching instances, getting launch template configs, getting launch templates, no security groups exist given constraints	{"commit": "5047f3c", "provisioner": "karpenter-provisioner"}
```
It seems there should be a way to specify a filter that will select multiple security groups.  What is the expected behavior for this?

**Comment by ricardorqr** [comment]
> The documentation for securityGroupSelector seems to imply that multiple criteria are OR'd together: https://karpenter.sh/docs/aws/provisioning/#securitygroupselector. Specifically,
> 
> ```
> Select security groups by name, or another tag:
> 
>  securityGroupSelector:
>    Name: sg-01077157b7cf4f5a8
>    MySecurityTag: '' # matches all resources with the tag
> ```
> 
> However, the logs indicate that the criteria are AND'd as we are getting the following error:
> 
> ```
> 2022-01-10T20:37:35.302Z	ERROR	controller.provisioning	Could not launch node, launching instances, getting launch template configs, getting launch templates, no security groups exist given constraints	{"commit": "5047f3c", "provisioner": "karpenter-provisioner"}
> ```
> 
> It seems there should be a way to specify a filter that will select multiple security groups. What is the expected behavior for this?

Have you fixed this problem?
