### ISSUE TITLE
Attache instance to karpenter autoscaler after migration from cluster autoscaler

### ISSUE THREAD

**Issue by lbvffvbl** [aws/karpenter#1125]
I want to migrate from cluster autoscaler to karpenter on an existing cluster without terminating old instances. I can just detach the instance from ASG, but how to attach it to karpenter autoscaler to downscale it in the future?

**Comment by bwagner5** [comment]
Hey @lbvffvbl !  It should be possible to detach the instances from the ASG and label the nodes w/ `karpenter.sh/provisioner-name: ${YOUR_PROVISIONER_NAME}`.  Karpenter's Node Controller should pick that label up and go through the normal checks for TTL, emptiness, etc. and also install Karpenter's Node Finalizer to support graceful cordon and drains.

I'd be careful to also remove any cluster autoscaler labels or annotations applied to the nodes. 

Keep in mind, I have not tested this migration from CA to Karpenter in the way described above, so definitely try this in a test env first! There may be something I'm overlooking in this migration plan :)

**Comment by adjain131995** [comment]
@lbvffvbl Did you find this solution working?

**Comment by suket22** [comment]
@lbvffvbl thanks for trying it out. Re-open if there's anything else we can help with
