### ISSUE TITLE
Include node logging commands in troubleshooting guide.

### ISSUE THREAD

**Issue by njtran** [aws/karpenter#1128]
**Is an existing page relevant?**
yes

**What karpenter features are relevant?**

**How should the docs be improved?**
We currently have commands to refer to controller and webhook logs, but should also include commands to refer to individual node logs for debugging purposes.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
This has been added.
