### ISSUE TITLE
The securityGroupSelector is not work

### ISSUE THREAD

**Issue by yzhengwei** [aws/karpenter#1130]
k8s cluster version: v1.21
karpenter version: v0.53

In my K8S cluster, I have v0.53 karpenter installed, I have a security group with a tag "name: CBS-Bigdata-u1-prod-nodesecurityGroup", and when I set "securityGroupSelector" in a provider, It doesn't  work. Karpenter's new machine security group is default through the Launch Templates. In the Launch Templates, I didn't set the security group, Why didn't it work? 

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: spark-driver-spot
spec:
  kubeletConfiguration: {}
  limits: {}
  provider:
    apiVersion: extensions.karpenter.sh/v1alpha1
    instanceProfile: cbs-bigdata-ue1-prod-NodeInstanceRole
    kind: AWS
    launchTemplate: cbs-bigdata-ue1-prod-spot-v1
    securityGroupSelector:
      Name: cbs-bigdata-ue1-prod-NodeSecurityGroup
    tags:
      Name: cbs-bigdata-ue1-prod-spark-driver-ondemand
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - m5.2xlarge
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  ttlSecondsAfterEmpty: 30
```

**Comment by ellistarn** [comment]
Security Groups are owned by the launch template. Karpenter's Security Group Selector injects those security groups into the karpenter managed launch template. If you specify a custom launch template, karpenter. 

I agree this is annoying and unintuitive, but it's how the AWS APIs work. I'd love to figure out why you need a custom launch template and if the requirements can be met another way. Custom launch templates in karpenter have a large number of gotchas.

**Comment by ellistarn** [comment]
Feel free to reopen if this doesn't make sense.
