### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by shirwahersi** [aws/karpenter#1131]
**Tell us about your request**
Windows OS support

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have mixed OS workload (Linux,Windows), we would like to managed both Linux/Windows nodes with Karpenter

**Comment by ellistarn** [comment]
This should be straightforward to support as a new value for key `kubernetes.io/os`.

**Comment by shirwahersi** [comment]
Hi all, Is there any plans to support Windows in near future?

**Comment by halovanic** [comment]
I believe @bwagner closed this patch attempt for the understandable difficulties keeping up with other changes around AMI handling in Karpenter.
Having gone back over the patches to test on my EKS cluster with post-0.15, we could aim for very basic support that gets Windows working, just not as its own first-class AMI Family:

1. Support vpc.amazonaws.com/PrivateIPv4Address resources that are needed for Windows-scheduled pods
2. Remove or replace a hardcoded requirement getting added in the instance type calculation that forbids non-Linux OSs

This does require the user to define a launch template in the Windows provisioner, but this is the same requirement Windows EKS users already had with [Self-Managed node groups](https://docs.aws.amazon.com/eks/latest/userguide/launch-windows-workers.html).  I also think a Windows provisioner probably should define the system reserved memory and restrict instance types more explicitly, but the effort is still quite minimal.

This has worked out quite well in my admittedly limited tests: without even really understanding anything specific about Windows, Karpenter seems to have done a more effective job of getting all of my large workloads scheduled.

Is there interest in pursuing these more limited changes?  I can submit reworked patches if there is.

**Comment by ellistarn** [comment]
> define a launch template in the Windows provisioner

We'll likely be deprecating custom launch template support. Any chance you use can `amiSelector` and `userData` to meet the use case instead?

**Comment by halovanic** [comment]
That would require a new user data format and corresponding AMI Family defined. That was already in the original patches, but seemed to be the part that was running into difficulties with a fast moving Karpenter target state.
What I am proposing are to tackle these more stable prerequisites for Windows separately, then we could come back to dedicated Windows AMI support before the launch template support goes away,

PrivateIPv4Address support was in the previous patches (see function `awsPodPrivateIPv4()` in either) and is needed because [Windows supports fewer pods](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#windows-support-prerequisites) and EKS's webhook adds this calculation to prevent overscheduling.

**Comment by bwagner5** [comment]
This may just work with Custom AMIs (not AMI Families) https://karpenter.sh/v0.16.0/aws/user-data/#custom-amis

You should be able to specify an arbitrary AMI and user-data which will be passed directly to EC2. You could also set the max-pods on the Provisioner spec to deal with the `PrivateIPv4Address` in the mean time at least. https://karpenter.sh/v0.16.0/provisioner/#:~:text=storage%3A%202Gi-,maxPods%3A%2020,-%23%20Resource%20limits%20constrain

**Comment by halovanic** [comment]
I will do some further tests to see if I can switch over to Custom AMIs from the launch templates in my end-to-end tests; I don't see anything that would block it.

Just to clarify, the need for PrivateIPv4Address is not directly one of pod density; it's that the AWS VPC Resource Controller forces this on scheduled pods.  This was the only reference I could actually find on this behavior:
https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/docs/windows/workflow.md

**Comment by marciogmorales** [comment]
Hello Karpenter experts, any update in this topic?

**Comment by pdavagia** [comment]
Checking in to see if there are any updates on this?

**Comment by DorukAkinci** [comment]
We have now managed Windows Node groups support on the EKS service. Is that mean this implementation/feature may also come soon? https://github.com/aws/containers-roadmap/issues/584
