### ISSUE TITLE
Spin up new node before expiring an existing node

### ISSUE THREAD

**Issue by arvindgorur** [aws/karpenter#1133]
**Tell us about your request**
Ability to analyze workload on a node that is going expire and spin up a new one to handle the workload before the old one is expired.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Let's say I have deployed a new application and there's no spare capacity in the cluster. Karpenter will provision a new node and the pods get created on it. Currently all pods for that app are on a single node. Also assume the **ttlSecondsUntilExpired** setting has been enabled. Once this node reaches the specified age, the node will be terminated. Since there's no spare capacity, the pods cannot be scheduled on any other node and the app is unavailable until the new node has been provisioned. It would be great to have the new node available prior to removal of the old one.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Hey @arvidgorur! Thanks for the issue. Karpenter's node deletion logic will actually drain the nodes and gracefully evict all pods scheduled to the node before we delete the node. This should allow the evicted/orphaned pods to schedule to a new node before we delete the node and the pod.

Have you seen behavior different than this?

**Comment by arvindgorur** [comment]
Hey @njtran thanks for getting back! So I'll elaborate a bit.

First, I followed the getting started guide to spin up a v1.20 EKS cluster. I scaled the deployment and Karpenter created a new node and bound the new pods to that node. At this point, there are two worker nodes - one part of the node group where Karpenter is running and one created by Karpenter to host the deployment. Then I updated the provisioner to include the **ttlSecondsUntilExpired** value. Once the node exceeded the expiration, that node was drained and deleted. A new node was provisioned, however it had not yet joined the cluster (I could see it in the ec2 console but not visible to EKS). At this point the deployment pods went into pending state. Eventually the new node joined the cluster and the pods were scheduled successfully. But there was a period of ~1 minute when the pods were pending.

Let me know if you need any further clarification. Thanks!

**Comment by ellistarn** [comment]
Make sure you configure a https://kubernetes.io/docs/concepts/workloads/pods/disruptions/ to ensure pod availability.

**Comment by arvindgorur** [comment]
@ellistarn configuring a PodDisrupitonBudget worked. Thanks for the suggestion and yes, it is good to have as a best practice. Appreciate the quick response. I'm going to close the request.

**Comment by coniferrkishor0874** [comment]
But i have pdb set already even this issue is persist.

**Comment by lllamnyp** [comment]
The solution with PDB does not cover some use-cases. We have a single-pod stateful application running in our cluster. While a brief disruption, needed for the migration of the app from one node to another would be acceptable, a longer disruption, lasting the duration of spinning up a new node leads to alerts firing and paging our engineers. How can we work around such issues?
