### ISSUE TITLE
Cleanup mechanism once a cluster is deleted

### ISSUE THREAD

**Issue by youngjeong46** [aws/karpenter#1134]
## Version

**Karpenter**: v0.3.5

**Kubernetes**: v1.20

## Expected Behavior

I created an EKS cluster with an existing VPC (3 Public, 3 Private subnet) - both created using CDK, and then deployed Karpenter. Karpenter scaled correctly with a provisioner when I deployed a sample php server and scaled to 20 pods (creating 2 new nodes). Upon resource deletion, one of the nodes shut down but the other remained. 

When I deleted the cluster, I expected the remaining node to shut down (and the other node from a nodegroup as expected). But  while the cluster deletion was successful, the subsequent VPC stack deletion failed due to the 1 node from Karpenter remaining despite the cluster deletion.

(As a side note, Launch Template also remained but that is addressed in another issue; I just ended up deleting it manually).

## Actual Behavior

Cluster deletion should remove all nodes provisioned by Karpenter

## Steps to Reproduce the Problem

Create a VPC resource using `ec2.Vpc` using CDK
then Create a cluster using `eks.Cluster` using CDK with default managed nodegroup.
then Follow the instruction from [here](https://karpenter.sh/docs/getting-started/).

After testing Karpenter functionality, `cdk destroy` cluster, then `cdk destroy` VPC stack.

## Resource Specs and Logs

CloudFormation error:

```
Resource handler returned message: "The vpc 'vpc-0e2181e7f888f3a0b' has dependencies and cannot be deleted. (Service: Ec2, Status Code: 400, Request ID: 2d8fe6f7-1636-4fdd-83cd-8cef9568ab15, Extended Request ID: null)" (RequestToken: 49dfba17-1518-beea-8f32-e572352e7ab0, HandlerErrorCode: InvalidRequest)
```

```
The subnet 'subnet-06b6f24c229a99221' has dependencies and cannot be deleted. (Service: AmazonEC2; Status Code: 400; Error Code: DependencyViolation; Request ID: 375a8dd3-0f83-47e0-a40c-2f9d56d5f3ff; Proxy: null)
```

**Comment by njtran** [comment]
Hey @youngjeong46! Thanks for cutting this issue.

If I understand correctly, `cdk destroy` is deleting the cluster stack without waiting for all nodes to finish terminating. Since Karpenter nodes aren't modeled in infrastructure as code, if the node with the Karpenter controller is terminated, any leftover unterminated Karpenter nodes will still have its finalizer and will be unable to be terminated.

This is a known limitation of in-cluster controllers (e.g.: LoadBalancerController), who do not have the opportunity to clean up if the cluster is deleted. Once you terminate the instances, you should be able to delete the VPC as well. I'll cut a PR to include these commands in the troubleshooting guide.

**Comment by youngjeong46** [comment]
@njtran Thanks for your response. Currently the way Karpenter is deployed on our cluster is using cluster.addHelmChart within the cluster stack. It would be great to see Karpenter nodes terminated when Karpenter itself is deleted.

**Comment by olemarkus** [comment]
I am not sure it is a good idea to terminate all karpenter nodes just because one reinstalls the helm chart. I think it falls on the cluster manager to clean up such instances (e.g terminating the instances, which would then lead to pods running there being scheduled on ASG-managed instances).

**Comment by alekc** [comment]
The "cleanest" way to deal with it would probably be providing in the docs one possible lambda which will terminate related nodes on cluster termination. 

But such implementation would be very provider specific (for now we have aws only but what about the feature).

**Comment by johngmyers** [comment]
In the kOps case, kOps has a component that runs upon cluster deletion that lists and deletes a particular set of AWS resources tagged as being owned by the cluster. I wonder if something like that should be turned into a standalone utility.

**Comment by ellistarn** [comment]
I'm not sure if there's much can we do from within the Karpenter project. This is a good feature request for EKS, KOPs, and other kubernetes installers.
