### ISSUE TITLE
amiIdList parameter not documented

### ISSUE THREAD

**Issue by bwmetcalf** [aws/karpenter#1138]
If we use a launch template that doesn't have an AMI defined, we get the following error:
```
2022-01-12T21:27:00.145Z	ERROR	controller.provisioning	Could not launch node, launching instances, creating fleet InvalidParameterValue: Parameter 'amiIdList' cannot be empty.
```
However, I can't find this parameter documented anywhere so I'm not sure how to define it in the provisioner helm chart.

**Comment by suket22** [comment]
What were the contents of your launch template? As called out [by our docs](https://karpenter.sh/docs/aws/launch-templates/), if you're providing your own launch template to Karpenter, it must include the AMI in it.

**Comment by bwmetcalf** [comment]
Yes, the ami field is empty in the launch template.  After looking at the doc you provided again, I see that the ami must be included in the template.  I'll close this issue.

**Comment by dectl** [comment]
Having this same issue. Does Karpenter, by default, pick up the latest version of a launch template? If not, how can the version be specified?
