### ISSUE TITLE
Leftover Network Interfaces after scaling down

### ISSUE THREAD

**Issue by mbevc1** [aws/karpenter#1148]
## Version

**Karpenter**: v0.5.4

**Kubernetes**: v1.21

## Expected Behavior

Scale up and down and Karpenter provisions and cleans up resources correctly. 

## Actual Behavior

When scaling down there are some Network Interfaces left unattached from removed Pods/Nodes.

## Steps to Reproduce the Problem

Deploy Karpenter and demo inflate Deployment. Scale it up and then down to 0. Not always there seems to be leftover Network Interfaces unattached after scaling down.

## Resource Specs and Logs

n/a

**Comment by ellistarn** [comment]
Hmm -- this looks like it might be an AWS VPC CNI bug. Can you file an issue over there: https://github.com/aws/amazon-vpc-cni-k8s

**Comment by suket22** [comment]
@mbevc - were you able to file an issue against the VPC CNI? The CNI is responsible for attaching, detaching and deleting ENIs on worker nodes I'm going to resolve this unless there's something else we can help with

**Comment by mbevc1** [comment]
Sorry, just opened the issue upstream as well: https://github.com/aws/amazon-vpc-cni-k8s/issues/1825

**Comment by ellistarn** [comment]
Thanks for following up. Feel free to reopen if you identify anything remaining in karpenter.
