### ISSUE TITLE
Provisioning Docs - link to Running pods is 404

### ISSUE THREAD

**Issue by aizumoff** [aws/karpenter#1149]
https://karpenter.sh/docs/tasks/provisioning-nodes/ in the text "Refer to Running pods to see how the same features are used in Pod specs to determine where pods run." Running pods -> https://karpenter.sh/docs/tasks/running-pods is not existing (404 error). 

https://karpenter.sh/docs/concepts/ -> "For more on how, as a developer, you can add constraints to your pod deployment, see Running pods for details." same incorrect link.

**Comment by ellistarn** [comment]
Nice catch! I just broke this -- let me fix it.

**Comment by ellistarn** [comment]
https://github.com/aws/karpenter/pull/1150
