### ISSUE TITLE
feat request: Add provisioned nodes to target group

### ISSUE THREAD

**Issue by RafPe** [aws/karpenter#1153]
**Tell us about your request**
Would be great to have ability to specify target group for AWS provisioner for nodes i.e. via annotations

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Trying to build completely automated/auto-scaling solution where from commit your IaC into running cluster there are no intermediary steps to be taken. 

**Are you currently working around this issue?**
Trying to implement a form of a node-init daemonset which would register a node in a target group., 

**Additional context**
--

**Attachments**
--

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
By target group, I'm assuming you mean load balancer target group? Have you looked at the load balancer controller (https://github.com/kubernetes-sigs/aws-load-balancer-controller)? This may be an easy path forward.

**Comment by RafPe** [comment]
@ellistarn hey - yes thats what I meant. But I wanted to avoid extra frameworks running on k8s cluster.  Also LB is part of platform IaC and should ( in my case ) be not created from k8s cluster.

Hence the idea was that karpenter could be a perfect solution to have zerto-touch-k8s-cluster running :)

**Comment by ellistarn** [comment]
I'd think of karpenter and loadbalancer controller as core k8s-on-aws controllers. IAC is a bit tricky with dynamic systems. Most commonly we see the static bits being IAC (including karpenter and lb controller install), and then the dynamic bits flow from there without IAC. 

I'm a bit pessimistic about taking on the complexity of integrating with load balancers directly. Karpenter aims to integrate as natively as possible with Kubernetes resources, and only interact with AWS abstractions where necessary. This helps maintain neutrality and separation of concerns between different systems.

**Comment by ellistarn** [comment]
Further, there are decent arguments that you shouldn't be load balancing directly to nodes using target registration. This can cause inefficient traffic patterns if pods are not equally spread across those nodes.

**Comment by RafPe** [comment]
@ellistarn So this is where it becomes a little bit subjective as from where I look at it I provision platform which is controlled by Terraform and enable the application layers to take over from a ready solution. And in that picture the load balancer controller does not really make a fit ( for me ) 

Further to that - I was not aiming to load balance directly to pods running on k8s various services but to dynamically build nodes which run ingress controller on specific ports. In this case scenario was client->nlb ( with ssl passthrough) -> nginx ingress -> target service. 

At the moment I am using cluster where I have dedicated nodes for ingress ( registering in target groups ) and one node for karpenter which spins up the remaining pieces of puzzle. 

But idea was to have option for provisioner to add a property or annotation whiich would add provisoned node into a target group.

**Comment by ellistarn** [comment]
What about a daemonset that registers the node on startup? I think it's unlikely we will implement this in karpenter itself due to the previously mentioned concerns.

**Comment by RafPe** [comment]
> What about a daemonset that registers the node on startup? I think it's unlikely we will implement this in karpenter itself due to the previously mentioned concerns.

Yep - I can do that. I have added instance-id into labels and will have an init-node code. 

Thanks!

**Comment by brankom-daon** [comment]
Hi @RafPe can you give details what you've done to solve your issue? I have similar situation and it would be great if you can help. Thanks!

**Comment by RafPe** [comment]
@brankom-daon I am crafting the setup still a little bit. Decided to use a form of a self-created mini operator to respond to the events of node-created/decomissioned, which is then connected to labels regoisters/deregisters targets. 

Its not yet in state to be shared - but if you are interested I could work the code to be reusable :)

**Comment by brankom-daon** [comment]
Hi @RafPe that would be awesome, thanks!

**Comment by staizen-stephen** [comment]
Hi. Just to add another contribution on this topic as this is almost a philosophical discussion and it comes up a lot in Kuberenetes.

As the requester mentioned, the ALB/NLB to node port to ingress controller is a common pattern, certainly for a subset of nodes. This causing some traffic balancing issues (and some security concerns on the ingress pod) is equally true.

From my own perspective and experience, our environments are much larger than just Kubernetes. We have Lambdas, multiple VPCs, other systems provided by SaaS providers or in other clouds, or simply not hosted in Kubernetes for a plethora of reasons (security, tenancy, isolation, performance, ownership, geography, and so on).

For example, sometimes I am integrating Lambda, CloudFront, Cognito, ALBs AND Kubernetes, and the Kubernetes ecosystem doesn't need to manage all of those pieces but it does need to connect to them. Managing this from the load balancer controller is just not realistic.

So why not use multiple load balancers (internal plus external)? Two main reasons: 1) complexity (two solutions when one is sufficient) and 2) cost. Load balancers have a significant cost in small deployments.

Then there's the security aspect of giving more security rights into the cluster. I'm already looking at deployment of Karpenter outside of the cluster (EKS managed control plane would be better still) as I don't want to expose those AWS permissions to the cluster workloads, even by accident. (Further, AWS EC2 permissions are not as fine grained as some other services).

So if Karpenter doesn't support this, like others I'll have to deploy a separate solution (probably Lambda outside of the cluster) but this complicates the transition from auto scaling groups that have this to Karpenter which doesn't.

Fully understand where you are coming from but hope this adds positively to the understanding of how some of us use Kuberenetes.

Thanks for reading!

**Comment by PLWagner** [comment]
This https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/use_cases/self_managed_lb/ is actually working for my team. We still manage our Load-balancers and Target Groups with Terraform. Adding the `TargetGroupBinding ` object to the good namespace allow the `aws-load-balancer-controller` to register and deregister instances added/removed by Karpenter.
