### ISSUE TITLE
page for cloudformation.yaml is not found

### ISSUE THREAD

**Issue by dhadkara** [aws/karpenter#1168]
Below page https://karpenter.sh/docs/getting-started/cloudformation.yaml is not found. So I cannot run below command in getting started guide
TEMPOUT=$(mktemp)
curl -fsSL https://karpenter.sh/docs/getting-started/cloudformation.yaml > $TEMPOUT \
&& aws cloudformation deploy \
  --stack-name Karpenter-${CLUSTER_NAME} \
  --template-file ${TEMPOUT} \
  --capabilities CAPABILITY_NAMED_IAM \
  --parameter-overrides ClusterName=${CLUSTER_NAME}

**Comment by ellistarn** [comment]
Thanks for calling this out. We'll try to resolve this before the next release.
