### ISSUE TITLE
Potential race signing with cosign

### ISSUE THREAD

**Issue by mattmoor** [aws/karpenter#1173]
## Version
HEAD

## Expected Behavior

Signing should happen by digest

I'd recommend hoisting the `ko publish` invocations that are embedded above this into variables and use them both places.

As a bonus, if you use `ko` at HEAD you will get SBOMs 😁 

## Actual Behavior

https://github.com/aws/karpenter/blob/a0b9ba6fba05b74408c38724352ecee0f34bdb5a/Makefile#L83-L84

**Comment by ellistarn** [comment]
Hoping to get a new one of these ;)
![image](https://user-images.githubusercontent.com/2585992/150026099-302ed5df-c208-4f32-b178-8333fad864e6.png)

https://github.com/aws/karpenter/blob/main/tools/go.mod#L8

**Comment by mattmoor** [comment]
I'll talk to my people 😄

**Comment by ellistarn** [comment]
https://github.com/aws/karpenter/pull/1251
