### ISSUE TITLE
Official documentation for fallback from spot to on-demand configuration.

### ISSUE THREAD

**Issue by Miszcz-AndY** [aws/karpenter#1183]
**What karpenter features are relevant?**
Spot, on-demand.

**How should the docs be improved?**

I know there is no native karpenter solution to fallback to on-demand instances if spot is not available yet and you are working on [that](https://github.com/aws/karpenter/issues/714). **If it's true, that we can configure karpenter in this way** (within fallback to on-demand if spot is not available (no spot capacity / quota is reached / other)) **will be super to see how to do that in the official karpenter information (as a 'fallback to on-demand' section').** 

I can understand that it's not a karpenter feature but rather pod configuration but if you can describe it (e.g. within some example of provisioner configuration and pod configuration (within nodeAffinity / preference section ?)) it can be really helpful.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Miszcz-AndY** [comment]
🤔 I can see documentation is changing dynamically (so cool and tx a lot!) 😄 I can see there is such section now: https://karpenter.sh/v0.5.3/tasks/running-pods/#node-affinity-nodeaffinity and I think it's mostly what I was asking for. 

As there is no information directly about fallback to on-demand I don't close this gentle request and want to ask you to decide if you want to close it (as actual documentation is good enough for spot vs ondemand case) or you want to back to that later and add such direct example.

**Comment by prateekgogia** [comment]
We can revisit this once we have the fallback to OD support available in Karpenter. 
I guess at the moment you found what you were looking for :)
I will close this issue for now :)

**Comment by ellistarn** [comment]
We need to document this more explicitly. If your provisioner supports capacitytype=[spot, on-demand], karpenter will prioritize spot, and launch on demand if every instance type is out of capacity. Leaving this open as a docs issue.

**Comment by bitshop** [comment]
The link above is no longer works, however this link currently has the documentation: https://karpenter.sh/docs/concepts/nodepools/#capacity-type

**Comment by jonathan-innis** [comment]
Thanks @bitshop for helping point anyone who comes here to the right place 🎉
