### ISSUE TITLE
Getting Started with Karpenter on AWS

### ISSUE THREAD

**Issue by flaviosakakibara** [aws/karpenter#1185]
**Issue**: 
When following the tutorial provided in [this](https://karpenter.sh/docs/getting-started/) link the created nodes are presenting a NotReady satus.

**Cause**:
Checking internal IPAM-D logs, I can see the following error

```log
{"level":"error","ts":"2022-01-19T14:52:50.585Z","caller":"ipamd/ipamd.go:444","msg":"Failed to call ec2:DescribeNetworkInterfaces for [eni-0b70601dc9
523f511]: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: f4fab8d0-6cd2-411b-972f-2445b5ebff
3b"}
```

This is happening because the the node role "KarpenterNodeRole" from [this](https://karpenter.sh/docs/getting-started/cloudformation.yaml) template is not adding the AmazonEKS_CNI_Policy policy.

By itself this is not an issue if we inform that IRSA should be configured for the aws-node DaemonSet.

**Possible Fixes**:

1. Add the AmazonEKS_CNI_Policy to the https://karpenter.sh/docs/getting-started/cloudformation.yaml node role;
2. Inform that IRSA is mandatory for the aws-node DaemonSet.

**Comment by prateekgogia** [comment]
Can you please share whats the version on CNI installed? I installed a CNI version `v1.10.1` and didn't see this issue.

**Comment by flaviosakakibara** [comment]
I'm using the **v1.9.3-eksbuild.1** version but, tbh, I don't see any relation between the CNI version and the IRSA configuration (unless that, in the referred version, the component make different API calls, which is not clear in the [Changelog](https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.10.1/CHANGELOG.md)). 

Could you just confirm if you're not using IRSA for it? ("kubectl get sa -n kube-system aws-node -o yaml | grep role-arn")

If you're not, I can run more tests here in my end with the above mentioned version to investigate a little deeper.

**Comment by ellistarn** [comment]
Thanks for reporting. Fixed here https://github.com/aws/karpenter/pull/1190
