### ISSUE TITLE
Weighted policy for capacity type

### ISSUE THREAD

**Issue by abhishiekgowtham** [aws/karpenter#1194]
**Is an existing page relevant?**

When using capacity type spot and on-demand instances, is there somehow i can set weighted policy like only use 80% of on-spot instances and 20% of on-demand? Also, how would karpenter deal with this if i set those constraints at launch template level.

**What karpenter features are relevant?**

**How should the docs be improved?**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Closing as dup of https://github.com/aws/karpenter/issues/331
