### ISSUE TITLE
Provisioner API - Doesn't mention LaunchTemplate

### ISSUE THREAD

**Issue by hawkesnc** [aws/karpenter#1202]
Referencing: https://karpenter.sh/v0.5.5/aws/launch-templates/#define-launchtemplate-for-provisioner

This link shows the option for `launchTemplate` and should be included in the Provisioner API page
https://karpenter.sh/v0.5.5/provisioner/

**Comment by ellistarn** [comment]
This piece of the docs is vendor neutral. You can find AWS Provider specific docs here: https://karpenter.sh/v0.5.5/provisioner/#specprovider

**Comment by hawkesnc** [comment]
Good point! Thanks for explaining! Good to keep it closed.
