### ISSUE TITLE
Does Karpenter provide vertical scale-in?

### ISSUE THREAD

**Issue by pnjihia** [aws/karpenter#1226]
I'm evaluating Karpenter and I wanted to know if there's a way to vertically scale down a large node with few pods. The only scaling actions seem to be triggered by either unschedulable pods or empty nodes.

Scenario: I scheduled **5** pods and the scheduler gave me one `c5d.2xlarge` instance, and that resulted in a **65%** utilization (not bad). I killed **3** pods and utilization dropped as expected to **25%**. I waited for a few hours to see if an optimization process would kick in but .. nothing (over **20** hours). The feature is barely documented, in fact the only reference of it, is in this independent article: https://blog.sivamuthukumar.com/karpenter-scaling-nodes-seamlessly-in-aws-eks

> How does it work?
> 
> 1. Observes the pod resource requests of unscheduled pods
> 2. Direct provision of Just-in-time capacity of the node. (Groupless Node Autoscaling)
> 3. Terminating nodes if outdated
> 4. Reallocating the pods in nodes for better resource utilization **<<<**

Am I missing something? Is there a way to do this, using Karpenter or another solution? TIA

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by suket22** [comment]
@pnjihia Thanks for reaching out. 

We've been tracking this feature request here - https://github.com/aws/karpenter/issues/1091. We've been calling it defragmentation and the idea is as you say to consolidate workloads once worker node node utilization reduces. 

As a workaround until that is impelemented, you could set a node TTL of 1 day. This would lead to Karpenter re-packing your pods every day and get better utilization.

I'm going to close this as a duplicate.

**Comment by pnjihia** [comment]
Thanks @suket22 .. I was missing the keywords.
