### ISSUE TITLE
Windows Support 

### ISSUE THREAD

**Issue by awsrjimenez** [aws/karpenter#1236]
What do you want us to build?

Karpenter to support windows for both nodes/pods.

What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

The outcome is for Karpenter to support windows autoscaling.

How are you currently solving this problem?

defaulting to traditional auto scaler.

Anything else we should know?

**Comment by akestner** [comment]
Resolving in favor of #1131. Can you please 👍 that issue?
