### ISSUE TITLE
Pods with SG for pods are slow in ContainerCreating when a new node is deployed

### ISSUE THREAD

**Issue by tomerpeer63** [aws/karpenter#1252]
## Version
Karpenter Version: v0.5.4
Kubernetes: v1.21

## Expected Behavior
When trying to scale new pods that has Security groups for pods, and a new node is created in Karpenter, the pod will get attached to the new node and will be deployed successfully

## Actual Behavior
The new pods get attached to the new node, but they are stuck in ContainerCreating even after the node is ready for use. Only when the node is ready, and I delete/create the pods manually, the pods are able to run. This happens only with pods that use Security groups for pods.
If a node is already ready when new pods needs to deploy, this doesn't happen. Only when a node is coming up, and a pod is attached to it, the problem gets reproduced
I think this happens because Karpenter doesn't honer pod's schedule restrictions. Karpenter bind pod that requires vpc.amazonaws.com/pod-eni resource to node without vpc.amazonaws.com/pod-eni resource. However, the VPCResourceController will ignore such pod bind event since the node is not been managed yet (https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/v1.1.0/controllers/core/pod_controller.go#L100).

## Steps to Reproduce the Problem
Use Karpenter with and have a deployment with SG for pods (VPC CNI), and try to deploy a new provisioner with new pods.

## Resource Specs and Logs
2022-01-23T09:40:50, pod default/krakend-deployment-7bd59cd948-zzzrl was created, vpc-resource-controller's webhook modified it to have schedule restriction vpc.amazonaws.com/pod-eni: 1
2022-01-23T09:40:53, node ip-xxx.eu-central-1.compute.internal was created by karpenter ahead of time(before EC2 instance is been initialized)
2022-01-23T09:40:53: karpenter binds pod default/krakend-deployment-7bd59cd948-zzzrl to node ip-xxx.eu-central-1.compute.internal. (even when the node haven't advertised to have the vpc.amazonaws.com/pod-eni resource yet, and vpc-resource-controller will ignore this pod update since node is not managed by it yet)
2022-01-23T09:43:44, node ip-xxx.eu-central-1.compute.internal was attached trunk-ENI and patched by vpc-resource-controller to have vpc.amazonaws.com/pod-eni resources.
2022-01-23T10:04:39, pod default/krakend-deployment-7bd59cd948-zzzrl was deleted by replication-controller(deletionTimestamp set, but pod object isn't deleted)
2022-01-23T10:04:40, pod default/krakend-deployment-7bd59cd948-zzzrl was modified to have branch-ENI annotation after branchENI attached to node.

**Comment by felix-zhe-huang** [comment]
I can recreate the problem. Looking for more details about the cause.

**Comment by felix-zhe-huang** [comment]
So in my environment it took about 2 minutes for the pod to get to running. Node is ready after 70 seconds. So the pod was stuck in the `ContainerCreating` state for about 1 minutes and 50 seconds. Most of the time is just waiting for the new eni to be created
![Screen Shot 2022-02-01 at 3 31 19 PM](https://user-images.githubusercontent.com/92051185/152046780-1608ea84-5fcd-40bf-85fd-8d9cba438ebb.png)
.

**Comment by felix-zhe-huang** [comment]
IIUC, the k8s scheduler and karpenter are not aware of the pod security group concept. However, the scheduling decision is correct and it is a matter of time for the node and the extra ENI to be ready for serving the new pods.

**Comment by ellistarn** [comment]
Further, it's undesirable to flood the system with errors in the success case. At worst, those events can clog up etcd and slow the cluster down at scale. At best, it may trigger false alarms.

**Comment by felix-zhe-huang** [comment]
Apparently my above example is a lucky outliner that doesn't show how long the pods will be stuck in the `ContainerCreating` state. The VPC resource controller resync all pods [every 30 minutes ](https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/145a1543ab797f2e1fc138c149a75d74ae6c026e/main.go#L63), and pods bound before the ENI is up and running will be recovered at the resync event. So in the worst case scenario pods will get stuck for 30 minutes.

Ideally the VPC resource controller should perform a resync when the node becomes ready. We will need the VPC resource controller team's help to implement that logic.

**Comment by tomerpeer63** [comment]
@felix-zhe-huang I did experience what you said, sometimes the pods would just unstuck themselves and ran with irregular timing, of up to 30 minutes. Now it makes sense. I can confirm that whenever a node gets an ENI, pods are able to get into Running state, but as long as it was running before (or apparently after a sync happens)
Is there a way to go around it and bypass this issue?

**Comment by yanshwork** [comment]
Please  keep  this issue  open.

**Comment by ellistarn** [comment]
@dewjam can we add this to Troubleshooting?

**Comment by dewjam** [comment]
Sure thing.  Will work on that today.

**Comment by dewjam** [comment]
Added to troubleshooting guide:  https://karpenter.sh/v0.8.2/troubleshooting/#pods-using-security-groups-for-pods-stuck-in-containercreating-state-for-up-to-30-minutes-before-transitioning-to-running

**Comment by dewjam** [comment]
Great, glad to hear the workaround is working @tomerpeer63 !  

Quick update on our efforts towards a permanent fix.  We were working towards implementing a fix in the aws-vpc-resource-controller (https://github.com/aws/amazon-vpc-resource-controller-k8s/pull/103), but have shifted efforts to looking into removing the "early binding" capability Karpenter uses to assign pods to nodes.  Without early binding, SGP would work as expected.

I'm in the process of validating this assumption by testing in some experimental code.  I'll keep you in the loop.

**Comment by tzneal** [comment]
Closed with https://github.com/aws/karpenter/pull/1856

**Comment by armenr** [comment]
@tzneal - Does this mean that we should remove `    vpc.amazonaws.com/has-trunk-attached: "false"` from the provisioner spec, and instead use

**Comment by tzneal** [comment]
Yes, this should work.

**Comment by armenr** [comment]
Going to wait for the next release before upgrading back to v0.12.x, but good to know about the provisioners!

**Comment by AaronFriel** [comment]
Should this be re-opened as pre-binding was reverted?
- https://github.com/aws/karpenter-provider-aws/pull/1856
