### ISSUE TITLE
Add support for custom resources annotations on helm chart

### ISSUE THREAD

**Issue by oussemos** [aws/karpenter#1263]
**Tell us about your request**
Add support for custom annotations when installing the helm chart

With something like

` --set controllerAnnotations`
`--set serviceAnnotations`

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
N/A
**Are you currently working around this issue?**
N/A
**Additional context**
N/A

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by felix-zhe-huang** [comment]
We have a coming PR #1145 that refactors the helm chart and provide a mechanism to support annotations.
