### ISSUE TITLE
Reimplement Spread/Antiaffinity to not use kubernetes.io/hostname label

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#1264]
**Tell us about your request**

The current implementation injects a hostname label to force pod separation. However, the hostname is not known until the node is created. This means we need to then strip the label to avoid creating the node with an opinionated hostname. All this mutation results in tricky race conditions with parallel code that assumes immutability (https://github.com/aws/karpenter/issues/1200). 

It may be an efficient use of time to rewrite at the same time as fixing https://github.com/aws/karpenter/issues/975

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Completed with pod affinity/anti-affinity PR https://github.com/aws/karpenter/pull/1626
