### ISSUE TITLE
kops Karpenter Documentation Change

### ISSUE THREAD

**Issue by ecda909** [aws/karpenter#1265]
**Is an existing page relevant?**
https://karpenter.sh/preview/getting-started-with-kops/#create-a-cluster

**What karpenter features are relevant?**
kops integration

**How should the docs be improved?**
The docs should have the section about "New Cluster" implementation of Karpenter removed because Karpenter does not have a flag for --instance-manager.  

Documentation Reference: 
https://karpenter.sh/preview/getting-started-with-kops/#create-a-cluster

Error Log:
Error: unknown flag: --instance-manager

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by olemarkus** [comment]
I assume you meant that kOps does not have the flag `--instance-manager`. 
The flag is not visible unless you enable the Karpenter feature flag. Also make sure that your kops version is new enough. There has been a lot of fixes in karpenter/kops lately, so recommend using a snapshot version if you can.

**Comment by ellistarn** [comment]
IIUC from @olemarkus's comment we can close. Feel free to reopen if I'm wrong.

**Comment by ecda909** [comment]
The feature flag was enabled by exporting the env variable KOPS_FEATURE_FLAGS=Karpenter. I set the flag, ran the following...
`kops create cluster --name <DNS> --cloud aws --networking=amazonvpc --zones=us-east-1a --master-count=1 --yes --state=s3://<endpoint> --instance-manager=karpenter`
and then the following error was returned...
`Error: unknown flag: --instance-manager`
Am I missing a step?

**Comment by olemarkus** [comment]
You need 1.24. I recommend using the CI version as it contains a host of fixes for karpenter: https://kops.sigs.k8s.io/contributing/test_versions/

**Comment by ecda909** [comment]
So, this deploys on version1.24, but I can't interface with the cluster via kubectl? I haven't got any warnings or errors on my output logs and I've exported the kubeconfig like so...
`./kops export kubeconfig <dns_name>.com`
error I got back when running a 
`kubectl get no`

Unable to connect to the server: dial tcp <ip_addr>: i/o timeout

and when running an update to set configs I get...
Error: error listing nodes in cluster: Get "https://api.<dns_name>.com/api/v1/nodes": dial tcp <ip_addr>:443: i/o timeout

Am I missing something in the configuration steps, I followed the instructions on the link you sent and everything seems to be deployed from my AWS console, just unable to run the kubectl CLI commands against the master node

**Comment by olemarkus** [comment]
You can check the logs of the unit called `kops-configuration`.

Feel free to drop by slack if you need help with this.

**Comment by ecda909** [comment]
I think I may have just gotten it back up. I think it just took a while to propagate on the Route53 side of things. I will still join the Slack though just in case if I have anymore issues later down the road.
