### ISSUE TITLE
Karpenter dose not always make sure to run right size nodes on the cluster 

### ISSUE THREAD

**Issue by Anto450** [aws/karpenter#1266]
## Version

**Karpenter**: v0.6.0

**Kubernetes**: v1.18.20

## Actual Behavior
When i scale up my deployment to 30 replicas karpenter brings up the right size nodes for the requested workload lets say "c5a.8xlarge" and the cpu resources utilised on that node is  "27110m (85%)" fine this has worked as expected but when i scale back the deployment replicas to 3 the cpu resources utilised on that node is now only "5110m (16%)" but karpenter continuous to  run those 3 pods on the same bigger instance "c5a.8xlarge" which is now over provisioned, resource is wasted, and results in high cost.
Karpenter sticks to the same instance type at the time of creation and does not recalculate the resource utilisation and normalise the instance type back to the expected size.
ttlSecondsUntilExpired cannot be configured here as if we set it to 30 days then the bigger node type will be running for 30 day which is also waste of cost and resource 

## Expected Behavior
As soon as the deployment replicas is reduced to 3 from 30 karpenter should create a new right size node to allocate those 3 pods and then delete the bigger instance "c5a.8xlarge" which is over provisioned. This way we can make sure karpenter is provisioning the right size nodes at all time in the cluster 

## Steps to Reproduce the Problem
1. Increases the inflate deployment from 0 - 30 replicas 
2. Right size node eg "c5a.8xlarge" will be created by karpenter and the pods get scheduled and running
3. Now scale down the deployment to 3 replicas you will see the cluster is still running on the same bigger instance c5a.8xlarge even after scaling down to 3 pods, which will lead to major resource wastage

**Comment by ellistarn** [comment]
Hey @Anto450, thanks for writing this up. Do you mind porting these requirements over to https://github.com/aws/karpenter/issues/1091. This is where we're tracking the consolidation effort, which is the exact problem you mention.
