### ISSUE TITLE
Document Metrics exposed by Karpenter

### ISSUE THREAD

**Issue by nonoswz** [aws/karpenter#1275]
**Is an existing page relevant?**
The only information I could find in the documentation about the metrics is to do a request on /metrics endpoint, the documentation is [here](https://karpenter.sh/v0.6.0/development-guide/#debugging-metrics)

**What karpenter features are relevant?**
All Metrics provided by Karpenter, below are a list of PR about metrics (the list might not be exhaustive):
#677 
#680 
#687 
#701 
#734 
#744 
#957 

**How should the docs be improved?**
It would be great if the documentation includes the different metrics that Karpenter exposes, a nice example of documentation is [kube-state-metrics one](https://github.com/kubernetes/kube-state-metrics/tree/master/docs) where they have a documentation file per type of metric. Thanks!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by felix-zhe-huang** [comment]
While we are working on documenting how to access the metrics, you can also take a look at the Karpenter Grafana dashboard that visualizes those metrics as a reference.
https://karpenter.sh/v0.6.0/getting-started/#create-grafana-dashboards-optional
Following the instructions you will deploy a Prometheus + Grafana cluster with predefined Karpenter dashboards onboarded already. They are great examples on how to access those metrics.

**Comment by nonoswz** [comment]
Thanks! The links that points to the Grafana dashboard in the code is actually broken (it points here https://github.com/aws/karpenter/tree/main/grafana-dashboards). I could find some dashboards there https://github.com/aws/karpenter/tree/main/website/content/en/preview/getting-started, I'll have a look at them ! Thanks.

**Comment by felix-zhe-huang** [comment]
Ah, thank you very much!
In fact that step is no longer needed because the dashboard will be onboarded automatically.
but you found the correct dashboard JSON files.

I will update the document about this.

**Comment by chrisnegus** [comment]
This issue appears to be resolved by [PR #1304](https://github.com/aws/karpenter/pull/1304). 
If there is some aspect of this issue that was missed, feel free to reopen this issue.

**Comment by tzneal** [comment]
The metrics are now documented on karpenter.sh, you can see the preview docs at https://karpenter.sh/preview/tasks/metrics/ and they'll be on the main site after the next release.

**Comment by cristiangstefan** [comment]
> The metrics are now documented on karpenter.sh, you can see the preview docs at https://karpenter.sh/preview/tasks/metrics/ and they'll be on the main site after the next release.

All good and fine, but what is the endpoint? On what port do we access it? can we filter for each metric that is there? Also can i scrape the metrics with Datadog? Is it necessary with Prometheus?
