### ISSUE TITLE
Add allowed-unsafe-sysctls kubelet flag

### ISSUE THREAD

**Issue by rkul** [aws/karpenter#1279]
**Tell us about your request**
It would be great to have an opportunity to allow unsafe sysctls for kubelet

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'm trying to fine tune some of sysctl parameters to improve performance of the node. Some of sysctls considered to be unsafe even if they are namespaced, so they need to be explicitly allowed by cluster admin (or set on the node level). For example: 
```
apiVersion: v1
kind: Pod
metadata:
  name: sysctl-example
spec:
  securityContext:
    sysctls:
        - name: net.unix.max_dgram_qlen
          value: "512"
        - name: net.core.wmem_max
          value: "4194304"
```
In that case pod get scheduled but can not be launched:
```
forbidden sysctl: "net.unix.max_dgram_qlen" not whitelisted

```
To enable unsafe sysctl it needs to add extra parameter to the kubelet:
```
kubelet --allowed-unsafe-sysctls 'net.unix.max_dgram_qlen,net.core.wmem_max'
```
or 
```
kubelet --allowed-unsafe-sysctls 'net.*'
```
So there is no opportunity to configure allowed sysctls for the nodes currently without using custom Launch Templates

**Are you currently working around this issue?**
I'm setting required sysctls on node level via privileged init container. The same result can be achieved via privileged daemonset on all the nodes

**Additional context**
Requirements of sysctl tuning came from congestion in Unix socket, when we started to send metrics to Datadog DogStatsd container https://docs.datadoghq.com/developers/dogstatsd/high_throughput/?#over-uds-unix-domain-socket

**Attachments**
General info: https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/
Details about quoting of this parameter for `bootstrap.sh`: https://github.com/awslabs/amazon-eks-ami/issues/184

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by felix-zhe-huang** [comment]
If I understand correctly, we should be able to specify the extra kubectl parameters through the launch template user data.
https://karpenter.sh/v0.6.1/aws/launch-templates/#user-data---autoconfigure

I will try it and see if that is doable.

**Comment by felix-zhe-huang** [comment]
> So there is no opportunity to configure allowed sysctls for the nodes currently without using custom Launch Templates

So if I understand the request, we are talking about enabling unsafe sysctls  without custom launch template?

**Comment by rkul** [comment]
>So if I understand the request, we are talking about enabling unsafe sysctls without custom launch template?
Hi @felix-zhe-huang
Sorry for the delayed answer. Yes, we're talking about enabling unsafe sysctls without custom launch template. Like you did for cluster dns. There is already `spec.kubeletConfiguration` section in API, I assume it is appropriate place for setting unsafe sysctls

**Comment by suket22** [comment]
Also, if we were to give you the ability to override just the UserData so you don't need to specify an entire launch template, would that be acceptable? I suppose you already tightly control the UserData when launching worker nodes if you're using EKS.

**Comment by rkul** [comment]
Hello @ellistarn 
Thank you for jumping into this issue.
As for your questions:

>Is this the only blocker that you have to using a custom launch template?

Yes, there is no other way to use `spec.securityContext.sysctls` for "unsafe" sysctls

>Can you provide any blogs/guides/examples of where else this field is useful for other customers?

We faced with congestion in Unix datagram socket when sending metrics to the DogStatsd agent. Datadog  is very popular monitoring service. To fix that issue it needs to increase datagram queue and buffer sizes. I left the link to the doc in the initial comment. Both of sysctls are namespaced, but considered "unsafe", which caused the problem. So there are two solutions:

1. Use privilege container to set sysctls above at node level, which is not exactly the same we want to achive

2. Use custom template to allow the list of "unsafe" sysctls and then use them as supposed by kubernetes specs

Also, tuning of `net.core.somaxconn` and `net.ipv4.tw_reuse` parameters is also common for those, who use Nginx Ingress controller

**Note:** I just noticed that `--allowed-unsafe-sysctls` flag is deprecated:
```
Flag --allowed-unsafe-sysctls has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
```
```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
allowedUnsafeSysctls:
- "net.core.somaxconn"
```

**Comment by rkul** [comment]
Actually,

>Use privilege container to set sysctls above at node level

Is not really a solution, because it needs to enable `hostNetwork: true` to get access to the `net.core.wmem_max` parameter, which potentially is not safe and breaks things. So, it looks like `net.core.wmem/rmem_max` is not namespaced and should be set on the node level in any case (e.g. via privileged DaemonSet)

**Comment by cebernardi** [comment]
we're interested in this feature as well.

Out of curiosity, is `spec.kubeletConfiguration` representing this KubeletConfiguration (https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/)?

**Comment by gazal-k** [comment]
Looks like https://github.com/aws/karpenter/blob/main/website/content/en/preview/AWS/provisioning.md#userdata would let us tweak bottlerocket settings like unsafe sysctl. For AL2, we may need to wait

**Comment by dschaaff** [comment]
This is the only reason I require custom launch templates, at least for production use cases. We have a few unsafe sysctls we need to add to the allow list.

**Comment by bwagner5** [comment]
You can set this via Bottlerocket today: https://karpenter.sh/v0.14.0/aws/user-data/#bottlerocket

You can set this via AL2 by specifying a user-data script in the AWSNodeTemplate that directly updates the kubelet config file: https://karpenter.sh/v0.14.0/aws/user-data/#al2-and-ubuntu

**Comment by dschaaff** [comment]
@bwagner5 If I modify `/etc/kubernetes/kubelet/kubelet-config.json` in the customer userdata portion, this will not be overridden in the karpenter managed portion that executes the bootstrap command? If so that would be enough for me.

**Comment by tehranian** [comment]
@dschaaff -- Sample JSON-injecting `sed` command please?  🙏 
We're trying to do the same thing with `"--allowed-unsafe-sysctls"`.

**Comment by dschaaff** [comment]
@tehranian We use bottlerocket now and it makes it super easy to control those settings.

**Comment by shreelola** [comment]
> @tehranian We use bottlerocket now and it makes it super easy to control those settings.

How are you controlling these settings in bottleRocket ?

**Comment by gazal-k** [comment]
> How are you controlling these settings in bottleRocket ?

You can create a NodeClass like this:

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  ...
  userData: |
    [settings.kubernetes]
    allowed-unsafe-sysctls = ["net.core.somaxconn", "net.ipv4.ip_local_port_range"]
```

References:
- https://karpenter.sh/docs/concepts/nodeclasses/#bottlerocket-2
- https://bottlerocket.dev/en/os/1.20.x/api/settings/kubernetes/#allowed-unsafe-sysctls
