### ISSUE TITLE
Document support for kubernetes,io/os well-known label

### ISSUE THREAD

**Issue by dnutels** [aws/karpenter#1280]
**Is an existing page relevant?**
[0.43 Docs](https://karpenter.sh/v0.4.3/cloud-providers/aws/aws-spec-fields/#operating-system)

**What karpenter features are relevant?**
Support for `kubernetes,io/os`, describes as implemented (and working) here: https://github.com/aws/karpenter/issues/905

**How should the docs be improved?**
Add `kubernetes.io/os` to well-known labels supported for nodeSelector

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by felix-zhe-huang** [comment]
Thank you very much for the suggestion! @geoffcline is a great point of contact for updating the document.

**Comment by chrisnegus** [comment]
Before we removed it from the docs, here is what it said:
```
Operating System 
* key: kubernetes.io/os
* values
    * linux (default)
```
Can we just add bullets for windows and mac?

**Comment by geoffcline** [comment]
We do not support windows/macOS instances at this time. I'm closing this "document issue", if you are interested in alt os support, I encourage you to join a community meeting to share more info :)

**Comment by bwagner5** [comment]
here's the windows support issue: https://github.com/aws/karpenter/issues/1131
