### ISSUE TITLE
Using Karpenter over two clusters in the same AWS account

### ISSUE THREAD

**Issue by Izvi-digibank** [aws/karpenter#1281]
I've been wondering how would Karpenter deal with 2 clusters in the same AWS account.
How should I define the Roles for defaultInstanceProfile and the IRSA role?

Thanks

**Comment by ellistarn** [comment]
It's somewhat up to you and your requirements for sharing/isolation for IAM/networking/etc. 

One way is to simply share the KarpenterControllerRole and KarpenterNodeRole between all clusters that host Karpenter. You could also create individual versions of those roles for each cluster. To reduce permission scope, you could explore tag based roles discussed here: https://github.com/aws/karpenter/issues/507

**Comment by l-rossetti** [comment]
Assuming that IAM roles are correctly set up, when Karpenter is deploied into one cluster, how does it operates on the second one? Is it enough to specify an additional NodePool and an EC2NodeClass discovering subnets/securityGroups of the second cluster?
