### ISSUE TITLE
Error: failed to renew lease 

### ISSUE THREAD

**Issue by Izvi-digibank** [aws/karpenter#1283]
I encountered this message while looking in Karpenter logs:

```
2022-02-06T17:26:05.226Z	ERROR	controller.controller.counter	Reconciler error	{"commit": "2346ed5", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "name": "integration-provisioner", "namespace": "", "error": "patching provisioner, Internal error occurred: failed calling webhook \"validation.webhook.provisioners.karpenter.sh\": Post \"https://karpenter-webhook.karpenter.svc:443/validate-resource?timeout=10s\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"karpenter-webhook.karpenter.svc\")"}
E0206 17:26:20.694975       1 leaderelection.go:361] Failed to update lock: Put "[https://10.100.0.1:443/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election](https://10.100.0.1/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election)": context deadline exceeded
I0206 17:26:20.695030       1 leaderelection.go:278] failed to renew lease karpenter/karpenter-leader-election: timed out waiting for the condition
panic: Unable to start manager, leader election lost

goroutine 1 [running]:
main.main()
github.com/aws/karpenter/cmd/controller/main.go:99 +0xed9
```

Can you guys please explain the cause and the meaning of this Error? 
After I manually deleted the secret (it was recreated automatically of course), this Error did not appear anymore.

**Comment by felix-zhe-huang** [comment]
This is an interesting one. Can you share a little bit more about the steps that you went through before you see this error?
I would like to see if I can recreate it.

**Comment by Izvi-digibank** [comment]
@felix-zhe-huang I am not sure this is the cause but... I am working GitOps-wise using ArgoCD. 
When I deployed Karpenter, ArgoCD did not like the idea of an [empty data in a secret](https://github.com/aws/karpenter/blob/v0.5.6/charts/karpenter/templates/webhook/deployment.yaml#L109). It won't load the whole application if there's an empty secret. 
The situation was that k8s has a secret with data (injected by the webhook) but the helm chart in git had an empty data. ArgoCD is gitOps, hence takes whatever he sees in git. 

So, I copied the data from K8S and pasted in the helm chart so ArgoCD will successfully load Karpenter. 
In case that the webhook would need to inject new values to the secret, the secret in k8s will include these new values together with the old values that I put in the helm chart.

Karpenter worked perfectly but suddenly stopped creating nodes. Then I saw the error mentioned above. 
I deleted the secret, a new one was generated and everything worked fine again.

Can you just explain what `update lock` and `renew lease` are? how often Karpenter renews lease?

**Comment by felix-zhe-huang** [comment]
Karpenter is developed using sigs.k8s.io/controller-runtime. It has a manager that manages all the k8s controllers lifecycles. This manager is designed using active-passive HA pattern. it uses the built-in Kubernetes leader election APIs to create a leader. The `update lock` is when the controller-runtime is calling the k8s leader election API and got a timeout. 
Therefore, the controller-runtime failed to renew the lease for the leader. No leader is declared in this case. Usually this only happens when Karpenter is launched. 
You can find more info here:  https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/leaderelection

**Comment by felix-zhe-huang** [comment]
It looks to me like a problem caused by misconfigured secret after seeing the timeout while calling the k8s API.
Is that secret for k8s api credential?

**Comment by Izvi-digibank** [comment]
Misconfigured secret may be the issue but it's not due to something I did wrong. Or did I?
Adding data to the secret in the helm chart isn't overwriting the secret in k8s..

**Comment by felix-zhe-huang** [comment]
Is it possible that this is also caused by the networking issue as in #1313 ? The error shows that API calls time out.

**Comment by igaskin** [comment]
@felix-zhe-huang #1313 looks like a timeout to sts, while the timeout in the description of this issue is to the kubernetes `leases` api.  I've see the same leases timeout in `v0.13.2`.
