### ISSUE TITLE
CloudProvider Controller Manager Hook for Provider Specific Controllers

### ISSUE THREAD

**Issue by bwagner5** [aws/karpenter#1288]
**Tell us about your request**
What do you want us to build?

CloudProviders should have the ability to hook into the Karpenter controller manager instantiation to run their own controllers. One example is a reconciliation loop within the AWS CloudProvider to query EC2 instances based on a tag. This would enable recovery of leaked instances in certain fault scenarios. Other reconciliation loops within cloud providers could be used for resource discovery. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
How are you currently solving this problem?

Some Async jobs are kicked off on cloudprovider instantiation. This may not be the best practice, but it is working today.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by billrayburn** [comment]
@bwagner5 and @jonathan-innis say this is done now.

**Comment by jonathan-innis** [comment]
Linking the relevant path: https://github.com/aws/karpenter/tree/main/pkg/controllers
