### ISSUE TITLE
[AWS] Attach Spot Pricing Data to Provisioned Nodes

### ISSUE THREAD

**Issue by bwagner5** [aws/karpenter#1289]
**Tell us about your request**
What do you want us to build?

EC2 Spot Pricing data can be easily accessed via an EC2 API within Karpenter. It would be helpful to attach the spot price at the time of provisioning a node so that the user can have more visibility into a cluster's node cost with Karpenter's extreme flexibility. (This came up in a community meeting from @mikesir87 )

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
How are you currently solving this problem?

Looking up and attributing back to launched nodes. 

**Additional context**
Anything else we should know?

https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-spot-price-history.html

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ghostsquad** [comment]
I'm not sure how valuable a spot-price at time of provisioning would be. However, it would be nice to possibly have an exported metric that shows abcost gauge. The controller knows about all nodes deployed, and can query and correlate the spot market price, and perform the sum operation.

**Comment by bwagner5** [comment]
A big driver for attaching it at launch time is understanding why an instance type was launched if it is bigger than the pod it's fitting. I think it would be helpful to show that number from a `kubectl describe nodes <my-spot-node>`.  It would also be possible to show the spot pricing history for the node in an annotation as well. 

I think the metric is also a great idea. I think we'd also only be able to do spot pricing aggregation though since on-demand pricing can be complicated to calculate if you're using savings plans, reserved instances, etc.

**Comment by billrayburn** [comment]
Closing, requirement satisfied by #3614.
