### ISSUE TITLE
Cannot create identity mapping

### ISSUE THREAD

**Issue by robertd** [aws/karpenter#1300]
Hello,

I've been having issues following the guide. Unfortunately, due to nature of my VPC I cannot use `eksctl` for eks cluster creation. Instead I'm using CDK construct (https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks-readme.html) which creates a simple EKS cluster with 1 node.

<img width="566" alt="image" src="https://user-images.githubusercontent.com/31543/153142128-bf98deb4-a29c-4c69-80c8-3e7b7658d721.png">

Any ideas? Thanks in advance.

**Comment by ellistarn** [comment]
Your cluster administrator or a role with access to the cluster needs to give you access for your role. These roles are configured in the aws-auth configmap. By default, the identity that created the cluster always has access.

**Comment by robertd** [comment]
@ellistarn Onto the next issue...

> 2022-02-09T21:38:01.417Z	ERROR	controller.provisioning	Could not launch node, launching instances, getting launch template configs, getting launch templates, no security groups exist given constraints	{"commit": "df57892", "provisioner": "default"}

I have a feeling it's related to `no security groups exist given constraints` as I'm not seeing anywhere in the guide being set and it's a required field. Which security group is this? Of a cluster... or EC2 instance? And where is being set in the guide?

Thanks in advance!

**Comment by robertd** [comment]
P.S. For `subnetSelector` I had to steer away from `karpenter.sh/discovery: clusterName` tag format and stick with older tagging structure `karpenter.sh/discovery/clusterName: '*'` because we're using a shared VPC with other groups within the same account. 

On the other hand... I'm having a hard time figuring out `securityGroupSelector` (`karpenter.sh/discovery: 'clusterName'`). Docs are suggesting that if this is not passed it will try to figure it out ( `If no security groups are explicitly listed, Karpenter discovers them using the tag “kubernetes.io/cluster/MyClusterName”, similar to subnet discovery.`). However... I wasn't able to create a provisioner omitting this or subnet parameter. I get errors.

**Comment by robertd** [comment]
I found out that cluster SG has the following tags... (I believe instruction guide should be updated with correct tag example)

<img width="574" alt="image" src="https://user-images.githubusercontent.com/31543/153299821-b9a521ed-9e7f-4199-ba11-898547a9506c.png">

I've updated `provider` section in my provisioner in manifest in my CDK code....

![image](https://user-images.githubusercontent.com/31543/153299930-680bfc9d-c920-4508-92f2-52eac78d3840.png)

Unfortunately... I'm still getting an error... so I'm still investigating... :(

> 2022-02-09T22:20:23.564Z	ERROR	controller.provisioning	Could not launch node, launching instances, getting launch template configs, getting launch templates, no security groups exist given constraints	{"commit": "df57892", "provisioner": "default"}

**Comment by robertd** [comment]
According to docs... launch template is optional?... or is it?

**Comment by robertd** [comment]
@ellistarn  I've commented out `launchTemplate` portion but I'm still getting this error...

<img width="1629" alt="image" src="https://user-images.githubusercontent.com/31543/153465584-1e01f7ff-e3b1-4089-9a65-17b2a0638a01.png">

**Comment by ellistarn** [comment]
Ah that makes complete sense.

**Comment by robertd** [comment]
@ellistarn

**Comment by robertd** [comment]
My next step is to try LT with bottlerocket AMI :D

**Comment by robertd** [comment]
@ellistarn Thank you so much for all your help!!!

**Comment by ellistarn** [comment]
Glad you sorted it out! It definitely gets a bit confusing with k8s style (level triggered reconciliation) and cfn/cdk style (edge triggered updating)

**Comment by dbaltor** [comment]
>ERROR controller.provisioning Could not launch node, launching instances, getting launch template configs, getting launch templates, no security groups exist given constraints {"commit": "df57892", "provisioner": "default"}

For future reference, I was getting the error above whist trying to install Karpenter `0.30.0` using `aws-ia/eks-blueprints-addons/aws` terraform module `1.7.2`. Managed to fix the problem with following node template configuration:
```
resource "kubectl_manifest" "karpenter_node_template" {
  yaml_body = <<-YAML
    apiVersion: karpenter.k8s.aws/v1alpha1
    kind: AWSNodeTemplate
    metadata:
      name: default
    spec:
      subnetSelector:
        "kubernetes.io/cluster/${module.eks.cluster_name}": "owned"
      securityGroupSelector:
        "kubernetes.io/cluster/${module.eks.cluster_name}": "owned"
      instanceProfile: ${module.karpenter.instance_profile_name}  
      tags:
        "karpenter.sh/discovery": "${module.eks.cluster_name}" 
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}
