### ISSUE TITLE
[Feature Request] Pod Anti-Affinity

### ISSUE THREAD

**Issue by Yitaek** [aws/karpenter#1308]
**Tell us about your request**
Support auto-scaling based on pod anti-affinity

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
A lot of the popular helm charts (e.g. Elasticsearch, Kafka, PostgreSQL) has pod anti-affinity baked in. Currently if I try to deploy one of those helm charts, karpenter does not scale up with the following message:

```
2022-02-09T22:20:06.877Z	DEBUG	controller.selection	Ignoring pod, pod anti-affinity is not supported	{"commit": "df57892", "pod": "default/elasticsearch-master-0"}
2022-02-09T22:20:06.930Z	DEBUG	controller.selection	Ignoring pod, pod anti-affinity is not supported	{"commit": "df57892", "pod": "default/elasticsearch-master-1"}
2022-02-09T22:20:06.965Z	DEBUG	controller.selection	Ignoring pod, pod anti-affinity is not supported	{"commit": "df57892", "pod": "default/elasticsearch-master-2"}
```

Is there a workaround until this feature is supported? 

Also, it would be good to update the docs since it currently mentions: "Evaluating scheduling constraints (resource requests, nodeselectors, **affinities**, tolerations, and topology spread constraints) requested by the pods" . 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by felix-zhe-huang** [comment]
Hi Yitaek, we are definitely working on  pod anti-affinity. There is an existing thread #942 on pod anti-affinity and we should merge the discussion threads together. Please keep an eye on that thread. Closing this one for redundancy. Please reopen it if not redundent.
