### ISSUE TITLE
Support for "Release Channels" or Ability to Specify Custom SSM Parameter Store

### ISSUE THREAD

**Issue by rayterrill** [aws/karpenter#1309]
**Tell us about your request**
It would be really nice if EKS (and EKS Optimized + Bottlerocket) had the concept of "release channels" for AMIs - something like "latest" and "recommended/stable".

Absent this, it would be nice if Karpenter supported the ability to provide a custom SSM parameter store values so we could implement this ourselves - allowing lower envs to pull latest, and after those have been vetted, updating the custom parameter store value to note the vetted version we'd like Karpenter to use.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We want to continue to "outsource" more and more of this nodegroup toil to EKS/Karpenter, but have run into issues historically around newly-released versions of AMIs (specifically Bottlerocket).

**Are you currently working around this issue?**
Pinning versions with launch templates - very manual.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by akestner** [comment]
What kinds of issues have you run into with the latest releases of the EKS Optimized and Bottlerocket AMIs? 

It might be worth cutting a sibling issue to the [aws/containers-roadmap](https://github.com/aws/containers-roadmap/) so that we can track this request across services / projects.

**Comment by rothgar** [comment]
I like this idea because other systems have worked in similar ways (e.g. CoreOS)

Is the main goal is to have production stability? I'm assuming you would want a dev environment to use newest available image and production to use the AMI after it has been used/trusted for some time. Ideally this would be through a promotion process of the AMI itself.

Without AMI channels would it be enough to have a delay to the AMI usage? For example you can have dev environment use the latest available AMI but production should be something like latest - 1 month (or whatever amount of time would give you confidence and time to test).

I'm not positive if that is possible, but it might be better than having to publish your own SSM parameter store or maintain launch templates.

**Comment by rothgar** [comment]
If AMI release skew (or whatever we call it) works then it would be possible to do this at the provisioner level and you could mix and match AMI releases in the same cluster. So you could have one deployment use something like the "beta" provisioner with the latest AMI and labels/taints added to the nodes so workloads could opt-in to using those nodes.

**Comment by rayterrill** [comment]
PROD stability is indeed the goal.

We'd really rather not maintain our own parameter store or launch templates. Ideally - we'd love for AWS to publish AMI channels, with documentation around it (what it means to be in each of the channels so we can choose appropriately). Karpenter is such a good tool - we're trying to use it to offload more of this work to AWS.

We'd likely set PROD to stable (and maybe staging), but set the other envs to latest.

**Comment by rayterrill** [comment]
Both of those would work for us! Thanks @rothgar !

**Comment by njtran** [comment]
Closing in favor of tracking in #3657 and #1495
