### ISSUE TITLE
Links to code on Github should have release tag in them

### ISSUE THREAD

**Issue by spring1843** [aws/karpenter#1310]
**Is an existing page relevant?**

https://karpenter.sh/v0.6.1/faq/

**What karpenter features are relevant?**

N/A

**How should the docs be improved?**

In places where we are linking to code on Github, Instead of linking to the main branch we should consider linking to a permanent link to code at the time of document generation i.e. release time by using the tag in the URL.

Example:
Correct: https://github.com/aws/karpenter/blob/v0.6.1/charts/karpenter/templates/controller/rbac.yaml
Incorrect: https://github.com/aws/karpenter/tree/main/charts/karpenter/templates/controller/rbac.yaml 

Here's an example of PRs that were trying to fix broken to out dated code:
https://github.com/aws/karpenter/pull/1305
https://github.com/aws/karpenter/pull/1304
https://github.com/aws/karpenter/pull/1301

This will have a couple of benefits:
1. If the files are deleted from the main branch, the documentation will still have working links
2. Users always see the "correct" file relevant to the release they are interested in

A few options here are
1. Use something similar to this: https://github.com/aws/karpenter/blob/main/hack/release.sh#L40
2. Use the templating features of hugo to render the release version

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by chrisnegus** [comment]
It appears that PRs [#1305](https://github.com/aws/karpenter/pull/1305)
and [#1402](https://github.com/aws/karpenter/pull/1402) resolve this issue.
Please reopen if there is anything that still needs to be done here.
