### ISSUE TITLE
Unit tests results are dependent to the running order

### ISSUE THREAD

**Issue by felix-zhe-huang** [aws/karpenter#1338]
## Version

**Karpenter**: v0.6.1

**Kubernetes**: v1.20

## Expected Behavior

Order of executing unit tests should not affect the results.

## Actual Behavior

A known bug will caused the selection controller unit tests to fail if tested separately. However, if we run `make test`, all tests will pass.

## Steps to Reproduce the Problem

1. Remove line 296 ~ 298 from pkg/apis/provisioning/v1alpha5/requirements.go.
```
func (r *Requirements) MarshalJSON() ([]byte, error) {
	/*
		if r.Requirements == nil {
			r.Requirements = []v1.NodeSelectorRequirement{}
		}
	*/
	return json.Marshal(r.Requirements)
}
```
2. run `make test` will pass all the tests.
3. run `ginkgo -r` for selection controller will fail all the tests.

**Comment by ellistarn** [comment]
I'm also noticing
```
ginkgo -r
[1644862888] Validation - 52/52 specs •••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 1.486174ms PASS
[1644862888] CloudProvider/AWS - 41/41 specs ••••••••••••••••••••••••••••••••••••••••• SUCCESS! 10.625161487s PASS
[1644862888] Node - 18/18 specs •••••••••••••••••• SUCCESS! 9.255173497s PASS
[1644862888] Volume - 3/3 specs ••• SUCCESS! 6.453747045s PASS
[1644862888] Controllers/Provisioning - 12/12 specs •••••••••••• SUCCESS! 8.939217924s PASS
PASS
testing: warning: no tests to run
Found no test suites, did you forget to run "ginkgo bootstrap"?[1644862888] Controllers/Scheduling - 44/44 specs •••••••••••••••••••••••••••••••••••••••••••S SUCCESS! 11.305665722s PASS
[1644862888] Controllers/Selection - 12/12 specs •••••••••••• SUCCESS! 9.129481224s PASS
[1644862888] Termination - 9/9 specs ••••••••• SUCCESS! 11.565414363s PASS
[1644862888] Functional Suite - 6/6 specs •••••• SUCCESS! 399.045µs PASS
[1644862888] Sets Suite - 11/11 specs ••••••••••• SUCCESS! 398.243µs PASS

Ginkgo ran 11 suites in 1m30.437211569s
```

Where is this coming from
```
Found no test suites, did you forget to run "ginkgo bootstrap"?[1644862888] Controllers/Scheduling - 44/44 specs 
```

**Comment by tzneal** [comment]
`Found no test suites, did you forget to run "ginkgo bootstrap"?` is because of packer_test.go , ginkgo apparently doesn't like standard Go benchmarks.

**Comment by spring1843** [comment]
This outcome was not because the tests results are dependent on the running order. In fact we randomize the order in `make battletest`.

It turns out when the user was running `make test` it would run `kube-apiserver v1.21.4` (the version for that is set [here](https://github.com/aws/karpenter/blob/main/Makefile#L2))  and when the user was running it in `pkg/controllers/provisioning` `kube-apiserver v1.19.c` was running because `KUBEBUILDER_ASSETS` was not set.

The code seems to be running as expected since reproduction of this error requires commenting out important lines of code that instantiate the slice.

**Comment by felix-zhe-huang** [comment]
Since we do support v1.19, can we find out why this will pass for v1.21 and not v1.19? This is because our github action has a flow that run all the tests in v1.19.
