### ISSUE TITLE
Newly added nodes stuck in NotReady state

### ISSUE THREAD

**Issue by astonim** [aws/karpenter#1342]
## Version

**Karpenter**: v0.5.4

**Kubernetes**: v1.20.10

## Expected Behavior
Follow "getting started guide" to setup the cluster. Install Karpenter, etc. Then take the launch template created automatically. Adjust the disk partition size. Use the launch template as custom launch template. Create a new provisioner. Create nodes using the label of the new provisioner. Expected node to function normally.

## Actual Behavior
Node provisioned shows up under "kubectl get nodes" as in NotReady status. Pod cannot be scheduled on node.

## Steps to Reproduce the Problem
As described in "Expected Behavior"

## Resource Specs and Logs
Cannot provide provisioner spec and Karpenter logs. as it is under company IP protection policy. Please work through AWS support to obtain.

Note: Please work through AWS support ticket to continue. This issue is entered per request from AWS support.

**Comment by suket22** [comment]
The best way to investigate issues with your worker node will be to [collect logs with this tool](https://github.com/awslabs/amazon-eks-ami/tree/master/log-collector-script/linux) and dive into them. If you can find me on Slack (K8s workspace) and give me your AWS case ID, I can try following up with AWS Support as well.

In general, we'd recommend to start looking at kubelet logs to understand why the kubelet doesn't declare itself as `Ready` and going from there. Common issues that you could be running into include a problem with the CNI w/ incorrect or insufficient IAM policies or some security group settings.

**Comment by astonim** [comment]
In this case "systemctl status kubelet" shows

> ● kubelet.service - Kubernetes Kubelet
>    Loaded: loaded (/etc/systemd/system/kubelet.service; disabled; vendor preset: disabled)
>   Drop-In: /etc/systemd/system/kubelet.service.d
>            └─10-kubelet-args.conf, 30-kubelet-extra-args.conf
>    Active: inactive (dead)
>      Docs: https://github.com/kubernetes/kubernetes

This means the kubelet wasn't even successfully started. So I believe the issue is in the AWS AMI that is used with the launch template. It is not really a Karpenter issue.

**Comment by suket22** [comment]
Which AMI version are you on? Can you check the contents of `/var/log/messages` ? That might have more info on what failed before the kubelet

**Comment by astonim** [comment]
The AMI version is ami-07854b27891cd310f

Here is the end of /var/log/messages (cloud-init failed?)

> Feb 15 19:01:35 ip-10-9-107-121 cloud-init: Cloud-init v. 19.3-44.amzn2 finished at Tue, 15 Feb 2022 19:01:35 +0000. Datasource DataSourceEc2.  Up 378.18 seconds
> Feb 15 19:01:35 ip-10-9-107-121 systemd: cloud-final.service: main process exited, code=exited, status=1/FAILURE
> Feb 15 19:01:35 ip-10-9-107-121 systemd: Failed to start Execute cloud user/final scripts.
> Feb 15 19:01:35 ip-10-9-107-121 systemd: Unit cloud-final.service entered failed state.
> Feb 15 19:01:35 ip-10-9-107-121 systemd: cloud-final.service failed.
> Feb 15 19:01:35 ip-10-9-107-121 systemd: Reached target Cloud-init target.
> Feb 15 19:01:35 ip-10-9-107-121 systemd: Startup finished in 3.446s (kernel) + 1.698s (initrd) + 6min 13.067s (userspace) = 6min 18.211s.
> Feb 15 19:01:44 ip-10-9-107-121 dhclient[9921]: XMT: Solicit on eth0, interval 124810ms.
> Feb 15 19:03:49 ip-10-9-107-121 dhclient[9921]: XMT: Solicit on eth0, interval 109500ms.
> Feb 15 19:05:38 ip-10-9-107-121 dhclient[9921]: XMT: Solicit on eth0, interval 118440ms.
> Feb 15 19:07:37 ip-10-9-107-121 dhclient[9921]: XMT: Solicit on eth0, interval 113030ms.
> Feb 15 19:08:19 ip-10-9-107-121 systemd: Created slice User Slice of ec2-user.
> Feb 15 19:08:19 ip-10-9-107-121 systemd-logind: New session 3 of user ec2-user.
> Feb 15 19:08:19 ip-10-9-107-121 systemd: Started Session 3 of user ec2-user.

**Comment by suket22** [comment]
Right. That explains why the kubelet didn't come up healthy. Somewhere in that log (slightly above) there should be an explanation as to what failed execution in the UserData. `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` should have this info too.

**Comment by astonim** [comment]
In /var/log/messages, I found this (probably the first entry of failure messages)

> Feb 15 19:20:14 ip-10-9-177-41 pull-sandbox-image.sh: main.main()
> Feb 15 19:20:14 ip-10-9-177-41 pull-sandbox-image.sh: github.com/containerd/containerd/cmd/ctr/main.go:37 +0x125
> Feb 15 19:20:14 ip-10-9-177-41 systemd: sandbox-image.service: main process exited, code=exited, status=2/INVALIDARGUMENT
> Feb 15 19:20:14 ip-10-9-177-41 systemd: Failed to start pull sandbox image defined in containerd config.toml.
> Feb 15 19:20:14 ip-10-9-177-41 systemd: Unit sandbox-image.service entered failed state.
> Feb 15 19:20:14 ip-10-9-177-41 systemd: sandbox-image.service failed.

And from /var/log/cloud-init.log

> Feb 15 19:20:14 cloud-init[10361]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)                            Feb 15 19:20:14 cloud-init[10361]: handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance      Feb 15 19:20:14 cloud-init[10361]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed                                                                                                                                  Feb 15 19:20:14 cloud-init[10361]: util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed                                                                                                                                    Traceback (most recent call last):                                                                                                                                          File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 851, in _run_modules                                                                                      freq=freq)                                                                                                                                                              File "/usr/lib/python2.7/site-packages/cloudinit/cloud.py", line 54, in run                                                                                                 return self._runners.run(name, functor, args, freq, clear_on_fail)                                                                                                      File "/usr/lib/python2.7/site-packages/cloudinit/helpers.py", line 187, in run                                                                                              results = functor(*args)                                                                                                                                                File "/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.py", line 45, in handle                                                                             util.runparts(runparts_path)                                                                                                                                            File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 920, in runparts                                                                                            % (len(failed), len(attempted)))
> RuntimeError: Runparts: 1 failures in 1 attempted commands

**Comment by suket22** [comment]
> Feb 15 19:20:14 ip-10-9-177-41 systemd: sandbox-image.service: main process exited, code=exited, status=2/INVALIDARGUMENT

This failure is indicative of [this script failing to execute](https://github.com/awslabs/amazon-eks-ami/blob/master/files/pull-sandbox-image.sh#L6) on the AMI. This is most likely to happen if the instances launched don't have any instanceProfile attached to them. 

This could happen if no instanceProfile was provided to the Karpenter binary as a CLI arg, or alternatively `provider.instanceProfile` was not set.

**Comment by astonim** [comment]
The provisioner does have a instanceProfile attached to it. Here is what I got by "kubectl get provisioner xxx -o yaml" (Sorry, I have to block off the name of the provisioner)

>   provider:
>     apiVersion: extensions.karpenter.sh/v1alpha1
>     instanceProfile: KarpenterNodeInstanceProfile-xxxx
>     kind: AWS
>     launchTemplate: Karpenter-xxxx

**Comment by suket22** [comment]
Ah, I think when you specify your own launch template, the instanceProfile might need to be specified within it. You can look at the EC2 console to verify if the instance did indeed have an instance profile attached

**Comment by ellistarn** [comment]
Is this a docs gap?

**Comment by suket22** [comment]
@ellistarn Our launch templates documents [do call this out](https://karpenter.sh/v0.6.2/aws/launch-templates/#instance-profile---iam) -  `The launch template must include an “instance profile” – an IAM role.` 

Maybe it's worth having some form of validation on the launch template - if it doesn't have an instance profile or a security group selector, your worker nodes aren't going to join / be healthy so we should maybe at least validate their existence?

**Comment by astonim** [comment]
Adding the instanceProfile INSIDE the launch template works. Thanks.

From a user's perspective, I would say why do I need to do this? The instanceProfile is specified in the provisioner. I would expect it to be carried into the launchTemplate. Also, having the instanceProfile baked into the launchTemplate won't allow sharing the same launchTemplate across multiple clusters because the IAM roles can be cluster specific.

In any case, the original reported issue is resolved.

**Comment by suket22** [comment]
There's a lot of complexity involved in merging fields in the Provisioner with what's in the launch template. We've found the cleanest abstraction to be that when you're using a launch template, you take over complete control over each instance level configuration and not have to worry about what overrides what. There's some more discussion about this very aspect of launch templates here [which we're actively working on.](https://github.com/aws/karpenter/pull/1270). 

> Also, having the instanceProfile baked into the launchTemplate won't allow sharing the same launchTemplate across multiple clusters because the IAM roles can be cluster specific.

I'd strongly recommend you do indeed have different launch templates per cluster to reduce your blast radius if a bad change is made to the launch template. Ideally a bad change to a launch template only limits your impact to the provisioner that was using it and not multiple production clusters, especially with Karpenter always automatically choosing whatever `$LATEST` is.
