### ISSUE TITLE
Deprecate Constraints Object

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#1350]
**Tell us about your request**
We currently use a `Constraints` struct that we pass around the code base. This is implemented using an inline struct inside the provisioner. It's caused some confusion to readers, and breaks doc generators as well as exposes a bug with nested inline structs. Instead, we should explore just passing the provisioner object around and promoting all fields of the constraints object up to the provisioner. 

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by felix-zhe-huang** [comment]
To make things more confusing, there is `schedule` which uses `Constraints` as an inline struct.
I think we need to define an API shim layer that defines the API specs, and internal implementation that defines structs with members to separate according to their abstraction.
