### ISSUE TITLE
Provisioner Taint is not accepted

### ISSUE THREAD

**Issue by oussemos** [aws/karpenter#1357]
## Version

**Karpenter**: v0.6.1

**Kubernetes**: v1.21.5-eks

## Expected Behavior

I am trying to add this taint that we had on instances managed by autoscaler/ASG to the Provisioner. 
`digital.example.com/spot-instance=spot:NoSchedule
`
I am not sure if I am doing it wrong or the regex validation is not good

```
taints:
  - key: "digital.example.com/spot-instance=spot"
     effect: "NoSchedule"
```

## Actual Behavior

`admission webhook "validation.webhook.provisioners.karpenter.sh" denied the request: validation failed: invalid value: name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'): spec.taints[0]`

**Comment by cest-pas-faux** [comment]
Hello,
This is not a bug, have a look at the doc : https://karpenter.sh/v0.6.2/tasks/provisioning/#example-isolating-expensive-hardware

It should look like this : 
`
  taints:
    - key: digital.example.com/spot-instance
      value: spot
      effect: “NoSchedule”
`

**Comment by oussemos** [comment]
My bad.. thanks @cest-pas-faux
