### ISSUE TITLE
Helm charts introduced breaking changes without bumping major semver

### ISSUE THREAD

**Issue by alekc** [aws/karpenter#1358]
During an upgrade to the latest helm chart (0.5.6->0.6.2), unexpectedly karpenter installation was not working anymore thus blocking entire cluster bootstrapping process. 

After further investigation, turns out that it was caused by a recent refactor where several options (i.e. webhook.nodeSelector and tolerations) were moved around thus preventing karpenter to come up because it didn't have any of the required tolerations. 

Imho, this should have been a bump to the v1 of the helm chart since it's a breaking change and no further communication has been provided (i.e. Readme). 

Potential Solutions:

- bump chart version to v1. It won't solve the issue for people using the >=0.6.1, but at the very least it will show that a new chart version exists with potentially breaking changes in place
- Put a description in chart readme warning about recent refactoring and documenting what has been changed from the value point of view.

**Comment by Skarlso** [comment]
I guess Karpenter cannot be considered stable in any case. So.... ¯\\\_(ツ)\_/¯ Just don't use it I guess for anything serious yet.

**Comment by ellistarn** [comment]
We're trying to balance agility and stability. For now, we may make breaking changes, but will only do so with the appropriate version bumps (e.g. CRD version, helm version, etc). With this approach, we hope to make it crystal clear to users when code changes may be required to upgrade. 

This issue calls out a gap in the above philosophy -- the helm chart refactor is a miss. 

> Same for eksctl's install flow.

Can you elaborate? The getting started guide is just a guide, and we don't have any compatibility guarantees.

**Comment by alekc** [comment]
@ellistarn I understand that at the moment karpenter is fast paced project and some breaks will come out, that's not the issue. The issue (imho) comes when there is a deliberate breaking change applied (as in not the actual bug/unseen side effect) which is not being documented (well, and in case of the helm chart nothing would have prevented us from decoupling it and having a separate versioning number) 

Having said that, I can amend the documentation if needed once we decide where it should go.

**Comment by ellistarn** [comment]
> The issue (imho) comes when there is a deliberate breaking change applied (as in not the actual bug/unseen side effect) which is not being documented (well, and in case of the helm chart nothing would have prevented us from decoupling it and having a separate versioning number)

Completely agree with this criticism. We need to improve on this.

**Comment by Skarlso** [comment]
@ellistarn Sure. It's the fact that helm value `clusterName` and `clusterEndpoint` moved out from under controller. Hence, the install failed, because the pods didn't start up because they were missing cluster name and endpoint values.

It's fine, it's not the end of the world. Was just unexpected. :))

**Comment by rayterrill** [comment]
> @ellistarn Sure. It's the fact that helm value clusterName and clusterEndpoint moved out from under controller. Hence, the install failed, because the pods didn't start up because they were missing cluster name and endpoint values.

Just ran into this yesterday upgrading to the new version of the helm chart.

**Comment by ellistarn** [comment]
Closing as I don't believe we have an AI here. We'll be improving our release process over the coming weeks.
