### ISSUE TITLE
Getting Started with Karpenter on AWS

### ISSUE THREAD

**Issue by ED-txtify** [aws/karpenter#1363]
I am running Helm Version:

`version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}`

And when I run the Helm command:

helm upgrade --install --namespace karpenter --create-namespace \
  karpenter karpenter/karpenter \
  --version v0.6.3 \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} \
  --set clusterName=${CLUSTER_NAME} \
  --set clusterEndpoint=${CLUSTER_ENDPOINT} \
  --set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
  --wait # for the defaulting webhook to install before creating a Provisioner

I get this error:

```
Error: "helm upgrade" requires 2 arguments

Usage:  helm upgrade [RELEASE] [CHART] [flags]
```

I don't use helm so I am unsure about this error message and was wondering if this may be an issues others are having?

UPDATE

If I run:

```
helm upgrade --install --namespace karpenter --create-namespace karpenter karpenter/karpenter \
  --version v0.6.3 \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} \
  --set clusterName=${CLUSTER_NAME} \
  --set clusterEndpoint=${CLUSTER_ENDPOINT} \
  --set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
```

Then it works for me

**Comment by duyhenryer** [comment]
I got an error when installing Karpenter 
Helm version:
```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```

```
helm repo add karpenter https://charts.karpenter.sh/
helm repo update

helm upgrade --install --namespace karpenter --create-namespace \
  karpenter karpenter/karpenter \
  --version v0.6.3 \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} \
  --set clusterName=${CLUSTER_NAME} \
  --set clusterEndpoint=${CLUSTER_ENDPOINT} \
  --set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
  --wait # for the defaulting webhook to install before creating a Provisioner
```
Error:
```
Update Complete. ⎈Happy Helming!⎈
Release "karpenter" does not exist. Installing it now.
Error: Chart.yaml file is missing
```

**Comment by ED-txtify** [comment]
> 

The docs say:

```
helm upgrade --install --namespace karpenter --create-namespace \
  karpenter karpenter/karpenter \
```

And I found that if I ran it like this it works:

```
helm upgrade --install --namespace karpenter --create-namespace karpenter karpenter/karpenter \

```

I am not sure, perhaps it is because I am doing it on a Mac and the Helm is treating the command a little bit different.

**Comment by ellistarn** [comment]
Not sure I'm understanding the issue here. Might be a local shell issue? Works in `zsh` and `sh` and `bash` for me
```
helm upgrade --install --namespace karpenter --create-namespace \
  karpenter karpenter/karpenter \
  --version v0.6.3 \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} \
  --set clusterName=${CLUSTER_NAME} \
  --set clusterEndpoint=${CLUSTER_ENDPOINT} \
  --set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
  --wait # for the defaulting webhook to install before creating a Provisioner
```
