### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by sriram0721** [aws/karpenter#1366]
## Version

**Karpenter**: v0.6.1

**Kubernetes**: v1.21.1
I deployed helm charts to install karpenter on eks. i've also created IAM roles and instance profiles. When i try to test the workflow by scaling a deployment, i get the error as **You are not authorized to perform this operation**

**Comment by suket22** [comment]
Where are you seeing - `You are not authorized to perform this operation`? Could you give us a logs snippet so we can help more

**Comment by suket22** [comment]
@sriram0721 could you give us more info? Feel free to re-open if you're still running into an issue and need help.

**Comment by sriram0721** [comment]
hey! apparently the issue is fixed. thanks
