### ISSUE TITLE
Provisioning Bare Metal Instance Type

### ISSUE THREAD

**Issue by felix-zhe-huang** [aws/karpenter#1371]
**Is an existing page relevant?**

**What karpenter features are relevant?**

Provisioning bare metal instance type.

**How should the docs be improved?**
By default, Karpenter will not provision bare metal node unless provisioner.spec explicitly select those types.
For example:
```
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - m5.metal
```
Documents need to be updated to reflect this behavior.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Completed.
