### ISSUE TITLE
Decouple provisioner selection logic from requirement logic through provisioner preferences and layered defaults

### ISSUE THREAD

**Issue by felix-zhe-huang** [aws/karpenter#1376]
**Tell us about your request**
What do you want us to build?

- A mechanism to assign preferences to multiple compatible provisioners
- Refactor the requirements to have a unified design logic (if not defined, everything is allowed)
- Remove provisioner.spec.labels in v1alpha6

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Currently the provisioner selection depends on validating the requirements described in the pod.spec against the provisioner requirements. Pods with node selector on custom labels will requires a provisioner with the same labels defined. This provisioner selection logic is then translated to requirement logic that results in a non-commutative rule that requirements object with In operator and a concrete value is not compatible to requirements object without the same key. However, this is against the requirement design logics that are implemented  in an explicit-list manner. If a key is not specified, all the values for that key are allowed. It makes this non-commutative rules an illy constructed corner case that causes a large amount of design complexity in scheduling logic.

A better design is to remove this non-commutative rule. It means that if a provisioner does not explicitly lists the allowed/deny values, it will allow any value. This will result in a pod being mapped to multiple provisioners. In this case, pod should be matched to a provisioner that has the tightest fit (i.e., the maximum number of matched requirements without violation in any other requirements.)  Karpenter should implement a provisioner preference mechanism for this purpose.

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
This is mostly done. The last topic is the following which is being tracked in https://github.com/aws/karpenter/issues/1327. Closing in favor of that.

> Remove provisioner.spec.labels in v1alpha6
