### ISSUE TITLE
Purge Karpenter Nodes when Cluster is destroyed

### ISSUE THREAD

**Issue by albertjunkim** [aws/karpenter#1382]
**Tell us about your request**
What do you want us to build?

- Let Karpenter(whether Karpenter is running in worker node or control plane) listen to EKS Cluster deletion events via CloudWatch(or etc.) and purge all provisioned Karpenter nodes.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

- Provisioning EKS clusters and Karpenter via terraform would not have any ability to de-provision the Karpenter Nodes automatically. While using the null resource with a local provisioner to trigger kubectl to scale down pods and delete(drain, cordon) nodes is one way to achieve this; however, this approach is still unreliable to clean up the nodes. 

**Are you currently working around this issue?**
How are you currently solving this problem?

- Utilizing null resource with local provisioner to delete nodes only when terraform destroy is triggered. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by suket22** [comment]
We've had this request come up before. See https://github.com/aws/karpenter/issues/1134

Essentially, we don't think this is the responsibility of Karpenter but rather whatever IaC tooling is used to create Karpenter instead. 

> While using the null resource with a local provisioner to trigger kubectl to scale down pods and delete(drain, cordon) nodes is one way to achieve this; however, this approach is still unreliable to clean up the nodes.

I don't think this is unreliable. When you're about to destroy a cluster, i'd assume that you've already started to scale down your application pods to 0. At this point, Karpenter should already be terminating your empty nodes. 

Alternatively, if you're looking to delete your worker nodes directly -`kubectl delete node` will work fine. It will trigger a graceful drain of all the pods on your worker node and then get rid of your instance after.
