### ISSUE TITLE
Default EC2 tagging configuration for Provisioner resources

### ISSUE THREAD

**Issue by bryangardner** [aws/karpenter#1383]
**Tell us about your request**
The Karpenter controller can add tags to every EC2 instance by configuring the `spec.provider.tags` property on the `Provisioner` resource. Organizations sometimes require all AWS resources to be tagged for cost allocation processes. It would be helpful if the Karpenter controller can apply a default set of tags to every `Provisioner` resource so that they do not need to be manually added to every one.

Users should be able to override a default tag by redeclaring it on a `Provisioner` resource.

I think this could either be done with a mutating web hook that modifies each `Provisioner` or within the AWS provider implementation in the controller.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Tag every EC2 instance to comply with organization standards for cost allocation. Right now, tags have to be manually added to every `Provisioner`.

**Are you currently working around this issue?**
Manually adding tags to every `Provisioner` resource.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
I've seen other projects do this via a `defaults` configmap. We currently do something similar for `aws.defaultinstanceprofile`. I could imagine extracting that out into a configmap that contains additional fields like you mention.

**Comment by njtran** [comment]
We have this implemented in `aws.tags` in the `karpenter/karpenter-global-settings` configmap. More here:  https://karpenter.sh/v0.27.3/concepts/settings/#configmap

Just to let you know, we're considering removing this as it makes it tough for Drift to reconcile, and the json representation of  the tags in the configmap is tricky as well. This would be a breaking change and a major version bump if we do, so make sure to watch release notes.

**Comment by montanaflynn** [comment]
@njtran I see that settings.aws.tags has been dropped in 0.32:

https://karpenter.sh/v0.32/upgrading/v1beta1-migration/#helm-values

Is there currently anyway to tag aws ec2 instances for nodes created by karpenter? We would ideally like to put that in either the nodepool and/or nodeclass so all pods scheduled using those would be tagged appropriately for cost reporting purposes.
