### ISSUE TITLE
Pod replicas are running on the same node

### ISSUE THREAD

**Issue by devopsjnr** [aws/karpenter#1385]
Deploying my new deployment with value `replicas: 3`. 

When I used Node Groups, each of the three pods ran In a different node - in that case, if one node was down, my service still ran in other nodes, so no downtime. 
When using Karpenter, all the 3 pods of the replica are sitting in the same node- so if the node is down, my service is down. 

Does Karpenter know to avoid that situation? I would like to have a pod separation into different nodes when defining `replicas`. 

Thanks in advance!

**Comment by ellistarn** [comment]
> When I used Node Groups, each of the three pods ran In a different node - in that case, if one node was down, my service still ran in other nodes, so no downtime.

This is not guaranteed by the kube scheduler. You were relying on the kube scheduler's preference for scheduling pods onto the least utilized node, but this cannot be relied on in dynamic clusters. e.g., if one of those nodes was full, the scheduler would happily put all 3 pods on the same node (if there's room).

You're looking for Pod Topology Spread:
https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
https://karpenter.sh/v0.6.3/tasks/scheduling/#topology-spread

**Comment by sylr** [comment]
Related to https://github.com/aws/karpenter/issues/1354

**Comment by ellistarn** [comment]
I'm not sure I'm tracking this issue.
1. Are you talking about karpenter controller pods running together?
2. Are you talking about karpenter launching nodes for unschedulable pods?

**Comment by devopsjnr** [comment]
@ellistarn I have something like 500 deployments in my cluster. 
I am talking about having a solution that will not involve editing all the 500 deployments, but **only** the provisioner. 

I'd like to have a field in the provisioner, so that when a deployment (the suits the provisioner) has `replica:5`, each replica will live in a different node. 

Is [topology spread](https://karpenter.sh/v0.6.3/tasks/scheduling/#topology-spread) answers my request?

**Comment by ellistarn** [comment]
Karpenter isn't the right system to inject default topology rules. Karpenter is only a piece of the puzzle. The kube scheduler is also deeply involved in scheduling (to existing capacity), and without some scheduling guarantee like Topology Spread, you're not going to get the behavior you're looking for. 

You could consider writing a mutating admission webhook to inject this parameter into your pod specs to avoid specifying them at the deployment level. However, this may not be desirable for all pods, so you'll need to be a bit careful about assumptions with this approach.
