### ISSUE TITLE
Error on creation using eksctl

### ISSUE THREAD

**Issue by tomahawk-pilot** [aws/karpenter#1386]
## Version
0.6.3
**Karpenter**: v0.0.0
Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b"  GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"
**Kubernetes**: v1.21.0

## Expected Behavior
installation success

## Actual Behavior
getting cant install helm chart . namespace not found error on eksctl create cluster

**Comment by suket22** [comment]
This might be related - https://github.com/weaveworks/eksctl/issues/4804

**Comment by ellistarn** [comment]
Closing in favor of tracking on the eksctl repo.
