### ISSUE TITLE
Is karpenter ready for production?

### ISSUE THREAD

**Issue by tomhardyctl** [aws/karpenter#1390]
**Is an existing page relevant?**

**What karpenter features are relevant?**

**How should the docs be improved?**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
https://aws.amazon.com/blogs/aws/introducing-karpenter-an-open-source-high-performance-kubernetes-cluster-autoscaler/

**Comment by ellistarn** [comment]
Just because we're production ready, doesn't mean the project is feature complete. If you're blocked on any missing features in Karpenter feel free to cut an issue.
