### ISSUE TITLE
Bottlerocket disks arent encrypted correctly

### ISSUE THREAD

**Issue by djtje12** [aws/karpenter#1408]
## Version

**Karpenter**: v0.6.2

**Kubernetes**: v21.9

## Expected Behavior

When the Karpenter controller creates a launchtemplate based of the bottlerocket amiFamily it encrypts both drives.

## Actual Behavior

The default launch template created for the Bottlerocket amiFamily only has encryption for 1 of its [2 drives](https://github.com/bottlerocket-os/bottlerocket/issues/1203)

## Steps to Reproduce the Problem

Create a provisioner with the bottlerocket amiFamily and check the launchtemplates created in the AWS console

## Resource Specs and Logs

See screenshot below how the launchtemplate now looks like encryption wise. 
![Screenshot 2022-02-23 at 20 39 46](https://user-images.githubusercontent.com/46244867/155395345-b52171de-0fe2-4023-a398-dd41ceeb4408.png)

**Comment by bwagner5** [comment]
Thanks for creating this issue! I believe this is a pretty simple fix to just add the `/dev/xvdb` if using `Bottlerocket`. I'm testing the changes to encrypt both volumes now.

**Comment by ellistarn** [comment]
Coming in v0.7.0!
