### ISSUE TITLE
Remove clusterEndpoint from Helm values.yaml to simplify GitOps usage by implementing autodiscovery of clusterEndpoint

### ISSUE THREAD

**Issue by youwalther65** [aws/karpenter#1411]
**Tell us about your request**
GitOps tools like Fluxv2 shine most when configurations can be kept generic. The Helm chart contains clusterEndpoint which will change with every cluster creation I 'd like to have auto-discovery of  clusterEndpoint to remove the value from Helm values.yaml 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
How are you currently solving this problem?
I use Fluxv2 Kustomization [variable substitution](https://fluxcd.io/docs/components/kustomize/kustomization/#variable-substitution) for all other values.yaml attributes which can be kept more generic (clusterName, defaultInstanceProfile). But the clusterEndpoint will change with every vluster creation. For AWS when providing clusterName the clusterEndpoint and other attributes like networkConfigustion could be gathered from EKS DescribeCluster API. So having clusterName and clusterEndpoint would be redundant information and the later could be removed.

**Additional context**
Anything else we should know?
This would only require to add eks:DescribeCluster to the IAM policy of the KarpenterController IAM Role which has to be done by the user. Controller is responsible for querying the EKS DescribeCluster AOI

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Posted in the other issue, but it applies here. We intentionally do not rely on EKS to ensure that Karpenter works well on selfhosted AWS (e.g. CAPA, etc). It's potentially a candidate for autodiscovery, but I'm wary about the number of code paths this creates.
