### ISSUE TITLE
Provisioning Configuration using wildcard * for spec.provider

### ISSUE THREAD

**Issue by smartbenson1** [aws/karpenter#1416]
When configuring spec.provider for provisioner, needs to use "" quotes for wildcard "*". 

In the example in doc, the following example need to be "*public*" instead; otherwise it will throw an error “error converting YAML to JSON: yaml: line 23: did not find expected alphabetic or numeric character”

subnetSelector:
    Name: *public*

**Comment by ellistarn** [comment]
Would you be willing to cut a PR to fix this?
