### ISSUE TITLE
Standardize Naming Schemes across guides

### ISSUE THREAD

**Issue by herbertgoto** [aws/karpenter#1421]
## Version
**Karpenter**: v0.6.3

**Kubernetes**: 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

## Expected Behavior
Karpenter is installed via Helm

## Actual Behavior
Release "karpenter" does not exist. Installing it now.
Error: timed out waiting for the condition

## Steps to Reproduce the Problem
eksctl create iamserviceaccount \
  --cluster $CLUSTER_NAME --name "${CLUSTER_NAME}-karpenter"  --namespace karpenter \
  --role-name "${CLUSTER_NAME}-karpenter" \
  --attach-policy-arn arn:aws:iam::$ACCOUNT_ID:policy/KarpenterControllerPolicy-$CLUSTER_NAME \
  --role-only \
  --approve

helm repo add karpenter https://charts.karpenter.sh/
helm repo update

helm upgrade --install --namespace karpenter --create-namespace \
  karpenter karpenter/karpenter \
  --version v0.6.3 \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=arn:aws:iam::${ACCOUNT_ID}:role/eks-fintech-karpenter \
  --set clusterName=${CLUSTER_NAME} \
  --set clusterEndpoint=$(aws eks describe-cluster --name ${CLUSTER_NAME} --query "cluster.endpoint" --output json) \
  --set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
  --wait 

## Resource Specs and Logs
panic: Unable to hydrate the AWS launch template cache, WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
        status code: 403, request id: a7cd3b2e-e0e5-45b8-8f8c-6da59fb29cab

I made sure the sa is created, associated to both the AWS role and the pod. I see the permission at the role and it is ok:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::AWS ACCOUNT:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/OIDC ID"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-1.amazonaws.com/id/OIDC ID": "system:serviceaccount:karpenter:eks-fintech-karpenter",
                    "oidc.eks.us-east-1.amazonaws.com/id/OIDC ID": "sts.amazonaws.com"
                }
            }
        }
    ]
}

If I remove the condition, it solves the problem.

**Comment by ellistarn** [comment]
Mine is 
```
                    "oidc.eks.us-west-2.amazonaws.com/id/BE5C79AC824BB1EF67DB8CC14D6A263F:sub": "system:serviceaccount:karpenter:karpenter"
```

Looks like your service account name is wrong and so is your oidc ID.

**Comment by herbertgoto** [comment]
With respect to OIDC: I just remove it from the policy. How can it be wrong, if it works  when I delete the condition and it remains untouched as principal? 

With respect to sa: it is the same I created with eksctl: --name "${CLUSTER_NAME}-karpenter" . ${CLUSTER_NAME} is eks-fintech and you can see that in the Trust policy.

**Comment by njtran** [comment]
Can you validate that the `karpenter/karpenter serviceaccount` has the following line with the environment variables replaced? 

`eks.amazonaws.com/role-arn: arn:aws:iam::{ACCOUNT_ID}:role/{CLUSTER_NAME}-karpenter`

**Comment by njtran** [comment]
Additionally, would you be able to post the following? 
- Did you create the cluster with the command in the getting-started guide?
- What version of eksctl are you using if so? `eksctl version` will give you the output.

**Comment by herbertgoto** [comment]
Name:                karpenter
Namespace:           karpenter
Labels:              app.kubernetes.io/instance=karpenter
                     app.kubernetes.io/managed-by=Helm
                     app.kubernetes.io/name=karpenter
                     app.kubernetes.io/version=0.6.3
                     helm.sh/chart=karpenter-0.6.3
Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXX:role/eks-fintech-karpenter
                     meta.helm.sh/release-name: karpenter
                     meta.helm.sh/release-namespace: karpenter
Image pull secrets:  <none>
Mountable secrets:   karpenter-token-h6dm9
Tokens:              karpenter-token-h6dm9
Events:              <none>

**Comment by herbertgoto** [comment]
Did you create the cluster with the command in the getting-started guide? No. I did it with:

**Comment by herbertgoto** [comment]
_What version of eksctl are you using if so?_
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by njtran** [comment]
Running with the same eksctl version, Karpenter version and same eksctl ClusterConfig, I wasn't able to reproduce your problem from following the getting-started guide. The only special thing you would've needed to do is run the following command prior to creating the IAM role that goes into the `karpenter/karpenter` ServiceAccount. 
```
eksctl utils associate-iam-oidc-provider --region=us-east-1 --cluster=CLUSTER_NAME
```
If you can ensure that the role `eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXX:role/eks-fintech-karpenter` has the following trust statements I think this should work for you. The command above + the command in the [getting-started guide](https://github.com/aws/karpenter/blob/main/website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step05-controller-iam.sh) should help you get there.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::${ACCOUNT_ID}:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/${CLUSTER_ENDPOINT}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-1.amazonaws.com/id/${CLUSTER_ENDPOINT}:aud": "sts.amazonaws.com",
                    "oidc.eks.us-east-1.amazonaws.com/id/${CLUSTER_ENDPOINT}:sub": "system:serviceaccount:karpenter:karpenter"
                }
            }
        }
    ]
}
```
If the IAM role that's annotated in the `karpenter/karpenter` ServiceAccount doesn't have trust policies like above, and the controller policy doesn't have the following permissions below, you'll run into the credential problem you're hitting. Can you confirm that all of these steps are correct and the IAM roles and policies exist?
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ec2:CreateLaunchTemplate",
                "ec2:CreateFleet",
                "ec2:RunInstances",
                "ec2:CreateTags",
                "iam:PassRole",
                "ec2:TerminateInstances",
                "ec2:DeleteLaunchTemplate",
                "ec2:DescribeLaunchTemplates",
                "ec2:DescribeInstances",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeSubnets",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeInstanceTypeOfferings",
                "ec2:DescribeAvailabilityZones",
                "ssm:GetParameter"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```

**Comment by ellistarn** [comment]
@herbertgoto were you able to reproduce?

**Comment by victor10x** [comment]
First of all, @herbertgoto I feel your pain. I found this "[How do I troubleshoot an OIDC provider and IRSA in Amazon EKS?](https://aws.amazon.com/premiumsupport/knowledge-center/eks-troubleshoot-oidc-and-irsa/)" troubleshooting document and it helped me realize my configuration issue that gave me the same error message you had.

I'll note that my issue was due to this: going back and forth between the `eksctl` and `terraform` getting started guides revealed some naming discrepancies.

Overall, my goal was to use `terraform` but only for AWS resources and not for the deployment, i.e. the `helm install` step. So, I tried to switch to the `eksctl` guide for just the `helm` CLI section. What I realized is that not only did I need this line ([from the "Create the KarpenterController IAM Role" section](https://karpenter.sh/v0.7.2/getting-started/getting-started-with-eksctl/#create-the-karpentercontroller-iam-role))

```
export KARPENTER_IAM_ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:role/${CLUSTER_NAME}-karpenter"
```
but that it should have been
```
export KARPENTER_IAM_ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:role/karpenter-controller-${CLUSTER_NAME}"
```

So, my suggestion for the maintainers is: if possible, standardize naming across the getting started guides if at all possible.

**Comment by ellistarn** [comment]
This has been a painpoint for us. Keeping these guides in sync is tough, and even worse since it was contributed by a community member. Thanks for calling this out, and we'll take a pass and check in on naming.

**Comment by FernandoMiguel** [comment]
@ellistarn you folks need a terraform copy editor :)
I'll try to contribute more where I can.
Clearly the terraform bits in the docs are not up to spec

**Comment by chrisnegus** [comment]
Rather than maintain our own Terraform guide, we are dropping the Karpenter Terraform guide and pointing to the [Amazon EKS Blueprints for Terraform](https://aws-ia.github.io/terraform-aws-eks-blueprints) guide and associated instructions for [Karpenter](https://aws-ia.github.io/terraform-aws-eks-blueprints/v4.18.0/add-ons/karpenter/). So we will no longer publish guides with conflicting naming. See [PR #3312](https://github.com/aws/karpenter/pull/3312).
