### ISSUE TITLE
Ignore podAffinity/podAntiAffinity

### ISSUE THREAD

**Issue by dotanalter** [aws/karpenter#1426]
**Tell us about your request**
We would like to have an option to ignore the pod's affinity/anti-affinity instead of not scheduling the pod at all.
(maybe add something like an unsafe flag to the controller)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently, since anti-affinity is still not implemented and pods that have affinity/anti-affinity will not schedule at all this is a huge blocker for us to implement Karpenter in our system. An option to ignore the affinity/anti-affinity will give us the option to keep testing Karpenter and maybe we can even decide to take it into production use, even though affinity is not really functioning at this point.

**Are you currently working around this issue?**
Right now no workaround at all, pods are stuck in a pending state.
Can't continue testing and of course, can't take it to production.

**Additional context**
I think ignoring the affinities can help the community take Karpenter to the next stage (at least in non-prod environments).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sylr** [comment]
I second that, I use third party helm charts that have antiAffinities hardcoded and that's cumbersome to have to fork the charts to remove them and then have to maintain that.

**Comment by njtran** [comment]
Hey @dotanalter thanks for opening the issue. We're currently working on this and you should see this soon. Currently node affinity is in the works here, where pod affinity will come after. https://github.com/aws/karpenter/pull/1392/files.

**Comment by ellistarn** [comment]
> We're currently working on this and you should see this soon.

To be clear. We're hoping to avoid short term hacks, since we believe we'll be able to deliver a fully functioning antiaffinity implementation in the near future. Keep an eye on @felix-zhe-huang's PRs.

**Comment by ellistarn** [comment]
Closing in favor of https://github.com/aws/karpenter/issues/942
