### ISSUE TITLE
Tag root volumes

### ISSUE THREAD

**Issue by johngmyers** [aws/karpenter#1430]
**Tell us about your request**

Tag the root EBS volumes of Karpenter-created instances, preferably with the instance tags.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

For cost control, we want all AWS resources that cost money to have tags which allow us to ascribe their cost to the responsible sub-organization.

Furthermore, for security purposes we want all AWS resources that store data to have a tag specifying the most restrictive security classification applicable to the data so stored.

Karpenter, as of v0.5.5, creates root EBS volumes with zero tags.

**Are you currently working around this issue?**

No, since we are just starting build-out of Karpenter. Back when we relied on systems that used Launch Configurations we had a lambda that would copy tags from an instance to its root EBS volume, but this is clunky.

**Additional context**

Simplest would be to use the same set of tags for both the instance and the volumes created by the launch template.

**Attachments**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Great suggestion. I hope it's possible to include this in the fleet request so we don't have to reconcile the tags. Is it possible to do cost allocation by checking the instances the root volumes are attached to?

**Comment by johngmyers** [comment]
It's a bit much to expect the cost reporting to follow root volumes back to the instance mounting (or having previously mounted) them. Also, as described in initial comment, there are reasons other than cost allocation to want root volumes to be tagged.

It looks like it would be possible to include an additional `TagSpecification` of `ResourceTypeVolume` in the fleet request. Alternatively, I would suggest putting both `TagSpecification`s in the launch template instead. That would make it easier to determine (by looking at the launch template version) when an extant instance is out of date with respect to the tags specified in the `Provisioner` and thus should be deleted.

**Comment by ellistarn** [comment]
> It looks like it would be possible to include an additional TagSpecification of ResourceTypeVolume in the fleet request.

Awesome -- let's do it. I'm not sure I see the use case for diverging the tags on the instance and the volume attached to the instance. Perhaps we can use `spec.provider.tags`.

> when an extant instance is out of date with respect to the tags specified in the Provisioner and thus should be deleted

This is not the semantic of the provisioner. We're not a node group abstraction and don't reconcile this type of field. Doing so would be pretty disruptive and impactful to cluster capacity. Instead, we're built on an eventually consistent model, where nodes will converge to the current specification. This can be accelerated via expirationTTLs. If you want to build your own rollout orchestration on top of Karpenter, we're highly supportive of this and our finalizer enables easy integration for cordon/drain.

**Comment by ellistarn** [comment]
> Reconciling out-of-spec instances is https://github.com/aws/karpenter/issues/1018.

This is a pretty fundamental change to how Karpenter thinks about the world. I'm not saying no, but we'd need to think carefully through the edge cases, as I can imagine some side effects and unintended consequences. If you think this would be valuable for your use case, do you mind cutting an issue for reconciliation of nondisruptive parameters (e.g. labels/taints)? We can discuss further there.

**Comment by johngmyers** [comment]
Filed #1457 on node reconciliation.
