### ISSUE TITLE
Docs on Migrating from Cluster Autoscaler to Karpenter

### ISSUE THREAD

**Issue by bwagner5** [aws/karpenter#1431]
**Is an existing page relevant?**

N/A

**What karpenter features are relevant?**

 - Node Expiry
 - Instance Type Diversity
 - Spot Support

**How should the docs be improved?**
A page with general guidelines on migrating from Cluster Autoscaler to Karpenter. 

Here are some things that might be useful to include:
 - Collapsing and consolidating ASGs into Provisioner(s)
 - How to support Spot and OD w/ fallback to OD
 - How to upgrade AMIs
 - 
 - How transition from CA to Karpenter in a cluster where both are running. 
   Some Ideas:
   - Duplicate Deployments and use node selectors to select a particular provisioner using either the provisioner's name directly or a add a label to all the provisioners and select on that label. (deployments could also be updated w/ the node selector rather than duplicated).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Another idea: 
- Mark all CAS nodes as unschedulable, uninstall CAS, install Karpenter, drain all CAS nodes. Karpenter would bring up capacity for the pending pods and would respect PDBs without having to create more deployments.

**Comment by ellistarn** [comment]
It would be great to have automated testing for whatever strategy we recommend.

**Comment by rothgar** [comment]
Here's a general outline of content I think would make sense. Some of this would link to existing docs. Let me know what you think.

1. Migrating from CAS to Karpenter
- Deploy (and verify) Karpenter
- Configure a provisioner (limits, node restrictions, etc.)
- Verify Workload config (spread, disruption budgets, etc.)
- Disable CAS
- Drain [M]NG nodes
2. Additional considerations
- Kubernetes upgrades (including node AMIs)
- Node draining
- Node TTLs vs ASG max life
- Splitting workloads onto different request types (spot vs on-demand)
- Using custom AMIs and LTs
- Karpenter maintenance

**Comment by jicowan** [comment]
I think there needs be an option for both K and CA to co-exist, at least until you are ready to switch to K.

**Comment by njtran** [comment]
Closing as the Migration guide has been merged.
