### ISSUE TITLE
Support terminating nodes when pod density is too low

### ISSUE THREAD

**Issue by stevehipwell** [aws/karpenter#1491]
**Tell us about your request**
I'd like Karpenter to terminate (or request termination) of a node when it has a low density of pods and there is another node which could take the nodes.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Karpenter provisioned nodes will currently fragment as pods are terminated and the capacity isn't re-used; this is likely to happen after a scaling event is over and could cause a significant cost increase over the CA version.

**Are you currently working around this issue?**
n/a

**Additional context**
This is related to #1457 #1018 in as much as all three require Karpenter to terminate or request node termination.

**Attachments**
n/a

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by stevehipwell** [comment]
FYI @bwagner5.

**Comment by bwagner5** [comment]
also related: https://github.com/aws/karpenter/issues/1091

**Comment by ellistarn** [comment]
Can we add this as a comment to the defrag work?

**Comment by stevehipwell** [comment]
Would it be worth having a meta issue or something to track groups of issues like this? I think that #1495 is also related to these issues as changing the version would want the nodes to be terminated and replaced with the new version.
