### ISSUE TITLE
"Getting started with eksctl" CloudFormation Template does not exist

### ISSUE THREAD

**Issue by harshitpassi** [aws/karpenter#1492]
I'm trying to use Karpenter with eksctl, but the CloudFormation template I'm supposed to download according to the docs does not exist on the server.

`https://karpenter.sh/v0.6.5/getting-started/cloudformation.yaml` is the URL.

**Comment by bwagner5** [comment]
Thanks for reporting! And apologies on the poor experience with the getting started guide! It is fixed now!

**Comment by harshitpassi** [comment]
Thanks for the prompt response!

**Comment by xr1776** [comment]
broken again
