### ISSUE TITLE
Scope provisioner to only serve specified namespaces

### ISSUE THREAD

**Issue by robertd** [aws/karpenter#1493]
**Tell us about your request**
What do you want us to build?

We're playing around with setting up an OpenFaaS ([openfaas.io](https://www.openfaas.com/)) on top of an EKS cluster w/ Karpenter installed... so namespace-based provisioner "awareness" would be a nice addition.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

This would allow provisioners to only serve specific namespaces (1 to n) and create the underlying nodes for the incoming workloads.   

**Are you currently working around this issue?**
How are you currently solving this problem?
N/A

**Additional context**
Anything else we should know?
N/A

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

cc @ellistarn

**Comment by bwagner5** [comment]
Thanks for the feature request!

Curious on yours and others thoughts on adding the namespace as a field in the provisioner spec (seems a little dirty) vs creating a `NamedspacedProvisioner` CRD?  We definitely want to maintain the current semantic of a global provisioner.

**Comment by ellistarn** [comment]
@bwagner5 I think we need a NamespaceSelector, similar to pod affinity rules. I'd push back pretty hard about making provisioners namespaced, since they own nodes that are global. Even worse to have multiple CRs.

**Comment by robertd** [comment]
+1 for `NamespaceSelector`... Is it too much to ask if it can handle multiple namespaces at once (array of namespaces)? TIA
