### ISSUE TITLE
I am getting this error when deploy kafka => Ignoring pod, pod anti-affinity is not supported. But some kafka pod deployed.

### ISSUE THREAD

**Issue by burakhalefoglu** [aws/karpenter#1507]
my provisioner;
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec: 
  limits:
    resources:
      cpu: "1000"
      memory: 1000Gi
  requirements:
    - key: "node.kubernetes.io/instance-type" 
      operator: In
      values:  ["r5n.large","r5n.xlarge","r5n.2xlarge","r5n.4xlarge", "t3.large","t3.xlarge","t3.2xlarge","t3.4xlarge", "m5n.large","m5n.xlarge","m5n.2xlarge","m5n.4xlarge","c5n.xlarge","c5n.2xlarge","c5n.4xlarge"]
    - key: "topology.kubernetes.io/zone" 
      operator: In
      values: ["us-east-2a", "us-east-2b", "us-east-2c"]
    - key: "karpenter.sh/capacity-type" # Defaults to on-demand
      operator: In
      values: ["spot"] # ["spot", "on-demand"]
  provider:
    subnetSelector:
      karpenter.sh/discovery: xxx
    securityGroupSelector:
      karpenter.sh/discovery: xxx
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000

---
my cluster config ->

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: xxx
  region: us-east-2
  version: '1.21'
  tags:
    karpenter.sh/discovery: xxx
managedNodeGroups:
  - name: xxx
    desiredCapacity: 2
    labels:
      dedicated: spot
    volumeSize: 20
    amiFamily: AmazonLinux2
    minSize: 1
    maxSize: 20
    spot: true
    privateNetworking: true
    volumeEncrypted: true
    availabilityZones: ["us-east-2a","us-east-2b","us-east-2c"]
    instanceTypes: ["c5n.xlarge","c5n.2xlarge","c5n.4xlarge","r5n.xlarge","r5n.2xlarge","r5n.4xlarge","m5n.xlarge","m5n.2xlarge","m5n.4xlarge"]
    iam:
      withAddonPolicies:
        autoScaler: true
    ssh:
      allow: false

---
kafka: 
afka                  kafka-zookeeper-0                                             0/1     Pending             0          0s
kafka                  kafka-0                                                       0/1     Pending             0          0s
kafka                  kafka-1                                                       0/1     Pending             0          0s
kafka                  kafka-2                                                       0/1     Pending             0          0s
kafka                  kafka-2                                                       0/1     Pending             0          0s
kafka                  kafka-3                                                       0/1     Pending             0          0s
kafka                  kafka-3                                                       0/1     Pending             0          0s
kafka                  kafka-4                                                       0/1     Pending             0          0s
kafka                  kafka-4                                                       0/1     Pending             0          0s
kafka                  kafka-zookeeper-0                                             0/1     Pending             0          6s
kafka                  kafka-0                                                       0/1     Pending             0          6s
kafka                  kafka-zookeeper-0                                             0/1     ContainerCreating   0          6s
kafka                  kafka-0                                                       0/1     ContainerCreating   0          6s
kafka                  kafka-1                                                       0/1     Pending             0          6s
kafka                  kafka-1                                                       0/1     ContainerCreating   0          6s
logging                elasticsearch-master-2                                        0/1     Pending             0          20m
kafka                  kafka-1                                                       0/1     Running             0          26s
kafka                  kafka-1                                                       0/1     Error               0          36s
kafka                  kafka-1                                                       0/1     Running             1          37s
kafka                  kafka-zookeeper-0                                             0/1     Running             0          37s
kafka                  kafka-0                                                       0/1     Running             0          38s
kafka                  kafka-zookeeper-0                                             1/1     Running             0          46s
kafka                  kafka-1                                                       0/1     Error               1          47s
kafka                  kafka-0                                                       0/1     Error               0          47s
kafka                  kafka-0                                                       0/1     Running             1          48s
kafka                  kafka-0                                                       1/1     Running             1          56s
kafka                  kafka-1                                                       0/1     CrashLoopBackOff    1          56s
kafka                  kafka-1                                                       0/1     Running             2          57s
 kafka                  kafka-1                                                       1/1     Running             2          66s

kafka-0, kafka-1 is deployed but. kafka-2,-3,-4 stay pending. 

I have 2 node now.
ip-xx-xx-xx-xx.us-east-2.compute.internal   Ready    <none>   36m 
ip-xx-xx-xx-xx.us-east-2.compute.internal   Ready    <none>   36m   

## Version

**Karpenter**: v0.6.5

**Kubernetes**: v1.21.x

**Comment by dewjam** [comment]
Hey @burakhalefoglu ,
One thing to note about Karpenter is it will only add new nodes when pods are unable to be scheduled (in Pending state).  So if there is sufficient capacity in the cluster which meet a pods requirements, kube-scheduler will use those existing nodes first before Karpenter can take any action.  

In your case, I would imagine that kafka-0 and kafka-1 are being scheduled on the existing managed nodes.  But Karpenter is ignoring kafka-2 through kafka-5 because Pod ant-affinity is not currently supported (https://github.com/aws/karpenter/issues/942).

Can you run this command to confirm?
```
kubectl get pods -o wide -n <kafka_namespace>
```

Also, this may help us understand why pods are still pending.
```
kubectl describe pod <kafka_pod> -n <kafka_namespace>
```

**Comment by dewjam** [comment]
Hey @burakhalefoglu .  Any updates on this issue?  Anything else we can help with?

**Comment by dewjam** [comment]
Hey @burakhalefoglu .  I haven't heard back on this issue for a while now.  I'm going to go ahead and close it.  Feel free to reopen if you still have questions.

Thanks!
