### ISSUE TITLE
AWS resources created by Karpenter do not have default tags outlined in docs

### ISSUE THREAD

**Issue by dewjam** [aws/karpenter#1525]
**Is an existing page relevant?**

https://karpenter.sh/v0.7.1/aws/provisioning/#tags

**What karpenter features are relevant?**

Karpenter resource Tagging in AWS provider

**How should the docs be improved?**
According to Karpenter docs, all resources created by Karpenter should have some tags applied by default:
```
Name: karpenter.sh/cluster/<cluster-name>/provisioner/<provisioner-name>
karpenter.sh/cluster/<cluster-name>: owned
kubernetes.io/cluster/<cluster-name>: owned
```
In reality, resources created by Karpenter only have the following default tags per [the code](https://github.com/aws/karpenter/blob/main/pkg/cloudprovider/aws/apis/v1alpha1/tags.go#L31-L32):
```
karpenter.sh/provisioner-name: <provisioner-name>
Name: karpenter.sh/provisioner-name/<provisioner-name>
```

We should align on a default resource tagging strategy and make sure Karpenter docs are updated accordingly.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by chrisnegus** [comment]
@dewjam It looks like [PR #1553](https://github.com/aws/karpenter/pull/1553) closes this issue. If there is more to do, feel free to reopen.
