### ISSUE TITLE
Support another registry private credential

### ISSUE THREAD

**Issue by KqLLL** [aws/karpenter#1531]
**Tell us about your request**
Configure another(dockerhub, qury.io) private registry credential in kubelet. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We'll replace CA with karpenter, we need to config private registry credential in worker node(provision node).

**Are you currently working around this issue?**
Set kubelet/config.json on bootstrap.sh via [tf-eks-module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest)
Example:
```
pre_bootstrap_user_data = <<EOF
......
cat <<-BOOTSTRAP > /etc/profile.d/bootstrap.sh
cat >> /var/lib/kubelet/config.json << CONFIG
{
  auths: {
    "quay.io": {}
  }
}
CONFIG
EOF
```
**Additional context**
Support AL and Bottlerocket ami type.
**Attachments**
None

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by KqLLL** [comment]
On Bottlerocket
```
bootstrap_extra_args = <<-EOF
[settings.host-containers.admin]
enabled = false

[[settings.container-registry.credentials]]
registry = "quay.io"
auth = "xxxx"

EOF
```

**Comment by tzneal** [comment]
You can now use custom userdata to add any required credentials.
