### ISSUE TITLE
Add "allow-eviction" functionality 

### ISSUE THREAD

**Issue by 644755** [aws/karpenter#1532]
**Tell us about your request**

Just like the "karpenter.sh/do-not-evict" annotation, It would be useful to achieve the opposite and tell the controller to evict specific pods that aren't owned by a Daemonset if they are the only ones left running on a node. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I Had a use case of which I had to use  [Cluster-Proportional-Autoscaler](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler) to scale coreDNS replicas in proportion to cluster size. 
My implementation added a coreDNS replica with every node added to the cluster. I Couldn't use daemonset and had to scale using Replicaset, which caused Karpenter to not de-provision and not terminating nodes after they were no longer needed. 

**Are you currently working around this issue?**
For first aid I lowered the number of replicas to 1:3 instead of 1:1. I'm intending to try [Descheduler](https://github.com/kubernetes-sigs/descheduler) for this or in case it won't work out I'll write a job that will run every few minutes, locate and delete these pods. 

**Additional context**
Me and @hagzag would be happy to help and contribute with this, in case it's accepted. 

**Attachments**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
This is an interesting idea. We currently scale down nodes that are empty (have zero non-daemonset pods). This would essentially look like adding this as an additional annotation and changing how Karpenter considers a node empty [here](https://github.com/aws/karpenter/blob/main/pkg/controllers/node/emptiness.go#L50) by decrementing the count for each pod that has the `karpenter.sh/allow-eviction` or `karpenter.sh/consider-empty`.

**Comment by billrayburn** [comment]
Closing, #2847 and aws/karpenter-core#70 were released in v0.19.0.
