### ISSUE TITLE
Support snapshotId in BlockDeviceMappings of AWS provisioner

### ISSUE THREAD

**Issue by walkley** [aws/karpenter#1538]
**Tell us about your request**
Support defining snapshotId in BlockDeviceMappings in AWS provisioner.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
BlockDeviceMappings was introduced in v0.7.0(https://github.com/aws/karpenter/pull/1420), with this feature, we can define most of the [EBS related parameters](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_LaunchTemplateEbsBlockDevice.html) in the generated launch template, **except snapshotId**. The use case that I need the EBS snapshot is to pre-pull some big container images in the data volume in order to speed up the boot time of big pod, this request and the workaround has been discussed in https://github.com/bottlerocket-os/bottlerocket/issues/1128. 

**Are you currently working around this issue?**
The workaround is to use pre-built launch template in AWS provisioner.

**Additional context**
n/a

**Attachments**
n/a

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Thanks for the feature request! I wasn't sure how SnapshotId would be used which is why I had originally left it off, but the use-case you describe seems completely valid to me, so I see no issue with adding snapshotId.
