### ISSUE TITLE
Karpenter default provisioner selection

### ISSUE THREAD

**Issue by jsmith97** [aws/karpenter#1570]
version 0.7.2
I have either miss-understood the documentation or there is an issue with the way the default provisioner is implemented.

Expected behaviour:

I create a Provisioner named default and a Provisioner named burstable.
when a pod is created it is provisioned using the default Provisioner .

----

apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
  labels:
    app.kubernetes.io/name: default
    app.kubernetes.io/component: karpenter
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - m6i.large
        - m6i.xlarge
        - m6i.2xlarge
        - c6i.large
        - c6i.xlarge
        - c6i.2xlarge
        - r6i.large
        - r6i.xlarge
        - r6i.2xlarge
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
  limits:
    resources:
      cpu: 100
  provider:
    amiFamily: Bottlerocket
    subnetSelector:
      kubernetes.io/cluster/mycluster: "*"
    securityGroupSelector:
      kubernetes.io/cluster/mycluster: "*"
  ttlSecondsAfterEmpty: 300
  ttlSecondsUntilExpired: 1209600 # = 14 days

----

apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: burstable
  labels:
    app.kubernetes.io/name: burstable
    app.kubernetes.io/component: karpenter
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - t3.micro
        - t3.small
        - t3.medium
        - t3.large
        - t3.xlarge
        - t3.2xlarge
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
  limits:
    resources:
      cpu: 100
  provider:
    amiFamily: Bottlerocket
    subnetSelector:
      kubernetes.io/cluster/mycluster: "*"
    securityGroupSelector:
      kubernetes.io/cluster/mycluster: "*"
  ttlSecondsAfterEmpty: 300
  ttlSecondsUntilExpired: 1209600 # = 14 days

----

Observed behaviour:

When a pod is created it is provisioned by the burstable provisioner.

Thanks

**Comment by dewjam** [comment]
Hey @jsmith97 
Just to clarify, the Provisioner spec with name "default" is just an arbitrary name and not treated any differently when compared to other provisioners.  So, when Pod requirements and constraints match more than one Provisioner spec, Karpenter will sort them alphabetically and choose the first one.  In this case, it would be "burstable" per your

**Comment by jsmith97** [comment]
﻿Thanks for the clarification Jim thought I must have miss-understood the docs.

Regards

Ben Smith

**Comment by dewjam** [comment]
Ha, sorry I accidentally hit the "comment" button before I was ready.  Hopefully this comment makes more sense ^ ^.
