### ISSUE TITLE
Getting started with eksctl

### ISSUE THREAD

**Issue by karlmutch** [aws/karpenter#1593]
eksctl only supports karpenter up to version 0.6.x, the KARPENTER_VERSION in this documentation is too recent to work.  This page needs a note maybe ?

**Comment by StarpTech** [comment]
Hi, I just wanted an open an issue. Is it possible that the karpenter team keeps ekctl with a recent karpenter version up to date?
https://github.com/weaveworks/eksctl/issues/5023

@karlmutch you can select the 0.6.5 version in the dropdown of the website.

**Comment by suket22** [comment]
> eksctl only supports karpenter up to version 0.6.x, the KARPENTER_VERSION in this documentation is too recent to work. This page needs a note maybe ?

I think they're two different things. The `Getting started with eksctl` doc in our documentation is using eksctl to create your cluster, nodegroup, IRSA set up but then uses kubectl and helm to install Karpenter onto your cluster. 

IIUC, the [eksctl doc](https://eksctl.io/usage/eksctl-karpenter/) helps install eksctl onto an EKS cluster for you in addition to what our guide does. 

Like @StarpTech recommended though, you can look at our GettingStarted experience for [v0.6.5](https://karpenter.sh/v0.6.5/getting-started/getting-started-with-eksctl/), but I think a lot depends on how you intend on installing Karpenter.

**Comment by suket22** [comment]
I'm closing this out, let me know if there's more information I can provide.
