### ISSUE TITLE
Maintain eksctl support

### ISSUE THREAD

**Issue by StarpTech** [aws/karpenter#1596]
**Tell us about your request**

Hello, is it possible that the karpenter team keeps ekctl with a recent karpenter version up to date? The karpenter integration is really promising but at the same time, we would like to be up-to-date (second last minor). I think it would be the best fit if the karpenter team manage the integration.

https://github.com/weaveworks/eksctl/issues/5023

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by suket22** [comment]
Hello! Thanks for opening this request. 

> Hello, is it possible that the karpenter team keeps ekctl with a recent karpenter version up to date? 

I think the onus is on the eksctl maintainers to keep things up to date as has been discussed [in that repo](https://github.com/weaveworks/eksctl/issues/5023). It's not scalable for the Karpenter team to ensure that every tooling like eksctl / kOps / terraform are correctly configured to use the latest version of Karpenter. 


Over time we do intend on Karpenter being more stable and fewer breaking changes being introduced like 0.6.3, so it gets easier to reduce the minor version skew.
