### ISSUE TITLE
webhook "address is not allowed" when applying provisioners / patch configmap

### ISSUE THREAD

**Issue by devopsjnr** [aws/karpenter#1602]
## Version

**Karpenter**: v0.5.6

**Kubernetes**: v1.21.5

Installed Karpenter through terraform, both controller and webhook pods are running well. 
When I tried to apply my first provisioner I get: 

```
➜  ~ kubectl apply -f first-provisioner.yaml
Error from server (InternalError): error when creating "first-provisioner.yaml": Internal error occurred: failed calling webhook "defaulting.webhook.provisioners.karpenter.sh": Post "https://karpenter-webhook.karpenter.svc:443/default-resource?timeout=10s": Address is not allowed
```

Since log level is INFO by default, I tried changing to DEBUG but ended up with the same message: 

```
➜  ~ kubectl patch configmap config-logging -n karpenter --patch '{"data":{"loglevel.controller":"debug"}}'
Error from server (InternalError): Internal error occurred: failed calling webhook "validation.webhook.config.karpenter.sh": Post "https://karpenter-webhook.karpenter.svc:443/config-validation?timeout=10s": Address is not allowed
```

 
I followed [issue-1165](https://github.com/aws/karpenter/issues/1165), tried restarting the webhook pod, restarting whole Karpenter app, delete the secret and validated the security group. I can't even see log errors due to log level.

Any suggestion ?

**Comment by dewjam** [comment]
Hey @devopsjnr 
I noticed we haven't seen a reply for several days.  Did you happened to find the solution to your problem?  I'll keep this issue open for a couple more days then will close it out.

**Comment by dewjam** [comment]
I believe we just need port 8443 to be allowed from the APIServer security group to the Nodes which are running Karpenter.  I'm trying to test to be sure, though.

**Comment by devopsjnr** [comment]
@dewjam Can you please update after your test ?

**Comment by devopsjnr** [comment]
@dewjam Also, could you please explain to me the process from hitting `kubectl apply -f provisioner` command on my computer until it reaches the webhook? I'm not so sure I understand it all. And why should I open port 8443 if my error mentions port 443?
Thanks!

**Comment by dewjam** [comment]
Hey @devopsjnr ,
Can you give me some more details about your network configuration?  Are you using the VPC CNI plugin?  Are you using Network Policies?

Thanks!

**Comment by devopsjnr** [comment]
@dewjam Thank you for the very elaborated answer above. I just managed to solve the issue, needed to set `hostNetwork` to `true` as I'm using a custom CNI. We can close this, thanks again!

**Comment by devopsjnr** [comment]
@dewjam Hey following this thread could you please take a look on this one? https://github.com/aws/karpenter/issues/1666
Thanks!
