### ISSUE TITLE
Unable to hydrate the AWS launch template cache, RequestCanceled: request context canceled

### ISSUE THREAD

**Issue by shirish-qub** [aws/karpenter#1614]
## Version
**Karpenter**: v0.8.0
**Kubernetes**: v1.19.1

## Expected Behavior
Karpenter pod should start-up after helm install

## Actual Behavior
karpenter pod goes into CrashLoopBackOff

## Steps to Reproduce the Problem

1. create the IAM resources using AWS CloudFormation. using   "aws cloudformation deploy..."
2. access to instances using the profile to connect to the cluster . using "eksctl create iamidentitymapping ...."
3. Create the KarpenterController IAM Role.  using "eksctl create iamserviceaccount ...."
4. Install chart using helm

## Resource Specs and Logs

2022-04-01T02:45:30.313Z        INFO    Successfully created the logger.
2022-04-01T02:45:30.313Z        INFO    Logging level set to: debug
{"level":"info","ts":1648781130.418466,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
2022-04-01T02:45:30.418Z        INFO    controller      Initializing with version v0.8.0        {"commit": "476804d"}
2022-04-01T02:45:30.418Z        DEBUG   controller.aws  AWS region not configured, asking EC2 Instance Metadata Service {"commit": "476804d"}
2022-04-01T02:45:34.728Z        DEBUG   controller.aws  Using AWS region eu-west-1      {"commit": "476804d"}
2022-04-01T02:45:34.728Z        DEBUG   controller.aws  Discovered caBundle, length 1025        {"commit": "476804d"}
2022-04-01T02:45:34.728Z        DEBUG   controller.aws.launchtemplate   Hydrating the launch template cache with names matching "Karpenter-euw1-prod-*"       {"commit": "476804d"}
panic: Unable to hydrate the AWS launch template cache, RequestCanceled: request context canceled
caused by: context canceled

goroutine 1 [running]:
github.com/aws/karpenter/pkg/cloudprovider/aws.(*LaunchTemplateProvider).hydrateCache(0xc000104d20, {0x27db3b8, 0xc0005ca2d0})
        github.com/aws/karpenter/pkg/cloudprovider/aws/launchtemplate.go:229 +0x4f4
github.com/aws/karpenter/pkg/cloudprovider/aws.NewLaunchTemplateProvider({0x27db3b8, 0xc0005ca2d0}, {0x28afb58, 0xc0003195a8}, 0xc0006389a0, 0xc0003195e8, 0xc0005bdf40, 0xc00037db00)
        github.com/aws/karpenter/pkg/cloudprovider/aws/launchtemplate.go:70 +0x225
github.com/aws/karpenter/pkg/cloudprovider/aws.NewCloudProvider({0x27db3b8, 0xc0005ca2a0}, {0x1e0c260})
        github.com/aws/karpenter/pkg/cloudprovider/aws/cloudprovider.go:90 +0x5d3
github.com/aws/karpenter/pkg/cloudprovider/registry.newCloudProvider(...)
        github.com/aws/karpenter/pkg/cloudprovider/registry/aws.go:27
github.com/aws/karpenter/pkg/cloudprovider/registry.NewCloudProvider({0x27db3b8, 0xc0005ca2a0}, {0x0})
        github.com/aws/karpenter/pkg/cloudprovider/registry/register.go:25 +0x28
main.main()
        github.com/aws/karpenter/cmd/controller/main.go:80 +0x30c

## Extra Information :
I checked https://github.com/aws/karpenter/issues/1452 and checked the annotation on the "karpenter" sa and that seems correct. The annotation there corresponds to a role in the IAM and the role has the correct policy attached which has the permisisons including "ec2:DeleteLaunchTemplate" & "ec2:CreateLaunchTemplate".
For testing I added "ec2:*" to for checking and it still gave the same.

Thank you for you help !
Shirish

**Comment by suket22** [comment]
I've got 0.8.0 running on my cluster and I'm not seeing this. 

```
2022-04-01T02:45:34.728Z DEBUG controller.aws.launchtemplate Hydrating the launch template cache with names matching "Karpenter-euw1-prod-*" {"commit": "476804d"}
panic: Unable to hydrate the AWS launch template cache, RequestCanceled: request context canceled
caused by: context canceled
```

Do you see the calls in your account's CloudTrail? I wanted to confirm if you're seeing an access denied from the EC2 API or if the calls aren't reaching EC2 at all due to some networking configuration - (restrictive security groups / private subnets etc)

**Comment by ellistarn** [comment]
Shouldn't our logs be spitting out access denied? It seems like we might be squashing an error somewhere.

**Comment by suket22** [comment]
> Shouldn't our logs be spitting out access denied? It seems like we might be squashing an error somewhere.

I agree. I can't reproduce this on my side however which is why I wanted to know if the requests are even making it to EC2.

**Comment by shirish-qub** [comment]
Apologies, **the EKS is v1.17 rather than v1.19.**
I will try to get the cloudtrail logs. anything particular I should be looking for ?
I can also confirm I have an EKS v1.21 (karpenter installed via cluster yaml setting rather than the manual install I am facing in this issue). The v1.21 uses the same subnets and security groups as v1.17

**Comment by shirish-qub** [comment]
I have since upgraded my EKS cluster and have not faced this issue. so probably it was something in v1.17 that karpneter didn't like.
