### ISSUE TITLE
Add configuration of key-pair for AWS EC2 in provisioner

### ISSUE THREAD

**Issue by vumdao** [aws/karpenter#1619]
**Tell us about your request**
Configure key-pair for AWS EC2 in provisioner

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
If we use `Bottlerocket` AMI Family we must have key-pair to access the EC2 instance under `ec2-user` user, SSM agent in this case is just able to enable admin access only

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
I wonder if the Bottlerocket folks would be able to open up admin access via SSM.

**Comment by vumdao** [comment]
@ellistarn Nope, reference to https://aws.amazon.com/bottlerocket/faqs/

> How do I debug issues with Bottlerocket?

You can run an “admin container” using Bottlerocket's API (invoked via user data or AWS Systems Manager) and then log in with SSH for advanced debugging and troubleshooting with elevated privilages. AWS provides the admin container that allows you to install and use debugging tools like sosreport, traceroute, strace, tcpdump. The act of logging into an individual Bottlerocket instance is intended to be an infrequent operation for advanced debugging and troubleshooting.

**Comment by vumdao** [comment]
@bwagner5 I don't know why karpanter does no support add ssh key-pair to configuration, is there any background reason?

- As I said in previouse comment, using SSM with bottolerocket just support to enable admin access, that's all, we are not able to switch user ther 
- Using EC2 Instance Connect requires public IPv4 address which is most avoided in EKS cluster nodes.

**Comment by vumdao** [comment]
@bwagner5 Security aspect is belong to users, they should aware the risk to decide attach SSH keys to the EC2 not the tool to block an option, I think

Thanks for your help to show me `enter-admin-container` but it does not help much since we're still in chroot not full control at all
```
[root@admin]# systemctl status kubelet
Running in chroot, ignoring request.
```

**Comment by bwagner5** [comment]
@vumdao you need to drop into the actual root filesystem shell by running `sudo sheltie` 

```
$ enter-admin-container
$ sudo sheltie
$ systemctl status kubelet
● kubelet.service - Kubelet
     Loaded: loaded (/x86_64-bottlerocket-linux-gnu/sys-root/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─exec-start.conf
     Active: active (running) since Mon 2022-04-11 18:38:35 UTC; 6min ago
       Docs: https://github.com/kubernetes/kubernetes
   Main PID: 6176 (kubelet)
      Tasks: 54 (limit: 629145)
     Memory: 258.1M
        CPU: 37.266s
     CGroup: /runtime.slice/kubelet.service
...
```

**Comment by renxunsaky** [comment]
Hi @ellistarn @bwagner5 @vumdao,

I just get a chance to read through your questions/responses.

I am agree it's more secure and a good way to use SSM session to connect to a node if it is necessary.

How you do think my arguments below ?
1. Karpenter supports only AWS for the moment, but according to the documentation, it seems that we want to support also the other cloud providers if people contributes on it. Here, with your suggestion, it is more a provider-specific option. It is not extensible or flexible for the futur multi-cloud supporting purpose.
2. As a product, we'd better leave the choices to the users, instead of making the decision for them. At least we provide the option for them to add the SSH key pair. But suggest them to not do that if not really necessary. If they do that, they should be aware of the danger and should take their responsibility for the security of their own infrastructure.
3. As an admin, I find it also fast and convenient to use command line to SSH into different nodes within 2 seconds. While, with SSM session, it may take longer time and should do more clicks. In addition, with SSH, we could take advantage of our own featured terminals.


Thanks.

**Comment by Sathyam-Unicommerce** [comment]
Yes, please provide feature to add key-pair. Like us some organisations have LDAP based authentications for users. So it should be an option to add keys.

**Comment by ellistarn** [comment]
We've documented a method to configure ssh-keys here: https://karpenter.sh/v0.17.0/faq/#can-i-add-ssh-keys-to-a-provisioner

**Comment by lnehrin** [comment]
> We've documented a method to configure ssh-keys here: https://karpenter.sh/v0.17.0/faq/#can-i-add-ssh-keys-to-a-provisioner

That page no longer exists when I click the link.  Did it move? (and is it still relevant?)

**Comment by ellistarn** [comment]
Here's a permalink: https://karpenter.sh/docs/faq/#can-i-add-ssh-keys-to-a-provisioner

**Comment by yogeek** [comment]
@ellistarn I am currently migrating from cluster-autoscaler (where I specified an AWS key pair in the launch template to be able to SSH into my nodes with an SSH key provisioned in AWS by infra-as-code) to karpenter and I just found out this thread.

The documentation you refer to is helping to put a key directly in the user-data but it is not helping in specifying an AWS key-pair as we can do when launching an EC2 instance in the console or like I said above in a launch template.

In our case, our cluster is not an EKS one (we deployed it on EC2 instances with specific user-data that contains the kubeadm logic) and we use a custom AMI (based on a CIS AMI from AWS marketplace for security reason).

We do not want to use ec2-instance-connect for now.

In addition to benefit from the great features of karpenter, we would like to keep the same user experience as before. 

And I may add that I quite agree with @vumdao  : karpenter is an autoscaling tool, even if it can come with best practices by default, decision about security details should belong to the users in the end, and karpenter should allow all basic features provided by EC2 like attaching an SSH key pair.

Is it possible to reopen this issue please ?

**Comment by ArieLevs** [comment]
+1 for @yogeek 

up until now i've been using `Provisioner` and refer a aws launch template were i could set [aws key pair name](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#key_name).  
while trying to migrate to 0.32.x version, found out its no longer possible (had to debug why nodes will not connect to cluster),  
connecting to an instance is a very rare event for me, but when its needed something really bad probably happened, please respect AWS EC2 api and let us decide how to connect to instances (personally i cannot even use SSM due to SSM not configured in the custom enterprise AMI i use) for now its a big blocker for upgrading karpenter, and a potential product drop if not added.

**Comment by bwagner5** [comment]
Are you able to use ec2-instance-connect instead of SSM for SSH access? https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connect-linux-inst-eic.html

**Comment by jonathan-innis** [comment]
Related to https://github.com/aws/karpenter/issues/2432

**Comment by ArieLevs** [comment]
> Are you able to use ec2-instance-connect instead of SSM for SSH access? https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connect-linux-inst-eic.html

had to extend our AMI to be able to use SSM (didn't wanted to deal with VPC endpoints to get the ec2-instance-connent working)

not related to the issue, but if anyone facing nodes not connecting to cluster api, check your aws-auth configmap 🤦‍♂️  
was able to continue with the 0.32.x upgrade, but i still think that SSH should stay an option.

**Comment by blame19** [comment]
Can we reopen this?
While i can use EC2 Instance Connect, I have clusters were I don't manage (and i don't want to manage) an additional endpoint.

The userdata option doesn't seem to work properly and it's overly complicated, since this should be an AWS basic feature.

**Comment by duxing** [comment]
any chance we can reopen this issue? 

I agree with the benefits of promoting SSM/EC2 instance connect. If `karpenter` `EC2NodeClass` can provide better parity with launch template, it would reduce the friction for more people to adopt `karpenter`.

Note that SSM / EC2 instance connect are both vendor-specific and this may be less preferred compared to SSH.

**Comment by saireddyb** [comment]
How to give keypair configuration in karpenter EC2NodeClass ?
So that I can ssh in to the ec2's

**Comment by renaudhager** [comment]
> @vumdao EC2 Instance Connect is able to SSH to instances with a private IP address: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Connect-using-EC2-Instance-Connect.html#:~:text=private%20IP%20addresses
> 
> We have avoided adding the key-pair to the provisioner to limit long-term SSH keys being placed on instances. We think that using SSM or EC2 Instance Connect for SSH access is a more secure way of accessing nodes.
> 
> You can gain root access to the bottlerocket host through the admin container. There is no direct way to SSH to a bottlerocket host without the admin container.
> 
> Here are the steps:
> 
> 1. Login to bottlerocket w/ ssm `aws ssm start-session --instance-id <instance-id>`
> 2. Once connected, on the prompt, type: `enter-admin-container`
> 3. Once inside the admin container, you can execute `sudo sheltie`
> 
> From the admin container's MOTD:
> 
> ```
>          Welcome to Bottlerocket's admin container!
>     ╱╲
>    ╱┄┄╲   This container provides access to the Bottlerocket host
>    │▗▖│   filesystems (see /.bottlerocket/rootfs) and contains common
>   ╱│  │╲  tools for inspection and troubleshooting.  It is based on
>   │╰╮╭╯│  Amazon Linux 2, and most things are in the same places you
>     ╹╹    would find them on an AL2 host.
> 
> To permit more intrusive troubleshooting, including actions that mutate the
> running state of the Bottlerocket host, we provide a tool called "sheltie"
> (`sudo sheltie`).  When run, this tool drops you into a root shell in the
> Bottlerocket host's root filesystem.
> ```
> 
> Hope this helps!

IMO, this is not a reasonable choice. People should be able choose whether to configure a key pair. 

In many situations, we need to access the host. Any solution that depends on a running container assumes that the kubelet is up and running. However, if there is any issue preventing a node from joining a cluster, these solutions become useless.

The other solutions mentioned are vendor-specific and require a certain amount of configuration.

SSH has been a standard for a decade. Any infrastructure provider provides an easy way to configure an SSH-key pair. AWS, in this case, allows it very easily.

It makes no sense to me, to not allow people to configure a key pair either at the node pool or node class level.

**Comment by dsoprea** [comment]
In our situation, we're trying to reproduce reoccurring EC2 host issues in a private subnet. Your security posture and your decision to impose them on us has been a nuisance, to say the least.

"We think that using SSM or EC2 Instance Connect for SSH access is a more secure way of accessing nodes."

We didn't ask. Can you just stay in your lane with the autoscaling? It's unclear why you'd think this interference was appropriate.

**Comment by lnehrin** [comment]
Clearly you can chose to view the better security as a nuisance, but it
would seem you have 3 options:
1. Look at the changes required to embrace the SSM Instance connect.
2. Offer to help add ssh features to the code.
3. Find a different solution.

I was initally fruatrated, but chose option 1, and happily carried the same
technique to ansible configuration of EC2 nodes on a different project -
avoiding the hassle of handling ssh keys.  My point is that one can yell at
the sky or find a silver lining on a problem.
