### ISSUE TITLE
Failed to find instance type option (g4dn.2xlarge)

### ISSUE THREAD

**Issue by sagi-shimoni** [aws/karpenter#1621]
## Version

**Karpenter**: v0.5.3

**Kubernetes**: v1.21.5

## Expected Behavior

I created a provisioner with instance type "g4dn.2xlarge" and taint "gpu-worker" (both spot and on-demand)
I'm expecting to deploy pods with toleration "gpu-worker" and pods should be running on a "g4dn.2xlarge" node.

## Actual Behavior

I confirmed that this instance type is available on the region, but karpenter does not spin up a node. 

## Steps to Reproduce the Problem

Create a provisioner with instance types "g4dn.2xlarge" 

## Resource Specs and Logs

2022-04-04T13:39:13.718Z	ERROR	controller.provisioning	Failed to find instance type option(s) for [testing-us-east-2/testing-us-east-2-master-mastermind-2]	{"commit": "5047f3c", "provisioner": "gpu-worker"}

**Comment by tzneal** [comment]
Can you upgrade to the latest version v0.8.0 and see if the issue still exists?  The helm chart format changed somewhat between v0.5.3 and v0.8.0, there is some additional information about the changes at [here](https://karpenter.sh/v0.8.0/upgrade-guide/#upgrading-to-v062)

**Comment by suket22** [comment]
Could you provide us your provisionerSpec and enable debug logs on the Karpenter controller?

**Comment by sagi-shimoni** [comment]
> Can you upgrade to the latest version v0.8.0 and see if the issue still exists? The helm chart format changed somewhat between v0.5.3 and v0.8.0, there is some additional information about the changes at [here](https://karpenter.sh/v0.8.0/upgrade-guide/#upgrading-to-v062)

issue was resolved in v0.8.0
thank you!
