### ISSUE TITLE
Documentation: change URL for the latest version to use "latest" instead of the version number

### ISSUE THREAD

**Issue by jicowan** [aws/karpenter#1622]
For example: 
Change `https://karpenter.sh/v0.8.0/` to `https://karpenter.sh/latest`

**Comment by jicowan** [comment]
or redirect URLs to `latest` to the latest version number.

**Comment by bwagner5** [comment]
I could potentially see us redirecting /latest to the latest released version. But I do like the current approach of sharing a specific docs page as a permalink. Using /latest can cause broken links when posted to blogs or other more static mediums.

**Comment by pjlewisuk** [comment]
Or just don't retire old docs versions so quickly?

**Comment by bwagner5** [comment]
@pjlewisuk What do you mean?  The docs weren't retired, the structure changed between the latest version and the version the workshop uses. The `/docs` that was being used before that PR would be the same functionality as `/latest` suggested in this issue. Pinning workshops to a specific version probably makes sense anyways.

**Comment by pjlewisuk** [comment]
@bwagner5 I originally came across this issue via a PR on EKS workshop (https://github.com/aws-samples/eks-workshop/pull/1370), which states that links to older versions of the docs in the workshop (e.g. https://karpenter.sh/v0.4.3-docs/) no longer work. 

As you said, it would probably make sense to pin the workshop to a particular version, but we’d need to be confident that the version would stay around for a long time.

**Comment by njtran** [comment]
>  but we’d need to be confident that the version would stay around for a long time.

We shouldn't be retiring the old docs at all. You're right that the format for the url for `v0.4.3` changed. As. I remember, we changed this a while ago, but we've been sticking to the pattern since then, so you shouldn't have problems with referring to pinning a version now.

**Comment by jonathan-innis** [comment]
Can this be closed or is this proposal still actively something that we are considering?

**Comment by jicowan** [comment]
It can be closed.
________________________________
