### ISSUE TITLE
Unable to install karpenter using terraform EKS Module v18.19.0  

### ISSUE THREAD

**Issue by sriram0721** [aws/karpenter#1635]
##Version
eks 1.21
Terraform eks module - 18.19.0

We are trying to install karpenter on eks which is provisioned through terraform aws eks module (18.19.0) . As per karpenter docs, it states eks version to be <18 . When i tried to install it on my cluster, i faced an error 

│   12:   role = module.eks.worker_iam_role_name
│     ├────────────────
│     │ module.eks is a object, known only after apply
│
│ This object does not have an attribute named "worker_iam_role_name".

When i referenced with tf docs, there is no output as "worker_iam_role_name" for version 18+ .
Do i need to use older eks module versions or is there any work around for this ?

**Comment by pratikbin** [comment]
@sriram0721  you can use this mine tf which is new, the one in docs are using deprecated modules.

https://github.com/aws/karpenter/issues/1634

**Comment by sriram0721** [comment]
hey thanks for that it worked!. btw, when i try to test it out by scaling a deployment, it does provisions the node. However, the node is not getting attached to the cluster. its in not ready state because of some taints. Any idea on this @pratikbin ?

**Comment by bwagner5** [comment]
We should probably update our docs to use v18 of the EKS Terraform module.

**Comment by bryantbiggs** [comment]
https://github.com/aws/karpenter/pull/1332 just merged and should resolve this

**Comment by sriram0721** [comment]
cool!. we can close this 👯
