### ISSUE TITLE
karpenter.sh/discovery tag on an EKS cluster -- what is it for?

### ISSUE THREAD

**Issue by victor10x** [aws/karpenter#1636]
**Is an existing page relevant?**
https://karpenter.sh/v0.8.1/getting-started/getting-started-with-terraform/

**What karpenter features are relevant?**
unsure

**How should the docs be improved?**
Can you address what the function of this code block does?
```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
...
  tags = {
    "karpenter.sh/discovery" = var.cluster_name
  }
```

I realize that `subnetSelector` and `securityGroupSelector` are meaningful in the provisioner such that the values must match the respective AWS resources for those selectors. However, I am unsure how Karpenter is affected if the value of the EKS tag `karpenter.sh/discovery` does _not_ match the cluster name.

Thank you!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
This doc may shed some more light on the selector fields in the AWS Cloud Provider: https://karpenter.sh/v0.8.1/aws/provisioning/#subnetselector 

It's not required that you use the cluster name as the tag's value. It's also not required to use the `karpenter.sh/discovery` tag key. We use that just to make our documentation consistent and unique. You will need to ensure that whatever tagging scheme you're using on your resources doesn't cause Karpenter to selector subnets or security groups of multiple VPCs or clusters.

**Comment by victor10x** [comment]
Hi @bwagner5 ,

Thank you so much for your response. I think I need to clarify in that I am asking about the function of the tag on the EKS cluster itself, not the tags on the subnets nor the security groups. Perhaps I am dense so apologies if I am misunderstanding the relationship here.

Thank you!

**Comment by bwagner5** [comment]
The tag has no affect on the EKS cluster itself. It's specified in the EKS Terraform module so that resources created by that module get that tag, but it doesn't matter if the cluster has the tag or not, just the subnets and security groups.

**Comment by victor10x** [comment]
Okay awesome — thank you for confirming my suspicion. Can I make a small suggestion then to remove that segment from the eksctl and terraform getting started docs, or make the tag name something else so that it doesn't share the same name as the provisioner tags? Thanks again!

**Comment by bwagner5** [comment]
Well the tag is still required for the eksctl and terraform module runs and is required to be the same as in the Provisioner spec for securityGroupSelector and subnetSelector. Since eksctl creates the subnets, you need to pass eksctl the tag to add to the subnets so that the provisioner can use the same tag to select the ones created by eksctl.

**Comment by victor10x** [comment]
Sorry, I just also noticed that `cluster_security_group_tags` isn't in the version of the EKS module you're currently specifying (`<18`). In finally reading the actual description of what `tag` does I see it's equivalent. I made the faulty assumption that `tag` only applied to the cluster only. Thanks again for all your responses.

**Comment by tyu0912** [comment]
Thanks for making this clear @bwagner5 . Fwiw, I feel like making it clear that `karpenter.sh/discovery` is just a tag key would be helpful. My first thought seeing an extension of `.sh` was that they key would be used to trigger a shell script somehow.
