### ISSUE TITLE
Not authorized to perform sts:AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by devopsjnr** [aws/karpenter#1666]
Karpenter version: 0.5.6
EKS version: 1.21.5

I installed Karpenter on another cluster and although I defined all roles and policies, I still get the following error:

```
2022-04-12T16:42:31.413Z	ERROR	controller.controller.provisioning	Reconciler error
"commit": "2346ed5", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner",
"name": "test-provisioner", "namespace": "",
"error": "fetching instance types using ec2.DescribeInstanceTypes,
WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: a88c1c3c-e52e-4a72-9baa"}
```

`defaultInstanceProfile` is an IAM Role that contains the following policies:

1. AmazonEKSWorkerNodePolicy
2. AmazonEC2ContainerRegistryReadOnly
3. AmazonSSMManagedInstanceCore
4. AmazonEKS_CNI_Policy
5. A policy called "karpenter" contains the following:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances",
                "ec2:RunInstances",
                "ec2:CreateFleet"
            ],
            "Resource": [
                "arn:aws:ec2:*:xxxxxxx:security-group/*",
                "arn:aws:ec2:*:xxxxxxx:instance/*",
                "arn:aws:ec2:*:xxxxxxx:network-interface/*",
                "arn:aws:ec2:*:xxxxxxx:volume/*",
                "arn:aws:ec2:*:xxxxxxx:subnet/*",
                "arn:aws:ec2:*:xxxxxxx:fleet/*",
                "arn:aws:ec2:*::image/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceTypeOfferings",
                "ec2:DescribeAvailabilityZones",
                "ec2:DescribeLaunchTemplates",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeSubnets",
                "ec2:DescribeSecurityGroups"
            ],
            "Resource": "*"
        }
    ]
}
```
`defaultInstanceProfile` role's Trust Policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "EKSWorkerAssumeRole",
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

I would also like to you Karpenter service account:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxx:role/KubernetesServiceAccount_karpenter
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: karpenter
  creationTimestamp: "2022-04-12T10:30:23Z"
  labels:
    app.kubernetes.io/component: karpenter
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/part-of: karpenter
    app.kubernetes.io/version: 0.5.6
    helm.sh/chart: karpenter-0.5.6
  name: karpenter
  namespace: karpenter
  resourceVersion: "456453035"
  uid: ec2fe4b1-0cbf-434b-bec8
secrets:
- name: karpenter-token-lgrbc
```

`KubernetesServiceAccount_karpenter` Role has the following policy named `karpenter-controller`:
```
{
    "Statement": [
        {
            "Action": [
                "ec2:CreateLaunchTemplate",
                "ec2:CreateFleet",
                "ec2:RunInstances",
                "ec2:CreateTags",
                "iam:PassRole",
                "ec2:TerminateInstances",
                "ec2:DescribeLaunchTemplates",
                "ec2:DescribeInstances",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeSubnets",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeInstanceTypeOfferings",
                "ec2:DescribeAvailabilityZones",
                "ssm:GetParameter"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ],
    "Version": "2012-10-17"
}
```

Also `KubernetesServiceAccount_karpenter` Role has the following Trust Relationship:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::xxxxxxx:oidc-provider/oidc.eks.xxxxxxx.amazonaws.com/id/xxxxxxx"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "arn:aws:iam::xxxxxxx:oidc-provider/oidc.eks.xxxxxxx.amazonaws.com/id/xxxxxxx:sub": "system:serviceaccount:karpenter:karpenter"
                }
            }
        }
    ]
}

```

Last thing I would like to share is the provisioner:

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: test-provisioner
spec:
  limits:
    resources:
      cpu: 1000
  provider:
    subnetSelector: 
      Name: private-eks-xxxxxxx
    securityGroupSelector: 
      aws:eks:cluster-name: my-cluster
  ttlSecondsAfterEmpty: 600
```

To me it looks like I set up everything properly. Hence I don't see a reason for the error I shared above.
If there are more information that you want me to share please let me know.
Thanks in advance!

**Comment by njtran** [comment]
Hey @devopsjnr! Did you create the `KubernetesServiceAccount_karpenter` role? The policy trust relationship should include `ec2.amazonaws.com` like in `defaultInstanceProfile` since `ec2.amazonaws.com` is making the call as you can see in the logs. Can you let me know if that works?

**Comment by devopsjnr** [comment]
@njtran Hey, I don't think that it is related. For a reference in my other cluster I have the same configuration (without `ec2.amazonaws.com` in `KubernetesServiceAccount_karpenter`) and it works.. 
Also I did not see it was mentioned in the documentation.

**Comment by njtran** [comment]
Got it. I'll reproduce your configs right now and see if it works for me.

**Comment by devopsjnr** [comment]
Found it! Apparently the `StringLike` should not contain the arn part, so instead of 
```
"arn:aws:iam::xxxxxxx:oidc-provider/oidc.eks.xxxxxxx.amazonaws.com/id/xxxxxxx:sub": "system:serviceaccount:karpenter:karpenter
"
```
It should be 
```
oidc.eks.xxxxxxx.amazonaws.com/id/xxxxxxx:sub: "system:serviceaccount:karpenter:karpenter
```

**Comment by yalattas** [comment]
I am following exactly the same and still facing issue. Even tried to add `AdministratorAccess` to the policy and still getting the same error.

I think controller couldn't assume the role even though role is already attached to EC2s. Everything done by terraform.

```
{"level":"FATAL","time":"2024-01-04T20:42:05.150Z","logger":"controller","message":"Checking EC2 API connectivity, WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: 97ec51e8-f5f8-4aee-bb04-e08f323ebc8a","commit":"2dd7fdc"}
```
Appreciate your help

**Comment by lemonScaletech** [comment]
@yalattas did you resolved the issue ? I have same problem, even after providing AdministratorAccess I am facing this error.

**Comment by yalattas** [comment]
Yes I did, problem relies with `Trust Relationship`

I have 2 conditions in `Trust Relationship` which means both must be met. and wasn't set correctly.

I used terraform. Here is my updated code
```
data "aws_iam_policy_document" "karpenter_controller_assume_role_policy" {
    statement {
        sid = "AllowKarpenterToAssumeRole"
        actions = ["sts:AssumeRoleWithWebIdentity"]
        effect  = "Allow"

        condition {
            test     = "StringEquals"
            variable = "${replace(aws_iam_openid_connect_provider.eks_cluster.url, "https://", "")}:sub"
            values   = ["system:serviceaccount:karpenter:karpenter"]
        }
        condition {
            test     = "StringEquals"
            variable = "${replace(aws_iam_openid_connect_provider.eks_cluster.url, "https://", "")}:aud"
            values   = ["sts.amazonaws.com"]
        }

        principals {
            identifiers = [aws_iam_openid_connect_provider.eks_cluster.arn]
            type        = "Federated"
        }
    }
    statement {
        sid = "AllowKarpenterEC2sToJoinCluster"
        actions = ["sts:AssumeRole"]
        effect = "Allow"
        principals {
            type = "Service"
            identifiers = ["ec2.amazonaws.com"]
        }
    }
}

```

Can you provide the trust relationship in your role to compare ?

**Comment by mmouselli** [comment]
> Yes I did, problem relies with `Trust Relationship`
> 
> I have 2 conditions in `Trust Relationship` which means both must be met. and wasn't set correctly.
> 
> I used terraform. Here is my updated code
> 
> ```
> data "aws_iam_policy_document" "karpenter_controller_assume_role_policy" {
>     statement {
>         sid = "AllowKarpenterToAssumeRole"
>         actions = ["sts:AssumeRoleWithWebIdentity"]
>         effect  = "Allow"
> 
>         condition {
>             test     = "StringEquals"
>             variable = "${replace(aws_iam_openid_connect_provider.eks_cluster.url, "https://", "")}:sub"
>             values   = ["system:serviceaccount:karpenter:karpenter"]
>         }
>         condition {
>             test     = "StringEquals"
>             variable = "${replace(aws_iam_openid_connect_provider.eks_cluster.url, "https://", "")}:aud"
>             values   = ["sts.amazonaws.com"]
>         }
> 
>         principals {
>             identifiers = [aws_iam_openid_connect_provider.eks_cluster.arn]
>             type        = "Federated"
>         }
>     }
>     statement {
>         sid = "AllowKarpenterEC2sToJoinCluster"
>         actions = ["sts:AssumeRole"]
>         effect = "Allow"
>         principals {
>             type = "Service"
>             identifiers = ["ec2.amazonaws.com"]
>         }
>     }
> }
> ```
> 
> Can you provide the trust relationship in your role to compare ?

Please use `enable_irsa` input flag, you don't have to handle this permission on your own.
https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/karpenter#input_enable_irsa

**Comment by storyalex** [comment]
Sorry for writing in an old thread...

The solution for me was to update the trust policy of the role I was trying to assume in the pod with the correct Principal -> Federated to the correct oidc-provider for that cluster. I was trying to reuse a role from another cluster.

**Comment by GustavooLucio** [comment]
in my case I deployed karpenter on kube-system, but on karpenter terraform module I was using 
`irsa_namespace_service_accounts = ["karpenter:karpenter"]` 
changed namespace to **kube-system** and then  it was fixed:
`irsa_namespace_service_accounts = ["kube-system:karpenter"]`
