### ISSUE TITLE
Provisioner volume modifications not picked up by karpenter controller 

### ISSUE THREAD

**Issue by noyoshi** [aws/karpenter#1669]
## Version

**Karpenter**: v0.8.1

**Kubernetes**: v1.20.15-eks-0d102a7

## Expected Behavior

Modifying the provisioner will be all that is needed for controller to get updated provisioner configs. 

## Actual Behavior

Controller seems to ignore updated provisioner. 

1. Created provisioner, and deployed controller
2. Modified the provisioner, specifically, added a section in `spec.provider.blockDeviceMappings` 
3. Noted that new nodes were not being created with the volumes configured in the provisioner
4. Checked to make sure provisioner had updated config, it did (`kubectl describe provisioner default`)
5. Deleted the controller pod, when it got re-created, it started behaving like it should (would do the volume mounting on subsequent nodes joining the cluster)

## Steps to Reproduce the Problem

Try the steps detailed above. 

## Resource Specs and Logs

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  # If omitted, the feature is disabled and nodes will never expire.  If set to less time than it requires for a node
  # to become ready, the node may expire before any pods successfully start.
  ttlSecondsUntilExpired: 2592000 # 30 Days = 60 * 60 * 24 * 30 Seconds;

  # If omitted, the feature is disabled, nodes will never scale down due to low utilization
  ttlSecondsAfterEmpty: 30

  # Provisioned nodes will have these taints
  # Taints may prevent pods from scheduling if they are not tolerated
  # taints:
  #   - key: example.com/special-taint
  #     effect: NoSchedule

  # Labels are arbitrary key-values that are applied to all nodes

  # Requirements that constrain the parameters of provisioned nodes.
  # These requirements are combined with pod.spec.affinity.nodeAffinity rules.
  # Operators { In, NotIn } are supported to enable including or excluding values
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m5.large", "m5.2xlarge", "p3.8xlarge", "p3.16xlarge", "m5.4xlarge", "m5.8xlarge", "m5.16xlarge"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["on-demand"]

  # Karpenter provides the ability to specify a few additional Kubelet args.
  # These are all optional and provide support for additional customization and use cases.
  # kubeletConfiguration:
  #   clusterDNS: ["10.0.1.100"]

  # Resource limits constrain the total size of the cluster.
  # Limits prevent Karpenter from creating new instances once the limit is exceeded.
  # limits:
  #   resources:
  #     cpu: "1000"
  #     memory: 1000Gi

  # These fields vary per cloud provider, see your cloud provider specific documentation
  provider:
    subnetSelector: 
      eksctl.cluster.k8s.io/v1alpha1/cluster-name: ":)
      Name: "*Public*"
    securityGroupSelector:
      Name: :)
    amiFamily: Bottlerocket
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          volumeSize: 100Gi
          volumeType: gp3
          iops: 10000
          encrypted: true
          kmsKeyID: ":)"
          deleteOnTermination: true
          throughput: 125
      - deviceName: /dev/xvdb
        ebs:
          volumeSize: 600Gi
          volumeType: gp3
          iops: 10000
          encrypted: true
          kmsKeyID: ":)"
          deleteOnTermination: true
          throughput: 125
```

**Comment by njtran** [comment]
Hey @noyoshi, can you elaborate on how you scaled up pods to get Karpenter to scale up? Could you share your deployment?

> Noted that new nodes were not being created with the volumes configured in the provisioner

Can you elaborate here? Were no nodes created at all? Or were nodes created without the configurations you defined?

> Deleted the controller pod, when it got re-created, it started behaving like it should (would do the volume mounting on subsequent nodes joining the cluster)

Did you delete the pod to essentially re-register the provisioner? Are you saying that the Karpenter controller may not have registered the change in the ProvisionerSpec in the form of nodes that were brought up after the change in Spec?

**Comment by njtran** [comment]
Just tried this out with your Provisioner and got some unexpected behavior in v0.8.2.
- Create Provisioner with BlockDeviceMappings
- Create Node with correct volumes
- Change Provisioner BlockDeviceMappings IOPS values
- Create Node and see the value not changed

After trying it at HEAD with commit https://github.com/aws/karpenter/pull/1673 and saw the value change with the same process. This should be fixed now, and should be fixed in the next release.
