### ISSUE TITLE
Conflicting information on docs

### ISSUE THREAD

**Issue by kreempuff** [aws/karpenter#1679]
**Is an existing page relevant?**

The docs on the [getting started page](https://github.com/aws/karpenter/blob/b1e93d3414de5fb86402425e00bf036654da4a6c/website/content/en/v0.8.2/getting-started/getting-started-with-eksctl/_index.md?plain=1#L68) mention that the controller _discovers_ a default instance profile name with a given format:

```
Karpenter discovers the InstanceProfile using the name KarpenterNodeRole-${ClusterName}.
```
But on the [provider specific page for AWS](https://github.com/aws/karpenter/blob/b1e93d3414de5fb86402425e00bf036654da4a6c/website/content/en/v0.8.2/AWS/provisioning.md?plain=1#L13-L16), it mentions provisioning will fail if you do not specify the instance profile name:

```
A default profile may be specified on the controller, allowing it to be omitted here. If not specified as either a default or on the controller, node provisioning will fail.
```

It seems that the provider specific page is correct:

```
ERROR	controller.provisioning	Launching node, creating cloud provider machine, getting launch template configs, getting launch templates, neither spec.provider.instanceProfile nor --aws-default-instance-profile is specified	{"commit": "c115db3", "provisioner": "default"}
``` 

**What karpenter features are relevant?**

**How should the docs be improved?**
Align on the configuration between docs or reference the source of truth

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by billrayburn** [comment]
Closing old issue.
