### ISSUE TITLE
Expose Batch Window & Idle Time as Configurable Options

### ISSUE THREAD

**Issue by tzneal** [aws/karpenter#1690]
**Tell us about your request**

I would like to expose the batch window and idle time as configurable options for Karpenter, or perhaps to expose less implementation details some other equivalent parameter e.g. a scale speed preference in the range [0,100] where 0 launches nodes instantly and 100 launches slowly but allows for longer batching?

This wouldn't really work as a provisioner specific parameter because of some other upcoming changes, so maybe as a config map entry?

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Customers may have varying use cases with respect to node provisioning.  Some may prefer getting workloads as quickly as possible at the cost of launching more nodes, while others may prefer to trade delayed startup in exchange for launching fewer but larger nodes.    In-Flight node awareness will help somewhat, but there are still cases where if Karpenter had waited a few more seconds for more pods it could have launched a single larger node.

The underlying cause is that pods arrive at different rates depending on if they are being scaled up from a deployment, in which case they are limited by the QPS of the kube-controller-manager or if they are launched from some other system where they may arrive a few seconds apart.  Through testing it also appears that notice these pods through reconciliation and our cached reader at a somewhat variable rate.  

**Are you currently working around this issue?**
There isn't a current ability to tweak batching depending on specific workloads.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
I think the idle and max timeout is more intuitive to expose rather than normalizing those values into a [0, 100] scale. But very supportive of the idea. I'm assuming this would be exposed via CLI params and not through the Provisioner spec.

**Comment by ellistarn** [comment]
It would have to be at the CLI level, since batching is global to the process.
