### ISSUE TITLE
Document value for the annotation key: karpenter.sh/do-not-evict

### ISSUE THREAD

**Issue by rajakshay** [aws/karpenter#1693]
**Is an existing page relevant?**

https://github.com/aws/karpenter/blob/fe3c3c287bb3d7c657dd6b9e15f0fc425dc26b9f/website/content/en/preview/tasks/deprovisioning.md 

**What karpenter features are relevant?**

NA

**How should the docs be improved?**
The doc does not specify that a value is needed for the key: `karpenter.sh/do-not-evict`. Due to this, I just used the key, and set the value to an empty string. When the change did not work as expected, I looked into the [code](https://github.com/aws/karpenter/blob/fe3c3c287bb3d7c657dd6b9e15f0fc425dc26b9f/pkg/controllers/termination/terminate.go) and found that it expects the value to be set to true. Hoping to update for more clarity. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by universam1** [comment]
@tzneal Shouldn't be the documented `bool` rather be a `string` of `"true"`?
