### ISSUE TITLE
spot market recovers

### ISSUE THREAD

**Issue by HazoomExpert** [aws/karpenter#1718]
I'm looking to deploy the solution in our environment. I tested our setup in production and when the spot market fails the autoscaler will automatically launch on-demand instances.

The question is will Karpenter migrate the cluster back to spots automatically once the spot market recovers?
Our current configuration was tested and indeed the cluster moved back to spots automatically once they were available.

**Comment by tzneal** [comment]
Karpenter tracks the availability of instance types and records that they are unavailable for a period of time to avoid retrying them.  Once this period expires, they are eligible to be launched again.  In this way, if a particular instance type becomes unavailable Karpenter will eventually retry it.  However it does not automatically terminate existing nodes to replace them unless you use something like the expiration TTL to force nodes to periodically be removed.  Does this answer your question?

**Comment by tzneal** [comment]
Closing as I believe this has been answered.
