### ISSUE TITLE
Karpenter Helm Deployment Default to more than 1 replica

### ISSUE THREAD

**Issue by njtran** [aws/karpenter#1723]
**Tell us about your request**
Karpenter's default deployment spec only creates one replica of the Karpenter controller pod. Karpenter's deployment should default to more replicas to reduce the chances that the Karpenter controller pod isn't scheduled and thus won't work.  This should work in the repo now, just need to change documentation. 

**Additional context**
May need to consider changing the default # of nodes used in getting-started guides as well.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@njtran Can we close this issue now with #2311?
