### ISSUE TITLE
Unable to create DaemonSet that connect to docker endpoint

### ISSUE THREAD

**Issue by amansaini46** [aws/karpenter#1724]
## Version

**Karpenter**: v0.0.0

**Kubernetes**: v1.0.0

## Expected Behavior

I'm unable to deploy papertrail on node created by the Karpenter autoscaler. However, if i deploy the papertrail demonset on the managed nodegroup it works. 

Error logs 
2022/04/25 23:51:36 # jobs    : pump routes http[routes,health,logs]:80
2022/04/25 23:51:36 # routes  :
2022/04/25 23:51:36 pump ended: cannot connect to Docker endpoint

**Comment by tzneal** [comment]
Karpenter uses containerd as the container runtime by default except for a few special cases.  Does papertrail work with containerd?

**Comment by amansaini46** [comment]
Thank you for your help. I was able to resolve the paper trail issue by switching to rkubelog (https://github.com/solarwinds/rkubelog) from logspout.  rkubelog supports containerd.

**Comment by tzneal** [comment]
Glad to hear it!
