### ISSUE TITLE
Karpenter webhook panics trying to hydrate cache

### ISSUE THREAD

**Issue by olemarkus** [aws/karpenter#1743]
## Version

**Karpenter**: v0.9.0

**Kubernetes**: v1.23.6

## Expected Behavior

Karpenter webhook to start

## Actual Behavior

Karpenter webhook crashes with the following:
```
panic: Unable to hydrate the AWS launch template cache, RequestCanceled: request context canceled
caused by: context canceled

goroutine 1 [running]:
github.com/aws/karpenter/pkg/cloudprovider/aws.(*LaunchTemplateProvider).hydrateCache(0xc00010a190, {0x26acb08, 0xc00048e420})
        github.com/aws/karpenter/pkg/cloudprovider/aws/launchtemplate.go:229 +0x4dc
github.com/aws/karpenter/pkg/cloudprovider/aws.NewLaunchTemplateProvider({0x26acb08, 0xc00048e420}, {0x272e278?, 0xc00031eab0}, 0xc00014edc0, 0xc00031eb00, 0xc00004cbc0, 0x0)
        github.com/aws/karpenter/pkg/cloudprovider/aws/launchtemplate.go:70 +0x225
github.com/aws/karpenter/pkg/cloudprovider/aws.NewCloudProvider({0x26acb08, 0xc0006756b0}, {0xc000678d80?})
        github.com/aws/karpenter/pkg/cloudprovider/aws/cloudprovider.go:90 +0x5cc
github.com/aws/karpenter/pkg/cloudprovider/registry.newCloudProvider(...)
        github.com/aws/karpenter/pkg/cloudprovider/registry/aws.go:27
github.com/aws/karpenter/pkg/cloudprovider/registry.NewCloudProvider({0x26acb08?, 0xc0006756b0?}, {0x1ec7a20?})
        github.com/aws/karpenter/pkg/cloudprovider/registry/register.go:25 +0x28
main.main()
        github.com/aws/karpenter/cmd/webhook/main.go:55 +0x219

```

It's worth nothing that the controller starts just fine:

```
2022-05-01T11:46:29.778Z        DEBUG   controller.aws.launchtemplate   Hydrating the launch template cache with names matching "Karpenter-<cluster name>-*"        {"commit": "9b1f078"}
2022-05-01T11:46:29.989Z        DEBUG   controller.aws.launchtemplate   Finished hydrating the launch template cache with 0 items       {"commit": "9b1f078"}
```

## Steps to Reproduce the Problem
This seems to happen just by running the Pod. No particular steps taken

## Resource Specs and Logs
It seems like the error happens before logging has initialised.

**Comment by bwagner5** [comment]
We've seen reports of this happening sporadically. Does the webhook recover on a restart?

**Comment by olemarkus** [comment]
No, I have yet to see it succeed.

**Comment by bwagner5** [comment]
Ok, interesting, I'll have to try to reproduce this consistently. It's also not even necessary for the webhook controller to hydrate the LT cache, so we should definitely remove that.

**Comment by spring1843** [comment]
Are you able to see this debug message? "[Hydrating the launch template cache with names matching](https://github.com/aws/karpenter/blob/bc2273f3ef1c0f17344811c1e60a7f51af4f1dcd/pkg/cloudprovider/aws/launchtemplate.go#L220)" in the logs?

It should tell you what launch template it's trying to read, and then you can validate if it exists or not.

**Comment by olemarkus** [comment]
As mentioned, the logging setup hasn't happened yet at the time it crashes.

**Comment by spring1843** [comment]
It seems like the logger would have been set [before calling the hydrate function](https://github.com/aws/karpenter/blob/bc2273f3ef1c0f17344811c1e60a7f51af4f1dcd/pkg/cloudprovider/aws/launchtemplate.go#L63), if you are not seeing any logs it could be because the log level is not set to Debug.

**Comment by olemarkus** [comment]
Logger is setup in `MainWithConfig`. That line you linked to just sets the object.

In the main controller you will see this code extracted into `LoggingContextOrDie`, but the same code does not exist for the webhook.
