### ISSUE TITLE
No logs appear in logLevel: error | v0.8.2

### ISSUE THREAD

**Issue by devopsjnr** [aws/karpenter#1744]
**Karpenter**: v0.8.2

**Kubernetes**: v1.21.5

Hi guys, I upgraded to v0.8.2 and I cannot see any logs when I change logLevel to `error`. Logs will be seen only in `debug`.

The installation has been done through terraform with changing log level from there:
```
  set {
    name  = "logLevel"
    value = var.log_level
  }
```

I can see in config-logging that `level` was changed to `error`:

```
apiVersion: v1
data:
  zap-logger-config: |
    {
      "level": "error",
      "development": false,
      "disableStacktrace": true,
      "disableCaller": true,
      "sampling": {
        "initial": 100,
        "thereafter": 100
      },
      "outputPaths": ["stdout"[],
      "errorOutputPaths": ["stderr"[],
      "encoding": "console",
      "encoderConfig": {
        "timeKey": "time",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "message",
        "stacktraceKey": "stacktrace",
        "levelEncoder": "capital",
        "timeEncoder": "iso8601"
      }
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: karpenter
  creationTimestamp: "2022-04-20T13:03:57Z"
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.8.2
    helm.sh/chart: karpenter-0.8.2
  name: config-logging
  namespace: karpenter
  resourceVersion: "482477052"
  uid: 67150e97-6f12-45bf-b697-5368799c00fe

```

When following the logs after applying the logLevel change, no logs will appear at all. 
I would see logs again only if I changed logLevel back to debug.

**Comment by dewjam** [comment]
Hey @devopsjnr ,
This is actually by design assuming Karpenter is functioning correctly.  At ERROR log level you will not see logs emitted with the INFO or DEBUG log level.  You should only see logs which are at severity of ERROR or greater.

I'm curious if the INFO level is a better fit for what you're expecting to see in logs.  Or can you share what you were expecting to see in the logs at ERROR log level?

**Comment by spring1843** [comment]
@dewjam is correct. To ensure logs would show up if there are errors you can cause a fake error, e.g. you can rename one of the many values in the provisioner to a fake one.

**Comment by devopsjnr** [comment]
when I choose logLevel to error, I expect to log in all levels including ERROR logs.
Currently if I set logLevel to error, no logs appear at all, nothing. although I caused errors deliberately. 
I saw now that if I leave logLevel as debug, I see all kinds of logs - including ERROR logs. Why is that?

**Comment by bwagner5** [comment]
Generally, log levels only show logs at that level and "worse". Here's a table that might make this clearer:

```
const (
	// DebugLevel logs are typically voluminous, and are usually disabled in
	// production.
	DebugLevel = [zapcore](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore).[DebugLevel](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore#DebugLevel)
	// InfoLevel is the default logging priority.
	InfoLevel = [zapcore](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore).[InfoLevel](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore#InfoLevel)
	// WarnLevel logs are more important than Info, but don't need individual
	// human review.
	WarnLevel = [zapcore](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore).[WarnLevel](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore#WarnLevel)
	// ErrorLevel logs are high-priority. If an application is running smoothly,
	// it shouldn't generate any error-level logs.
	ErrorLevel = [zapcore](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore).[ErrorLevel](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore#ErrorLevel)
	// DPanicLevel logs are particularly important errors. In development the
	// logger panics after writing the message.
	DPanicLevel = [zapcore](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore).[DPanicLevel](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore#DPanicLevel)
	// PanicLevel logs a message, then panics.
	PanicLevel = [zapcore](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore).[PanicLevel](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore#PanicLevel)
	// FatalLevel logs a message, then calls os.Exit(1).
	FatalLevel = [zapcore](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore).[FatalLevel](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore#FatalLevel)
)
```
https://pkg.go.dev/go.uber.org/zap#pkg-constants

So when you set the logger to ERROR, you'll only see things logged at ERROR, PANIC, and FATAL.  If DEBUG logs are showing you too much, you probably want to set your logger at INFO. INFO will show you everything at INFO, WARN, ERROR, PANIC, and FATAL.

**Comment by devopsjnr** [comment]
@bwagner5  Got it, thanks a lot!!
