### ISSUE TITLE
Instance profile InvalidParameterValue

### ISSUE THREAD

**Issue by devopsjnr** [aws/karpenter#1748]
**Karpenter**: v0.8.2

**Kubernetes**: v1.21.5

I created an instance profile (with terraform) which I proved that works properly on my cluster. This instance profile contains exactly what mentioned in the guide. 
Only the name of the instance profile is `instance-profile-483980943424`. 

*Note that I have already used an instance profile with a different name as presented in the guide, with a little bit of modifications it works so the name is not the problem.

Karpenter controller logs shows error: 
```
2022-05-02T23:14:04.060Z	ERROR	controller.provisioning	Launching node, creating cloud provider machine, with fleet error(s), InvalidParameterValue: Value (instance-profile-483980943424) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name	{"commit": "c115db3", "provisioner": "general-provisioner"}
```

Karpenter does not like the digits at the end of the name. I tried to add quotes from the helm chart: 
```
  set {
    name  = "aws.defaultInstanceProfile"
    value = "'${var.default_instance_profile}'" 
  }
```

But seems like the value get in the manifest without quotes:

```
    - name: AWS_DEFAULT_INSTANCE_PROFILE                                                                                                    
      value: instance-profile-483980943424
```

Is the a way to make Karpenter approve my Instance profile name?

**Comment by bwagner5** [comment]
can you try using `set_string` rather than `set` ?  

Here's an example: 
https://registry.terraform.io/providers/hashicorp/helm/0.10.6/docs/resources/release#:~:text=set_string%20%7B%0A%20%20%20%20name%20%20%3D%20%22service.annotations.prometheus%5C%5C.io/port%22%0A%20%20%20%20value%20%3D%20%229127%22%0A%20%20%7D

**Comment by devopsjnr** [comment]
@bwagner5  thanks! I have another issue regarding helm_release, I opened a different thread: https://github.com/aws/karpenter/issues/1753

I would be grateful to get your advise there too :)
