### ISSUE TITLE
limit number of pods in a single node

### ISSUE THREAD

**Issue by devopsjnr** [aws/karpenter#1759]
**Karpenter**: v0.8.2

**Kubernetes**: v1.21.5

I am not specifying requests and limits in my containers so scheduled pods are coming without requests and limits (I am aware that it is not the proper way to manage a cluster).
From the provisioner I specified cpu & memory limits so I expect Karpenter to create new nodes if the others exceeded those limits.

Although the limits I defined in the provisioner, it looks like pods are still being scheduled on nodes that already have higher memory and cpu usage. As a consequence Karpenter nodes are getting stuck in `notReady` state forever. 

I would like to limit the number of pods that can run on a single node to 20. 
So for example, if there are 30 pods that are waiting to be scheduled, Karpenter will create a node, 20 pods get into that node and 10 will get into a new node after Karpenter noticed that first node reached the limit number of pods.

**Comment by tzneal** [comment]
I think resource requests and resource limits on your workloads is the correct answer here.  Without these, Karpenter doesn't know which size of instance to launch.  Karpenter is not scheduling the pods on existing nodes, that is kube-scheduler. If your pods have no resources/requests, then kube-scheduler will schedule far more on a node than you likely intend as well.
