### ISSUE TITLE
Ec2 node gets deleted right after it was created

### ISSUE THREAD

**Issue by macdrorepo** [aws/karpenter#1760]
**Karpenter**: v9.0.0

Server Version: version.Info{Major:"1", Minor:"22+"}

## Expected Behavior
Deploy EC2 spot nodes

## Actual Behavior
Node been deployed but right after it is deleted.

## Steps to Reproduce the Problem
I'm deploying cluster, node group, helm chart through AWS CDK (python). Using custom AMI with launch template.

## Resource Specs and Logs

Logs from karpenter controller:

2022-05-04T12:44:25.241Z    INFO    controller.provisioning    Batched 3 pod(s) in 1.040383661s    {"commit": "9b1f078", "provisioner": "default"}                                                                       │
│ 2022-05-04T12:44:25.438Z    DEBUG    controller.provisioning    Discovered subnets: [subnet-0af358a4d266c691c (eu-west-2c) subnet-0255d68c7e1f44c9d (eu-west-2b) subnet-03c59ac596a01eea0 (eu-west-2a)]    {"commit": "9 │
│ 2022-05-04T12:44:27.510Z    INFO    controller.provisioning    Launched instance: i-0c179cf2c58ac9f40, hostname: ip-172-19-11-235.eu-west-2.compute.internal, type: m5.2xlarge, zone: eu-west-2b, capacityType: spot     │
│ 2022-05-04T12:44:27.524Z    INFO    controller.provisioning    Created node with 3 pods requesting {"cpu":"3125m","pods":"5"} from types m5.xlarge, m5.2xlarge    {"commit": "9b1f078", "provisioner": "default"}        │
│ 2022-05-04T12:44:27.539Z    INFO    controller.provisioning    Waiting for unschedulable pods    {"commit": "9b1f078", "provisioner": "default"}                                                                         │
│ 2022-05-04T12:44:40.316Z    INFO    controller.provisioning    Batched 5 pod(s) in 1.07323734s    {"commit": "9b1f078", "provisioner": "default"}                                                                        │
│ 2022-05-04T12:44:42.351Z    INFO    controller.provisioning    Launched instance: i-015673f5d4fb6c2bb, hostname: ip-172-19-11-187.eu-west-2.compute.internal, type: m5.2xlarge, zone: eu-west-2b, capacityType: spot     │
│ 2022-05-04T12:44:42.364Z    INFO    controller.provisioning    Created node with 5 pods requesting {"cpu":"5125m","pods":"7"} from types m5.2xlarge    {"commit": "9b1f078", "provisioner": "default"}                   │
│ 2022-05-04T12:44:42.383Z    INFO    controller.provisioning    Waiting for unschedulable pods    {"commit": "9b1f078", "provisioner": "default"}                                                                         │
│ 2022-05-04T12:44:47.863Z    INFO    controller.termination    Cordoned node    {"commit": "9b1f078", "node": "ip-172-19-11-235.eu-west-2.compute.internal"}                                                              │
│ 2022-05-04T12:44:47.886Z    DEBUG    controller.eviction    Evicted pod    {"commit": "9b1f078", "pod": "default/inflate-6b88c9fb68-trmxc"}                                                                              │
│ 2022-05-04T12:44:47.907Z    DEBUG    controller.eviction    Evicted pod    {"commit": "9b1f078", "pod": "default/inflate-6b88c9fb68-zxq6h"}                                                                              │
│ 2022-05-04T12:44:47.931Z    DEBUG    controller.eviction    Evicted pod    {"commit": "9b1f078", "pod": "default/inflate-6b88c9fb68-qrlsh"}                                                                              │
│ 2022-05-04T12:44:48.130Z    INFO    controller.termination    Deleted node    {"commit": "9b1f078", "node": "ip-172-19-11-235.eu-west-2.compute.internal"}                                                               │
│ 2022-05-04T12:44:48.973Z    INFO    controller.provisioning    Batched 3 pod(s) in 1.068513963s    {"commit": "9b1f078", "provisioner": "default"}                                                                       │
│ 2022-05-04T12:44:51.062Z    INFO    controller.provisioning    Launched instance: i-03e894c699e4508ff, hostname: ip-172-19-10-242.eu-west-2.compute.internal, type: m5.2xlarge, zone: eu-west-2b, capacityType: spot     │
│ 2022-05-04T12:44:51.072Z    INFO    controller.provisioning    Created node with 3 pods requesting {"cpu":"3125m","pods":"5"} from types m5.xlarge, m5.2xlarge    {"commit": "9b1f078", "provisioner": "default"}        │
│ 2022-05-04T12:44:51.087Z    INFO    controller.provisioning    Waiting for unschedulable pods    {"commit": "9b1f078", "provisioner": "default"}                                                                         │
│ 2022-05-04T12:44:51.087Z    DEBUG    controller.selection    Relaxing soft constraints for pod since it previously failed to schedule, adding: toleration for PreferNoSchedule taints    {"commit": "9b1f078", "pod": "d │
│ 2022-05-04T12:44:52.087Z    INFO    controller.provisioning    Waiting for unschedulable pods    {"commit": "9b1f078", "provisioner": "default"}                                                                         │
│ 2022-05-04T12:44:58.412Z    INFO    controller.termination    Cordoned node    {"commit": "9b1f078", "node": "ip-172-19-11-187.eu-west-2.compute.internal"}                                                              │
│ 2022-05-04T12:44:58.434Z    DEBUG    controller.eviction    Evicted pod    {"commit": "9b1f078", "pod": "default/inflate-6b88c9fb68-slkr5"}                                                                              │
│ 2022-05-04T12:44:58.455Z    DEBUG    controller.eviction    Evicted pod    {"commit": "9b1f078", "pod": "default/inflate-6b88c9fb68-hf9vf"}                                                                              │
│ 2022-05-04T12:44:58.483Z    DEBUG    controller.eviction    Evicted pod    {"commit": "9b1f078", "pod": "default/inflate-6b88c9fb68-hjqr8"}                                                                              │
│ 2022-05-04T12:44:58.509Z    DEBUG    controller.eviction    Evicted pod    {"commit": "9b1f078", "pod": "default/inflate-6b88c9fb68-6rvph"}                                                                              │
│ 2022-05-04T12:44:58.532Z    DEBUG    controller.eviction    Evicted pod    {"commit": "9b1f078", "pod": "default/inflate-6b88c9fb68-fp5m6"}                                                                              │
│ 2022-05-04T12:44:59.472Z    INFO    controller.termination    Deleted node    {"commit": "9b1f078", "node": "ip-172-19-11-187.eu-west-2.compute.internal"}

https://karpenter.sh/v0.9.0/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume <- this didn't solve the issue. 

My python generated user data for launch template: (using custom AMI which works perfectly for AWS managed node groups with auto scaling groups)

MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

--==MYBOUNDARY==
Content-Type: text/x-shellscript; charset="us-ascii"

#!/bin/bash
set -o xtrace
/etc/eks/bootstrap.sh eks-cluster-eu-west-2
--apiserver-endpoint https://B4B769B02F447C0293313F5787654r.gr7.eu-west-2.eks.amazonaws.com
--b64-cluster-ca LS0tLS1CRUdJT.....0tCg==
--kubelet-extra-args --node-labels=cluster-name=eks-cluster-eu-west-2
--kubelet-extra-args --node-labels=node.k8s.aws/capacity-type=spot

--==MYBOUNDARY==--

**Comment by bwagner5** [comment]
```
│ 2022-05-04T12:44:27.510Z INFO controller.provisioning Launched instance: i-0c179cf2c58ac9f40, hostname: ip-172-19-11-235.eu-west-2.compute.internal, type: m5.2xlarge, zone: eu-west-2b, capacityType: spot │

│ 2022-05-04T12:44:47.863Z INFO controller.termination Cordoned node {"commit": "9b1f078", "node": "ip-172-19-11-235.eu-west-2.compute.internal"} │
```

Looks like it was only up for 20 seconds before being deleted. Can you post your provisioner spec? 

Karpenter shouldn't terminate the node unless the `ttlSecondsUntilExpired` is set before the node is ready.

**Comment by macdrorepo** [comment]
` karpenter_provisioner_manifest = cluster.add_manifest(
            "karpenter_manifest",
            {
                "apiVersion": "karpenter.sh/v1alpha5",
                "kind": "Provisioner",
                "metadata": {
                    "name": "default",
                },
                "spec": {
                    "ttlSecondsUntilExpired": 2592000,
                    "ttlSecondsAfterEmpty": 30,
                    "requirements": [
                        {
                            "key": "karpenter.sh/capacity-type",
                            "operator": "In",
                            "values": ["spot"],
                        },
                        {
                            "key": "kubernetes.io/arch",
                            "operator": "In",
                            "values": ["arm64", "amd64"],
                        },
                        {
                            "key": "node.kubernetes.io/instance-type",
                            "operator": "In",
                            "values": ["m5.large", "m5.xlarge", "m5.2xlarge"],
                        },
                    ],
                    "labels": {
                        "cluster-name": cluster.cluster_name,
                    },
                    "provider": {
                        "subnetSelector": {"karpenter.sh/discovery": cluster.cluster_name},
                        # "securityGroupSelector": {"aws:eks:cluster-name": cluster.cluster_name},
                        "launchTemplate": karpenter_launch_template.launch_template_name,
                    },
                },
            },
        )
`

**Comment by bwagner5** [comment]
Is this the exact user-data you are using? If so, there's an issue in the line-breaks that may be causing the script arguments to not be passed to `bootstrap.sh` properly.  You may have just formatted it for readability in this issue, but if not, are you able to put `\` at the end of each line, like so?  

```
--==MYBOUNDARY==
Content-Type: text/x-shellscript; charset="us-ascii"

#!/bin/bash
set -o xtrace
/etc/eks/bootstrap.sh eks-cluster-eu-west-2 \
--apiserver-endpoint https://xxxxxxxxxxxxx.gr7.eu-west-2.eks.amazonaws.com/ \
--b64-cluster-ca LS0tLS1CRUdJT.....0tCg== \
--kubelet-extra-args --node-labels=cluster-name=eks-cluster-eu-west-2 \
--kubelet-extra-args --node-labels=node.k8s.aws/capacity-type=spot

--==MYBOUNDARY==--
```

If your node has permissions to call the EKS API, I believe the above, without `\` for the line-breaks, would appear to work since the bootstrap.sh will fallback to querying for EKS cluster details if it knows the cluster name. 

Also, it looks like you're using an old label for capacity-type. We decided to namespace that under `karpenter.sh` now, so the label Karpenter uses is: `karpenter.sh/capacity-type`.

**Comment by macdrorepo** [comment]
Thank you, will check that. So in user data it is possible to have only:

```
--==MYBOUNDARY==
Content-Type: text/x-shellscript; charset="us-ascii"

#!/bin/bash
set -o xtrace
/etc/eks/bootstrap.sh eks-cluster-eu-west-2

--==MYBOUNDARY==--

```
and the rest is optional?

**Comment by dewjam** [comment]
Hey @macdrorepo .  Checking in to see if you were able to solve the issue.  Let us know if there's anything else we can help with.

**Comment by macdrorepo** [comment]
Hi, I'm off for few days will be checking this next week

**Comment by macdrorepo** [comment]
Found some time. Didn't help. My user data (no readability changes):

```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

--==MYBOUNDARY==
Content-Type: text/x-shellscript; charset="us-ascii"

#!/bin/bash
set -o xtrace
/etc/eks/bootstrap.sh test-eks-cluster-eu-west-2 --apiserver-endpoint https://49865204177D06FD5C98E8D0DF1FA7A2.yl4.eu-west-2.eks.amazonaws.com --b64-cluster-ca LS0tLS1CRUdJTi<cut>g==

--==MYBOUNDARY==-- 
```
Provisioner taken from eks cluster:

```
│ Name:         default                                                                                                                                                                                                                                                                                                  │
│ Namespace:                                                                                                                                                                                                                                                                                                             │
│ Labels:       aws.cdk.eks/prune-c8bdfbc4880a90c980a53d325e92fa769957346013=                                                                                                                                                                                                                                            │
│ Annotations:  <none>                                                                                                                                                                                                                                                                                                   │
│ API Version:  karpenter.sh/v1alpha5                                                                                                                                                                                                                                                                                    │
│ Kind:         Provisioner                                                                                                                                                                                                                                                                                              │
│ Metadata:                                                                                                                                                                                                                                                                                                              │
│   Creation Timestamp:  2022-05-10T17:47:27Z                                                                                                                                                                                                                                                                            │
│   Generation:          1                                                                                                                                                                                                                                                                                               │
│   Managed Fields:                                                                                                                                                                                                                                                                                                      │
│     API Version:  karpenter.sh/v1alpha5                                                                                                                                                                                                                                                                                │
│     Fields Type:  FieldsV1                                                                                                                                                                                                                                                                                             │
│     fieldsV1:                                                                                                                                                                                                                                                                                                          │
│       f:metadata:                                                                                                                                                                                                                                                                                                      │
│         f:annotations:                                                                                                                                                                                                                                                                                                 │
│           .:                                                                                                                                                                                                                                                                                                           │
│           f:kubectl.kubernetes.io/last-applied-configuration:                                                                                                                                                                                                                                                          │
│         f:labels:                                                                                                                                                                                                                                                                                                      │
│           .:                                                                                                                                                                                                                                                                                                           │
│           f:aws.cdk.eks/prune-c8bdfbc4880a90c980a53d325e92fa769957346013:                                                                                                                                                                                                                                              │
│       f:spec:                                                                                                                                                                                                                                                                                                          │
│         .:                                                                                                                                                                                                                                                                                                             │
│         f:labels:                                                                                                                                                                                                                                                                                                      │
│           .:                                                                                                                                                                                                                                                                                                           │
│           f:cluster-name:                                                                                                                                                                                                                                                                                              │
│         f:provider:                                                                                                                                                                                                                                                                                                    │
│           .:                                                                                                                                                                                                                                                                                                           │
│           f:launchTemplate:                                                                                                                                                                                                                                                                                            │
│           f:subnetSelector:                                                                                                                                                                                                                                                                                            │
│         f:requirements:                                                                                                                                                                                                                                                                                                │
│         f:ttlSecondsAfterEmpty:                                                                                                                                                                                                                                                                                        │
│         f:ttlSecondsUntilExpired:                                                                                                                                                                                                                                                                                      │
│     Manager:      kubectl-create                                                                                                                                                                                                                                                                                       │
│     Operation:    Update                                                                                                                                                                                                                                                                                               │
│     Time:         2022-05-10T17:47:27Z                                                                                                                                                                                                                                                                                 │
│     API Version:  karpenter.sh/v1alpha5                                                                                                                                                                                                                                                                                │
│     Fields Type:  FieldsV1                                                                                                                                                                                                                                                                                             │
│     fieldsV1:                                                                                                                                                                                                                                                                                                          │
│       f:status:                                                                                                                                                                                                                                                                                                        │
│         f:resources:                                                                                                                                                                                                                                                                                                   │
│           f:cpu:                                                                                                                                                                                                                                                                                                       │
│           f:memory:                                                                                                                                                                                                                                                                                                    │
│     Manager:         karpenter                                                                                                                                                                                                                                                                                         │
│     Operation:       Update                                                                                                                                                                                                                                                                                            │
│     Time:            2022-05-10T18:11:35Z                                                                                                                                                                                                                                                                              │
│   Resource Version:  11740                                                                                                                                                                                                                                                                                             │
│   UID:               5909bdc1-cbae-4322-8c63-ba8583265279                                                                                                                                                                                                                                                              │
│ Spec:                                                                                                                                                                                                                                                                                                                  │
│   Labels:                                                                                                                                                                                                                                                                                                              │
│     Cluster - Name:  test-eks-cluster-eu-west-2                                                                                                                                                                                                                                                              │
│   Provider:                                                                                                                                                                                                                                                                                                            │
│     Launch Template:  karpenter-nodes-lt                                                                                                                                                                                                                                                                               │
│     Subnet Selector:                                                                                                                                                                                                                                                                                                   │
│       karpenter.sh/discovery: test-eks-cluster-eu-west-2                                                                                                                                                                                                                                                     │
│   Requirements:                                                                                                                                                                                                                                                                                                        │
│     Key:       karpenter.sh/capacity-type                                                                                                                                                                                                                                                                              │
│     Operator:  In                                                                                                                                                                                                                                                                                                      │
│     Values:                                                                                                                                                                                                                                                                                                            │
│       spot                                                                                                                                                                                                                                                                                                             │
│     Key:       kubernetes.io/arch                                                                                                                                                                                                                                                                                      │
│     Operator:  In                                                                                                                                                                                                                                                                                                      │
│     Values:                                                                                                                                                                                                                                                                                                            │
│       amd64                                                                                                                                                                                                                                                                                                            │
│     Key:       node.kubernetes.io/instance-type                                                                                                                                                                                                                                                                        │
│     Operator:  In                                                                                                                                                                                                                                                                                                      │
│     Values:                                                                                                                                                                                                                                                                                                            │
│       c5.2xlarge                                                                                                                                                                                                                                                                                                       │
│       c5.large                                                                                                                                                                                                                                                                                                         │
│       c5.xlarge                                                                                                                                                                                                                                                                                                        │
│   Ttl Seconds After Empty:    30                                                                                                                                                                                                                                                                                       │
│   Ttl Seconds Until Expired:  2592000                                                                                                                                                                                                                                                                                  │
│ Status:                                                                                                                                                                                                                                                                                                                │
│   Resources:                                                                                                                                                                                                                                                                                                           │
│     Cpu:     0                                                                                                                                                                                                                                                                                                         │
│     Memory:  0                                                                                                                                                                                                                                                                                                         │
│ Events:      <none>
```

**Comment by KarthikRajashekaran** [comment]
Any updates regarding this issue

**Comment by tzneal** [comment]
The node gets cordoned once it has been deleted. This sets the deletion timestamp to non-zero and Karpenter gets a chance to clean up due to the finalizer that it has placed on the node.  Can you look at the audit logs to see what is deleting the node?

**Comment by macdrorepo** [comment]
Hi, Ive gave up on using this product. One request / suggestion on getting started - add aws cdk (python) specially passing user data for custom launch template. Maybe then I'll spot some mistakes in my cdk code. For now I'm using autoscaler as it is working like out of the box.

**Comment by gowthasa** [comment]
Hi, I had one of my customer facing similar issue and that was due to having EBS encryption enabled at EC2 settings. I was able to replicate the same issue in my EKS cluster. Following https://karpenter.sh/v0.10.1/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume helped me resolve the issue. 

However, the one shared on the Karpenter troubleshooting docs for some reason was not allowing the nodes get launched by Karpenter Node role. Had to work on the KMS IAM policy on my own to allow Karpenter Node role launch nodes and the join the cluster and then become `Ready` and have pods in `Running` state.

**Comment by macdrorepo** [comment]
> Hi, I had one of my customer facing similar issue and that was due to having EBS encryption enabled at EC2 settings. I was able to replicate the same issue in my EKS cluster. Following https://karpenter.sh/v0.10.1/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume helped me resolve the issue.
> 
> However, the one shared on the Karpenter troubleshooting docs for some reason was not allowing the nodes get launched by Karpenter Node role. Had to work on the KMS IAM policy on my own to allow Karpenter Node role launch nodes and the join the cluster and then become `Ready` and have pods in `Running` state.

So what did you do with KMS policy to get that worked?

**Comment by suket22** [comment]
@gowthasa would you be willing to cut a PR and update the troubleshooting steps if they're not accurate? I'm curious what the delta was as well. 

@macdrorepo - It does sound like there's something else in your launch template (maybe an encrypted EBS volume?) that's causing these issues. When the instance is created, it's worth looking at the EC2 console if it was created successfully. To me, it appears that that might not be the case. When EC2 deletes the instance, the corresponding node object in the cluster will also be automatically removed which is probably what you're seeing.

**Comment by gowthasa** [comment]
> > Hi, I had one of my customer facing similar issue and that was due to having EBS encryption enabled at EC2 settings. I was able to replicate the same issue in my EKS cluster. Following https://karpenter.sh/v0.10.1/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume helped me resolve the issue.
> > However, the one shared on the Karpenter troubleshooting docs for some reason was not allowing the nodes get launched by Karpenter Node role. Had to work on the KMS IAM policy on my own to allow Karpenter Node role launch nodes and the join the cluster and then become `Ready` and have pods in `Running` state.
> 
> So what did you do with KMS policy to get that worked?

Initially, I was trying to create a KMS policy and add the same to the Karpenter Node role and instead of the Karpenter Controller role (IRSA role), it was my bad. 

However, following the Karpenter troubleshooting docs  https://karpenter.sh/v0.10.1/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume and EBS KMS https://docs.aws.amazon.com/autoscaling/ec2/userguide/key-policy-requirements-EBS-encryption.html#eding-key-policies-console , I went about adding the Karpenter Controller role (IRSA role) as KMS Key users in the KMS console and that solved the issue for me. 

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/98508448/173300606-6f261d7b-5300-4ca1-8464-b1cb5e3e6796.png">




Below is the snippet of the KMS Key policy permissions. 

```
{
    "Id": "key-consolepolicy-3",
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Allow use of the key",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<Account_ID>:role/demo-karpenter"
            },
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:DescribeKey"
            ],
            "Resource": "*"
        },
        {
            "Sid": "Allow attachment of persistent resources",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<Account_ID>:role/demo-karpenter"
            },
            "Action": [
                "kms:CreateGrant",
                "kms:ListGrants",
                "kms:RevokeGrant"
            ],
            "Resource": "*",
            "Condition": {
                "Bool": {
                    "kms:GrantIsForAWSResource": "true"
                }
            }
        }
    ]
}
```
Note : As mentioned above, I added the Karpenter Controller IAM role (IRSA role used by the Karpenter Controller pods per https://karpenter.sh/v0.10.1/getting-started/getting-started-with-eksctl/#create-the-karpentercontroller-iam-role) and not the KarpenterNode IAM Role.

**Comment by gowthasa** [comment]
> @gowthasa would you be willing to cut a PR and update the troubleshooting steps if they're not accurate? I'm curious what the delta was as well.
> 
> @macdrorepo - It does sound like there's something else in your launch template (maybe an encrypted EBS volume?) that's causing these issues. When the instance is created, it's worth looking at the EC2 console if it was created successfully. To me, it appears that that might not be the case. When EC2 deletes the instance, the corresponding node object in the cluster will also be automatically removed which is probably what you're seeing.

@[suket22](https://github.com/suket22)

I have created a PR for docs update https://github.com/aws/karpenter/issues/1926 which mentions the KMS policy should allow `Karpenter Controller role (IRSA role)` and not the `Karpenter Node role` which would help customers add right roles for allow EBS encryption for the nodes provisioned by Karpenter controller.

**Comment by tzneal** [comment]
Closing as we've updated the docs for this now.
