### ISSUE TITLE
Recommend that Karpenter run on Fargate

### ISSUE THREAD

**Issue by chrisnegus** [aws/karpenter#1763]
**Is an existing page relevant?**
Yes, the Karpenter getting started guides. 

Also, review the wording related to this issue in the [Karpenter Best Practices](https://aws.github.io/aws-eks-best-practices/karpenter/#run-the-karpenter-controller-on-eks-fargate-or-on-a-worker-node-that-belongs-to-a-node-group) guide.

**What karpenter features are relevant?**
How to run the Karpenter controller securely.

**How should the docs be improved?**
Make sure that each getting started guide either notes that Karpenter is added to its own nodegroup by default or describe how to configure Karpenter to run in Fargate or its own nodegroup. Also note that nodes should be configured (probably with taints) to prevent workloads from running on any node running Karpenter.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by suket22** [comment]
Alternatively, we should recommend to run Karpenter on Fargate instead.

**Comment by chrisnegus** [comment]
Running Karpenter on Fargate is now described in [Getting started with eksctl](https://github.com/aws/karpenter/pull/1834) and in the [Troubleshooting](https://github.com/aws/karpenter/pull/1864).
