### ISSUE TITLE
evicted daemonset pod

### ISSUE THREAD

**Issue by trondhindenes** [aws/karpenter#1769]
## Version
**Karpenter**: v0.9.1
**Kubernetes**: v1.21.0

## Expected Behavior
We're seeing that karpenter-provisioned nodes might evict daemonset pods to make room for the "workload pod". Is there a way to configure how much resource overhead karpenter should calculate with, in order to fit all daemonset pods?

## Actual Behavior
Daemonset pods get evicted because of memory pressure

## Steps to Reproduce the Problem
I haven't done enough research to have a good repro description

**Comment by tzneal** [comment]
This can occur if your daemonset pods are of lower priority than your workload pods.  In this case, the kube-scheduler will evict a daemonset to let the workload run.  Karpenter won't launch a new node just for the DS. 

Are your workloads higher priority than your daemonsets?

**Comment by dewjam** [comment]
Hey @trondhindenes ,
Were you able to validate the priority of your pods vs DaemonSets?  Is there anything else we can do to help with this issue?

**Comment by trondhindenes** [comment]
Hi, 
I think this was related to node disk pressure. Will keep watching for this, but for now I'll close the issue. Thanks for following up!!
