### ISSUE TITLE
Karpenter support for eks ipv6

### ISSUE THREAD

**Issue by chaitugsk07** [aws/karpenter#1777]
**Is an existing page relevant?**

**What karpenter features are relevant?**

**How should the docs be improved?**
It would be great to have some documentation on karpenter for eks ipv6 cluster. Or may be a sample codebase

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Hey thanks for raising this docs request. We're currently working on supporting ipv6 natively in Karpenter here https://github.com/aws/karpenter/pull/1605 once this PR is merged, we might be able to provide something in our getting started docs on how to use with IPv6.
