### ISSUE TITLE
Provisioning Configuration

### ISSUE THREAD

**Issue by lmouhib** [aws/karpenter#1779]
It would be good to have more details on the configuration API, what is required and what is not would be a good start/

**Comment by bwagner5** [comment]
Are you looking for something more than what this page describes? https://karpenter.sh/v0.9.1/provisioner/

**Comment by lmouhib** [comment]
Yes, one example, if we take the AWS provider it needs an SG, but in the documentation we do not specify it is mandatory, it will fail through the admission control. I do understand it is the SG that is attached to the provisioned EC2, but the documentation is not explicit about it. The SG is either provided through the manifest or the launch template.

**Comment by bwagner5** [comment]
I see, maybe adding a full example with comments like we do for the Provisioner spec (without the provider) would be good.

**Comment by lmouhib** [comment]
Either comments in a full example, like `#required` or  `#optional`. Or annotate the documentation itself if the doc generation allow it.

**Comment by chrisnegus** [comment]
I'm going to to the following:
* Create a full example provisioner in [AWS Provisioning](https://karpenter.sh/v0.9.1/aws/provisioning/) (like the one on [Provisioner API](https://karpenter.sh/v0.9.1/provisioner/)), with optional and required fields marked.
* Mark individual field descriptions on that page as required or optional.
* Describe why required fields are needed.
* Do similar to the descriptions in the [AWS Launch Templates](https://karpenter.sh/v0.9.1/aws/launch-templates/) section.

**Comment by lmouhib** [comment]
closing this, comments addressed  in commit f1ec9a5 release v0.10.1.
