### ISSUE TITLE
Does Karpenter support Elastic GPUs ?

### ISSUE THREAD

**Issue by mandeepgoyat** [aws/karpenter#1789]
Hi Team

I am trying karpenter now a days.

I have one query :- Does karpenter support Elastic GPUs ? I know karpenter support GPUs and I saw specs in karpenter documentation but I do not see anything related to Elastic GPUs. Like which property i should use to enable Elastic GPU etc..

Please share information related to Elastic GPU with Karpenter.

**Comment by dewjam** [comment]
Hey @mandeepgoyat ,
Karpenter does not support provisioning instances with Elastic Graphics at the moment.  As you mentioned, Karpenter supports GPU instances as an alternative.  

Would you be willing to share your use-case for Elastic Graphics?  Can GPU instances fulfill your needs instead?

**Comment by dewjam** [comment]
Hello @mandeepgoyat .  I'm going to go ahead and close this out.  Please feel free to reopen if there are any additional questions.
