### ISSUE TITLE
Allow user-specified instance types to pass through filter

### ISSUE THREAD

**Issue by thepinetree** [aws/karpenter#1791]
**Tell us about your request**
The filter referenced in #1053 continues to be restrictive (e.g. the `i4` and `z1` instances classes are disallowed).

https://github.com/aws/karpenter/blob/ec2b5c021ca8baa2bebae36fac4f6c5969d2bfa3/pkg/cloudprovider/aws/instancetypes.go#L172

Ideally, as @bwagner5 mentioned in a comment on the aforementioned issue, it would be nice to allow instances specified by the user with `node.kubernetes.io/instance-type` to pass through the filter. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are trying to schedule jobs on a variety of instance types with Karpenter, in this situation, one-off testing runs.

Unfortunately, the filter prevents Karpenter from provisioning certain node types (`i4`, `z1`) from being provisioned.

**Are you currently working around this issue?**
Not currently working around this, though an alternative certainly would be to add an instance type class to the filter whenever needed.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Yes! Thanks for the issue! I just put up a PR to at least allow the use of any instance type that you directly specify in the provisioner spec.  I also set `i*` in the filter rather than just allowing `i3` before. I didn't include `z*` in the standard set, but you can set the provisioner to use `z1d` instance types which it will only use if no other instance types are available. There's probably still work to do in Karpenter to not prioritize when instance type requirements are passed into the provisioner at all, but hopefully this helps in the near term.

**Comment by bwagner5** [comment]
ah! I didn't even see the PR you submitted, apologies. I haven't taken a look at it yet, but if yours solves this problem as well, then I'd be happy to take yours.  I can take a closer look tomorrow.

**Comment by thepinetree** [comment]
ack, thanks for the quick turnaround @bwagner5! Feel free to use whichever PR works out better. 

My first-order takeaway seems like #1793 might increase the set of potential instance types to consider (to nearly all instance types, I think) but is a cleaner change, while #1792 changes the set to known families + requested nodes but is  more invasive. 

I also planned on adding a unittest with a little guidance to #1792 to confirm the intended behavior is met.

**Comment by bwagner5** [comment]
I've merged in #1793 which will hopefully unblock you. We'll likely release a new version next week. I'm still open to #1792 as that would increase the amount of instance types passed to the EC2 Fleet API to make more flexible decisions.

I'm not sure how often a more flexible set of instance types would actually be passed through though. For example, if I specify that I want "z" instance types in my provisioner spec, I'm not sure if I'd be mixing them with the standard set of instance types (m, c, r, a, t, i).  But if you have a use-case for mixing standard and what karpenter considers special instance types, let me know!

**Comment by thepinetree** [comment]
Thank you @bwagner5! I'll think about how to address your comment on #1792 next week. 

Our use case was to enable one-off and lasting instance type shift, where we found that for a CPU-bound task, the z1 (along with some m and c instances) should work better than the i instances, but other jobs still used the i instances for storage bound workloads.

**Comment by bwagner5** [comment]
> Thank you @bwagner5! I'll think about how to address your comment on #1792 next week.
> 
> Our use case was to enable one-off and lasting instance type shift, where we found that for a CPU-bound task, the z1 (along with some m and c instances) should work better than the i instances, but other jobs still used the i instances for storage bound workloads.

Interesting, so IIUC you'd set something like this in your provisioner (for cpu bound workloads):

```
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m5.large", "z1d.large", "c5.large"]
```

and expect Karpenter to treat them more or less equal? 

And then in another provisioner you'd specify the `i` instance types for storage bound workloads?

**Comment by dewjam** [comment]
Hey there @thepinetree .  Can you confirm #1793 has unblocked you?  Can we close this out?

**Comment by thepinetree** [comment]
Sorry for my late reply here. @bwagner5 yes, though eventually we will probably land on one of the three nodes as the best given our constraints for the job.

@dewjam I believe we are waiting for a new release before we test and confirm our problem is solved, though I'm optimistic :) Shall we still hold off on closing until the release lands and is tested in our environment?

**Comment by dewjam** [comment]
Sure, sounds good!
