### ISSUE TITLE
feedback: possible use of conventional commits?

### ISSUE THREAD

**Issue by robertd** [aws/karpenter#1799]
Hello,

Would Karpenter team ever consider adopting “conventional commits” specification for the Karpenter project?https://www.conventionalcommits.org/en/v1.0.0/

For example, CDK project has been using this specification and it’s really working out well for them (and their community).  

One of the benefits that comes to mind, for users (i.e. downstream CDK package maintainers), is that it would be much easier to read the changelog between the releases, and see what’s `feat`, `chore`, `fix`, `docs`, etc in the upcoming release. 

Just a friendly suggestion 😅 … I can also bring this up during our next Karpenter call as a community feedback. 

Thanks!

**Comment by bwagner5** [comment]
We're definitely not against it and our release notes automation actually does pick up conventional commits to put them in the correct headings. We've mainly been cherry-picking commits to put in the "Features" and "Bug Fixes" sections of the release notes manually.   I'll bring this up with the team to see if we can be more diligent about using conventional commits.
