### ISSUE TITLE
Balance capacity between AZs

### ISSUE THREAD

**Issue by dotanalter** [aws/karpenter#1810]
**Tell us about your request**
Balance capacity between AZs equally (using a flag maybe).

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently, Karpenter decides instance types using the following logic: 
https://karpenter.sh/v0.10.0/faq/#how-does-karpenter-dynamically-select-instance-types
In this way, Karpenter can schedule all/most of the nodes on the same AZ which is not good for HA.
In cluster autoscaler there is a flag (--balance-similar-node-groups) to improve the balance between node groups: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#im-running-cluster-with-nodes-in-multiple-zones-for-ha-purposes-is-that-supported-by-cluster-autoscaler

**Are you currently working around this issue?**
We can use anti-affinity to improve the balancing between the AZs, that's not a good solution for production environments. 

**Attachments**
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/43717802/168564900-b1c71df7-109a-458d-977f-c6434e534548.png">

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
You can use topology spread constraints on your workloads to spread them across zones. See https://karpenter.sh/v0.10.0/tasks/scheduling/#topology-spread

**Comment by ankitjain28may** [comment]
Would it be possible to get this feature on karpenter itself rather than depending on the pod's topology constraint.

**Comment by tzneal** [comment]
Just launching nodes in different AZs isn't enough to ensure that workloads are spread across AZs.  You could end up with a workload entirely in a single AZ, even though the nodes themselves are spread.  Topology spread constraints on the workloads are the method to inform both Karpenter and the scheduler that you care about how the workloads are spread.

**Comment by thomaschaaf** [comment]
@tzneal we do that but karpenter just relaxes the constraints.. I think it's because one az is cheaper or has better node availability

**Comment by ellistarn** [comment]
If you use zonal topology spread w/ `DoNotSchedule` policy, Karpenter will not relax the requirements.
