### ISSUE TITLE
karpenter won't work if there is no dns in the cluster

### ISSUE THREAD

**Issue by marcelobartsch** [aws/karpenter#1836]
## Version

**Karpenter**: v0.10.0

**Kubernetes**: v1.0.0
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-0d102a7", GitCommit:"eb09fc479c1b2bfcc35c47416efb36f1b9052d58", GitTreeState:"clean", BuildDate:"2022-02-17T16:36:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

## Expected Behavior

running karpenter as the first pod in the cluster to allow it to scale from 0 the worker nodes based on the Providers CDR Configuration, this happen when deployed with the helm chart.
## Actual Behavior

Karpenter fails to work as it inherits the dnsConfig , which in our case is ClusterFirst (EKS Default?) but as there are no nodes, coredns is no running in the cluster
## Steps to Reproduce the Problem

configure a cluster with no worker nodes, a fargate profile to run karpenter on fargate, karpenter will start but will restart as no DNS is available in the cluster.

**Comment by marcelobartsch** [comment]
I submitted the pr #1835 to address the dnsConfig on the helm chart.

**Comment by bwagner5** [comment]
merged, will likely be released next week.
