### ISSUE TITLE
[Help] Can I use Fargate without managed node groups ?

### ISSUE THREAD

**Issue by rohitjha941** [aws/karpenter#1848]
### What am I trying to do?
 I want to run Karpenter on Fargate without any managed node groups.  Fargate does not seem to start if the number of instances in managed node group are 0. The health check keeps failing in this case. 
 
 ### Codebase
 
```
module "karpenter_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 4.15"

  role_name                          = "karpenter-controller-${var.eks_cluster_name}"
  attach_karpenter_controller_policy = true
  karpenter_controller_cluster_id    = var.cluster_id
  oidc_providers = {
    ex = {
      provider_arn               = var.oidc_provider_arn
      namespace_service_accounts = ["${var.namespace}:karpenter"]
    }
  }
}

resource "aws_iam_instance_profile" "karpenter" {
  name_prefix = "KarpenterNodeInstanceProfile-${var.eks_cluster_name}-"
  role        = var.node_group_role_name
}

resource "helm_release" "karpenter" {
  namespace        = var.namespace
  create_namespace = var.create_namespace

  name       = "karpenter"
  repository = "https://charts.karpenter.sh"
  chart      = "karpenter"
  version    = "0.9.1"

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = module.karpenter_irsa.iam_role_arn
  }

  set {
    name  = "clusterName"
    value = var.cluster_id
  }

  set {
    name  = "clusterEndpoint"
    value = var.cluster_endpoint
  }

  set {
    name  = "aws.defaultInstanceProfile"
    value = aws_iam_instance_profile.karpenter.name
  }

}

resource "kubectl_manifest" "karpenter_provisioner" {
  yaml_body = <<-YAML
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: default
  spec:
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"]
    limits:
      resources:
        cpu: 50
    provider:
      subnetSelector:
        karpenter.sh/discovery: ${var.eks_cluster_name}
      securityGroupSelector:
        karpenter.sh/discovery: ${var.eks_cluster_name}
      tags:
        karpenter.sh/discovery: ${var.eks_cluster_name}
        Name: ${var.eks_cluster_name}-cluster-node
      blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          volumeSize: 100Gi
          volumeType: gp3
          encrypted: true
          deleteOnTermination: true
 
    ttlSecondsAfterEmpty: 30
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}

```
The node group node is passed by using `eks.eks_managed_node_groups["default_node_group"].iam_role_name`  and default node group config is 

```
  eks_managed_node_groups = {
    default_node_group = {
      min_size     = 0
      max_size     = 0
      desired_size = 0
    }
  }
```
 I am using terraform eks module to provision the cluster.,

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
what's your fargate profile namespace you created for karpenter?

**Comment by rohitjha941** [comment]
I have created a fargate profile for namespace and am sure that karpenter is running on Fargate.

**Comment by tzneal** [comment]
I've tested a few clusters now with fargate + karpenter and no MNG with no issues.  If you use eksctl, you need to ensure that there's a fargate profile setup in your `ClusterConfig` that covers the `kube-system` namespace. eksctl detects this and patches the coredns deployment so that it will run on fargate.  

If you don't use eksctl, you'll need to manually patch and restart coredns per the instructions [here](https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html).
