### ISSUE TITLE
Prevent pods from being rescheduled.

### ISSUE THREAD

**Issue by zaphinath** [aws/karpenter#1849]
**Tell us about your request**
What do you want us to build?

We have a case where we run a monte carlo set of ML tests. These use statefulsets and we keep everything in memory to be faster. When we use a karpenter provisioner for these we notice that a pod will quietly move from one node to another node without showing a restart. We tried using the annotation safe-to-evict and that seems to only work if the node is going down. In our cases the nodes are still up and running, but we want to prevent pods from moving from one node to another. If we use nodegroups and the cluster autoscaler we are able to prevent this, but with karpenter for some reason how it interacts with the scheduler we seem to get this kind of pod drift.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

We need to prevent pods from moving to prevent data loss. It is costly to add a pvc to each one in our monte carlo simulation and thus we keep all the databases in memory only.

**Are you currently working around this issue?**
How are you currently solving this problem?

We use annotations with the current autoscaler and have a special node group to run these tests.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by zaphinath** [comment]
Shouldn't be. They all have the same priority in this setup. Just when a new node is brought up we will see a pod reassigned to that new node when we didn't want it to move. If we go back to node groups we don't see this behavior for some reason.

**Comment by suket22** [comment]
Are you running on Spot instances by any chance?

**Comment by zaphinath** [comment]
No spot instances for these tests. Some of them take several days to run and I will try and catch the events/ see if I can forward them onto a log service to gather them there too.

**Comment by manojtr** [comment]
This is still happening. @zaphinath have you figured out why? Any help is appreciated on this. Thanks

**Comment by Quanalogy** [comment]
We are experiencing this too, events doesn't seems to help us on this. 

Our setup is such that nodes for this is setup with a taint that only a single deployment is using, i.e there is only replicas of that deployment using these nodes. Requests are set such that there can be two replicas on each node and what we see is that when new nodes are requested the existing nodes are 100% full of their capacity, when the new node starts up, a running pod is immidiately rescheduled on that node. This creates capacity for the newly requested pods which in turn will make the typically two pods waiting to start space out, one on the old node and one on the newly created node.

This is quite annoying to us as the startup time of these pods is longer than you would like and scaling up actually is at a cost of performance while this is settling.

Anyone found a solution on this the last two years :) ?
