### ISSUE TITLE
Taints - no schedule expalanation

### ISSUE THREAD

**Issue by mro-amboss** [aws/karpenter#1853]
**Is an existing page relevant?**
https://karpenter.sh/v0.5.6/tasks/scheduling/#taints-and-tolerations

**How should the docs be improved?**
The statement in text sounds contradictionary  to yaml manifest. 
The text says:

> This example shows a Provisioner that was set up with a taint for only running pods that require a GPU, such as the following

However the yaml manifest looks saying, that nvidia.com/gpu should not be scheduled.
` taints:
  - key: nvidia.com/gpu
    value: true
    effect: "NoSchedule"`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
It's common to taint nodes with an NVidia GPU with that taint to prevent pods that don't require a GPU from scheduling against the node. This then requires adding a toleration to any workloads that require a GPU so they can schedule against the node.  There is further explanation and an example workload with the toleration [here](https://aws.github.io/aws-eks-best-practices/karpenter/#create-provisioners-that-are-mutually-exclusive).
