### ISSUE TITLE
Question: customize the servers in provisioners

### ISSUE THREAD

**Issue by funes79** [aws/karpenter#1873]
I do have a question about the customization of worker nodes in the Karpenter provider. In case of EC2 instances with local storage in AWS I would like to auto format and mount the NVME ephemeral volumes.

https://aws.amazon.com/blogs/containers/optimizing-spark-performance-on-kubernetes/

Is there a way to insert script like this into the provider's configuration?
```
preBootstrapCommands:
      - IDX=1
      - for DEV in /dev/disk/by-id/nvme-Amazon_EC2_NVMe_Instance_Storage_*-ns-1; do  mkfs.xfs ${DEV};mkdir -p /local${IDX};echo ${DEV} /local${IDX} xfs defaults,noatime 1 2 >> /etc/fstab; IDX=$((${IDX} + 1)); done
      - mount -a
```

**Is an existing page relevant?**

**What karpenter features are relevant?**

**How should the docs be improved?**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by funes79** [comment]
Yes the design looks great. In my case I do not want to mess around with kubelet args just modify the system. I vote for Option 3 in case AL2.

**Comment by njtran** [comment]
Closing this, as we're working on it. Feel free to reach out to @suket22 who's working on this.
