### ISSUE TITLE
Filtering restricted labels that are passed to kubelet parameters when launching node

### ISSUE THREAD

**Issue by felix-zhe-huang** [aws/karpenter#1883]
## Version

**Karpenter**: v0.10.1

**Kubernetes**: v1.21.9

## Expected Behavior
Karpenter allows using certain label keys in the restricted namespace which are not allowed by kubelet (e.g., `kops.k8s.io`). These labels should not be injected to kubelet when karpetner cloud provider launches node.

## Actual Behavior
Defining a label with key in the domain namespace `kops.k8s.io` in the provisioner label section will pass the label key value pair to 
kubelet parameters which causes kubelet to fail to start up. Node will be stuck at `NotReady` state.

## Steps to Reproduce the Problem
Add a label `kops.k8s.io/test: test` in the label section of the provisioner.

## Extra Consideration
Filtering the labels before launching node will cause cloud provider to generate multiple duplicate custom LTs because cloud provider generate LT IDs using the hashing values of the provisioner nodeTemplate.
Karpenter community should also discuss with kOps community about using the `kops.k8s.io` label namespace to better align with kubelet's requirements. 

## Resource Specs and Logs
```
I0602 00:32:57.840051    3505 flags.go:59] FLAG: --node-labels="karpenter.sh/capacity-type=spot,karpenter.sh/provisioner-name=default,kops

E0602 00:32:51.861590    3266 server.go:192] "Failed to validate kubelet flags" err="unknown 'kubernetes.io' or 'k8s.io' labels specified
Jun 02 00:32:57 ip-192-168-123-144.us-west-2.compute.internal systemd[1]: kubelet.service holdoff time over, scheduling restart.
```

**Comment by felix-zhe-huang** [comment]
This issue is related to #1802 since it added a new exception domain `node.kubernetes.io` that will potentially causes similar problems.

**Comment by olemarkus** [comment]
I saw kOps mentioned here, but I'm not sure what needs discussing. kOps is free to set labels in this namespace.

If I remember correctly, I implemented a filter preventing karpenter from setting these labels through kubelet.

**Comment by bwagner5** [comment]
https://github.com/aws/karpenter-core/blob/d04b91e893e75951ff29b6ff1dc4c43060b2a65a/pkg/apis/v1alpha5/labels.go#L70
