### ISSUE TITLE
Question about spot instances and cost

### ISSUE THREAD

**Issue by funes79** [aws/karpenter#1886]
I would like to explore the costs incurred by the auto scaled nodes. According to AWS ec2 the `describe-spot-fleet-request-history` can help with that but I need `spot-fleet-request-id`. Does Karpenter create a spot fleet request? Is it possible to get the spot-fleet-request-id from karpenter's logs? 

Or is there any other way how to report out how many instances were started at what price?
Thanks

**Is an existing page relevant?**

**What karpenter features are relevant?**
Logging

**How should the docs be improved?**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Metric being added here https://github.com/aws/karpenter/pull/3613. I'll close this, feel free to re-open if you want other specific metrics.
