### ISSUE TITLE
Nodes hitting max-volume limit still considered eligible for pods by Karpenter?

### ISSUE THREAD

**Issue by diranged** [aws/karpenter#1888]
## Version

**Karpenter**: v0.10/1

**Kubernetes**: v1.22.6-eks-7d68063

## Background

We have certain workloads that mount a lot of PVCs to our EC2 nodes. Because these EC2 nodes are Nitro nodes, they share their "attachment limits" between ENI and EBS volumes. To try to minimize the situation where we run out of ENIs because of EBS volume mounts, we pass in `--volume-attach-limit=15` to our aws-ebs-csi-driver chart, expecting that the chart will set the "attachable-volumes-aws-ebs" status on the nodes to 15. However, as I have reported in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1258, we still see that value set to 39.

## Expected Behavior

To some extent, I expect that Karpenter should be able to monitor for _all_ reasons why a pod may not be scheduled onto a host ... and once it has not been scheduled for long enough, it should try to launch new hardware if one of the provisioners matches the general requirements for the pod.

In this specific case, I expect Karpenter to fully understand the way the aws-ebs-csi-driver works and honor whatever max-volume setting we have applied.

## Actual Behavior

When our nodes have available CPU and Memory, but have hit the 15 volume limit, we expect that Karpenter will understand this and know that it needs to scale up new hardware. However, instead we see the controller go into a loop where it just keeps indicating that these pods should be scheduled against the "existing  capacity":

```
2022-06-02T00:24:18.865Z	INFO	controller	Batched 15 pod(s) in 10.000533501s	{"commit": "10fc37b"}
2022-06-02T00:24:18.875Z	INFO	controller	0 pod(s) will schedule against new capacity, 15 pod(s) against existing capacity	{"commit": "10fc37b"}
2022-06-02T00:24:18.875Z	INFO	controller	Waiting for unschedulable pods	{"commit": "10fc37b"}
```

Here is the pod-event log:
```
Warning  FailedScheduling   6s (x2 over 22s)  default-scheduler   0/13 nodes are available: 1 Too many pods, 1 node(s) had taint {kubernetes.io/arch: arm64}, that the pod didn't tolerate, 1 node(s) were unschedulable, 5 node(s) exceed max volume count, 5 node(s) had taint {nd.group-name: kube-system}, that the pod didn't tolerate.
```
After trying this out for a few hours and poking around, we had to roll back to allowing our partner (spot.io) to launch hardware and temporarily disable Karpenter.

## Steps to Reproduce the Problem

1. Use EKS 1.22, Karpenter v0.10.6, and Bottlerocket v1.7.2 AMIs to spin up a Kubernetes cluster.
2. Install the aws-ebs-csi-driver chart, and set the max-volume limit to something low (say, 5)
3. Install Karpenter with provisioning that allows it to launch very large hosts that have plenty of CPU/Memory.
4. Spin up a bunch of pods with PVC requirements ... but with very low CPU/Memory requirements.
5. Watch Karpenter decide not to scale up the hardware.

**Comment by diranged** [comment]
cc @tzneal

**Comment by tzneal** [comment]
Related to #919

**Comment by diranged** [comment]
@tzneal,
  Regarding the scheduling... as I understand the documentation, Karpenter only schedules pods on to hardware that it launched. If I understand that correctly, then in this case the log messages that Karpenter is printing out are a little misleading ... they imply that Karpenter is trying to schedule the pod onto existing hardware, but I think it's actually trying to let the `kube-scheduler` do that, right?

  It seems like after some timeout period, we could let Karpenter go ahead and scale up ... eg, if a pod is unscheduled for more than XX minutes (obviously configurable), then if Karpenter thinks it can launch new hardware to solve the problem, it should do that. Would that be a reasonable short term fix?

  Another short-term fix would be to take a configuration parameter (env variable, etc) that lets us tell Karpenter how many volumes can be assigned to a node. Since AWS has already decided that automatically determining that [_is hard_](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/2d9fe32601ff9d7308e12133f8fe5655ff421c1f)**, it seems reasonable to have the same decision here for a cluster administrator.

** *Nitro Nodes* make life pretty difficult here... because ENIs and EBS volumes pull from the same capacity pool, so the actual dynamic value of capacity is very complicated to deal with because it is always changing. Yet, Nitro nodes are the standard for all new EC2 types at this time, and so I don't see this pattern changing any time soon. Given that, a hard-coded setting that we can apply to set the max-volume-limit per node seems like a reasonable approach to me.

**Comment by diranged** [comment]
@tzneal Any further thoughts here? This issue is preventing us from being able to roll out Karpenter unfortunately. We have it all set up and ready to go to do some side by side testing in our production clusters, but we can't with this issue in place. :/

**Comment by diranged** [comment]
> Sorry @diranged , I was on vacation and out last week. I'll be looking into this issue in more detail.

No worries at all, hope it was a good one! Thanks for getting back to me..

**Comment by diranged** [comment]
:+1: awesome, thank you!
