### ISSUE TITLE
Explicitly triggering Karpenter to scale up?

### ISSUE THREAD

**Issue by diranged** [aws/karpenter#1889]
**Tell us about your request**

I'd like there to be a mechanism to force Karpenter to scale up nodes, even when Pods are not in a `Pending` state. I could imagine it is an annotation that is applied manually to the `Provisioner` resources.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

There are going to be situations where we need more hardware to be scheduled, even if Pods may not be requesting it yet. Whether that is pre-scaling for some event, or due to a scaling bug (eg https://github.com/aws/karpenter/issues/1888) where Karpenter is not scaling up even though we need it to. Most other managed platforms provide a mechanism to tell the system to scale up "anyways".

**Are you currently working around this issue?**

Right now we have a shortcut tool for launching a pod with specific node selectors, and we just launch a blank pod that has that selector.. but that is clumsy.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Hey @diranged, thanks for opening this issue. 

Can you expand more on how you might want to see these surfaced as controls? [Here](https://github.com/aws/karpenter/issues/987) is a feature request for overprovisioning, does this fit the same use-case? 

In any case, forcing Karpenter to scale up when there are no pending pods would need to also implement special scale-down logic in order to maintain the forced extra capacity (think [ttlSecondsAfterEmpty](https://karpenter.sh/v0.10.1/tasks/deprovisioning/#how-karpenter-nodes-are-deprovisioned)). In addition, if you want controls to manually dictate a Provisioner to provision, you also need to dictate the properties of that node and underlying instance, since these properties are computed based on the existing set of pending pods in the cluster.

**Comment by diranged** [comment]
I definitely understand that this isn't a trivial change - it seems that if the user wants to scale up nodes explicitly, there is going to have to be some amount of configuration available to them at the time to do it. I could imagine a few different scenarios.

**Launch a node, any node**

Launch a single node.. any node that could be launched by the Provisioner. Perhaps in this mode, its a random lottery for which node type gets launched.

```
$ kubectl annotate provisioner default karpenter.sh/launch=1
provisioner.karpenter.sh/default annotated
```

**Launch a specific node type**

Launching a specific node type from a Provisioner...  allowing us to proactively launch X number of a specific instance type.

```
$ kubectl annotate provisioner default karpenter.sh/launch/c6i.4xlarge=10
provisioner.karpenter.sh/default annotated
```

**Setting the TTL for manually launched nodes**

When manually launching a node, I could imagine that the Provisioner has a TTL that is set as part of its configuration.... `.spec.ttlGracePeriodAfterManualLaunch: 3600`. When a manually launched node is created, the node could be annotated immediately with this grace period, and only after that grace period would the node become eligible for "normal" lifecycle behaviors.

**Comment by diranged** [comment]
Oh here's another one that would be useful:

**Rolling replacement of all nodes in a Provisioner**

```
$ kubectl annotate provisioner default karpenter.sh/roll=true
```

This would be useful to let the provisioner do a rolling replacement of nodes. Obviously this adds a lot of logic, but we use this functionality regularly in our Spot.io managed groups.

**Comment by ellistarn** [comment]
Related: https://github.com/aws/karpenter/issues/2050
