### ISSUE TITLE
ERROR   controller.aws.launchtemplate   Unable to hydrate the AWS launch template cache,

### ISSUE THREAD

**Issue by gentitope** [aws/karpenter#1899]
## Version

**Karpenter**: v0.10.1

**EKS**: v1.22

## Expected Behavior

Expected the controller pod start

## Actual Behavior

Back-off restarting failed container

## Steps to Reproduce the Problem

New EKS Cluster Setup

## Resource Specs and Logs

 kubectl -n karpenter  logs -f karpenter-6989b5d849-lbrcx -c controller

2022-06-06T09:43:49.666Z        INFO    Successfully created the logger.
2022-06-06T09:43:49.666Z        INFO    Logging level set to: debug
2022-06-06T09:43:49.770Z        INFO    controller      Initializing with version v0.10.1       {"commit": "10fc37b"}
2022-06-06T09:43:49.770Z        DEBUG   controller.aws  Using AWS region us-east-2      {"commit": "10fc37b"}
{"level":"info","ts":1654508629.7703185,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
2022-06-06T09:43:49.770Z        DEBUG   controller.aws  Discovered caBundle, length 1099        {"commit": "10fc37b"}
2022-06-06T09:43:49.770Z        DEBUG   controller.aws.launchtemplate   Hydrating the launch template cache with names matching "Karpenter-credkin-dev-*"       {"commit": "10fc37b"}
2022-06-06T09:44:19.469Z        ERROR   controller.aws.launchtemplate   Unable to hydrate the AWS launch template cache, RequestCanceled: request context canceled
caused by: context canceled     {"commit": "10fc37b"}
2022-06-06T09:44:19.469Z        DEBUG   controller.aws.launchtemplate   Finished hydrating the launch template cache with 0 items       {"commit": "10fc37b"}

kubectl -n karpenter  logs -f karpenter-6989b5d849-lbrcx -c webhook

{"level":"error","ts":1654508669.4692636,"logger":"fallback.aws.launchtemplate","caller":"aws/launchtemplate.go:229","msg":"Unable to hydrate the AWS launch template cache, RequestCanceled: request context canceled\ncaused by: context canceled","stacktrace":"github.com/aws/karpenter/pkg/cloudprovider/aws.(*LaunchTemplateProvider).hydrateCache\n\tgithub.com/aws/karpenter/pkg/cloudprovider/aws/launchtemplate.go:229\ngithub.com/aws/karpenter/pkg/cloudprovider/aws.NewLaunchTemplateProvider\n\tgithub.com/aws/karpenter/pkg/cloudprovider/aws/launchtemplate.go:70\ngithub.com/aws/karpenter/pkg/cloudprovider/aws.NewCloudProvider\n\tgithub.com/aws/karpenter/pkg/cloudprovider/aws/cloudprovider.go:92\ngithub.com/aws/karpenter/pkg/cloudprovider/registry.newCloudProvider\n\tgithub.com/aws/karpenter/pkg/cloudprovider/registry/aws.go:27\ngithub.com/aws/karpenter/pkg/cloudprovider/registry.NewCloudProvider\n\tgithub.com/aws/karpenter/pkg/cloudprovider/registry/register.go:25\nmain.main\n\tgithub.com/aws/karpenter/cmd/webhook/main.go:55\nruntime.main\n\truntime/proc.go:250"}
2022/06/06 09:44:29 Registering 2 clients
2022/06/06 09:44:29 Registering 2 informer factories
2022/06/06 09:44:29 Registering 3 informers
2022/06/06 09:44:29 Registering 4 controllers
2022/06/06 09:44:34 Error reading/parsing logging configuration: timed out waiting for the condition: context canceled

**Comment by suket22** [comment]
Could you verify if the node running your Karpenter pod has networking connectivity to the AWS API? 

You might have some security group rules, subnet settings that are causing Karpenter's calls to the EC2 API to timeout. You can verify if Karpenter is able to reach out to the AWS API by looking at CloudTrail logs too.

**Comment by gonfva** [comment]
Hi,
I'm facing exactly the same issue on EKS 1.22, with something based on the Terraform getting started guide (the nodegroup and the EKS cluster were created as different entities). 

The nodes themselves can access the EC2 endpoint (I can run `aws ec2 describe-launch-templates --region us-east-1` from the node where the pod is scheduled), and I believe I have the proper configuration in terms of roles (role for EC2 nodes created independently, role for the controller created with the IRDA terraform module,  now both of them with ec2:* to test). 

The region that appears in the logs (in my case us-east-1) is the one the cluster is running on.

I think I have the proper discovery tags (including the one here https://github.com/aws/karpenter/issues/1919, the security group and the subnets). I assume it might not be strange that I've missed some kind of tag but I've checked a few times already.

In the text `Hydrating the launch template cache with names matching "Karpenter-credkin-dev-*"` on the initial report of this ticket, I also have "Karpenter-{name of cluster}-*". I confirm that I do NOT have launch templates with that format (I assume they will be created by karpenter once it is working)

Similarly I have a 30 second gap between "Hydrating the launch template cache" and the ERROR in the line that follows. It suggests some network timeout, but again, I can reach EC2 from the node. 

I can see the DescribeLaunchTemplates  in Cloudtrail when launched from the instance. I cannot see anything similar denied for role or anything.

Hope this helps.

**Comment by dewjam** [comment]
Hello @gonfva and @gentitope ,
I have seen this in the past when the Karpenter containers can't resolve DNS records properly.  Can you confirm CoreDNS is up and running?  Another thing you could try is set the `dnsPolicy` to be "Default", instead of "ClusterFirst" when installing the Helm chart.  

Here's some info on possible Helm values:  https://github.com/aws/karpenter/blob/main/charts/karpenter/README.md

**Comment by gonfva** [comment]
@dewjam Thank you so much!!!!
CoreDNS was already working. But using dnsPolicy as Default fixed the issue for me.
Thanks again!!!

**Comment by dewjam** [comment]
Glad to hear it @gonfva !  It is strange that "ClusterFirst" is not working, though.  It might be worth looking whether other pods are able to resolve DNS records.

Also, here's some more info on this setting from the [K8S docs](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) if you're interested.

**Comment by gentitope** [comment]
yeah..it was DNS issue. EKS was bootstrap to start with node localDns ip and node local dns was to be installed by the time karpenter was installed, so in that case karpenter could not resolve the DNS. After installing the node localDns, the issue got resolved.

Thanks
