### ISSUE TITLE
Support setting node.kubernetes.io/role label

### ISSUE THREAD

**Issue by diranged** [aws/karpenter#1902]
**Tell us about your request**

The `node.kubernetes.io/role` node label is useful for developers and operators alike because it helps identify what "role" a node is intended to support, quickly and easily from the `kubectl get nodes` command. However, this label must be applied _out of band_ from the node itself - kubelet is not allowed to set this label itself.

Karpenter should be able to set this label if we want to ... but for some reason it's listed as a protected label and is not settable in the Provisioner. This seems like a simple feature to support.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by suket22** [comment]
We've got another issue open for this - https://github.com/aws/karpenter/issues/1802 and a PR is in the works - https://github.com/aws/karpenter/pull/1882

**Comment by diranged** [comment]
@suket22 Indeed, thank you! I can close this for now in favor of the more generic #1802.
