### ISSUE TITLE
Only use instances that our listed in eni-max-pods.txt

### ISSUE THREAD

**Issue by rwilliams-r7** [aws/karpenter#1911]
**Tell us about your request**
We have suffered from Karpenter pulling instances that cannot join the cluster as that our not listed in https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt and not supported in the aws-vpc-cni and the amazon ami. This caused the cluster to not be able to scale causing production issues.

Should Karpenter even look at instances that are not on this list?

This causes Karpenter to fall into a loop of trying to start the instance then remove it and in the worse case pulling the same instance type again which means the pod is never started.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are trying to stop possible outages where pods do not start as instances (nodes) are chosen that cannot join the cluster.

We want to use karpenter to select the cheapest/best available instances. However, karpenter should not select instances it knows it can not use/deploy. Karpenter should know what instance types are safe to launch and only launch these

**Are you currently working around this issue?**
Yes

**How are you currently solving this problem?**
Hard coding a NotIn list to remove the ec2 types that are not supported but this is a poor solution.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rwilliams-r7** [comment]
https://github.com/awslabs/amazon-eks-ami/issues/942 -> for reference.

**Comment by suket22** [comment]
I've [made a change](https://github.com/awslabs/amazon-eks-ami/commit/917c62133800999ae4ae49c1df6415261bd645bd) in the bootstrap script to retrieve information about an instanceType from the EC2 API when not present in the eni-max-pods.txt file. This was included as [part of this AMI release](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20220406).

1. Which AMI did you see you this issue on? 
2. Could you provide your UserData execution logs on this instance?

**Comment by tzneal** [comment]
Should be resolved now thanks to @suket22
