### ISSUE TITLE
Feature Request / Question: Karpenter should respect pod limits when selecting an instance type

### ISSUE THREAD

**Issue by snorlaX-sleeps** [aws/karpenter#1913]
**Tell us about your request**
Karpenter should respect pod limits when selecting an instance type for scaling, or at least the largest limit of a pod scheduled onto the node i.e the instance type selected should have enough CPU and memory for a pod to burst to its limits (unsure if this is a configuration issue on our end, but I can't see info on it in the documentation).
I was under the impression this was supported during earlier testing, but it was proven not to be the case

NB: Please read below - I am not sure if this is something that Karpenter should support, but it would make our cluster far more efficient as we would select a compatible instance type for a larger service and other pods could be scheduled with it, then it would use smaller instance types when average sized pods are pending.
With the cluster-autoscaler we would just select a default instance type that would support the limits of these large pods.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have a cluster running Karpenter, which has single provisioner for all services.
This includes things like per-node daemonsets, "core services", as well the main application(s) the cluster is for.

We use a single provisioner as we want all of the services to share the same node pool, as none have any specific requirements and this would allow Karpenter to be the most efficient in terms of cost (current provisioner is using any instance type and both on-demand and spot)

Some of the applications we deploy are very small and thus have low requests / limits.
On the other hand several of the pods we are running have much larger limits - but are given smaller requests as they are not always running anywhere near these limits 60-80% of the time and they could easily share an instance with many other pods.

What we are seeing is that Karpenter will calculate the size of node needed based on the requests of pending pods - as expected with scheduling.
However when our larger pods burst to their limit, the pod will be restarted by K8s as it breaches the resources available on the instance type.

For example:
One pod is only using its set limit of 30 CPU / 32Gb RAM several times a day (e.g 1hr each day in 4 bursts of 15mins).
The rest of the time it would sit around 1 CPU / 5Gb, therefore we give it requests of 5 / 5Gb so that it can be scheduled to share nodes with other services. We can't scale to `0` replicas as it needs to be available to receive webhooks.

In this instance what we are seeing is the pod being scheduled onto `c5.4xlarge` nodes, which only have 16 CPU available. Whenever the usage spikes, we are seeing the pod being restarted.

**Are you currently working around this issue?**
We are setting the requests to 16 CPU to ensure that this pod (and doing similar for other large pods) will only be scheduled onto a larger node (may not always work), but this is leaving a lot of wasted CPU and memory during the downtime that could be used for other pods.

**Additional context**
The cluster in question is running multiple [Atlantis installations](https://github.com/runatlantis/atlantis) - each has assigned resources based on the size of the Terraform repository and the number of workspaces, so each installation varies in size and compute requirements. The service is only active when a pull request is opened.

Having a pod restarted due to node termination or via `kubectl` is not an issue, as Kubernetes honours the `terminationGracePeriodSeconds` set in the statefulset. The issue is when it consistently attempts to use more CPU or RAM than is available on the instance and Kubernetes abruptly terminates it.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Karpenter works similarly to the kube-scheduler in that it only considers requests when scheduling. If Karpenter were to consider limits and launch more or larger nodes than necessary, kube-scheduler would still place pods per the pod requests. In general the limits shouldn't be much larger than the requests. There is more specific guidance in the EKS best practices https://aws.github.io/aws-eks-best-practices/reliability/docs/dataplane/#configure-and-size-resource-requestslimits-for-all-workloads

**Comment by snorlaX-sleeps** [comment]
Thanks @tzneal, I thought it might be the case.
I'll take a look into one of the resource/limits monitors and adjust how we size the services. The service in question is highly burstable by nature and it just seemed wasteful to set `requests==limits` like we would do normally as the instances would be under-utilised a lot of the time.
Afaik cluster-autoscaler advises setting limits
