### ISSUE TITLE
ephemeral ec2 storage

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/karpenter#1916]
**What karpenter features are relevant?**
blockDeviceMappings

**How should the docs be improved?**
Is there docs on how to mount ec2 ephemeral instance storage in the provider block?
for both AL and Bottlerocket

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by suket22** [comment]
Are you referring to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html ?
* AL2 - You would need to mount those via your UserData. See https://github.com/awslabs/amazon-eks-ami/issues/326 for more detail.  `BlockDeviceMappings` will only work for your EBS volumes. 
* BR - https://github.com/bottlerocket-os/bottlerocket/issues/1209 seems to have detail on how to get that done.

**Comment by FernandoMiguel** [comment]
Thanks.
I'll take a look tomorrow.

I remember reading something about VPC CNI not supporting ephemeral disk instances..

Do you know if that is still the case?

**Comment by suket22** [comment]
I'm not entirely sure about that one, couldn't find any information with some searching either.

**Comment by rafilkmp3** [comment]
would be nice if karpenter could detect if instance has something to if instance has instance storage 


```    preBootstrapCommands:
      - "mkfs -t ext4 /dev/nvme1n1"
      - "mkdir -p /ephemeral1"
      - "mount /dev/nvme1n1 /ephemeral1"
      - "chown ec2-user:ec2-user /ephemeral1"```

**Comment by rafilkmp3** [comment]
@suket22  +1
