### ISSUE TITLE
Custom launch template requires appropriate tag (while using Terraform irsa module)

### ISSUE THREAD

**Issue by vi-credo** [aws/karpenter#1919]
**Is an existing page relevant?**
[Launch template for provisioner](https://karpenter.sh/v0.10.1/aws/launch-templates/#define-launchtemplate-for-provisioner) and/or [Getting Started with Terraform](https://karpenter.sh/v0.10.1/getting-started/getting-started-with-terraform)

**What karpenter features are relevant?**
Custom launch template.

**How should the docs be improved?**
Disclaimer - I deployed all resources following Getting Started with Terraform page.

I was going though the process of creating a custom launch template (mainly for bootstrapping script), and I was stuck with UnauthorizedOperation error. The reason ended up being missing `karpenter.sh/discovery` tag on the launch template itself (with the value of cluster's name). This was due to using that Terraform irsa module that creates a policy with a resource tag condition by default including launch templates as well. I believe it would be nice to mention that user is also responsible to tag custom resources accordingly.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by suket22** [comment]
Thanks for reporting this. It's difficult to synchronize Karpenter docs and the Terraform module in general, but in this case, I'm not sure why that tag based access was required on the launch template. 

I think we should consider removing [this line](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/2f1b2bf80501b472be620c88e6339c4f622d4800/modules/iam-role-for-service-accounts-eks/policies.tf#L555) from the terraform module, rather than modifying the Karpenter documentation. 

Having said that, now that we will start supporting a flat list of subnetIds and not always use tag based discovery, some folks might even run into this issue in a different flavor - [missing tags on the security groups](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/2f1b2bf80501b472be620c88e6339c4f622d4800/modules/iam-role-for-service-accounts-eks/policies.tf#L556). 

@bryantbiggs what are your thoughts on this?

**Comment by bryantbiggs** [comment]
The tag is applied to ensure the Karpenter IRSA role can only create/destroy resources created by Karpenter. I agree that it is confusing that currently users are on the hook for adding the tag to the provisioner where it would be preferable if  Karpenter automatically tagged resources based on a defined standard - similar to what services like CloudFormation do:

```
    aws:cloudformation:logical-id
    aws:cloudformation:stack-id
    aws:cloudformation:stack-name
```

This ensures the permissions provided are scoped to only permit managing the lifecycle of those resources created by the provisioner. Something like:

```
  karpenter:cluster-id
```

**Comment by vi-credo** [comment]
Definitely agree on the idea to protect resources from modification/deletion. Therefore, it probably make sense to require such tags on modification/deletion actions and not in read actions (I assume RunInstances is read in this context). Probably should open an issue in Terraform module to apply more granular permissions (or actually I can play myself around and find appropriate required permissions 🙂)

**Comment by vi-credo** [comment]
If I understood it correctly, then tag enforcement should be in the following [statement](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/2f1b2bf80501b472be620c88e6339c4f622d4800/modules/iam-role-for-service-accounts-eks/policies.tf#L566) for instance, volume and network interface, since these are basically the only resources that Karpenter creates as part of it's basic funcitonality (I actually don't understand why there is no tag condition there as well, similar to launch template and security groups statement). By allowing users to customize launch template, basically to bring their own, it is possible that Karpenter won't have to create/delete it. Same applies to security groups. Therefore, tag enforcement on those resources for [create operation](https://docs.aws.amazon.com/systems-manager/latest/userguide/automation-action-runinstance.html) doesn't make much sense in my opinion.

**Comment by dewjam** [comment]
Hey @vi-credo ,
I figured I'd chime in given I've done some testing recently which might be of value to this discussion.

>If I understood it correctly, then tag enforcement should be in the following [statement](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/2f1b2bf80501b472be620c88e6339c4f622d4800/modules/iam-role-for-service-accounts-eks/policies.tf#L566) for instance, volume and network interface, since these are basically the only resources that Karpenter creates as part of it's basic funcitonality (I actually don't understand why there is no tag condition there as well, similar to launch template and security groups statement)

Only certain conditions are supported for the RunInstances action.  The conditions which are supported depends on the resource type in the statement.  For example instance, volume, and network-interface resources types do not support conditions which query "aws:ResourceTag".  [Here is a great doc](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html) which outlines the conditions which are supported per resource for the RunInstances Action.

>By allowing users to customize launch template, basically to bring their own, it is possible that Karpenter won't have to create/delete it. Same applies to security groups. Therefore, tag enforcement on those resources for [create operation](https://docs.aws.amazon.com/systems-manager/latest/userguide/automation-action-runinstance.html) doesn't make much sense in my opinion.

When conditions are used with the RunInstances action, they limit which resources can be used or referenced when launching an instance.  A simple example is using tag enforcement on subnets to limit which subnets an instance can be launched within.  In the case of Karpenter, the IAM policy is limiting Karpenter so it can only launch instances using specific Security Groups and Launch Templates (those which have the ResourceTag defined in the IAM policy).

[Here is more info](https://aws.amazon.com/blogs/aws/amazon-ec2-resource-level-permissions-for-runinstances/#:~:text=Using%20EC2%20Resource%2Dlevel%20Permissions,of%20a%20call%20to%20RunInstances.) on resource-level permissions for the RunInstances action if you're interested.

Hopefully you find this info to be helpful!

**Comment by dewjam** [comment]
One other quick note.  Instance, volume, and network-interface resources support the "aws:RequestTag" condition when used with the RunInstances action.  This requires the RunInstances request to include a specific tag for resources it creates, otherwise the request will be denied.
