### ISSUE TITLE
Failed to download karpenter helm chart error

### ISSUE THREAD

**Issue by brettgpalmer** [aws/karpenter#1933]
**Error in Getting Started with Terraform instructions**
I'm seeing the following error when trying to karpenter helm chart via terraform using the example from:

https://karpenter.sh/v0.10.1/getting-started/getting-started-with-terraform/

```
resource "helm_release" "karpenter" {
  namespace        = "karpenter"
  create_namespace = true

  name       = "karpenter"
  repository = "https://charts.karpenter.sh"
  chart      = "karpenter"
  version    = "v0.10.1"
```

The error is failing to download the helm chart from the specified URL.
```
helm_release.karpenter: Creating...
╷
│ Error: could not download chart: failed to download "https://charts.karpenter.sh/karpenter-0.10.1.tgz" at version "v0.10.1"
│ 
│   with helm_release.karpenter,
│   on main.tf line 25, in resource "helm_release" "karpenter":
```

I was able to work around the error by downloading the helm chart locally and then references the file in my terraform.

```
  chart = "./helm_charts/karpenter-0.10.1.tgz"
```

Is anyone else having this same problem?  Is there a better workaround for the error?

Thanks

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
can you try with 0.11.0 ?

**Comment by bpalmerutah** [comment]
Thanks for the quick reply but I got the same error using karpenter v0.11.0 as well.  Here is the terraform resource and the error:

resource "helm_release" "karpenter" {
  namespace        = "karpenter"
  create_namespace = true
  verify = false

  name       = "karpenter"
  repository = "https://charts.karpenter.sh"
  chart      = "karpenter"
  version    = "v0.11.0"

Error:  helm_release.karpenter: Modifying... [id=karpenter]
╷
│ Error: failed to download "https://charts.karpenter.sh/karpenter-0.11.0.tgz" at version "v0.11.0"
│ 
│   with helm_release.karpenter,
│   on main.tf line 24, in resource "helm_release" "karpenter":

**Comment by FernandoMiguel** [comment]
I'm not a developer, just a user of this chart.
I tried both 0.10.1 and 0.11.0 today in a dev cluster and it worked fine, as did the upgrade.
Sorry I can't be of more help.

**Comment by brettgpalmer** [comment]
Thanks for your help.  It was worth a try.  I'm checking if there is a restriction on the egress settings for the VPC.  I have a work around for now.

**Comment by bizonek27** [comment]
I had the same problem after deleting the helm cache. Please try:
`rm -rf ~/.config/helm/ ~/.cache/helm/`

**Comment by brettgpalmer** [comment]
> I had the same problem after deleting the helm cache. Please try: `rm -rf ~/.config/helm/ ~/.cache/helm/`

Thanks I cleared the HELM_REPOSITORY_CONFIG and HELM_REPOSITORY_CACHE and was able to deploy the helm chart.

**Comment by applike-ss** [comment]
Had the same issue today with different charts and a simple `helm repo update` fixed it for me cleanly
