### ISSUE TITLE
Karpenter does not scale up nodes

### ISSUE THREAD

**Issue by qwert9917** [aws/karpenter#1935]
## Version

**Karpenter**: v0.7.3

**Kubernetes**: v1.22.6

Hi all, 

My eks cluster is v1.22.6

I am implementing Karpenter v0.7.3 using terraform module eks v17.24.0 by following this documentation >>>
https://karpenter.sh/v0.7.3/getting-started/getting-started-with-terraform/

the reason why I am using Karpenter v0.7.3 bc the latest karpenter version doc requires me to start up a new eks managed node group which I don't want

I have enabled irsa and using oidc issuer url 
configured IAM roles

code like below, this part is pretty much same like the doc

```
data "aws_iam_policy" "ssm_managed_instance" {
  arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_role_policy_attachment" "karpenter_ssm_policy" {
  role       = module.eks.worker_iam_role_name
  policy_arn = data.aws_iam_policy.ssm_managed_instance.arn
}

resource "aws_iam_instance_profile" "karpenter" {
  name = "KarpenterNodeInstanceProfile-${var.eks_cluster_name}"
  role = module.eks.worker_iam_role_name
}

module "iam_assumable_role_karpenter" {
  source                        = "terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc"
  version                       = "4.7.0"
  create_role                   = true
  role_name                     = "karpenter-controller-${var.eks_cluster_name}"
  provider_url                  = module.eks.cluster_oidc_issuer_url
  oidc_fully_qualified_subjects = ["system:serviceaccount:karpenter:karpenter"]
}

resource "aws_iam_role_policy" "karpenter_controller" {
  name = "karpenter-policy-${var.eks_cluster_name}"
  role = module.iam_assumable_role_karpenter.iam_role_name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = [
          "ec2:CreateLaunchTemplate",
          "ec2:CreateFleet",
          "ec2:RunInstances",
          "ec2:CreateTags",
          "iam:PassRole",
          "ec2:TerminateInstances",
          "ec2:DescribeLaunchTemplates",
          "ec2:DeleteLaunchTemplate",
          "ec2:DescribeInstances",
          "ec2:DescribeSecurityGroups",
          "ec2:DescribeSubnets",
          "ec2:DescribeInstanceTypes",
          "ec2:DescribeInstanceTypeOfferings",
          "ec2:DescribeAvailabilityZones",
          "ssm:GetParameter"
        ]
        Effect   = "Allow"
        Resource = "*"
      },
    ]
  })
}

resource "helm_release" "karpenter" {
  depends_on       = [module.eks.kubeconfig]
  namespace        = "karpenter"
  create_namespace = true

  name       = "karpenter"
  repository = "https://charts.karpenter.sh"
  chart      = "karpenter"
  version    = "v0.7.3"

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = module.iam_assumable_role_karpenter.iam_role_arn
  }

  set {
    name  = "clusterName"
    value = var.eks_cluster_name
  }

  set {
    name  = "clusterEndpoint"
    value = module.eks.cluster_endpoint
  }

  set {
    name  = "aws.defaultInstanceProfile"
    value = aws_iam_instance_profile.karpenter.name
  }
}
```

the eks module is using worker node groups and launch template. there is no eks managed node group.

```
module "eks" {
  source                    = "terraform-aws-modules/eks/aws"
  version                   = "17.24.0"
  cluster_name              = var.eks_cluster_name
  cluster_version           = var.eks_cluster_version
  subnets                   = aws_subnet.services.*.id
  vpc_id                    = aws_vpc.main.id
  cluster_enabled_log_types = var.eks_cluster_enabled_log_types

  worker_groups                 = var.eks_worker_groups
  worker_groups_launch_template = var.eks_worker_groups_launch_template
  worker_security_group_id      = aws_security_group.worker_group.id

  write_kubeconfig = false

  map_roles    = var.eks_map_roles
  map_users    = var.eks_map_users
  map_accounts = var.eks_map_accounts

  enable_irsa = true
  tags = {
    "karpenter.sh/discovery" = var.eks_cluster_name
  }
}
```

the worker node group contain a couple worker group inside and the kubelet_extra_args specify nodegroup name

eg. 
```
{
    name                 = "bla"
    instance_type        = "m3.2xlarge"
    asg_desired_capacity = 1
    asg_min_size         = 1
    asg_max_size         = 1
    key_name             = "blas"
    kubelet_extra_args   = "--node-labels=cluster=bla-cluster,nodegroup=bla --kube-reserved=cpu=xxxm,memory=xxxGi,ephemeral-storage=xxGi --system-reserved=cpu=xxxm,memory=xxxGi,ephemeral-storage=xxxGi --register-with-taints=bla=true:NoSchedule"
  },
```

also in eks module has been specify launch template

```
eks_worker_groups_launch_template = [
  {
    name                    = "spot"
    override_instance_types = ["c4.2xlarge","c3.2xlarge"]
    spot_instance_pools     = xxx
    asg_min_size            = xxx
    asg_max_size            = xxx
    asg_desired_capacity    = xxx
    key_name                = "blas"
    kubelet_extra_args      = "--node-labels=node.kubernetes.io/lifecycle=spot --kube-reserved=cpu=xxxm,memory=xxxGi,ephemeral-storage=xxGi --system-reserved=cpu=xxxm,memory=xxxGi,ephemeral-storage=xxxGi"
    additional_userdata     = "xxxx"
  }
]
```

## Expected Behavior

karpenter should help to scale up nodes when I scale up inflate or any deployments in the cluster.

## Actual Behavior

karpenter did not scale up nodes after I scale-up deployments. I reckon the launch template did starting up nodes as nodes created are from the instance type in ["c4.2xlarge","c3.2xlarge"]

## Resource Specs and Logs

```
ERROR	controller.controller.volume	Reconciler error	{"commit": "xxxx", "reconciler group": "", "reconciler kind": "PersistentVolumeClaim", "name": "xxxx", "namespace": "xxxx", "error": "binding persistent volume claim for pod xxxxx to node \"ip-xxxxxxx\", Operation cannot be fulfilled on persistentvolumeclaims \"xxxxxx\": the object has been modified; please apply your changes to the latest version and try again"}
```

or 

```
controller.selection	Could not schedule pod, matched 0/1 provisioners, tried provisioner/default: incompatible requirements, [one-of-node-group] not in [], key nodegroup	{"commit": "xxx", "pod": "xxxxx"}
```

Anyone could help? thank you so much.

**Comment by qwert9917** [comment]
> > the reason why I am using Karpenter v0.7.3 bc the latest karpenter version doc requires me to start up a new eks managed node group which I don't want
> 
> I doubt that this is a hard requirement, have you by any chance tried to use `worker_groups` instead of `eks_managed_node_groups` with latest version? I would highly advise using the later/latest versions as we have already addressed many of the issues.

I started to use the latest version by following the doc but new issues came up.

```
container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
```

the doc for the latest version to solve cni by adding additional policy, but I am using eks module v17.24 and worker node. so there is no that kind of variables allow me to pass arn.

**Comment by ivan-amity** [comment]
facing the same issue as @qwert9917

**Comment by spring1843** [comment]
@ivan-amity are you also using terraform?

**Comment by ivan-amity** [comment]
> @ivan-amity are you also using terraform?

It's not with the terraform.
I'm sorry, I forgot to add my tool. It was with eksctl ( version: 0.101.0 )

**Comment by spring1843** [comment]
You should be able to look at the CNI logs and see more details about why it failed to initialize. 

Also please take a look at some of the helpful comments in https://github.com/aws/karpenter/issues/1391

**Comment by ivan-amity** [comment]
> You should be able to look at the CNI logs and see more details about why it failed to initialize.
> 
> Also please take a look at some of the helpful comments in #1391
@spring1843 Thanks for your comment. It just needs to tag the securityGroupSelector.

**Comment by qwert9917** [comment]
I have the securityGroupSelector setup.
```
securityGroupSelector:
     karpenter.sh/discovery: my cluster name
```
I found out if I set provisioner to amd64. karpenter ran nodes can be ready
but when I change to arm64, it has that cni error.
@spring1843 Could you help with that?

**Comment by dewjam** [comment]
Hey @qwert9917 ,
I haven't seen any updates to this ticket in quite some time.  I'm going to go ahead and close this out as stale, but please feel free to reopen if it continues to be a problem for you.
