### ISSUE TITLE
Non-string type support for AWS Tag values in the Provisoner CRD spec

### ISSUE THREAD

**Issue by morganrowse** [aws/karpenter#1936]
**Tell us about your request**

Hi there,

Thank you for the awesome tool!

Please can you make it so that non-string typed values are supported in the `spec.provider.tags` attribute of the Provisioner CRD

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

We are trying to ensure consistent tagging across our infra to better understand costs in AWS. To do this, we generate a set of standardized tags in our Terraform, which is passed to all infra pieces to identify them to the product they were created for.

We are running Karpenter `0.10.1` via Helm deployed with Terraform

In the Terraform we declare our tags with values of mixed type (string, bool, number)
```terraform
# terraform.tf

locals {
  tags = {
    Terraform   = true
    Root        = "path/to/root/in/git"
    Project     = "productA"
    CostCenterID = 43
    Environment = "Production"
  }
}
```

And then these tags are rendered out to a Provsioner spec `values.yaml` using terraform templates
```yaml
# values.yaml.tpl

tags:
  ${indent(2, yamlencode(tags))}
  
# Renders out to
tags:
    Terraform: true
    Root: "path/to/root/in/git"
    Project: "productA"
    CostCenterID: 43
    Environment: "Production"
```
And the above tags block is placed in a Provisioner spec at `spec.provider.tags`

When trying to create a CRD with such tags it will issue error
```
│Error: cannot patch "<provisioner_name>" with kind Provisioner: admission webhook "validation.webhook.provisioners.karpenter.sh" denied the request: validation failed: v1alpha1.AWS.Tags: ReadString: expects " or n, but found t, error found in #10 byte of ...|rraform":true}}|..., bigger context ...|","root":"path/to/root/in/git","Terraform":true}}|...:  
```

The issue seems to be that Karpenter expects only strings for Tag values where we are passing strings,bools and numbers.

It would be great if this supported other types of tag values and not just strings. (numbers,bools etc)

**Are you currently working around this issue?**

To work around this we first excluded non-string tags and then did some messy Terraform config to convert to string in the `values.yaml`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Agree with Suket. Feel free to reopen if you'd like to continue the discussion

**Comment by morganrowse** [comment]
Thanks for the Feedback. I would agree with your comment `this code fix rather belongs in Terraform` if it weren't for the amount of other charts we are doing exactly this without issue, including official AWS and third party charts. Of the 10 or so Helm charts that we do AWS tagging from Terraform, this has been the only one so far that requires type conversion.

The [AWS LB Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/values.yaml#L252) chart supports boolean and number type tag values

The [AWS EBS CSI Driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L87) chart supports boolean and number type tag values

The [AWS EFS CSI Driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml#L47) chart supports boolean and number type tag values

Happy to leave closed if you still feel it should be, but please be aware this does not seem to be the route other charts have taken in this regard.

If you need to fix this issue in your Terraform code, this is how you could do it.
```terraform
{for k,v in local.tags: k => tostring(v)}
```

**Comment by ellistarn** [comment]
Keep in mind, our push back is not in changes to the chart, but changes to the Provisioner API (CRD).
