### ISSUE TITLE
Ability to use Price()/InstanceSize() Instead of Price() for defining ec2 instance priority. 

### ISSUE THREAD

**Issue by UnamedRus** [aws/karpenter#1944]
**Tell us about your request**
Ability to prioritize instances with better price per cpu factor in karpenter. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Maximize CPU (or Memory) per cost ratio

Current prices for spot instances:

```
instance type     per hour     per cpu*hour
m5.8xlarge        $0.4189       $0.0523
m5.12xlarge       $0.4844       $0.0403
m5zn.12xlarge     $0.4871       $0.0405
```
From this pricing 12xlarge looks like a much more efficient choice. 

There are also amd based m5ad instances:

```
m5ad.8xlarge      $0.3193    $0.0399
m5ad.12xlarge     $0.4789    $0.0399
m5ad.16xlarge     $0.6385    $0.0399
```

But they are slower bc of lower Turbo CPU clock speed (we either should exclude instances with that different CPU freq, either to use it our estimations as well).

**Are you currently working around this issue?**
No

**Attachments**
https://github.com/aws/karpenter/blob/7d2414be24220e7b0e24f4a981c6fd0df4fdcd06/pkg/controllers/provisioning/scheduling/scheduler.go#L39

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by billrayburn** [comment]
Closing in favor of https://github.com/aws/karpenter/issues/4136

**Comment by UnamedRus** [comment]
Moved to https://github.com/aws/karpenter-provider-aws/issues/5163
