### ISSUE TITLE
Karpenter does not delete nodes when the cluster is deleted

### ISSUE THREAD

**Issue by zenbones** [aws/karpenter#1955]
We've been experimenting with karpenter, which has involved putting up and removing clusters, which we do with terraform. We noticed that we have a bunch of 'orphaned' nodes we've been paying for after the clusters have been removed. With the cluster-autoscaler, when we delete the cluster the ASGs and the nodes are all removed, so it was an unwelcome monetary surprise to find we had nodes created by karpenter and tagged for deleted clusters still operating. I understand that removing karpenter should not delete the nodes it was controlling, but it seems like deleting the EKS cluster definitely should.

**Comment by ellistarn** [comment]
We just made a change where deleting a provisioner will clean up nodes to catch this exact use case. This catches many cases, but if you just delete the cluster, it's possible that karpenter will be uninstalled and won't be able to execute the cleanup. In that case, you could include a cleanup script in your cluster deletion logic to delete instances tagged by karpenter.

**Comment by zenbones** [comment]
Thank you. Does that change, 'just made' have an associated version number?

**Comment by dewjam** [comment]
Hey @zenbones .  Try out v0.12.1 to test the change: https://github.com/aws/karpenter/releases/tag/v0.12.0

**Comment by zenbones** [comment]
Thank you! I'll add that as Karpenter is an AWS product, and the nodes are tagged, that deleting those nodes when the cluster is deleted seems like something AWS could do. That said, we install with terraform via helm, and therefore uninstall with terraform and helm as well, so Karpenter should get a chance to properly clean up.
