### ISSUE TITLE
Karpenter doesn't support new 6th generation instance types with AWS_ENABLE_POD_ENI = true

### ISSUE THREAD

**Issue by maksym-iv** [aws/karpenter#1965]
## Version

**Karpenter**: v0.11.1

**Kubernetes**: v1.22.9

## Expected Behavior
Karpenter should support `c6i.*`, `c6a.*`, `m6i.*`, `m6a.*` EC2 instance types with `AWS_ENABLE_POD_ENI = true`.
New 6th gen instances are listed in the [supported instances list](https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/pkg/aws/vpc/limits.go)

## Actual Behavior
Karpenter does not support `c6i.*`, `c6a.*`, `m6i.*`, `m6a.*` EC2 instance types with `AWS_ENABLE_POD_ENI=true`.

## Steps to Reproduce the Problem
* Create EKS cluster
* Follow [Security groups for pods](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html#supported-instance-types) guide
* Schedule a pod with security group and any c6i.*, c6a.*, m6i.*, m6a.* instance type selector.

## Notes
Core of the issue seems to be in the fact that `github.com/aws/amazon-vpc-resource-controller-k8s` `v1.1.0` is used, which doesn't have 6th gen listed with `IsTrunkingCompatible: true`/`BranchInterface > 0`, `v1.1.3` already has them.

## Resource Specs and Logs
```
Could not schedule pod, incompatible with provisioner "default", no instance type satisfied resources {"cpu":"200m","memory":"256Mi","pods":"1","vpc.amazonaws.com/pod-eni":"1"} and requirements karpenter.sh/capacity-type In [on-demand], karpenter.sh/provisioner-name In [default], node.kubernetes.io/instance-type In [c6i.large], kubernetes.io/arch In [amd64]
```

```
Could not schedule pod, incompatible with provisioner "default", no instance type satisfied resources {"cpu":"200m","memory":"256Mi","pods":"1","vpc.amazonaws.com/pod-eni":"1"} and requirements karpenter.sh/provisioner-name In [default], node.kubernetes.io/instance-type In [c6a.large], kubernetes.io/arch In [amd64], karpenter.sh/capacity-type In [on-demand]
```

```
Could not schedule pod, incompatible with provisioner "default", no instance type satisfied resources {"cpu":"200m","memory":"256Mi","pods":"1","vpc.amazonaws.com/pod-eni":"1"} and requirements karpenter.sh/capacity-type In [on-demand], node.kubernetes.io/instance-type In [m6a.large], kubernetes.io/arch In [amd64], karpenter.sh/provisioner-name In [default]
```

**Comment by tzneal** [comment]
The new types are included and we automatically pull the latest version of this file now.
