### ISSUE TITLE
Karpenter believes pods to be scheduled will not fit on requisite nodes

### ISSUE THREAD

**Issue by JamesWojewoda** [aws/karpenter#1969]
## Version

**Karpenter**: v0.11.0

**Kubernetes**: v1.22.9-eks-a64ea69

## Expected Behavior

Karpenter calculates and schedules node from list on provisioner, schedules pods associated with provisioner
## Actual Behavior

Getting error that states that the requirements do not fit what karpenter can do, possibly claiming no node can fit said pods
## Steps to Reproduce the Problem

See resource specs for workloads scheduled. average pods usually are about 1 vcpu and 2000 Mi memory
## Resource Specs and Logs

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  labels:
    app.kubernetes.io/instance: karpenter
  name: foo
spec:
  labels:
    dedicated: foo
    eks.amazonaws.com/capacityType: SPOT
  provider:
    amiFamily: Bottlerocket
    blockDeviceMappings:
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 64Gi
    securityGroupSelector:
      Name: foo-eks_worker_sg
    subnetSelector:
      karpenter.sh/discovery: foo-eu-west-1
    tags:
      Name: foo-eu-west-1-worker-node
      eks:cluster-name: foo-eu-west-1
  providerRef:
    name: bottlerocket
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - m5.16xlarge
    - m5a.16xlarge
    - m5d.16xlarge
    - m5n.16xlarge
    - m5ad.16xlarge
    - m5dn.16xlarge
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - eu-west-1a
    - eu-west-1b
    - eu-west-1c
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
status: {}
```

logs
```
incompatible with provisioner "foo", no instance type satisfied resources {"cpu":"1010m","memory":"2058Mi","pods":"1"} 
and requirements karpenter.sh/provisioner-name In [foo], dedicated In [foo], eks.amazonaws.com/capacityType In [SPOT], 
topology.kubernetes.io/zone In [eu-west-1a eu-west-1b eu-west-1c], kubernetes.io/arch In [amd64], node.kubernetes.io/instance-type 
In [m5.16xlarge m5a.16xlarge m5ad.16xlarge m5d.16xlarge m5dn.16xlarge and 1 others], karpenter.sh/capacity-type In [spot]
```

daemonset output
```
aws-node	{"requests":{"cpu":"25m"}}
ebs-csi-node	{}
kube-proxy	{"requests":{"cpu":"100m"}}
datadog-agent	{}
fluentd-elasticsearch	{}
grafana-agent-logs	{}
prom-foo-prometheus-node-exporter	{}
consul-consul	{"limits":{"cpu":"100m","memory":"1Gi"},"requests":{"cpu":"100m","memory":"1Gi"}}
```

**Comment by dewjam** [comment]
Hey @JamesWojewoda ,
I've been trying to reproduce this problem with your provisioner spec and Karpenter v0.11.0 and have not been successful thus far.  This might be a silly question, but is it possible the availability zones are not correctly defined in this provisioner spec?

**Comment by JamesWojewoda** [comment]
@dewjam Rechecked that and that should be good. Forgot to report in that for some reason, upgrading to karpenter 0.12 and downgrading to 0.11 fixed my issue. No change on the provisioners, I'm beginning to think this is an issue with the state of the cluster at the time, or maybe with bottlerocket being used.

**Comment by dewjam** [comment]
Thanks @JamesWojewoda .  I'm going to go ahead and close this out.  If you find any other relevant logs or would like to dive a bit deeper, please feel free to reopen the issue.
