### ISSUE TITLE
Allow allocating storage capacity based on instance type 

### ISSUE THREAD

**Issue by tonylsw** [aws/karpenter#1995]
**Tell us about your request**
When using custom launch template with Karpenter, a single node storage capacity (specified in the launch template) is used by all types of instances launched by Karpenter. We'd like to able to allocate storage capacity based on instance type.

For example:
m5.xlarge: /dev/sdf=100
m5.2xlarge /dev/sdf=200

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Currently Karpenter using a single volume capacity for all types of instances, it's not possible to allocate volume based on instance type.

Using multiple provisioners, one for each instance type, can support this, but the instance launched in such case is undeterministic  
and not optimal.

**Are you currently working around this issue?**

Have to specify the maximum volume size in the launch template in order to avoid running out of disk.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dewjam** [comment]
Hey @tonylsw,
Thanks for creating this issue and sorry for the delayed response.  Would you be willing to share more info regarding your use-case?  Are you looking to scale storage based on instance types to accommodate container images and filesystems?  Or are you allocating local ephemeral storage to pods/containers?

**Comment by tonylsw** [comment]
Hi @dewjam ideally, we'd like to have a solution to scale up/down node storage on-demand, much like Karpenter does for pod :-) , short of that, we'd like to allocate storage based on instance type for container images.

**Comment by carlesjavierre** [comment]
@dewjam Do we have any news regarding this/these (maybe they can be considered different) features?

**Comment by dewjam** [comment]
Hey @carlesjavierre ,
My apologies for the delayed response.  For your use-case, you could expand a nodes storage from the default (20GB) by defining a Block Device Mapping in the Karpenter Provisioner.  Take a look at the docs and let me know if that helps:  https://karpenter.sh/v0.14.0/aws/provisioning/#block-device-mappings

**Comment by dewjam** [comment]
>ideally, we'd like to have a solution to scale up/down node storage on-demand, much like Karpenter does for pod :-)

@tonylsw, one feature we've considered is dynamically scaling node storage based on the ephemeral-storage requested by incoming pods.  So for example, if you were to spawn 5 pods each with a request for 20GB of ephemeral-storage, then Karpenter will provision a node with 100GB + overhead to accomodate those pods.

I'm curious what your thoughts are on this potential feature.

**Comment by dewjam** [comment]
Closing this in favor of #2394
