### ISSUE TITLE
Custom user data for AL2

### ISSUE THREAD

**Issue by JohnMops** [aws/karpenter#2009]
## Version

**Karpenter**: v0.013.0

**Kubernetes**: v1.20.0

## Expected Behavior
Launch template will be created and used by the provisioner

## Actual Behavior
Controller error

```2022-06-28T06:55:29.927Z	ERROR	controller.provisioning	Provisioning failed, launching node, creating cloud provider instance, getting launch template configs, getting launch templates, creating launch template, parsing custom user data input unreadable user data malformed MIME header: missing colon: "--BOUNDARY"	{"commit": "37c8653"}```

## Steps to Reproduce the Problem
```apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: sample
  namespace: karpenter
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: [ "m5.large", "m5.2xlarge" ]
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  providerRef:
    name: sample
  ttlSecondsAfterEmpty: 3000
  ttlSecondsUntilExpired: 2592000
  taints:
    - key: sample-taint
      effect: NoSchedule
  labels:
    sample: karpenter
---

apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: sample
  namespace: karpenter
spec:
  amiFamily: AL2
  instanceProfile: eks-nodes-us-east-1
  subnetSelector:
    kubernetes.io/cluster/research-us-east-1: shared
  securityGroupSelector:
    kubernetes.io/cluster/research-us-east-1: owned
  userData:  |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"
      
    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"
    
    #!/bin/bash
    yum install -y amazon-ssm-agent
    systemctl enable amazon-ssm-agent && systemctl start amazon-ssm-agent

    --BOUNDARY--
```

Create the above and deploy a pod/deployment

**Comment by JohnMops** [comment]
Even using the example that you provided gives out the same error

**Comment by suket22** [comment]
I wasn't able to reproduce this, still looking into it. I see my nodes come up fine and no errors parsing that UserData. Your UserData looks perfectly fine to me, so it might be something I'm missing. Maybe line-endings, but I'll get back to you on that.

**Comment by JohnMops** [comment]
> I wasn't able to reproduce this, still looking into it. I see my nodes come up fine and no errors parsing that UserData. Your UserData looks perfectly fine to me, so it might be something I'm missing. Maybe line-endings, but I'll get back to you on that.

much appreciated, ive tried typing everything by hand to avoid yaml issues but still cant make it work.

**Comment by suket22** [comment]
We figured this out on Slack so adding a comment here for posterity. The problem in the UserData was in this section - 
```
  userData:  |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"
      
    --BOUNDARY
```

The whitespaces in the line between  `Content-Type: multipart/mixed; boundary="BOUNDARY"` and `--BOUNDARY` is what causes this to become invalid MIME content.
