### ISSUE TITLE
weight provisioners?

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/karpenter#2024]
**What karpenter features are relevant?**
provisioners

**How should the docs be improved?**
We currently deploy a single provisioner with both X64 and ARMv8 archs
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
...
  generation: 1
  name: default-dev-ue1-008-flying-possum
  resourceVersion: "4109"
spec:
  limits:
    resources:
      cpu: 1k
  provider:
    amiFamily: AL2
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        iops: 10000
        throughput: 125
        volumeSize: 100Gi
        volumeType: gp3
    securityGroupSelector:
      aws-ids: sg-xxxx
    subnetSelector:
      aws-ids: subnet-xxx
    tags:
      Environment: dev
  requirements:
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
    - on-demand
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - c6a.large
    - c6g.large
    - c6i.large
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
    - arm64
  ttlSecondsAfterEmpty: 120
  ttlSecondsUntilExpired: 2592000
status:
  resources:
    attachable-volumes-aws-ebs: "39"
    cpu: "2"
    ephemeral-storage: 113224684Ki
    memory: 3915268Ki
    pods: "29"
```

Our question is if there is an option to have two provisioners, one per arch but with different weights in each.
We want to offer both arch but not all workloads work on ARM, but we can't currently modify the Deployment for all of them to pin an arch.
If we could influence Karpenter to pick x64 over ARMv8 (it tends to pick graviton cause it is cheaper, I believe), and then specific workloads that pick arm arch would ask for those specific nodes.

Thanks

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Very supportive of this. +1 for using similar semantic to nodeaffinity `weight`. Instead of pod level preferences, this is cluster global preferences.

**Comment by FernandoMiguel** [comment]
Hi team.
Wonder if some of you have any ideas on how best to implement this ?
Thanks in advance.

**Comment by ellistarn** [comment]
Sort the provisioners by weight here. Should be straightforward. https://github.com/aws/karpenter/blob/2844a2461bae20c0792748e6c344f51cf85f31ff/pkg/controllers/provisioning/provisioner.go#L189.

**Comment by ellistarn** [comment]
FYI: this was originally proposed by @stevehipwell here: https://github.com/aws/karpenter/issues/783. @stevehipwell, is this still valuable for you?

**Comment by stevehipwell** [comment]
@ellistarn yes this is still on my wish list.

**Comment by jonathan-innis** [comment]
Further design is needed from the maintainers before we will implement and merge the PR for this feature
