### ISSUE TITLE
Make Karpenter be aware of failure-domain.beta.kubernetes.io/zone of workloads on ASGs

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/karpenter#2025]
**Tell us about your request**
Karpenter should consider existing ASG nodes AZs prior to deploying new nodes for workloads that request topologySpreadConstraints / failure-domain.beta.kubernetes.io/zone

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
On clusters with mixed ASG nodes and Karpenter nodes, workloads will spin up on both EC2 groups.
ASGs tend to balance nodes among AZs.
For Deployments with `topologySpreadConstraints` we have noticed that workloads filling up the ASG nodes, will request Karpenter for more capacity and that while Karpenter will provide nodes in different AZs, it does not take in account existing ASG ones, and sometimes we get unbalanced workloads that have now some pods in the same AZ multiple times.

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
failure-domain.beta.kubernetes.io/zone

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
I can't reproduce this and verified in our code that we don't filter by the node origin when counting topology domains.  

Topology spread doesn't prevent multiple pods from the same deployment from getting scheduled in the same AZ multiple times, it only ensures that the skew between the domains doesn't exceed max-skew.  e.g. 6 pods with a topology spread and 2 per zone is valid.

The complication to this is that `kube-scheduler` is only aware of domains for which nodes already exist.  If you scale up a deployment with a zonal topology spread but there are only nodes in a single zone, then `kube-scheduler` isn't aware of the other zones and will put all of the pods on the existing nodes if they have capacity.  There is an upstream KEP to fix this at: https://github.com/kubernetes/enhancements/issues/3022

**Comment by tzneal** [comment]
We handle topology spread constraints against arbitrary labels.  Is there a specific case where you are seeing Karpenter behave incorrectly?

**Comment by FernandoMiguel** [comment]
I'll do a bit more testing and gather logs and see if I can reproduce it again.
thanks for all the info.
