### ISSUE TITLE
Does karpenter support resident instances?

### ISSUE THREAD

**Issue by hantmac** [aws/karpenter#2045]
Hi there,
I want karpenter to keep only one long-lived instance and not be recycled. How to make it?

**Comment by FernandoMiguel** [comment]
@hantmac see if this helps https://karpenter.sh/preview/tasks/deprovisioning/#pod-set-to-do-not-evict

**Comment by ellistarn** [comment]
Related: https://github.com/aws/karpenter/issues/2050

**Comment by bwagner5** [comment]
Feel free to reopen if #2050 or https://karpenter.sh/preview/tasks/deprovisioning/#pod-set-to-do-not-evict  do not cover your use-case!
