### ISSUE TITLE
Support Gt and Lt operators in provisioner requirements

### ISSUE THREAD

**Issue by mKeRix** [aws/karpenter#2046]
**Tell us about your request**
I would like to be able to specify min and max amounts for both CPU and memory using your new labels. For that, I would like to use the `Gt` and `Lt` operators as available in Kubernetes [nodeAffinity expressions](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity).

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We want to fine-tune the kinds of instances that Karpenter spins up natively, without calculating the list of instance types ourselves. For us, we know that usually an instance should have at least 4 vCPUs to join the cluster, as on smaller ones the ratio between system services and actual applications isn't what we'd like to have. Having this natively in Karpenter would make our provisioner configurations much easier to read.

**Are you currently working around this issue?**
Looking up a list of instance types fulfilling our use case with the [aws_ec2_instance_types](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ec2_instance_types) data source in Terraform and then restricting them in the provisioner using `node.kubernetes.io/instance-type`.

**Additional context**
The logs in Karpenter explicitly say that these operators are not supported currently, see for example here:

```
2022-07-05T11:21:45.793Z	INFO	webhook	remote admission controller audit annotations=map[string]string(nil)	{"commit": "1f7a67b", "knative.dev/kind": "karpenter.sh/v1alpha5, Kind=Provisioner", "knative.dev/namespace": "", "knative.dev/name": "default", "knative.dev/operation": "CREATE", "knative.dev/resource": "karpenter.sh/v1alpha5, Resource=provisioners", "knative.dev/subresource": "", "admissionreview/allowed": false, "admissionreview/result": "&Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:validation failed: invalid value: key karpenter.k8s.aws/instance-cpu has an unsupported operator Gt, provisioner only supports [In NotIn Exists]; key karpenter.k8s.aws/instance-cpu has an unsupported operator Lt, provisioner only supports [In NotIn Exists]: spec.requirements,Reason:BadRequest,Details:nil,Code:400,}"}

```

Note that I removed some information from the log above for brevity & to remove internal resource ids.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Thanks for the issue! @ellistarn looked into adding support for this very recently. Can you provide some info on the issues you ran into Ellis?

**Comment by ellistarn** [comment]
I have a work in progress on this!

**Comment by ellistarn** [comment]
I threw up the PR. It needs some big changes and my priorities are elsewhere at the moment.
