### ISSUE TITLE
split webhoook default/validation methods out from cloudprovider

### ISSUE THREAD

**Issue by tzneal** [aws/karpenter#2052]
**Tell us about your request**
Split the webhoook default/validation methods out from cloudprovider

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

The webhook shouldn't make any AWS API calls. Since the default/validate methods are on the cloud provider there is a bit of trickiness to enable this that it would be nice to eliminate.

**Are you currently working around this issue?**

The cloud provider knows when it's being instantiated solely for use by the webhook.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
This will enable us to lower the liveness probe startup period, as well.
