### ISSUE TITLE
Align node finalizer behavior to `kubectl drain`

### ISSUE THREAD

**Issue by vadimgusev-codefresh** [aws/karpenter#2088]
**Tell us about your request**
Make it safe to delete nodes hosting naked pods (like Jobs or CI pipelines) by aligning finalizer's behavoir to `kubectl drain`.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I've noticed that Karpernter's behavior differs from `kubectl drain --ignore-daemonsets --delete-emptydir-data`.
When I issue the command above against the node, containing naked pods, I get this result:
```
node/<NODE> cordoned
error: unable to drain node "<NODE>" due to error:cannot delete Pods declare no controller (use --force to override): <LIST OF PODS>, continuing command...
There are pending nodes to be drained:
 <NODE>
cannot delete Pods declare no controller (use --force to override): <LIST OF PODS>
```
So I cannot accidentally nuke naked pods, unless I issue `--force`.
In contrast, Karpenter's finalizer will happily remove naked pods from node, introducing disruption.

In theory problem can be solved by adding various annotations to pods, but IMO what works fine with `kubectl drain` should keep working with Karpenter.

**Are you currently working around this issue?**
Disable `ttlSecondsUntilExpired` on provisioners designated for disruption-sensitive naked pods and cordon nodes manually when I want to perform a rotation.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
You may want to annotate the pods without controller owners w/ `karpenter.sh/do-not-evict: true`

**Comment by bwagner5** [comment]
I would agree that Karpenter shouldn't delete naked pods though like we are today. I'll submit a PR to fix this.
