### ISSUE TITLE
karpenter.k8s.aws/instance-family not working?

### ISSUE THREAD

**Issue by jinghea** [aws/karpenter#2116]
**Is an existing page relevant?**
[](https://karpenter.sh/v0.13.2/tasks/provisioning/)

**What karpenter features are relevant?**
So in this document https://karpenter.sh/v0.13.2/tasks/provisioning/ it indicate 
```
   - key: karpenter.k8s.aws/instance-family
        operator: In
        values: [c5, m5, r5]
```
could limit the instance family. But after trying to add both in Provisioner or AWSNodeTemplate under spec -> requirements, both are not working. Checked the Customresourcedefinitions they are not defined as well. 
How to make this working?
Same issue also happen to karpenter.k8s.aws/instance-size

**How should the docs be improved?**
Please indicate how to make it work

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Can you provide your complete provisioner spec?

`kubectl get provisioners -oyaml`

**Comment by jinghea** [comment]
So when I try to applied this on 0.13.2

`apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
  limits:
    resources:
      cpu: 100
  provider:
    requirements:
      - key: karpenter.k8s.aws/instance-size
        operator: NotIn
        values: [nano, micro, small, large]
    launchTemplate: xxxxxxxx
    subnetSelector:
      karpenter.sh/discovery: eks-shared
  ttlSecondsAfterEmpty: 60`
  
  I got 
  
  `Error from server (BadRequest): error when creating "provisioner_instance_size_not_working.yaml": admission webhook "validation.webhook.provisioners.karpenter.sh" denied the request: validation failed: strict decoder error for {"launchTemplate":"xxxxxxxxx","requirements":[{"key":"karpenter.k8s.aws/instance-size","operator":"NotIn","values":["nano","micro","small","large"]}],"subnetSelector":{"karpenter.sh/discovery":"eks-shared"}}: v1alpha1.AWS.ReadObject: found unknown field: requirements, error found in #10 byte of ...|uirements":[{"key":"|..., bigger context ...|xxxxxxxx","requirements":[{"key":"karpenter.k8s.aws/instance-size","operat|...:`

**Comment by jinghea** [comment]
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
  limits:
    resources:
      cpu: 100
  provider:
    requirements:
      - key: karpenter.k8s.aws/instance-size
        operator: NotIn
        values: [nano, micro, small, large]
    launchTemplate: xxxxxxxxxxxx
    subnetSelector:
      karpenter.sh/discovery: eks-shared
  ttlSecondsAfterEmpty: 60

**Comment by jinghea** [comment]
Since the document says the provider will be replaced soon, I tried

apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  launchTemplate: xxxxxx
  requirements:
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values: [ nano, micro, small, large ]
  subnetSelector:
    karpenter.sh/discovery: eks-shared

also no luck

**Comment by jinghea** [comment]
Those were applied

`kubectl replace -f https://raw.githubusercontent.com/aws/karpenter/v0.13.2/charts/karpenter/crds/karpenter.sh_provisioners.yaml
kubectl apply -f https://raw.githubusercontent.com/aws/karpenter/main/charts/karpenter/crds/karpenter.k8s.aws_awsnodetemplates.yaml`

**Comment by bwagner5** [comment]
The requirements block is a list of requirements and is not duplicated in the Provider spec. You can include cloud-provider specific label requirements outside of the provider block like this:

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values: ["spot", "on-demand"]
  - key: karpenter.k8s.aws/instance-size
    operator: NotIn
    values: [nano, micro, small, large]
limits:
  resources:
    cpu: 100
provider:
  launchTemplate: xxxxxxxxxxxx
  subnetSelector:
    karpenter.sh/discovery: eks-shared
ttlSecondsAfterEmpty: 60
```

**Comment by bwagner5** [comment]
Feel free to reopen if the above is still not working for you! :)

**Comment by jinghea** [comment]
It works! Thank you very much Brandon.
But does it means document under https://karpenter.sh/v0.13.2/tasks/provisioning/ is wrong?
