### ISSUE TITLE
controller container not starting but doesn't say why

### ISSUE THREAD

**Issue by welljonathan** [aws/karpenter#2133]
## Version

**Karpenter**: v0.13.2

**Kubernetes**: v1.22  (EKS)

## Expected Behavior

Include enough logging to determine why the container doesn't get to a point where it can respond to health checks successfully. 

I am attempting to bring up Karpenter in an EKS cluster generated by a `pulumi` stack.  This stack creates all of the AWS Roles and related pieces as described in a combination of all the [Getting Started](https://karpenter.sh/v0.13.2/getting-started/) pages.   This stack worked in a different AWS account, but attempting to switch accounts, it mostly comes up but Karpenter never actually successfully brings up its own pods.  

Below is the entire log that the `controller` container gives. I would like to have enough logs that I can determine what's missing in the IAM roles, or why otherwise the container start is failing. 

## Actual Behavior

The logs below are the entirety of an attempt to start the container.  The pod never gets healthy because the controller container never starts fully. I can't figure out why without more information. 

## Steps to Reproduce the Problem

Reproducing would be including code for a pulumi stack that works in one account/vpc, but not another. I don't think that sharing this code would be helpful.  The logging can be added in a vacuum. I just would like additional logging that helps determine exactly what part of the setup is silently failing. Ideally, there would be a log before/after every call that does something important. 

## Resource Specs and Logs

```
2022-07-14T13:47:29.514Z    INFO    Successfully created the logger.                                                                                                                        
2022-07-14T13:47:29.514Z    INFO    Logging level set to: debug                                                                                                                             
2022-07-14T13:47:29.519Z    INFO    controller    Initializing with version v0.13.2    {"commit": "062a029"}                                                                                
{"level":"info","ts":1657806449.519197,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}                                                              
2022-07-14T13:47:29.536Z    DEBUG    controller.aws    Using AWS region us-east-1    {"commit": "062a029"}    
```

**Comment by welljonathan** [comment]
I was able to resolve my issue with trial and error, so this isn't critical for me any more. However, I do think it would be valuable for other people with similar issues in the future.

**Comment by ellistarn** [comment]
Closing, as issue was resolved. Would love to hear how you solved this.

**Comment by ellistarn** [comment]
Will need to think on what specifically we can log in this case.
