### ISSUE TITLE
Security groups

### ISSUE THREAD

**Issue by funes79** [aws/karpenter#2140]
I do have a question about security group creation via Terraform EKS module. The cluster created according to the [docs](https://karpenter.sh/v0.13.2/getting-started/getting-started-with-terraform/#create-a-cluster) with
```
  create_cluster_security_group = false
  create_node_security_group    = false
  tags = {
    # Tag node group resources for Karpenter auto-discovery
    # NOTE - if creating multiple security groups with this module, only tag the
    # security group that Karpenter should utilize with the following tag
    "karpenter.sh/discovery" = var.cluster_name
  }
```
works fine with Karpenter and auto scaling. But when we try to add more SG rules and let the module create sg:
```
  create_cluster_security_group = true
  create_node_security_group    = true
  node_security_group_additional_rules = {
    ingress_rule_abc = {
     ....
    } 
  }
  tags = {
    # Tag node group resources for Karpenter auto-discovery
    # NOTE - if creating multiple security groups with this module, only tag the
    # security group that Karpenter should utilize with the following tag
    "karpenter.sh/discovery" = var.cluster_name
  }
```

**the cluster nodes are started but the nodes do not join the cluster.**
It is not clear how we should tag only one specific SG in the case when we need to create and modify node SG. 
Can somebody update the docs or explain how it should be configured?

Thanks!

**Is an existing page relevant?**

**What karpenter features are relevant?**
security groups

**How should the docs be improved?**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
>It is not clear how we should tag only one specific SG in the case when we need to create and modify node SG.

Is it not simply adding the tag `karpenter.sh/discovery/var.cluster_name` to the SG?

>Can somebody update the docs or explain how it should be configured?

To further clarify, how is this single SG created, what do we know about it? Do we know its ARN or name?
What sort of access do we have to this SG? Can we tag it?
