### ISSUE TITLE
Specify Image Registry

### ISSUE THREAD

**Issue by jordanfelle** [aws/karpenter#2151]
Right now there is just an image value for the image to pull:

https://github.com/aws/karpenter/blob/main/charts/karpenter/values.yaml#L91

Ideally it should get broken up into registry, image, and then tag like most other helm charts. Our use case it to utilize ECR pullthrough cache and only need to specify a registry for that to work.

**Comment by ellistarn** [comment]
See: https://github.com/aws/karpenter/pull/1737
