### ISSUE TITLE
controller.aws.pricing  updating on-demand pricing, AccessDeniedException 

### ISSUE THREAD

**Issue by satya67** [aws/karpenter#2172]
Hi 

I have deployed the karpenter on the eks cluster and see the below error in the pod logs ,I have given karpenter controller role all the acceess mentined in documentation still I see below error,
\
![image](https://user-images.githubusercontent.com/17108400/180432132-9c123775-e16d-4ec2-87cd-4ffd8adfec2f.png)

**Comment by bwagner5** [comment]
Can you verify the Karpenter controller policy has the `pricing:GetProducts` permission?  

The policy should look something like this:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ec2:CreateLaunchTemplate",
                "ec2:CreateFleet",
                "ec2:RunInstances",
                "ec2:CreateTags",
                "ec2:TerminateInstances",
                "ec2:DeleteLaunchTemplate",
                "ec2:DescribeLaunchTemplates",
                "ec2:DescribeInstances",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeSubnets",
                "ec2:DescribeImages",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeInstanceTypeOfferings",
                "ec2:DescribeAvailabilityZones",
                "ec2:DescribeSpotPriceHistory",
                "ssm:GetParameter",
                "pricing:GetProducts"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "iam:PassRole"
            ],
            "Resource": "arn:aws:iam::xxxxxxxxxxx:role/KarpenterNodeRole-kdemo-us-east-2",
            "Effect": "Allow"
        }
    ]
}
```

**Comment by satya67** [comment]
Well this is working with out "pricing:GetProducts" in another environment.

**Comment by bwagner5** [comment]
If Karpenter is unable to access the pricing api, it will continue with static pricing data in the binary. So should still work fine, but if it's possible to allow it to query the pricing api, that would be best so it can have the most up-to-date information on new instance types launches.

**Comment by satya67** [comment]
Thanks for the detailed explanation , will try it .

**Comment by satya67** [comment]
Closed
