### ISSUE TITLE
How to set node scaling policy

### ISSUE THREAD

**Issue by cjub-oh** [aws/karpenter#2178]
**Is an existing page relevant?**

**What karpenter features are relevant?**

**How should the docs be improved?**
Hello 
I want to scale out node instance according to scaling policy such as traget tracking policy of AWS. 
That is, If I set the CPU target value as 50% then karpenter node should be increased  even its CPU is enough. 
For example, a pod CPU 1G, its instance CPU 4G, If I scale replicas as 2 then its sum would be reached up to 2G and it can be over 50% of node limit, then new node should be created. 
Could I set CPU target value of node using provisioner ?
And what is default CPU limit of Karpenter node scaling?

ex. AWS target tracking policy)
AWS autoscaling group > Scaling policies > Traget Tracking Scaling policy
Metric Type > Average  CPU Utilization
Set target value percentage

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
If I understand correctly you are asking about ability to set a maximum CPU usage. 

>Could I set CPU target value of node using provisioner ?
Assuming you mean CPU usage target value then no. Karpenter 

>And what is default CPU limit of Karpenter node scaling?
Karpenter doesn't monitor or react to CPU usage as such, Karpenter rather scales up when there are pending pods because it's indicative of a need to scale up.

**Comment by topikachu** [comment]
> If I understand correctly you are asking about ability to set a maximum CPU usage.
> 
> > Could I set CPU target value of node using provisioner ?
> 
> Assuming you mean CPU usage target value then no [the provisioner API](https://karpenter.sh/v0.13.2/provisioner/) doesn't include that.
> 
> > And what is default CPU limit of Karpenter node scaling?
> 
> Karpenter doesn't monitor or react to CPU usage as such, Karpenter rather scales up when there are pending pods because it's indicative of a need to scale up.

I think @cjub-oh requires a ratio between the required capacity and provisioned.
Suppose the CPU ratio is 50%, if all pending pods require 10 CPU, he wants karpenter to provision new nodes at least in a total of 20 CPU.

Correct me if I'm wrong.

**Comment by cjub-oh** [comment]
@topikachu topikachu
Hello yes that's right

1. I wonder what criteria the karpenter scales out the node. CPU target value, or memory value, network throughput, or any other threshold default?
That is, is it launching a new node when the CPU average of the pods in the current node exceeds 50%, or is there a standard other than CPU?

2. Is the standard of scale out and scale up the same?

3. I wonder if I can set the value arbitrarily.

4. And I wonder if the scale out of the pod can be set in the horizontal pod autoscaler of Kubernetes.

**Comment by vi-credo** [comment]
If I understand Karpenter correctly, scaling decisions are not based directly on some target values, such as CPU or memory, but just "replicates" decisions made by `kube-scheduler`. That is, if Pod is in pending state and there is no hardware available for it, Karpenter spins up a node for it (if it matches various provisioner settings as well).

That being said you control your CPU consumption on particular deployment (or other Kubernetes) object level, not nodes directly. And yes, you can (and should) use HorizontalPodAutoscalar object to further modify behavior to what you need.

Scaling down a node is based on just two setting in the provisioner, both are based on TTL: time a node is allowed to be empty and overall expiration time for a node, after which it will be removed. This should make you think about adding a PodDisruptionBudget as well to avoid potentially removing multiple nodes at the same time.
