### ISSUE TITLE
Limit nodes by amount of pods

### ISSUE THREAD

**Issue by devopsjnr** [aws/karpenter#2180]
Not too long ago I asked to add an option to limit nodes by pods limitation. 
I would like to know from which version this feature should be available. Thanks!

**Comment by spring1843** [comment]
Is this about having a maximum number of pods scheduled on a node?

There are some ways to [control pod density](https://karpenter.sh/v0.13.2/tasks/pod-density/) in Karpenter, do any of those help?

**Comment by spring1843** [comment]
Additionally Karpenter doesn't really schedule pods as mentioned in https://github.com/aws/karpenter/issues/1759 . It's kube-scheduler as mentioned [in the other issue](https://github.com/aws/karpenter/issues/1759) that does that job.

**Comment by devopsjnr** [comment]
@spring1843 I think I saw somewhere in the Karpenter documentation that limiting by amount of pods is yet to be supported but will be in future versions. I'll try to look for it again

**Comment by ellistarn** [comment]
We could consider exposing a MaxPods override (https://github.com/kubernetes/kubelet/blob/v0.24.3/config/v1beta1/types.go#L415) in Karpenter's KubeletConfiguration to help control this.

**Comment by devopsjnr** [comment]
@ellistarn Though this was already in process. Anyway, it would be great exposing it. Could you think of overriding MaxPods from the provisioner?

**Comment by bwagner5** [comment]
@devopsjnr we've talked about this a lot before and I'm very supportive of it. The KubeletConfiguration that @ellistarn is referring to is apart of the provisioner spec: https://karpenter.sh/v0.13.2/provisioner/#:~:text=and%20use%20cases.-,kubeletConfiguration,-%3A%0A%20%20%20%20clusterDNS%3A
