### ISSUE TITLE
Use dnsPolicy=Default by default in helm chart

### ISSUE THREAD

**Issue by anguslees** [aws/karpenter#2186]
**Tell us about your request**

I think the karpenter helm chart should use `dnsPolicy=Default` (not `ClusterFirst`) by default.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Karpenter has a boostrapping challenge.  You need to run karpenter somewhere in order to have karpenter manage all the rest of your capacity.  One solution is to run karpenter on fargate, as a special case.

If you _only_ run karpenter on fargate, then at initial cluster bootstrap, karpenter is _the only pod running_.  In particular, coreDNS is still Pending.  At this moment, karpenter fails because it tries to do simple DNS lookups to find the AWS and k8s API endpoints - which go to the _cluster_ DNS clusterIP, which fails (times out with no response) because coreDNS is not yet functional.

However! Karpenter doesn't actually need to talk to other pods or internal ClusterIPs, so doesn't actually need to use the cluster-internal DNS resolver.  Setting `pod.spec.dnsPolicy=Default` (note this is not the k8s default, despite the name) on karpenter pods tells kubelet to configure the karpenter pod with the _host's_ (route53/droplet) resolver, and allows karpenter to lookup these non-cluster hostnames even before coreDNS is functional.  Karpenter is then able to create nodes for coreDNS as usual and everyone is happy.

**Are you currently working around this issue?**

Manually set `dnsPolicy=Default` on every karpenter helm chart install.   I think we can help others get past this hurdle by making this the default, even for non-fargate.

**Additional context**

Note https://karpenter.sh/v0.13.2/getting-started/getting-started-with-eksctl/#create-a-cluster "Example 2" gives an example of running karpenter on fargate.  This example adds `kube-system` to the fargate profile, presumably so coreDNS (and everything else in kube-system!) runs on fargate.  This is unnecessary with the above `dnsPolicy` change, and this documentation should be updated.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Very cool suggestion!

**Comment by snorlaX-sleeps** [comment]
Just a note incase this causes an issue for other users: 
When using a network stack in Kubernetes e.g Istio, Karpenter will fail to start as `dnsPolicy: default` is connecting to the VPC based DNS servers which don't have any kubernetes services listed.
The istio-proxy needs to connect to the `istiod.istio-system.svc` which is a kubernetes service and unavailable with the current setting.
The fix is to revert to `dnsPolicy: ClusterFirst` in the Helm values file

**Comment by johngmyers** [comment]
Another situation this breaks: running Karpenter on an ipv6-only cluster on a dual-stack node. Using the node's DNS servers, without DNS64, causes Karpenter to attempt connecting to STS using IPv4. Reverting to `ClusterFirst` causes it to use coredns, with DNS64, so the connections to STS go through NAT64.
