### ISSUE TITLE
Add toleration to helm chart with terraform

### ISSUE THREAD

**Issue by Izvi-digibank** [aws/karpenter#2193]
v10.0.1

Using terraform and following the docs I have been trying to add tolerations to Karpenter's helm chart. 
This case isn't covered in the docs and I'm getting hard time implementing it. 

From main.tf I am using `set` to inject vars to the chart values:

```
resource "helm_release" "karpenter" {
  name       = var.name
  repository = var.helm_repo
  chart      = var.helm_chart
  version    = var.helm_chart_version

  namespace        = var.name
  create_namespace = true
  timeout          = 300

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = aws_iam_role.main.arn
  }
  set {
    name  = "clusterName"
    value = var.cluster_id
  }
  set {
    name  = "clusterEndpoint"
    value = data.aws_eks_cluster.cluster.endpoint
  }
  set {
    name  = "aws.defaultInstanceProfile"
    value = "${var.default_instance_profile}"
  }
  set {
    name  = "webhook.hostNetwork"
    value = var.host_network
  .
  .
  .
  .
  .
  set {
    name  = "tolerations"
    value = var.tolerations
}
``` 

From file `variables.tf` I call `tolerations` var:

```
variable "tolerations" {
  type        = any
  description = "tolerations for karpenter"
  default = <???>
}
```

The `default` value should be the value of tolerations. 
I tried many ways none of them worked.
My goal is that eventually the Helm chart's values file will look something like:

```
.
.
.
tolerations: 
  - key: "tool"
    value: "karpenter"
.
.
.

```

Thanks!

**Comment by Izvi-digibank** [comment]
Hi guys please advise I am pretty stuck right now. Thanks!

**Comment by anguslees** [comment]
> I tried many ways none of them worked.

In what way didn't it work?

**Comment by muram** [comment]
@Izvi-digibank another simpler option is to use `values` and provide the `tolerations` key directly inside of a `values.yaml` file like:

```hcl
values           = [templatefile("${path.module}/values.yaml", {})]
```

values.yaml:

```yml
tolerations:
  - key: tool
    operator: Exists
```

This will be merged with all the other `set` values by helm.

**Comment by hnp2** [comment]
@Izvi-digibank you can try to wrap terraform with yaml

```
values = [yamlencode({
    clusterName      = module.eks.cluster_id
    clusterEndpoint = module.eks.cluster_endpoint
    serviceAccount = {
      annotations     = {
        "eks.amazonaws.com/role-arn" = module.iam_assumable_role_karpenter.iam_role_arn
      }
    }
    aws = {
      defaultInstanceProfile = aws_iam_instance_profile.karpenter.name
    }
    tolerations = [
      {
              key          = "tool"
              operator = "Exists"
              effect      = "NoExecute"
        },
        {
              key          = "tool"
              operator = "Equal"
              value       = "karpenter"
              effect      = "NoExecute"
        },
    ]
  })]
```

**Comment by MaciejKucia** [comment]
```
  set {
    name  = "tolerations[0].key"
    value = "dedicated"
  }

  set {
    name  = "tolerations[0].value"
    value = "karpenter"
  }

  set {
    name  = "tolerations[0].operator"
    value = "Equal"
  }

  set {
    name  = "tolerations[0].effect"
    value = "NoSchedule"
  }
```

**Comment by billrayburn** [comment]
No longer maintainer getting started for Terraform, please refer to https://github.com/terraform-aws-modules/terraform-aws-eks

**Comment by billnbell3** [comment]
> @Izvi-digibank you can try to wrap terraform with yaml
> 
> ```
> values = [yamlencode({
>     clusterName      = module.eks.cluster_id
>     clusterEndpoint = module.eks.cluster_endpoint
>     serviceAccount = {
>       annotations     = {
>         "eks.amazonaws.com/role-arn" = module.iam_assumable_role_karpenter.iam_role_arn
>       }
>     }
>     aws = {
>       defaultInstanceProfile = aws_iam_instance_profile.karpenter.name
>     }
>     tolerations = [
>       {
>               key          = "tool"
>               operator = "Exists"
>               effect      = "NoExecute"
>         },
>         {
>               key          = "tool"
>               operator = "Equal"
>               value       = "karpenter"
>               effect      = "NoExecute"
>         },
>     ]
>   })]
> ```

Switch module.eks.cluster_id to module.eks.cluster_name
