### ISSUE TITLE
Karpenter metrics attribute pods to a node even after the pod completes

### ISSUE THREAD

**Issue by jbouricius** [aws/karpenter#2197]
## Version
**Karpenter**: v0.13.1

## Expected Behavior

I want to chart overall efficiency of jobs running in my cluster. I'm looking at the Prometheus metrics `karpenter_nodes_total_pod_requests`, `karpenter_nodes_total_daemon_requests`, and `karpenter_nodes_allocatable` . I would expect (pod requests + daemon requests) / (node allocatable) to be a reasonable measure of efficiency. That is, at any given moment, the total pod requests metric reflects what is currently running on the node.

## Actual Behavior
However, it looks as though Karpenter is continuing to attribute a pod's requests to its node even after that pod has completed.

## Steps to Reproduce the Problem
Run multiple pods on the same node, in parallel and series. Observe that the `karpenter_nodes_total_pod_requests` metric for a given node doesn't decrease.

## Resource Specs and Logs

Here is a subset of the metrics for a single node in my cluster:
```
karpenter_nodes_allocatable{arch="amd64",capacity_type="on-demand",instance_type="m5n.xlarge",node_name="ip-10-191-218-99.ec2.internal",phase="",provisioner="karpenter-default-provisioner",resource_type="cpu",zone="us-east-1d"} 3.92
karpenter_nodes_total_daemon_requests{arch="amd64",capacity_type="on-demand",instance_type="m5n.xlarge",node_name="ip-10-191-218-99.ec2.internal",phase="",provisioner="karpenter-default-provisioner",resource_type="cpu",zone="us-east-1d"} 0.375
karpenter_nodes_total_pod_requests{arch="amd64",capacity_type="on-demand",instance_type="m5n.xlarge",node_name="ip-10-191-218-99.ec2.internal",phase="",provisioner="karpenter-default-provisioner",resource_type="cpu",zone="us-east-1d"} 6.02
karpenter_nodes_total_pod_requests{arch="amd64",capacity_type="on-demand",instance_type="m5n.xlarge",node_name="ip-10-191-218-99.ec2.internal",phase="",provisioner="karpenter-default-provisioner",resource_type="pods",zone="us-east-1d"} 6
karpenter_pods_state{arch="amd64",capacity_type="on-demand",instance_type="m5n.xlarge",name="gr-main",namespace="<redacted>",node="ip-10-191-218-99.ec2.internal",owner="",phase="Running",provisioner="karpenter-default-provisioner",zone="us-east-1d"} 1
karpenter_pods_state{arch="amd64",capacity_type="on-demand",instance_type="m5n.xlarge",name="gr-main",namespace="<redacted>",node="ip-10-191-218-99.ec2.internal",owner="",phase="Succeeded",provisioner="karpenter-default-provisioner",zone="us-east-1d"} 1
karpenter_pods_state{arch="amd64",capacity_type="on-demand",instance_type="m5n.xlarge",name="gr-main",namespace="<redacted>",node="ip-10-191-218-99.ec2.internal",owner="",phase="Succeeded",provisioner="karpenter-default-provisioner",zone="us-east-1d"} 1
karpenter_pods_state{arch="amd64",capacity_type="on-demand",instance_type="m5n.xlarge",name="gr-main",namespace="<redacted>",node="ip-10-191-218-99.ec2.internal",owner="",phase="Running",provisioner="karpenter-default-provisioner",zone="us-east-1d"} 1
karpenter_pods_state{arch="amd64",capacity_type="on-demand",instance_type="m5n.xlarge",name="gr-main",namespace="<redacted>",node="ip-10-191-218-99.ec2.internal",owner="",phase="Succeeded",provisioner="karpenter-default-provisioner",zone="us-east-1d"} 1
karpenter_pods_state{arch="amd64",capacity_type="on-demand",instance_type="m5n.xlarge",name="gr-main",namespace="<redacted>",node="ip-10-191-218-99.ec2.internal",owner="",phase="Running",provisioner="karpenter-default-provisioner",zone="us-east-1d"} 1
```

The `karpenter_nodes_total_pod_requests{resource_type="pods"}` value is 6, for the 3 "Running" and 3 "Succeeded" pods. Similarly, `karpenter_nodes_total_pod_requests{resource_type="cpu"}` is 6.02, larger than the node's allocation of 3.92 . Of course from k8s' perspective, the node is not over-allocated, because the Succeeded pods are no longer running. The efficiency score I would like to track for this node is not possible to know.

Would it be possible to either filter to "Running" pods when reporting the total_[pod|daemon]_[request|limits] metrics? Or populate the "phase" attribute so the user can filter them?

**Comment by suket22** [comment]
Each time a pod is updated, our metrics controller verifies if the pod is still bound to the node it originally thought it was. If so, it returns early. [This is the bit of code we need to change](https://github.com/aws/karpenter/blob/main/pkg/controllers/state/cluster.go#L378-L382) we need to fix.

**Comment by njtran** [comment]
https://github.com/aws/karpenter/pull/2265
