### ISSUE TITLE
Controller doesn't start up and there is no error logs

### ISSUE THREAD

**Issue by eduanb** [aws/karpenter#2216]
## Version
**Karpenter**: v0.13.2
**Kubernetes**: v1.22.10-eks

## Expected Behavior
The controller container should start up or log an error.

## Actual Behavior
This is all the logs:
```
2022-07-29T10:46:28.676Z	INFO	Successfully created the logger.
2022-07-29T10:46:28.676Z	INFO	Logging level set to: debug
{"level":"info","ts":1659091588.6812754,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
2022-07-29T10:46:28.681Z	INFO	controller	Initializing with version v0.13.2	{"commit": "062a029"}
2022-07-29T10:46:28.764Z	DEBUG	controller.aws	Using AWS region us-east-2	{"commit": "062a029"}
```

## Steps to Reproduce the Problem
Install helm and create provisioner. Karpenter was working fine until a cluster upgrade from 1.21 to 1.22. After draining the node group it did not start up again. I tried to completely uninstall the chart and install it again with the same issue. I also tried v0.12 of Karpenter but the same issue.

## Resource Specs and Logs
Provisoiner
```apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ttlSecondsUntilExpired: 2592000
  ttlSecondsAfterEmpty: 30
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: [ "t3.medium" ]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [ "us-east-2a", "us-east-2b" ]
  limits:
    resources:
      memory: 100Gi
  provider:
    subnetSelector:
      karpenter.sh/discovery: my-cluster
    securityGroupSelector:
      karpenter.sh/discovery: my-cluster
```
![image](https://user-images.githubusercontent.com/6643196/181744219-2ad68ef1-91a6-4714-95c1-112bec8fedff.png)

**Comment by ellistarn** [comment]
Interesting. Not obvious what this is, though my guess is that it has something to do with the container runtime environment. We can try to reproduce this, but I've definitely run Karpenter-0.13.2 on EKS-1.22 before. 

- What's your CNI / CRI settings?
- Have you made any tweaks to the Karpenter install?
- Are there any other special details in your environment (security groups) that could be blocking network connectivity?

**Comment by dewjam** [comment]
Hey @eduanb
Any updates on this issue?  We will need some additional details in order to help debug.

**Comment by SilentEntity** [comment]
Karpenter version : v0.13.2, 
EKS version : v1.22.11-eks-18ef993 ,
Karpenter Nodes are not becoming ready even after 20m.
CRI: containerd.

**Comment by eduanb** [comment]
I think I found the issue. I think the security groups on node were blocking Karpenter from connecting to the AWS API. Destroying the node and creating it again solved the problem. So I guess liveness/startup probes are failing faster than the connection refused timeout and thus the pod is restarted before it could print the error.
