### ISSUE TITLE
Karpenter provisioned nodes do not always terminate

### ISSUE THREAD

**Issue by toddatapiture** [aws/karpenter#2252]
**Is an existing page relevant?**
https://karpenter.sh/v0.13.2/tasks/deprovisioning/

**What karpenter features are relevant?**
Deprovisioning nodes.

We are currently using Kubernetes version `1.22` and the latest version of Karpenter which is `0.13.2`. Our use case is that we use Kubernetes and Karpenter for our Jenkins agents. This allows us to scale out when Jenkins is under load but scale in as the demand falls off. For the most part, it's scaling fine but sometimes as the Jenkins job completes and the pod is removed from the node might not terminate. We have caught instances where the node is hung and is running for months.

We install some additional helm charts on our cluster such as `fluent-bit`, `aws-efs-csi-driver`, `aws-load-balancer-controller`, etc.. These will create pods and schedule them onto the node provisioned for the Jenkins job. For various reasons: storage, networking, logs/metrics, etc... After the Jenkins job pods are done, the supporting pods mentioned earlier are still running on the node. So, I thought that was the case since the node wasn't empty Karpenter didn't expire it. Although I see Karpenter provisioned nodes working correctly probably 80-90% of the time, they have the same pods getting scheduled. This killed my theory of additional running pods on the node and not allowing it to expire. Here is an example of the additional supporting pods that get scheduled onto the node:
![image](https://user-images.githubusercontent.com/63865255/182889464-dcee51bb-a3e3-4e5d-a63b-d1870f397bb6.png)

Here is another example that is a real example of this. This node was created nearly 1 day ago. There are no Jenkins jobs running on it so all jobs are completed. It only has supporting Pods that are running for logs/metrics, storage, etc... But, the node never terminated after the jobs are completed. As mentioned above I have seen nodes like this will all the support pods scheduled to it terminate just fine after the Jenkins job has been completed.
![image](https://user-images.githubusercontent.com/63865255/182891292-2b73c15d-6461-44b7-a504-c4d6faa9c63c.png)
 

**How should the docs be improved?**
N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dewjam** [comment]
@toddatapiture are there any relevant Karpenter logs being emitted?  If so, can you share them?

**Comment by dewjam** [comment]
Also, I'm assuming Jenkins is launching Kubernetes Batch Jobs, is that correct?

**Comment by dewjam** [comment]
Hey @toddatapiture ,
Checking in here.  Any additional info you can share about this issue?

**Comment by toddatapiture** [comment]
Hi @dewjam! Thanks for the response and my apologies I missed your questions. I am not seeing anything in the Karpenter logs. Probably due to these being older nodes and not recent. I've used both commands to try to scan the logs

```
stern -n karpenter -l [app.kubernetes.io/name=karpenter](http://app.kubernetes.io/name=karpenter)
kubectl logs -f -n karpenter -l app.kubernetes.io/name=karpenter -c controller
```

**Comment by toddatapiture** [comment]
We aren't using Kubernetes Batch jobs. Jenkins is using the Kubernetes plugin which allows us to use Kubernetes for our agents. It requires Kubernetes Pod templates (https://plugins.jenkins.io/kubernetes/). This means every time a job is executed a Pod is created and scheduled onto a node. After job execution, the Pod is then terminated.

**Comment by pa5hgan** [comment]
Hello, I use same versions (K8s 1.22 on top of EKS and Karpenter 0.13.2) and see same behavior, Karpenter:
* successfully launches new nodes (lifecycle=spot) for newly appeared pods
* marks empty nodes by TTL label, when pods terminated
* no errors reported
* no attempts to terminate marked nodes after TTL (30s) expiration, logs are pretty clean after message about labeling a node, just messages from controller.node-state like:
`2022-08-09T15:58:31.591Z	DEBUG	controller.node-state	Discovered EC2 instance types zonal offerings	{"commit": "062a029", "node": "ip-10-0-161-201.us-east-2.compute.internal"}
2022-08-09T16:03:32.563Z	DEBUG	controller.node-state	Discovered 497 EC2 instance types	{"commit": "062a029", "node": "ip-10-0-161-201.us-east-2.compute.internal"}
2022-08-09T16:03:32.642Z	DEBUG	controller.node-state	Discovered subnets: [subnet-xxx (us-east-2b) subnet-yyy(us-east-2c)]	{"commit": "062a029", "node": "ip-10-0-161-201.us-east-2.compute.internal"}
2022-08-09T16:03:32.796Z	DEBUG	controller.node-state	Discovered EC2 instance types zonal offerings	{"commit": "062a029", "node": "ip-10-0-161-201.us-east-2.compute.internal"}`

Checked versions 0.12, 0.10 of Karpenter, same behaviour -- instances are launched well but not auto-terminated.

**Comment by tzneal** [comment]
Do you have `AWS_ENABLE_POD_ENI` set on the Karpenter deployment?

**Comment by pa5hgan** [comment]
@tzneal nope, tried earlier to enable it in conjunction with ENABLE_POD_ENI for aws-node, hoping that it can clarify the issue, but it impacted nothing, so reverted back the settings, recreating nodes and redeploying Karpenter to initial state.

**Comment by toddatapiture** [comment]
@tzneal Same as @pa5hgan in regards to `AWS_ENABLE_POD_ENI`.

**Comment by tzneal** [comment]
If you run:

**Comment by pa5hgan** [comment]
@tzneal all Karpenter initialized nodes have "true" for that label, i.e. looks well. Going to build and deploy controller version with additional debug info for termination loop. Can you advice/point to place in code where it would better to do?

**Comment by tzneal** [comment]
I'd add a log in `func (r *Emptiness) Reconcile(ctx context.Context, provisioner *v1alpha5.Provisioner, n *v1.Node) (reconcile.Result, error) {`  everywhere it returns before adding the emptiness TTL.

**Comment by toddatapiture** [comment]
@tzneal For me, running the command you provided is showing the Karpenter provisioned node as initialized (`ready`). Although, this node should have been deleted. It has been up and running for 11 days.

![Screen Shot 2022-08-09 at 2 53 35 PM](https://user-images.githubusercontent.com/63865255/183740195-886cf18c-9b69-4b37-b87d-beaad51cafb9.png)
![Screen Shot 2022-08-09 at 2 56 06 PM](https://user-images.githubusercontent.com/63865255/183740197-20e59b27-a185-425e-9e76-57bd0550b3da.png)
![image](https://user-images.githubusercontent.com/63865255/183740218-b017c41a-d3e6-4a62-98f5-2c6ddc19fcdf.png)

**Comment by tzneal** [comment]
@toddatapiture  Try this to get all of the metadata for the pods bound to that node, it will show the owner references. If there's a custom controller that owns one of the pods, it can block emptiness:

```
kubectl get -A pod --field-selector spec.nodeName=ip-10-0-166-42.us-west-2.compute.internal |  grep Running | awk '{print "kubectl get pod -n " $1 " " $2 " -o json"}' | bash  | jq '.metadata'
```

**Comment by toddatapiture** [comment]
Here's the output:

```
➜  ~ kubectl get -A pod --field-selector spec.nodeName=ip-10-0-166-42.us-west-2.compute.internal |  grep Running | awk '{print "kubectl get pod -n " $1 " " $2 " -o json"}' | bash  | jq '.metadata'
{
  "annotations": {
    "kubernetes.io/psp": "eks.privileged"
  },
  "creationTimestamp": "2022-07-29T20:25:14Z",
  "generateName": "cloudwatch-agent-",
  "labels": {
    "controller-revision-hash": "595744dcd5",
    "name": "cloudwatch-agent",
    "pod-template-generation": "2"
  },
  "name": "cloudwatch-agent-kpljs",
  "namespace": "amazon-cloudwatch",
  "ownerReferences": [
    {
      "apiVersion": "apps/v1",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "DaemonSet",
      "name": "cloudwatch-agent",
      "uid": "56f7870a-124b-498c-8174-fd49fde01de6"
    }
  ],
  "resourceVersion": "174336278",
  "uid": "7c00be28-f3e1-4bb8-a539-090918f7692e"
}
{
  "annotations": {
    "kubernetes.io/psp": "eks.privileged"
  },
  "creationTimestamp": "2022-07-29T20:23:35Z",
  "generateName": "fluent-bit-",
  "labels": {
    "controller-revision-hash": "687ddcdbdc",
    "k8s-app": "fluent-bit",
    "kubernetes.io/cluster-service": "true",
    "pod-template-generation": "3",
    "version": "v1"
  },
  "name": "fluent-bit-zc6pl",
  "namespace": "amazon-cloudwatch",
  "ownerReferences": [
    {
      "apiVersion": "apps/v1",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "DaemonSet",
      "name": "fluent-bit",
      "uid": "f92d9bb4-32f1-4607-ba27-e19e1502cb47"
    }
  ],
  "resourceVersion": "174336275",
  "uid": "80e61165-f755-471c-8594-0e3c3f486299"
}
{
  "annotations": {
    "kubernetes.io/psp": "eks.privileged"
  },
  "creationTimestamp": "2022-07-29T20:24:33Z",
  "generateName": "aws-node-",
  "labels": {
    "app.kubernetes.io/instance": "aws-vpc-cni",
    "app.kubernetes.io/name": "aws-node",
    "controller-revision-hash": "5c7b458969",
    "k8s-app": "aws-node",
    "pod-template-generation": "3"
  },
  "name": "aws-node-7dnd8",
  "namespace": "kube-system",
  "ownerReferences": [
    {
      "apiVersion": "apps/v1",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "DaemonSet",
      "name": "aws-node",
      "uid": "1bb52c77-bc4c-40c2-9cfd-74b3e2613af7"
    }
  ],
  "resourceVersion": "174336068",
  "uid": "6a8991eb-1adb-452b-b746-53cfb0020c8c"
}
{
  "annotations": {
    "kubernetes.io/psp": "eks.privileged"
  },
  "creationTimestamp": "2022-07-29T20:24:34Z",
  "generateName": "efs-csi-node-",
  "labels": {
    "app": "efs-csi-node",
    "controller-revision-hash": "69589d46bf",
    "pod-template-generation": "1"
  },
  "name": "efs-csi-node-j7jx6",
  "namespace": "kube-system",
  "ownerReferences": [
    {
      "apiVersion": "apps/v1",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "DaemonSet",
      "name": "efs-csi-node",
      "uid": "e3c7bcf3-636b-4041-80af-1cc972669420"
    }
  ],
  "resourceVersion": "174336028",
  "uid": "39512118-bff9-4823-8969-6c9c945da12e"
}
{
  "annotations": {
    "kubernetes.io/psp": "eks.privileged"
  },
  "creationTimestamp": "2022-07-29T20:24:34Z",
  "generateName": "kube-proxy-",
  "labels": {
    "controller-revision-hash": "d99849db4",
    "k8s-app": "kube-proxy",
    "pod-template-generation": "2"
  },
  "name": "kube-proxy-xr74h",
  "namespace": "kube-system",
  "ownerReferences": [
    {
      "apiVersion": "apps/v1",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "DaemonSet",
      "name": "kube-proxy",
      "uid": "f3c7a3ad-820e-4e3e-bdf8-216c1f612a81"
    }
  ],
  "resourceVersion": "174335891",
  "uid": "66e70c79-a559-437d-be72-a0f093d81393"
}
{
  "annotations": {
    "checksum/agent-config": "99030e441a1690dee31e9d0b07916dbe23a5f54e3a8b751a6f375093daad829c",
    "checksum/integrations_config": "5da4ab0fd9975072b8415f617f8b4f56bd786e4a755175d5035123d7b319494b",
    "checksum/license-secret": "244a3f2411f1be7480b1b796322e0b6fc375762354d8f6070875d10622056f43",
    "checksum/nri-kubernetes": "56e1247cc185cd269480792f857d3431976d16d20ca82baafab85b5eea137664",
    "kubernetes.io/psp": "eks.privileged"
  },
  "creationTimestamp": "2022-07-29T20:23:35Z",
  "generateName": "newrelic-bundle-nrk8s-kubelet-",
  "labels": {
    "app.kubernetes.io/component": "kubelet",
    "app.kubernetes.io/instance": "newrelic-bundle",
    "app.kubernetes.io/name": "newrelic-infrastructure",
    "controller-revision-hash": "7668c449cb",
    "mode": "privileged",
    "pod-template-generation": "1"
  },
  "name": "newrelic-bundle-nrk8s-kubelet-ctkjb",
  "namespace": "newrelic",
  "ownerReferences": [
    {
      "apiVersion": "apps/v1",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "DaemonSet",
      "name": "newrelic-bundle-nrk8s-kubelet",
      "uid": "a561ba25-a4f2-4ebc-a88a-ce154e8f2fc7"
    }
  ],
  "resourceVersion": "174336421",
  "uid": "9e1312dd-8cd3-4847-8607-29910aedf1aa"
}
{
  "annotations": {
    "kubernetes.io/psp": "eks.privileged",
    "vizier-name": "pixie"
  },
  "creationTimestamp": "2022-08-05T00:47:59Z",
  "generateName": "vizier-pem-",
  "labels": {
    "app": "pl-monitoring",
    "component": "vizier",
    "controller-revision-hash": "5b79766bbc",
    "name": "vizier-pem",
    "plane": "data",
    "pod-template-generation": "6",
    "vizier-name": "pixie"
  },
  "name": "vizier-pem-tz25w",
  "namespace": "newrelic",
  "ownerReferences": [
    {
      "apiVersion": "apps/v1",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "DaemonSet",
      "name": "vizier-pem",
      "uid": "8486f69c-081c-4083-9af9-0858285a8f97"
    }
  ],
  "resourceVersion": "181022562",
  "uid": "877011d0-79b5-42a7-b602-51c14fd0a8ce"
}
{
  "annotations": {
    "kubernetes.io/psp": "eks.privileged",
    "meta.helm.sh/release-name": "newrelic-bundle",
    "meta.helm.sh/release-namespace": "newrelic"
  },
  "creationTimestamp": "2022-07-29T20:27:04Z",
  "generateName": "pixie-operator-index-",
  "labels": {
    "catalogsource.operators.coreos.com/update": "",
    "olm.catalogSource": "pixie-operator-index"
  },
  "name": "pixie-operator-index-r4vjg",
  "namespace": "px-operator",
  "ownerReferences": [
    {
      "apiVersion": "operators.coreos.com/v1alpha1",
      "blockOwnerDeletion": false,
      "controller": false,
      "kind": "CatalogSource",
      "name": "pixie-operator-index",
      "uid": "f46bead3-5e60-4fff-8800-afd74fd469c3"
    }
  ],
  "resourceVersion": "174337215",
  "uid": "771ea715-b351-4e8b-af47-fb673a8166fa"
}
```
So, if I am looking at this correctly there's a custom controller that owns some of these pods. But, I have seen nodes get terminated with these same pods attached to Karpenter provisioned nodes before (maybe luck timing?). Do you have any suggestions to work around this?

**Comment by tzneal** [comment]
Yup, that's it.  That pod which is owned by the CatalogSource is preventing the node from being deleted.  That shouldn't stop a node from expiring, but it will block it from being deleted as empty.  I think the #1532 feature request would cover this.

**Comment by toddatapiture** [comment]
🙇  Any ETA on this feature?

**Comment by pa5hgan** [comment]
Right, since source of the pod is not Daemonset, node should be kept living, according to current logic. But now I see that I have different situation, all pods running on a node, that is unwilling to be terminated, came from Daemonsets:
`kubectl get -A pod --field-selector spec.nodeName=ip-10-0-168-124.us-east-2.compute.internal |  grep Running | awk '{print "kubectl get pod -n " $1 " " $2 " -o json"}' | bash  | jq '.metadata'
{
  "annotations": {
    "checksum/config": "6ff266498d90744e1e393859030e47a38cabcbfadb71e1971f83cf0d5e09a514",
    "kubernetes.io/psp": "eks.privileged"
  },
  "creationTimestamp": "2022-08-10T08:38:23Z",
  "generateName": "aws-for-fluent-bit-",
  "labels": {
    "app.kubernetes.io/instance": "aws-for-fluent-bit",
    "app.kubernetes.io/name": "aws-for-fluent-bit",
    "controller-revision-hash": "6b87c5dcfb",
    "pod-template-generation": "1"
  },
  "name": "aws-for-fluent-bit-2zr59",
  "namespace": "kube-system",
  "ownerReferences": [
    {
      "apiVersion": "apps/v1",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "DaemonSet",
      "name": "aws-for-fluent-bit",
      "uid": "93e73183-3288-48a5-9aae-2b7239a4cc86"
    }
  ],
  "resourceVersion": "17801682",
  "uid": "f7b8462c-6f9c-4322-b85f-471b6f245651"
}
{
  "annotations": {
    "kubernetes.io/psp": "eks.privileged"
  },
  "creationTimestamp": "2022-08-10T08:38:23Z",
  "generateName": "aws-node-",
  "labels": {
    "app.kubernetes.io/name": "aws-node",
    "controller-revision-hash": "76f5646cfb",
    "k8s-app": "aws-node",
    "pod-template-generation": "6"
  },
  "name": "aws-node-7pw5c",
  "namespace": "kube-system",
  "ownerReferences": [
    {
      "apiVersion": "apps/v1",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "DaemonSet",
      "name": "aws-node",
      "uid": "f7063029-a286-4612-ab74-0226f14b62ef"
    }
  ],
  "resourceVersion": "17801334",
  "uid": "0cfc8c35-de34-4edf-bc63-e6953a755581"
}
{
  "annotations": {
    "kubernetes.io/psp": "aws-node-termination-handler"
  },
  "creationTimestamp": "2022-08-10T08:38:23Z",
  "generateName": "aws-node-termination-handler-",
  "labels": {
    "app.kubernetes.io/component": "daemonset",
    "app.kubernetes.io/instance": "aws-node-termination-handler",
    "app.kubernetes.io/name": "aws-node-termination-handler",
    "controller-revision-hash": "74bdd5d77c",
    "k8s-app": "aws-node-termination-handler",
    "kubernetes.io/os": "linux",
    "pod-template-generation": "1"
  },
  "name": "aws-node-termination-handler-9h4mc",
  "namespace": "kube-system",
  "ownerReferences": [
    {
      "apiVersion": "apps/v1",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "DaemonSet",
      "name": "aws-node-termination-handler",
      "uid": "1444fd78-d467-4aae-9658-8cb67038cd3f"
    }
  ],
  "resourceVersion": "17801229",
  "uid": "1471ef50-bedb-4d89-8bc5-2b935bdf1669"
}
{
  "annotations": {
    "kubernetes.io/psp": "eks.privileged"
  },
  "creationTimestamp": "2022-08-10T08:38:23Z",
  "generateName": "ebs-csi-node-",
  "labels": {
    "app": "ebs-csi-node",
    "app.kubernetes.io/component": "ebs-csi-node",
    "app.kubernetes.io/managed-by": "EKS",
    "app.kubernetes.io/name": "aws-ebs-csi-driver",
    "app.kubernetes.io/version": "1.8.0",
    "controller-revision-hash": "5f854897d8",
    "pod-template-generation": "2"
  },
  "name": "ebs-csi-node-bjbh2",
  "namespace": "kube-system",
  "ownerReferences": [
    {
      "apiVersion": "apps/v1",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "DaemonSet",
      "name": "ebs-csi-node",
      "uid": "ed7a1c49-d766-4435-a792-1f4e0be397a3"
    }
  ],
  "resourceVersion": "17801431",
  "uid": "bbce462e-c965-40c0-bb65-31c48f037819"
}
{
  "annotations": {
    "kubernetes.io/psp": "eks.privileged"
  },
  "creationTimestamp": "2022-08-10T08:38:23Z",
  "generateName": "kube-proxy-",
  "labels": {
    "controller-revision-hash": "5744c47fd",
    "k8s-app": "kube-proxy",
    "pod-template-generation": "2"
  },
  "name": "kube-proxy-w5g67",
  "namespace": "kube-system",
  "ownerReferences": [
    {
      "apiVersion": "apps/v1",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "DaemonSet",
      "name": "kube-proxy",
      "uid": "e60cc862-5f11-4272-bc04-b6e89aacfd48"
    }
  ],
  "resourceVersion": "17801231",
  "uid": "a6985af7-ad11-4303-96a3-c097ae464f07"
}`

Label INITIALIZED:
`kubectl get node -L karpenter.sh/initialized
NAME                                         STATUS   ROLES    AGE    VERSION               INITIALIZED
ip-10-0-157-181.us-east-2.compute.internal   Ready    <none>   2d1h   v1.22.9-eks-810597c
ip-10-0-161-201.us-east-2.compute.internal   Ready    <none>   38h    v1.22.9-eks-810597c   true
ip-10-0-168-124.us-east-2.compute.internal   Ready    <none>   34m    v1.22.9-eks-810597c   true`

**Comment by pa5hgan** [comment]
Found the issue in my setup, provisioner got wrong value in ttlSecondsAfterEmpty parameter, misconfiguration. It became clear with additional logging in emptiness subreconciler. @tzneal thanks for the help!
