### ISSUE TITLE
Instance tags do not get updated when a node template gets updated

### ISSUE THREAD

**Issue by blakepettersson** [aws/karpenter#2257]
**Tell us about your request**
When an `AWSNodeTemplate` gets updated with new tags, I'd want to see all instances that are making use of said node template to get their tags updated, alternatively that new instances gets spawned with said tags. I'm not sure whether this is more of a bug than a missing feature, but I'm leaning towards the latter.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
In this case I just wanted to update the `Name` tag from the default name generated by Karpenter. We have a bunch of clusters managed by dev-teams, whom we also would like to be properly managing their own tags (for cost allocation purposes among other things) in the very near future. It's a bit prohibitive to be asking them to be terminating their nodes and/or scaling up and down their applications every time a tag gets updated.   

**Are you currently working around this issue?**
For this case, there's not much of a workaround other than recreating any instances that are making use of the node template.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
This is related to this issue on keeping the spec and current state of nodes consistent: https://github.com/aws/karpenter/issues/1457

**Comment by blakepettersson** [comment]
Seems like that one is closed in favour of #1738

**Comment by ellistarn** [comment]
Closing. Let's track this work in #1738
