### ISSUE TITLE
Allow setting the --cpu-manager-policy to static and use --reserved-cpus in kubeletConfiguration

### ISSUE THREAD

**Issue by liorfranko** [aws/karpenter#2271]
**Tell us about your request**
I would like to provision some of the nodes with static CPU.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We need to be able to change the --cpu-manager-policy from none to static and reserve CPUs for daemonsets.

**Are you currently working around this issue?**
No

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
This should help you in the upcoming v0.14.0 release: https://karpenter.sh/preview/provisioner/#system-reserved-resources 

You can set the cpuManagerPolicy directly in the kublet-configuration on the node in a user-data script specified on the AWSNodeTemplate https://karpenter.sh/preview/aws/user-data/#al2-and-ubuntu

**Comment by njtran** [comment]
Closing as v0.14.0 has been released. Feel free to open if you have more questions.
