### ISSUE TITLE
Migrating from Cluster Autoscaler

### ISSUE THREAD

**Issue by kafkasl** [aws/karpenter#2275]
If I try to add a custom provisioner with `kubectl apply -f karpenter-provisioner.yaml` I get the following error. I copied one of the provisioner examples provided.

```
unable to recognize "karpenter-provisioner.yaml": no matches for kind "Provisioner" in version "karpenter.sh/v1alpha5"
unable to recognize "karpenter-provisioner.yaml": no matches for kind "AWSNodeTemplate" in version "karpenter.k8s.aws/v1alpha1"
```

**Comment by njtran** [comment]
Have you deployed Karpenter yet with Helm? https://karpenter.sh/v0.13.2/getting-started/migrating-from-cas/#deploy-karpenter

**Comment by njtran** [comment]
Hopefully you should be able to create these provisioners once you have helm installed. Closing this. Feel free to re-open if that doesn't solve it.
