### ISSUE TITLE
How does Karpenter provision capacity for jobs?

### ISSUE THREAD

**Issue by georgeboot** [aws/karpenter#2281]
**What karpenter features are relevant?**
provisioning

**How should the docs be improved?**
We have a cluster that we primarily use for running heavy and log jobs (think multiple hours with 4-10 CPU and 16-64GB RAM). These taks don't run all the time. Sometimes we run none, sometimes we run multiple concurrently. In addition to that, we have some regular deployments that run 24/7.

How could Karpenter provision capacity for the above scenario? From that I understand from the docs, it will provision the most efficient instances fitting the needs of the deployments. Additionally, when one or more jobs need to be scheduled, it will provision nodes for the known requirements at that point.

Will this in practice mean that every job gets it's own node? Is this still the most efficient? I know I can prevent downscales, leave some spare capacity, but with our rather unpredictable load, this practically means throwing money at the problem which will not make it any more efficient.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
> Will this in practice mean that every job gets it's own node? Is this still the most efficient? I know I can prevent downscales, leave some spare capacity, but with our rather unpredictable load, this practically means throwing money at the problem which will not make it any more efficient.

that depends on your antiaffinity
https://github.com/aws/karpenter/blob/5167f5b/examples/workloads/spread-hostname-zone.yaml#L27

**Comment by georgeboot** [comment]
So how would that work in practice? Say the cluster is running with 2 nodes, both (almost) fully utilised with the running workloads (deployments).

Then, a job comes in that requires at minimum 6 cores and 20GiB RAM. I assume that Karpenter will now provision a new node that fits closely to the job, or alternatively, a node that fits the job + some of the deployments that can be re-scheduled.

What if another job comes in? It can't re-schedule the already running job, so I guess this one will go to it's own node, right?

**Comment by FernandoMiguel** [comment]
> What if another job comes in? It can't re-schedule the already running job, so I guess this one will go to it's own node, right?
yes

**Comment by FernandoMiguel** [comment]
karpenter is only there to provide your cluster hardware capacity if there are pending pods with no place to be placed

**Comment by georgeboot** [comment]
But I guess it will also move things around then that is more efficient?

From what I understand from the docs, it can taint /drain a node and have the scheduler re-schedule the pods to a new home.

**Comment by FernandoMiguel** [comment]
that code is not yet merged. expected to be deployed on 0.15

**Comment by FernandoMiguel** [comment]
https://github.com/aws/karpenter/blob/main/designs/consolidation.md
