### ISSUE TITLE
Consolidate on a schedule

### ISSUE THREAD

**Issue by maximmold** [aws/karpenter#2308]
**Tell us about your request**
The new consolidation feature looks promising. I would like to update this to have the provisioner only consolidate during certain time windows to reduce impact to tenants.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
For workloads that would not easily shift to other nodes without disruption, I'd prefer for these happen at night to reduce the affect on platform tenants.

**Are you currently working around this issue?**
It may be possible to have cron job update the consolidation flag on a nightly schedule. This is still TBD.

**Additional context**
n/a

**Attachments**
n/a

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Related: https://github.com/aws/karpenter/issues/1738

**Comment by ellistarn** [comment]
> It may be possible to have cron job update the consolidation flag on a nightly schedule. This is still TBD.

We recommend this in the short term. There may by other orchestration mechanisms like Kyverno that can help with this case. Generally, we're hoping to operate at a lower level of abstraction.

**Comment by sidewinder12s** [comment]
Also related: #1302

**Comment by njtran** [comment]
Hey all, if you're tracking this issue, come give some feedback on https://github.com/aws/karpenter-core/pull/207!

**Comment by sichiba** [comment]
Hello, any news about this feature so far?

**Comment by ellistarn** [comment]
Closing in favor of #1302 mega issue
