### ISSUE TITLE
Support for burstable performance instances selector

### ISSUE THREAD

**Issue by cebernardi** [aws/karpenter#2321]
**Tell us about your request**
We would need a selector for Burstable performance instances.

It could be something like
```
karpenter.k8s.aws/instance-cpu-performance [burstable, not-burstable]
```
(or maybe `karpenter.sh/instance-cpu-performance`?)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

We would like to exclude or include burstable machine types in our provisioners.

This could be partially achieved using the `karpenter.k8s.aws/instance-family` selector, but this method requires to update the Provisioners every time AWS emits a new family of burstable machines, leading to possible leaks in the meanwhile. 

**Are you currently working around this issue?**

We're explicitly excluding `T4g`, `T3`, `T3a` and `T2` families with the `karpenter.k8s.aws/instance-family` selector

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by cebernardi** [comment]
I would be happy to contribute to the feature

**Comment by FernandoMiguel** [comment]
FYI
> Karpenter filters out t2's by default unless directly specified in the provisioner spec.

https://github.com/aws/karpenter/pull/2227#discussion_r935745866

**Comment by ellistarn** [comment]
Does karpenter.k8s.aws/instance-category = "T" solve this use case instead?

**Comment by bwagner5** [comment]
This should solve filtering out Burstable types. Feel free to reopen if this doesn't fulfill your use-case.


```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: gpu
spec:
  requirements:
  - key: karpenter.k8s.aws/instance-category
    operator: NotIn
    values:
      - t
```

**Comment by cebernardi** [comment]
This assumes that AWS will release burstable machines only in the T category (for reasonably long time).

Can you confirm this?

Our main use case was to protect our fleet from leaks in case of AWS releasing new burstable machines under a different family.

**Comment by cebernardi** [comment]
@bwagner5 @ellistarn can you kindly confirm the above?
