### ISSUE TITLE
Statefulsets fail scheduling on Karpenter managed spot nodes

### ISSUE THREAD

**Issue by njohnstone2** [aws/karpenter#2344]
## Version
**Karpenter**: v0.14.0
**Kubernetes**: v1.23.7-eks-4721010

## Expected Behavior
statefulset pods are successfully deployed on karpenter managed `spot` nodes

## Actual Behavior
Scheduling fails when assigning more than one statefulset replica to spot nodes managed by karpenter with the following error

```Failed to provision new node, incompatible with provisioner "spot-nodes", incompatible requirements, key topology.kubernetes.io/region does not have known values```

This same statefulset is scheduled successfully when a toleration is added to ensure scheduling via a second provisioner that uses the `on-demand` instance type. 

## Steps to Reproduce the Problem
- deploy the karpenter provisioner `kubectl apply -f provisioner.yaml`
- deploy test statefulset `kubectl apply -f sts.yaml`

### Provisioner
    apiVersion: karpenter.sh/v1alpha5
    kind: Provisioner
    metadata:
      name: spot-nodes
    spec:
      kubeletConfiguration:
        systemReserved:
          cpu: 800m
          ephemeral-storage: 1Gi
          memory: 2Gi
      limits:
        resources:
          cpu: 1k
      provider:
        securityGroupSelector:
          karpenter.sh/discovery: my-eks-cluster
        subnetSelector:
          karpenter.sh/discovery: my-eks-cluster
      requirements:
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c4.2xlarge
        - c5.2xlarge
        - c3.2xlarge
        - c5d.2xlarge
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - ap-southeast-2a
        - ap-southeast-2b
        - ap-southeast-2c
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      ttlSecondsAfterEmpty: 30
      ttlSecondsUntilExpired: 1209600

### Statefulset (excuse the hacked together test manifest)
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: teststs
      namespace: default
    spec:
      selector:
        matchLabels:
          app: test
      serviceName: "test"
      replicas: 3
      minReadySeconds: 10
      template:
        metadata:
          labels:
            app: test
        spec:
          terminationGracePeriodSeconds: 10
          containers:
          - name: inflate
            image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
            volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
      volumeClaimTemplates:
      - metadata:
          name: www
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "gp2"
          resources:
            requests:
              storage: 100Mi

### Controller log
```karpenter-5db9ffbfc-zdxrm controller 2022-08-23T05:28:18.078Z	ERROR	controller.provisioning	Could not schedule pod, incompatible with provisioner "spot-nodes", incompatible requirements, key topology.kubernetes.io/region does not have known values	{"commit": "5edcce3", "pod": "default/teststs-1"}```

**Comment by njohnstone2** [comment]
Unsure if this is related to https://github.com/aws/karpenter/pull/1299

**Comment by bwagner5** [comment]
I think this is related to this fix https://github.com/aws/karpenter/pull/2294

If you upgrade to v0.15.0, things should start working

**Comment by njohnstone2** [comment]
Thanks @bwagner5, this is the same issue as described in your link and upgrading has resolved the failed scheduling.
