### ISSUE TITLE
Error in Install documentation with Helm TF provider

### ISSUE THREAD

**Issue by photosojourn** [aws/karpenter#2345]
Hey, 

During testing, I found an error in the examples for [Getting Started with Terraform - Install Karpenter Helm Chart](https://karpenter.sh/v0.15.0/getting-started/getting-started-with-terraform/#install-karpenter-helm-chart). Due to changes released in Kubectl 1.24 which where rolled into Helm the TF provider needs to the pinned to version .2.5.1 as documented [here](https://github.com/hashicorp/terraform-provider-helm/issues/893).

Given EKS 1.23 is out the whole section prob needs a refresh. :)

Thanks!

**Comment by FernandoMiguel** [comment]
but those docs already use v1beta1, not v1alpha1
`      api_version = "client.authentication.k8s.io/v1beta1"`

**Comment by bwagner5** [comment]
Is the only part missing the version pin? 

```
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.5"
    }
```

I thought that `~> 2.5` would allow 2.5.1 , but I might be mistaken. 


From Terraform docs:
```
[~>](https://www.terraform.io/language/expressions/version-constraints#-3): Allows only the rightmost version component to increment. For example, to allow new patch releases within a specific minor release, use the full version number: ~> 1.0.4 will allow installation of 1.0.5 and 1.0.10 but not 1.1.0. This is usually called the pessimistic constraint operator.
```

This reads like `~> 2.5` only allows it to install 2.6 and not patches... which makes no sense to me... 

Maybe we should use `>= 2.5.1, < 3.0.0` ?

**Comment by FernandoMiguel** [comment]
> I thought that `~> 2.5` would allow 2.5.1 , but I might be mistaken.

from my experience, it should. but very easy to test
