### ISSUE TITLE
Upgrade Guide

### ISSUE THREAD

**Issue by yum-dev** [aws/karpenter#2360]
It doesn't specify to do a `helm upgrade` after updating the CRDs.

**Comment by FernandoMiguel** [comment]
Are you referring to this guide?
https://karpenter.sh/preview/upgrade-guide/#custom-resource-definition-crd-upgrades

**Comment by bwagner5** [comment]
You could apply the CRDs before you upgrade or after. We don't have a full list of steps for upgrades since the installation method can vary between users (helm, terraform, kustomize, cdk, flux, argo, etc.)
