### ISSUE TITLE
[Feature Request] add instance ID to the logs

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/karpenter#2362]
**Tell us about your request**
What do you want us to build?
show aws ec2 instance ID in the logs

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.
Right now the logs show something like
`2022-08-25T13:01:34.069Z    INFO    controller.termination    Deleted node    {"commit": "639756a", "node": "ip-10-24-25-63.ec2.internal"}`
when using multiple ENIs on ec2, this IP format does not really help locate the instance.
Having the instance ID would allow for a 1:1 mapping and easier finding

**Are you currently working around this issue?**
How are you currently solving this problem?
haven't found an easy solution for this 

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
We could add more to the log there, but curious if you have looked into instance-id based node names instead of using the IP address. This was released a while back and hopefully will become the default node name for K8s nodes: https://github.com/aws/containers-roadmap/issues/1723 .

**Comment by bwagner5** [comment]
The node name in your case is the IP-based DNS name of the root ENI attached to the instance. You should be able to query it for a specific node with this command:

```
NODE_NAME=ip-10-24-26-90.ec2.internal
aws ec2 describe-instances --filters Name=private-dns-name,Values=${NODE_NAME}
```

The Private DNS Name filter also exists in the EC2 console search. 

But I was suggesting that moving to instance-id based host named might be more clear for lookups. If you switched to [resource based DNS names](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-naming.html) your node name would look like this: `i-0123456789abcdef.ec2.internal`

**Comment by FernandoMiguel** [comment]
thanks for the link. i'll go over the docs and see the impact on our accounts

**Comment by FernandoMiguel** [comment]
i think my main issue here is that once the instance is terminated, the ENI is detached so there is nothing to look up by the IP name.
Running instance are searchable tho.
