### ISSUE TITLE
Managing CRDs with Terraform

### ISSUE THREAD

**Issue by rpadovani** [aws/karpenter#2382]
Hi all,
thank you so much for this wonderful autoscaler! I use it in production and cannot be happier.

One thing that bothers me is managing the CRDs: I use Terraform and GitOps for everything, so having to manually manage the lifecycle for CRDs manually is a big no-go in my book.

For this, I have created a small Terraform module, that uses the `http` provider and `gavinbunney/kubectl` to download YAML manifests from GitHub and install them on the cluster.

I use it like this:

```
module "karpenter-crds" {
  source  = "rpadovani/helm-crds/kubectl"
  version = "0.1.0"
  
  crds_urls = [
    "https://raw.githubusercontent.com/aws/karpenter/v${var.chart_version}/charts/karpenter/crds/karpenter.sh_provisioners.yaml",
    "https://raw.githubusercontent.com/aws/karpenter/v${var.chart_version}/charts/karpenter/crds/karpenter.k8s.aws_awsnodetemplates.yaml"
  ]
}
```

Notice the `var.chart_version` to be sure to use the right CRDs definition. In this way, everything is managed by Terraform.

Question: would you be interested if I create a pull request to add such a module to the documentation for Terraform? I don't want to spam the module, I truly think it is a valuable addition. However, I opened this ticket before just to be sure that it would be okay with you all as well. What do you think?

Meanwhile, have a lovely weekend, and keep up the good work :-)

**Comment by FernandoMiguel** [comment]
I did something very similar in blueprints 
https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/883/files
no need for extra modules btw.
but yeah, having this in the docs or examples can help others

**Comment by rpadovani** [comment]
> I did something very similar in blueprints https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/883/files no need for extra modules btw. but yeah, having this in the docs or examples can help others

Oh, I didn't see your blueprints, nice!
Yeah, I went the module way 'cause many Helm Charts have CRDs, but for Karpenter examples, of course just writing the 3 resources is more than enough :-) Do you think would it be better an example or the documentation?

**Comment by FernandoMiguel** [comment]
I do
