### ISSUE TITLE
Node provisioning invalid capacity 0 on image filesystem

### ISSUE THREAD

**Issue by njohnstone2** [aws/karpenter#2385]
## Version

**Karpenter**: v0.16.0

**Kubernetes**: v1.23.7-eks-4721010

## Notes
This is more of a query and does not affect the functionality of the node. I am only logging as node event monitoring logs this every time a new node is provisioned.

## Expected Behavior

Karpenter creates the EBS volume before initializing the node.

## Actual Behavior

The new node does not detect the EBS volume size and logs `InvalidDiskCapacity` warnings on startup.

## Steps to Reproduce the Problem

- Trigger karpenter node scale up
-  Check node events

### Node Events
    Events:
      Type     Reason                   Age                    From        Message
      ----     ------                   ----                   ----        -------
      Normal   Starting                 2m10s                  kube-proxy  
      Warning  InvalidDiskCapacity      2m18s                  kubelet     invalid capacity 0 on image filesystem
      Normal   NodeAllocatableEnforced  2m18s                  kubelet     Updated Node Allocatable limit across pods
      Normal   Starting                 2m18s                  kubelet     Starting kubelet.
      Normal   NodeHasSufficientMemory  2m15s (x3 over 2m18s)  kubelet     Node ip-10-202-144-6.ap-southeast-2.compute.internal status is now: NodeHasSufficientMemory
      Normal   NodeHasNoDiskPressure    2m15s (x3 over 2m18s)  kubelet     Node ip-10-202-144-6.ap-southeast-2.compute.internal status is now: NodeHasNoDiskPressure
      Normal   NodeHasSufficientPID     2m15s (x3 over 2m18s)  kubelet     Node ip-10-202-144-6.ap-southeast-2.compute.internal status is now: NodeHasSufficientPID
      Normal   NodeReady                105s                   kubelet     Node ip-10-202-144-6.ap-southeast-2.compute.internal status is now: NodeReady

**Comment by mogggggg** [comment]
We just had one node that seems to have had this same issue. After 20 minutes of being NotReady is was removed and there have been instances since then that have started without problems.

Karpenter: v0.15.0
Kubernetes: v1.23.7-eks-7709a84

**Comment by haarchri** [comment]
we have the same issue on v0.19.1 any ideas what happen?

**Comment by ellistarn** [comment]
Does the kubelet recover? I wonder if this is a result of Karpenter creating the node object, and this breaking assumptions in k8s 1.23. Did you upgrade nodes/master recently? Does reverting to an older version of Karpenter help?

**Comment by FernandoMiguel** [comment]
@ellistarn we started seeing this on 0.19 only. it's not happening on previous versions.
AFAICT, it has no impact since the node will be READY anyway.
Feels more like unwanted warnings

**Comment by FernandoMiguel** [comment]
When I saw this, it was happening on all brand new nodes after the upgrade to 0.19

**Comment by jonathan-innis** [comment]
@njohnstone2, we have a design doc up now that should address this issue: #2944

**Comment by jonathan-innis** [comment]
@njohnstone2 Are you still seeing this event on `v0.28.0-rc.1` that we just released where we now don't create the node? I would expect that the EBS volume should mount now before the node registers to the cluster.

**Comment by njohnstone2** [comment]
@jonathan-innis apologies for the very slow response. Yes this is still occurring in 0.29.0. Based on https://github.com/aws/containers-roadmap/issues/1403 this may be an EKS issue?
