### ISSUE TITLE
How to get instance type inside the pod?

### ISSUE THREAD

**Issue by n07n0w** [aws/karpenter#2398]
Hello,

I use karpenter (and it's amazing) with Gitlab pipeline, to run ML pods on GPU

I want to calculate the price of each pipeline and show it at the end.
I have the execution time, and price of each instance, 
but what node type executes the pod, that was scheduled by Karpenter?

Is it possible somehow to get this information, 
other than using kubectl outside of the pod, or reading karpenter logs?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
i assume you are using instance metadata?
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
`instance-type` is available

**Comment by n07n0w** [comment]
Thank you for pointing this out, the real issue is how I create a kubernetes cluster, because the metadata URL is unreachable.

**Comment by FernandoMiguel** [comment]
> Thank you for pointing this out, the real issue is how I create a kubernetes cluster, because the metadata URL is unreachable.

@n07n0w you need to change the IMDS hop value to two
