### ISSUE TITLE
Provisioner should default to `amd64` if `kubernetes.io/arch` is not set under requirements

### ISSUE THREAD

**Issue by aaroniscode** [aws/karpenter#2407]
## Version

**Karpenter**: v0.16.0

**Kubernetes**: v1.23.7

## Expected Behavior

Using the default provisioner in the docs, I expect my non-multi-arch containers to run.

## Actual Behavior

Karpenter is launching Graviton nodes, ie c6g and t4g nodes

**Comment by sbkg0002** [comment]
I'd argue that the default should be configurable.

**Comment by FernandoMiguel** [comment]
I believe that if no arch is added to the provisioner, it will do amd64 only.
but if you are using a provisioner, you choose what arch you want to support.
can you share it @aaroniscode  ?

**Comment by FernandoMiguel** [comment]
@sbkg0002 a default is a default... it's what it is if nothing is provided.
and arch is entirely customisable
