### ISSUE TITLE
Fargate profile namespace selector does not allow core-dns to be scheduled on Fargate

### ISSUE THREAD

**Issue by eichlerr** [aws/karpenter#2426]
**Is an existing page relevant?**
[Example 2: Create basic cluster with Karpenter on Fargate](https://karpenter.sh/v0.16.0/getting-started/getting-started-with-eksctl/#create-a-cluster)

**What karpenter features are relevant?**
Instructions for creating a cluster with Karpenter on Fargate omit the fact that `core-dns` needs to run in the `kube-system` namespace. Using `karpenter` as the namespace selector means that `core-dns` isn't able to be scheduled on the cluster after it's created using the example provided.

**How should the docs be improved?**
Add `kube-system` as a namespace selector in the sample yaml file to create a cluster for Karpenter using Fargate.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
@eichlerr i believe the idea is for ONLY karpenter to run on fargate.
Karpenter will then add ec2 nodes where `core-dns` runs.

FYI `core-dns` does not run on fargate without some heavy modifications, and even then I never had it run stable there, sadly.

**Comment by eichlerr** [comment]
`eksctl` has an option to create a [Fargate-only cluster](https://eksctl.io/usage/fargate-support/#creating-a-cluster-with-fargate-support) in the docs which modifies `core-dns` (see note [here](https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html#fargate-gs-coredns)) to run on Fargate, so I don't know why we wouldn't just do the same in the Karpenter example for using Karpenter with Fargate.

**Comment by FernandoMiguel** [comment]
wasnt aware of that modification.
