### ISSUE TITLE
Add Termination Reason Metrics

### ISSUE THREAD

**Issue by njtran** [aws/karpenter#2443]
**Tell us about your request**
Currently in Karpenter, nodes can be deleted by a select number of reasons:
- Consolidation Node Deletion
- Consolidation Node Replacement
- Emptiness
- Expiration
- Manual User Termination (`kubectl delete node`)

In the future we may handle more reasons as well. We should add go metrics that indicate the number of node termination requests and segment by the reasons the nodes were deleted so that users can include this in metrics dashboards. 

**Additional context**
We should also add this into the Grafana dashboards.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Tracking manual termination seems a little more difficult and feels out-of-scope to me for the project
