### ISSUE TITLE
Remove namespace field for webhooks configuration in helm chart

### ISSUE THREAD

**Issue by olfway** [aws/karpenter#2464]
## Version

**Karpenter**: v0.16.1

## Expected Behavior
MutatingWebhookConfiguration and ValidatingWebhookConfiguration should be cluster resources

## Actual Behavior
Helm chart adds "namespace" field to their manifests
```
charts/karpenter/templates/webhooks.yaml:
...
  namespace: {{ .Release.Namespace }}
...
```

**Comment by spring1843** [comment]
I think you are referring to [L5](https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/webhooks.yaml#L5) and  [L48](https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/webhooks.yaml#L48).

It makes sense to me to remove them, but is this currently causing an issue for you?

**Comment by olfway** [comment]
Yes, you are right, exactly these lines

I was installing karpenter with terraform + kustomize provider
https://registry.terraform.io/providers/kbst/kustomization/latest/docs

It generates resources id like this:
```
group/Kind/namespace/name with _ as a placeholder for empty values
```
So it generates id with namespace but cannot verify that manifest in k8s and print strange "resource not found" error
