### ISSUE TITLE
validation.webhook.config.karpenter.sh ValidatingWebhookConfiguration has no rules

### ISSUE THREAD

**Issue by grosser** [aws/karpenter#2472]
the [webhook](https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/webhooks.yaml#L84-L103) has no rules, which means it would match every object ?
kubernetes docs say a [webhook needs rules](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-rules)

please add `rules` or some inline docs on what having no rules does for the webhook

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
I'm not sure if this is needed because it's using [objectSelector](https://github.com/aws/karpenter/blob/ff931f9c81d8ce6192eeaaeadc1750f21f94f617/charts/karpenter/templates/webhooks.yaml#L101) and matchLabels:

```
  Object Selector:
    Match Labels:
      app.kubernetes.io/part-of:  karpenter
```

So it's not matching every object.

**Comment by grosser** [comment]
but this will still match against every kind of thing in the cluster, it would be nice to scope this to what is intended (pods or webhook ... or whatever this is actually used fro)

**Comment by saurabhpal97** [comment]
I can take a stab at it if this issue is not being worked on rn

**Comment by ellistarn** [comment]
I think this is updated at runtime by the Karpenter webhook controller. Should be fine to statically populate it if the values are the same.

**Comment by ellistarn** [comment]
What's the AI here?

**Comment by grosser** [comment]
what is AI and who are you asking ?

**Comment by ellistarn** [comment]
Action item. I'm not sure I understand what the request is for this issue.

**Comment by grosser** [comment]
add rules to the webhook

**Comment by ellistarn** [comment]
I'm confused: https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/webhooks.yaml#L20

**Comment by grosser** [comment]
seems to be solved then 🎉
