### ISSUE TITLE
Metrics are missing

### ISSUE THREAD

**Issue by himanshurajput32** [aws/karpenter#2473]
## Version

**Karpenter**: v0.16.0

**Kubernetes**: v1.21.0

## Expected Behavior

Karpenter should expose all the metrics listed here https://karpenter.sh/v0.16.0/tasks/metrics/
## Actual Behavior

Metrics are missing for provisioners and few other also.
https://karpenter.sh/v0.16.0/tasks/metrics/#provisioner-metrics
## Steps to Reproduce the Problem

Use `/metrics` endpoint

**Comment by tzneal** [comment]
In v0.16.0 we only reported provisioner metrics if limits were set on the provisioner. v0.16.1 added a change where we would always report the provisioner status metrics, even if limits weren't set.  Are there other metrics missing?

**Comment by himanshurajput32** [comment]
Thanks @tzneal , we will try `0.16.1` for provisioner metrics as our provisioners don't have any limits.

The other missing metrics are as -
```
karpenter_nodes_count
karpenter_kube_api_time_seconds
karpenter_consolidation_actions_performed
karpenter_consolidation_evaluation_duration_seconds
```

**Comment by jonathan-innis** [comment]
@himanshurajput32 Do you have any update here? Did `v0.16.1` fix the issue for you?
