### ISSUE TITLE
Support for specifying memory and CPU constraints on instance types

### ISSUE THREAD

**Issue by broonie** [aws/karpenter#2483]
What do you want us to build?

Currently it is possible to specify an explicit list of instance types that Karpenter will consider using with things that end up as labels on the node like architecture or instance type but it does not so far as I can tell appear to be possible to specify constraints on other parameters like CPU or memory.

What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

The basic issue I have is that for one of my workloads I end up with Karpenter creating quite large instances (eg, I have a i4i.32xlarge running now) which often spend a lot of time quite lightly utilised (eg, the actually running jobs on that node fit fine into an r6gd.8xlarge).

My particular use case is that I'm starting a lot of batch jobs which have wildly varying runtimes. Unfortunately there's not a constant stream of new jobs, instead the jobs are generated in intermittent bursts. This results in some very large instances getting allocated to handle the initial burst of work with large and small jobs distributed over them which end up being underutilised as the shorter jobs finish and the larger jobs continue to run (it's not a binary, there's a sliding scale here). Since I know how many CPUs and how much memory are allocated to the largest jobs I run if I could constrain the node types such that only a limited number of such jobs would run on a given node I could greatly improve the utilisation of individual nodes which would in turn improve cost efficiency.

How are you currently solving this problem?

Currently I'm mostly just ignoring the issue since overall it's not causing huge issues, though it is clearly increasing cost. The most obvious workaround is to constrain the total set of resources allocatable by Karpenter such that they can't all be started immediately and the Kubernetes scheduler can pack the nodes, though there's an obvious latency tradeoff there.

Another straightforward workaround would be for me to explicitly enumerate a set of node types that could be used but this is cumbersome as a very large set of node types would be suitable and the set of node types offered is constantly changing. 

I could also mitigate the issue by tagging jobs so that they end up in separate node pools depending on how long they're likely to run for, though for implementation reasons specific to what I'm doing it'd be hassle to identify the jobs ahead of time.

Anything else we should know?

If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

eksctl has a feature which does some of this, you can specify a nodeGroup with explicit memory and vCPUs parameters and the cluster will then pick any instance type that meets the requirements.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by broonie** [comment]
https://github.com/aws/karpenter/issues/1091 is somewhat related here - this is more attacking things from the other end by reducing the need to consolidate.

**Comment by tzneal** [comment]
I wrote up some new docs at https://karpenter.sh/preview/aws/provisioning/#aws-specific-labels , specifically does something like this in your provisioner work to limit your node sizes:

```yaml
  - key: karpenter.k8s.aws/instance-cpu
    operator: Lt
    values:
    - "9"
  - key: karpenter.k8s.aws/instance-memory
    operator: Lt
    values:
    - "16385"
```

**Comment by broonie** [comment]
Ah, nice - looks like this should just be a request to add those to the docs then rather than any sort of implementation thing.

**Comment by FernandoMiguel** [comment]
> Ah, nice - looks like this should just be a request to add those to the docs then rather than any sort of implementation thing.

https://github.com/aws/karpenter/pull/2467

https://karpenter.sh/preview/aws/provisioning/#:~:text=These%20requirements%20can%20be%20useful%20to%20select%20nodes%20of%20a%20particular%20%E2%80%9Cshape%E2%80%9D.%20For%20example%20the%20following%20filters%20out%20all%20instance%20types%20with%20more%20than%208%20CPUs%20or%20more%20than%2016%20GiB%20of%20memory%3A

**Comment by broonie** [comment]
Thanks, that's much more discoverable - I think I'd have found that when I was looking and it does explicitly call out the CPU and memory options in the examples.
