### ISSUE TITLE
support startupTaints without exact value match

### ISSUE THREAD

**Issue by grosser** [aws/karpenter#2484]
**Tell us about your request**
our startup script updates the value of the startuptaint, leading to new nodes getting started while the previous is not finished

logic is [here](https://github.com/aws/karpenter/blob/84a44abb719f1f0f63ef1b44b82bd9fa989a0e73/pkg/controllers/provisioning/scheduling/existingnode.go#L81)

result looks like this: (false column is our internal "ready" label that gets set once the taint is gone)
```
ip-172-30-225-58.us-west-2.compute.internal   Unknown   <none>   44s                              us-west-2a
ip-172-30-227-25.us-west-2.compute.internal   Ready     node     4m53s   v1.23.7   false          us-west-2b
```

so what I'd need is some way to either declare the taint an `ephemeralTaints` (but without a value) or some way to make a startuptaint ignore the value, for example by setting a fake `any` value

**Are you currently working around this issue?**

not updating the taint value

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Can you explain a little more about how the startup script is updating the value of the startup taint and how this is causing an issue with the current Karpenter startup taint logic?

Currently, we don't consider a node initialized until the startupTaint is removed, and we consider whether the startupTaint is removed [based off of the key:effect pair](https://github.com/aws/karpenter/blob/main/pkg/controllers/node/initialization.go#L89), the value is not considered in this logic.

**Comment by grosser** [comment]
hmm yeah, this codepath seems to go by key:effect as per [docs](https://pkg.go.dev/k8s.io/kubernetes/pkg/apis/core#Taint.MatchTaint) but the issue I see is that a new node gets created as soon as the taint value is changed

**Comment by jonathan-innis** [comment]
After repro-ing, I can see why this is happening. The [original link] you had was correct. When the node is updated, we attempt to re-schedule the pods and since the taint's value doesn't match, we try to launch a new node.

So an exact value match is currently required.

> our startup script updates the value of the startuptaint, leading to new nodes getting started while the previous is not finished

Can I ask, why don't you just break the phases of your node startup into pieces by introducing multiple taints that handle the multiple phases of startup? That would get around this problem of you needing a wildcard match for your taints.

**Comment by grosser** [comment]
Our workaround is to never update the value.
If there is no downside to changing the logic I'd still prefer it to be
key+effect only like the other taint compares.

**Comment by jonathan-innis** [comment]
There is a downside, which is that we should honor the taint exactly as it is state in the Provisioner spec. We can't really change this behavior without breaking existing functionality. Unfortunately a taint is a combination of the key/value/effect together and an "empty" value in a taint just means the matching toleration should be `""`.

I'm not really in favor of expanding this logic as a feature if there is a workaround for the use-case.

**Comment by grosser** [comment]
let's close this then ... easy enough to work around and not worth the trouble if nobody else ran into this
