### ISSUE TITLE
Price List Query API stale without VPC Endpoints when running karpenter in private subnets

### ISSUE THREAD

**Issue by htoo97** [aws/karpenter#2485]
**Tell us about your request**
When running Karpenter in an isolated private subnet (without any Internet egress via IGW or NAT gateways), we see the following error, which presumably means we are using stale pricing data.
```
ERROR   controller.aws.pricing  updating on-demand pricing, RequestError: send request failed
caused by: Post "https://api.pricing.us-east-1.amazonaws.com/": dial tcp 52.94.231.236:443: i/o timeout; RequestError: send request failed
caused by: Post "https://api.pricing.us-east-1.amazonaws.com/": dial tcp 52.94.231.236:443: i/o timeout, using existing pricing data from 2022-08-17T00:19:52Z  {"commit": "4b5f953"}
```
It does not seem like there is a VPC endpoint available for the [Price List Query API](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/using-pelong.html), according to the list of services in https://docs.aws.amazon.com/vpc/latest/privatelink/aws-services-privatelink-support.html. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Since there is no VPC endpoint officially supported yet for the pricing API, at least a doc update on https://aws.github.io/aws-eks-best-practices/karpenter/#amazon-eks-private-cluster-without-outbound-internet-access would be great to warn that price data will be stale without.

**Are you currently working around this issue?**
No workarounds, just using the stale data.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
Why you say "warn that price data will be stale without", do you mean in the error message?

If so it already [does that](https://github.com/aws/karpenter/blob/de309caa29a76aa3e8cd220c525f9b3970282c10/pkg/cloudprovider/aws/pricing.go#L198). The rest of the error message should tell you pricing data from what date will be used instead.

**Comment by htoo97** [comment]
Sorry for the ambiguity, to clarify, I think it would make sense to warn this on the documentation itself linked above, so that users don't have to find out only at runtime, if up-to-date price data were important to them.

**Comment by chrisnegus** [comment]
I opened two PRs to describe this issue: one in the Karpenter Troubleshooting guide and the other in Karpenter Best Practices.
