### ISSUE TITLE
Make consolidation remove unwanted instance types

### ISSUE THREAD

**Issue by grosser** [aws/karpenter#2486]
**Tell us about your request**
we run most of our workloads on:
- m6i but fallback to m5
- c7g but fallback to m6i/m5

when consolidation happens it should never remove one of the preferred nodes types if fallback types are still in use
(multiple provisioners does not work since we already use that for az balance)
so some optional `preferredInstanceTypes` flag

**Are you currently working around this issue?**
no

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
I'm not sure about the feature request here.  Are you trying to implement preferred instance types now and don't have a mechanism?  

What does using multiple provisioners for AZ spread provide that a topology spread doesn't?

**Comment by grosser** [comment]
We want to prefer certain times during scale-down, so we don't end up scaling down the "good" types when they happen to get empty.
We use per-az provisioners so we can replace them az-by-az when doing a cluster-rollout.

**Comment by billrayburn** [comment]
Closing, will track in https://github.com/aws/karpenter/issues/3714
