### ISSUE TITLE
Limit amount of nodes

### ISSUE THREAD

**Issue by Izvi-digibank** [aws/karpenter#2490]
Version: v10.0.1

I would like to limit the amount of Nodes that Karpenter can create from a specific provisioner.
Did not find any provisioner field for it. 
Does that feature exist?

Thanks

**Comment by Izvi-digibank** [comment]
@FernandoMiguel So when using for example:


```
      resources:
        cpu: 1000
        memory: 1000Gi
```

As many nodes as need will be provisioned, until the **sum** of all Nodes reaches to 1 core or 1000Gi?

**Comment by FernandoMiguel** [comment]
1000 cores @Izvi-digibank

**Comment by Izvi-digibank** [comment]
@FernandoMiguel Right, thanks!
