### ISSUE TITLE
A new implementation for OCI/OKE (Oracle cloud)

### ISSUE THREAD

**Issue by Noksa** [aws/karpenter#2507]
### What karpenter features are relevant?

Hello guys.

I'm considering writing a new implementation for OCI/OKE (due the fact the we've moved to Oracle) and I found that the main.go contains specific AWS code: https://github.com/aws/karpenter/blob/main/cmd/controller/main.go#L27

So my question is - what is the best way to add a new implementation? I can't find any documentation about it.

### How should the docs be improved?

Please add a new section 'How to add a new implementation for `CLOUD_NAME`

**Comment by bwagner5** [comment]
We'd love to have more providers implemented for Karpenter! A new provider would live in its own Git repo, not within the `github.com/aws/karpenter` repo. An example implementation of another provider can be found here: https://github.com/bwagner5/karpenter-k3d

**Comment by Noksa** [comment]
@bwagner5 
Thanks, will take a look!

**Comment by Noksa** [comment]
@bwagner5 
I've found that some of flags are specific to `AWS`:

```
	// AWS Specific
	f.StringVar(&opts.ClusterName, "cluster-name", env.WithDefaultString("CLUSTER_NAME", ""), "The kubernetes cluster name for resource discovery")
	f.StringVar(&opts.ClusterEndpoint, "cluster-endpoint", env.WithDefaultString("CLUSTER_ENDPOINT", ""), "The external kubernetes cluster endpoint for new nodes to connect with")
```

But they are validated by default.

```
func (o Options) Validate() (err error) {
	err = multierr.Append(err, o.validateEndpoint())
	if o.ClusterName == "" {
		err = multierr.Append(err, fmt.Errorf("CLUSTER_NAME is required"))
	}
```

Is it expected?

**Comment by bwagner5** [comment]
We haven't quite untangled are flags yet, but we should definitely remove the dependency on those.

**Comment by ellistarn** [comment]
See: https://github.com/aws/karpenter/issues/936

**Comment by jonathan-innis** [comment]
Closing since we will now be tracking these requests in the mega issue #2532

**Comment by wy0824** [comment]
we have implemented the oracle provider: https://github.com/zoom/karpenter-oci
