### ISSUE TITLE
Honor requests for ephemeral storage size passed down from Kubernetes

### ISSUE THREAD

**Issue by pcolmer** [aws/karpenter#2512]
### Tell us about your request

I'd like ephemeral storage requests from Kubernetes to be honored in some way, rather than relying solely on [Block Device Mappings](https://karpenter.sh/v0.16.0/aws/provisioning/#block-device-mappings).

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I'm using Karpenter with AWS EKS to deliver a scaleable compute infrastructure for use with GitLab's CI feature. The infrastructure uses GitLab's Kubernetes executor to take CI jobs and turn them into pods. Due to corporate requirements, design decisions mean that we need each job (pod) to run on its own compute instance. I've configured Karpenter and the GitLab Runner so that node affinity and pod anti-affinity rules ensure this requirement is met.

Assuming that the GitLab Runner is appropriately configured, the Kubernetes executor allows variables to be set to request CPU, memory and ephemeral storage requirements. For CPU and memory, this is working really well - Karpenter selects the most appropriate EC2 instance for those requirements. However, the moment I pass an ephemeral storage requirement through, Karpenter fails to find a matching instance.

The storage requirements for CI jobs vary hugely. Building a static website, for example, will require the git repository plus any packages required to build the site plus the built output. That size will only really be known to the developer.

### Are you currently working around this issue?

We're currently working around the issue the only way we can - have multiple Provisioners, each with their own Block Device Mapping and pre-determined device size. That, in turn, requires multiple Runners and a CI job will need to use a tag that corresponds to the Runner that provides the nearest appropriate disc space.

That is not a good use of resources: multiple Runners is wasteful for the compute usage, the predefined block sizes will not meet everyone's needs and the developer will need to look up which Runner provides which capacity and tag their jobs appropriately.

### Additional Context

Related issues:
#2298 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
There's https://github.com/aws/karpenter/issues/2394 which is related, but you might workaround this for now by weighting your provisioners sorted with the smallest disk weighted highest.  That won't match pods which request more ephemeral storage and should remove the requirement for the tag selecting the best fit.  Karpenter would try each provisioner in order, smallest disk to largest and launch the first node that worked.

**Comment by jonathan-innis** [comment]
Closing as a duplicate/additional use-case for #2394. Tracking around the request will be captured in that mega-issue
