### ISSUE TITLE
[Helm chart] configmap-logging.yaml use the wrong "logEncoding" key

### ISSUE THREAD

**Issue by chrisduong** [aws/karpenter#2540]
### Version

Karpenter version: 0.16.2

Affected line: https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/configmap-logging.yaml#L26 

it should be like this:

```yaml
"encoding": "{{ .Values.controller.logEncoding }}",
```

### Expected Behavior

Set `.Values.controller.logEncoding` to `json` and it takes effective

### Actual Behavior

It will be ignored by the Helm chart

### Steps to Reproduce the Problem

Set `.Values.controller.logEncoding` to `json` and it will be ignored

### Resource Specs and Logs

not relevant 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dewjam** [comment]
Thanks for reporting this @chrisduong .  I'll try to reproduce and get back to you.

**Comment by dewjam** [comment]
Hey @chrisduong ,
The line you referenced is for the "Global" logEncoding value, which appears to work as expected (view below).  I'm wondering if we really need container specific logEncoding values.  I can't really think of a case where you would want the log format to be different between the Controller and Webhook containers.

```
helm upgrade --install --namespace karpenter --create-namespace \
  karpenter karpenter/karpenter \
  --version ${KARPENTER_VERSION} \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} \
  --set clusterName=${CLUSTER_NAME} \
  --set clusterEndpoint=${CLUSTER_ENDPOINT} \
  --set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
  --set aws.enablePodENI=true \
  --set logEncoding="json" \
  --wait

# Example logs
{"level":"DEBUG","time":"2022-09-29T20:25:44.733Z","message":"Successfully created the logger."}
{"level":"DEBUG","time":"2022-09-29T20:25:44.733Z","message":"Logging level set to: debug"}
{"level":"INFO","time":"2022-09-29T20:25:44.742Z","logger":"controller","message":"Initializing with version v0.16.3","commit":"5d4ae35-dirty"}
{"level":"INFO","time":"2022-09-29T20:25:44.742Z","logger":"controller","message":"Setting GC memory limit to 966367641, container limit = 1073741824","commit":"5d4ae35-dirty"}
{"level":"info","ts":1664483144.7420082,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
{"level":"DEBUG","time":"2022-09-29T20:25:44.776Z","logger":"controller.aws","message":"Using AWS region us-west-2","commit":"5d4ae35-dirty"}
{"level":"DEBUG","time":"2022-09-29T20:25:44.958Z","logger":"controller.aws","message":"Discovered caBundle, length 1066","commit":"5d4ae35-dirty"}
{"level":"INFO","time":"2022-09-29T20:25:44.958Z","logger":"controller","message":"loading config from karpenter/karpenter-global-settings","commit":"5d4ae35-dirty"}
{"level":"INFO","time":"2022-09-29T20:25:45.064Z","logger":"controller","message":"Starting server","commit":"5d4ae35-dirty","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
{"level":"INFO","time":"2022-09-29T20:25:45.064Z","logger":"controller","message":"Starting server","commit":"5d4ae35-dirty","kind":"health probe","addr":"[::]:8081"}
```

**Comment by chrisduong** [comment]
Hi @dewjam, Thanks for explaining the usage of the Global  `.Values.logEncoding`, I overlook this.

For me, I'm good to have to one global log encoding for both controller and webhook.

But if `.Values.controller.logEncoding` is useless, it's better to be removed from the chart.

**Comment by dewjam** [comment]
I agree, @chrisduong .  Let me look into removing those.

**Comment by bwagner5** [comment]
No more webhook, so only one option to control logEncoding now
