### ISSUE TITLE
Is it possible to use Karpenter to provision Dedicated Hosts?

### ISSUE THREAD

**Issue by hawkesn** [aws/karpenter#2556]
### What karpenter features are relevant?

AWS provisioning

### How should the docs be improved?

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dewjam** [comment]
Hey @hawkesn ,
Can you clarify your question?  Are you referring to a host which is dedicated to a single purpose/workload?  

Thanks,
Jim

**Comment by hawkesn** [comment]
Thanks Jim! Sorry yes let me clarify, I'm looking specifically at:
https://aws.amazon.com/ec2/dedicated-hosts/ - Dedicated Hosts.

In `AWS EC2` -> `Launch Templates` -> Either creating a new one or modifying an existing -> Under Advanced -> Tenancy -> You have options to select:
- Shared (default)
- Dedicated
- Dedicated Instance 

![image](https://user-images.githubusercontent.com/1168175/192600962-207a6f65-987d-48fa-8b3b-1a7f568884d7.png)

So my question more specifically is, is it possible for Karpenter to spin up something on Dedicated (Instance) or Dedicated Host?
Would it be possible using a custom LaunchTemplate? 

Thanks!

**Comment by MaciejKucia** [comment]
You can specify launchtemplate in `AWSNodeTemplate` and your custom template can have "Dedicated host" tenancy defined.
https://github.com/aws/karpenter/blob/main/charts/karpenter/crds/karpenter.k8s.aws_awsnodetemplates.yaml#L138:~:text=type%3A%20string-,launchTemplate%3A,-description%3A%20%27

> So my question more specifically is, is it possible for Karpenter to spin up something on Dedicated (Instance) or Dedicated Host?
> Would it be possible using a custom LaunchTemplate?

Yes, yes

**Comment by hawkesn** [comment]
Fantastic! Thanks so much @MaciejKucia - closing this
