### ISSUE TITLE
Reference secret for registry credentials.

### ISSUE THREAD

**Issue by empath-nirvana** [aws/karpenter#2558]
### Tell us about your request

We should be able to reference a k8s secret to populate the auth data in registry credentials in user data.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I don't want credentials in clear text in my awsnodetemplate... 

### Are you currently working around this issue?

Currently aren't putting credentials in the node template

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
If you don't want credentials in clear text in your AWSNodeTemplate, you can add the file in your AMI and reference it with custom UserData - [this](https://karpenter.sh/v0.16.3/faq/#can-i-add-ssh-keys-to-a-provisioner) is similar. Does this work for you?
