### ISSUE TITLE
Release 0.17 was not published to the helm chart

### ISSUE THREAD

**Issue by auyer** [aws/karpenter#2617]
### Description

```
helm search repo  karpenter
NAME               	CHART VERSION	APP VERSION	DESCRIPTION                                       
karpenter/karpenter	0.16.3       	0.16.3     	A Helm chart for Karpenter, an open-source node...
```

### Expected Behavior

Latest version of the helm chart should be 0.17.0

### Actual Behavior

It is insted 0.16.3

### Steps to Reproduce the Problem

Attempt to pull the helm chart with the Helm CLI, or to install with terraform as the docs recommend.

### Resource Specs and Logs

Na

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by SilentEntity** [comment]
Please read : https://karpenter.sh/v0.17.0/upgrade-guide/#upgrading-to-v0170
`helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version ${KARPENTER_VERSION} --namespace karpenter --create-namespace \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} \
  --set clusterName=${CLUSTER_NAME} \
  --set clusterEndpoint=${CLUSTER_ENDPOINT} \
  --set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
  --wait # for the defaulting webhook to install before creating a Provisioner
`

For ref: https://karpenter.sh/v0.17.0/getting-started/getting-started-with-eksctl/#install-karpenter-helm-chart

For terraform, please change the following repository url:

`resource "helm_release" "karpenter" {
  namespace        = "karpenter"
  create_namespace = true

  name       = "karpenter"
  repository = "oci://public.ecr.aws/karpenter/karpenter"
  chart      = "karpenter"
  version    = "v0.17.0"

  set {`

and also make sure to upgrade the helm version too, like below:

`helm = {
      source  = "hashicorp/helm"
      version = "~> 2.7"
    }`

**Comment by ellistarn** [comment]
The old helm chart is deprecated. See docs.
