### ISSUE TITLE
Helm OCI version change not mentioned in the Upgrade guide

### ISSUE THREAD

**Issue by snorlaX-sleeps** [aws/karpenter#2658]
### Is an existing page relevant?

https://karpenter.sh/v0.18.0/upgrade-guide/#upgrading-to-v0170

### What karpenter features are relevant?

The upgrade guide for v0.17.0 mentions the migration to the OCI repository and away from https://charts.karpenter.sh/

However, it does not mention the change to versioning - versions are now prefixed with a `v` e.g going from `0.16.2` to `v0.17.0`
This causes Helm installations (we are using Terraform) to fail as it cannot find the version in the repo:
```
failed to download "oci://public.ecr.aws/karpenter/karpenter" at version "0.18.0"
```

File in question: https://github.com/aws/karpenter/blob/main/website/content/en/v0.17.0/upgrade-guide/_index.md?plain=1#L104-L106

### How should the docs be improved?

This change should be documented as part of the upgrade guide alongside the URL change.

Related issue: https://github.com/aws/karpenter/issues/2633

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
I'll update the upgrade guide and troubleshooting doc to call this out. 

We had expected that most users were already using the `v0.17.0` versioning syntax since that's what we use in the [Getting Started Guide](https://karpenter.sh/v0.18.0/getting-started/getting-started-with-eksctl/#install-karpenter-helm-chart). The non-OCI helm chart worked with both the `v` prepended and without it. 

```
## This works
> helm template karpenter/karpenter --version v0.16.0
...

## This works
> helm template karpenter/karpenter --version 0.16.0
...

## This works
> helm template oci://public.ecr.aws/karpenter/karpenter --version v0.17.0
...

## This does not work
> helm template oci://public.ecr.aws/karpenter/karpenter --version 0.17.0
```

**Comment by bwagner5** [comment]
PR is out to add upgrade guide instructions and adds a troubleshooting entry.

**Comment by snorlaX-sleeps** [comment]
Thanks @bwagner5 ! (We've been using Karpenter since 0.9.x and hadn't been checking the guide 😉)
