### ISSUE TITLE
Getting Started with eksctl

### ISSUE THREAD

**Issue by lyuin** [aws/karpenter#2662]
https://karpenter.sh/v0.18.0/getting-started/getting-started-with-eksctl/

It didn't work in my environment.
`helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version ${KARPENTER_VERSION} --namespace karpenter --create-namespace \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} \
  --set clusterName=${CLUSTER_NAME} \
  --set clusterEndpoint=${CLUSTER_ENDPOINT} \
  --set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
  --wait # for the defaulting webhook to install before creating a Provisioner
`

I met error when I run above is below.

`Error: "helm upgrade" requires 2 arguments

Usage:  helm upgrade [RELEASE] [CHART] [flags]
`

But it worked so in helm command misunderstood comment out in this getting started.
Could you delete comment out?

`helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version ${KARPENTER_VERSION} --namespace karpenter --create-namespace \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} \
  --set clusterName=${CLUSTER_NAME} \
  --set clusterEndpoint=${CLUSTER_ENDPOINT} \
  --set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
  --wait
`

**Comment by tzneal** [comment]
Sorry, I'm not seeing the issue. I copied/pasted the command from the getting started guide and the installation of v0.18.0 worked for me.

**Comment by tzneal** [comment]
Could it be possible you ran this in a shell that didn't have those environment variables set? Maybe try resetting them and re-running the command?
