### ISSUE TITLE
make consolidation speed controllable

### ISSUE THREAD

**Issue by grosser** [aws/karpenter#2680]
### Tell us about your request

Make consolidation less scary by allowing to configure a cooldown period or interval for it.
For example "wait 5 minutes after each consolidation", so impact on the cluster can be limited.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I want to enable consolidation but not make it impact the cluster tenants too much.

### Are you currently working around this issue?

no

### Additional Context

similar to [schedule request](https://github.com/aws/karpenter/issues/2308)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
dupe: https://github.com/aws/karpenter/issues/2370#event-7607149241

**Comment by grosser** [comment]
yes, @ishworg comment says the same, but the issue is closed, so let's have a separate issue for it

**Comment by FernandoMiguel** [comment]
@grosser my understanding is that the issue is now fixed.
can you help me understand you need?

**Comment by grosser** [comment]
"wait 5 minutes after each consolidation" is what I'm trying to do
the merged PR only adds a hardcoded 15s interval

**Comment by FernandoMiguel** [comment]
it also adds support to bring back `ttlSecondsAfterEmpty` which would control that, no?

**Comment by tzneal** [comment]
Yes, the PR that was merged uses a fixed time instead of re-using `ttlSecondsAfterEmpty` to avoid some confusion over the parameter.  This is about something different I think, only checking for consolidation every 5 minutes at most.

**Comment by grosser** [comment]
prefer not to reuse ttlSecondsAfterEmpty since these are 2 different concerns.

**Comment by FernandoMiguel** [comment]
@grosser how so?

**Comment by ellistarn** [comment]
Closing in favor of #3059
