### ISSUE TITLE
karpenter pod and node metrics

### ISSUE THREAD

**Issue by jicowan** [aws/karpenter#2684]
### Version

__Karpenter Version:__ 0.6.3

__Kubernetes Version:__ v1.20.15

The karpenter pod and node metrics json file is not located at https://karpenter.sh/preview/getting-started/ or https://karpenter.sh/preview/getting-started/getting-started-with-eksctl/

### Expected Behavior

I expect to find these files at the path in the documentation

### Actual Behavior

timeout

### Steps to Reproduce the Problem

Try curl'ing https://karpenter.sh/preview/getting-started/karpenter-pod-metrics.json or karpenter-node-metrics.json

### Resource Specs and Logs

```
set -euf
mkdir -p /var/lib/grafana/dashboards/default
curl -skf --connect-timeout 60 --max-time 60 -H 'Accept: application/json' -H 'Content-Type: application/json;charset=UTF-8' https://karpenter.sh/preview/getting-started/karpenter-pod-metrics.json
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
These are in the capacity dashboard now. Where are you seeing the pod and node metrics files referenced? I only see them in old versions of the docs.

https://karpenter.sh/preview/getting-started/getting-started-with-eksctl/karpenter-capacity-dashboard.json

**Comment by jicowan** [comment]
I was referencing them in a grafana pod. They were being pulled and loaded dynamically. I saw the pod was failing because the request was timing out. What has replaced them?

**Comment by bwagner5** [comment]
The [capacity-dashboard](https://karpenter.sh/preview/getting-started/getting-started-with-eksctl/karpenter-capacity-dashboard.json) replaced the pod and node metrics. 

The dashboards for the getting started guide should be pulled from here: https://github.com/aws/karpenter/blob/main/website/content/en/preview/getting-started/getting-started-with-eksctl/grafana-values.yaml#L22
