### ISSUE TITLE
Rolling restart of Nodes

### ISSUE THREAD

**Issue by transadm312** [aws/karpenter#2703]
### What karpenter features are relevant?

I have installed Karpenter in Fargate profile to manage nodes with cni plugin installed https://github.com/aws/amazon-vpc-cni-k8s 
Now i have upgraded the CNI, for CNI to reflect we need to do rolling restart of nodes as per below. so workloads won't get impacted
1. create new nodes with new CNI
2. drain old nodes / evict pods 
3. delete old nodes

Is there anyway we can achieve this ?

### How should the docs be improved?

how to do nodes rolling restart ?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
i guess the easier way is to do a new provisioner, and then cordon the old provisioner, meaning all deploys would move to nodes created by the new provisioner.
once the old ones are empty, depending on your provisioner ttl, they can be terminated

**Comment by ellistarn** [comment]
Would be pretty cool if you could do something like this on your provisioner
```
kind: Provisioner
spec:
  labels: 
    lastRollingUpdate: "10-20-2020"
```
and trigger our #1738 workflow to safely upgrade. Similar to https://github.com/kubernetes-client/python/issues/1378#issuecomment-779323573

**Comment by sftim** [comment]
Maybe the request is to mark a provisioner as one to prefer draining nodes from, and then something else (eg a `kubectl` plugin) can automate rotating the provisioner.
