### ISSUE TITLE
Handling multiple EKS managed node group

### ISSUE THREAD

**Issue by Sakib37** [aws/karpenter#2716]
### Is an existing page relevant?

https://karpenter.sh/v0.18.1/getting-started/getting-started-with-terraform/

### What karpenter features are relevant?

The doc explains how to setup Karpenter when there is only one `eks_managed_node_groups`. However, in practice it will be always multiple node group that is managed by EKS in a cluster. It is not clear how to handle multiple EKS managed node group using Karpenter. 

### How should the docs be improved?

The doc should explain how to configure Karpenter when multiple EKS managed node groups exist in the cluster. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
That document just describes using the node group to only run Karpenter (Karpenter can't run on a node that it provisioned itself).  Other than a place to run, there's no interaction between Karpenter and managed node groups.

**Comment by Sakib37** [comment]
@tzneal  Thank you for the clarification. I am closing the ticket then
