### ISSUE TITLE
Parameter in provisioner to specify number of instance types to pass into CreateFleet request, instead of limiting this to 20 instance types

### ISSUE THREAD

**Issue by ashwinikumar-sa** [aws/karpenter#2721]
### Tell us about your request

We can have a configurable parameter in Provisioner to specify number of instance types to pass into CreateFleet request instead of limiting this to 20 (for example, "`instance-type-pools`"). this will increase diversification for accessing larger pools of Spot capacity. Default value for this parameter can be number of all instance types eligible from provisioner requirements as per current Karpenter logic and users can limit that to 20, 40, 60 types.... but a number below 20 may not be allowed (throwing a warning or error). 

Currently, Karpenter passes only up to 20 instance types in the CreateFleet request (it first finds most efficient instance type/size (based upon batch of packable pods) and then adds 19 more instance types of that type/size or above sizes). Even if we are instance type flexible with many instance families/ types in Provisioner requirements as a Spot best practice for instance diversification, Karpenter will only pass 20 or less instance types to CreateFleet request. Lesser pools in CreateFleet requests are causing capacity-optimized-prioritized allocation strategy to pick up deepest capacity only from these 20 or less pools. This is making wider Instance diversification in Provisioner ineffective.  

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

When Karpenter is deployed on EKS along with [AWS Node Termination handler](https://github.com/aws/aws-node-termination-handler#instance-metadata-service-processor) (IMDS processor), which is configured with enableRebalanceDraining="true" to cordon and drain Spot instances on receiving Instance Rebalance Recommendation (indicating higher risk of interruption), Karpenter is sometimes marking newly launched Spot node unschedulable immediately, draining pods and then launching another node with same instance type and then same behavior is repeated again and again creating a continuous cordoning and draining of newly launched instance and pods always remain pending (This behaviour is possible when Spot capacity is depleting for the instance type launched by Karpenter)

The reason of the issue seems to be that Karpenter passes only up to 20 instance types in the CreateFleet request (it first finds most efficient instance type/size (based upon batch of packable pods) and then adds 19 more instance types of that type/size or above sizes). Even if we become instance type flexible with many instance families/ types in Provisioner as Spot best practice for instance diversification, Karpenter will only pass 20 or less instance types to CreateFleet request. Lesser pools in CreateFleet requests are causing capacity-optimized-prioritized allocation strategy to pick up most available instance type only from these pools. This is making diversification in provisioner becomes ineffective.  

### Are you currently working around this issue?

As this limit of 20 instance types is hard-coded in Karpenter code, it's not possible to change this value from Provisioner. 

### Additional Context

Saw some Karpenter adopters reducing usage of Spot and increasing proportion of On-demand capacity due to this issue. This is hindering their cost optimization efforts with Spot instances.

### Attachments

![image](https://user-images.githubusercontent.com/75417152/197340108-1bec56bc-88e9-44db-9f0a-16300497511d.png)

**Example Provisioner requirements, when the above issue occurred:**
```
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values:
    - t3
    - t3a
    - t2
    - m6a
    - m5
    - m5a
    - m4
    - c6a
    - c5
    - c5a
  - key: karpenter.k8s.aws/instance-size
    operator: NotIn
    values:
    - metal
    - medium
    - small
    - 32xlarge
    - 24xlarge
    - 48xlarge
    - 56xlarge
    - 112xlarge
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot

```

**AWS Node termination handler config used to handle CORDON and DRAIN on Instance Rebalance signal**
`kubectl get ds -n kube-system aws-node-termination-handler -o yaml`

```
        - name: ENABLE_SPOT_INTERRUPTION_DRAINING
          value: "true"
        - name: ENABLE_SCHEDULED_EVENT_DRAINING
          value: "false"
        - name: ENABLE_REBALANCE_MONITORING
          value: "true"
        - name: ENABLE_REBALANCE_DRAINING
          value: "true"
        - name: CHECK_ASG_TAG_BEFORE_DRAINING
          value: "false"
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
I'm all for increasing number from 20 to probably 100.  I don't know if it will make a big difference with the case you are facing though. Since Karpenter sorts the instance types, it's more likely to put smaller instance types in the first batch of 20 (which is usually 60 instance pools when requesting across 3 AZs). Generally, smaller instance types are more plentiful, although in some cases that may not always hold true.  

We can certainly try increasing this number and see if it helps.  We'll likely just increment the hard-coded number rather than making it configurable since there's not much of a reason for configuring it. The only reason there is a limit is due to the max EC2 request size.

**Comment by ashwinikumar-sa** [comment]
> I'm all for increasing number from 20 to probably 100. I don't know if it will make a big difference with the case you are facing though. Since Karpenter sorts the instance types, it's more likely to put smaller instance types in the first batch of 20 (which is usually 60 instance pools when requesting across 3 AZs). Generally, smaller instance types are more plentiful, although in some cases that may not always hold true.
> 
> We can certainly try increasing this number and see if it helps. We'll likely just increment the hard-coded number rather than making it configurable since there's not much of a reason for configuring it. The only reason there is a limit is due to the max EC2 request size.

Thanks Brandon. Yes, this makes sense to increase number to widen the instance types list in CreateFleet requests and that may increase chances of picking up pools with deeper Spot capacity. We can begin with a hard-coded larger number and observe change in Spot interruption rates

**Comment by ashwinikumar-sa** [comment]
Hi Brandon, any recent updates or roadmap for this?

**Comment by bwagner5** [comment]
Still need to test the number increase.  Will try to get a PR in this week.

**Comment by jonathan-innis** [comment]
@bwagner5 I believe this can be closed now?
