### ISSUE TITLE
Reconsider publishing to only the OCI repository

### ISSUE THREAD

**Issue by hawkesn** [aws/karpenter#2726]
### Tell us about your request

Looking for continued chart publishing to the https://charts.karpenter.sh/ repository

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Currently running into an issue using the `helm chart inflator` via `Kustomize`. 
There seems to be an ongoing debate on the future of Kustomize's support for the Helm Chart Plugin inflator.

Specifically, there will be [no support for the OCI repositories](https://github.com/kubernetes-sigs/kustomize/issues/4401#issuecomment-1213360696). And there seems to also be little support for the new KRM function which is the recommended alternative.

### Are you currently working around this issue?

Currently investigating alternatives to the helm chart inflator.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
Can you please clarify what `helm chart inflator` is?

Are you referring to a third party library? If so can you link it?

**Comment by FalconerTC** [comment]
+1. Karpenter is the only tool I use that only publishes to OCI and I'm stuck on v0.16.2 until Kustomize relents or I use a different method for installing Karpenter than I do for the rest of my tooling.

**Comment by ellistarn** [comment]
Reminder: if this is a big issue for your team, please +1 the issue. We have limited resources to support different installation techniques, of which there are many. We want to make sure we're prioritizing the ones that work for most of our users without spreading the karpenter team too thin. We're wholly supportive of someone in the community taking on publishing the chart from the sources here: https://github.com/aws/karpenter/tree/main/charts

**Comment by piedro** [comment]
+1 Karpenter is the only tool that I want to migrate our Infra from AWS
 To OCI

**Comment by spring1843** [comment]
@hawkesn any updates on this? were you able to make it work with Kustomize?

**Comment by spring1843** [comment]
> +1 Karpenter is the only tool that I want to migrate our Infra from AWS
> To OCI

I'm not sure I understand this, do you mind rephrasing it? Karpenter's image is already in OCI so what do you mean by "migrate our infra from AWS to OCI" ?

**Comment by hawkesn** [comment]
> @hawkesn any updates on this? were you able to make it work with Kustomize?
@spring1843 
I was unable to make it work with Kustomize, I had to refactor the repo and use a somewhat hacky method to get ArgoCD to render the chart (needed to use the [lovely](https://github.com/crumbhole/argocd-lovely-plugin) plugin). Of the 20 applications we install on cluster, Karpenter is the only one that is installed this way since all others charts are available on non-OCI repos. Would still prefer to use the non-oci method.

I also found most of the other AWS EKS charts still have the option to install via a non-OCI repo (eg: https://github.com/aws/eks-charts) and there seems to be some automation around how they do that. 

I've been following the [thread](https://github.com/kubernetes-sigs/kustomize/issues/4401#issuecomment-1213360696) on Kustomize and their support for OCI repos and it doesn't seem likely there will be any changes there unfortunately.

Thanks for checking in @spring1843!

**Comment by ellistarn** [comment]
Can you explain your install methods a bit? I'm not understanding why you need to bake this into kustomize. 
1. Can you use `helm template` and then just use kubectl apply?
2. Have you looked into using fluxv2, which supports both helm and kustomize? 

There are *many* ways to install things on Kubernetes, and we don't have the resources to support all of them. We do, however, want to support things that are used broadly and that we understand well. This will enable us to test it, so we can ensure that users are never broken.

**Comment by olfway** [comment]
@hawkesn you can use helm wrapper like this
```
#!/bin/bash

set -eu

if [[ "${1:-}" == "pull" && "${2:-}" != "--help" ]]; then
  for arg do
    shift

    if [[ ${skip:-0} -gt 0 ]]; then
      skip=$((skip-1))
      continue
    fi

    if [[ "${arg}" == "--repo" ]]; then

      if [[ "${chartRepo%://*}" == "oci" ]]; then
        skip=2
        arg="$1/$2"
      fi
    fi

    set -- "${@}" "${arg}"
  done
fi

exec helm "${@:-}"
```
This is part of our internal wrapper, I removed non-relevant details
Basicaly it "fixes" helm command from
```
helm pull --untar --untardir /path/to/kustomize/dir/charts --repo oci://public.ecr.aws/karpenter karpenter --version v0.19.0'
```
to
```
helm pull --untar --untardir /path/to/kustomize/dir/charts oci://public.ecr.aws/karpenter/karpenter --version v0.19.0'
```

**Comment by hawkesn** [comment]
@ellistarn. Sure! Thanks for asking!

We use ArgoCD (GitOps tool) to deploy our charts. 
1. Using `helm template` + `kubectl apply` is a manual installation method that goes against a lot of best practices.
2. Fluxv2 is a similar gitops product of ArgoCD. ArgoCD supports both Kustomize and Helm. You could potentially run into this same situation with Flux as well. 

With ArgoCD, there are a few methods to install:
1. Point it to a directory in your repo with raw manifests
2. Point it to a helm chart directly (this DOES support OCI)
3. Use Kustomize and the HelmChartInflator 

We prefer option 3 because Kustomize allows us to "group" raw yamls AND a helm chart as a single Application (Application is a ArgoCD concept) - this keeps things on the dashboard neat and tidy. This is especially useful for Karpenter because we want to separate the Helm Chart from any Provisioner manifests.

Option 1 wouldn't work unless I pre-template a helm chart and commit it to the repo - that would be very messy.
Option 2 doesn't allow us to group the Helm chart and the raw manifests together, which means we would need to create two applications. From a developer UX perspective, that would be very confusing.

This isn't a "new" installation method. All I'm looking for is to publish the charts to the OCI repo AND https://charts.karpenter.sh/ - _how it was done previously_. That's all 👍 

Let me know if you have any more questions! 😄

**Comment by ellistarn** [comment]
Can you describe the pain around separating our Provisioners into their own Application as separate from the installation. In my mind, you want these to be separate, since you need to delete any provisioners before uninstalling Karpenter, otherwise you'll leak instances. 

They are logically separate. You could imagine many teams sharing a cluster that share a Karpenter installation, but each define their own Provisioner as a shard of isolated capacity for their workloads. 

We used to ship a `default` provisioner that was parametrizable, but we ran into installation ordering problems (and the uninstall cleanup problem). Are you wanting to set up multiple Provisioners in the Kustomize inflator?

Apologies if this is off base, but the kustomize chart inflator sounds like a hack to get the argo UI to behave, which is then resulting in new infrastructure for the Karpenter team to maintain. Not to say that we'd never support both of these methods, just trying to understand which system should be responsible for a fix.

**Comment by hawkesn** [comment]
> Can you describe the pain around separating our Provisioners into their own Application as separate from the installation. In my mind, you want these to be separate, since you need to delete any provisioners before uninstalling Karpenter, otherwise you'll leak instances.
They are logically separate. You could imagine many teams sharing a cluster that share a Karpenter installation, but each define their own Provisioner as a shard of isolated capacity for their workloads.

Why would I EVER want to uninstall Karpenter? 😆 - Joking aside, that's fair. For decentralized or embedded DevOps members that model makes sense. For other companies, like ours, we have a centralized DevOps team that provisions infrastructure for others. Having Karpenter as a single Application in ArgoCD helps build the correct mental model - being that every Application is an application in the real sense. For example, our ArgoCD application - it's a single Application - but we also combine it with raw manifests (eg. Traefik IngressRoutes (a CRD) for ingress, External Secret secrets (another CRD) for bootstrapping auth and deploy keys, etc). I wouldn't want these to be separate Applications but conceptually "belonging" to the same Application.

If anything were to break in Karpenter, I'll go check the Karpenter Application - visually it's all in one place.

 >We used to ship a default provisioner that was parametrizable, but we ran into installation ordering problems (and the uninstall cleanup problem). Are you wanting to set up multiple Provisioners in the Kustomize inflator?

We have a raw yaml manifest per Provisioner (currently 3 separate files). Kustomize effectively concats the rendered (inflated) helm chart + raw manifests into one mega yaml file that then gets applied by ArgoCD. We currently like this pattern and would prefer to keep that separated from the Karpenter helm chart - mostly so it's decoupled and easier for us to make upgrades if there are any breaking changes in the chart.

> Apologies if this is off base, but the kustomize chart inflator sounds like a hack to get the argo UI to behave, which is then resulting in new infrastructure for the Karpenter team to maintain. Not to say that we'd never support both of these methods, just trying to understand which system should be responsible for a fix.

You absolutely hit the nail on the head here. There seems to be a limitation on ArgoCD for us to bind resources together and have them appear as a part of the same Application (there might be a solution but I wasn't able to find one - maybe I'll go re-read the docs). From this standpoint, having to re-engineer a non-OCI pipeline to fix this doesn't make sense - agree with you on this. 

>I'm a big fan of OCI charts, since they have really nice availability/caching properties by reusing container registry infra.
This seems to be the growing trend and so we are actually re-thinking our gitops repo design to better incorporate these OCI charts.

I'm ok at this point if we want to close this issue having thought it over a bit more. Thanks very much for your time @ellistarn.

Although it seems there are a few other 👍 on the issue so maybe they have other thoughts or use-cases to share.

**Comment by ellistarn** [comment]
Fun to explore the darker corners of GitOps with you @hawkesn. I'm open minded here -- happy to keep the discussion open.

**Comment by spring1843** [comment]
Thanks for opening the ticket.

At this point we are not planning to publish the old Helm Chart website.  We've decided to move to OCI and we think it's a better choice. We may revisit this decision in the future but since the original problem for this ticket is resolved I'm gonna close the issue. Please feel free to reopen or open another issue if you need to.

**Comment by gchait** [comment]
Even if OCI is better, I think we are not yet at the stage of forcing users to use it.
Supporting it in enterprise automations and getting familiar with the new interactions (`helm search repo`?) take time.
And K8s is complex enough to maintain as it is, so I think it would be a viable approach only when most charts migrate to it and enough time has passed since its introduction to the mainstream.
