### ISSUE TITLE
Further Information on Debug Logs for Scaling Decisions

### ISSUE THREAD

**Issue by seanocca** [aws/karpenter#2733]
### Tell us about your request

The debug logs currently don't give anyone a whole lot of information regarding the scaling choices and events. This would be very helpful to determine better config changes for better and more accurate scaling from both the controller and the webhook

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I need to have a lot of Provisioners to scale our production environment correctly. I need to separate pods into multiple different Provisioners to better utilise instance types and separate workloads for better safety against overactive pods. The Provisioners are distributed against multiple instance types to improve performance and without further knowledge of the scaling choices of Karpenter. I see nodes of a larger instance type being chosen over smaller ones when scaling for 1 or 2 pods. When the smaller instance type could easily accommodate the new pods. Especially in production on large days of large spikes and staging when we are doing load testing.

### Are you currently working around this issue?

The only way in which I am working around it is using looking up docs and user's examples to better prevent this. But without more informative logs we can't really work around it as the operator is fairly new and people are yet to find any groundbreaking configurations that change the performance of the operator and it's scaling.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
> I see nodes of a larger instance type being chosen over smaller ones when scaling for 1 or 2 pods. When the smaller instance type could easily accommodate the new pods. Especially in production on large days of large spikes and staging when we are doing load testing


What version of Karpenter are you using? Some of this information is available in the logs, but it'll be more helpful if you can copy a log message and mention how you would like it to change.
