### ISSUE TITLE
Set Instance Sizes

### ISSUE THREAD

**Issue by mindovermiles262** [aws/karpenter#2748]
### Tell us about your request

Using helm, I'd like to be able to specify which instances sizes Karpenter can use (`*.medium`, `*.4xlarge`, etc)

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Karpenter is spinning up t3.small instances in a production cluster, when we really want to use larger instances and "grow" into them. There is already functionality to use instance classes `cX`, `fX`, `gX`, etc

### Are you currently working around this issue?

Sort of - I am specifying which instance classes I want to use, hoping that they don't schedule on `.small` instances sizes

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
You can use all these labels to constrain which instance types to schedule on. Sounds like you are looking for this one: `karpenter.k8s.aws/instance-size` but there is also some other interesting ones like `karpenter.k8s.aws/instance-cpu`.

Check them out here: https://karpenter.sh/v0.18.1/tasks/scheduling/#selecting-nodes
