### ISSUE TITLE
Contributing- version v0.18.1 and V 0.17.0

### ISSUE THREAD

**Issue by kwiemily** [aws/karpenter#2775]
missing this step
"Make sure the Karpenter repo is added to Helm by running the following commands."
helm repo add karpenter https://charts.karpenter.sh/
helm repo update
  . 
Above step and command missing

**Comment by SilentEntity** [comment]
For Ref:
https://karpenter.sh/v0.18.1/upgrade-guide/#upgrading-to-v0170

Please upgrade your helm version and start using OCI repo for karpenter.

Users who have scripted the installation or upgrading of Karpenter need to adjust their scripts with the following changes:

There is no longer a need to add the Karpenter helm repo to helm
The full URL of the Helm chart needs to be present when using the helm commands

```
helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version ${KARPENTER_VERSION} --namespace karpenter --create-namespace \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} \
  --set clusterName=${CLUSTER_NAME} \
  --set clusterEndpoint=${CLUSTER_ENDPOINT} \
  --set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
  --wait
```
