### ISSUE TITLE
Node internal IP and DNS are set to IPv4 

### ISSUE THREAD

**Issue by StellaV** [aws/karpenter#2776]
### Version

__Karpenter Version:__ v0.18.1

### Expected Behavior

Both Karpenter node internal IP and DNS in the pod's /etc/resolv.conf to be automatically IPv6. Tested on an EKS cluster, created with the terraform-aws-eks module and ipv6 enabled.

### Actual Behavior

/etc/resolv.conf on the pods shows 172.20.0.10, instead of v6. kubectl get node -o wide shows that the internal IP is v4.

### Steps to Reproduce the Problem

helm install karpenter to an existing, ipv6-enabled EKS cluster.

### Resource Specs and Logs

kubectl get no -o wide
NAME                                          STATUS   ROLES    AGE    VERSION               INTERNAL-IP                             EXTERNAL-IP   OS-IMAGE         KERNEL-VERSION                 CONTAINER-RUNTIME
ip-1-2-3-4.eu-west-1.compute.internal   Ready    <none>   135m   v1.23.9-eks-ba74326   1.2.3.4

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
v0.19.0 will likely be released next week. You can test with the current snapshot if you'd like! 

public.ecr.aws/karpenter/karpenter:v0-4f7d74f49954b9f2d8f15bd46a499d9ac6cefb35

installation instructions are in the usage tab here: https://gallery.ecr.aws/karpenter/karpenter

Release notes for the snapshot of v0.19.0 are here: https://karpenter.sh/preview/upgrade-guide/#upgrading-to-v0190

**Comment by StellaV** [comment]
@bwagner5 Thanks! I'll give it a try!

**Comment by bwagner5** [comment]
Feel free to re-open if you find any issues :D
