### ISSUE TITLE
Add EC2 Instance ID as Label

### ISSUE THREAD

**Issue by celestialorb** [aws/karpenter#2780]
### Tell us about your request

I'd like to be able to easily extract the EC2 instance ID of the node from the node itself, or from a set of nodes selected via labels.

As such I think adding another label to the node with the EC2 instance ID would be a helpful addition to Karpenter.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I'd like to be able to easily correlate a node in a cluster provisioned by Karpenter to an AWS EC2 instance primarily for debugging and potential automation purposes.

### Are you currently working around this issue?

The EC2 instance ID does exist in the node information, but only under `spec.providerID` and in the format `aws://${aws.region}/${aws.ec2.id}` which would require some parsing in order to extract just the AWS EC2 instance identifier.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by celestialorb** [comment]
Seems like it's a duplicate of this issue: https://github.com/aws/karpenter/issues/998

**Comment by ellistarn** [comment]
This will be fixed in the latest version of the aws cloud provider (v1.24? I think?).
