### ISSUE TITLE
fatal Unable to detect the IP of the kube-dns service

### ISSUE THREAD

**Issue by grosser** [aws/karpenter#2787]
### Version

using 5a75885484210c8a0ad0f1d47828c0899554df31

### Expected Behavior

ip configurable or optional like before

### Actual Behavior

... previous versions did not have this requirement
we use coredns so need a auto-discovery for that or a way to inject the IP via ENV

### Steps to Reproduce the Problem

boot without kubedns

### Resource Specs and Logs

```
"Unable to detect the IP of the kube-dns service, services \"kube-dns\" not found
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Is your cluster dns service called something different than `kube-dns` ?  

Most clusters are using coredns, but the service name is still `kube-dns` for compatibility reasons. 

https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#:~:text=Note%3A%20The%20CoreDNS%20Service%20is%20named%20kube%2Ddns%20in%20the%20metadata.name%20field.

**Comment by grosser** [comment]
we don't have a kubernetes dns service, we install coredns on the hosts
so we need to either hardcode the ip or have a flag to disable this feature

**Comment by grosser** [comment]
https://github.com/aws/karpenter/pull/2793 might fix it, trying that atm

**Comment by grosser** [comment]
confirmed working

**Comment by bwagner5** [comment]
A really hacky workaround is to setup a  kube-dns service that doesn't point to any pods so that you get a cluster IP that can be used to reference the cluster's IP Family.

1. Are you using EKS and the EKS Optimized AMI? 
1. Are you passing your hardcoded cluster IP to the `kubeletConfiguration` in your Provisioner specs?

**Comment by grosser** [comment]
1: no
2: no

we are not using kubeletConfiguration nor eks
this is a custom cluster that runs coredns on the nodes via systemd

**Comment by bwagner5** [comment]
I assume you're using the "custom" amiFamily then?  If so, we could just have the dns discovery not panic.

**Comment by grosser** [comment]
yes, and yes "just don't fail" is good enough afaik
