### ISSUE TITLE
Pods stuck in Pending due to POD_ENI configuration

### ISSUE THREAD

**Issue by JRemitz** [aws/karpenter#2803]
### Is an existing page relevant?

https://karpenter.sh/v0.18.1/tasks/configuration/#environment-variables--cli-flags

### What karpenter features are relevant?

Configuration of the controller.

### How should the docs be improved?

While `POD_ENI` is referenced here: https://karpenter.sh/v0.18.1/upgrade-guide/#upgrading-to-v0110 in the upgrade guide, we weren't upgrading from a previous version and overlooked this.  Instead, it might be helpful in the migration guide in the [deployment section](https://karpenter.sh/v0.18.1/getting-started/migrating-from-cas/#deploy-karpenter) as a reference to POD_ENI and security groups, and that pods will be stuck in `Pending` status with that reason about `Insufficient vpc.amazonaws.com/pod-eni` being the cause.

### Community Note

We recently upgraded from Cluster Autoscaler to Karpenter. The initial setup was very straight forward however we ran into two issues unrelated to Karpenter but highlighted by the migration.
1. Critical daemonsets for observability and CSI features were not getting priority during scheduling.  This was a straight forward fix to set the `priorityClassName` as long as it was supported to something that was relevant within your cluster. If not custom, `system-cluster-critical` was the appropriate value for us.
2. We recently added support within our clusters for [pod security groups](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html) which require enabling Pod ENI features. This wasn't needed in Cluster Autoscaler and therefore was a miss the the bulk of our overhead during the migration. Maybe we should have caught it sooner but in case it helps anyone else, the symptoms were seeing pods with security groups attached to them stuck in `Pending`.  This was frustrating because we expected Karpenter to autoscale but it wouldn't.  Looking at the pod status we would see something like `0/11 nodes are available: 1 Too many pods, 1 node(s) were unschedulable, 4 Insufficient cpu, 6 Insufficient [vpc.amazonaws.com/pod-eni](http://vpc.amazonaws.com/pod-eni), 8 Insufficient memory.` The link there should have been enough but our focus was on the `Pending` status and making sure that the permissions were correct with Karpenter and any other gaps in the setup.

The fix for number 2 was to include the environment variable in our controller configuration like so:
```yaml
controller:
  env:
    - name: "AWS_ENABLE_POD_ENI"
      value: "true"
```

**Comment by jonathan-innis** [comment]
Can you clarify where you feel like the miss in the documentation was? What could be added that would ease your experience here?

I will note that there is some troubleshooting docs around this stored here: https://karpenter.sh/v0.18.1/troubleshooting/#pods-using-security-groups-for-pods-stuck-in-containercreating-state-for-up-to-30-minutes-before-transitioning-to-running

**Comment by billrayburn** [comment]
Closing old issue, please reopen if still an issue.

**Comment by changhyuni** [comment]
@billrayburn 
we had a same issue.
Node created with karpenter does not have pod-eni capacity after taint(CriticalAddonsOnly:true) to the default node where karpenter controller is deployed
