### ISSUE TITLE
Helm install does not work for appVersion newer than 0.16.3

### ISSUE THREAD

**Issue by jebbens** [aws/karpenter#2808]
### Version

__Karpenter Version:__ v0.0.0

__Kubernetes Version:__ v1.0.0

### Expected Behavior

When running `helm upgrade --install` for version newer than v0.16.3, a new release should be created.

### Actual Behavior

Receive the following error:   
Error: failed to download "karpenter/karpenter" (hint: running `helm repo update` may help)

Issue is that the charts.karpenter.sh manifest does not include information for appVersion newer than 0.16.3

### Steps to Reproduce the Problem

helm repo add karpenter
helm repo update
helm upgrade --install karpenter karpenter/karpenter --namespace karpenter --create-namespace --version 0.18.1 --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn=arn:aws:iam::<account>:role/eks/test/karpenter-test" --set serviceAccount.name=karpenter --set clusterName=test --set clusterEndpoint=<cluster endpoint> --set aws.defaultInstanceProfile=<arn of node instance profile> --wait

### Resource Specs and Logs

Error: failed to download "karpenter/karpenter" (hint: running `helm repo update` may help)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
https://karpenter.sh/v0.18.1/upgrade-guide/#upgrading-to-v0170
