### ISSUE TITLE
Karpenter fails to reinstall after an uninstall

### ISSUE THREAD

**Issue by jebbens** [aws/karpenter#2815]
### Version

__Karpenter Version:__ v0.16.3

__Kubernetes Version:__ v1.22

### Expected Behavior

Install karpenter, uninstall karpenter, then reinstall karpenter.

### Actual Behavior

Karpenter deploys first time without any issues, but then fails to install after an uninstall. Issue is specific to the webhook container.

### Steps to Reproduce the Problem

Create cluster and deploy Karpenter v0.16.3 using Helm 3.8.2 with the following command: 
helm repo add karpenter "https://charts.karpenter.sh/"  
helm repo update  
helm upgrade --install karpenter karpenter/karpenter \  
--namespace karpenter \  
--create-namespace \  
--version "v0.16.3" \  
--set serviceAccount.annotations."eks\.amazonaws\.com/role-arn=arn:aws:iam::<account>:role/eks/test/karpenter-test" \  
--set serviceAccount.name=karpenter \  
--set clusterName="test" \  
--set clusterEndpoint="https://<cluster id>.gr7.us-east-1.eks.amazonaws.com" \  
--set aws.defaultInstanceProfile="eks-node-test"  

Uninstall the karpenter release: helm uninstall karpenter
Reinstall the karpenter release using same command as above

### Resource Specs and Logs

`WARN    webhook server key missing`  
`TLS handshake error from 10.0.34.70:43408: tls: no certificates configured`  
Note: The IP address corresponds to the primary Private IP of the node where pod is deployed.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by lucass4** [comment]
Looks like the problem that was described here
https://github.com/aws/karpenter/issues/2562

**Comment by jebbens** [comment]
Agree. I also have v0.18.1 running now, so less of a concern. Tks!
