### ISSUE TITLE
`Make test` can not run a single test

### ISSUE THREAD

**Issue by yizhang-zen** [aws/karpenter#2830]
### Tell us about your request

Run `make test` to be able to test a single test, like termination. For now, using `TEST_FILTER` env doesn't work.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Tried exporting `TEST_FILTER` with file name, test name and keywords. But none of them work.
`TEST_FILTER=github.com/aws/karpenter-core/pkg/controllers/termination make test`
`TEST_FILTER='Termination Reconciliation node that could not be drained [BeforeEach] should delete nodes that have timed out drain' make test`
`TEST_FILTER='timed\ out' make test`

### Are you currently working around this issue?

No

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
`FOCUS "Scheduling" make test` works for me!

**Comment by grosser** [comment]
```
FOCUS="Scheduling" make test
```
- is not obvious + is not documented
- produces lots of noise

can we make `go test github.com/aws/karpenter/pkg/controllers/interruption` work ? (so regular go devs can run tests without having to lookup specifics)

**Comment by ellistarn** [comment]
Lots of ways to skin this cat. I played with a couple approaches and landed on this one. As a developer, I just run `go test github.com/aws/karpenter/pkg/controllers/interruption` if I want to test that directly.

```
❯ go test github.com/aws/karpenter/pkg/controllers/interruption
ok  	github.com/aws/karpenter/pkg/controllers/interruption	11.203s
```

**Comment by grosser** [comment]
for me this always results in:
```
[BeforeSuite]! [PANICKED] [0.145 seconds]
[BeforeSuite]
/Users/mgrosser/Code/tools/karpenter/pkg/controllers/interruption/suite_test.go:90

  Test Panicked
  In [BeforeSuite] at: /Users/mgrosser/go/1.19.0/pkg/mod/github.com/samber/lo@v1.33.0/errors.go:53

  unable to start control plane itself: failed to start the controlplane. retried 5 times: timeout waiting for process etcd to start successfully (it may have failed to start, or stopped unexpectedly before becoming ready)

  Full Stack Trace
```

**Comment by grosser** [comment]
but somehow `make test` works, so I though this is some setup issue where only `make test` is supported

**Comment by ellistarn** [comment]
export KUBEBUILDER_ASSETS ?= ${HOME}/.kubebuilder/bin

**Comment by grosser** [comment]
this worked:
```
export KUBEBUILDER_ASSETS=${HOME}/.kubebuilder/bin
```

... can we make this either the default or fail when it's set incorrectly ?

**Comment by ellistarn** [comment]
This is unfortunately buried in the testenv library. I'd recommend just setting it up in your bashrc.

**Comment by grosser** [comment]
can the tests or some helper fail when it's not set to make this easy to discover ?
... alternatively is there maybe a good place for "development" docs ?

**Comment by ellistarn** [comment]
Check out https://karpenter.sh/v0.18.1/contributing/development-guide/
