### ISSUE TITLE
Deleting provisioner while draining a node orphans the node

### ISSUE THREAD

**Issue by yizhang-zen** [aws/karpenter#2831]
### Tell us about your request

We started deleting a node, then deleted its provisioner. This left the node in deletion status since nothing removed its finalizer.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Trying to prevent orphan node when replacing or removing provisioners.

### Are you currently working around this issue?

We manually remove the finalizer to get the orphaned node deleted

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dewjam** [comment]
Hey @yizhang-zen ,
Can you clarify?  Are you asking that Karpenter keep track of Ready nodes even if the ownerRef has been removed?  (after deleting a Provisioner)

**Comment by yizhang-zen** [comment]
Hi @dewjam , I updated the description. Does it make more sense now?

**Comment by ellistarn** [comment]
Makes complete sense.

**Comment by jonathan-innis** [comment]
@yizhang-zen, we have a design doc up now that should address this issue: #2944

**Comment by grosser** [comment]
that looks great 👍

**Comment by jonathan-innis** [comment]
@yizhang-zen @grosser  Have you been able to install version `v0.28.0-rc.1` to try and see if the orphaned node issue you were seeing is resolved?

**Comment by grosser** [comment]
no, we no longer run karpenter, will retry if we pick it back up
