### ISSUE TITLE
Karpenter for control plane nodes

### ISSUE THREAD

**Issue by tsutsarin** [aws/karpenter#2848]
### What karpenter features are relevant?

Can be karpenter used to provision control plane nodes, which are running k8s apiserver?
Feature is relevant when not using EKS for cluster management and using custom solution.

### How should the docs be improved?

Clarify if karpenter can be used to provision control plane nodes and how, which labels and taints to use, etc.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
This is a very cool idea. In theory, it should work, but you'd need somewhere to run Karpenter to bootstrap this.
