### ISSUE TITLE
Unable to install helm with oci URL via terraform

### ISSUE THREAD

**Issue by slobo** [aws/karpenter#2849]
### Is an existing page relevant?

https://karpenter.sh/v0.18.1/getting-started/getting-started-with-terraform/

### What karpenter features are relevant?

Trying to install via `terraform` fails with this message:

```
│ Error: could not download chart: failed to download "oci://public.ecr.aws/karpenter/karpenter" at version "v0.18.1"
```

### How should the docs be improved?

It is necessary to instruct `helm_release` provider to obtain token for authentication with oci repository
```tf
data "aws_ecrpublic_authorization_token" "token" {}
resource "helm_release" "karpenter" {

  repository_username = data.aws_ecrpublic_authorization_token.token.user_name
  repository_password = data.aws_ecrpublic_authorization_token.token.password
  lifecycle {
    ignore_changes = [ repository_password ]
  }

  namespace        = "karpenter"
  create_namespace = true

  name       = "karpenter"
  repository = "oci://public.ecr.aws/karpenter"
  chart      = "karpenter"
  version    = "v0.18.1"
...
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Yes, you will need an ecr public token to authenticate, or ensure you have no token for ecr public so that you are authenticated as `anonymous`. 

https://karpenter.sh/preview/troubleshooting/#helm-error-when-pulling-the-chart

**Comment by bwagner5** [comment]
@slobo, Would you like to submit a PR with these changes?

**Comment by slobo** [comment]
Hopefully I edited the right files - clicking "Edit this page" on https://karpenter.sh/v0.18.1/getting-started/getting-started-with-terraform/ took me to edit 0.18.1 docs which I believe are auto-generated / copied from `preview` on release?

**Comment by chandrakanthkannam** [comment]
Hi,
I'm facing the same issue
` Error: could not download chart: failed to download "oci://public.ecr.aws/karpenter/karpenter/karpener" at version "v0.20.0"` 

I have below terraform definition running
```
terraform {
  required_providers {
    kustomization = {
      source  = "kbst/kustomization"
      version = "0.7.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "2.5.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.10.0"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "1.14.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

data "aws_ecrpublic_authorization_token" "token" {}

resource "helm_release" "karpenter" {
  depends_on = [
    module.eks
  ]
  repository          = "oci://public.ecr.aws/karpenter/karpenter"
  chart               = "karpener"
  version             = "v0.20.0"
  repository_username = data.aws_ecrpublic_authorization_token.token.user_name
  repository_password = data.aws_ecrpublic_authorization_token.token.password
  name                = "karpenter"
  namespace           = kubernetes_namespace.karpenter.id
  values = []
}
```

can you please suggest what is that i'm missing here?
