### ISSUE TITLE
New Helm Chart v0.19.0

### ISSUE THREAD

**Issue by fascenvi** [aws/karpenter#2865]
### Tell us about your request

I would like to know if you will launch a new helm chart release to v0.19.0

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

When I try to use the latest helm chart (v0.16.3) I getting some erros about related to role permissions missing and now have new values file template

### Are you currently working around this issue?

Just fixing manualy, but I would like to have a new halm chart version

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Helm charts are now published in ECR starting w/ v0.17.0: https://gallery.ecr.aws/karpenter/karpenter

Here are the upgrade notes https://karpenter.sh/v0.19.0/upgrade-guide/#upgrading-to-v0170

We won't be publishing any more helm charts to the charts.karpenter.sh helm repo and instead using the ECR repo.

**Comment by bwagner5** [comment]
Let us know if you have anymore questions! Will close for now, but feel free to reopen!
