### ISSUE TITLE
Karpenter not optimising instance size for multiple pods

### ISSUE THREAD

**Issue by frankh** [aws/karpenter#2875]
Version
Karpenter Version: v0.16.3

Kubernetes Version: v1.22 (EKS)

I have a provisioner which allows the following instance types:

c6i.2xlarge (8 CPU, 16Gi Memory) - cost ~$0.71
c6i.8xlarge (32 CPU, 64Gi Memory) - cost ~$2.84 (4x)

And I provision hundreds of pods each requesting 4 CPU and 8Gi Memory.

Due to overheads, only a single pod will fit on a 2xlarge instances, but 7 pods will fit on an 8xlarge instance.

My expectation is that Karpenter realises this, and the cost per pod is $0.71 for 2xlarge or $0.41 for 8xlarge, so it should launch 8xlarge instances

Instead, it seems to examine each pod 1 at a time, and always picks the smallest available instance in which the pod fits.

See the attached logs showing it launching 1 node at a time for each pod

![image](https://user-images.githubusercontent.com/2088870/202446023-03b2fc40-3883-47d4-a90f-5d533d12cd49.png)

Is there any way to get Karpenter to optimise this? My understanding was that was how it should work from the FAQ https://karpenter.sh/v0.19.0/faq/#how-does-karpenter-dynamically-select-instance-types

**Comment by bwagner5** [comment]
Are you able to post the following info:
 - Provisioner Spec
 - Deployment Spec
 - More of the logs during the scale-up timespan


A few initial thoughts: 
 - It could be that the pods are being created slowly and trigger an early launch of the instance. We batch pods based on a dynamic batching window that is configurable in the karpenter-global-settings configmap ([docs](https://karpenter.sh/v0.19.0/tasks/globalsettings/#configmap)).
 - Are there any scheduling constraints on the deployments that would be limiting their ability to pack on one node, like anti-affinities? 
 - Have you looked at the actual allocatable capacity for those instance types? ([docs](https://karpenter.sh/v0.19.0/aws/instance-types/#c6i8xlarge))

**Comment by frankh** [comment]
I think from further looking into it the issue is to do with allocatable ephemeral storage

The instances request 10Gi of ephemeral storage and the launch template provisions the instances with 100Gi volumes. I confirmed that the nodes have ~100Gi of allocatable ephemeral storage after launch, however it seems Karpenter uses a set 18Gi value for every instance size and so only ever allocates 1 Pod per node

Is there a way to override what Karpenter thinks is allocatable for storage?

**Comment by bwagner5** [comment]
If you use the awsnodetemplate and set the block device mappings (like you are doing with launch templates), Karpenter will know what the storage allocatable is for the node.  https://karpenter.sh/v0.19.0/aws/provisioning/#block-device-mappings

**Comment by frankh** [comment]
That's definitely what I'm doing. I'm going to close this ticket until I have time to do some more investigation and figure out what's happening

**Comment by frankh** [comment]
I looked into it some more and the issue is that we're using a custom launch template which has BlockDeviceMappings, but Karpenter only looks at the mappings from the provisioner itself. And you can't set both launch template and block device mappings in the provisioner :/ so looks like we'll need to stop using our own launch template, or we need to patch Karpenter to fetch the mappings from the launch template if provided

**Comment by ellistarn** [comment]
>  we'll need to stop using our own launch template

Custom launch templates are a legacy feature that are very challenging to work with for a number of reasons. We highly recommend using AWSNodeTemplates instead. It's likely that launch templates will be deprecated at some point in the future.
