### ISSUE TITLE
Version 0.19.0 migrating-from-cas page contains wrong configuration

### ISSUE THREAD

**Issue by v-sag** [aws/karpenter#2877]
### Is an existing page relevant?

https://karpenter.sh/v0.19.0/getting-started/migrating-from-cas/

### What karpenter features are relevant?

"Deploy Karpenter" section in [migrating-from-cas](https://karpenter.sh/v0.19.0/getting-started/migrating-from-cas/) has wrong configuration.

### How should the docs be improved?

All the keys starting with "aws" should be inside "settings" key.

- --set aws.defaultInstanceProfile=KarpenterInstanceProfile
- --set aws.clusterEndpoint="${CLUSTER_ENDPOINT}"
- --set aws.clusterName=${CLUSTER_NAME}

should be
- --set settings.aws.defaultInstanceProfile=KarpenterInstanceProfile
- --set settings.aws.clusterEndpoint="${CLUSTER_ENDPOINT}"
- --set settings.aws.clusterName=${CLUSTER_NAME}
   

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Should be fixed now in the preview docs! Thanks for reporting!
