### ISSUE TITLE
Can't Deploy 1.19 with Argocd

### ISSUE THREAD

**Issue by mattslane** [aws/karpenter#2887]
### Version

__Karpenter Version:__ v1.19.0

__Kubernetes Version:__ v1.21.0

### Expected Behavior

Installing Karpenter via Argocd works. This was originally an upgrade attempt from 1.18 but we deleted everything karpenter related in an attempt to get it working. We saw almost identical behaviour during the upgrade

### Actual Behavior

Karpenter doesn't enter a  working state.  ArgoCd reports sync issues and eventuall fails with 

```Failed sync attempt to aeaf18f0736452d57bb75aa8e361a0bec7ec5cf1: one or more objects failed to apply, reason: Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": Post "https://karpenter.karpenter.svc:443/default/karpenter.k8s.aws?timeout=10s": context deadline exceeded```

### Steps to Reproduce the Problem

Create an ArgoCD application on a cluster running ArgoCD for karpenter 1.19.

example values file 

```
karpenter:
    settings:
      aws:
        clusterName: xxxxx
        clusterEndpoint: xxxxxx
        defaultInstanceProfile:  xxxxxx
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: xxxxxxxx
```

### Resource Specs and Logs

We're seeing a lot of logs of this nature 

```
{"level":"ERROR","time":"2022-11-18T15:07:52.154Z","logger":"webhook.DefaultingWebhook","message":"Reconcile error","commit":"ea5dc14","knative.dev/traceid":"e7c14041-2e0d-4a97-8aa9-d27ace483deb","knative.dev/key":"defaulting.webhook.karpenter.k8s.aws","duration":"25.228415ms","error":"failed to update webhook: Operation cannot be fulfilled on mutatingwebhookconfigurations.admissionregistration.k8s.io \"defaulting.webhook.karpenter.k8s.aws\": the object has been modified; please apply your changes to the latest version and try again"}
```

validation.webhook.karpenter.k8s.aws is showing as out of sync and the diff is showing a desired apiVersion of 
```
      - apiGroups:
          - karpenter.sh
        apiVersions:
          - v1alpha5
```
but this is what is deployed

```
      - apiGroups:
          - karpenter.k8s.aws
        apiVersions:
          - v1alpha1
```

The live manifest is reporting that it was deployed from `helm.sh/chart: karpenter-v0.19.0`

The same version mismatch is happening with `defaulting.webhook.karpenter.k8s.aws`

We've deleted the karpenter CRDS and webhooks multiple times, even resorted to wiping out the namespace and all karpenter related resources such as the CRDS. We've followed the steps to replace the CRDS from the upgrade guide. We've ompletely removed karpenter from our ArgoCD configuration and added it back. 
 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mattslane** [comment]
The second time I tried to upgrade from 1.18 it is in a working  but zombielike state. The webhooks are still constantly out of sync due to the versioning issue and we can't deploy, update or delete provisioners due to the following 

```Unable to delete resource: Internal error occurred: failed calling webhook "validation.webhook.provisioners.karpenter.sh": the server rejected our request for an unknown reason```

**Comment by gmontanola** [comment]
I think [this ](https://github.com/aws/karpenter/pull/2858)solves the issue.

**Comment by bwagner5** [comment]
this should be released in v0.19.1

**Comment by hahasheminejad** [comment]
I had this problem even in v0.19.1. Deleting the ArgoApp with all the resources and recreating them fixed this for me.

**Comment by elocke** [comment]
Same @hahasheminejad

**Comment by bwagner5** [comment]
@mattslane the second error message you reported:

```
Unable to delete resource: Internal error occurred: failed calling webhook "validation.webhook.provisioners.karpenter.sh": the server rejected our request for an unknown reason
```

is referencing the old webhook name. It was changed from `validation.webhook.provisioners.karpenter.sh` -> `validation.webhook.karpenter.k8s.aws` in https://github.com/aws/karpenter/commit/b358e0040153183d2df720e39b9530f50251889f#diff-5927aca3e6dc2d45a21fac224ad6f06051d5ea414e7d0a54f540f0a5fbfd537fL4

How is Karpenter being updated in argocd? Is it a helm upgrade or is it templating the helm chart and applying the raw yaml?

**Comment by skdltmxn** [comment]
I think this is related to #2891

**Comment by mattslane** [comment]
> @mattslane the second error message you reported:
> 
> ```
> Unable to delete resource: Internal error occurred: failed calling webhook "validation.webhook.provisioners.karpenter.sh": the server rejected our request for an unknown reason
> ```
> 
> is referencing the old webhook name. It was changed from `validation.webhook.provisioners.karpenter.sh` -> `validation.webhook.karpenter.k8s.aws` in [b358e00#diff-5927aca3e6dc2d45a21fac224ad6f06051d5ea414e7d0a54f540f0a5fbfd537fL4](https://github.com/aws/karpenter/commit/b358e0040153183d2df720e39b9530f50251889f#diff-5927aca3e6dc2d45a21fac224ad6f06051d5ea414e7d0a54f540f0a5fbfd537fL4)
> 
> How is Karpenter being updated in argocd? Is it a helm upgrade or is it templating the helm chart and applying the raw yaml?

I'm not 100% sure how ArgoCD deploys helm charts, it's not something I've had to look into. I think it is a helm upgrade. We're deploying from the 1.19 chart. ArgoCd is reporting that the deployed apiVersion is different from the manifest version. This usually happens when something is mutating the manifest and we normally fix this with argoCds ignoreDifferences feature. However this doesn't feel like the correct solution for something as important as apiVersion as it would cause issues with future upgrades.

**Comment by Ruubmeister** [comment]
I managed to fix it by adding the ignoreDifferences as described above, then syncing, and then deleting the following old resources:
- mutatingwebhookconfiguration `defaulting.webhook.provisioners.karpenter.sh`
- validatingwebhookconfiguration `validation.webhook.provisioners.karpenter.sh`

This is without downtime, for me. Also I am not sure if the ignoreDifferences is needed, just want to share what works for me.

**Comment by ellistarn** [comment]
Does anyone know why argo doesn't cleaning up the old resources?

**Comment by mattslane** [comment]
> I managed to fix it by adding the ignoreDifferences as described by @mattslane, then syncing, and then deleting the following old resources:
> 
>     * mutatingwebhookconfiguration `defaulting.webhook.provisioners.karpenter.sh`
> 
>     * validatingwebhookconfiguration `validation.webhook.provisioners.karpenter.sh`
> 
> 
> This is without downtime, for me. Also I am not sure if the ignoreDifferences is needed, just want to share what works for me. Seems indeed similar to #2891, as mentioned by @skdltmxn

I don't think they're needed with 19.2. If the provisioners or webhooks are constantly getting recreated then they will be. I've not removed them as they don't have a negative impact if they're not needed.

**Comment by Ruubmeister** [comment]
> 

For me an upgrade from v18 to v19.2 only created the new webhooks, but left the old webhooks there. Somehow they were not removed, so that is why I had to do it manually.
