### ISSUE TITLE
support capacity reservations

### ISSUE THREAD

**Issue by grosser** [aws/karpenter#2912]
### Tell us about your request

we use capacity reservations for our preferred instance types (m6i.16xlarge)
but with karpenter is spins up whatever fits the current pending pods
so the only option we have is to limit it to just this instance type
but what we want is the ASG behavior of ordered types, for example "16xl,12xl,8xl"
so once aws runs out of 16xl (and we run out of reservations) it would give us 12xl and so forth

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

we need to reserve capacity to ensure we get enough of the instance types our workload depends on

### Are you currently working around this issue?

using a single instance type

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
have you seen? 
https://karpenter.sh/preview/tasks/scheduling/#weighting-provisioners

**Comment by grosser** [comment]
hmmm so you are saying I could use a reserved instance provisioner to get the reserved types
I'd still want "ordered provisioning", let me update the issue to that since the capacity part would be solved with what you suggested.

**Comment by grosser** [comment]
actually better to close this to have a findable artifact and I'll open a new issue

**Comment by FernandoMiguel** [comment]
You can create weighted provisioners for each instance family you want with the "priority" to be per size.

**Comment by FernandoMiguel** [comment]
When one pool is exhausted, it would move to the next one until that capacity is exhausted

**Comment by grosser** [comment]
https://github.com/aws/karpenter/issues/2916

**Comment by grosser** [comment]
thx, added that to the request ... it's a ok workaround, just a kinda ugly duplication and it won't work with consolidation
