### ISSUE TITLE
Suggestions for setting a Pods resources (CPU/Memory) when using Karpenter

### ISSUE THREAD

**Issue by toddatapiture** [aws/karpenter#2915]
### Is an existing page relevant?

N/A

### What karpenter features are relevant?

I am curious if you guys have suggestions or a best practice you use when setting a Pods resources CPU/Memory request and limits. I think this especially comes into play with Karpenter because one of the amazing benefits is node right sizing so each Pod needs different amounts of resources. 

When it comes to the CPU we are less concerned with it as it's usually spiky but has quick spikes. Plus, there's not as much downfall to it. As a team, we have decided to not set a limit for CPU and only a request.  I think memory gets a bit tricky though. If there's not enough memory a Pod can get evicted. We have been trying to set requests and limits for memory but you don't always know what size node will come up. So, the limit could be outside the range of the node.

When setting memory should we always have the request and limit the same to ensure we never exceed what is available? We try to set low request with high limits to save on cost. Also, during our monitoring, it doesn't consume those resources the entire time it's spikey. This is why we set the limit high to "hopefully" capture those spikes. We are afraid stability wise doing it this way could cause issues down the road.

### How should the docs be improved?

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
from what I've read around here and slack, Karpenter team tends to align with Kubernetes best practices and set limits very close to requests (sorry, no ink on hand)

you can also use [VPA Recommender](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/README.md) and track down your usage and adjust your limits.

**Comment by ellistarn** [comment]
+1. Really depends on usecases. Take a look at QOS Classes: https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/

**Comment by andrewhibbert** [comment]
You could try [goldilocks](https://github.com/FairwindsOps/goldilocks) or (kubecost)[https://blog.kubecost.com/blog/kubecost-version-1-98-0-new-feature-highlights/]

**Comment by toddatapiture** [comment]
@FernandoMiguel @andrewhibbert We have used goldilocks (uses VPA recommender under the covers) in the past and it was ok. It still wasn't perfect and needed tweaking/tuning. It especially got challenging to use if we were also using HPA then the resource metrics seemed to have gotten screwed. Kubecost is something we want to explore but our team hasn't gotten around to trying.

@ellistarn I will take a look!

Thanks for all the recommendations...
