### ISSUE TITLE
Cant use consolidation on Provisioner

### ISSUE THREAD

**Issue by ducchusipher** [aws/karpenter#2928]
### Version

__Karpenter Version:__ v0.0.0

__Kubernetes Version:__ v1.0.0

### Expected Behavior

i cant add consolidation 

### Actual Behavior

apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: test-ga
spec:
  consolidation:
    enabled: true

### Steps to Reproduce the Problem

apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: test-ga
spec:
  consolidation:
    enabled: true

### Resource Specs and Logs

error: error validating "test.yaml": error validating data: ValidationError(Provisioner.spec): unknown field "consolidation" in sh.karpenter.v1alpha5.Provisioner.spec; if you choose to ignore these errors, turn validation off with --validate=false

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
what version of karpenter?
did you apply the CRDs?

**Comment by bwagner5** [comment]
Like @FernandoMiguel alluded to, I suspect you are running a version of Karpenter that doesn't support consolidation or are upgrading from a version that doesn't support it. Consolidation was supported in v0.16.0+. If you are upgrading from a version before that, you'll need to replace the CRD as described in the Upgrade Guide [here](https://karpenter.sh/v0.19.2/upgrade-guide/#custom-resource-definition-crd-upgrades).

**Comment by ducchusipher** [comment]
i used verion v0.16.3 (the latest version of helmchart), and try in v0.19.2 the result same with v0.16.3
![image](https://user-images.githubusercontent.com/107382598/203887890-d9593f39-19f0-43e5-b743-d5995233d946.png)

**Comment by ducchusipher** [comment]
Thank @bwagner5 after upgrade crds, it running
