### ISSUE TITLE
Helm template generation fails - Error: failed to download "oci://public.ecr.aws/karpenter/karpenter" at version "v0.19.2"

### ISSUE THREAD

**Issue by prabhatsharma** [aws/karpenter#2933]
### Is an existing page relevant?

https://karpenter.sh/v0.19.2/getting-started/migrating-from-cas/

### What karpenter features are relevant?

Following the documentation for template generation fails with message:

```shell
 helm template karpenter oci://public.ecr.aws/karpenter/karpenter --version ${KARPENTER_VERSION} --namespace karpenter \
    --set settings.aws.defaultInstanceProfile=KarpenterInstanceProfile \
    --set settings.aws.clusterEndpoint="${CLUSTER_ENDPOINT}" \
    --set settings.aws.clusterName=${CLUSTER_NAME} \
    --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::${AWS_ACCOUNT_ID}:role/KarpenterControllerRole-${CLUSTER_NAME}" \
    --version ${KARPENTER_VERSION} > karpenter.yaml

Error: failed to download "oci://public.ecr.aws/karpenter/karpenter" at version "v0.19.2"
```

### How should the docs be improved?

Needs right instructions

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
https://karpenter.sh/v0.19.2/troubleshooting/#helm-error-when-pulling-the-chart
`docker logout public.ecr.aws`
