### ISSUE TITLE
Proposal: toggle to let karpenter use Resource Limits to calculate node resources instead of Resources

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/karpenter#2937]
### Tell us about your request

Currently Karpenter uses Resources to calculate the size of a new node
While it is recommended for most scenarios it is recommended for Resource Limits to match Resource, it might not be what Partitioners desire

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

To have a toggle that have makes karpenter use Resource Limit instead of Resources.

### Are you currently working around this issue?

N/A

### Additional Context

Previous discussion:
https://github.com/aws/karpenter/issues/2915

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Unfortunately, we're bound by the kube scheduler in this case. We need to launch nodes that correspond to what will cause the kube scheduler to successfully schedule the pod. The kube scheduler uses requests, and not limits.

If you're interested in different behavior, consider moving this discussion upstream to SIG Scheduling.

**Comment by forkdevops** [comment]
Cant we use pod auto scalar in this case? New pods are launched when cpu , memory is high. If the existing node doesn't have enough capacity then karpenter will launch new node and schedule the pod.

Set the memory, cpu utilization 5 or 10 point less than the expected amount , i.e if you want new pods after 80 % , set 65-70% as utilization limit.
