### ISSUE TITLE
In version 1.11 of bottlerocket, Add harbor credential provider config that can enter userdata

### ISSUE THREAD

**Issue by FRABUCHI** [aws/karpenter#2939]
### Tell us about your request

I am putting the following part in the userdata when launching the bottlerocket 1.11 version image.
```
[settings.kubernetes.credential-providers.harbor-credential-provider]
enabled = true
cache-duration = "30m"
image-patterns = ["abc.abc.com"]
```

It is not supported by BottlerocketConfig in that part, so it is used through custom build.

Can you please add that part?

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

By specifying the harbor-credential-provider in the userdata, I can configure the node using the bottlerocket image to access the harbor.

If the harbor credential provider is not supported as it is now, I have to manually specify the id/pwd information of the harbor in the userdata.

### Are you currently working around this issue?

As mentioned above, I downloaded the source of karpenter, modified the BottlerocketConfig part, and custom built it for use.

```

// BottlerocketKubernetes is k8s specific configuration for bottlerocket api
type BottlerocketKubernetes struct {
	APIServer                 *string                             `toml:"api-server"`
	ClusterCertificate        *string                             `toml:"cluster-certificate"`
	ClusterName               *string                             `toml:"cluster-name"`
	ClusterDNSIP              *string                             `toml:"cluster-dns-ip,omitempty"`
	CredentialProviders       map[string]HarborCredentialProvider `toml:"credential-providers,omitempty"`
	NodeLabels                map[string]string                   `toml:"node-labels,omitempty"`
	NodeTaints                map[string][]string                 `toml:"node-taints,omitempty"`
	MaxPods                   *int                                `toml:"max-pods,omitempty"`
	StaticPods                map[string]BottlerocketStaticPod    `toml:"static-pods,omitempty"`
	EvictionHard              map[string]string                   `toml:"eviction-hard,omitempty"`
	KubeReserved              map[string]string                   `toml:"kube-reserved,omitempty"`
	SystemReserved            map[string]string                   `toml:"system-reserved,omitempty"`
	AllowedUnsafeSysctls      []string                            `toml:"allowed-unsafe-sysctls,omitempty"`
	ServerTLSBootstrap        *bool                               `toml:"server-tls-bootstrap,omitempty"`
	RegistryQPS               *int                                `toml:"registry-qps,omitempty"`
	RegistryBurst             *int                                `toml:"registry-burst,omitempty"`
	EventQPS                  *int                                `toml:"event-qps,omitempty"`
	EventBurst                *int                                `toml:"event-burst,omitempty"`
	KubeAPIQPS                *int                                `toml:"kube-api-qps,omitempty"`
	KubeAPIBurst              *int                                `toml:"kube-api-burst,omitempty"`
	ContainerLogMaxSize       *string                             `toml:"container-log-max-size,omitempty"`
	ContainerLogMaxFiles      *int                                `toml:"container-log-max-files,omitempty"`
	CPUManagerPolicy          *string                             `toml:"cpu-manager-policy,omitempty"`
	CPUManagerReconcilePeriod *string                             `toml:"cpu-manager-reconcile-period,omitempty"`
	TopologyManagerScope      *string                             `toml:"topology-manager-scope,omitempty"`
	TopologyManagerPolicy     *string                             `toml:"topology-manager-policy,omitempty"`
}

type HarborCredentialProvider struct {
	Enabled       *bool     `toml:"enabled,omitempty"`
	CacheDuration *string   `toml:"cache-duration,omitempty"`
	ImagePatterns *[]string `toml:"image-patterns,omitempty"`
}

```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by stmcginnis** [comment]
I work on Bottlerocket, and just curious about this. Is there a Harbor credential provider available publicly? If so, we could possibly look at adding that to Bottlerocket. PRs are also very welcome to Bottlerocket!

I don't know Karpenter well, but I would suggest one small change to the above. Rather than calling the new struct `HarborCredentialProviders`, it might be better to call it `ImageCredentialProvider` and have some name mapping. Then it would be flexible enough to configure whatever credential provider the user would be trying to use.

**Comment by ellistarn** [comment]
> I don't know Karpenter well, but I would suggest one small change to the above.

We just directly translate BR's toml -> json.

**Comment by billrayburn** [comment]
Closing, doesn't look like something for Karpenter to do.
