### ISSUE TITLE
Upgrade getting started to EKS 1.24

### ISSUE THREAD

**Issue by eduanb** [aws/karpenter#2940]
### Is an existing page relevant?

https://karpenter.sh/v0.19.2/getting-started/

### What karpenter features are relevant?

Installation

### How should the docs be improved?

New users should not be using older EKS versions so the examples should be updated.
For eksctl the example is 1.23, and the terraform example is 1.22.

For clusters with 1.23 or newer, you need the CSI plugin. It might be a good idea to add it to the samples or at least note it.
https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Hey @eduanb, we're working on revamping the getting started guide to be more expandable to different use-cases like this like the EBS installation and vending specific commands that become can become stale after one dependency or the other updates and changes. More about this here https://github.com/aws/karpenter/pull/3017/files. Feel free to re-open this once this PR gets in if you need to.
