### ISSUE TITLE
Launch template documentation is missing from docs

### ISSUE THREAD

**Issue by samson-plutoflume** [aws/karpenter#2941]
### Is an existing page relevant?

https://karpenter.sh/v0.19.2/aws/provisioning/#instanceprofile

### What karpenter features are relevant?

Custom launch templates for the provisioner

### How should the docs be improved?

In the Provisioning documentation for v0.19.* (and possibly others), it is implied that it's possible to have a custom launch template specified in the AWSNodeTemplate. 

It says:

> ```
> launchTemplate: MyLaunchTemplate            # optional, see Launch Template documentation
> ```

But this Launch Template documentation doesn't seem to exist - the path `v0.19.2/aws/launch-templates` does not exist. In v0.16.2, it says ["this feature is deprecated"](https://karpenter.sh/v0.16.2/aws/launch-templates/). 

However in the [upgrade guide](https://karpenter.sh/v0.19.2/upgrade-guide/#released-upgrade-notes), there isn't anywhere where it mentions that this feature is no longer supported, only that you *can* now support custom user data (v0.13.0) and custom AMIs (v0.14.0) without a custom launch template. 

Could the v0.19.0+ docs provide some clarity on this
* Are custom launch templates still supported?
  * If yes, where is the documentation?
  * If no, can that be stated somewhere?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
We intentionally removed the documentation to minimize the numbers that would take a dependency on it. We recommend using AWSNodeTemplate instead, as it's essential to avoid binpacking problems, race conditions, and leaked instances, all of which are problems with custom launch templates. We're planning on deprecating support in v1alpha6: see #1327 for more.

**Comment by samson-plutoflume** [comment]
Maybe it should be stated that this isn't recommended then, rather than including it in the main example and pointing people to the non-existent "Launch Template documentation"

**Comment by ellistarn** [comment]
https://github.com/aws/karpenter/pull/2947

**Comment by njtran** [comment]
Hey @samson-plutoflume, we're going to close this as the documentation for custom launch templates has been intentionally left out. If the current AWSNodeTemplateSpec doesn't capture all your use cases, feel free to cut a feature request so the feature request can be considered.
