### ISSUE TITLE
possible typo with awsnodetemplate in cluster role

### ISSUE THREAD

**Issue by ArieLevs** [aws/karpenter#2962]
### Version

__Karpenter Version:__ v0.19.2

__Kubernetes Version:__ v1.23.13

### Expected Behavior

karpenter helm chart should allow list resource "awsnodetemplate"

### Actual Behavior

when installing current helm chart, getting below error.
```
cannot list resource "awsnodetemplate"
```

after changing this line https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/clusterrole.yaml#L33
from: `resources: ["awsnodetemplates"]` to: `resources: ["awsnodetemplate"]`
error resolved

### Steps to Reproduce the Problem

install helm chart v0.19.2

### Resource Specs and Logs

```
k8s.io/client-go@v0.25.2/tools/cache/reflector.go:169: Failed to watch *v1alpha1.AWSNodeTemplate: failed to list *v1alpha1.AWSNodeTemplate: awsnodetemplate.karpenter.k8s.aws is forbidden: User "system:serviceaccount:karpenter:karpenter" cannot list resource "awsnodetemplate" in API group "karpenter.k8s.aws" at the cluster scope
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Did you modify the helm chart? It looks correct here: https://github.com/aws/karpenter/blob/v0.19.2/charts/karpenter/templates/clusterrole.yaml#L33

**Comment by ellistarn** [comment]
and here: https://github.com/aws/karpenter/blob/v0.19.2/charts/karpenter/templates/aggregate-clusterrole.yaml#L17

**Comment by ArieLevs** [comment]
the 0.19.2 version has the `awsnodetemplates` string (with an `s`) while to make karpenter work, removing above error I had to change it to `awsnodetemplate` (removing the `s` char),
just wanted to verify its a local issue with my setup, or its a real issue with the chart

**Comment by ArieLevs** [comment]
This really looks like an issue on my side
seems like I had an old CRD named `awsnodetemplate.karpenter.k8s.aws` (without the `s`) installed few months ago maybe some api changed, it failed with
```
"AWSNodeTemplateList" is already in use, ListKindConflict
```

I had to clean that up, after upgrade to the chart, and restart to the controllers, all looks to be OK
Thanks!
