### ISSUE TITLE
Old instanceprofile is still used

### ISSUE THREAD

**Issue by runningman84** [aws/karpenter#2973]
### Version

__Karpenter Version:__ v0.19.2

__Kubernetes Version:__ v1.23.x

### Expected Behavior

my configmap looks like this:
````
apiVersion: v1
data:
  aws.clusterEndpoint: https://XXXXXXXX.gr7.eu-central-1.eks.amazonaws.com
  aws.clusterName: prod-mgmt-new
  aws.defaultInstanceProfile: KarpenterInstanceProfile-prod-mgmt-new
  aws.enableENILimitedPodDensity: "true"
  aws.enablePodENI: "false"
  aws.interruptionQueueName: KarpenterInterruptions-prod-mgmt-new
  aws.isolatedVPC: "false"
  aws.nodeNameConvention: ip-name
  aws.vmMemoryOverheadPercent: "0.075"
  batchIdleDuration: 1s
  batchMaxDuration: 10s
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: karpenter
  creationTimestamp: "2022-12-02T14:15:03Z"
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.19.2
    helm.sh/chart: karpenter-v0.19.2
    helm.toolkit.fluxcd.io/name: karpenter
    helm.toolkit.fluxcd.io/namespace: karpenter
  name: karpenter-global-settings
  namespace: karpenter
  resourceVersion: "766878352"
  uid: f41c692a-3bf7-4982-a69c-c8fb48070207
````

But karpenter still uses the old instance profile:
arn:aws:iam::XXXX:instance-profile/KarpenterInstanceProfile

### Actual Behavior

Use the correct Instance profile as defined in helm/configmap.

The old instanceprofile is from an older test... but not referenced anymore in my configs.

### Steps to Reproduce the Problem

- Install v0.18.x
- Setup iam stuff
- Add Addtional iam role and profile
- Install v0.19.x
- Use New iam role and profile

### Resource Specs and Logs

│ 2022-12-02T14:51:11.859Z    DEBUG    controller.deprovisioning.cloudprovider    created launch template    {"commit": "470aa83", "provisioner": "x86", "launch-template-name": "Karpenter-prod-mgmt-new-6990000180439999 │
│ 044", "launch-template-id": "lt-0d8957041548b4a35"}                                                                                                                                                                      │
│ 2022-12-02T14:51:13.771Z    INFO    controller.deprovisioning.cloudprovider    launched new instance    {"commit": "470aa83", "provisioner": "x86", "launched-instance": "i-09fcccdf0c77e3ab7", "hostname": "ip-10-18-20 │
│ 2-220.eu-central-1.compute.internal", "type": "c5a.xlarge", "zone": "eu-central-1b", "capacity-type": "on-demand"}   

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Thanks for the report! This sounds like a real problem

**Comment by runningman84** [comment]
The funny thing is when I deleted the corresponding launch template it recreated it with the wrong values again. When I modified the launch template manually it did not notice it and started instances with the new profile.

**Comment by ellistarn** [comment]
Restarting karpenter should catch this -- but we should be hot reloading this.

**Comment by runningman84** [comment]
Restarting might fix that it does not notice that the launch template was changed externally...  but the problem with ignoring the new defaultInstanceProfile stays the same. In our usecase karpenter runs as eks fargate pods and was restarting multiple time... we are afraid to delete the old instance profiles.

**Comment by tzneal** [comment]
I'm not seeing this issue.  When I edit my CM I get this log:

```
karpenter-d445d7c7d-mf8lm controller 2022-12-06T15:36:10.790Z	DEBUG	controller	karpenter-global-settings config "karpenter-global-settings" config was added or updated: settings.Settings{ClusterName:"tnealt-karpenter-demo", ClusterEndpoint:"https://3F2D6FFB398CF227B804AD8F49E5A350.gr7.us-west-2.eks.amazonaws.com", DefaultInstanceProfile:"KarpenterNodeInstanceProfile-tnealt-karpenter-demo", EnablePodENI:false, EnableENILimitedPodDensity:true, IsolatedVPC:false, NodeNameConvention:"ip-name", VMMemoryOverheadPercent:0.075, InterruptionQueueName:"tnealt-karpenter-demo", Tags:map[string]string{}}	{"commit": "5d20fe2-dirty"}
```

And then new node launches use the updated instance profile. Do you see the log when you update the settings configmap?

**Comment by ellistarn** [comment]
Is there an instance profile in your node template?

**Comment by runningman84** [comment]
You are right it was also defined in the node template. Btw. can we just skip defining it there and the global defaults will be used?

**Comment by tzneal** [comment]
Yes, that works.  You only need to put it on the node template if you want to vary the instance profile across provisioners.  I'll go ahead and close this, but feel free to re-open.

**Comment by ls-omar-ajamieh** [comment]
we faced similar issue where karpenter didn't update the instance profile for the existing nodes when we replaced it and this led to many workers becoming in "NotReady" and bringing the cluster down and we had to recycle the nodes in order to make it work again
