### ISSUE TITLE
C, M, R default

### ISSUE THREAD

**Issue by nirroz93** [aws/karpenter#3000]
### What karpenter features are relevant?

Provisioner not mentioning type, family, category or generation defaults to C2+, M2+, R2+
https://github.com/aws/karpenter/blob/b6f87def5bb772362d7cec9fab7975b572d9a402/pkg/apis/v1alpha5/provisioner.go#L70

I don't see the explanation why is it needed (with the recent consolidation feature preferring cheaper type it will mostly take them anyway), and even so, why C, M and R and not all All Standard (A, C, D, H, I, M, R, T, Z) instances (that all share quotas called Running Spot/On-Demand Standard (A, C, D, H, I, M, R, T, Z) instances).

This issue opened for 2 reasons:
1. Add somewhere in the documentation that it defaults to C, M, R and why
2. Question why C, M, R defaults are needed  (not sure issue category is good for this)

### How should the docs be improved?

Maybe I was missing this, but I didn't find the docs mentioning this defaults, and why it is needed. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
We've added documentation for this now (https://karpenter.sh/preview/concepts/provisioning/#instance-types) so I'm closing this out.
