### ISSUE TITLE
Nodes stuck in Ready,SchedulingDisabled due to Failed to drain node, does not have any owner references

### ISSUE THREAD

**Issue by mvaal** [aws/karpenter#3002]
### Version

__Karpenter Version:__ v0.16.1
__Kubernetes Version:__ v1.22.15

### Expected Behavior

This is happening when upgrading versions of kubernetes (in this case 1.21 to 1.22)

Pods are getting stuck in the `Not Ready` state and causing nodes to never fully terminate.
```
k get nodes -A | grep 100.67.164.55
ip-100-67-164-55.ec2.internal    Ready,SchedulingDisabled   <none>   34d     v1.21.14-eks-ba74326
```

```
k describe node ip-100-67-164-55.ec2.internal
...
  Type     Reason          Age                       From       Message
  ----     ------          ----                      ----       -------
  Warning  FailedDraining  52m (x675 over 4d22h)     karpenter  Failed to drain node, pod xxxx/yyyyyyyyyyyyy does not have any owner references
  Warning  FailedDraining  28m (x180 over 4d22h)     karpenter  Failed to drain node, pod yyyy/zzzzzzzzzzzzz does not have any owner references
```

What we found was there the pods without owner references stuck in the `NotReady` state
```
k get pods -n xxxx yyyyyyyyyyyyy
NAME                                                       READY   STATUS     RESTARTS   AGE
yyyyyyyyyyyyy  1/2     NotReady   0          21d
```

### Actual Behavior

We should be able to terminate nodes without owner references if the pod is not in `Ready` state.

### Steps to Reproduce the Problem

Start a pod with no owner reference which has a health check that never becomes stable (so it remains in `Not Ready` state.

When looking through issues/PRs, we found this which is related:
https://github.com/aws/karpenter/pull/2255/files#diff-43e1a79f8872c4ceacb09ea283643de44dcbcb004e406e53b5d08fc95e592da5R128-R130

but has since been removed in 0.19.0 and I am unable to find where termination logic happens now.

### Resource Specs and Logs

n/a

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
In Karpenter  v0.16.1, we would not delete a node if a controller-less pod was running on the node.  This changed in v0.19.0 where we no longer prevent a node from being deleted due to a controller-less pod.  If you upgrade to the latest version, v0.19.3, you should see these nodes be removed.

**Comment by tzneal** [comment]
Closing for now, but feel free to re-open if you have any other questions.

**Comment by MickeyShiue** [comment]
kubectl get node <node-name> -o json | jq .metadata.finalizers

if output
[
  "karpenter.sh/termination"
]

kubectl patch node <node-name> -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl delete node <node-name>
