### ISSUE TITLE
subnetSelector selects subnet with no valid security groups

### ISSUE THREAD

**Issue by tjhiggins** [aws/karpenter#3007]
### Version

__Karpenter Version:__ v0.19.2

__Kubernetes Version:__ v1.22.0

### Expected Behavior

The karpenter provisioner should only select a subnet if there is a matching security group in that vpc. 

### Actual Behavior

Karpenter selects a subnet in another vpc and tries to use the security group from the same vpc as the cluster. 

### Steps to Reproduce the Problem

Follow terraform installation https://karpenter.sh/v0.19.3/getting-started/getting-started-with-terraform/
1. Create a new vpc/eks cluster and go through the whole flow (cluster_name=cluster-a)
2. Create another new vpc/eks cluster and go through the whole flow (cluster_name=cluster-b)

karpenter provisioner on `cluster-a` will match the private subnets for cluster-b's vpc. Which causes karpenter to throw the error in the section below and stay in a bad state.

The fix is easy and reverts back to older docs by matching the subnet with the cluster name included:
```
provider:
    subnetSelector:
      Name: "${module.eks.cluster_id}-private-*"  // In the docs it uses *private*
    securityGroupSelector:
      karpenter.sh/discovery/${module.eks.cluster_id}: ${module.eks.cluster_id}
    tags:
      karpenter.sh/discovery/${module.eks.cluster_id}: ${module.eks.cluster_id}
```

Proposals:
1. Update docs to make the subnet selector more targeted 
2. Make the subnetSelector more intelligent and disregard subnets that don't have a matching and valid security group

### Resource Specs and Logs

```
msg: Instance creation failed => InvalidParameter: Security group sg-XxXxXxXx and subnet subnet-YyYyYyYy belong to different networks.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
I'm not sure we want to do this level of validation in Karpenter. It's not clear what the right semantic is regarding subnet or securitygroup -- which should dictate which VPC is used? Is there something about our current tagging mechanism that you find challenging to use? 

From your yaml snippit, `"${module.eks.cluster_id}` implies that your tags are scoped to the cluster, which should correspond to  the same VPC. Is there another misconfiguration somewhere? Feel free to reopen if I'm misunderstanding something.
