### ISSUE TITLE
Upgrade chart repository https://charts.karpenter.sh

### ISSUE THREAD

**Issue by rnpaiva** [aws/karpenter#3008]
### Tell us about your request

Cheking the karpenter's chart repository (https://charts.karpenter.sh) the latest version upgraded was 0.16.3 .
Can you upgrade it with the others stable version please ? 

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I'm using karpenter repository to deploy the chart with terraform and the latest version that I can see there it's version 0.16.3 and I'd like to upgrade it , since the latest version is 0.19.X

### Are you currently working around this issue?

no , for now I'm using the version 0.16.3 

### Attachments

![Screenshot from 2022-12-08 13-00-43](https://user-images.githubusercontent.com/97540715/206497036-82629e62-e6d7-4aa0-8a3d-1b4840ecbd33.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rnpaiva** [comment]
Also , is it normal karpenter v0.16.3 not recycle the ec2 instances according with the ttlSecondsUntilExpired ? 
my provisioner : 
```
"apiVersion": "karpenter.sh/v1alpha5"
"kind": "Provisioner"
"metadata":
  "name": "default"
"spec":
  "labels":
    "purpose": "auto-scalling"
  "provider":
    "blockDeviceMappings":
    - "deviceName": "/dev/xvda"
      "ebs":
        "deleteOnTermination": true
        "volumeSize": "100Gi"
        "volumeType": "gp3"
    "securityGroupSelector":
      "aws:eks:cluster-name": "next-k8s-cluster-prod"
    "subnetSelector":
      "karpenter.sh/discovery": "next-k8s-cluster-prod"
  "requirements":
  - "key": "node.kubernetes.io/instance-type"
    "operator": "In"
    "values":
    - "m5a.2xlarge"
    - "m5a.4xlarge"
    - "m5a.8xlarge"
    - "m6a.large"
    - "m6a.xlarge"
    - "m6a.2xlarge"
    - "m6a.4xlarge"
    - "m6a.8xlarge"
  - "key": "topology.kubernetes.io/zone"
    "operator": "In"
    "values":
    - "us-east-1a"
    - "us-east-1b"
  - "key": "kubernetes.io/arch"
    "operator": "In"
    "values":
    - "amd64"
  - "key": "karpenter.sh/capacity-type"
    "operator": "In"
    "values":
    - "on-demand"
    - "spot"
  "ttlSecondsAfterEmpty": 400
  "ttlSecondsUntilExpired": 86400

```
And the nodes disabled for scheduling by karpenter isn't recycling every 86400 sec ( see attached ) 
![Screenshot from 2022-12-08 13-04-49](https://user-images.githubusercontent.com/97540715/206498198-886c04c9-64c2-47a2-b34b-be127e718930.png)

**Comment by tzneal** [comment]
For why it won't be recycled, pre v0.19.0 a controllerless pod would prevent draining.  PDBs can also prevent node termination.  Are there any controllerless pods or PDBs preventing pod evictions?
