### ISSUE TITLE
terraform getting started: DNS failure with ECR public auth token

### ISSUE THREAD

**Issue by draeath** [aws/karpenter#3015]
### Is an existing page relevant?

https://karpenter.sh/preview/getting-started/getting-started-with-terraform/

### What karpenter features are relevant?

Helm chart & the repository hosting Karpenter when not using `us-east-1`

### How should the docs be improved?

The following is included in the guide:

    data "aws_ecrpublic_authorization_token" "token" {}

This is later used in the helm chart module:

      name                = "karpenter"
      repository          = "oci://public.ecr.aws/karpenter"
      repository_username = data.aws_ecrpublic_authorization_token.token.user_name
      repository_password = data.aws_ecrpublic_authorization_token.token.password

When using AWS region us-east-2, this causes the following failure:

    data.aws_ecrpublic_authorization_token.token: Still reading... [10s elapsed]
    data.aws_ecrpublic_authorization_token.token: Still reading... [20s elapsed]
    ╷
    │ Error: error getting Public ECR authorization token: RequestError: send request failed
    │ caused by: Post "https://api.ecr-public.us-east-2.amazonaws.com/": dial tcp: lookup api.ecr-public.us-east-2.amazonaws.com on REDACTED:53: no such host
    │ 
    │   with data.aws_ecrpublic_authorization_token.token,
    │   on main.tf line 54, in data "aws_ecrpublic_authorization_token" "token":
    │   54: data "aws_ecrpublic_authorization_token" "token" {}

This DNS name is also invalid when using, say, `8.8.8.8` as a resolver, so this does not appear to be a local issue:

    $ dig @8.8.8.8 api.ecr-public.us-east-2.amazonaws.com

    ; <<>> DiG 9.11.36-RedHat-9.11.36-5.el8_7.2 <<>> @8.8.8.8 api.ecr-public.us-east-2.amazonaws.com
    ; (1 server found)
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 19307
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 512
    ;; QUESTION SECTION:
    ;api.ecr-public.us-east-2.amazonaws.com.	IN A

    ;; AUTHORITY SECTION:
    us-east-2.amazonaws.com. 5	IN	SOA	dns-external-master.amazon.com. root.amazon.com. 2374 180 60 2592000 5

    ;; Query time: 36 msec
    ;; SERVER: 8.8.8.8#53(8.8.8.8)
    ;; WHEN: Fri Dec 09 13:08:26 EST 2022
    ;; MSG SIZE  rcvd: 135

----

The example should be edited such that a token is not required, or this at least functions in regions other than `us-east-1`

I have not attempted simply omitting the credentials, this may work. In such case, there's no reason to provide them and an easy fix is to remove them (and the data source) from the example. If they *are* required, then this is a more significant issue.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by draeath** [comment]
https://github.com/aws/aws-cli/issues/5917#issuecomment-774317587 suggests that ECR public actions are only supported in `us-east-1` so this may actually be a problem with [the vpc module](https://github.com/hashicorp/terraform-provider-aws).

I'm happy to file a bug report there, if that's true?

**Comment by draeath** [comment]
I have filed the bug against the AWS provisder: https://github.com/hashicorp/terraform-provider-aws/issues/28281

**Comment by draeath** [comment]
Found a workaround. Add an additional `aws` provider block, specify region `us-east-1` and assign it an alias. Use this in the data block:

```hcl
terraform {
  required_version = "~> 1.3"
  required_providers {
    aws       = {
      source  = "hashicorp/aws"
      version = "~> 4.46"
    }
  }
}

provider "aws" {
  region = "us-east-2"
}

provider "aws" {
  region = "us-east-1"
  alias = "virginia"
}

data "aws_ecrpublic_authorization_token" "token" {
  provider = aws.virginia
}
```

I suggest adding this workaround to the documentation.

**Comment by spring1843** [comment]
Thank you @draeath please feel free to contribute to the docs. Closing the ticket please feel free to reopen.

**Comment by aliahmedmytoys** [comment]
is the bug resolved or not as i am also facing same problem in eu-central-1?

**Comment by robertocuccurese** [comment]
I have the same problem in eu-west-1
