### ISSUE TITLE
helm release seems to not work

### ISSUE THREAD

**Issue by SoulKyu** [aws/karpenter#3019]
### Version

__Karpenter Version:__ v0.0.0

__Kubernetes Version:__ v1.0.0

### Expected Behavior

Be able to add karpenter repository 

### Actual Behavior

```
helm repo add karpenter oci://public.ecr.aws/karpenter/karpenter
Error: looks like "oci://public.ecr.aws/karpenter/karpenter" is not a valid chart repository or cannot be reached: object required
```
can't use karpenter repository...

### Steps to Reproduce the Problem

helm repo add karpenter oci://public.ecr.aws/karpenter/karpenter

### Resource Specs and Logs

helm repo add karpenter oci://public.ecr.aws/karpenter/karpenter

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kirek007** [comment]
I'm having same issue, same error message.

**Comment by youngjeong46** [comment]
@kirek007 @SoulKyu as provided in the upgrade path [here](https://karpenter.sh/v0.20.0/upgrade-guide/#upgrading-to-v0170), adding repo is not a pre-requisite anymore.

Having said that, I went straight to `helm upgrade` and got this error:

```
Release "karpenter" does not exist. Installing it now.
Error: failed to download "oci://public.ecr.aws/karpenter/karpenter" at version "v0.20.0"
```

**Comment by kirek007** [comment]
Good point, but for terraform I had actually provide proper repository :) 
Finally it works like this:
```
resource "helm_release" "karpenter" {
  name       = "karpenter"
  repository = "oci://public.ecr.aws/karpenter"
  chart      = "karpenter"
  version    = "v0.20.0"
```

**Comment by spring1843** [comment]
With the OCI format there's no longer a concept of "adding a repository" per say.

**Comment by spring1843** [comment]
>Having said that, I went straight to helm upgrade and got this error:
>Release "karpenter" does not exist. Installing it now.
> Error: failed to download "oci://public.ecr.aws/karpenter/karpenter" at version "v0.20.0"

You should be able to fix that by running run `docker logout public.ecr.aws` as indicated [here](https://karpenter.sh/preview/troubleshooting/#helm-error-when-pulling-the-chart)
