### ISSUE TITLE
Add field indexer to include kind and API Version for AWSNodeTemplates

### ISSUE THREAD

**Issue by njtran** [aws/karpenter#3023]
### Tell us about your request

Add field indexer as described here: https://github.com/aws/karpenter/pull/2812/files/47690c9e57f918b94da87c1ec1b2c587ffd172a3#r1046402188

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Field Indexer used for watching provider ref only does it for the providerRef and name, but we may need to also index on Kind and API Version to be more robust in the future. It is technically sound now since the only Provider Ref is the AWSNodeTemplate.

### Are you currently working around this issue?

Not a problem right now

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Closing this since it's no longer relevant.
