### ISSUE TITLE
grafana not accepting ./metrics as prometheus source

### ISSUE THREAD

**Issue by mpechner-akasa** [aws/karpenter#3024]
### Version

__Karpenter Version:__ v0.20.0

__Kubernetes Version:__ v1.23.0

### Expected Behavior

Expect the when I create a new grafana data source using the URL:
http://karpenter.karpenter.svc.cluster.local:8080/metrics
It would not return a 404.

### Actual Behavior

Trying to create a datasrouce in grafna, ver 9.3. Using data source type prometheus using URL
http://karpenter.karpenter.svc.cluster.local:8080/metrics

When I lick "save & test" i et the error "Error reading Prometheus: client_error: 404"

I am forward the karpenter metric and in my local browser I see. Small smaple:

 HELP certwatcher_read_certificate_errors_total Total number of certificate read errors
# TYPE certwatcher_read_certificate_errors_total counter
certwatcher_read_certificate_errors_total 0
# HELP certwatcher_read_certificate_total Total number of certificate reads
# TYPE certwatcher_read_certificate_total counter
certwatcher_read_certificate_total 0
# HELP controller_runtime_active_workers Number of currently used workers per controller
# TYPE controller_runtime_active_workers gauge
controller_runtime_active_workers{controller="counter"} 0
controller_runtime_active_workers{controller="node"} 0
controller_runtime_active_workers{controller="node-state"} 0
controller_runtime_active_workers{controller="pod-state"} 0
controller_runtime_active_workers{controller="podmetrics"} 0
controller_runtime_active_workers{controller="provisioner-state"} 0
controller_runtime_active_workers{controller="provisionermetrics"} 0
controller_runtime_active_workers{controller="provisioning"} 0
controller_runtime_active_workers{controller="termination"} 0
# HELP controller_runtime_max_concurrent_reconciles Maximum number of concu

### Steps to Reproduce the Problem

In grafana create new data source.  Choose prometheus as type.
Give URL http://karpenter.karpenter.svc.cluster.local:8080/metrics
Leave everythng else default.
When I lick "save & test" i et the error "Error reading Prometheus: client_error: 404"

### Resource Specs and Logs

NA - URL works. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by thelman** [comment]
@mpechner-akasa i have the same problem, what was your solution?
