### ISSUE TITLE
Configure node tags from Provisioner resource

### ISSUE THREAD

**Issue by sergkondr** [aws/karpenter#3025]
### Tell us about your request

Hello Karpenter developers!

I think it will be nice to have the ability to configure node tags not only in AWSNodeTemplate but also in the Provisioner.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

We are trying to migrate to Karpenter from Cluster Autoscaler + AWS-managed Node groups. Our approach is to use shared nodes for most of our workloads and separate node groups for a couple of our specific applications. But all these node groups use the same subnets, user data, metadata options, etc. We'd like to save this approach and use one AWSNodeTemplate and separate Provisioners for each node group. And it will be very nice to configure tags independently for each group of nodes.

### Are you currently working around this issue?

Now we are using Karpenter in test mode for only one node group.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
https://karpenter.sh/v0.20.0/concepts/node-templates/#tags

**Comment by olfway** [comment]
I guess tags concept exist in any cloud provider

Currently with have to create multiple AWSNodeTemplates which is different only by tags

Another way is to make tags based on Provisioners properties, like
```
tags:
  Pool: "{{ Provisioner.name }}"
  Costs: "{{ Provisioner.labels.costs }}"
```

**Comment by ellistarn** [comment]
> I guess tags concept exist in any cloud provider

Not necessarily. Cluster API is a prime example. Given that this is currently possible under the existing API model, I'd recommend that you template out your AWSNodeTemplates, and configure them 1:1 with provisioners, if you want different tags on your nodes.
