### ISSUE TITLE
Have an ability to filter AWS AMIs with amiName

### ISSUE THREAD

**Issue by sergkondr** [aws/karpenter#3026]
### Tell us about your request

Hello Karpenter developers!

I think it will be nice to have the ability to filter AMIs not only with AMI ID or Tags but with AMI Name also.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

As far as I see, the current implementation assumes that we can find and filter AMIs by AMI ID or by Tags. But every AMI also has an AMI Name parameter that is independent of the region and more clear for most people. It will be great to implement this to Karpenter like it is implemented in terraform aws provider, for example: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami

### Are you currently working around this issue?

We are using unique AMI ID to filter AMI across all regions

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
Seems to duplicate https://github.com/aws/karpenter/issues/3022, closing in favor of it.
