### ISSUE TITLE
Support CRD Fleet kind

### ISSUE THREAD

**Issue by laivu266** [aws/karpenter#3032]
### Tell us about your request

Hi team,

We're developing a game which base on Unreal Engine 5, so we're using [Fleet](https://agones.dev/site/docs/reference/fleet/) for running Dedicated game servers (DGS). All of our DGS are running on EKS and we're using Karpenter for cluster autoscaling. However as I know that Karpenter doesn't support `Fleet` or [GameServer](https://agones.dev/site/docs/reference/gameserver/) if we want to use `Karpenter consolidation`.
So could you support that in the near future?

Thanks.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

`Karpenter consolidation` is not support CRD Fleet

### Are you currently working around this issue?

No

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
Can you elaborate on what the specific incompatible behavior is? Is it that you do not want GameServer pods to be interrupted? If so you wanna annotate them with do not evict. https://karpenter.sh/v0.16.3/tasks/deprovisioning/#pod-set-to-do-not-evict

**Comment by billrayburn** [comment]
Closing we think Karpenter should already be compatible, Karpenter will provision nodes in response to unscheduled pods.
