### ISSUE TITLE
Expire time should be partly random

### ISSUE THREAD

**Issue by runningman84** [aws/karpenter#3050]
### Tell us about your request

We use the "Ttl Seconds Until Expired" feature to ensure that all of our nodes used the latest AMI. So we have configured it as 10 hours... It would be great if the actual expire time would not be exactly 10 hours for all nodes... because this means all of our nodes restart at the same time... it would be cool if 10 hours would mean 5 hours + random(0-5) hours. This would ensure that not everything happens at the same time... (I am talking about hours but the setting should be configured in seconds)

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Right now all values are static... 

### Are you currently working around this issue?

We hope that our workloads do not bother ... but we now that this might be a problem for specific workloads... 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
I recall a past card about this. can't find it
here are some other options
https://github.com/aws/karpenter/issues/2949
https://github.com/aws/karpenter/blob/main/designs/deprovisioning.md

**Comment by runningman84** [comment]
I think the other options are not really sufficient here…

**Comment by njtran** [comment]
Hey @runningman84 we've recently made it so that Karpenter will expire nodes serially as opposed to in parallel [here](https://github.com/aws/karpenter-core/pull/59). This should be included in v0.20.0. What version of Karpenter are you using? Are you using v0.20.0 and not seeing this?

**Comment by FernandoMiguel** [comment]
@runningman84 that's where PDB can help, and readiness checks

**Comment by jonathan-innis** [comment]
I'm not convinced that randomness is the way to solve this problem. I think the crux of this issue is that you don't want node expiration at the same time due to the implication of disruption of your workloads. As @FernandoMiguel mentioned, I think PDB can help here.

Can you describe if there's a reason that PDBs don't meet your use-case for expiring the nodes.?

**Comment by runningman84** [comment]
Pdp and readiness checks are a valid solution I just find it scary that all parts move at the same time. Imagine there is an error with the latest ami. This would lead to a complete outage instead of a slowly expanding problem….

**Comment by FernandoMiguel** [comment]
> Pdp and readiness checks are a valid solution I just find it scary that all parts move at the same time. Imagine there is an error with the latest ami. This would lead to a complete outage instead of a slowly expanding problem….

It happened with bottlerocket AMI just a few weeks ago.

**Comment by njtran** [comment]
@runningman84 the rate at which Karpenter expires nodes should be at least a node a minute. Karpenter waits for any replacement nodes to become ready before terminating the expired nodes. In addition, with PDBs, you can even further rate-limit this. If a node doesn't come online, let's say due to some AMI error, we won't expire that node. 

Is this still too fast for you? Rate-limiting at the pod level with PDBs will definitely help slow this down.

**Comment by jonathan-innis** [comment]
>Pdp and readiness checks are a valid solution I just find it scary that all parts move at the same time. Imagine there is an error with the latest ami.

What kind of error are you thinking? If it's an error that doesn't allow your containers to come back into a ready state, then this should block on PDBs or as @njtran mentioned if the node never comes ready we just won't continue expiring nodes.

**Comment by njtran** [comment]
As it looks like this issue is resolved, I'm going to close this. Feel free to cut a feature request or check the [aggregate node control issue](https://github.com/aws/karpenter/issues/1738) and comment for any other controls you might want that aren't already mentioned.
