### ISSUE TITLE
Provision to specify the max Drain / Pod evictions attempts  in Provisioner 

### ISSUE THREAD

**Issue by ra-grover** [aws/karpenter#3052]
### Tell us about your request

We have hundreds on nodes in our clusters which are just hung on `Unschedulable` state because Karpenter is not able to drain them, might be a bad Application PDB or a Pod on that node stuck in `ImagePullBackoff` and Karpenter tries forever to evict it. 
I think a flag in `Consolidation` stanza of the provisioner spec would be good option to specify maxDrainAttempts/maxPodEvictions for Karpenter to not stuck indefinitely. 

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

The nodes are stuck in un-schedulable state which are impacting costs. 

### Are you currently working around this issue?

We have manually written a cron job to Delete the pods stuck in those state, preventing Karpenter to terminate gracefully.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Hey @ra-grover. Not saying no to this request, but I'm curious why it isn't easier for you folks to fix the underlying problem of broken PDBs. If karpenter deprovisions nodes, it's just going to move around the misconfigured pods. I worry that violating fundamental mechanisms of kubernetes (e.g. pdbs) may have unforeseen side effects.

**Comment by ra-grover** [comment]
Hey @ellistarn , We have almost fixed the bad PDBs by implementing Gatekeeper rules and keeping them clean. But still there are exceptions such as Pods stuck in `ImagePullBackOff` on which Karpenter gets stuck. 
The configurable attempts that I am proposing,  will atleast help us to keep the test environments cost effective. And we can set high values for production to make sure that Karpenter has made enough attempts to Evict it gracefully. 

If you still insists on not providing the option for the right reasons you mentioned :)  Is there any chance for Karpenter to ignore graceful evictions if any of the container is stuck in `ImagePullBackOff` or is failing to start ?

**Comment by ellistarn** [comment]
>  Pods stuck in ImagePullBackOff on which Karpenter gets stuck.

Why doesn't karpenter evict these?

**Comment by ra-grover** [comment]
Apologies for replying late @ellistarn , I think the PDB gets in the way because the pod is already in a failed state (due to whatever reason). I found this long standing [issue](https://github.com/kubernetes/kubernetes/issues/72320) which is resolved just recently in https://github.com/kubernetes/kubernetes/pull/113375.

I think a work-around that I proposed to specify a configurable max eviction tries will be really helpful.

**Comment by ellistarn** [comment]
That upstream issue seems like a great fit. If you enabled that policy, would you still need the karpenter override?

**Comment by ra-grover** [comment]
I think we would still need the Karpenter override, we are running 1.22 and wont be able to just upgrade to 1.26 (EKS is supported till 1.24) for that feature. Also thats behind a feature gate,  It will be really helpful to have this override in Karpenter.

**Comment by ellistarn** [comment]
Sure -- I'm thinking about the future state though. Do we need a long term solution in Karpenter, or do we need a short term fix to tide you over until 1.26. Once that feature is available, is there any value in karpenter also having an override?

**Comment by ra-grover** [comment]
I think it's more of a short term fix only. We wont need Karpenter override past 1.26.

**Comment by ellistarn** [comment]
Let me think on what we can do to help in the near term. One idea:
* We could ignore imagepullbackoff pods in termination decisions
* It's possible the pod could get stuck evicting due to PDBs
* You could implement a cronjob that gets and deletes pods that are in imgpullbackoff
wdyt?

**Comment by tzneal** [comment]
> In the case where nodes are removed for consolidation purposes, does Karpenter only select nodes for scale-down if it is sure that all pods on those nodes can be scheduled somewhere else? AFAIK that is the behavior of the cluster-autoscaler, which I personally think is an acceptable behavior.

No, we attempt this first but if we can replace a node with a cheaper node, we will also launch a cheaper replacement and then drain/shutdown the more expensive node.

**Comment by njtran** [comment]
@ra-grover looking at this issue again, is it feasible to do what Ellis has mentioned above here? https://github.com/aws/karpenter/issues/3052#issuecomment-1362399148

**Comment by ra-grover** [comment]
> You could implement a cronjob that gets and deletes pods that are in imgpullbackoff

We can implement for sure on our end, but I think since Karpenter is the one initiating the Cordoning/Pod eviction, it makes much more sense(atleast for me) to have this in Karpenter.

**Comment by jonathan-innis** [comment]
Similar to #1526 in its use-case

**Comment by njtran** [comment]
Sounds like the linked upstream issue is beta in 1.27 now in the [above comments](https://github.com/aws/karpenter/issues/3052#issuecomment-1361742147). Considering EKS supports both 1.26 and 1.27, which has the [feature](https://kubernetes.io/blog/2023/01/06/unhealthy-pod-eviction-policy-for-pdbs/) in alpha and in beta, I'll close this one. Feel free to re-open if you disagree.
