### ISSUE TITLE
Nodes getting cordoned and deleted as soon as they starts

### ISSUE THREAD

**Issue by Avani231194** [aws/karpenter#3060]
### Version

Karpenter Version: 0.20.0
Kubernetes Version:v1.22

### Expected Behavior

Expected behaviour is to get pods scheduled on nodes

### Actual Behavior

	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "f60dacd", "provisioner": "spot-karpenter-nodes-arm64", "launched-instance": "", "hostname": "", "type": "c6gd.medium", "zone": "ap-south-1a", "capacity-type": "spot"}
	INFO	controller.interruption	deleted node from interruption message	{"commit": "f60dacd", "queue": "bms-eks-sit", "messageKind": "StateChangeKind", "node": "", "action": "CordonAndDrain"}
	INFO	controller.termination	cordoned node	{"commit": "f60dacd", "node": ""}
INFO	controller.termination	deleted node	{"commit": "f60dacd", "node": ""}

### Steps to Reproduce the Problem

Install Karpenter, Add provisioners and aws-node template

### Resource Specs and Logs

`---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: spot-karpenter-nodes-arm64
spec:
  annotations:
    karpenter.sh/do-not-consolidate: "true"
    karpenter.sh/do-not-evict: "true"
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - c6g.medium
        - m6g.medium
        - t4g.small
        - c6g.large
        - t4g.medium
        - c6g.xlarge
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-south-1a"]
  taints:
    - key: "arch"
      value: "arm64test"
      effect: "NoSchedule"
  limits:
    resources:
      cpu: "100"
      memory: 100Gi
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 500
`

`---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: <>
  securityGroupSelector:
    karpenter.sh/discovery: <>
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 30Gi
        volumeType: gp3
        iops: 3000
        encrypted: true
        deleteOnTermination: true
        throughput: 125
  instanceProfile: <profile name created>`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@Avani231194 Can you share the instance ID or the node name of the launched instance that is getting terminated? This instance ID should appear further up in the logs if you could share those.

**Comment by Avani231194** [comment]
@jonathan-innis  Thankyou for response.
Instance ID : i-03c6a154bacfb375f

**Comment by jonathan-innis** [comment]
@Avani231194 Looking at the logs internally, it looks like you are trying to create an encrypted device volume but do not have the permission to access the encryption keys, which is causing instance start to fail and the instance to go immediately into a terminating state.

Typically, encryption settings might be region/account-wide so can you check if EBS encryption is set by default in the region/on the account?

**Comment by Avani231194** [comment]
Hey @jonathan-innis 

We do not have  EBS encryption set by default, not sure if Karpenter expects it.

`
aws ec2 disable-ebs-encryption-by-default 
{
    "EbsEncryptionByDefault": false
}`

Also, I tried removing EBS Volume block from aws-node-template.yaml, but didn't help

**Comment by jonathan-innis** [comment]
Hmmm, do you have another instance ID after launching with the EBS encryption disabled. There may be a different error that is plaguing you now.

**Comment by Avani231194** [comment]
Hey @jonathan-innis 

I tried again without EBS, but the issue seems to be same.

Instance ID : i-0ceccec5bb82fa390

Ref : AWSNodeTemplate.yaml

`---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: <CLUSTER NAME>
  securityGroupSelector:
    karpenter.sh/discovery: <CLUSTER NAME>`

`2022-12-21T04:03:08.761Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "f60dacd", "provisioner": "spot-karpenter-nodes-arm64", "launched-instance": "i-0ceccec5bb82fa390", "hostname": "", "type": "c6gn.medium", "zone": "XXXXXX, "capacity-type": "spot"}
2022-12-21T04:03:10.091Z	INFO	controller.interruption	deleted node from interruption message	{"commit": "f60dacd", "queue": "bms-eks-sit", "messageKind": "StateChangeKind", "node": "ip-10-27-30-252.ap-south-1.compute.internal", "action": "CordonAndDrain"}
2022-12-21T04:03:10.135Z	INFO	controller.termination	cordoned node	{"commit": "f60dacd", "node": ""}
2022-12-21T04:03:10.289Z	INFO	controller.termination	deleted node	{"commit": "f60dacd", "node": ""}`

**Comment by Avani231194** [comment]
Hi @jonathan-innis 

One more thing that I found in CloudTrail logs is, the event "AttachNetworkInterface" is not getting triggered, or it is failing to attach an interface to pod.

**Comment by Avani231194** [comment]
Hey @jonathan-innis  We were able to launch nodes.
Standalone pods are getting scheduled, but  when added a side car going into crashloop backoff as sidecar is unable to run

**Comment by jonathan-innis** [comment]
Still looking into this one internally. Are you saying that you are no longer observing the issue?

**Comment by Avani231194** [comment]
@jonathan-innis  Yes, that issue seems to be resolved. 
Other one that we are facing now is on one same node, some of the pod will go in running state and for the same application some will go in to crashloopbackoff

**Comment by jonathan-innis** [comment]
@Avani231194, that sounds like it may be unrelated to Karpenter since it's related to the container running successfully or erroring out. I'm going to close this since you say that you are no longer observing the issue.

Feel free to re-open if you begin observing it again.
