### ISSUE TITLE
Impelment node rotation solution 

### ISSUE THREAD

**Issue by karma-git** [aws/karpenter#3062]
### Tell us about your request

As a cluster administrator and `karpenter` user, I manage worker nodes via `Provisioner` and `AWSNodeTemplates`.

But when I change some parameters of EC2 instance via `Provisioner` or `AWSNodeTemplate` (eg `AMI`) it applies only for new nodes that `karpenter` creates. So after the update of one of these `CRDs` I should rotate my nodes somehow (eg`kubectl drain <node_name>`, `kubectl delete node <node_name>`). 

Is there any way to automate it?  I imagine It looks like *EKS NodeGroup rollingUpdate*

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

`karpenter` should have a mechanism to rotate old nodes

### Are you currently working around this issue?

At this moment I use simple bash loop

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by karma-git** [comment]
I've found that `karpenter` has architecture concept of [NodesDrift](https://github.com/aws/karpenter/blob/main/designs/node-upgrades.md#background---what-is-node-drift).
Looks like what I need, but, as I understand, it has not been implemented yet.

**Comment by ellistarn** [comment]
Drift is currently in implementation phase and should cover this usecase. Feel free to chime in on #1738
