### ISSUE TITLE
Binpack multiple Spot instances instead of one large OD instance

### ISSUE THREAD

**Issue by nirroz93** [aws/karpenter#3063]
### Version

__Karpenter Version:__ v0.20.0

Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
### 

### Expected Behavior

We rollout multiple deployments, which created 160 pods pending, requesting lots of resources. We expected it to lunch multiple nodes, using spot instances. Instead we got HUGE instance, which doesn't have spot capacity (so OD). We also expected consolidation mechanism to remove the OD instance (to split to multiple spot instances), but this node was running 3 days before we manually deleted it.

No affinities in all pods (not to think we want the to have affinity :-) )

### Actual Behavior

Karpenter launched u-3tb1.56xlarge OD instance, consolidation didn't remove it as cheaper instances were available 

### Steps to Reproduce the Problem

Cordon all nodes, rollout the deployments/STS at once by 
``` 
kubectl rollout deploy -n <my-large-namespace>
```

### Resource Specs and Logs

2022-12-14T16:12:40.904Z INFO controller.provisioner launching node with 160 pods requesting {\"cpu\":\"208255m\",\"ephemeral-storage\":\"98687305Ki\",\"memory\":\"573667929600\",\"pods\":\"165\"} from types u-3tb1.56xlarge, u-6tb1.56xlarge, u-6tb1.112xlarge, u-9tb1.112xlarge, u-12tb1.112xlarge and 1 other(s) {\"commit\": \"f60dacd\", \"provisioner\": \"general\"}

2022-12-14T16:12:48.850Z INFO controller.provisioner.cloudprovider launched new instance {\"commit\": \"f60dacd\", \"provisioner\": \"general\", \"launched-instance\": \"i-0d67a7a1f36857363\", \"hostname\": \"ip-10-14-32-170.ec2.internal\", \"type\": \"u-3tb1.56xlarge\", \"zone\": \"us-east-1b\", \"capacity-type\": \"on-demand\"}

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: karpenter
  creationTimestamp: "2022-12-11T13:04:45Z"
  generation: 5
  labels:
    app.kubernetes.io/managed-by: Helm
  name: general
  resourceVersion: "683290867"
  uid: e681c7ae-6c86-4344-abd3-940b97611535
spec:
  consolidation:
    enabled: true
  kubeletConfiguration:
    containerRuntime: dockerd
    evictionHard:
      imagefs.available: 5%
      imagefs.inodesFree: 5%
      memory.available: 500Mi
      nodefs.available: 10%
      nodefs.inodesFree: 10%
      pid.available: 7%
    evictionSoft:
      imagefs.available: 10%
      imagefs.inodesFree: 10%
      memory.available: 600Mi
      nodefs.available: 15%
      nodefs.inodesFree: 15%
      pid.available: 10%
    evictionSoftGracePeriod:
      imagefs.available: 2m0s
      imagefs.inodesFree: 2m0s
      memory.available: 2m0s
      nodefs.available: 2m0s
      nodefs.inodesFree: 2m0s
      pid.available: 2m0s
  labels:
    instance-types: general
    managed-by: karpenter
  limits:
    resources:
      cpu: 1k
  provider:
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
    metadataOptions:
      httpEndpoint: enabled
      httpProtocolIPv6: disabled
      httpPutResponseHopLimit: 2
      httpTokens: optional
    securityGroupSelector:
      karpenter.sh/discovery/my-cluster: my-cluster
    subnetSelector:
      Name: '*private*'
      aws-ids: <subnet-ids>
    tags:
      Name: my-cluster-general
      environment: integration
      group: search
      instance-types: general
      k8sClusterName: my-cluster
      karpenter.sh/discovery/my-cluster: my-cluster
      owner: Terraform
      product_component: k8s
      product_unit: eks
      service_name: eks_machines_general
  requirements:
  - key: karpenter.k8s.aws/instance-category
    operator: NotIn
    values:
    - p
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
    - on-demand
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  ttlSecondsUntilExpired: 2592000
  weight: 30

```
Sunbets IDs are 3 subnets in different AZs in us-east-1 region (removed the IDs). This seems like some sort of over-batching (batching the large request into a big instance, while we can use multiple smaller spot instances). Also opened an issue with the AWS support (just to make sure I understand correctly)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Node binpacking is an NP-hard problem. This means that for any decision Karpenter makes, there's always a chance that there's a better theoretical decision than what our heuristic makes. The binpacking algorithm currently favors larger instance types, as it's cheap to compute and results in lower load on the API Server and lower daemonset overhead. 

In order to detect cases like the one you mention, we'd need to do more sophisticated heuristics. Specifically, our binpacker would need to consider launching an additional node rather than increasing the size of the node. To do this, it would need to be aware of the incremental overhead of daemons and system resources for the additional node, as well as the combined cost of both nodes compared to the larger node. Finally, we'd need to decide exactly how to split it. For example, do you split a node of family `m` into an `r` and `c`? 

So far, we haven't come up with something that we're confident can handle this case well. We're very open minded to ideas to solve this problem.

**Comment by runningman84** [comment]
How about limiting the max number of cores? Wouldn’t that help in this situation?

**Comment by tzneal** [comment]
There are a few options for avoiding the super large instancetypes.  You can add some requirement to limit the provisioner or exclude particular sizes using the `karpenter.k8s.aws/instance-size` label, or add a generic requirement like this to limit instance types to those with 32 CPUs or fewer:

```yaml
  - key: karpenter.k8s.aws/instance-cpu
    operator: Lt
    values:
    - "33"
 ```

**Comment by nirroz93** [comment]
Is there a option to address this problem specifically for OD (if OD - try to divide)? 

I'm more worried about large OD instances, than large spot instances.

**Comment by nirroz93** [comment]
Maybe prefer size up to N (not sure what the number) cores with spot instances, and not going for the largest,  as anyway smaller instances are more stable in terms of interruption rate.

**Comment by tzneal** [comment]
Right now you would do that with multiple weighted provisioners. The higher weighted one would be spot and you would put a requirement on the lower weighted on-demand provisioner.

**Comment by nirroz93** [comment]
> Right now you would do that with multiple weighted provisioners. The higher weighted one would be spot and you would put a requirement on the lower weighted on-demand provisioner.

If I go this way, and a node was provisioned in the OD provisioner (due to lack of spot capacity), consolidation now won't replace the OD node with spot (when capacity is available), right (as consolidation is working on provisioner level)?

**Comment by sftim** [comment]
> Is there a option to address this problem specifically for OD (if OD - try to divide)?

We could have a check to see if a spot-only solution exists that is cheaper than the selected on-demand solution, and that satisfied consolidation constraints. However, it might be hard to encode that heuristic in a way that is agnostic to cloud providers.

Consolidation across multiple weighted provisioners would solve this, I think.

**Comment by jonathan-innis** [comment]
> Consolidation across multiple weighted provisioners would solve this, I think

Consolidation _does_ work across multiple provisioners as @sftim calls out. I'm going to close this since this looks like this use-case can mostly be solved with weighted provisioners.
