### ISSUE TITLE
The karpenter_pods_state is reported in a different way

### ISSUE THREAD

**Issue by kwarunek** [aws/karpenter#3064]
### Version

__Karpenter Version:__ v0.20.0

__Kubernetes Version:__ v1.22.15

### Expected Behavior

The **karpenter_pods_state** "should reflec" (?) the **kube_pod_status_phase** metrics.

### Actual Behavior

After upgrade to 0.20.0 from 0.19.3 metric seems to be incremental.

### Steps to Reproduce the Problem

Upgrade from v0.19.3 to v0.20.0

### Resource Specs and Logs

![cmp_karpenter_vs_kube_metrics](https://user-images.githubusercontent.com/670887/208427628-f3b915f7-df87-4db2-842f-0b96c4c87d25.png)

Upgrade date 2022-12-12.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@kwarunek You're confirming that prior to v0.20.0, this metric worked correctly?
