### ISSUE TITLE
Allow setting webhook certificate TTL

### ISSUE THREAD

**Issue by grosser** [aws/karpenter#3067]
### Tell us about your request

I want to make the webhook certs be valid for at least 3 days

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

we have monitoring that ensures all webhook certs are valid >x, but there is no setting in karpenter to allow specifying that, so we have to mute the alert for karptenter webhooks

I did not see where exactly in the code the certs get refreshed, but the controller has permission to modify karpenter-cert so I assume it's in there somewhere.

### Are you currently working around this issue?

muting monitoring for karpenter

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> but there is no setting in karpenter to allow specifying that, so we have to mute the alert for karptenter webhooks

I'm confused, what is the monitor that you have? Are you having issues because the cert is rotating too quickly or too slowly?

**Comment by grosser** [comment]
- we monitor the ttl (not after) of the certs of the webhooks
- the cert is rotating too quickly (as in it's fine to rotate on the current schedule, but we'd want it to be valid for longer)

**Comment by grosser** [comment]
we want to ensure that all certs in the cluster have >x days ttl so we have time to fix if cert rotation fails (and we alert when the ttl is <x hours)
