### ISSUE TITLE
charts/index.yaml not reflecting release 0.20.0

### ISSUE THREAD

**Issue by peteroruba** [aws/karpenter#3091]
### Version

v0.20.0

### Expected Behavior

helm repo add karpenter   https://charts.karpenter.sh
helm install  --namespace karpenter karpenter/karpenter --version v0.20.0
NAME: karpenter
LAST DEPLOYED: Wed Dec 21 09:58:28 2022
NAMESPACE: karpenter
STATUS: deployed
REVISION: 1
TEST SUITE: None

### Actual Behavior

helm repo add karpenter   https://charts.karpenter.sh
helm install  --namespace karpenter karpenter/karpenter --version v0.20.0
Error: chart "karpenter" matching v0.20.0 not found in karpenter index. (try 'helm repo update'): no chart version found for karpenter-v0.20.0

### Steps to Reproduce the Problem

helm repo add karpenter   https://charts.karpenter.sh
helm install  --namespace karpenter karpenter/karpenter --version v0.20.0

### Resource Specs and Logs

See above

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
see upgrade guide
https://karpenter.sh/v0.20.0/upgrade-guide/#upgrading-to-v0170
the repo changed to aws ecr gallery https://gallery.ecr.aws/karpenter/karpenter
