### ISSUE TITLE
panic: failed to wait for drift caches to sync

### ISSUE THREAD

**Issue by bwmetcalf** [aws/karpenter#3117]
### Version

__Karpenter Version:__ v0.21.0

__Kubernetes Version:__ v1.23.13-eks-fb459a0

### Expected Behavior

karpenter pod to remain healthy and not crash

### Actual Behavior

Shortly after upgrading to `v0.21.0` from `0.9.1` karpenter pods crash with the following:
```
panic: failed to wait for drift caches to sync: timed out waiting for cache to be synced

goroutine 345 [running]:
github.com/samber/lo.must({0x2344300, 0xc001dddd00}, {0x0, 0x0, 0x0})
	github.com/samber/lo@v1.36.0/errors.go:53 +0x1f4
github.com/samber/lo.Must0(...)
	github.com/samber/lo@v1.36.0/errors.go:72
github.com/aws/karpenter-core/pkg/operator.(*Operator).Start.func1()
	github.com/aws/karpenter-core@v0.21.0/pkg/operator/operator.go:167 +0x85
created by github.com/aws/karpenter-core/pkg/operator.(*Operator).Start
	github.com/aws/karpenter-core@v0.21.0/pkg/operator/operator.go:165 +0xec
```

### Steps to Reproduce the Problem

Upgrade to `v0.21.0`

### Resource Specs and Logs

Our user supplied values are (cluster endpoint and account id masked):
```
$ helm get values karpenter
USER-SUPPLIED VALUES:
replicas: 1
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::***********:role/dev-test-karpenter
settings:
  aws:
    clusterEndpoint: https://43360E31525DF56CD************.gr7.us-west-2.eks.amazonaws.com
    clusterName: dev-test-k8s-cluster
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
This is a fairly large version jump. From v0.9.1 to v0.21.0, that's 12 versions with a LOT of features in between. To ensure that this isn't something you might've missed in the [upgrade guide](https://karpenter.sh/v0.21.0/upgrade-guide/), could you try doing a fresh install with the same settings? 

In addition, could you post your provisioner spec and AWSNodeTemplate Spec and your `karpenter/karpenter-global-settings` configmap with any confidential information x'd out with this command `kubectl get cm karpenter-global-settings -n karpenter -oyaml` ?

**Comment by bwmetcalf** [comment]
@njtran Thanks for the reply.  This may take a couple of days to refactor everything.  We just found that launch templates were deprecated in 0.16.3 so we'll need to migrate everything to a `AWSNodeTemplate` specification.  We put a significant amount of work into creating our karpenter launch templates; it's unfortunate this is no longer supported.

**Comment by njtran** [comment]
Sounds good. We released a fix that prevents log spamming that occurred on v0.21.0 when you used a provider, so please upgrade to v0.21.1 if you could. Regardless of the issue, it would be useful to have any details you could provide, since we shouldn't have a panic anyways. Let me know how your fresh install works. You should still be able to use your custom launch template, but won't be able to use drift.

**Comment by njtran** [comment]
Hey @bwmetcalf, any update on the specs? Would like to see if this is an error with the large jump in versions or our code.

**Comment by bwmetcalf** [comment]
Hi @njtran.  We have three provisioners configured and are shown below:
```
apiVersion: v1
items:
- apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    creationTimestamp: "2022-07-26T22:32:07Z"
    generation: 1
    name: provisioner-1
    resourceVersion: "347469051"
    uid: ad4a7505-9fb6-4d53-9f7e-bb8bc911eb04
  spec:
    labels:
      provisioner-1-dedicated: "true"
      node.umbra.space/exclude-from-external-load-balancers: "true"
    limits:
      resources:
        memory: 16Gi
    provider:
      launchTemplate: dev-test-k8s-worker-custom-template-karpenter
      subnetSelector:
        Name: dev-test-compute-private*
      tags:
        Name: dev-test-k8s-worker-autoscale
        Provisioner: provisioner-1
    requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
      - on-demand
      - spot
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
      - m5.2xlarge
      - m5.large
      - m5.xlarge
    taints:
    - effect: NoSchedule
      key: provisioner-1-dedicated
    ttlSecondsAfterEmpty: 300
  status:
    resources:
      cpu: "0"
      memory: "0"

- apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    creationTimestamp: "2022-07-26T19:55:20Z"
    generation: 1
    name: provisioner-2
    resourceVersion: "347469050"
    uid: 6732e17c-d35d-43d3-bba0-b74b553fa49a
  spec:
    labels:
      provisioner-2-dedicated: "true"
      node.umbra.space/exclude-from-external-load-balancers: "true"
    limits:
      resources:
        memory: 32Gi
    provider:
      launchTemplate: dev-test-k8s-worker-custom-template-karpenter
      subnetSelector:
        Name: dev-test-compute-private*
      tags:
        Name: dev-test-k8s-worker-autoscale
        Provisioner: provisioner-2
    requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
      - on-demand
      - spot
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
      - m5.large
      - m5.xlarge
    taints:
    - effect: NoSchedule
      key: provisioner-2-dedicated
    ttlSecondsAfterEmpty: 7200
  status:
    resources:
      cpu: "4"
      memory: 16076856Ki

- apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    creationTimestamp: "2022-07-26T19:55:20Z"
    generation: 1
    name: karpenter-provisioner
    resourceVersion: "347469052"
    uid: a742c9f6-4bef-4c2c-90fd-f4ed5df68e32
  spec:
    limits:
      resources:
        memory: 80Gi
    provider:
      launchTemplate: dev-test-k8s-worker-custom-template-karpenter
      subnetSelector:
        Name: dev-test-compute-private*
      tags:
        Name: dev-test-k8s-worker-autoscale
        Provisioner: karpenter-provisioner
    requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
      - on-demand
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
      - m5.2xlarge
      - m5.xlarge
    ttlSecondsAfterEmpty: 30
    ttlSecondsUntilExpired: 1296000
  status:
    resources:
      cpu: "16"
      memory: 64135376Ki
kind: List
metadata:
  resourceVersion: ""
```
I will be attempting an clean upgrade this week.  Please let me know if I can provide more information at this point.

Thanks.

**Comment by vegassor** [comment]
I had the same error when I was upgrading from v0.16 to v0.22 and forgot to upgrade CRDs.
After upgrading CRDs (https://karpenter.sh/preview/upgrade-guide/#custom-resource-definition-crd-upgrades) the error was gone.

**Comment by morepe** [comment]
> I had the same error when I was upgrading from v0.16 to v0.22 and forgot to upgrade CRDs. After upgrading CRDs (https://karpenter.sh/preview/upgrade-guide/#custom-resource-definition-crd-upgrades) the error was gone.

That helped for also for us. Attention: there are two commands in that one field on the upgrade rule.

The aws node template did not exist for me, so I could not use the replace command and applied it: 
`kubectl apply -f https://raw.githubusercontent.com/aws/karpenter/main/pkg/apis/crds/karpenter.k8s.aws_awsnodetemplates.yaml`

**Comment by bwmetcalf** [comment]
We successfully upgraded to 0.22.1 and deleting the CRDs before upgrading was part of our process and most likely the resolution to this issue.  I'm going to close this issue.  Thank you.
