### ISSUE TITLE
conflicting docs on Node Termination Handler

### ISSUE THREAD

**Issue by pdeva** [aws/karpenter#3142]
### Is an existing page relevant?

https://aws.github.io/aws-eks-best-practices/karpenter/#install-the-aws-node-termination-handler-when-using-spot

### What karpenter features are relevant?

Node Termination Handler

### How should the docs be improved?

 - [FAQ](https://karpenter.sh/preview/faq/#should-i-use-karpenter-interruption-handling-alongside-node-termination-handler) says to **_not install_**  Node Termination Handler.

however, 

- [Best Practices](https://aws.github.io/aws-eks-best-practices/karpenter/#install-the-aws-node-termination-handler-when-using-spot) says to **_install_** the Node Termination Handler?

**Issue 1:** Which one is it? To install or not install the Node Termination Handler?

Similarly,

On [Terraform installation page](https://karpenter.sh/preview/getting-started/getting-started-with-terraform/#create-the-karpenter-aws-resources) , it talks about installing resources to help with Node Termination:

> We will utilize the karpenter sub-module to create the necessary AWS resources required by Karpenter, including those necessary to support node termination handling (SQS queue and EventBridge rules).

However the [guide on eksctl](https://karpenter.sh/preview/getting-started/getting-started-with-eksctl/) does not mention these SQS and EventBridge resources at all.

**Issue 2:** Are the SQS queue and EventBridge rules referred in the terraform guide actually needed? If so, what are they and where can one find documentation for those?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
@pdeva Thanks for opening this up and bringing it to our attention. We'll try and fix this as soon as possible!

**Comment by andrewhibbert** [comment]
I used the module `terraform-aws-modules/eks/aws//modules/karpenter` to setup the SQS queue and Event bridge stuff and then the blueprints github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons to install karpenter via helm and setup the IAM role for service accounts. There is a bug in the blueprints though https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1285.

**Comment by pdeva** [comment]
The pr in https://github.com/aws/aws-eks-best-practices/pull/261 talks about additional permissions being needed for accessing the sqs queue. Would be great if it could point to the exact doc that has these permissions listed.

**Comment by jonathan-innis** [comment]
@pdeva Makes sense. I don't think we have the exact permissions documented beyond the CF template. I'll add a PR and add it to the docs.

**Comment by pdeva** [comment]
Also the docs on [setup with terraform](https://karpenter.sh/preview/getting-started/getting-started-with-terraform/) make no mention of `karpenter-global-settings` config map  that is mentioned in the documentation on [Interruption](https://karpenter.sh/preview/concepts/deprovisioning/#interruption). I didnt know about this config map until now since i  did my setup using the 'getting started with terraform' docs and so apparently node termination is not even turned on for my Karpenter installation since I havent specified the queue name in the config map.

When i do a search for `karpenter-global-settings` map it points me to an [outdated version's documentation](https://karpenter.sh/v0.19.3/tasks/globalsettings/). The documentation for `karpenter-global-settings` doesnt even exist for latest version..

**Comment by jonathan-innis** [comment]
> Also the docs on [setup with terraform](https://karpenter.sh/preview/getting-started/getting-started-with-terraform/) make no mention

We are planning to remove these docs with [this change](https://github.com/aws/karpenter/pull/3017) so we won't be making updates to that terraform guide in our getting started guide anymore.

> When i do a search for karpenter-global-settings map it points me to an

It [does exist](https://karpenter.sh/v0.21.1/concepts/settings/#configmap), though the file name has changed.

We've done a bunch of docs consolidation lately to help make the flow of things a bit clearer so that is the reason sifting between the docs you are most likely getting not found.

**Comment by jonathan-innis** [comment]
For the two issues:
1. Improving Permissions Documentation: We are working on releasing some documentation that would allow this information to be better-discovered
2. EKS Best Practices is kept up-to-date: [This PR](https://github.com/aws/aws-eks-best-practices/pull/260) is handling getting that doc updated with the best recommendations


We're working on documenting the permissions that are required for each feature to work appropriately alongside making sure

**Comment by jonathan-innis** [comment]
PR is merged so I'm closing this one for now. As for the permission docs, we discussed offline and think that the current CloudFormation in the EKS getting-started guide (which should soon be the only getting started guide in the docs) is sufficient to show the permissions needed to run all the aspects of Karpenter.
