### ISSUE TITLE
Node is not being removed despite ttlSecondsUntilExpired expiration

### ISSUE THREAD

**Issue by peteroruba** [aws/karpenter#3158]
### Version

__Karpenter Version:__ v0.21.1
__Kubernetes Version:__ v1.22.0

We managed to launch an additional EKS Worker Node via Karpenter, however, the same node does not get terminated. The corresponding settings are as follows:

ttlSecondsUntilExpired: 300
consolidation:
  enabled: true

The Logs show now ERRORs in respect to missing IAM permissions. Also I cannot code referencing the 'ttlSecondsUntilExpired' string. 

Happy to provide more details. 

Thanks

### Expected Behavior

EC2 launched by Karpenter gets terminated after 300 seconds.

### Actual Behavior

EC2 launched by Karpenter is not being terminated.

### Steps to Reproduce the Problem

Deploy a workload that triggers the launch of an additional EC2 and wait for ttlSecondsUntilExpired seconds.

### Resource Specs and Logs

apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  providerRef:
    name: default
  ttlSecondsUntilExpired: 300
  consolidation:
    enabled: true
  kubeletConfiguration:
    containerRuntime: dockerd
  requirements:
    - key: "node.kubernetes/instance-type"
      operator: In
      values: ["r6i.large"]
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["r"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["eu-central-1a", "eu-central-1b"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
> The Logs show now ERRORs in respect to missing IAM permissions.

**Comment by peteroruba** [comment]
[karpenter-5f7544869b-l2pxm.log](https://github.com/aws/karpenter/files/10352583/karpenter-5f7544869b-l2pxm.log)

Providing the full log.

**Comment by tzneal** [comment]
The ENI resource isn't registering, so the node never gets fully initialized.  This occurs when you enable `AWS_ENABLE_POD_ENI`, but don't make the corresponding VPC CNI DaemonSet changes described at https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html


```
2023-01-05T11:04:52.392Z	INFO	controller.inflightchecks	Inflight check failed for node, Expected resource "vpc.amazonaws.com/pod-eni" didn't register on the node	{"commit": "06cb81f-dirty", "node": "ip-10-139-149-155.eu-central-1.compute.internal"}
```

**Comment by peteroruba** [comment]
@tzneal that was it. Much appreciated. Thank you!
