### ISSUE TITLE
Deploy first provisionner

### ISSUE THREAD

**Issue by DGILLES-CPX** [aws/karpenter#3160]
### Version

__Karpenter Version:__ v0.21.1
__Kubernetes Version:__ Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.7-eks-fb459a0", GitCommit:"c240013134c03a740781ffa1436ba2688b50b494", GitTreeState:"clean", BuildDate:"2022-10-24T20:36:26Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}

Hello,

1) With consolidation 
k apply -f karpenter.yaml
error: error validating "karpenter.yaml": error validating data: [ValidationError(Provisioner.spec): unknown field "consolidation" in sh.karpenter.v1alpha5.Provisioner.spec, ValidationError(Provisioner.spec): unknown field "providerRef" in sh.karpenter.v1alpha5.Provisioner.spec]; if you choose to ignore these errors, turn validation off with --validate=false

1) Remove consolidation. 
k apply -f karpenter.yaml
error: error validating "karpenter.yaml": error validating data: ValidationError(Provisioner.spec): unknown field "providerRef" in sh.karpenter.v1alpha5.Provisioner.spec; if you choose to ignore these errors, turn validation off with --validate=false

See my config complete config in attachment. 

Thank you for your support
Regards Damien. 

### Expected Behavior

After successfully install Karpenter on my EKS 
I try to deploy my Provisionner and AWSNodeTemplate 

### Actual Behavior

I have two issues maybe more but I stopped after. 
1) With consolidation 
k apply -f karpenter.yaml
error: error validating "karpenter.yaml": error validating data: [ValidationError(Provisioner.spec): unknown field "consolidation" in sh.karpenter.v1alpha5.Provisioner.spec, ValidationError(Provisioner.spec): unknown field "providerRef" in sh.karpenter.v1alpha5.Provisioner.spec]; if you choose to ignore these errors, turn validation off with --validate=false

1) Remove consolidation. 
k apply -f karpenter.yaml
error: error validating "karpenter.yaml": error validating data: ValidationError(Provisioner.spec): unknown field "providerRef" in sh.karpenter.v1alpha5.Provisioner.spec; if you choose to ignore these errors, turn validation off with --validate=false

### Steps to Reproduce the Problem

helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version ${KARPENTER_VERSION} --namespace karpenter --create-namespace \
  --set serviceAccount.create=false \
  --set settings.aws.clusterName=${CLUSTER_NAME} \
  --set settings.aws.clusterEndpoint=${CLUSTER_ENDPOINT} \
  --set settings.aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
  --set settings.aws.interruptionQueueName=${CLUSTER_NAME} \
  --wait 

k apply -f karpenter.yaml 

### Resource Specs and Logs

[karpenter.yml.zip](https://github.com/aws/karpenter/files/10353995/karpenter.yml.zip)

 k get all -n karpenter
NAME                             READY   STATUS    RESTARTS   AGE
pod/karpenter-5fbfb54f5b-qgxl7   1/1     Running   0          56m
pod/karpenter-5fbfb54f5b-qk7rm   1/1     Running   0          56m

NAME                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)            AGE
service/karpenter   ClusterIP   10.100.116.172   <none>        8080/TCP,443/TCP   56m

NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/karpenter   2/2     2            2           56m

NAME                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/karpenter-5fbfb54f5b   2         2         2       56m

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Make sure your CRDs are up to date: https://karpenter.sh/v0.21.1/upgrade-guide/#custom-resource-definition-crd-upgrades

Here's what I get with your provisioner. 
```
k apply -f ~/Downloads/karpenter.yml
awsnodetemplate.karpenter.k8s.aws/template-webapp created
Error from server (BadRequest): error when creating "/Users/etarn/Downloads/karpenter.yml": admission webhook "validation.webhook.karpenter.sh" denied the request: validation failed: expected exactly one, got both: spec.consolidation.enabled, spec.ttlSecondsAfterEmpty
```

Currently, you can either use consolidation or TTLSecondsAfterEmpty

**Comment by DGILLES-CPX** [comment]
Tada ! 
Et voila 
provisioner.karpenter.sh/provisionner-webapp created
awsnodetemplate.karpenter.k8s.aws/template-webapp created

thank you for your support ! 
Regards,
Damien
