### ISSUE TITLE
Deleting the karpenter namespace should delete all nodes spun up by Karpenter

### ISSUE THREAD

**Issue by pdeva** [aws/karpenter#3179]
### Version

__Karpenter Version:__ v0.21.1

__Kubernetes Version:__ 1.24

### Expected Behavior

Getting rid of the `karpenter` namespace should also delete all the nodes spun up by Karpenter

### Actual Behavior

Nodes remain in the cluster

### Steps to Reproduce the Problem

Create EKS cluster, install Karpenter and let it create new nodes.
Then delete the `karpenter` namespace entirely using kubectl.

### Resource Specs and Logs

NA

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
This cleanup problem is broad across any kubernetes operator. You'll see the same issues with the LB controller and loadbalancers it creates. As soon we karpenter is uninstalled, we lose our ability to execute code (like deleting nodes).

**Comment by pdeva** [comment]
i think its still worth documenting so folks know what they are in for if they uninstall karpenter. i specifically noticed that its tough to delete the karpenter nodes manually after removing karpenter installation. had to patch out the node finalizer for k8s to finally delete the node.

**Comment by njtran** [comment]
This is detailed in the Karpenter website. https://karpenter.sh/v0.22.0/concepts/deprovisioning/#methods

> If the Karpenter controller is removed or fails, the finalizers on the nodes are orphaned and will require manual removal.
