### ISSUE TITLE
Does drift detection stable enough to run in production?

### ISSUE THREAD

**Issue by jacob-amar-rapidapi** [aws/karpenter#3181]
### Is an existing page relevant?

https://karpenter.sh/v0.22.0/concepts/settings/#feature-gates

### What karpenter features are relevant?

I see that in order to allow drift detection we should enable a feature gate called driftEnabled, does the alpha version safe enough to run in production?

### How should the docs be improved?

If this feature is not safe for production we should add a warning

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
This is safe to run in production. You should try this out in your dev clusters before rolling it out to prod though. It's important to be aware that if you have nodes that have drifted AMIs, they will be eventually updated as the pods on the node are allowed to be evicted. We are working on more controls for other use cases. Please be aware that turning on the feature gate turns it on globally. 

If you have requests for more ways to control this, feel free to comment in #1738 .  Going to close this as this as the question is answered.
