### ISSUE TITLE
ondemand > spot is actually more expensive

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/karpenter#3183]
### Version

__Karpenter Version:__ v0.21.1

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.8-eks-ffeb93d", GitCommit:"abb98ec0631dfe573ec5eae40dc48fd8f2017424", GitTreeState:"clean", BuildDate:"2022-11-29T18:45:03Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}

### Expected Behavior

for karpenter to pick the cheaper option

### Actual Behavior

karpenter replaced a ondemand instance by a spot that was more expensive

### Steps to Reproduce the Problem

add spot to the provisioner

### Resource Specs and Logs

initial state, with the provisioner with only ondemand
```
sre-karpenter-system/karpenter-64684d4f49-f7p4k[controller]: 2023-01-09T13:09:24.491Z	DEBUG	controller.provisioner	43 out of 599 instance types were excluded because they would breach provisioner limits	{"commit": "06cb81f-dirty"}
sre-karpenter-system/karpenter-64684d4f49-f7p4k[controller]: 2023-01-09T13:09:24.502Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "06cb81f-dirty", "pods": 2}
sre-karpenter-system/karpenter-64684d4f49-f7p4k[controller]: 2023-01-09T13:09:24.502Z	INFO	controller.provisioner	computed new node(s) to fit pod(s)	{"commit": "06cb81f-dirty", "newNodes": 1, "pods": 2}
sre-karpenter-system/karpenter-64684d4f49-f7p4k[controller]: 2023-01-09T13:09:24.502Z	INFO	controller.provisioner	launching node with 2 pods requesting {"cpu":"325m","memory":"180Mi","pods":"4"} from types c6id.2xlarge, m6a.4xlarge, c6id.large, m6i.2xlarge, c6a.large and 28 other(s)	{"commit": "06cb81f-dirty", "provisioner": "fernando-golden-liger-a76ea62cda68567c"}
sre-karpenter-system/karpenter-64684d4f49-f7p4k[controller]: 2023-01-09T13:09:26.593Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "06cb81f-dirty", "provisioner": "fernando-golden-liger-a76ea62cda68567c", "launched-instance": "i-08dee91b3bcd20cbf", "hostname": "i-08dee91b3bcd20cbf.ec2.internal", "type": "c6a.large", "zone": "us-east-1d", "capacity-type": "on-demand"}
sre-karpenter-system/karpenter-64684d4f49-f7p4k[controller]: 2023-01-09T13:09:31.548Z	INFO	controller.termination	deleted node	{"commit": "06cb81f-dirty", "node": "i-02e967d9dfce1f774.ec2.internal"}
```
![image](https://user-images.githubusercontent.com/168366/211316279-3cabb409-57ac-4d6f-aa49-2d2a14815a6a.png)
eks viewer shows ondemand costing `c6a.large/$0.076 On-Demand`

now we add spot to the provisioner
karpenter determines that spot is cheaper and replaces the node
```
sre-karpenter-system/karpenter-64684d4f49-f7p4k[controller]: 2023-01-09T13:15:12.848Z	INFO	controller.deprovisioning	deprovisioning via consolidation replace, terminating 1 nodes i-08dee91b3bcd20cbf.ec2.internal/c6a.large/on-demand and replacing with spot node from types r6id.large, m6i.xlarge, m6a.large, r6a.large, m6id.large and 5 other(s)	{"commit": "06cb81f-dirty"}
sre-karpenter-system/karpenter-64684d4f49-f7p4k[controller]: 2023-01-09T13:15:12.885Z	INFO	controller.deprovisioning	launching node with 2 pods requesting {"cpu":"325m","memory":"180Mi","pods":"4"} from types r6id.large, m6i.xlarge, m6a.large, r6a.large, m6id.large and 5 other(s)	{"commit": "06cb81f-dirty", "provisioner": "fernando-golden-liger-a76ea62cda68567c"}
sre-karpenter-system/karpenter-64684d4f49-f7p4k[controller]: 2023-01-09T13:15:13.231Z	DEBUG	controller.deprovisioning.cloudprovider	created launch template	{"commit": "06cb81f-dirty", "provisioner": "fernando-golden-liger-a76ea62cda68567c", "launch-template-name": "Karpenter-fernando-golden-liger-3463100294626697689", "launch-template-id": "lt-086919be676f08f30"}
sre-karpenter-system/karpenter-64684d4f49-f7p4k[controller]: 2023-01-09T13:15:15.305Z	INFO	controller.deprovisioning.cloudprovider	launched new instance	{"commit": "06cb81f-dirty", "provisioner": "fernando-golden-liger-a76ea62cda68567c", "launched-instance": "i-026e129bc4cab47bd", "hostname": "i-026e129bc4cab47bd.ec2.internal", "type": "c6id.large", "zone": "us-east-1d", "capacity-type": "spot"}
sre-karpenter-system/karpenter-64684d4f49-f7p4k[controller]: 2023-01-09T13:15:59.883Z	INFO	controller.termination	cordoned node	{"commit": "06cb81f-dirty", "node": "i-08dee91b3bcd20cbf.ec2.internal"}
```

this is the price showing
![image](https://user-images.githubusercontent.com/168366/211316637-ca6ae5a2-d234-4d28-a140-f4c5b4aaf6c4.png)

but then i see a refreshed price, which is more expensive than the initial one.
![image](https://user-images.githubusercontent.com/168366/211316962-c32142cd-e3f5-4353-9a85-cedc8b76b05c.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
My guess is that it's a bug in the eks node viewer.  The $0.101 appears to be the on-demand price.

**Comment by FernandoMiguel** [comment]
@tzneal is there anywhere in karpenter logs where we get the price fleet api chose ?

**Comment by cristim** [comment]
As far as I know karpenter doesn't consider the price of the previous instances.

It just uses a wide range of instance types that cover the capacity needed to run the pending pods. Many of those are probably more expensive than the original instance, but they're also often going to be bigger.

**Comment by FernandoMiguel** [comment]
@cristim afaik karpenter consolidation takes in consideration the node that it is replacing, otherwise you may get a more expensive one

**Comment by tzneal** [comment]
@FernandoMiguel Do you want to close this one and open it on the eks-node-viewer repo?

**Comment by tzneal** [comment]
Ah, sorry I missed that.  We don't currently have anything that logs the calculated cost that was used.
