### ISSUE TITLE
karpenter pods not coming up when using Secondary Non Routable CIDR

### ISSUE THREAD

**Issue by sujith1594** [aws/karpenter#3188]
Hi Team,
We are trying to configure karpenter in our EKS cluster which is working fine on primary CIDR.
But, when we enable secondary CIDR karpenter pods are not coming up whereas other pods are working fine.

Below is the error message from karpenter pods.

`controller.aws  Checking EC2 API connectivity, WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post "[https://sts.us-east-2.amazonaws.com/ ](https://sts.us-east-2.amazonaws.com/)": dial tcp 10.188.214.212:443: i/o timeout`

**Comment by jonathan-innis** [comment]
I don't think there should be anything unique about the networking setup for Karpenter pods. Can you provide more details about your networking setup?

**Comment by sidewinder12s** [comment]
Seems like the secondary subnet doesn't have outbound networking. You'd either need to add a NAT or add VPC Endpoints to that subnet for STS and any other services required?

**Comment by sujith1594** [comment]
The issue was the Security Group assigned to VPC Endpoints didn't allow Secondary CIDR.
