### ISSUE TITLE
Controller memory allocation steadily increasing over time

### ISSUE THREAD

**Issue by vassilvk** [aws/karpenter#3209]
### Version

__Karpenter Version:__ v0.16.0

__Kubernetes Version:__ v1.22.15

### Expected Behavior

Memory allocation of Karpenter controller should be a function of quantifiable factors such as cluster size, available EC2 instances, etc., not time.

### Actual Behavior

We have been testing Karpenter 0.16.0 for a little over a month, and in some of our clusters we are observing what looks like a memory leak in Kerpenter’s controller container. For example, for one of our clusters, karpenter `controller` container begins its life with a memory footprint (cAdvisor metric `container_memory_usage_bytes`) at about 400 MB. After 22 days of activity, it’s at 1.8 GB (see snapshots below).

The number of nodes in the cluster remains relatively stable over time, but the memory footprint of Karpenter `controller` shows steady growth throughout the month.

From functional perspective Karpenter seems to be working as expected - nodes are provisioned and deprovisioned often as a result of active consolidation.

For what it’s worth, the memory footprint of `webhook` container remains steady at around 25 MB.

### Steps to Reproduce the Problem

Run Karpenter in a highly dynamic environment where nodes are provisioned and deprovisioned several times per hour. Observe `container_memory_usage_bytes` cAdvisor metric for container `controller` of the Karpenter leader pod. Take measurements for 20+ days.

### Resource Specs and Logs

Memory usage of `controller` container of the Karpenter leader pod in one of our busier clusters.
The graph is aligned with the variable number of nodes in the cluster over the same period of time.

<img width="1200" alt="image (1)" src="https://user-images.githubusercontent.com/317808/212173849-0b7baa14-4106-468c-ad02-9bf4fc09efd2.png">

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Thanks for opening this @vassilvk. This is a really important find and a good signal that we should be doing better to ensure new changes and commits don't create memory leaks like this. I don't have a long running cluster but I'll try and replicate this to see if I can. Are you able to share any provisioner or node template or pod specs that I can use to maybe pin-point where this memory leak is?

**Comment by vassilvk** [comment]
Hi @njtran,

Unfortunately I won't be able to provide much more information. Hopefully you'll be able to reproduce on your end.

In the meantime, we are considering the option of restarting the controller on a regular basis (say each week) in order to avoid OOMKills.

Does Karpenter handle SIGTERM gracefully during rolling restart or are there any risks caused by interrupted [dual writes](https://developers.redhat.com/articles/2021/07/30/avoiding-dual-writes-event-driven-applications)?
For example, is there a risk of leaking AWS nodes if Karpenter's controller process is terminated immediately after an AWS node is provisioned, but before the node is registered with K8S?

**Comment by jonathan-innis** [comment]
> if Karpenter's controller process is terminated immediately after it provisions an AWS

There's no risk here because in the general case, userData will ensure that the correct labels are added to the node and the node will be registered as expected by the kubelet. The only risk here is if the userData doesn't ensure that the `karpenter.sh/provisioner-name` isn't added to the node through the kubelet args. This would cause the node and instance to get orphaned.

**Comment by vassilvk** [comment]
Thank you @jonathan-innis.
In this case are we safe to assume that restarting Karpenter through deployment rolling restart is safe? Are there other risks related to terminating Karpenter midflight?

**Comment by tzneal** [comment]
Yes, restarting Karpenter is mostly safe.  If you restart while a node is launching, and it fails to connect to your cluster, we can leak the node. There is ongoing work at https://github.com/aws/karpenter/pull/2944 that will prevent this from happening even in this case.

**Comment by engedaam** [comment]
@vassilvk have tried upgraded to a newer version of Karpenter? and if so, do you see the same memory allocation steadily increasing?

**Comment by ellistarn** [comment]
Note that we are working to prioritize performance and regression tests to prevent this problem for the long haul. @engedaam is suggesting a short term workaround.

**Comment by vassilvk** [comment]
Hello @engedaam,

We upgraded to Karpenter 0.21.1. We also implemented a cron job to restart Karpenter on a weekly basis.
Please see below the memory allocation of Karpenter's controller container for the past 30 days. As you can see, the gradual allocation continues to be a problem:

<img width="1591" alt="image" src="https://user-images.githubusercontent.com/317808/223753302-e8d5ebec-98a5-498b-bc4a-2333d21e2448.png">

**Comment by gkalwig** [comment]
Hi, we had the same problem in our environment:

Karpenter Version: v0.23.0
Kubernetes Version: v1.23.14

![image](https://user-images.githubusercontent.com/87004230/224632661-6c9354e5-92a3-46a1-b249-020da7dedba3.png)

**Comment by gkalwig** [comment]
We changed our cronjobs to deployments so now we don't create about ~100 jobs every few minutes, instead we deploys it in  deployments.

So it seems to be related to the creation/destruction of pods in the cluster, not create/destroy nodes.

In green graph we have disabled consolidation and enabled 50minutes empty wait, so we didn't create nodes so often. In blue, we've turned on consolidation, so node changes are more regular.


![image](https://user-images.githubusercontent.com/87004230/225547237-4fcc8cde-dc96-4370-904c-115b2b40131b.png)

**Comment by engedaam** [comment]
The memory leak of the controller seems to becoming from metrics controllers for the [provisioner](https://github.com/aws/karpenter-core/blob/0b437c20140f8d2e5a6a0947650c01d931cf594c/pkg/controllers/metrics/provisioner/controller.go#L125) and [pod](https://github.com/aws/karpenter-core/blob/0b437c20140f8d2e5a6a0947650c01d931cf594c/pkg/controllers/metrics/pod/controller.go#L135).  The PR address these leaks and contains more information on the memory performance during reproduction this leaks.

**Comment by jonathan-innis** [comment]
@gkalwig @vassilvk Did you observe that the memory leaks are resolved starting in v0.27.1?

**Comment by vassilvk** [comment]
Thank you for working on this and for the reminder @jonathan-innis!
We just deployed 0.27.1 to our clusters. Will keep an eye on the metrics and report back here in a week or so.

**Comment by gkalwig** [comment]
@engedaam @jonathan-innis, we needed more time to verify, but for now i can say we succeeded, well done :1st_place_medal: memory usage looks much better than before.

![image](https://user-images.githubusercontent.com/87004230/231753536-e89b50d2-1159-4455-b7f1-b56ce09f57d9.png)

**Comment by astralko** [comment]
I have installed 0.28.1 on two clusters. one is fine but the other one still has the issue
    Image:       public.ecr.aws/karpenter/controller:v0.28.1@sha256:66227007f8ebadd16da3095a4c966ab9cf56a90a9f71238f341404bbafb1acea
![image](https://github.com/aws/karpenter/assets/25593797/abd95448-35a1-438a-80d5-c4df6463b029)

**Comment by jonathan-innis** [comment]
@astralko Is it possible for you to [enable Pprof on your cluster](https://karpenter.sh/docs/contributing/development-guide/#profiling-memory) (you can do this by setting the `ENABLE_PROFILING` environment variable to `true` on the container) that is showing the memory leak and do a heap dump that we could investigate further? In the meantime, we are going to try to get a repro on our side. Re-opening if this is getting reported on the latest versions of Karpenter.

**Comment by astralko** [comment]
@jonathan-innis I am attaching files when it was around 16% mem usage, and files when it was 26% usage (around 10 minutes after)
[profile_10percent_more.pb.gz](https://github.com/aws/karpenter/files/11968329/profile_10percent_more.pb.gz)
[heap_10percent_more.txt](https://github.com/aws/karpenter/files/11968330/heap_10percent_more.txt)
[profile.pb.gz](https://github.com/aws/karpenter/files/11968331/profile.pb.gz)
[heap.txt](https://github.com/aws/karpenter/files/11968332/heap.txt)

**Comment by engedaam** [comment]
@astralko Would you be able to share a graph with the amount of memory that is being used and the number of nods/pods? Also, are seeing the memory usage growing with v0.29.0?

**Comment by astralko** [comment]
@engedaam sure. currently there are 10 nodes, but only 7 are managed by karpenter
![image](https://github.com/aws/karpenter/assets/25593797/13e0fe58-3097-4b86-8183-ec7466a27d0e)
[heap_19_7.txt](https://github.com/aws/karpenter/files/12091872/heap_19_7.txt)
@jonathan-innis 
now that it is on 90% percent, attaching the heap

**Comment by astralko** [comment]
@engedaam hi, I did something stupid and upgraded midweek :)
but 24 hours later, doesn't seem like the memory is leaking.
![image](https://github.com/aws/karpenter/assets/25593797/7d4a6a35-9153-42aa-9d20-abedf9c7cb80)

**Comment by engedaam** [comment]
@astralko What Karpenter version are you running?

**Comment by jonathan-innis** [comment]
> now that it is on 90% percent, attaching the heap

@astralko It looks like we might have solved the issue but would still be nice to view this heap. Can you attach the `.pb` file as well?

**Comment by jonathan-innis** [comment]
@astralko Also, I know you've lost the repro, but it would also be good to see the `container_file_descriptors` metric on the problematic version since this memory leak might be linked to #4296
