### ISSUE TITLE
Why is the aws node templates CRD in the karpenter CRDs chart, but not the provisioner CRD?

### ISSUE THREAD

**Issue by paul-civitas** [aws/karpenter#3210]
### Is an existing page relevant?

https://github.com/aws/karpenter/tree/main/charts/karpenter-crd

### What karpenter features are relevant?

Installation

### How should the docs be improved?

The CRD helm chart isn't even documented

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
The chart directory you referred to is still work in progress and should be completed soon. The provisioner CRD will become part of a chart that comes from karpenter-core, that's why it's not there.
