### ISSUE TITLE
Allow to select instance types by in-transit encryption support

### ISSUE THREAD

**Issue by wkaczynski** [aws/karpenter#3216]
### Tell us about your request

We'd like to be able to specify in provisioner's requirements as well as in pod's nodeSelector and affinity whether I'm only interested in instance types that support the in-transit encryption (not the same set as instance types with nitro hypervisor). 

Added a PR with possible solution: https://github.com/aws/karpenter/pull/3213

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

For selected (more secure) environments we have compliance requirements regarding used encryption for the traffic between instances.

### Are you currently working around this issue?

Currently the only way to achieve this is to limit to instance types listed here (and try to be up-to-date with any changes): https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/data-protection.html#encryption-transit
(note that the rules are not very clear and depend not only on family but also on generation)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
I'm happy to support this. Thanks for the PR.

**Comment by tzneal** [comment]
Fixed in https://github.com/aws/karpenter/pull/3213
