### ISSUE TITLE
Karpenter Nodes Not Ready Error

### ISSUE THREAD

**Issue by kumarvedavyas** [aws/karpenter#3218]
### What karpenter features are relevant?

Hi Team, I have an EKS cluster running in AWS. I'm facing an issue when Karpenter is trying to provision nodes. Karpenter is able to create nodes, but those nodes are in not-ready status. 
Below is the node template file:
resource "kubectl_manifest" "karpenter_node_template" {
  count     = var.deploy_karpenter ? 1 : 0
  yaml_body = <<-YAML
    apiVersion: karpenter.k8s.aws/v1alpha1
    kind: AWSNodeTemplate
    metadata:
      name: default
    spec:
      subnetSelector:
        karpenter.sh/discovery: "${aws_eks_cluster.eks_cluster.name}"
      securityGroupSelector:
        karpenter.sh/discovery: "${aws_eks_cluster.eks_cluster.name}"
      tags:
        karpenter.sh/discovery: "${aws_eks_cluster.eks_cluster.name}"
  YAML

  depends_on = [
    helm_release.helm_karpenter
  ]
}
Logged into the node and checked for the logs:
Error getting node" err="node \"ip-192-168-67-130.ec2.internal\" not found
Failed to contact API server when waiting for CSINode publishing: Unauthorized
I'm following this doc to resolve the issue but didn't help: https://karpenter.sh/preview/troubleshooting/#node-notready

### How should the docs be improved?

https://karpenter.sh/preview/troubleshooting/#node-notready

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
This occurs when your node doesn't have permission to talk to the API server.  On the doc you linked, did you check the aws-auth configmap to ensure the Karpenter node role is listed:

```
kubectl get configmaps -n kube-system aws-auth -o yaml
```

**Comment by kumarvedavyas** [comment]
Thanks for the info @tzneal
It worked by changing the appropriate role
I have one doubt, when I implement the Karpenter, will Karpenter in the background edit aws-auth configmap or do I need to do it manually?

**Comment by tzneal** [comment]
No, it's performed as part of the getting started guide here: https://karpenter.sh/v0.22.1/getting-started/getting-started-with-eksctl/#grant-access-to-nodes-to-join-the-cluster
