### ISSUE TITLE
Host Port Configuration

### ISSUE THREAD

**Issue by jtgorny** [aws/karpenter#3222]
### Problem
IF [aws-load-balancer controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) is already present in a single node EKS cluster, Karpenter fails to startup and stays in a pending state with the error:
```
Warning  FailedScheduling  33s (x6 over 3m55s)  default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.
```
This is because host port 8080, which is the port Karpenter expects to bind http-metrics to, is already in use by the aws-load-balancer controller metrics-server. This is currently not configurable in either open-source project. 

### Workaround
Option 1: Allow Karpenter to come online before the alb controller. 
Option 2: Scale down alb controller to 0 to allow Karpenter to bind to port 8080 first, then allow Karpenter to recognize the alb controller as unschedulable and scale out accordingly.

### Solution
Allow the host port to be configurable with something like:
```
controller:
  env:
  - name: METRICS_PORT
    value: "8088"
  - name: HEALTH_PROBE_PORT
    value: "8089"
```
https://github.com/aws/karpenter-core/blob/main/pkg/operator/options/options.go#L59

### How should the docs be improved?

Troubleshooting guide could be improved to include a note on this subject until the host port becomes configurable.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by igor-nikiforov** [comment]
I have exactly same issue with karpenter when trying to deploy it with host mode on the same nodes where ALB controller resides. 

> I'm confused. You can currently set this with env vars.
To be honest this does not work for some reason. I tried to did the similar settings before:

```yaml
controller:
  env:
  - name: METRICS_PORT
    value: "8188"
  - name: HEALTH_PROBE_PORT
    value: "8189"
```

And it didn't helped. Moreover these ports just hardcoded in chart https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/deployment.yaml#L88-L93.

**Comment by igor-nikiforov** [comment]
@jtgorny forgot to add that I ended up with set `metricsBindAddr: ":8180"` on ALB controller chart and was able to successfully deploy karpenter on the same nodes as ALB.

**Comment by ellistarn** [comment]
> I have exactly same issue with karpenter when trying to deploy it with host mode on the same nodes where ALB controller resides.
> 
> > I'm confused. You can currently set this with env vars.
> 
> @ellistarn To be honest this does not work for some reason. I tried to did the similar settings before:
> 
> ```yaml
> controller:
>   env:
>   - name: METRICS_PORT
>     value: "8188"
>   - name: HEALTH_PROBE_PORT
>     value: "8189"
> ```
> 
> And it didn't helped. Moreover these ports just hardcoded in chart https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/deployment.yaml#L88-L93.

Good point. You need to both set the pod port and the env var. Happy to accept a pull request on this.

**Comment by jtgorny** [comment]
Thanks for that @igor-nikiforov , setting the `metricsBindAddr` on the ALB controller worked for me. I must've missed this when skimming the docs initially as I opened this ticket under the impression this wasn't configurable on either project!

I do still think it would be convenient to configure this on Karpenter as well ¯\_(ツ)_/¯

**Comment by igor-nikiforov** [comment]
@ellistarn @jtgorny PR for this issue is already opened https://github.com/aws/karpenter/pull/3119. Hope it will be merged soon.

**Comment by ellistarn** [comment]
Needs a rebase, I think.
