### ISSUE TITLE
Getting started with eksctl cloudformation yaml missing for karpenter version 0.19.3

### ISSUE THREAD

**Issue by RobertNorthard** [aws/karpenter#3247]
### Version

N/A

### Expected Behavior

https://karpenter.sh/v0.19.3/getting-started/getting-started-with-eksctl/cloudformation.yaml to return the clouformation.yaml

### Actual Behavior

Returns 404

### Steps to Reproduce the Problem

Follow steps to install Karpenter as part of the EC2 spot workshop here: https://ec2spotworkshops.com/karpenter/050_karpenter/set_up_the_environment.html

### Resource Specs and Logs

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
The file is still in the repo, but no longer on the docs site.  I created a PR at https://github.com/awslabs/ec2-spot-workshops/pull/233 to update the version info there.

**Comment by RobertNorthard** [comment]
Thank you, I was just testing the latest version in the workshop and creating a PR.
