### ISSUE TITLE
Migrating from Cluster Autoscaler - quick doc correction

### ISSUE THREAD

**Issue by gotchipete** [aws/karpenter#3250]
This line:
```SECURITY_GROUPS=$(aws eks describe-cluster \
    --name ${CLUSTER_NAME} --query "cluster.resourcesVpcConfig.clusterSecurityGroupId")
```
I believe should change to:
```SECURITY_GROUPS=$(aws eks describe-cluster \
    --name ${CLUSTER_NAME} --query "cluster.resourcesVpcConfig.clusterSecurityGroupId" --output text)
```
... otherwise the following `aws ec2 create-tags` command chokes with 

`An error occurred (InvalidID) when calling the CreateTags operation: The ID '"sg-12345"' is not valid`

MacOS Ventura 13.1

**Comment by ellistarn** [comment]
Do you mind adding this to https://github.com/aws/karpenter/tree/main/website/content/en/preview?
