### ISSUE TITLE
Metrics collection does not work correctly with the default AWS EC2 metadata options for AWS Node Templates

### ISSUE THREAD

**Issue by snorlaX-sleeps** [aws/karpenter#3254]
### What karpenter features are relevant?

AWS Node Templates

### How should the docs be improved?

Unsure if the docs need improved as this is probably related to certain types of metrics collection: specifically adding tags to any metrics generated in a cluster, on a node created by an AWS Node Template, using Datadog, but it may affect other users.

Opening this issue for future searchers more than anything, it can probably just be closed.

When using the default metadata options suggested by the [AWS Node Template documentation](https://karpenter.sh/preview/concepts/node-templates/#specmetadataoptions), access to the IMDS from the host is restricted. In our use case this stopped all metrics generated in the cluster from being tagged, making them unavailable for graphing / monitors.
Setting the following resolved the issue - this way the other suggested security defaults should be used.

```
spec:
  metadataOptions:
    httpTokens: optional
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
Thanks for opening the ticket, if this becomes a repeated issue we may consider adding a FAQ entry for it.
