### ISSUE TITLE
Support scheduling of scale operations

### ISSUE THREAD

**Issue by timrafay** [aws/karpenter#3295]
### Tell us about your request

Add the ability for users to define schedules which control scale operations.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Users want the ability to schedule scale operations based off of set schedules.  As an example, at 5PM users leave for the day and the node count can be scaled down to 0 to allow for cost savings while compute resources are not required.  At 7AM, the cluster can scale back up and allow users the compute needed.

### Are you currently working around this issue?

Using automation or manually scaling node count

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Have you looked into https://keda.sh/docs/2.9/scalers/cron/? You can hook up a cronscaler to your pods, which will reactively scale out additional capacity. If your workloads don't exist yet, you can define negative preemption pause pods to inflate the cluster, which will be preempted when the real workload pods come in.

**Comment by arusahni** [comment]
Is this a duplicate of #1302?
