### ISSUE TITLE
Enable usage of fpga instance-types (f1 family)

### ISSUE THREAD

**Issue by isaaguilar** [aws/karpenter#3305]
The following snippet explicitly filters out FGPA instance types from the available list of instance-types. I was wondering if we can remove this filter or somehow make it user-configurable. 
https://github.com/aws/karpenter/blob/1f92a4fa221eea1e3b39d27fdeb2622b59dd794c/pkg/cloudprovider/instancetypes.go#L243-L246

**Comment by bwagner5** [comment]
Merged pending release in v0.24.0
