### ISSUE TITLE
Support `hugepages-2Mi` resource type

### ISSUE THREAD

**Issue by DanielJuravski** [aws/karpenter#3315]
### Tell us about your request

Support `hugepages-2Mi` resource type. 

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I need to apply various workloads that should allocate different values for `hugepages-2Mi` resource type.
```
resources:
  limits:
    habana.ai/gaudi: 8
    hugepages-2Mi: "21000Mi"
    memory: 50Gi
  requests:
    habana.ai/gaudi: 8
    hugepages-2Mi: "21000Mi"
    memory: 50Gi
```
The main instance type I'm using is dl1.24xlarge - it doesn't support `hugepages-2Mi` resource type https://karpenter.sh/v0.22.1/concepts/instance-types/#resources-148 (none of the Karpenter's instances types do). 
Thus I can't apply workload with custom `hugepages-2Mi` value.

### Are you currently working around this issue?

No

### Additional Context

The message from Karpenter log when it does not work:

```
Failed to schedule pod, incompatible with provisioner "gaudi", no instance type satisfied resources
{"cpu":"24","_[_habana.ai/gaudi":"8","hugepages-2Mi":"21000Mi","pods":"1_|http://habana.ai/gaudi":"8","hugepages-2Mi":"21000Mi","pods":"1]_"}
and requirements_ [kubernetes.io/os](http://kubernetes.io/os) In [linux], karpenter.sh/capacity-type In [on-demand], [node.kubernetes.io/instance-type](http://node.kubernetes.io/instance-type) In [dl1.24xlarge], karpenter.k8s.aws/instance-family In [dl1], [habana.ai/gaudi](http://habana.ai/gaudi) In [true], karpenter.sh/provisioner-name In [gaudi], [kubernetes.io/arch](http://kubernetes.io/arch) In [amd64]
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
I'm not too familiar with huge pages. Is this set for all nodes, or only under some settings?

**Comment by DanielJuravski** [comment]
All nodes,
> For Linux workloads, you can specify huge page resources. Huge pages are a Linux-specific feature where the node kernel allocates blocks of memory that are much larger than the default page size.

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-types
https://aws.amazon.com/premiumsupport/knowledge-center/configure-hugepages-ec2-linux-instance/

**Comment by jonathan-innis** [comment]
We're tracking extended resources as part of #1900. I'd recommend +1-ing that issue. Closing this as a duplicate.
