### ISSUE TITLE
ERROR   controller.provisioner  creating scheduler, getting instance types, no subnets matched selector map

### ISSUE THREAD

**Issue by mikaelboto** [aws/karpenter#3341]
### What karpenter features are relevant?

I am facing the following error when trying to start the inflate procedure in karpenter:

`2023-02-02T12:45:34.945Z        ERROR   controller.provisioner  creating scheduler, getting instance types, no subnets matched selector map[karpenter.sh/discovery:karpenter-argocd]    {"commit": "5a7faa0-dirty"}`

Subnets: 
Subnets already tagged correctly
```
,
            "Tags": [
                {
                    "Key": "Name",
                    "Value": "SubNet-1a-priv-vpc-karpenter-argocd"
                },
                {
                    "Key": "tag-key",
                    "Value": "karpenter.sh/discovery"
                },
                {
                    "Key": "karpenter.sh/discovery",
                    "Value": "demo"
                }
            ],
```

### How should the docs be improved?

Nothing

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@mikaelboto From the output you are showing above, it doesn't look like the tags that you have on that subnet match the selector that is showing up in the log. You would need a tag like the one below to match what you have selected.

```json
 {
       "Key": "karpenter.sh/discovery",
       "Value": "karpenter-argocd"
}
```
