### ISSUE TITLE
How to remove "name" tag or customize it dynamically?

### ISSUE THREAD

**Issue by cep21** [aws/karpenter#3342]
### What karpenter features are relevant?

labels and tags.

### How should the docs be improved?

Rather than spin up ec2 instances with a static EC2 tag name of the provisioner, it would be really useful if the EC2 tag name matched the node's name, which is currently the private IP for us in EKS.  Is this possible?  It may require karpenter to update the name after the node is provisioned.

If it is not, is it possible to just not tag the node's name at all?  We currently use datadog that automatically imports EC2 tags into metric tags, but aren't getting much use out of `name` since they all have the same name tag.

Thanks!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
>If it is not, is it possible to just not tag the node's name at all?

If Karpenter had to tag the instance with something, what would you prefer it to be? We have [this proposal](https://github.com/aws/karpenter/blob/main/designs/node-ownership.md) that is in the works and one of the thoughts is to tag the instances that would be launched with the machine name, which we could know ahead of time.

**Comment by cep21** [comment]
> what would you prefer it to be

Whatever shows up when I type `kubectl get nodes` is my preference.  I don't particularly care what the node names are, but do prefer the `kubectl` and EC2 UI match.

**Comment by pincher95** [comment]
Or resource id would be also great

**Comment by ellistarn** [comment]
Resource Based Naming https://github.com/aws/containers-roadmap/issues/1723#issuecomment-1217343633 causes node name and instance id to converge. EC2 name tag is another thing entirely. It's a bit redundant to have a name tag == instance id. The other challenge is that the instance id isn't known until the instance is created, so the tagging would have to happen later, creating reconciliation / atomicity challenges. Possible, just work to deal with.
