### ISSUE TITLE
How Does Drift Detection work with AWS Node Templates when not setting an AMI?

### ISSUE THREAD

**Issue by snorlaX-sleeps** [aws/karpenter#3344]
### Is an existing page relevant?

https://karpenter.sh/v0.23.0/concepts/deprovisioning/#drift

### What karpenter features are relevant?

- Drift Detection Feature Gate
- AWS Node Template AMI Selection

### How should the docs be improved?

The documentation is not clear about how drift detection works with AWS Node Templates whenever the AMI is not selected.

When setting the AMI Family, the documentation states that:
> "Karpenter will automatically query for the appropriate [EKS optimized AMI](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-amis.html) via AWS Systems Manager (SSM)"

This implies that when an AWS Node Template is created it will lookup the latest AMI, but it fails to mention how often this is checked.
When does Karpenter query for the latest AMI?
Is it when a new node is started (ensuring the latest node is up to date) or is it periodically?
When this check occurs (if it does) and a new AMI is available, will Karpenter will mark all existing nodes that use that AWS Node Template as "drifted"?

Drift when the AMI is set or queried is clear, it's just in the case where this is left up to Karpenter that is unclear

Thanks

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Karpenter will check for a new AMI every 5 minutes or when the AWSNodeTemplate has changed. 

Karpenter will mark a node if it's AMI does not match the AMI that's resolved from the AWSNodeTemplate. It will keep checking any time that setting might change or every 5 minutes. Am I answering the question? 

https://github.com/aws/karpenter-core/blob/main/pkg/controllers/node/drift.go marks nodes as drifted and the deprovisioning controller will query for nodes with that annotation and deprovision them. https://github.com/aws/karpenter-core/blob/main/pkg/controllers/deprovisioning/controller.go

**Comment by snorlaX-sleeps** [comment]
Thats great, thank you for the info @njtran - we've got a bit of a roll / migration to do in several clusters and knowing this will help me reassure people that enabling the feature is a good idea.
