### ISSUE TITLE
Feature: Support Pre and Post EKS Bootstrap Userdata with AWS Node Templates

### ISSUE THREAD

**Issue by snorlaX-sleeps** [aws/karpenter#3346]
### Tell us about your request

Requesting a change / update for AWS Node Templates to allow providing Userdata that should be run **after** the `/etc/eks/bootstrap.sh` script which configures the node to join the cluster - not just before, as is currently supported.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

[Memory Manager](https://kubernetes.io/blog/2021/08/11/kubernetes-1-22-feature-memory-manager-moves-to-beta/) is a new feature-gate available in K8s > v1.22.
This requires setting the total reserved memory for the system and kubelet to allow Kubernetes to better allocate memory for pods.
When the bootstrap script is run, it generates a lot of node and Kubernetes information to be used by the system, which is inserted in the`kubelet-config.json`.

These values can then be used for calculating the total reserved memory (which is particular to the current instance size) without needing to do calls to IMDS and figuring out how much memory is required for pods.

However this information is not available until after the bootstrap script is executed - which is now handled by the AWS Node Template / Karpenter after all user input has been completed.

### Are you currently working around this issue?

We have written a python script embedded in the Node Template Userdata that emulates the functionality of `/etc/eks/bootstrap.sh` to calculate `systemReserved` and `kubeReserved` memory values, using data from IDMS and `/etc/eks/eni-max-pods.txt` before then calculating the `reservedMemory` required for `memory-manager` to function.
This is then updated in the kubelet-config file.

### Additional Context

This is a new feature we are trying to use to improve memory management / usage, however historically as we were running `/etc/eks/bootstrap.sh` ourselves we could have just put this section after the bootstrap script and been able to pull the value pre-calculated from the file.

Being able to run code / userdata "post-bootstrap" would resolve the issue.
As more K8s features are added this may become more important (e.g if in the future we need to set CPU reservations in a similar way).

Similar to https://github.com/aws/karpenter/issues/3110 in that this involves a setting for the kubelet-config, however this value needs calculated for any instance that is created with the provisioner.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> Being able to run code / userdata "post-bootstrap" would resolve the issue.

How would this work since you would have to restart kubelet once it start up? It sounds like the data that you are trying to pass through is specified in the KubeletConfiguration so it needs to be used by the kubelet.

**Comment by snorlaX-sleeps** [comment]
Hey @jonathan-innis, yes it is - it's for configuring the memory-management settings for the node.
I was trying to think of the best way to do this, outside of writing a script to calculate the values in userdata.
The bootstrap script is what generates this information, so it seems like duplication of effort if it's going to exist anyway

**Comment by jonathan-innis** [comment]
> The bootstrap script is what generates this information, so it seems like duplication of effort if it's going to exist anyway

If we supported this, would you be ok with the fact that you would require a kubelet restart that you would have to implement in the userdata in order to pick-up the new settings?

**Comment by jonathan-innis** [comment]
For now, have you tried using a Custom AMI family where you specify the entirety of the userData including the bootstrap script, which would allow you to do post-rendering like you are proposing?

**Comment by bwagner5** [comment]
This seems to make more sense to be included directly within the eks bootstrap script itself. Have you opened an issue in https://github.com/awslabs/amazon-eks-ami ?

**Comment by snorlaX-sleeps** [comment]
I had not considered setting it to `CUSTOM` @jonathan-innis, we may try this - it would be more similar to what we were doing before with launch-templates so it should not be an issue.
Reading the docs "`CUSTOM`" made me think more of self-built AMIs rather than using AL2, but we should be able to get the same results using the AMI selectors (getting the latest AMI but with custom user-data).

@bwagner5 I am not sure if they would accept it - `systemReserved ` seems to be based on what agents / software is installed on the node and would vary between users / accounts / node groups, which could be why it is currently not set as part of the bootstrap script.
Calculating `reservedMemory` is then done afterwards - however it could calculate `reservedMemory` when a flag was passed and / or if `systemReserved` was set, so I will open an issue and ask about this.

Thanks for the info / workaround - I believe we can probably close this

**Comment by snorlaX-sleeps** [comment]
I see the documentation mentions [system reserved overrides](https://karpenter.sh/v0.23.0/concepts/provisioners/#reserved-resources), however these probably change on a node-size basis?
