### ISSUE TITLE
helm-chart inconsistent tag in default values.yaml for controller image

### ISSUE THREAD

**Issue by haarchri** [aws/karpenter#3347]
### Version

__Karpenter Version:__ v0.23.0

__Kubernetes Version:__ v1.22.0

### Expected Behavior

using v0.23.0 tag for v0.23.0 helm-chart https://github.com/aws/karpenter/blob/v0.23.0/charts/karpenter/values.yaml#L95

### Actual Behavior

any reason why the karpenter controller is running with v0.22.1 in the v0.23.0 release tag ?  https://github.com/aws/karpenter/blob/v0.23.0/charts/karpenter/values.yaml#L95

### Steps to Reproduce the Problem

.

### Resource Specs and Logs

.

### Community Note

https://kubernetes.slack.com/archives/C02SFFZSA2K/p1675239955473259

**Comment by spring1843** [comment]
This is because of the way we trigger our releases with a tag. The tag is assigned and pushed first and that triggers a build mechanism that then releases the application and then opens a PR with some changes including to the line you have mentioned.

It's something we can potentially fix by switching the timing of the merge of PR from tagging. Is this causing an issue for you @haarchri ?

**Comment by haarchri** [comment]
It's hard to understand which release is running - checking logs from Controller and you see an older version - but from helm-chart perspective it looks correct - we running hundreds of clusters with different base version for Karpenter because of staging concepts and it's hard to find out the current version

**Comment by spring1843** [comment]
>'s hard to understand which release is running - checking logs from Controller and you see an older version - but from helm-chart perspective it looks correct - we running hundreds of clusters with different base version for Karpenter because of staging concepts and it's hard to find out the current version

Not sure I understand how the two relate. The helm chart that you have used to install the running version should have the right version. Also you can get the running version by looking at what version the deployment is using. If you try to look at the karpenter version in the source code of a given tag though you are right, but that's not how you would normally check to see what version is running.

Changing this is going to require a restricting of how we have built our build system and it doesn't seem to be worth the effort at this point. We can revisit the problem again if it becomes a more common issue. Please feel free to reopen if you disagree.

**Comment by everythings-gonna-be-alright** [comment]
It's confused. When I select a tag, I expect to get the same version as in this tag.
Perhaps it would be better to remove the confusing versions from the values file in the git repository at all and set the image version only into the helm values file in ECR?
