### ISSUE TITLE
Custom RBAC

### ISSUE THREAD

**Issue by Kostavro** [aws/karpenter#3353]
### Tell us about your request

I would like to be able to add rules to the generated Role/ClusterRole resources, for example karpenter-core ClusterRole.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Installing datadog-agent sidecar container, it needs some extra cluster-wide permissions.

### Are you currently working around this issue?

Patching the ClusterRole resource.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@Kostavro This sounds reasonable to me. Would you be interested in opening a PR to add the relevant values to add the extra cluster role permissions to the helm chart?

**Comment by Kostavro** [comment]
> @Kostavro This sounds reasonable to me. Would you be interested in opening a PR to add the relevant values to add the extra cluster role permissions to the helm chart?

Hey @jonathan-innis ! Sure, will do :)
