### ISSUE TITLE
Will Karpenter fall back on lower weight provisioner in the absence of AWS instance capacity

### ISSUE THREAD

**Issue by vassilvk** [aws/karpenter#3378]
### Is an existing page relevant?

https://karpenter.sh/preview/concepts/scheduling/#weighting-provisioners

### What karpenter features are relevant?

Karpenter scheduling with multiple weighted provisioners.

### How should the docs be improved?

Consider the following situation:
- Karpenter is configured with two provisioners - ARM64 and AMD64
- The ARM64 provisioner has a higher `spec.weight` than the AMD64 provisioner
- A multi-arch workload is deployed to the cluster - pods can be scheduled on either ARM64 or AMD64 nodes

According to the documentation, using a higher weight on the ARM64 provisioner will lead to all the multi-arch pods that match that provisioner to be deployed to ARM64 nodes.
It is not clear what will happen in the event AWS runs out of ARM64 nodes in the region/zone where the pods are deployed.
Will Karpenter fall back to AMD64 or will it get stuck as it has already chosen the ARM64 provisioner based on weight?

The documentation does touch upon a similar case in section [Savings Plans and Reserved Instances](https://karpenter.sh/preview/concepts/scheduling/#savings-plans-and-reserved-instances), where it discusses a setup where Karpenter will fall back on a lower weighted provisioner once the higher weighted provisioner runs out of capacity defined through `.spec.limits`. This is different than what we are looking for, which is, what would Karpenter do if no `.spec.limits` are defined, but AWS runs out of the specific ARM64 instances required by the provisioner.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
> Will Karpenter fall back to AMD64 or will it get stuck as it has already chosen the ARM64 provisioner based on weight?

If there are no more ARM64 instance types available, Karpenter will fallback to the AMD64 provisioner.

**Comment by vassilvk** [comment]
Thank you @bwagner5. Closing the issue.
