### ISSUE TITLE
Add envFrom to container spec and expose in values file for use in proxy environments

### ISSUE THREAD

**Issue by jebbens** [aws/karpenter#3388]
### Tell us about your request

Add the envFrom property to the container spec in charts/karpenter/templates/deployments.yaml and expose that property in the charts/karpenter/values.yaml file.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Many of our customers route traffic through network proxies, which requires deploying a configMap with http_proxy environment variables in the cluster, and referencing that configMap in each container that is part of a deployment. Adding the envFrom property in the container spec and exposing it in the values file makes it easy for customers to use the upstream directly without having to maintain their own charts with that modification.

### Are you currently working around this issue?

I have made the changes suggested above, packaged the charts, and tested in an environment with a proxy. PR is ready to go, but I wanted to create the issue first and ask when submitting the PR, would this be a feat, docs, fix, etc.? It doesn't warrant updating a minor version , but I think updating the patch version would be appropriate even though it's not a "fix" in the purest sense.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Feel free to submit the PR, we can categorize it while reviewing the PR!

**Comment by jebbens** [comment]
https://github.com/aws/karpenter/pull/3394

**Comment by bwagner5** [comment]
Merged! Thanks!
