### ISSUE TITLE
Add one-line support for Karpenter to launch nodes configured for use with network proxy

### ISSUE THREAD

**Issue by jebbens** [aws/karpenter#3389]
### Tell us about your request

Add spec.proxy that would allow a customer to enter the URL of their network proxy and then Karpenter would automatically add the appropriate user data that will enable a node to join the cluster.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Many of our customers operate clusters behind a network proxy. This requires an additional layer of configuration on the worker nodes and pods. There is limited guidance on this process and it requires a LOT of time and troubleshooting to get it right. We typically provide launch templates for customers that include the necessary user-data, which can be used when cluster-autoscaler provisions new nodes via Autsocaling service. I am currently trying to use this same user-data in the AWSNodeTemplate for use with Karpenter, but it is not quite working. This gave me the idea that we could handle this undifferentiated heavy lifting for customers with a single property. OK, maybe two properties, e.g. spec.httpProxy and spec.noProxy.

### Are you currently working around this issue?

I have not solved this problem yet and I'm not sure why given that I'm using the same script I use for non-Karpenter launched nodes, e.g. the ones Karpenter is running on, and everything seems to be configured correctly. 

### Additional Context

  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    exec > >(tee /var/log/pre-user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
    set -x
    PROXY_URL="${outbound_proxy_url}"
    if [[ -n "$PROXY_URL" ]]; then
    # Set NO_PROXY_LIST
    EKS_IPv4_RANGE=${service_ipv4_cidr}
    VPC_CIDR=${vpc_cidr}
    if [[ "${cluster_endpoint_private_access}" == "true" ]]
    then EKS_ENDPOINT="eks.${dns_suffix}"
    fi
    NO_PROXY_LIST=$EKS_IPv4_RANGE,$VPC_CIDR,localhost,127.0.0.1,169.254.169.254,.internal,${no_proxy_endpoints},$EKS_ENDPOINT
    NO_PROXY_LIST=$(sed "s/,,/,/g" <<< "$NO_PROXY_LIST")
    NO_PROXY_LIST=$(sed "s/,$//" <<< "$NO_PROXY_LIST")

    # Set proxy for future processes
    cloud-init-per instance env_proxy_config cat <<EOF >> /etc/profile.d/set_proxy.sh
    export http_proxy="$PROXY_URL"
    export https_proxy="$PROXY_URL"
    export no_proxy="$NO_PROXY_LIST"
    export HTTP_PROXY="$PROXY_URL"
    export HTTPS_PROXY="$PROXY_URL"
    export NO_PROXY="$NO_PROXY_LIST"
    export AWS_DEFAULT_REGION="${region}"
    EOF

    # Create the Docker systemd directory
    mkdir -p /etc/systemd/system/docker.service.d

    # Configure Docker to use the proxy
    cloud-init-per instance docker_proxy_config tee <<EOF /etc/systemd/system/docker.service.d/http-proxy.conf >/dev/null
    [Service]
    Environment="HTTP_PROXY=$PROXY_URL"
    Environment="HTTPS_PROXY=$PROXY_URL"
    Environment="NO_PROXY=$NO_PROXY_LIST"
    EOF

    # Configure the kubelet with the proxy
    cloud-init-per instance kubelet_proxy_config tee <<EOF /etc/systemd/system/kubelet.service.d/http-proxy.conf >/dev/null
    [Service]
    Environment="HTTP_PROXY=$PROXY_URL"
    Environment="HTTPS_PROXY=$PROXY_URL"
    Environment="NO_PROXY=$NO_PROXY_LIST"
    EOF

    # Reload the daemon and restart Docker to reflect proxy configurations at launch of instance
    cloud-init-per instance reload_daemon systemctl daemon-reload
    cloud-init-per instance enable_docker systemctl enable --now --no-block docker

    # https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-proxy-with-ssm-agent.html#ssm-agent-proxy-systemd
    mkdir /etc/systemd/system/amazon-ssm-agent.service.d
    cat <<EOF >> /etc/systemd/system/amazon-ssm-agent.service.d/override.conf
    [Service]
    Environment="http_proxy=$PROXY_URL"
    Environment="https_proxy=$PROXY_URL"
    Environment="no_proxy=169.254.169.254"
    EOF

    systemctl daemon-reload && systemctl restart amazon-ssm-agent

    source /etc/profile.d/set_proxy.sh
    fi

    --BOUNDARY--

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
I think this would be better handled in the EKS Optimized AMI bootstrap script. What do you think about opening this issue in there since it isn't specific to Karpenter?  https://github.com/awslabs/amazon-eks-ami

**Comment by jebbens** [comment]
Good idea - I should have thought of that. Will do.

**Comment by jebbens** [comment]
On second thought, the proxy configuration has to run BEFORE the bootstrap.sh. So, it could be a file loaded on to the instance - like bootstrap.sh - but, I'm not sure how one would indicate that it should be run. Any ideas?

**Comment by bwagner5** [comment]
It should be placed before the actual node bootstrap steps within the bootstrap.sh script (so more towards the front of bootstrap.sh). bootstrap.sh has some other initialization steps as well.  If it can't be placed in the bootstrap script, I think the next best thing would be a separate script shipped with the eks-bootstrap script.

**Comment by ellistarn** [comment]
Is it possible to just configure this using `clusterEndpoint` in karpenter's settings configmap?

**Comment by jebbens** [comment]
> Is it possible to just configure this using `clusterEndpoint` in karpenter's settings configmap?

Unfortunately not - you have to configure the host, kubelet, docker, systems manager, etc. But, that's the simplicity I'd like to see us implement.

**Comment by jebbens** [comment]
> It should be placed before the actual node bootstrap steps within the bootstrap.sh script (so more towards the front of bootstrap.sh). bootstrap.sh has some other initialization steps as well. If it can't be placed in the bootstrap script, I think the next best thing would be a separate script shipped with the eks-bootstrap script.

Submitted an [issue](https://github.com/awslabs/amazon-eks-ami/issues/1182) to the amazon-eks-ami repo.

**Comment by ellistarn** [comment]
Closing in favor of that issue.
