### ISSUE TITLE
[Termination] Add test case for node termination w/ provisioner label changes

### ISSUE THREAD

**Issue by bwagner5** [aws/karpenter#341]
There was a bug fixed where nodes could be orphaned if the provisioner Labels section was updated. The check for the node labels to match the provisioner labels was removed in https://github.com/awslabs/karpenter/pull/338.  We should add additional tests for catching this type of node orphan scenario.

**Comment by njtran** [comment]
We no longer list nodes for every reconcile loop in a controller, so this is no longer relevant.
