### ISSUE TITLE
No nodes provisioned when spot service linked role is missing

### ISSUE THREAD

**Issue by fernandezcuesta** [aws/karpenter#3413]
### Version

__Karpenter Version:__ 0.24.0

__Kubernetes Version:__ v1.22.16

### Expected Behavior

When both spot and on-demand instances are set in the provisioner, Karpenter should provision on-demand when spot is not available.

### Actual Behavior

Even though provisioner has [spot, on-demand] values in the `karpenter.sh/capacity-type`, when the account is missing the spot service linked role no (neither spot or on-demand) instances are provisioned

### Steps to Reproduce the Problem

AWS account without `spot.amazonaws.com` service linked role created. Providerref containing the following requirement:

```
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
    - spot
```

### Resource Specs and Logs

```
 ERROR    controller.provisioner    launching machine, creating cloud provider instance, creating instance, with fleet error(s), AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.; UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.; launching machine, creating cloud provider instance, creating instance, with fleet error(s), AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.; launching machine, creating cloud provider instance, creating instance, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.; AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.; launching machine, creating cloud provider instance, creating instance, with fleet error(s), AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.; launching machine, creating cloud provider instance, creating instance, with fleet error(s), AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.; UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.; launching machine, creating cloud provider instance, creating instance, with fleet error(s), AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.; UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.    {"commit": "8c27519-dirty"}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
We intentionally don't fallback on auth error and instead report the auth error. Otherwise we risk only launching on demand capacity in accounts that are misconfigured.
