### ISSUE TITLE
Karpenter images running dirty commit

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#3414]
### Version

__Karpenter Version:__ v0.24.0

### Expected Behavior

Karpenter releases should run clean images. 

### Actual Behavior

v0.24.0 runs with `{"commit": "8c27519-dirty"}`

### Steps to Reproduce the Problem
```
helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version ${KARPENTER_VERSION} --namespace karpenter --create-namespace --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} --set settings.aws.clusterName=${CLUSTER_NAME} --set settings.aws.clusterEndpoint=${CLUSTER_ENDPOINT} --set settings.aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} --set settings.aws.interruptionQueueName=${CLUSTER_NAME} --wait
```
### Resource Specs and Logs

karpenter-5cc96cdff-djd6g controller 2023-02-17T18:16:57.342Z	INFO	controller.interruption	starting controller	{"commit": "8c27519-dirty"}

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
i've been seeing this for a while now in our clusters.

**Comment by bwagner5** [comment]
I inspected the release process before releasing v0.25.0 and it looked good, but alas after release the `-dirty` was still appended :( 

I thought this was fixed a while ago, but looking back here's what I found:
```
v0.25.0 -> {"commit": "beb0a64-dirty"}
v0.24.0 -> {"commit": "8c27519-dirty"}
v0.23.0 -> {"commit": "5a7faa0-dirty"}
v0.22.1 -> {"commit": "c4a4efd-dirty"}
v0.22.0 -> {"commit": "038d219-dirty"}
v0.21.1 -> {"commit": "06cb81f-dirty"}
v0.21.0 -> {"commit": "0c8536a-dirty"}
v0.20.0 -> {"commit": "f60dacd"}
v0.19.3 -> {"commit": "683d4b0"}
v0.19.2 -> {"commit": "470aa83"}
v0.19.1 -> {"commit": "27a51c0"}
v0.19.0 -> {"commit": "ea5dc14"}
v0.18.1 -> {"commit": "51becf8-dirty"}
v0.18.0 -> {"commit": "1d8eb34"}
v0.17.0 -> {"commit": "077c099-dirty"}
v0.16.3 -> {"commit": "5d4ae35-dirty"}
```

Going to look into what changed between v0.20.0 and v0.21.0
