### ISSUE TITLE
Zombie instance not terminated 

### ISSUE THREAD

**Issue by nirroz93** [aws/karpenter#3421]
### Version

__Karpenter Version:__ v0.21.1

__Kubernetes Version:__ v1.23

### Expected Behavior

Karpenter provisioned a node that never started (EC2 reachability check failed from the beginng). After 3 day, I manually terminated the node.

Node that doesn't join to the cluster after some timeout should be terminated automatically.

Side note -
I also noticed that CPU utilization of the cluster was low (more than expected impact) during this time, and improved significantly in the hour after it was terminated (also other provisioners which is weird). However, there was scaling down events during this time and I can't pinpoint the reason. Just mentioning here in case it make sense to find another bug (again, it was 3 days of low utilization that improved the hour after I manually terminated).

### Actual Behavior

Manual monitoring and termination is needed

### Steps to Reproduce the Problem

Get a node not to start due to some hardware issue (probably any issue, not just hardware)

### Resource Specs and Logs

Karpenter just logged using drift detection that it couldn't identify the type (not relevant, I can add later)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Closing in favor of #2021. @jonathan-innis FYI
