### ISSUE TITLE
Auto terminate unhealthy karpenter node

### ISSUE THREAD

**Issue by xinguaws** [aws/karpenter#3428]
### Tell us about your request

I would like Karpenter periodically check each ec2's health status and terminate it based on certain intervals if health check failed. 

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

For example, I had a node which was running fine but for some reason started failing where "reachability check failed", because pods running on it are stuck on terminating status, this node was never terminated by Karpenter, it would be nice to have such feature. similar to how AWS ASG works where unhealthy instances will be replaced  

### Are you currently working around this issue?

manually terminate those karpenter nodes

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Close in favor of #2021
