### ISSUE TITLE
[Documentation] Propose CAPI integration

### ISSUE THREAD

**Issue by JacobGabrielson** [aws/karpenter#343]
Per https://github.com/awslabs/karpenter/blob/main/docs/aws/provisioner-launch-templates-options.md (see open questions section at the end), need a proposal for how Karpenter will work with [CAPI](https://github.com/kubernetes-sigs/cluster-api).

**Comment by rosskukulinski** [comment]
Just noting the file was moved to https://github.com/aws/karpenter/blob/main/website/content/en/docs/AWS/launch-templates.md

**Comment by MMartyn** [comment]
Just curious about the plans or lack there of for this feature. Thanks.

**Comment by MMartyn** [comment]
Updating link location: https://github.com/aws/karpenter/blob/main/designs/aws-launch-templates-options.md#capi-integration
