### ISSUE TITLE
Pods scheduled to not-ready nodes

### ISSUE THREAD

**Issue by maximethebault** [aws/karpenter#3436]
### Version

__Karpenter Version:__ v0.25.0

__Kubernetes Version:__ v1.24

### Expected Behavior

Pods are only scheduled to nodes that are in a "Ready" state

### Actual Behavior

Pods are scheduled to nodes in a non-ready state, when the kubelet starts communicating with the API Server.

Details about the bug and potential cause: https://kubernetes.slack.com/archives/C02SFFZSA2K/p1677019487428879

### Steps to Reproduce the Problem

Start a pod, wait for Karpenter to provision a new node and observe when scheduling happens.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Thanks for filing this! As discussed in slack, the machine migration should be happening soon which will mitigate this issue. If there are any set backs on the machine migration timeline, we'll look into mitigating this another way within the current node creation logic.

**Comment by jonathan-innis** [comment]
As mentioned by @bwagner5, this issue should be solved and closed when the [Machine Migration](https://github.com/aws/karpenter/blob/main/designs/node-ownership.md) work is done and merged in

**Comment by jonathan-innis** [comment]
@maximethebault Have you been able to test out `v0.28.0-rc.1` and see if this resolves the behavior you were seeing. We are now no longer creating the node object before it actually joins the cluster so we shouldn't be scheduling to NotReady nodes anymore.

**Comment by maximethebault** [comment]
@jonathan-innis just tested it out, and after starting several dozens of pods, the issue seems to be gone indeed  🎉

From what I remember, this issue could be somewhat random. I'll keep a close look from next week and report here if I ever see this issue again with v0.28.0-rc.1. Thanks for the hard work!

**Comment by infa-msheik** [comment]
@maximethebault  I am seeing this issue v0.30.0
karpenter scheduling the pods on the Notready nodes

karpenter          Pod should schedule on: machine/consul-9pwrv, node/ip-10-15-10-190.ec2.internal

k get nodes | grep ip-10-15-10-190.ec2.internal
ip-10-15-10-190.ec2.internal   NotReady   <none>   3d20h   v1.24.13-eks-0a21954

I could see ec2 instance ip-10-15-10-190.ec2.internal failied instance statuscheck that made instanceNotReady.

**Comment by hobbsh** [comment]
@jonathan-innis Also seeing this on 0.30.0 on EKS v1.27
