### ISSUE TITLE
Support a ttlSecondsAfterClusterVersionUpdate

### ISSUE THREAD

**Issue by wpbeckwith** [aws/karpenter#3443]
### Tell us about your request

It would be real nice if Karpenter would drain and replace a node a configurable amount of time after a cluster upgrade.  We can use the ttlSecondsUntilExpired option but that leaves the cluster in an undeterministic state of how long our nodes can be off by one version.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

We prefer keeping our cluster version and nodes versions in sync as much as possible.  Once a cluster has upgraded from 1.22 to 1.23, we would like a provisioner to then cycle the nodes a configurable amount of time after it has noticed the cluster version has changed.

### Are you currently working around this issue?

Manually deleting the nodes, which allows Karpenter to drain and replace the node.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sidewinder12s** [comment]
Shouldn't AMI Drift handle this, since you must upgrade the AMI in use after upgrades to get the new cluster version binaries?

**Comment by wpbeckwith** [comment]
No this is different.  In our scenario we are not use an AWSNodeTemplate and are letting karpenter choose the lastest AMI for the cluster version, which it currently does.  We would like to be able to configure Karpenter to cycle nodes auto-magically X seconds after a cluster update.

**Comment by bwagner5** [comment]
Check out this RFC which proposes something similar. It's probably worth covering this slightly different use-case in the same design. https://github.com/aws/karpenter/pull/3356

**Comment by njtran** [comment]
> No this is different. In our scenario we are not use an AWSNodeTemplate and are letting karpenter choose the lastest AMI for the cluster version, which it currently does. We would like to be able to configure Karpenter to cycle nodes auto-magically X seconds after a cluster update.

Hey @wpbeckwith I agree with @sidewinder12s, this sounds like AMI Drift. Karpenter checks the latest AMI for a cluster version, so if your cluster version updates, then AMI Drift should notice that these nodes are on the drifted AMI. The TTL that you're requesting sounds like a Drift TTL, but instead of a Drift TTL, I am suggesting a Node Disruption Gate as the solution. This wouldn't be a TTL, but is time-based deprovisioning block. More [here](https://github.com/aws/karpenter-core/pull/207/files).

**Comment by wpbeckwith** [comment]
The AMI drift does work, once I figured out how to enable it. The sorta issue is that it does it as soon as it detects the version change.  In general this may not be a problem, but this means we will have the manage node group we use to initialize the cluster with compute capacity and the Karpenter nodes both churning at the same time.   We would prefer to delay Karpenter until the MNG finishes or at least mostly done.  Again this may only be an issue in our perceptions of reality.  I'm ok with this issue being closed as a dupe.

**Comment by Constantin07** [comment]
Slightly off topic - does anyone use AMI drift in production ? or it's just enabled/tested in development before rolled out to prod ?

**Comment by njtran** [comment]
@wpbeckwith thanks for the information! We're working on [Machine Disruption Gates](https://github.com/aws/karpenter-core/pull/221) (sort of like an inverse maintenance window) to let people have more controls over situations like those. Would love to get your eyes on the RFC [here](https://github.com/aws/karpenter-core/pull/207/files) for that. 

I'll close the issue as a duplicate. Thanks!

@Constantin07 you should ask in #1738 or in the K8s slack! I think you'll be able to reach a larger audience there.
