### ISSUE TITLE
Migrate Custom Async Reconcile Flows to Controller-Based Reconcile Flows

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter#3459]
### Tell us about your request

Both the [Pricing Provider](https://github.com/aws/karpenter/blob/08949e35ef9d493d5c8346acd43d598353eebd69/pkg/providers/pricing/pricing.go#L124) and the [Launch Template Provider](https://github.com/aws/karpenter/blob/08949e35ef9d493d5c8346acd43d598353eebd69/pkg/cloudprovider/launchtemplate.go#L78) have custom async reconcile flows to hydrate their caches on startup. In the pricing provider's case, it continually refreshes the cache.

This seems like a great fit for a standard `Reconcile` flow with the [`NewSingletonManagedBy`](https://github.com/aws/karpenter-core/blob/2fe0c7634cc43cc0321abf0a020c570400eee6e3/pkg/operator/controller/singleton.go#L38) singleton controller to reconcile and register similar to a standard controller. This unification will make the code easier to parse for new users.

An example of a similar "Singleton Controller" can be found [here](https://github.com/aws/karpenter/blob/08949e35ef9d493d5c8346acd43d598353eebd69/pkg/controllers/interruption/controller.go#L84).

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

N/A

### Are you currently working around this issue?

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Launch Provider Template will not need to be updated to a singleton controller as the provider only updates at creation.
