### ISSUE TITLE
Control Pod Density

### ISSUE THREAD

**Issue by praseedasathaye** [aws/karpenter#3461]
In this page https://karpenter.sh/v0.25.0/concepts/pod-density/, under the Dynamic Pod Density section, the link to [Provisioner API Kubelet Configuration](https://karpenter.sh/v0.25.0/provisioner/#pods-per-core) is broken.

**Comment by bwagner5** [comment]
Thanks for reporting! Should be fixed in https://github.com/aws/karpenter/pull/3464
