### ISSUE TITLE
Add provisioner to karpenter_deprovisioning_actions_performed metric

### ISSUE THREAD

**Issue by liorfranko** [aws/karpenter#3466]
### Version

__Karpenter Version:__ v0.23.0

__Kubernetes Version:__ v1.24.8-eks-ffeb93d

### Expected Behavior

When consolidation is done, we would like to know which provisioner it was done.

### Actual Behavior

The metric `karpenter_deprovisioning_actions_performed` shows that total consolidation of the cluster.the

### Steps to Reproduce the Problem

None

### Resource Specs and Logs

None

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by abirsigron** [comment]
This is really important in order to have spot interruption visibility when using karpenter for handling node termination.
Please add provisioner name also to this metrics: 
karpenter_interruption_received_messages
karpenter_interruption_actions_performed

**Comment by jonathan-innis** [comment]
@abirsigron Would you be interested in adding these metrics into the code-base? I think it would be fairly straight-forward and we always welcome new contributors!

**Comment by sbhrule15** [comment]
@engedaam are you working on this? if not, I'd like to work on this as my first contribution to the Karpenter project!

**Comment by sbhrule15** [comment]
@jonathan-innis looking at my karpenter installation of the latest version, I actually already see these metrics, and it looks like they are in the repo. Should this be closed?

https://github.com/aws/karpenter/blob/main/pkg/controllers/interruption/metrics.go#L36

**Comment by liorfranko** [comment]
@sbhrule15 
The purpose of this PR is to add a provisioner label to the existing metrics:
karpenter_interruption_received_messages
karpenter_interruption_actions_performed

**Comment by jonathan-innis** [comment]
@liorfranko Yes, the purpose was to add it to the interruption metrics as you mentioned as well as to update the [Deprovisioner Metrics](https://github.com/aws/karpenter-core/blob/main/pkg/controllers/deprovisioning/metrics.go) to add the provisioner label to some of these metrics (where it makes sense) as well.

**Comment by jonathan-innis** [comment]
Happy to assign you @sbhrule15. We are looking for the `provisioner` label in the [interruption metrics](https://github.com/aws/karpenter/blob/main/pkg/controllers/interruption/metrics.go) and the [deprovisioning metrics](https://github.com/aws/karpenter-core/blob/main/pkg/controllers/deprovisioning/metrics.go) similar to https://github.com/aws/karpenter-core/pull/210

**Comment by sbhrule15** [comment]
Sounds good! And yes, my apologies, I definitely misred the original comment. Thanks!

**Comment by sbhrule15** [comment]
@jonathan-innis I'm almost positive the changes I have are what's needed, but trying to confirm locally. I apologize if these have been addressed but I couldn't find any docs outside of the normal setup docs (if there are docs for this, please lmk)

1. Is AWS mocked anywhere in the local setup so I can run this via minikube outside of the test suite?
2. Is there a way to simulate the karpenter events manually?

If not I can setup a quick cluster in AWS but if I can run all of this from minikube on my machine I can get this done faster. Thanks!

**Comment by jonathan-innis** [comment]
@sbhrule15 Me and @njtran were thinking about this one a bit more and thinking that `karpenter_nodes_terminated` should already capture this with the _reason_ and _provisioner_ labels. Are you able to use those metrics to capture the information that you are proposing in this issue?

From what I can tell, it doesn't always make sense to assign a provisioner to a deprovisioning action, since that action may occur across provisioners and it may also capture more than one machine.

**Comment by sbhrule15** [comment]
I would think that would be enough information to just sum on those labels on `karpenter_nodes_terminated`, but that's a question likely better suited to @liorfranko.

@liorfranko - is this approach doable, of group summing on the labels on karpenter_nodes_terminated instead of duping the info to the deprovisioning action?

**Comment by liorfranko** [comment]
@jonathan-innis I'm okay with using the `karpenter_nodes_terminated,` but if so, I'm not sure I understand what changes you're suggesting.
`karpenter_nodes_terminated` already has the `provisioner`

This is what we're trying to achieve:
We're building a dashboard that shows the Spot interruptions and consolidations on a cluster.

We can either work with `karpenter_nodes_terminated{reason="consolidation/delete"}` and `karpenter_nodes_terminated{reason="interruption"}`

Or with `karpenter_deprovisioning_actions_performed` and `karpenter_interruption_actions_performed`

**Comment by jonathan-innis** [comment]
> I'm not sure I understand what changes you're suggesting

I'm not recommending any changes. My thought was that we can probably achieve what you are wanting already today.

> We can either work with...

I'd recommend that you work with the `karpenter_nodes_terminated` metrics as you mentioned and use that to get the dashboards you want.

**Comment by liorfranko** [comment]
Sure, we'll use `karpenter_nodes_terminated`.
