### ISSUE TITLE
Karpenter to use internal kubernetes endpoint

### ISSUE THREAD

**Issue by anwoolterton** [aws/karpenter#3470]
Would it be possible for karpenter to utilize the in-cluster endpoint (default.svc.cluster.local) for api calls to avoid unnecessary egress and loop back problems when communicating to EKS endpoint.

We occasionally see TLS errors when communicating to EKS endpoints in the karpenter logs this is on different account so this looks to be generic.

Let me know if there is any further information needed.

**Comment by ellistarn** [comment]
You can't rely on this endpoint at the node level, since the node (kube-proxy) can't resolve kube-dns until it's able to communicate with the API Server. It's a bootstrapping problem, so we use the cluster endpoint to connect instead.

**Comment by ellistarn** [comment]
Feel free to reopen if you have further questions.
