### ISSUE TITLE
Getting Started with Karpenter

### ISSUE THREAD

**Issue by jansony1** [aws/karpenter#3481]
Can we provide a separated getting started guide for installing Karpenter on existing EKS cluster, otherwise customer need spends lots of time on the initialization

**Comment by tzneal** [comment]
If you have a cluster already, you can follow the getting started guide and just modify the instructions to match your cluster.

**Comment by chrisnegus** [comment]
I agree that's a good place to start for now. But I'm working on a "bring-your-own-cluster" Karpenter getting started guide. I'm going to try to devote some time to it this week.
