### ISSUE TITLE
Docs script conflict

### ISSUE THREAD

**Issue by tzneal** [aws/karpenter#3510]
### Version

__Karpenter Version:__ v0.26.0

### Description

The eksctl getting started guide embeds `step02-create-cluster.sh` which also has the Helm install.  There is a separate Helm install command for Karpenter at `step08-apply-helm.sh`, which is referenced from the FAQ. 

- The two scripts have different content.
- Some of the other scripts aren't referenced anywhere currently (e.g. step04-grant-access.sh)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mbevc1** [comment]
Seems `step04-grant-access.sh` is referenced in `getting-started/getting-started-with-eksctl/scripts/add-roles.sh` which is used in Makefile :wink:
