### ISSUE TITLE
Multiple errors on 'Migrating from Cluster Autoscaler' tutorial

### ISSUE THREAD

**Issue by davivcgarcia** [aws/karpenter#3517]
We found multiple erros when executing the tutorial:

- At section of [Update aws-auth ConfigMap](https://karpenter.sh/v0.26.0/getting-started/migrating-from-cas/#update-aws-auth-configmap), the tutorials adds an mapping to IAM Role named `KarpenterInstanceNodeRole` instead of `KarpenterNodeRole-${CLUSTER_NAME}`.

- At the section of [Create IAM roles](https://karpenter.sh/v0.26.0/getting-started/migrating-from-cas/#create-iam-roles), the command used to create the IAM EC2 Instance Profile misspelled the environment variable `ClusterName` and `CLUSTER_NAME`.

- At the section [Remove CAS](https://karpenter.sh/v0.26.0/getting-started/migrating-from-cas/#remove-cas), it makes an assumption that EKS is using a single Managed Node Group. It would be nice to have an option to loop over the list `$NODEGROUP` environment variable.

I'll send a PR to address those. ☺️

**Comment by ellistarn** [comment]
We're currently rewriting this guide to be more focused on migration strategies, rather than specific commands, which are better suited to the getting started guide.

**Comment by davivcgarcia** [comment]
@ellistarn That's awesome! But don't you think it's valid to fix the current tutorial while the new one is not yet released? This would avoid problems with customers trying to migrate from CAS to Karpenter right now, and relying on official docs to do so.

**Comment by ellistarn** [comment]
Sure thing -- just wanted to let you know, so you didn't go do a bunch of work. Thanks for doing it though -- let's get it reviewed and merged.
