### ISSUE TITLE
How to detect Provisioner Failures

### ISSUE THREAD

**Issue by sidewinder12s** [aws/karpenter#3523]
### Is an existing page relevant?

Didn't fine one. 

### What karpenter features are relevant?

Is the amount of time that a karpenter will wait for a provisioner node to come up documented or configurable?

Does Karpenter kill nodes that fail to come up and try again?

Are there metrics for this?

It appears this is the only relevant metric, but I think it might be too verbose: `karpenter_provisioner_reconcile_errors_total`

Should probably have a metric per provisioner and maybe state a reason as a label?

### How should the docs be improved?

Document the above

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
There is an issue at https://github.com/aws/karpenter/issues/2021 that discusses some in-flight work for handling nodes that never go ready better.

**Comment by sidewinder12s** [comment]
Excellent, had missed those issues around how it behaves. I think this is probably still a needed bit of docs around more metrics & documentation on how Provisioners fail & how you can monitor for it.

**Comment by sidewinder12s** [comment]
Not stale

**Comment by jonathan-innis** [comment]
`v0.28.0-rc.2` (and soon `v0.28.0`) has a timeout that is hard-coded to 15m that should kill off nodes that don't register in a certain amount of time. We have the `karpenter_machines_terminated` metric with a label value `reason=liveness` that should give you the information you are wanting for metrics.

In terms of killing off nodes that do register to the cluster, but go into a NotReady state after coming up successfully or register but never go Ready, we are planning on expanding out this liveness through the #2021 feature that's on the roadmap.

**Comment by jonathan-innis** [comment]
I think the registration timeout should solve any issues that you have with the node never coming online. For issues related to the node going NotReady, we're going to track that through #2021. Closing this one.

**Comment by sidewinder12s** [comment]
Excellent I'll have to give 0.28 a try soon, haven't had time to give it a go yet.
