### ISSUE TITLE
podAntiAffinity missing from values.yaml in public.ecr.aws

### ISSUE THREAD

**Issue by flickers** [aws/karpenter#3526]
### Version

__Karpenter Version:__ v0.26.1

__Kubernetes Version:__ v1.25.6

podAntiAffinity block seems to be missing from the values file in public.ecr.aws
# -- Affinity rules for scheduling the pod.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: karpenter.sh/provisioner-name
              operator: DoesNotExist

### Expected Behavior

That the values.yaml file in this repository is the actual values.yaml file in public.ecr.aws
`helm dep up`
`helm template karpenter . -f values-from-github.yaml`
Produces
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/provisioner-name
                operator: DoesNotExist
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - '{{ .Release.Name }}'
              topologyKey: kubernetes.io/hostname
            weight: 100

### Actual Behavior

The values.yaml file in public.ecr.aws produces this
`helm dep up`
`helm template karpenter .`
Produces
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/provisioner-name
                operator: DoesNotExist

### Steps to Reproduce the Problem

`helm dep up`
`helm template karpenter .`

### Resource Specs and Logs

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Those changes were added yesterday and haven't been released yet.  https://github.com/aws/karpenter/commit/df17e150da00c23af16860bfaaeeef6044c558fe
