### ISSUE TITLE
FAQ: How to schedule full worker node shutdown

### ISSUE THREAD

**Issue by udhos** [aws/karpenter#3539]
### Is an existing page relevant?

https://karpenter.sh/v0.26.1/faq/

### What karpenter features are relevant?

Unsure.

### How should the docs be improved?

With managed node groups, one can schedule cron rules to automatically bring worker nodes up/down based on time.

In our staging environments, we rely heavily on that feature to deactivate all our worker nodes on non-working-hours.

What is the recommended approach to set a similar working time window for Karpenter?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
There are multiple ways, it depends on what works best for you:
- Add a zero CPU limit to provisioners, and then delete all nodes, remove the limit to re-enable provisioning
- Delete all provisioners and then re-create later, deleting provisioners will cause all nodes to be deleted
- Scale all workloads to zero, Karpenter will then delete the unused nodes

**Comment by udhos** [comment]
> * Add a zero CPU limit to provisioners (`.spec.limits`), and then delete all nodes, remove the limit to re-enable provisioning
> * Delete all provisioners and then re-create later, deleting provisioners will cause all nodes to be deleted
> * Scale all workloads to zero, Karpenter will then delete the unused nodes

In my specific case, I guess I can use the 2nd option with CloudWatch events plus Lambda function to delete/restore the provisioner.

Thanks for the directions, much appreciated!

As side notes:
- Should that recommendation be added to the FAQ document?
- Shouldn't karpenter add native support for time rules into the provisioner itself, in order to not depend on external mechanisms to enable/disable provisioners? Something like:
```
spec:
  activeHours:
    - weekDays: MON-FRI
      begin: 10h00
      end: 23h00
    - weekDays: SAT
      begin: 10h00
      end: 16h00
```

**Comment by jonathan-innis** [comment]
> Should that recommendation be added to the FAQ document?

Yes, if you would be open to submitting a PR that adds this guidance to the FAQ, we would happily accept it.

> Shouldn't karpenter add native support for time rules into the provisioner itself, in order to not depend on external mechanisms to enable/disable provisioners?

This conversation has come up among the maintainers related to the [Deprovsioining Controls and the Machine Disruption Gate RFC](https://github.com/aws/karpenter-core/pull/207). Right now there hasn't been a ton of ask for disabling provisioning natively beyond using the workaround mentioned above. If this is something that you are interested in, feel free to add some details on your use-case and the feature ask over in the [Machine Disruption Gate Issue](https://github.com/aws/karpenter/issues/1302)

**Comment by runningman84** [comment]
I would suggest to use the kube downscaler project to scale down everything. If karpenter itself runs in fargate everything should get up again flawlessly.

**Comment by ellistarn** [comment]
Closing in favor of https://github.com/aws/karpenter/issues/1302
