### ISSUE TITLE
Karpenter to notify when Spot Interruption occurs

### ISSUE THREAD

**Issue by hawkesn** [aws/karpenter#3552]
### Tell us about your request

This is similar to the Node Termination Handler feature where, given a URL, posts event data to the URL upon instance interruption action. 
We're currently using this to be notified via Slack when this happens.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Notifications for when an event occurs (ie. rebalance recommendation, spot interruption, etc.)

### Are you currently working around this issue?

Currently, we're still using NTH in `dryRun` mode set to `true` to monitor events.

### Additional Context

One possible option is to utilize the existing SQS queue to send a message to a webhook, however, the queue itself is populated for all events that may not pertain to the EKS cluster itself. For example, if I shutdown an EC2 instance not in the cluster, that event will also be sent to the queue and therefore the webhook.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
There's been some talk about building an event forwarder from the cluster to something like EventBridge so you could create rules that have the cluster context to forward onto some other event flow, like a Slack webhook. So the flow would look like:

1. EC2 service fires health information about an instance
2. The SQS gets that forwarded info and stores it in a message
3. Karpenter sees that message and fires a K8s even for the RebalanceRecommendation
4. Some other event-forwarding controller takes that event and forwards that (with cluster-context information and involved object) over to EventBridge, which then has a rule configured to Slack

**Comment by ellistarn** [comment]
I hacked together a bridge between kube-events and AWS event-bridge: https://github.com/ellistarn/kube-event-bridge/tree/main. I got all kubernetes events in a cluster posting to a slack channel. The code may be useful inspiration to get you going.

**Comment by ellistarn** [comment]
cc @embano1

**Comment by embano1** [comment]
Disclaimer: I'm from the EventBridge team

Thx for looping me in @ellistarn

I also created a small prototype on a weekend to subscribe to any Kubernetes resource, incl. `events.k8s.io/v1` and forward to [EventBridge](https://aws.amazon.com/eventbridge/?nc1=h_ls) for filtering and target delivery. Just didn't have time to polish and release the code.

Similar ideas where tracking namespace creation/deletion and sending notifications to Slack, IT automation on CRD creation e.g., managing IP address pools, VPC network policies, etc. by triggering a Lambda or Step Function workflow, etc.

Happy to brainstorm further here if there's interest.

**Comment by jonathan-innis** [comment]
Hi @hawkesn. This is definitely an interesting ask but not something that we feel is within the scope of the Karpenter project right now or in the future. Definitely encourage you to reach out to the contacts listed here if you're interested in getting a solution that extends Karpenter in the way that you want
