### ISSUE TITLE
Karpenter Node always in "Not Ready" status (or) Deamonset( aws-node-xxxx, kube-proxy-xxx) in pending status

### ISSUE THREAD

**Issue by manu6300** [aws/karpenter#3557]
### Is an existing page relevant?

https://karpenter.sh/v0.25.0/getting-started/migrating-from-cas/

### What karpenter features are relevant?

While Migrating from CA to karpenter I have followed the above document. But there was a small mistake which takes me 2-3 days to resolve. 
At "Update aws-auth ConfigMap" step, we have to edit  aws-auth configmap with the following rolearn as per doc.
                          rolearn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/KarpenterInstanceNodeRole 
But the role was created with different name in the earlier steps of the doc as KarpenterNodeRole-${CLUSTER_NAME}

### How should the docs be improved?

Please replace the role name in the rolearn.
 rolearn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/KarpenterNodeRole-${CLUSTER_NAME}

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Thanks for surfacing this! #3518 fixes the problem that you are describing. I'll close this issue when that goes in.

**Comment by jonathan-innis** [comment]
Closing now that #3518 is in
