### ISSUE TITLE
Wrong logging format on startup

### ISSUE THREAD

**Issue by agustin-dona-peya** [aws/karpenter#3560]
### Version

__Karpenter Version:__ v0.23.0

__Kubernetes Version:__ v1.23.0

### Expected Behavior

All logs must follow the same format, like "DATE" "LEVEL" "MESSAGE"

### Actual Behavior

When Karpenter startup there's some logs that are not well formatted and difficult the log monitoring
Logs in example are missing log level and bad formatted date:
`2023/02/09 18:52:57 Registering 2 clients`
`2023/02/09 18:52:57 Registering 2 informer factories`
`2023/02/09 18:52:57 Registering 3 informers`
`2023/02/09 18:52:57 Registering 6 controllers`
`I0209 18:52:57.648980       1 leaderelection.go:248] attempting to acquire leader lease tools/karpenter-leader-election...`

### Steps to Reproduce the Problem

Every karpenter startup

### Resource Specs and Logs

No other logs

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
My assumption is that this is coming from somewhere in the [startup/operator](https://github.com/aws/karpenter-core/blob/main/pkg/operator/operator.go#L69) logic where we don't have the logger registered or Knative is taking some opinionated stance on printing logs.

We should look around for any `fmt.Print` statements throughout the codebase.

**Comment by cep21** [comment]
For us, this makes monitoring of karpenter difficult since our monitoring solution is expecting JSON output and considers these non-JSON strings as errors.
