### ISSUE TITLE
Multi provisioner consolidation

### ISSUE THREAD

**Issue by runningman84** [aws/karpenter#3566]
### Tell us about your request

We have two provisioners:
- x86, weight 20
- arm (with arm taint), weight 30 

At daytime the clusters run dozens of projects with a lot of pods. Most of these pods are x86 only and will be placed on the x86 nodes. There are also some management applications like prometheus which tolerate arm.

For example at daytime it looks like this:
- 5 arm nodes, one per az
- 10 x86 nodes, one per az

At night most of the project workload is teared down using the kube-downscaler project. This might leave some 2x.large instanece with only one pod running:
- 3 arm nodes, one per az (only a few pods running per node)
- 3 x86 nodes, one per az z (only a few pods running per node)

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

At night we would like to see the nodes consolidated like this:

- 3 arm nodes
- 1 x86 node

Topology spreads and other constraints look fine for this scenario.

Furthermore we would like to see smaller instances at night instead of 2xlarge which were used at daytime.

Right now replacing a bigger node with a smaller node is blocked by "cannot replace spot with spot".

Consolidating the 6 nodes to 4 nodes is not possible because karpenter seems to consolidate only within the same provisioner.

### Are you currently working around this issue?

We have no real solution

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Spot to spot consolidation is being tracked at https://github.com/aws/karpenter/issues/2741

Karpenter will consolidate across provisioners.  When you are in this situation:

> 
    3 arm nodes, one per az (only a few pods running per node)
    3 x86 nodes, one per az z (only a few pods running per node)


Can you run `kubectl describe node node-name`? This will display the periodic events Karpenter creates related to the node including why it can't be consolidated.  Ensure that you are running Karpenter v0.27 as it fixed a bug where these events wouldn't always get reported.
