### ISSUE TITLE
Provisioner from previous Karpenter installation seems non-functional

### ISSUE THREAD

**Issue by kenny-monster** [aws/karpenter#3572]
### Version

__Karpenter Version:__ v0.22.1

__Kubernetes Version:__ v1.24.0

### Expected Behavior

After uninstalling the Karpenter helm release, I expected that a re-installation would allow everything to work again. No provisioners or nodes are removed before uninstalling the helm release.

The specific case I'm having trouble with is that the default provisioner with `ttlSecondsAfterEmpty: 30` does not remove an empty node that only has DaemonSet pods (`aws-node-xxxxx`, `csi-s3-xxxxx`, `ebs-csi-node-xxxxx`, `kube-proxy-xxxxx`, `nvidia-device-plugin-daemonset-xxxxx`).

### Actual Behavior

Despite having `ttlSecondsAfterEmpty: 30` set, the node is never removed.

I removed the provisioner post-installation to have the owned node be removed and created it again with the same setting which going the TTL to work again.

I thought maybe I would need to try to get Karpenter to "re-initialize" the node so I removed the `karpenter.sh/initialized` label but it gets put back onto the node instantly.

I feel like I need to do something to link the nodes or provisioners to work with the new Karpenter installation but I haven't figure out what that is.

### Steps to Reproduce the Problem

1. Follow the Getting Started instructions.
2. Ensure that an inflate pod is on the node (by scaling the deployment up from 0 to 1).
3. Run `helm uninstall karpenter --namespace karpenter` to remove the Helm release.
4. Reinstall Karpenter through the Helm chart again. In my case, I'm trying to go to **v0.23.0**.
5. Scale down the inflate deployment to 0.
6. Notice that the node now only has DaemonSet pods but doesn't get removed.

### Resource Specs and Logs

I am using the default provisioner with the `inflate` deployment from the Getting Started guide.
https://karpenter.sh/preview/getting-started/getting-started-with-karpenter/

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kenny-monster** [comment]
The reason I'm doing this is because I'm trying to avoid doing a Terraform import. I thought I could simply remove my manual installed Karpenter and replace it with a `helm_release` but I ended up encountering this issue instead.

**Comment by jonathan-innis** [comment]
Confirming: when you uninstall Karpenter, you are leaving behind the provisioner, so that when you install the newer version of Karpenter, the old provisioner still exists and the node still exists?

**Comment by kenny-monster** [comment]
That's right. Deleting provisioners would bring down any nodes associated with them so I thought to try to keep them there. That seemed to work until I realised the provisioners that were created for the previous Karpenter installation don't seem to be working well with the new Karpenter installation.

**Comment by engedaam** [comment]
Hey @kenny-monster, what version of Karpenter are you upgradeing to, and can you share the karpenter logs?

**Comment by kenny-monster** [comment]
@engedaam I've updated the description to mention that I'm trying to install v0.23.0. I'll try to share some logs soon but I don't recall anything noteworthy.

**Comment by engedaam** [comment]
@kenny-monster Would you also be able to share your Provisioner and AWSNodeTemplate? I was not able to replicate this issue of upgrading from v0.22.1 -> v0.23.0, or any other later versions

**Comment by engedaam** [comment]
@kenny-monster any updates?

**Comment by kenny-monster** [comment]
Sorry for not following up on this. I don't have much intention to try to reproduce it for now so I'm going to close this.
