### ISSUE TITLE
ephemeralStorage computation for instance types doesn't work with AWSNodeTemplate that uses launchTemplateName

### ISSUE THREAD

**Issue by thelabdude** [aws/karpenter#3579]
### Version

Karpenter Version: 0.26.1
Kubernetes Version: v1.23.14-eks-ffeb93d

### Expected Behavior

Our LaunchTemplates are quite complex, so our `AWSNodeTemplate` points to a LaunchTemplate that we create, e.g.
```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: karp-prov1-nt
spec:
  detailedMonitoring: false
  launchTemplate: my-complicated-launch-template
  subnetSelector:
    aws-ids: ...
```

This ends up with the `amifamily.DefaultEBS.VolumeSize` (20Gi) being applied for my instances.

### Actual Behavior

This works well until a pod requests `ephemeral-storage` and then the pods won't schedule. I tracked this down to the assumption in `computeCapacity` that the `AWSNodeTemplate` has `blockDeviceMappings` defined. 

Here's a diff of a hack I added to get this working (which should illustrate the issue):

```
diff --git a/pkg/cloudprovider/instancetype.go b/pkg/cloudprovider/instancetype.go
index e718bd68..4f85d55d 100644
--- a/pkg/cloudprovider/instancetype.go
+++ b/pkg/cloudprovider/instancetype.go
@@ -55,7 +55,7 @@ func NewInstanceType(ctx context.Context, info *ec2.InstanceTypeInfo, kc *v1alph
                Name:         aws.StringValue(info.InstanceType),
                Requirements: computeRequirements(ctx, info, offerings, region, amiFamily, kc),
                Offerings:    offerings,
-               Capacity:     computeCapacity(ctx, info, amiFamily, nodeTemplate.Spec.BlockDeviceMappings, kc),
+               Capacity:     computeCapacity(ctx, info, amiFamily, nodeTemplate, kc),
                Overhead: &cloudprovider.InstanceTypeOverhead{
                        KubeReserved:      kubeReservedResources(cpu(info), pods(ctx, info, amiFamily, kc), eniLimitedPods(info), amiFamily, kc),
                        SystemReserved:    systemReservedResources(kc),
@@ -131,12 +131,19 @@ func getArchitecture(info *ec2.InstanceTypeInfo) string {
 }
 
 func computeCapacity(ctx context.Context, info *ec2.InstanceTypeInfo, amiFamily amifamily.AMIFamily,
-       blockDeviceMappings []*v1alpha1.BlockDeviceMapping, kc *v1alpha5.KubeletConfiguration) v1.ResourceList {
+       nodeTemplate *v1alpha1.AWSNodeTemplate, kc *v1alpha5.KubeletConfiguration) v1.ResourceList {
+
+       var storage resource.Quantity
+       if nodeTemplate.Spec.LaunchTemplateName != nil {
+               storage = resource.MustParse("1000Gi")
+       } else {
+               storage = *ephemeralStorage(amiFamily, nodeTemplate.Spec.BlockDeviceMappings)
+       }
 
        return v1.ResourceList{
                v1.ResourceCPU:               *cpu(info),
                v1.ResourceMemory:            *memory(ctx, info),
-               v1.ResourceEphemeralStorage:  *ephemeralStorage(amiFamily, blockDeviceMappings),
+               v1.ResourceEphemeralStorage:  storage,
                v1.ResourcePods:              *pods(ctx, info, amiFamily, kc),
                v1alpha1.ResourceAWSPodENI:   *awsPodENI(ctx, aws.StringValue(info.InstanceType)),
                v1alpha1.ResourceNVIDIAGPU:   *nvidiaGPUs(info),

```

Obviously, the `storage = resource.MustParse("1000Gi")` was just for my env.

### Steps to Reproduce the Problem

try to schedule any pod with `ephemeral-storage` requests > 20Gi and Karpenter won't match it to a instance.

```
    resources:
      requests:
        cpu: "4"
        ephemeral-storage: 30Gi
        memory: 16Gi
```

### Resource Specs and Logs

Bunch of log messages like this:
```
2023-03-10T21:19:14.289Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "karp-prov1", no instance type satisfied resources {"cpu":"4600m","ephemeral-storage":"20Gi","memory":"17536Mi","pods":"1"} and requirements topology.kubernetes.io/zone In [us-west-2b], karpenter.k8s.aws/instance-size In [12xlarge 16xlarge 24xlarge 2xlarge 4xlarge and 3 others], karpenter.sh/capacity-type In [on-demand], kubernetes.io/os In [linux], karpenter.sh/provisioner-name In [karp-prov1], kubernetes.io/arch In [amd64], karpenter.k8s.aws/instance-family In [c5 c6i m6i r5 r6i
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@thelabdude Do you have the ability to migrate away from using the launch template value and use the fields that Karpenter uses to discover some of this info i.e. `blockDeviceMappings`? We are [thinking about deprecating the `launchTemplate` field](https://github.com/aws/karpenter/pull/2964) in the `AWSNodeTemplate` as part of the upgrade to `v1beta1` so we're generally recommending that users move to the new format if they can.

**Comment by thelabdude** [comment]
The reason I'm using `launchTemplate` is our `userData` section is quite complicated to construct (3-4 cloud-init scripts + several shell scripts). We already have infra that contructs a `LaunchTemplate` with all the necessary `userData` sections. Maybe my use case is unique in this regard? Ability to point to an existing `LaunchTemplate` in my infra seemed like a nice feature of Karpenter. 

I guess I'm missing why Karpenter can't just call into the AWS API to get the `blockDeviceMappings` from the LT? Looking at the EC2 API, seems like it would just be a call to `describe-launch-template-versions` for the `$Latest` or `$Default` version. What other "sharp edges" (mentioned in the link you provided) exist when using LaunchTemplates (I've only encountered this one).

The `blockDeviceMapping` approach in `AWSNodeTemplate` may not be quite right anyway because the EBS root volume size (+ IOPS, throughput, etc) are somewhat dependent on the size of the instance that gets provisioned. One can fit a lot more pods on a `16xlarge` than on an `xlarge` (obviously), so it follows that I'd need a bigger root EBS vol to service more `emptyDir` requests. I wouldn't want to provision a 1TB gp3 with 16000 IOPS for an `xlarge` but I may need that for a `16xlarge` instance. How does Karpenter address this problem today?

**Comment by jonathan-innis** [comment]
A couple of the other "sharp edges" that maybe aren't mentioned in that doc are the lack of multi-architecture support with launch templates. We are limited to only support whatever architecture that the launch template specifies. 

Maybe we could discover the architecture that the launch template AMI uses to constrain any provisioners that use that launch template, but you are still limited in the workloads that you can deploy through the launch template.

> The blockDeviceMapping approach in AWSNodeTemplate may not be quite right anyway because the EBS root volume size
For scaling the EBS volume size, we are tracking a feature request to be able to scale the ephemeral-storage requests based on the pod requests that are needed #2394. You could imagine that we could potentially add a fixed overhead to this blockDeviceMapping size in the future if it was needed.

**Comment by thelabdude** [comment]
yes, I hit the arch issue today but solved with a separate provisioner for graviton ... however, I think I've solved my complex userData problem and am going to migrate away from LaunchTemplate and specify all my needs in the AWSNodeTemplate directly.

**Comment by thelabdude** [comment]
I actually spoke too soon, trying to construct the `userData` string from Pulumi is proving to be a bit challenging :-( this is why we have data structures vs. just a string blob!

**Comment by jonathan-innis** [comment]
Can you share more details about what specific issues you are hitting that aren't great/workable in the userData string section?

**Comment by thelabdude** [comment]
I'm not constructing the `AWSNodeTemplate` YAML manually, trying to use Pulumi's `k8s.apiextensions.CustomResource` and the resulting YAML looks to have all the `\n` escaped improperly, etc. I'm not sure the correct approach for trying to take a big string clob and fit into a YAML string.

Ideally, `AWSNodeTemplate` would just take a base64 encoded value for `userData` as an option and then decode it in Karpenter's `eksbootstrap.go`. Maybe as another option in the CRD, such as `userDataBase64`?

**Comment by jonathan-innis** [comment]
@thelabdude I'm pretty against adding additional api-surface, giving users two paths to the same solution if there isn't a big technical hurdle that's causing us to need to do this. Is the main pain-point here that you will have to go back and escape all of the `\n` values to make it work? Is there any technical limitation to the current string format for `userData`?

**Comment by thelabdude** [comment]
I think allowing base64 encoded would be a nice addition. Other than the giant ugly chunk of multi-line string in my YAML, I actually tracked the problem down to Karpenter expecting:
```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="PULUMI_MIME_BOUNDARY"
```

but our userData had:
```
Content-Type: multipart/mixed; boundary="PULUMI_MIME_BOUNDARY"
MIME-Version: 1.0
```

What's weird is EC2 LaunchTemplates have no issue with the order of those being swapped, the userData section works either way, so I'm not sure if this a bug in our infra (I don't control the code that generates userData like this) or if the order doesn't actually matter?

Swapping the order of those two header lines gets this working, so I'll close this issue for now.

**Comment by thelabdude** [comment]
fwiw ~ I heard from some internal Pulumi experts that our `userData` section is:
```
They are rendered using the Go stdlib package for mime
```
so this requiring `userData` to start with `MIME-Version: 1.0` might actually be a Karpenter bug!
