### ISSUE TITLE
Node Termination Protection

### ISSUE THREAD

**Issue by yws-ss** [aws/karpenter#3583]
### Tell us about your request

Hello team,

I'm wondering to know whether have a annotation or label could protect one node launch by Karpenter to be deprovisioning.

Just like Cluster AutoScaler have annotation:

`cluster-autoscaler.kubernetes.io/scale-down-disabled: true`

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-prevent-cluster-autoscaler-from-scaling-down-a-particular-node

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Sometime, node will have issue and need to do further troubleshooting. Before that, to avoid affect current business, we might drain all the pod from node. After that, the node should be empty and Karpenter will might consider to deprovisiong it. 

I understand that `ttlSecondsAfterEmpty` might help to extend the live time. However, it's for whole provisioner, and I think this feature aren't designed for this behavior. 

### Are you currently working around this issue?

Running a dummy pod on that node to make sure the node is not empty.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by James-Quigley** [comment]
If you are using consolidation, you can opt a node out of consolidation by adding the annotation `karpenter.sh/do-not-consolidate: "true"` on the node. [See the docs](https://karpenter.sh/v0.27.0/concepts/deprovisioning/#node-consolidation)

**Comment by njtran** [comment]
In general we recommend you drive this at the application level, to ensure that applications aren't disrupted. https://karpenter.sh/v0.27.3/concepts/deprovisioning/#disabling-deprovisioning should give you all the ways you can block different types of deprovisioning. If you're looking to have some capacity that Karpenter doesn't deprovision you may want to track this through #2050. I'm going to close this in favor of the existing options and #2050 if that works for you. Feel free to re-open if you have more questions.
