### ISSUE TITLE
Support cordon only for Spot Interruption Events

### ISSUE THREAD

**Issue by sidewinder12s** [aws/karpenter#3604]
### Tell us about your request

Karpenter will emit metrics/events to Kubernetes & will cordon nodes impacted by interruption events.

NTH supports this mode currently. 

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

We have cases within Batch systems where we're aware spot int is incoming and we want to allow a task to attempt to finish as much work as possible before dying instead of being rescheduled. Or we're aware the node is degraded, cordon the node so nothing new comes in but let whatever is running finish and exit.

### Are you currently working around this issue?

We use NTH in this mode instead of Karpenter. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Here are some potential workarounds:
 - You could ignore the SIGINT signal that the kubelet sends your container from within your application OR 
 - Use a Prestop container to ignore the signal

**Comment by ellistarn** [comment]
> allow a task to attempt to finish

Another option: use a PDB or `do-not-evict` to block these pods from being disrupted.

**Comment by ellistarn** [comment]
Feel free to reopen if these workarounds don't work for you. Right now, we're cautious about adding more complexity to the current deprovisioning flows.
