### ISSUE TITLE
running longhorn on karpenter managed nodes

### ISSUE THREAD

**Issue by abhishiekgowtham** [aws/karpenter#3609]
### What karpenter features are relevant?

when running longhorn DS, it starts an `instance-manager-e-xxxx` or `instance-manager-r-xxxx` pod(s) that are managed and started by the longhorn-manager. When we have consolidation enabled on the controller, it doesn't really delete those nodes where no pods are running except `instance-manager-e-xxxx` or `instance-manager-r-xxxx` pod(s) which is adding up the costs in our bill. Is there a way to work around this issue? please let me know! 

### How should the docs be improved?

NA

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
The node isn't considered empty unless all the pods running on a node are DaemonSets. 

These are the actual conditions to that we look for when determining if a node is empty: https://github.com/aws/karpenter-core/blob/main/pkg/utils/node/node.go#L39-L42


Can you post the full resource yaml for `instance-manager-e-xxxx` pods? Curious if there's some indication that we could use to know that these pods are node scoped. I'm guessing the DS uses a very specific node selector too where consolidation wouldn't consolidate the node either (which in this case I don't think would make any sense anyways).

**Comment by abhishiekgowtham** [comment]
hey @bwagner5, here's the resource yaml. I think there're some labels (like `longhorn.io/node`) that can be used to identify that the pod is scoped to a node.

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
    longhorn.io/last-applied-tolerations: '[{"key":"nodetype","operator":"Exists","effect":"NoSchedule"}]'
  creationTimestamp: "2023-02-11T01:43:58Z"
  labels:
    longhorn.io/component: instance-manager
    longhorn.io/instance-manager-image: imi-fd1efc79
    longhorn.io/instance-manager-type: engine
    longhorn.io/managed-by: longhorn-manager
    longhorn.io/node: ip-10-0-140-160
  name: instance-manager-e-f59ea997
  namespace: longhorn-system
  ownerReferences:
  - apiVersion: longhorn.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: InstanceManager
    name: instance-manager-e-f59ea997
    uid: 31cf3818-26e5-4471-b9c7-2c0b78321466
  resourceVersion: "1176633951"
  uid: 098d72a3-5996-48a0-b173-f0a54d3b81be
spec:
  containers:
  - args:
    - engine-manager
    - --debug
    - daemon
    - --listen
    - 0.0.0.0:8500
    image: longhornio/longhorn-instance-manager:v1_20220303
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 3
      periodSeconds: 5
      successThreshold: 1
      tcpSocket:
        port: 8500
      timeoutSeconds: 4
    name: engine-manager
    resources:
      requests:
        cpu: 470m
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/dev
      name: dev
    - mountPath: /host/proc
      name: proc
    - mountPath: /engine-binaries/
      mountPropagation: HostToContainer
      name: engine-binaries
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-89nvz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-0-140-160
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: longhorn-service-account
  serviceAccountName: longhorn-service-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: nodetype
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /dev
      type: ""
    name: dev
  - hostPath:
      path: /proc
      type: ""
    name: proc
  - hostPath:
      path: /var/lib/longhorn/engine-binaries/
      type: ""
    name: engine-binaries
  - name: kube-api-access-89nvz
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

**Comment by ellistarn** [comment]
The core challenge is this
```
  ownerReferences:
  - apiVersion: longhorn.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: InstanceManager
    name: instance-manager-e-f59ea997
    uid: 31cf3818-26e5-4471-b9c7-2c0b78321466
```
Karpenter can't be aware of all third party extensions, so our emptiness logic cannot factor in these daemons, since they're not owned by daemonsets.

I could see a feature request to label a pod (similar to do-not-evict), where we exclude the pod from utilization calculations. 
However, there's some more complexity here. We will miscalculate launch decisions, because we can't be aware of the resource requirements of these pods, since we can't model them as daemons. 

Unfortunately, I don't see a great path to supporting 3rd party daemonsets in Karpenter (or Cluster Autoscaler, for that matter). I'd recommend reaching out to the Longhorn maintainers to see if they can model this using Daemonsets.

Feel free to reopen if you learn more and want to continue the discussion.

**Comment by mo-saeed** [comment]
@gothka I am exploring the use of Longhorn but I have the same scenario, EKS with karpenter so I am wondering if you found any solution for that.
