### ISSUE TITLE
Best practices regarding AMIs

### ISSUE THREAD

**Issue by JacobAmar** [aws/karpenter#3624]
### What karpenter features are relevant?

We are proceeding with karpenter to production, I wanted to know how are you testing AMIs before proceeding to prod. are you using the latest only? is it safe to only use the latest AMIs?

Thanks

### How should the docs be improved?

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Hey @JacobAmar, thanks for opening this. It seems like you're wanting feedback from the of Karpenter user community. I'm not sure how many people are actively following GH issues to give their feedback. If you're able to, you should direct your questions to the [Kubernetes Karpenter slack](https://kubernetes.slack.com/archives/C02SFFZSA2K)! I'll close this in favor of that. Feel free to re-open if you want.
