### ISSUE TITLE
Fix APICodeGen

### ISSUE THREAD

**Issue by spring1843** [aws/karpenter#3631]
### Version

n/a

### Expected Behavior

https://github.com/aws/karpenter/actions/workflows/api-code-gen.yaml should pass

### Actual Behavior

Failing https://github.com/aws/karpenter/actions/runs/4468543916/jobs/7849428249

### Steps to Reproduce the Problem

n/a

### Resource Specs and Logs

n/a

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
I was able to do it locally and it looks like the most recent one passed. Do you know what might've happened here?
