### ISSUE TITLE
Add a draining node label when a node is being deprovisioned

### ISSUE THREAD

**Issue by nadavbuc** [aws/karpenter#3638]
### Tell us about your request

When node is draining due to either consolidation or interruption - it would be helpful to label it with something like
`karpenter_sh/DrainingInitiated: "true"`

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

This functionality currently exists on 3rd party provider we are using and allows us to scrape this as part of `kube_node_labels` in prometheus - and create graphs which correlates between pods availability against draining nodes

### Are you currently working around this issue?

No, i am in the process of migrating to Karpenter (already done so in our Dev Environment)

### Attachments

![image](https://user-images.githubusercontent.com/36670281/227204283-09121d40-7b19-4135-b4b2-c6607cc9974f.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
You can identify that a node is draining when its deletionTimestamp is set. Does your scraper require it to be a label, or could it potentially track other data?

**Comment by nadavbuc** [comment]
The scraper is using labels which are expoed by prometheus node-exporter daemon set, it doesn't track anything other than labels AFAIK

**Comment by ellistarn** [comment]
One concern I'd have is about write volume. It's probably fine in this case, but we try to minimize writes to the API Server, especially if it scales with pods/nodes. I wonder if the node exporter would be able to track unschedulable taints. This would work for management solutions outside of karpenter too.

**Comment by nadavbuc** [comment]
@ellistarn You are correct - i completely missed that option
`kube_node_spec_taint{key="node.kubernetes.io/unschedulable"}`
It should be more than enough 
Thanks!
