### ISSUE TITLE
Adding Provisioners and NodeTemplates manifests to the helm chart?

### ISSUE THREAD

**Issue by nirroz93** [aws/karpenter#3639]
### Tell us about your request

As a karpenter user, I have a helm chart with provisioners and AWSNodeTemplates with controller chart as a dependency, in order to create them easily and manage them. 

Something like this https://github.com/aws/karpenter/compare/main...nirroz93:karpenter:main?expand=1

The request/feature here is if you want to provide such helm chart (some people I talked with suggested I open PR, so sharing here). 

I'm not sure that it's needed/wanted so for now opening an issue for discussion before opening PR from the link I sent (need to add few comments, option to add metadata and test)

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Easy way to create multiple provsioners using helm chart. 

### Are you currently working around this issue?

I have a chart using controller as dependency, with extra manifests

### Additional Context

In the comparison I also added over provision using preemption example, maybe it's not needed

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by snorlaX-sleeps** [comment]
Is having a common Helm chart for provisioners or node templates a common request?
I just assumed each use case was specific enough?

**Comment by bwagner5** [comment]
We've tried to make our helm chart pretty light weight, so I don't think the complexity of adding templated provisioners and node templates is something we'd like in this repo. I think your approach is correct by depending on the Karpenter chart and creating your own chart for your provisioners and node templates.

**Comment by ItaloChagas** [comment]
Agreed that each use case is specific enough, although I think that having provisioners and AWSNodeTemplate templates based on the examples we have here at the repo can really come in handy.

**Comment by nadavbuc** [comment]
I actually thought about the exact same thing - and also prepared an internal helm chart for it
and planned to create a public version of it
It saves loads of code duplications

**Comment by jonathan-innis** [comment]
If you wanted to link your public chart somewhere, we'd be supportive of something like a blog posting that could be referenced in the Karpenter docs so that Karpenter users could track it down if that was something that they wanted to use
