### ISSUE TITLE
Consolidation process not happens because of spreadConstraint, hpa scale down behavior

### ISSUE THREAD

**Issue by Yufeireal** [aws/karpenter#3641]
### Version

__Karpenter Version:__ v0.27.0

__Kubernetes Version:__ v1.22

I have just migrated from Cluster Autoscaler + Auto scaling group to Karpenter.
Well, when I compare the request/allocatable ratio, I find Karpenter provisioned nodes have only 30% cpu&memory utilization. I have opened consolidation for the Karpenter controller, not sure what cause this problem. 

FYI, I didn't uninstall Cluster Autoscaler but instead I adjust the corresponding min/max replicas of ASG to 0. So the certain nodes can only be provsioned by Karpenter.

The pods only have spreadConstraints for availibility zones
(There is only one instance_type: c6g.8xlarge and node type is ondemand)

### Expected Behavior

The nodes with low cpu&memory utilization will be deleted and reschedule the pods to other nodes.

### Actual Behavior

The nodes have low resource utilization and the logs keep saying "Not all pods will be schedule".

### Steps to Reproduce the Problem

1. Before then, I have a cluster autoscaler and autoscaling group, the asg has min/max 1/100
2. I launched provisioner for the same node type
3. Manually scale down the min/max replcas of asg, 1/100 -> 25/25 -> 20/20 -> ... -> 0/0
4. Then all the workload is managed by Karpenter
5. But however, Karpenter did not deprovision though the pods only request few resources.

### Resource Specs and Logs

Here is the log for the nodes which should be consolidated:
```
`Non-terminated Pods:          (8 in total)
  Namespace                   Name                        CPU Requests  CPU Limits   Memory Requests  Memory Limits  Age
  ---------                   ----                        ------------  ----------   ---------------  -------------  ---
  default                     vcamsegs-59b8dc555-2kxmm    1 (3%)        2 (6%)       300Mi (0%)       0 (0%)         3d11h
  default                     vcamsegs-59b8dc555-d2zfv    1 (3%)        2 (6%)       300Mi (0%)       0 (0%)         3d11h
  default                     vsubmit-78c49fbbcf-tpczs    5400m (16%)   5500m (17%)  6400Mi (10%)     8448Mi (13%)   2d3h
  kube-system                 aws-node-b24gl              10m (0%)      0 (0%)       0 (0%)           0 (0%)         3d11h
  kube-system                 ebs-csi-node-vhqq4          0 (0%)        0 (0%)       0 (0%)           0 (0%)         3d11h
  kube-system                 kube-proxy-vftq4            100m (0%)     0 (0%)       0 (0%)           0 (0%)         3d11h
  monitoring                  datadog-86gxf               200m (0%)     0 (0%)       256Mi (0%)       0 (0%)         3d11h
  monitoring                  node-exporter-r2clz         10m (0%)      100m (0%)    100Mi (0%)       100Mi (0%)     3d11h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests      Limits
  --------                    --------      ------
  cpu                         7720m (24%)   9600m (30%)
  memory                      7356Mi (11%)  8548Mi (13%)
  ephemeral-storage           0 (0%)        0 (0%)
  hugepages-1Gi               0 (0%)        0 (0%)
  hugepages-2Mi               0 (0%)        0 (0%)
  hugepages-32Mi              0 (0%)        0 (0%)
  hugepages-64Ki              0 (0%)        0 (0%)
  attachable-volumes-aws-ebs  0             0
  vpc.amazonaws.com/pod-eni   3             3
Events:
  Type    Reason            Age                    From       Message
  ----    ------            ----                   ----       -------
  Normal  Unconsolidatable  52s (x318 over 3d11h)  karpenter  not all pods would schedule
```

For Karpenter logs, I didn't see any useful information related to this provisioner.
Why not all pods would schedule, was this caused by Karpenter can not reschedule daemonset? 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Yufeireal** [comment]
`Name:         cpu-c6g-streaming
Namespace:    
Labels:       app.kubernetes.io/instance=vkarpenter
Annotations:  <none>
API Version:  karpenter.sh/v1alpha5
Kind:         Provisioner
Metadata:
  Creation Timestamp:  2023-03-22T00:23:30Z
  Generation:          4
  Managed Fields:
    API Version:  karpenter.sh/v1alpha5
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:resources:
          .:
          f:attachable-volumes-aws-ebs:
          f:cpu:
          f:ephemeral-storage:
          f:memory:
          f:pods:
          f:vpc.amazonaws.com/pod-eni:
    Manager:      karpenter
    Operation:    Update
    Subresource:  status
    Time:         2023-03-22T10:49:53Z
    API Version:  karpenter.sh/v1alpha5
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:app.kubernetes.io/instance:
      f:spec:
        .:
        f:consolidation:
          .:
          f:enabled:
        f:kubeletConfiguration:
          .:
          f:evictionHard:
            .:
            f:memory.available:
            f:nodefs.available:
          f:evictionMaxPodGracePeriod:
          f:evictionSoft:
            .:
            f:memory.available:
            f:nodefs.available:
          f:evictionSoftGracePeriod:
            .:
            f:memory.available:
            f:nodefs.available:
          f:kubeReserved:
            .:
            f:ephemeral-storage:
            f:memory:
          f:systemReserved:
            .:
            f:ephemeral-storage:
            f:memory:
        f:labels:
          .:
          f:asg-name:
          f:graviton-c6g:
          f:lifecycle:
          f:streaming:
          f:type:
        f:providerRef:
          .:
          f:name:
        f:requirements:
        f:taints:
        f:ttlSecondsUntilExpired:
        f:weight:
    Manager:         argocd-application-controller
    Operation:       Update
    Time:            2023-03-22T22:33:03Z
  Resource Version:  5517302040
  UID:               8a1f95aa-578d-4dc2-926c-7d5ef53a3839
Spec:
  Consolidation:
    Enabled:  true
  Kubelet Configuration:
    Eviction Hard:
      memory.available:             200Mi
      nodefs.available:             10%
    Eviction Max Pod Grace Period:  60
    Eviction Soft:
      memory.available:  500Mi
      nodefs.available:  15%
    Eviction Soft Grace Period:
      memory.available:  1m30s
      nodefs.available:  1m30s
    Kube Reserved:
      Ephemeral - Storage:  1Gi
      Memory:               300Mi
    System Reserved:
      Ephemeral - Storage:  1Gi
      Memory:               200Mi
  Labels:
    Asg - Name:    cpu-c6g-streaming
    graviton-c6g:  true
    Lifecycle:     ondemand
    Streaming:     true
    Type:          cpu
  Provider Ref:
    Name:  default
  Requirements:
    Key:       node.kubernetes.io/instance-type
    Operator:  In
    Values:
      c6g.8xlarge
    Key:       topology.kubernetes.io/zone
    Operator:  In
    Values:
      us-west-2a
      us-west-2b
      us-west-2c
    Key:       kubernetes.io/arch
    Operator:  In
    Values:
      arm64
    Key:       kubernetes.io/os
    Operator:  In
    Values:
      linux
    Key:       karpenter.sh/capacity-type
    Operator:  In
    Values:
      on-demand
  Taints:
    Effect:                   NoSchedule
    Key:                      streaming
    Value:                    true
    Effect:                   NoSchedule
    Key:                      graviton-c6g
    Value:                    true
  Ttl Seconds Until Expired:  1209600
  Weight:                     50
Status:
  Resources:
    Attachable - Volumes - Aws - Ebs:  3861
    Cpu:                               3168
    Ephemeral - Storage:               3319757892Ki
    Memory:                            6401522556Ki
    Pods:                              23166
    vpc.amazonaws.com/pod-eni:         5346
Events:                                <none>`

Provisioner info

**Comment by bwagner5** [comment]
From the provisioner you pasted above, it looks like `c6g.8xlarge` is the only instance type allowed. This will prevent consolidation from happening since there are no cheaper instance types that will fit your pods.

I'd recommend removing the following requirement from your provisioner:

```
    Key:       node.kubernetes.io/instance-type
    Operator:  In
    Values:
      c6g.8xlarge
```

and see if consolidation works after that.  Karpenter will still select a graviton node since you have a kubernetes.io/arch=arm64 requirement.

**Comment by Yufeireal** [comment]
Thanks for the quick response. 
I think if Karpenter can not replace that with a cheaper node, the log should be "Can not replace with a cheaper node "? And let's suppose I have two c6g.8xlarge A and B. Let's assume both of them use 20% cpu and 20% memory. I think the Karpenter can schedule the workload from node A to node B correctly? Not sure the internal process of deprovisioning. Is this expected or a corner case if I only allow one instance_type and enabled consolidation also?

**Comment by bwagner5** [comment]
If you have multiple c6g.8xlarge nodes running and they're not utilized to where the pods can be consolidated to a smaller number of nodes, then Karpenter should take that action. I'm not sure why it is not in this case. 

I don't think there should be any issues with the daemonsets scheduling. 

Are you able to post the deployment specs for the pods running on the node?

**Comment by Yufeireal** [comment]
Sure, I can do that. Just want to confirm, the consolidation process only takes care of non-daemonset pods right? Like when we run the command `kubectl drain nodes --ignore-daemonset`? Also, during my experimentation, if hpa scales down, like all the service pods were removed from the node, Karpenter can trigger deprovision behavior(not consolidation). For consolidation, it keeps logging 
"  Normal   Unconsolidatable         2m57s (x2 over 18m)  karpenter        not all pods would schedule"

The deployment has a spreadConstraints, but I don't think that's the issue since there are no consolidation behavior at all. Here is an attached configuration for the deployment and it's controlled by a HPA
`
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '4'
    deployment.kubernetes.io/desired-replicas: '0'
    deployment.kubernetes.io/max-replicas: '0'
    deployment.kubernetes.io/revision: '63'
  creationTimestamp: '2023-03-27T17:56:52Z'
  generation: 1
  labels:
    admission.datadoghq.com/enabled: 'true'
    app: vsubmit
    appInst: vsubmit
    pod-template-hash: 7d984bdfff
    tags.datadoghq.com/service: vsubmit
    tags.datadoghq.com/version: a734957
    vertical: streaming
  name: vsubmit-7d984bdfff
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: vsubmit
      uid: 94fe7e03-cf5d-474d-9452-463efec4b1d3
  resourceVersion: '5522817073'
  uid: b40c5dd5-5ec3-4d5e-afbd-91b9576356d5
spec:
  replicas: 0
  selector:
    matchLabels:
      appInst: vsubmit
      pod-template-hash: 7d984bdfff
  template:
    metadata:
      creationTimestamp: null
      labels:
        admission.datadoghq.com/enabled: 'true'
        app: vsubmit
        appInst: vsubmit
        pod-template-hash: 7d984bdfff
        tags.datadoghq.com/service: vsubmit
        tags.datadoghq.com/version: a734957
        vertical: streaming
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
                  - key: streaming
                    operator: In
                    values:
                      - 'true'
      containers:
        - env:
            - name: CLUSTER
              value: prod1
            - name: OPENBLAS_NUM_THREADS
              value: '4'
            - name: DISABLE_LOGZIO
              value: 'true'
          image: :)
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sleep
                  - '25'
          livenessProbe:
            exec:
              command:
                - test
                - '-S'
                - /app/sockets/vsubmit.sock
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: vsubmit
          readinessProbe:
            exec:
              command:
                - test
                - '-S'
                - /app/sockets/vsubmit.sock
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 20
          resources:
            limits:
              cpu: 5500m
              memory: 8Gi
            requests:
              cpu: 5144m
              memory: 6Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/config
              name: config
            - mountPath: /app/sockets
              name: socket-data
        - env:
            - name: CLUSTER
              value: prod1
            - name: DISABLE_LOGZIO
              value: 'true'
          image: >-
            :)
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sleep
                  - '25'
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 4003
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 20
          name: vsubmit-nginx
          ports:
            - containerPort: 4003
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 4003
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 20
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 256m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/config
              name: config
            - mountPath: /var/run/sockets
              name: socket-data
      dnsPolicy: ClusterFirst
      priorityClassName: high-priority
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      serviceAccount: vsubmit
      serviceAccountName: vsubmit
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: graviton-c6g
          operator: Equal
          value: 'true'
        - effect: NoSchedule
          key: streaming
          operator: Equal
          value: 'true'
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              appInst: vsubmit
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
      volumes:
        - configMap:
            defaultMode: 420
            name: :)
          name: config
        - emptyDir: {}
          name: socket-data
status:
  observedGeneration: 1
  replicas: 0

`

**Comment by Yufeireal** [comment]
Also, I didn't see there are any logs in Karpenter that shows the consolidation process but only some node events show unable to consolidate. Is there any places or log level I should set to see some detailed logs?

**Comment by Yufeireal** [comment]
Just found out the pods have priorityClass, high-priority with a value of 100. Is that blocked the eviction process??

**Comment by bwagner5** [comment]
a high-priority class shouldn't block consolidation, it should only be used to determine the order of pod preemption if kube-scheduler needs to evict pods to make room on a node.

**Comment by Yufeireal** [comment]
**Using preferred anti-affinity and topology spreads can reduce the effectiveness of consolidation. At node launch, Karpenter attempts to satisfy affinity and topology spread preferences. In order to reduce node churn, consolidation must also attempt to satisfy these constraints to avoid immediately consolidating nodes after they launch. This means that consolidation may not deprovision nodes in order to avoid violating preferences, even if kube-scheduler can fit the host pods elsewhere.**

referenced from official doc.
Do we have some plan to enable force evict even though it will temporarily violate the current constraints like spreadConstraint?

**Comment by Yufeireal** [comment]
Another issue is we have a service running in only us-west-2a. It's used for setting up connections with camera. In the hpa, **it does not allow scale down behavior**. This behavior will block Karpenter from evicting pods(Like put 3 or 4 pods in 2 machines into 1 machine). I think we should we should not respect this behavior during scheduling but respect this "do not scale down" in the final state? Like though consolidation will make some pods unavailable, they should still evict those instead of keep them on the nodes to respect the rule?
Cluster AutoScaler can handle this well. I think this is a **bug** which we probably need to pay attention on. Maybe we can come up with another parameters to enable force eviction?

**Comment by tzneal** [comment]
Closing in preference to #3694
