### ISSUE TITLE
How to pass extra args to kubelet?

### ISSUE THREAD

**Issue by sergkondr** [aws/karpenter#3648]
### What karpenter features are relevant?

Hello Karpenter team!

[As far as I see](https://github.com/aws/karpenter/blob/b58d4cd2515951c2ee7f0afd5dbdca73aa48c768/pkg/providers/amifamily/bootstrap/eksbootstrap.go#L64), Karpenter adds bootstrap.sh trigger to the user data itself. And I don't understand, how to add my custom parameters to kubelet, for example: "--pod-max-pids=4096" or something else.

Also, I can't find a way to prevent Karpenter from adding this section with `bootstrap.sh` to the end of the user data, is there any way to do that? I'd like to add this section myself, the same way I do in AWS-managed node groups.

### How should the docs be improved?

It would be nice to describe:
1. How to configure kubelet extra parameters
2. How to prevent Karpenter from adding the `bootstrap.sh` to the end of the user data

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
The opinionated bootstrap.sh call is performed as part of the AL2 AMIFamily specified in the AWSNodeTemplate (or defaulted if not specified). You can choose to use the Custom AMIFamily and then the bootstrap script will not be injected.

However, if you just want to add kubelet params in the kubeletConfiguration file, you can specify a script like [this](https://karpenter.sh/v0.27.0/concepts/node-templates/#:~:text=You%20can%20also%20set%20kubelet%2Dconfig%20properties%20by%20modifying%20the%20kubelet%2Dconfig.json%20file%20before%20the%20EKS%20bootstrap%20script%20starts%20the%20kubelet%3A) in your AWSNodeTemplate spec.userData field which will execute right before the bootstrap script.

**Comment by sergkondr** [comment]
Thanks for the answer!

>  You can choose to use the Custom AMIFamily and then the bootstrap script will not be injected.

What is the difference between `Custom` and `AL2`? I mean, what else will change if I set `Custom`?

> you can specify a script like [this](https://karpenter.sh/v0.27.0/concepts/node-templates/#:~:text=You%20can%20also%20set%20kubelet%2Dconfig%20properties%20by%20modifying%20the%20kubelet%2Dconfig.json%20file%20before%20the%20EKS%20bootstrap%20script%20starts%20the%20kubelet%3A)

Unfocrutently, your link is 404 for me.

**Comment by ellistarn** [comment]
Try incognito or clearing your browser cache -- we've been seeing customers having issues with client side caching of the website. This link should work, pointing to the latest docs https://karpenter.sh/v0.27.1/concepts/node-templates/#:~:text=You%20can%20also%20set%20kubelet-config%20properties%20by%20modifying%20the%20kubelet-config.json%20file%20before%20the%20EKS%20bootstrap%20script%20starts%20the%20kubelet%3A

**Comment by ellistarn** [comment]
Feel free to reopen if this doesn't address your question.
