### ISSUE TITLE
aws-auth not updated when attaching a default instance profile in karpenter helm chart

### ISSUE THREAD

**Issue by vivekkarne** [aws/karpenter#3661]
### Version

__Karpenter Version:__ v0.26.1

__Kubernetes Version:__ v1.25.0

### Expected Behavior

helm chart:
```
resource "helm_release" "karpenter" {
  namespace        = "karpenter"
  create_namespace = true

  name       = "karpenter"
  # repository = "oci://public.ecr.aws/karpenter/karpenter"
  chart      = "oci://public.ecr.aws/karpenter/karpenter"
  version    = "v0.26.1"

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = aws_iam_role.karpenter_controller.arn
  }

  set {
    name  = "settings.aws.clusterName"
    value = aws_eks_cluster.vkarne-eks.id
  }

  set {
    name  = "settings.aws.clusterEndpoint"
    value = aws_eks_cluster.vkarne-eks.endpoint
  }

  set {
    name  = "settings.aws.defaultInstanceProfile"
    value = aws_iam_instance_profile.karpenter_node.name
  }
}
```

karpenter node role:
```
## Instance profile for nodes to pull images, networking, etc
resource "aws_iam_role" "karpenter_node" {
  name = "karpenter-node-${var.cluster_name}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "ec2.amazonaws.com"
        }
      },
    ]
  })
}

resource "aws_iam_role_policy_attachment" "AmazonEKSWorkerNodePolicy_" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
  role       = aws_iam_role.karpenter_node.name
}

resource "aws_iam_role_policy_attachment" "AmazonEKS_CNI_Policy_" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  role       = aws_iam_role.karpenter_node.name
}

resource "aws_iam_role_policy_attachment" "EC2InstanceProfileForImageBuilderECRContainerBuilds_" {
  policy_arn = "arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds"
  role       = aws_iam_role.karpenter_node.name
}

resource "aws_iam_role_policy_attachment" "AmazonEC2ContainerRegistryReadOnly_" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
  role       = aws_iam_role.karpenter_node.name
}

resource "aws_iam_instance_profile" "karpenter_node" {
  name = "KarpenterNodeInstanceProfile"
  role = aws_iam_role.karpenter_node.name
}
```

It is expected that the karpenter_node role will be present in aws_auth which will allow new nodes spawned by karpenter to register with the API server, but aws-auth configmap contains only the managed-group role if used while creating the cluster.

### Actual Behavior

aws-auth should contain the karpenter_node role as well

### Steps to Reproduce the Problem

Use the above karpenter helm config and see that aws-auth is not populated

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.46.0"
    }

    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.9"
    }

    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.7.0"
    }
  }

  required_version = "~> 1.3"
}
```

### Resource Specs and Logs

NA

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
nor helm no terraform know anything about `aws-auth`
as an operator is on you to update it to include the new role

**Comment by vivekkarne** [comment]
So will I have to get the current aws-auth configmap add to it and then update? I am using terraform hence all of this becomes cumbersome. Can i just pass a string to the helm karpenter chart's defaultInstanceProfile and can I expect it to create the role and update the configMap? I am not sure since there is very sparse documentation regarding this.

**Comment by FernandoMiguel** [comment]
yep, not easy with terraform and the current lack of CRDs for aws-auth.
blueprints uses a module and allows vars to pass along.
internally, we have a module that knows all the roles we create, and does a data lookup for them.
sadly we need to apply it on both the eks root module and the addons.

**Comment by ellistarn** [comment]
As @FernandoMiguel mentioned, this is the responsibility of installation tools like terraform or eksctl.
