### ISSUE TITLE
ECDSA verification failure on webhook call when updating provisioner

### ISSUE THREAD

**Issue by woehrl01** [aws/karpenter#3663]
### Version

__Karpenter Version:__ v0.27.1

__Kubernetes Version:__ v1.23

### Expected Behavior

Updating the provisioner

### Actual Behavior

Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.sh": failed to call webhook: Post "https://karpenter.karpenter.svc:443/default/karpenter.sh?timeout=10s": x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "karpenter.karpenter.svc")

### Steps to Reproduce the Problem

Modify an existing provisioner

### Resource Specs and Logs

\"https://karpenter.karpenter.svc:443/default/karpenter.sh?timeout=10s\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"karpenter.karpenter.svc\")"}2023-03-30T15:14:36.574Z	ERROR	controller	Reconciler error	{"commit": "7131be2-dirty", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "Provisioner": {"name":"default"}, "namespace": "", "name": "default", "reconcileID": "14460c1e-6391-47d9-b444-632489e8b134", "error": "Internal error occurred: failed calling webhook \"defaulting.webhook.karpenter.sh\": failed to call webhook: Post \"https://karpenter.karpenter.svc:443/default/karpenter.sh?timeout=10s\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"karpenter.karpenter.svc\")"}2023-03-30T15:14:36.628Z	ERROR	controller	Reconciler error	{"commit": "7131be2-dirty", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "Provisioner": {"name":"default"}, "namespace": "", "name": "default", "reconcileID": "2ea08894-19a8-49e0-ae26-1407a7d35c85", "error": "Internal error occurred: failed calling webhook \"defaulting.webhook.karpenter.sh\": failed to call webhook: Post \"https://karpenter.karpenter.svc:443/default/karpenter.sh?timeout=10s\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"karpenter.karpenter.svc\")"}2023-03-30T15:14:36.731Z	ERROR	controller	Reconciler error	{"commit": "7131be2-dirty", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "Provisioner": {"name":"default"}, "namespace": "", "name": "default", "reconcileID": "cdfc29dd-2033-47cb-ba50-887680014f21", "error": "Internal error occurred: failed calling webhook \"defaulting.webhook.karpenter.sh\": failed to call webhook: Post \"https://karpenter.karpenter.svc:443/default/karpenter.sh?timeout=10s\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"karpenter.karpenter.svc\")"}2023-03-30T15:14:36.910Z	ERROR	controller	Reconciler error	{"commit": "7131be2-dirty", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "Provisioner": {"name":"default"}, "namespace": "", "name": "default", "reconcileID": "fa32a757-b3e4-478e-a1ac-56c8af5fc476", "error": "Internal error occurred: failed calling webhook \"defaulting.webhook.karpenter.sh\": failed to call webhook: Post \"https://karpenter.karpenter.svc:443/default/karpenter.sh?timeout=10s\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"karpenter.karpenter.svc\")"}

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Can you provide the Karpenter logs? 

Are you using ArgoCD or Flux to install Karpenter? We've seen issues where Argo fights the webhook reconciler within the Karpenter controller and can cause these cert verficiation errors.

**Comment by woehrl01** [comment]
@bwagner5 yes, I'm using argocd. Is there anything I can do here? I already tried replace, deleting individual resources, etc.

The Karpenter logs are the provided ones, is there anything additional I should look for in the logs which could be helpful for you?

**Comment by bwagner5** [comment]
Can you try adding a block like this?

```
      ignoreDifferences:
      - kind: ValidatingWebhookConfiguration
        group: admissionregistration.k8s.io
        name: validation.webhook.karpenter.k8s.aws
        jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
      - kind: MutatingWebhookConfiguration
        group: admissionregistration.k8s.io
        name: defaulting.webhook.karpenter.k8s.aws
        jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
```

**Comment by woehrl01** [comment]
@bwagner5 I already had those `ignoreDifferences` in place, including that one:

```yaml
ignoreDifferences:
  - kind: Secret
    name: karpenter-cert
    jsonPointers:
      - /data
```

But removing those, also, don't make a difference.

**Comment by woehrl01** [comment]
Alright, I could find the issue, there was a duplicate webhook with a different name which wasn't deleted, during an upgrade:

`defaulting.webhook.karpenter.sh`

The new one is `defaulting.webhook.karpenter.k8s.aws`

I had to delete the old webhook, then everything worked again.

**Comment by hari-rad** [comment]
In 0.27.2, ClusterRole `karpenter-core` retains this
```
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["update"]
    resourceNames: ["defaulting.webhook.karpenter.sh"]
```
Should it be changed to the new MutatingWebhookConfiguration `defaulting.webhook.karpenter.k8s.aws`?
