### ISSUE TITLE
question: what is the best practices when doing blue/green eks cluster?

### ISSUE THREAD

**Issue by tuananh** [aws/karpenter#3670]
we have this use case where we need to do blue/green eks cluster: moving the whole workload from 1 cluster to another.

this is where it hits us.

we are doing gitops with argo-cd. for most of the workload, it's fine but karpenter requires certain resources to be provisioned in advance (sqs, eventbridge rules,...) and when we do blue/green, we will have to update our gitops repo for those new resources arn.

what would be the best practices in this case? can we share the resource (eg: sqs) for both blue & green cluster? I'm afraid it may cause problem if 2 karpenters instance were using the same queue at the same time.

**Comment by ellistarn** [comment]
You should make a fresh queue per cluster as part of cluster setup. Otherwise everything should work fine.

**Comment by tuananh** [comment]
Got it. Thanks.
