### ISSUE TITLE
A chart to install karpenter resources

### ISSUE THREAD

**Issue by vladarts** [aws/karpenter#3674]
### Tell us about your request

Hi!

We've developed a solution to automatically generate Helm Charts using Kubernetes Resources JSON Schemas. Using such charts, you can define all required resources in values.yaml file. There are also some features supported like templating support for string values. Our best product is [Simple Helm Chart](https://github.com/iponweb/charts/tree/main/charts/simple)

We have a separate chart for prometheus-operator resources only: [meta-karpenter](https://github.com/iponweb/charts/tree/main/charts/meta-karpenter)
It's maintenance is pretty simple - you only have to update chart [config](https://github.com/iponweb/charts/tree/main/charts/meta-karpenter/config) and re-generate the chart using updated karpenter resources schema.

If you interested in it, we can move the chart to the karpenter repository and you can offer users to use it instead of raw yaml.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

How to install Karpenter resources to Kubernetes using Helm Chart

### Are you currently working around this issue?

In Terraform, man cat use `kubectl_manifest` resource as alternative.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
We'd rather have the chart stay in your github org. We are trying to scope down what is house in the karpenter repos to the bare minimum so that the community can build and extend installation solutions on-top of what we're offering through things like helm, flux, argo, terraform, etc.
