### ISSUE TITLE
chart repo is not valid in offical karpenter page

### ISSUE THREAD

**Issue by arunteliolabs** [aws/karpenter#3690]
### What karpenter features are relevant?

Error: looks like "oci://public.ecr.aws/karpenter/karpenter" is not a valid chart repository or cannot be reached: object required

### How should the docs be improved?

please update proper docs that is very useful to implement

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
What command are you running to get that error? Karpenter uses an OCI repo which doesn't work as a helm repo (for listing versions, etc) but it does work for installing a chart.

**Comment by rr-paras-patel** [comment]
Facing same issue +1

**Comment by rr-krupesh-savaliya** [comment]
We are facing a similar issue: `Error: Failed to download "oci://public.ecr.aws/karpenter/karpenter"`
We are just installing a karpenter with the helm upgrade command.

can anyone please help here?

**Comment by ellistarn** [comment]
What command are you running to get that error?

**Comment by ellistarn** [comment]
The helm install is working for me here: https://karpenter.sh/v0.27.1/getting-started/getting-started-with-karpenter/#3-create-a-cluster

**Comment by rr-krupesh-savaliya** [comment]
Issue found. I am using the old Helm version `3.2.1`, which doesn't support OCI. I tried with the latest version and it's working fine. Thanks

**Comment by ellistarn** [comment]
👍
