### ISSUE TITLE
Karpenter can not evict pods in ONE availability zone if define spreadConstraints with maxSkew number

### ISSUE THREAD

**Issue by Yufeireal** [aws/karpenter#3694]
### Version

__Karpenter Version:__ v0.27.0

__Kubernetes Version:__ v1.22

Hi team, I filed a github issue two weeks ago https://github.com/aws/karpenter/issues/3641 
After doing some experimentation and trying to dive deep into some potential issues. I think it's actually a "bug" we need to fix or do a workaround as a new feature.

Created a notion doc to better explain the issue 
https://temporal-energy-11d.notion.site/Karpenter-issues-demo-f3ce32e6cbe542d5bfe0519994571f95

Karpenter's consolidation process will respect topologyConstraints(availability zone) and also hpa status to not consolidate the pods even the nodes are underutilized.

Btw, I think we should make Karpenter able to handle this situation. Since for Cluster Autoscaler, it will detect underutilized node and just shut them down. Then the pods on the underutilized node will be schedule elsewhere. 

### Expected Behavior

For example, during daytime, I have several pods on three availability zones, each az has approaching 60 pods running in 30 nodes. The CPU&memory request/allocatable ratio are pretty high.

During night, when the traffic goes down, there are only 20 pods distributed in 30 nodes in each az. And Karpenter fails to merge them into 5 or 6 nodes (the resource is enough to accomodate the pods, I promise).

### Actual Behavior

Instead of merging the workload to much fewer nodes, Karpenter will leave them over there in each az. And the log keeps throwing **"Not all pods will schedule”**

I think it's caused by topologyConstraints.
In the same AZ, when Karpenter wants to schedule pods from one underutilized node to another underutilized node, the pods will temporarily be evicted. Which will cause the total pods number in that az decrease (temporarily). And that will violate the spreadConstraints maxSkew number.

Then Karpenter will fail to schedule pods and throw "Not all pods will schedule".

Same for one of my service that the hpa does not allow scale down(When karpenter evict the pods, these temporary unavailable pods will violate the hpa status).

For detail information, check this doc I created 
https://temporal-energy-11d.notion.site/Karpenter-issues-demo-f3ce32e6cbe542d5bfe0519994571f95

### Steps to Reproduce the Problem

https://temporal-energy-11d.notion.site/Karpenter-issues-demo-f3ce32e6cbe542d5bfe0519994571f95

### Resource Specs and Logs

https://temporal-energy-11d.notion.site/Karpenter-issues-demo-f3ce32e6cbe542d5bfe0519994571f95 
All resource details are specified in this doc

The logs are just 
Normal.              Karpenter              Not all pods will schedule

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
> In the same AZ, when Karpenter wants to schedule pods from one underutilized node to another underutilized node, the pods will temporarily be evicted. Which will cause the total pods number in that az decrease (temporarily). And that will violate the spreadConstraints maxSkew number.

Karpenter simulates scheduling as if the pod is moved from the node it is considering consolidating to a) some other existing node or b) a new node. It doesn't care about the transient state in between.

> Same for one of my service that the hpa does not allow scale down(When karpenter evict the pods, these temporary unavailable pods will violate the hpa status).

I'm not following this part.  Karpenter isn't aware and has no special support for HPA.  It launches capacity for pending pods and consolidates when it can as long as it doesn't violate preferred or required scheduling constraints.

**Comment by Yufeireal** [comment]
Hi @tzneal  For the AZ issues, I mean if we have **3 pods** running on **3 machines** in each AZ(9 machines in total). And we define topologyConstraints for availability_zone with maxSkew = 1. Will this block Karpenter to consolidate 3 pods to 1 machine? Since in this process when Karpenter evicts the pods from 3 machines, those pods will become temporarily unavailable, which make the skew number in one AZ higher than 1.  (I am not super sure this is a potential issue, if we can confirm this is not an issue, I can continue debugging)

To clarify the second concerns, I'd better attach the hpa configuration here.

`  minReplicas: 1
  maxReplicas: 100
  metrics:
    # Order should be exactly like this due to https://github.com/argoproj/argo-cd/issues/1079.
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    # Scaling down disrupts active streams, so avoid it. Maintain enough
    # replicas to serve peak daily traffic, and just eat the cost.
    scaleDown:
      selectPolicy: Disabled
`

We define a behavior to disable scale down. Suppose we have 125 pods, so define this behavior is equal to define a hpa which has min replicas to 125. And when Karpenter tries to consolidate the nodes(evicts pods on them), I am wondering will this block Karpenter evicting the pods since it violate the min replicas status of hpa?

**Comment by ellistarn** [comment]
> Will this block Karpenter to consolidate 3 pods to 1 machine?

Yes -- Karpenter will not consolidate if it would impact skew. 

> I am wondering will this block Karpenter evicting the pods since it violate the min replicas status of hpa?

HPA will set replica count on the Deployment -- Karpenter won't touch this, it will just respond to existing pods.

**Comment by Yufeireal** [comment]
Hi, just to clarify the question. For the **"consolidate 3 pods to 1 machine"**, I didn't mean to let Karpenter schedule pods in us-west-2b and us-west-2c all to us-west-2a. What I mean is we have 9 pods in total, and in each az we have 3 pods.

So when traffic is low, in us-west-2a for example, we have 3 pods(request 2 cpu and 3Gi memory in total) But They are running on 2 nodes (each with 64 cpu and 128Gi memory). Does this mean Karpenter can not evict the pods to fit into one machine even the node utilization is low?  Though in **each** az, we still have 3 pods.

Is this expected, something happens like during daytime, we have 2 large capacity nodes running different kinds of pods(also includes the 3 pods we mentioned before), but when traffic goes low, some pods using large amount of resources are scaled down. If Karpenter can not consolidate, as a result, there are only 3 pods running  on 2 nodes instead of 1 node in each az?

**Comment by ellistarn** [comment]
@tzneal can correct me if I'm wrong, but I believe we should be able to consolidate one large node with 3 pods into one smaller node with 3 pods. The pods should evict one-by-one, maintaining topology spread.

I'll see if I can reproduce.

**Comment by tzneal** [comment]
Correct, we look at the resulting state.  We will follow preferred topology spreads/anti-affinities though.  If you have a preference to run in different AZs/nodes, we will follow your preference.
