### ISSUE TITLE
AWS Cloud Provider - ICE Cache to Make Packing Progress

### ISSUE THREAD

**Issue by bwagner5** [aws/karpenter#371]
If EC2 does not have capacity to support a request, karpenter may encounter an Insufficient Capacity Exception (ICE).  

This can happen due to limited instance type options because of defined constraints like AZs, enumerated instance types, special resources like GPUs, etc. 

Here are a few examples: 

1. A Large number of pods are being scheduled at once. Since karpenter tries to use bigger instance types to reduce cluster overhead (daemonsets, kubelet, etc), there may only be 1 or a few instance types that are passed to CreateFleet which would increase the chance of receiving an ICE. 
2. The Provisioner or Pods are restricted to 1 or a few instance types. Even if the resources requested by a group of pods is not that large, if the constraints severely limit the number of instance type options available, then an ICE could happen.
3. The pods require special resources like GPUs. Again, this will severely limit the instance type options and could result in an ICE. 

In order for karpenter's packing logic to make progress, the instance type provider can temporarily omit instance types that have resulted in an ICE. 

Example:

1. A group of pods are created that need 96 vcpus (disregarding overhead calculations for simplicity)
2. The provisioner is limited to using r5.4xlarge (16 vcpus), r5.8xlarge (32 vcpus), r5.24xlarge (96 vcpus)  
3.  The packer computes a packing for the r5.24xlarge and 1 instance type option is supplied to ec2 CreateFleet
4. CreateFleet returns an ICE for the r5.24xlarge, so it is blocked temporarily
5. The packer now computes a packing for 3 r5.8xlarge and is fulfilled by CreateFleet.

**Comment by eptiger** [comment]
Can you assign this to me?

**Comment by bwagner5** [comment]
If there's an alternative to the ICE Cache mentioned in this issue, feel free to discuss or implement something else. This is just the only idea we've had so far.
