### ISSUE TITLE
Karpenter images running dirty commit

### ISSUE THREAD

**Issue by gezb** [aws/karpenter#3711]
### Version

__Karpenter Version:__ v0.27.1@sha256:aa4c1b1dca9d928e4a04f63680ae14cc912bc1b02146e0d3d36c8cd873bbc1e9

__Kubernetes Version:__ v1.22.17

### Expected Behavior

Karpenter releases should run clean images.

### Actual Behavior

I am seeing a "-dirty" suffix on the git hash in the logs

e.g. 
`{"level":"INFO","time":"2023-04-06T09:19:49.872Z","logger":"controller","message":"Starting server","commit":"7131be2-dirty","path":"/metrics","kind":"metrics","addr":"[::]:8080"}` 

### Steps to Reproduce the Problem

I have just started evaluating Karpenter, using helm chart version 0.27.1 with no overrides on the image in my values

### Resource Specs and Logs

I think this looks to be a repeat of #3414

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
@njtran, what's the status here? Should this be burning?
