### ISSUE TITLE
Considering the termination pod as a factor when schedule a new POD

### ISSUE THREAD

**Issue by gaussye** [aws/karpenter#3729]
### Tell us about your request

Assume that we have a POD named podA is running on a Node named nodeA .  After a while podA is in termination status for some reason and it would take around 20 seconds to terminate. At this moment, podB (with the same cpu and memory request) creation request is triggered and in pending status because nodeA is full.  So a new Node named nodeB will be created for podB soon.  After a short while podB is created and running in nodeB, and podA is terminated. Now nodeA is not filled fully, neither nodeB if i set a large instance-type in the provisioner. Can we considerate the termination pod as a factor when schedule podB, for example just wait a few seconds for the termination of podA and then podB will be scheduled to nodeA. In this situation nodeA is fully utilized and nodeB will not be created.  Consolidation feature is an alternative way to do this but it solve the problem after scheduling and will cause some pods termination again. I just want to know if it is possible to make this happen before scheduling.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Now i can use consolidation feature to finish this but i want to know if we have a better way to do that.

### Are you currently working around this issue?

No.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Is this in reference to restarting a deployment?

**Comment by gaussye** [comment]
It is not about restarting a deployment. It is about the karpenter schedule algorithm will consider the terminating pods when new pods are triggered to schedule.

**Comment by tzneal** [comment]
Unfortunately pods can get stuck terminating for long period of time.  This would result in pods staying stuck pending. We follow the logic of the kube-scheduler in this regard.
