### ISSUE TITLE
After update to 0.27.1 not all merics from karpenter_nodes* are present 

### ISSUE THREAD

**Issue by E1v1s** [aws/karpenter#3736]
### Is an existing page relevant?

https://karpenter.sh/v0.27.1/concepts/metrics/

### What karpenter features are relevant?

metrics

### How should the docs be improved?

but it's present in https://karpenter.sh/v0.27.1/concepts/metrics/
so i'm looking why it's absent

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
What specific metrics are you looking for that you don't see?
