### ISSUE TITLE
Incorrect release notes for v0.27.2

### ISSUE THREAD

**Issue by guessi** [aws/karpenter#3744]
### Is an existing page relevant?

https://github.com/aws/karpenter/releases/tag/v0.27.2

### Note:
* It is okay for karpenter-core: https://github.com/aws/karpenter-core/releases/tag/v0.27.2
* But not okay for karpenter: https://github.com/aws/karpenter/releases/tag/v0.27.2

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/984415/231437517-a250aa47-a131-4c9c-b7bf-0d96ef89df0a.png">

### How should the docs be improved?

When corss referencing PR links, should include with full links instead of shortcut reference `#279`, `#288`.

### Correct:
* https://github.com/aws/karpenter-core/pull/279
* https://github.com/aws/karpenter-core/pull/288

### Incorrect ( ref with shortcut `#279`, `#288`):
* #279
* #288

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Thanks for reporting, fixed!
