### ISSUE TITLE
Some nodes are not consolidated

### ISSUE THREAD

**Issue by AndrzejWisniewski** [aws/karpenter#3753]
### Version

__Karpenter Version:__ v0.27.0

__Kubernetes Version:__ v1.24.10

### Expected Behavior

1. I have a node (`ip-10-1-60-88.us-west-2.compute.internal`) where are onlyfew pods started within daemonsets and one pod (coredns) started within deployment. Node is almost 'empty' (cpu/mem requested near 0%).
2. There are also other, almost 'empty', nodes but consolidation is not done.
3. When I delete (above described) coredns pod, the new one coredns pod is started in the other (already existing) node and after about 3 minutes, `ip-10-1-60-88.us-west-2.compute.internal` node is deprovisioned (consolidated by deleting).

I expect it should be done (consolidation) automatically (without my manual 'delete').

### Actual Behavior

Consolidation is not done.

### Steps to Reproduce the Problem

I can observe such situation every night in our envs so I believe it can be reproduced within below info (configurations/descriptions for pod/node).

### Resource Specs and Logs

1. We have some almost empty nodes:
```
> kb resource-capacity -u --sort cpu.request
NODE                                         CPU REQUESTS    CPU LIMITS     CPU UTIL        MEMORY REQUESTS   MEMORY LIMITS   MEMORY UTIL
(...)
ip-10-1-204-234.us-west-2.compute.internal   10650m (22%)    0Mi (0%)       4677m (9%)      21579Mi (23%)     0Mi (0%)        15892Mi (17%)
ip-10-1-49-8.us-west-2.compute.internal      16700m (34%)    0Mi (0%)       6328m (13%)     28511Mi (31%)     0Mi (0%)        11205Mi (12%)
ip-10-1-221-166.us-west-2.compute.internal   3850m (8%)      0Mi (0%)       1702m (3%)      7065Mi (7%)       170Mi (0%)      21365Mi (23%)
ip-10-1-178-96.us-west-2.compute.internal    3200m (6%)      1250m (2%)     3206m (6%)      3813Mi (2%)       4394Mi (2%)     24464Mi (13%)
ip-10-1-162-70.us-west-2.compute.internal    2550m (5%)      1000m (2%)     2246m (4%)      1935Mi (1%)       2602Mi (1%)     23164Mi (12%)
ip-10-1-216-255.us-west-2.compute.internal   2500m (5%)      1000m (2%)     2201m (4%)      6359Mi (7%)       2048Mi (2%)     26832Mi (29%)
ip-10-1-60-88.us-west-2.compute.internal     250m (0%)       0Mi (0%)       847m (1%)       145Mi (0%)        170Mi (0%)      10084Mi (11%)
```

2. Those nodes are in diff AZ:
```
> kb get node  -L node.kubernetes.io/instance-type -L topology.kubernetes.io/zone  ip-10-1-60-88.us-west-2.compute.internal ip-10-1-216-255.us-west-2.compute.internal ip-10-1-162-70.us-west-2.compute.internal ip-10-1-178-96.us-west-2.compute.internal ip-10-1-221-166.us-west-2.compute.internal ip-10-1-188-150.us-west-2.compute.internal ip-10-1-204-234.us-west-2.compute.internal ip-10-1-49-8.us-west-2.compute.internal

NAME                                         STATUS   ROLES    AGE     VERSION                          INSTANCE-TYPE   ZONE
ip-10-1-60-88.us-west-2.compute.internal     Ready    <none>   41h     v1.24.10-eks-08ad9cc     c5.12xlarge     us-west-2b
ip-10-1-216-255.us-west-2.compute.internal   Ready    <none>   44h     v1.24.10-eks-08ad9cc     c5.12xlarge     us-west-2a
ip-10-1-162-70.us-west-2.compute.internal    Ready    <none>   2d20h   v1.24.10-eks-08ad9cc     m5.12xlarge     us-west-2c
ip-10-1-178-96.us-west-2.compute.internal    Ready    <none>   3d10h   v1.24.10-eks-08ad9cc     m5.12xlarge     us-west-2c
ip-10-1-221-166.us-west-2.compute.internal   Ready    <none>   2d3h    v1.24.10-eks-08ad9cc     c5.12xlarge     us-west-2a
ip-10-1-188-150.us-west-2.compute.internal   Ready    <none>   16h     v1.24.10-eks-08ad9cc     c5.4xlarge      us-west-2c
ip-10-1-204-234.us-west-2.compute.internal   Ready    <none>   15h     v1.24.10-eks-08ad9cc     c5.12xlarge     us-west-2a
ip-10-1-49-8.us-west-2.compute.internal      Ready    <none>   42h     v1.24.10-eks-08ad9cc     c5.12xlarge     us-west-2b
```

3. In one node (similar situation is in other nodes but let's focus on this one node only) there are few daemonset's pods and only one (coredns) deployment's pod:
```
> kb get pods -A -o wide | grep ip-10-1-60-88.us-west-2.compute.internal
(...)
kube-system                  coredns-799c5565b4-hbmqc                                     1/1     Running       0                40h     100.92.204.117   ip-10-1-60-88.us-west-2.compute.internal     <none>           <none>
```

4. Part of this coredns pod configuration which I believe can be connected with consolidation process:
```
> kb get pod coredns-799c5565b4-hbmqc -n kube-system -o yaml
(...)
labels:
    (...)
    k8s-app: kube-dns
(...)
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
            - arm64
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - kube-dns
          topologyKey: kubernetes.io/hostname
        weight: 100
(...)
  containers:
  (...)
      resources:
      limits:
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 70Mi
(...)
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```
5. Node description:
```
> kb describe node ip-10-1-60-88.us-west-2.compute.internal
(...)
Name:               ip-10-1-60-88.us-west-2.compute.internal
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=c5.12xlarge
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-west-2
                    failure-domain.beta.kubernetes.io/zone=us-west-2b
                    karpenter.k8s.aws/instance-category=c
                    karpenter.k8s.aws/instance-cpu=48
                    karpenter.k8s.aws/instance-family=c5
                    karpenter.k8s.aws/instance-generation=5
                    karpenter.k8s.aws/instance-hypervisor=nitro
                    karpenter.k8s.aws/instance-memory=98304
                    karpenter.k8s.aws/instance-network-bandwidth=12000
                    karpenter.k8s.aws/instance-pods=234
                    karpenter.k8s.aws/instance-size=12xlarge
                    karpenter.sh/capacity-type=spot
                    karpenter.sh/initialized=true
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ip-10-1-60-88.us-west-2.compute.internal
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=c5.12xlarge
                    topology.kubernetes.io/region=us-west-2
                    topology.kubernetes.io/zone=us-west-2b
                    vpc.amazonaws.com/eniConfig=us-west-2b
                    (...)
Annotations:        
                    alpha.kubernetes.io/provided-node-ip: 10.1.60.88
                    node.alpha.kubernetes.io/ttl: 15
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Tue, 11 Apr 2023 14:15:41 +0200
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  ip-10-1-60-88.us-west-2.compute.internal
  AcquireTime:     <unset>
  RenewTime:       Thu, 13 Apr 2023 07:41:06 +0200
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 13 Apr 2023 07:37:38 +0200   Tue, 11 Apr 2023 14:16:00 +0200   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 13 Apr 2023 07:37:38 +0200   Tue, 11 Apr 2023 14:16:00 +0200   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 13 Apr 2023 07:37:38 +0200   Tue, 11 Apr 2023 14:16:00 +0200   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Thu, 13 Apr 2023 07:37:38 +0200   Tue, 11 Apr 2023 14:16:31 +0200   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:   10.1.60.88
  Hostname:     ip-10-1-60-88.us-west-2.compute.internal
  InternalDNS:  ip-10-1-60-88.us-west-2.compute.internal
Capacity:
  attachable-volumes-aws-ebs:  25
  cpu:                         48
  ephemeral-storage:           154797828Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      96674548Ki
  pods:                        234
Allocatable:
  attachable-volumes-aws-ebs:  25
  cpu:                         47810m
  ephemeral-storage:           153749252Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      95038368299
  pods:                        234
System Info:
 (...)
  Kernel Version:             5.15.90
  OS Image:                   Bottlerocket OS 1.13.2 (aws-k8s-1.24)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.19+bottlerocket
  Kubelet Version:            v1.24.10-eks-08ad9cc
  Kube-Proxy Version:         v1.24.10-eks-08ad9cc
ProviderID:                   aws:///us-west-2b/i-019ce758f8a6cb075
Non-terminated Pods:          (6 in total)
 (...)
Events:                       <none>
```

7. When I removed this pod manually from the node (` delete pod coredns-799c5565b4-hbmqc -n kube-system`) new cordns pod was created in other (already existing) node:
```
> kb get pods -A -o wide | grep coredns
(...)
kube-system                  coredns-799c5565b4-dfklg                                     1/1     Running     0                42s     100.93.201.16    ip-10-1-188-150.us-west-2.compute.internal   <none>           <none>
```

8. About 3 minutes later I can see such log in karpenter:
```
2023-04-13T05:49:45.301Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 1 nodes ip-10-1-60-88.us-west-2.compute.internal/c5.12xlarge/spot	{"commit": "dc3af1a"}
2023-04-13T05:49:45.313Z	INFO	controller.termination	cordoned node	{"commit": "dc3af1a", "node": "ip-10-1-60-88.us-west-2.compute.internal"}
2023-04-13T05:49:45.640Z	INFO	controller.termination	deleted node	{"commit": "dc3af1a", "node": "ip-10-1-60-88.us-west-2.compute.internal"}
```

9. There is no PDB configured for coredns.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by AndrzejWisniewski** [comment]
FYI: We didn't upgrade karpenter to v0.27.2 as we are waiting when this [PR](https://github.com/aws/karpenter/pull/3675) will be in the release. But I believe there are no changes in the last two releases which can address/resolve such issue.

**Comment by tl-alex-nicot** [comment]
do you have consolidation enabled or are you using ttlsecondsafterempty my understanding with the latter is that until all non daemonset pods are off the node it wont begin a countdown to terminate 

`Karpenter notes when the last workload (non-daemonset) pod stops running on a node. From that point, Karpenter waits the number of seconds set by ttlSecondsAfterEmpty in the provisioner, then Karpenter requests to delete the node. This feature can keep costs down by removing nodes that are no longer being used for workloads.`

**Comment by AndrzejWisniewski** [comment]
Hi @tzneal . Thank you for your answer and information!

> You have a preferred anti-affinity that Karpenter is respecting. You've indicated that you prefer those pods to not run on the same node, so Karpenter is not consolidating to respect your preferences

As we had much more nodes still run in our cluster where the coredns pod could be started, Karpenter could consolidate (respecting our preferred anti-affinity) this node.

**Comment by tzneal** [comment]
There was a bug in v0.27.0 where deprovisioning in general would slow down, it should be fixed in v0.27.2.  You would need to debug this by running `kubectl describe node node-name` on the node that you expect to deprovision.  Karpenter records events there to identify why the node is not consolidatable.  In general though if you use any preferred anti-affinities/topology spreads, we will respect them and your cluster will not end up packed as tightly as it could be.

**Comment by AndrzejWisniewski** [comment]
I did it (`kubectl describe node node-name`) and there was no any event :/ (you can see some part (including events) of this node description above in point `5. Node description`).

**Comment by AndrzejWisniewski** [comment]
> We didn't upgrade karpenter to v0.27.2 as we are waiting when this https://github.com/aws/karpenter/pull/3675 will be in the release.

**Comment by tzneal** [comment]
You can also restart the Karpenter deployment which will also reset any slow deprovisioning for a while.

**Comment by AndrzejWisniewski** [comment]
@tzneal Tx for a hint - I will try to restart Karpenter pods and I will check in next 12h if it works better (will put then some info here).

**Comment by tzneal** [comment]
It will log those messages a few times per hour and the events only last for 1 hour, so check within an hour of restarting Karpenter. You should see events like:

**Comment by AndrzejWisniewski** [comment]
Seems workaround works (consolidation feature consolidate also nodes which were not consolidated before (those described above)). Tx @tzneal again for the workaround hint. 

@tzneal Do you know maybe when new Karpenter release within [this](https://github.com/aws/karpenter/pull/3675) change is planned?

**Comment by tzneal** [comment]
v0.27.2 should have this issue resolved, if you still experience this problem after upgrading, please re-open.

**Comment by shay-ul** [comment]
Hey @tzneal, we are experiencing a similar issue with Karpenter 0.27.2. Very slow to non-existent deprovisioning on nodes that are near empty. Restarting the Karpenter deployment immediately initiates the process (controller.deprovisioning) and nodes start to deprovision quickly.
On some nodes we see the "not all pods would schedule"  Events before we restart the Karpenter deployment, but after the restart those nodes are immediately deleted.
This is very costly for us since we are running at scale with peak hours. in peak hours we run ~200 nodes which we expect to decrease over 4 hours to around ~30 nodes. This means the consolidation feature is critical for us in terms of cost.
Any idea how we can troubleshoot this?
Thanks
