### ISSUE TITLE
AMI update in provisioner triggers existing nodes to be removed and new nodes spun up immediately

### ISSUE THREAD

**Issue by ben5556** [aws/karpenter#3760]
### What karpenter features are relevant?

Drift feature

### How should the docs be improved?

On karpenter v0.20.0 where Drift feature is non-existent (if I understand it correctly it is introduced in v0.21.0?) why is karpenter de-provisioning existing nodes and launching new nodes immediately on updating the AMI in provisioner ?

If this is expected behaviour, we need to document the same. Please clarify that would help a lot!

We upgraded EKS from 1.21 to 1.22
Updated provisioner yaml and applied it

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
It shouldn't do this.  Can you provide Karpenter logs showing this occurring?

**Comment by ben5556** [comment]
Sorry! Closing this as it turned out to be a human error
