### ISSUE TITLE
Helm chart issue for upgrading karpenter by terraform

### ISSUE THREAD

**Issue by behnm** [aws/karpenter#3761]
### Version

I want to upgrade my karpenter from 0.16.3 to 0.27.2. The blow lines are my configuration in terraform.

```
resource "helm_release" "karpenter" {
  namespace        = "karpenter"
  name             = "karpenter"
  repository       = "public.ecr.aws/karpenter"
  chart            = "karpenter"
  version          = "v0.27.2"
```
Ive searched  alot, but non of solutions such as `docker logout`, or using `ecrpublic_token` helped me .
I have no idea what kind of solution can help me.

Version of helm provider on terraform:
provider "registry.terraform.io/hashicorp/helm" = "2.4.1"

### Expected Behavior

upgrading karpenter from 0.16.3 to v0.27.2

### Actual Behavior

Gives an error related to failure in downloading karpenter image

### Steps to Reproduce the Problem

Having a helm_release resource to install karpenter

### Resource Specs and Logs

```
│ Error: failed to download "public.ecr.aws/karpenter/karpenter" at version "v0.27.2"

ERRO[0412] 1 error occurred:
        * exit status 1
          
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
The helm terraform provider 2.4.1 does not support OCI repositories.  You'll need to upgrade to a newer version.

**Comment by tzneal** [comment]
I'll close this as it appears to be due to using an old version, but feel free to re-open if you still run into issues.

**Comment by behnm** [comment]
I have upgraded my helm provider to latest . `registry.terraform.io/hashicorp/helm = 2.9.0`
But is gives me the error.

`Error: repo public.ecr.aws not found`

**Comment by behnm** [comment]
It's solved. After upgrading helm provider, I forgot to add `v` in version. 

`version          = "v0.27.3"`

**Comment by aditya-pingsafe** [comment]
I am facing the same issue. Helm provider version is v2.9.0. 
![Screenshot 2023-04-29 at 2 47 12 AM](https://user-images.githubusercontent.com/122784506/235255815-b3ee5579-798e-4d4f-99fc-ce0d0404bceb.jpg)

The helm_release config is 
```
resource "helm_release" "karpenter" {
  namespace        = "karpenter"
  create_namespace = true
  name             = "karpenter"
  repository       = "public.ecr.aws/karpenter"
  chart            = "karpenter"
  version          = "v0.27.3"
```

But I am getting this error
![Screenshot 2023-04-29 at 2 51 10 AM](https://user-images.githubusercontent.com/122784506/235256314-115eb055-9295-4377-aaf7-e74094597b57.jpg)

@behnm Can you please share your updated `helm_release` config.

**Comment by aditya-pingsafe** [comment]
It worked with this config 

```
resource "helm_release" "karpenter" {
  namespace        = "karpenter"
  create_namespace = true
  name             = "karpenter"
  repository       = "oci://public.ecr.aws/karpenter"
  chart            = "karpenter"
  version          = "v0.27.3"

```

**Comment by jpat-te** [comment]
Assuming we have the needed terraform and helm versions, does this mean that by just changing the version number and applying the terraform change, karpenter gets upgraded ?

**Comment by BikesAndBBQ** [comment]
Recent versions seem to have dropped the "v" prefix, so this is working for me with a recent release:

```
resource "helm_release" "karpenter" {
  name             = "karpenter"
  namespace        = "karpenter"
  create_namespace = true
  repository       = "oci://public.ecr.aws/karpenter"
  chart            = "karpenter"
  version          = "0.36.0"
}

```
