### ISSUE TITLE
Karpenter erroring with "Could not wait for Cache to sync"

### ISSUE THREAD

**Issue by ra-grover** [aws/karpenter#3765]
### Version

__Karpenter Version:__ v0.25.0

__Kubernetes Version:__  v1.23.16-eks-48e63af

### Expected Behavior

We have a huge cluster having 20K+ Pods and around 2200 Nodes. Karpenter informers shouldn't timeout and there should be an option to tweak the timeout.

### Actual Behavior

Logs point to the fact that Karpenter was not able to sync informer caches. 

### Steps to Reproduce the Problem

We turned off consolidation in our Provisioners to make Karpenter work, and gave it 6Gigs of memory. 

### Resource Specs and Logs

Few of the log entries:
```	Could not wait for Cache to sync	{"commit": "beb0a64-dirty", "controller": "node", "controllerGroup": "", "controllerKind": "Node", "error": "failed to wait for node caches to sync: failed to get informer from cache: Timeout: failed waiting for *v1alpha5.Provisioner Informer to sync"}```

```{"commit": "beb0a64-dirty", "controller": "node", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"<REDACTED>.us-west-2.compute.internal"}, "namespace": "", "name": <REDACTED>.us-west-2.compute.internal", "reconcileID": "ab8d6386-e166-4541-8903-31f9c993b6cb", "error": "Timeout: failed waiting for *v1.Node Informer to sync"}```

```ERROR	controller.deprovisioning	determining candidate nodes, listing provisioners, Timeout: failed waiting for *v1alpha5.Provisioner Informer to sync	{"commit": "beb0a64-dirty"}```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Can you share the output of `kubectl get crds` on your cluster?

**Comment by ra-grover** [comment]
I fear thats huge list, because we have Crossplane which generates 100s of CRDs.
For now, let me know if only the count works for you ?
```
k get crds | wc -l
     295
```

**Comment by jonathan-innis** [comment]
I'm mainly just interested in Karpenter crds so you could just do `kubectl get crds | grep karpenter`

**Comment by ra-grover** [comment]
Sure.
``` 
awsnodetemplates.karpenter.k8s.aws                                2022-09-13T07:53:05Z
karpenterreservednode.constraints.gatekeeper.sh                   2022-03-31T11:44:59Z
provisioners.karpenter.sh
```

**Comment by jonathan-innis** [comment]
Got it, so the issue _does_ appear to be related directly to the cache timeout. I'm surprised that the Provisioner informer cache timed out. How many Provisioners are you running with Karpenter on your system?

**Comment by ra-grover** [comment]
Just 4 Provisioners. The logs above also contains Node timeouts:
```
"Timeout: failed waiting for *v1.Node Informer to sync"}
```

**Comment by jonathan-innis** [comment]
Would extending the current timeout to work such that it works at your scale be sufficient? I'm mainly just wondering if we need to expose this as a config option if we can just wait for a longer time than the default controller-runtime setup gives us.

**Comment by jonathan-innis** [comment]
> The logs above also contains Node timeouts

I'll try and repro this at the same scale. I'm surprised it's Node informer timeouts and not also Pod informer timeouts. Especially at the scale of pods that you are running at, I'd expect that to the main thing to be timing out here.

**Comment by ra-grover** [comment]
> Would extending the current timeout to work such that it works at your scale be sufficient? I'm mainly just wondering if we need to expose this as a config option if we can just wait for a longer time than the default controller-runtime setup gives us.

I am going to turn on the consolidation back on again on Monday, and see if we again face these timeouts. 
If we again see those issue, we may need that as a config option to see if that works. 
How many controllers does consolidation alone run ?

**Comment by jonathan-innis** [comment]
> I am going to turn on the consolidation back on again on Monday, and see if we again face these timeouts

Ah, so this issue went away when you turned off consolidation? What are your CPU requests that you are running the Karpenter pod on?

> How many controllers does consolidation alone run

It's a single controller that runs in a loop but it is fairly cpu-intensive as it's doing a lot of computation to mock out the best cost-savings for your cluster

**Comment by ra-grover** [comment]
Resources for Karpenter.
```resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 6Gi
```

> Ah, so this issue went away when you turned off consolidation? 

Yeah thats the theory, because we raised memory to 6Gigs and still Karpenter didn't launch instances. I can confirm this with team, if we want to enable consolidation next Week to confirm if current resources dont allow consolidation to work, because its production and might cause an outage. 

Also apart from manually matching the pod startup timestamp and the first instance launch timestamp, is there any metric that gives us this information related to the time taken for controllers to be fully ready. 

I believe its taking almost 15 mins after a Karpnter pod restart to finally be ready.

**Comment by jonathan-innis** [comment]
>I believe its taking almost 15 mins after a Karpnter pod restart to finally be ready.

That's surprising. That certainly shouldn't be the case. If you're able to repro this, we definitely need to dig into what's bottlenecking here.

**Comment by alagukannan** [comment]
I ran into the same issue once I turned of the settings.featureGates.driftEnabled to true as well. I'm stuck on cluster sync for close to 16m now

```
2023-04-18T17:30:51.567Z	DEBUG	controller.inflightchecks	discovered EC2 instance types zonal offerings for subnets	{"commit": "d01ea11-dirty", "node": "ip-xxx.us-west-2.compute.internal", "subnet-selector": "{\"karpenter.sh/discovery\":\"xxxx\"}"}
2023-04-18T17:30:51.690Z	DEBUG	controller.deprovisioning	waiting on cluster sync	{"commit": "d01ea11-dirty"}
```

**Comment by alagukannan** [comment]
> 

I was able to add more CPU to 2.0 and memory of 4 GB which solved the issue

**Comment by jonathan-innis** [comment]
> I'm stuck on cluster sync for close to 16m now

I don't think it's actually waiting on cluster sync in this case. If it was waiting on cluster sync you would [keep seeing the log over and over again](https://github.com/aws/karpenter-core/blob/main/pkg/controllers/deprovisioning/controller.go#L122). I suspect in this case, the controller is doing scheduling calculations and that's what's holding the log here. Do you see any logs in DEBUG that start with "abnormal time between runs of"?

**Comment by alagukannan** [comment]
> > I'm stuck on cluster sync for close to 16m now
> 
> I don't think it's actually waiting on cluster sync in this case. If it was waiting on cluster sync you would [keep seeing the log over and over again](https://github.com/aws/karpenter-core/blob/main/pkg/controllers/deprovisioning/controller.go#L122). I suspect in this case, the controller is doing scheduling calculations and that's what's holding the log here. Do you see any logs in DEBUG that start with "abnormal time between runs of"?

No I don't see any issues of that sort but increasing CPU is the one solved it. These clusters are only about 10 nodes and 1000 pods.

**Comment by ra-grover** [comment]
Does these logs point out to the fact that it is taking time ?

```2023-04-18T17:02:20.611Z	INFO	controller	Starting workers	{"commit": "beb0a64-dirty", "controller": "provisionerstate", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "worker count": 10}
2023-04-18T17:02:20.616Z	INFO	controller	Starting workers	{"commit": "beb0a64-dirty", "controller": "node", "controllerGroup": "", "controllerKind": "Node", "worker count": 10}
2023-04-18T17:02:20.656Z	INFO	controller	Starting workers	{"commit": "beb0a64-dirty", "controller": "provisionermetrics", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "worker count": 1}
2023-04-18T17:02:20.838Z	INFO	controller	Starting workers	{"commit": "beb0a64-dirty", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "worker count": 10}
2023-04-18T17:02:20.839Z	INFO	controller	Starting workers	{"commit": "beb0a64-dirty", "controller": "inflightchecks", "controllerGroup": "", "controllerKind": "Node", "worker count": 10}
2023-04-18T17:02:20.979Z	DEBUG	controller.awsnodetemplate	discovered subnets	{"commit": "beb0a64-dirty", "awsnodetemplate": "<REDACTED>", "subnets": ["<REDACTED>(us-west-2b)", "<REDACTED> (us-west-2c)", "<REDACTED> (us-west-2a)"]}
2023-04-18T17:02:21.766Z	DEBUG	controller.awsnodetemplate	discovered security groups	{"commit": "beb0a64-dirty", "awsnodetemplate": "<REDACTED>", "security-groups": ["<REDACTED>", "<REDACTED>"]}
2023/04/18 17:02:22 http: TLS handshake error from 100.125.38.179:55942: EOF
2023-04-18T17:02:22.756Z	DEBUG	controller.deprovisioning	discovered EC2 instance types	{"commit": "beb0a64-dirty", "instance-type-count": 627}
2023-04-18T17:02:23.269Z	DEBUG	controller.inflightchecks	discovered EC2 instance types zonal offerings for subnets	{"commit": "beb0a64-dirty", "node": "<REDACTED>", "subnet-selector": "<REDACTED>"}
2023/04/18 17:12:22 http: TLS handshake error from 100.125.38.179:44692: EOF
2023/04/18 17:27:23 http: TLS handshake error from 100.125.38.179:33210: EOF
2023-04-18T17:27:51.023Z	INFO	controller.provisioner	pod <REDACTED> has a preferred Anti-Affinity which can prevent consolidation	{"commit": "beb0a64-dirty"}
2023-04-18T17:27:51.023Z	INFO	controller.provisioner	pod <REDACTED> has a preferred Anti-Affinity which can prevent consolidation	{"commit": "beb0a64-dirty"}
2023-04-18T17:27:51.737Z	DEBUG	controller.provisioner	relaxing soft constraints for pod since it previously failed to schedule, removing: spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0]={"weight":100,"podAffinityTerm":{"labelSelector":{"matchLabels":{"name":"deployment-name"}},"topologyKey":"kubernetes.io/hostname"}}	{"commit": "beb0a64-dirty", "pod": "<REDACTED>"}
2023-04-18T17:27:51.801Z	DEBUG	controller.provisioner	relaxing soft constraints for pod since it previously failed to 
2023-04-18T17:27:51.931Z
```
The start logs are from 17:02 but the first log from provisioner controller is at 17:27. This is with consolidation off.

**Comment by jonathan-innis** [comment]
> The start logs are from 17:02 but the first log from provisioner controller is at 17:27

At the point where you start getting the "discovered" messages, the caches should be synced and the controller should be ready to receive pending pods. Are you seeing pending pods that Karpenter should consider not being considered until after that 25 minute timeframe?

**Comment by njtran** [comment]
Closing this one as communicated with @ra-grover over slack
