### ISSUE TITLE
Configure Karpenter to watch a subset of Pods for scheduling

### ISSUE THREAD

**Issue by sidewinder12s** [aws/karpenter#3768]
### Tell us about your request

I have Batch compute clusters in which we run a custom autoscaler (and dedicated kube-scheduler instance). We've migrated to Karpenter to manage the non-workload containers/dedicated set of system nodes we run the cluster controllers on.

As we deployed Karpenter we discovered as the cluster/number of pods increased the resource requirements of Karpenter ballooned. 

Would it be possible to configure Karpenter to only be concerned with these system nodes/pods? We do have a single provisioner configured with affinities and taints so that Karpenter can only launch nodes for these system workloads, but watching all the pods that are running through the system is adding a significant amount of load (we did have the same problem with Cluster Autoscaler). 

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Configure Karpenter to only watch a subset of pods in the cluster.

### Are you currently working around this issue?

So far, feeding Karpenter more resources has kept it stable but it might be throwing errors we're not aware of yet.

### Additional Context

Node Count: ~1400
Pod Count: ~25k+

Asked similar in slack: https://kubernetes.slack.com/archives/C02SFFZSA2K/p1681497443197849

Previous art: #1493, #1509

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sftim** [comment]
Should Karpenter also expect an additional restriction on those Pods? For example, document an expectation for particular tolerations (so that the scheduler doesn't use a Karpenter-managed node to run some other workload that Karpenter isn't watching?)

**Comment by sidewinder12s** [comment]
With both Karpenter and CAS previously, we just configured both systems only with a Node configuration that'd support the pods it should be worried about. We run all our 'cluster components' in a dedicated node pool with all cluster component workloads explicitly setting affinities and tolerations for it, so we only create a provisioner with those affinities and tolerations set. 

I think CAS had the same issue where it'd require a lot of resources to watch a bunch of work it shouldn't care about. 

I think both those options for limiting would work in our case, but I know you folks said this is somewhat complicated cause Karpenter is behaving like the scheduler and the scheduler does not have many nobs to limit what pods it should be worried about. 

Also in our case however, we do have our Batch pods all using a dedicated Kubernetes Scheduler while the cluster components are using the default scheduler managed by Kubernetes. Perhaps that could also be a pivot point, though that would increase the cost for users to be able to utilize this feature.

**Comment by ellistarn** [comment]
Realistically, I don't see a way for us to redesign Karpenter in a way that only looks at a subset of pods and nodes. Scheduling is a global concept, and if we're unable to observe some pods/nodes, we won't be able to support basic things like topology, affinity, or in flight capacity.
