### ISSUE TITLE
E2E Testing Snapshot Race Condition

### ISSUE THREAD

**Issue by engedaam** [aws/karpenter#3774]
### Version

__Karpenter Version:__ v0.27.2

__Kubernetes Version:__ v1.23.0

### Expected Behavior

E2E tests should wait to have snapshots finish the creation process before the e2e tests are run.

### Actual Behavior

We see e2e tests failing due to a snapshot not being existing in the ECR. 

### Steps to Reproduce the Problem

See in the E2E test Logs

### Resource Specs and Logs

NA

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
This is still an issue that we need to track, but was not the root cause of our current failure.s
