### ISSUE TITLE
Let karpenter to check possible free capacity reservations and start that instances first.

### ISSUE THREAD

**Issue by iaroslav-nakonechnikov** [aws/karpenter#3779]
### Tell us about your request

let karpenter to check free slots in capacity reservations, and utilize it with priority

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

as we are hosting our servers in Frankfurt, we see lots of issues with capacity. 
So we created capacity reservations and noticed, that karpenter ignores it, and creates instance with defined instance type, but in different AZ.

### Are you currently working around this issue?

as we need to keep system working - we had to disbalance nodes across AZs, so for example now we have:
2 instances in eu-central-1a, 5 instances in eu-central-1b and 8 instances in eu-central-1c. 

but we would like to see that it started in more balanced way.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
There's an issue (https://github.com/aws/karpenter/issues/3042) covering AWS Capacity Reservation, so I encourage to +1 that issue and add the context around your use-case.
