### ISSUE TITLE
very slow Karpenter consolidation

### ISSUE THREAD

**Issue by shay-ul** [aws/karpenter#3785]
### Version

__Karpenter Version:__ v0.27.2

__Kubernetes Version:__ v1.25.0

### Expected Behavior

1. We have peak hours where hundreds of nodes are being provisioned.
2. In a matter of hours, most of the workload (deployments) is scaled down or deleted.
3. We expect rapid decrease in node count using the consolidation method.

### Actual Behavior

We see very slow consolidation. When we restart the Karpenter pods, we see Karpenter immediately starts working as expected.

We first witnessed this issue on April 17th, we did not understand what is going on so we restarted Karpenter at around 7am, and then we saw a decrease in node count. After investigating, we came across https://github.com/aws/karpenter/issues/3576 which suggested we should upgrade to 0.27.2 to avoid this issue, and so we did. 
April 18th looked fantastic, Karpenter started consolidation at 4am and by the time we started working at 7am the node count was great and we declared this issue as resolved.
On April 19th and today (April 20th) we woke up to see we have many nodes, we restarted Karpenter and again the consolidation started working again.

All of this can be witnessed here:
![Screenshot from 2023-04-20 10-58-04](https://user-images.githubusercontent.com/64831892/233299454-1e221fb1-a8f5-408c-8993-c2df3d8d8d3c.png)

In comparison to the overall number of pods in the cluster, we can see that the peak starts at 1:30am (UTC+3). We have 15k pods running at peak. by 5am we have less than 5k pods, which means that by 5:30am we should have much less nodes on the cluster:
![Screenshot from 2023-04-20 11-29-16](https://user-images.githubusercontent.com/64831892/233307463-a726c48f-42b0-430f-b585-2d898d0e94f1.png)

### Steps to Reproduce the Problem

I have the full log of the Karpenter controller before we restarted the deployments. While it does look like the controller.deprovision is doing **some** work, it is very slow to initiate the process and we expect many more nodes to be already gone by this point:

```
2023-04-20T04:42:37.773Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 8 machines ip-192-168-1-180.us-east-2.compute.internal/c5a.xlarge/spot, ip-192-168-1-48.us-east-2.compute.internal/c5a.xlarge/spot, ip-192-168-1-240.us-east-2.compute.internal/c5a.xlarge/spot, ip-192-168-2-74.us-east-2.compute.internal/c6a.2xlarge/spot, ip-192-168-1-74.us-east-2.compute.internal/c5a.xlarge/spot, ip-192-168-1-39.us-east-2.compute.internal/c5a.xlarge/spot, ip-192-168-1-173.us-east-2.compute.internal/c5a.xlarge/spot, ip-192-168-1-69.us-east-2.compute.internal/c5a.xlarge/spot	{"commit": "d01ea11-dirty"}
2023-04-20T04:42:37.785Z	INFO	controller.termination	cordoned node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-180.us-east-2.compute.internal"}
2023-04-20T04:42:37.795Z	INFO	controller.termination	cordoned node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-48.us-east-2.compute.internal"}
2023-04-20T04:42:37.804Z	INFO	controller.termination	cordoned node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-240.us-east-2.compute.internal"}
2023-04-20T04:42:37.834Z	INFO	controller.termination	cordoned node	{"commit": "d01ea11-dirty", "node": "ip-192-168-2-74.us-east-2.compute.internal"}
2023-04-20T04:42:37.874Z	INFO	controller.termination	cordoned node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-74.us-east-2.compute.internal"}
2023-04-20T04:42:37.914Z	INFO	controller.termination	cordoned node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-39.us-east-2.compute.internal"}
2023-04-20T04:42:37.922Z	INFO	controller.termination	cordoned node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-173.us-east-2.compute.internal"}
2023-04-20T04:42:37.968Z	INFO	controller.termination	cordoned node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-69.us-east-2.compute.internal"}
2023-04-20T04:42:38.599Z	INFO	controller.termination	deleted node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-69.us-east-2.compute.internal"}
2023-04-20T04:42:38.602Z	INFO	controller.termination	deleted node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-173.us-east-2.compute.internal"}
2023-04-20T04:42:38.606Z	INFO	controller.termination	deleted node	{"commit": "d01ea11-dirty", "node": "ip-192-168-2-74.us-east-2.compute.internal"}
2023-04-20T04:42:38.608Z	INFO	controller.termination	deleted node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-180.us-east-2.compute.internal"}
2023-04-20T04:42:38.611Z	INFO	controller.termination	deleted node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-48.us-east-2.compute.internal"}
2023-04-20T04:42:44.040Z	INFO	controller.termination	deleted node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-39.us-east-2.compute.internal"}
2023-04-20T04:42:44.371Z	INFO	controller.termination	deleted node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-240.us-east-2.compute.internal"}
2023-04-20T04:42:50.385Z	INFO	controller.termination	deleted node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-74.us-east-2.compute.internal"}
2023-04-20T04:43:07.684Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 3 machines ip-192-168-1-132.us-east-2.compute.internal/c6a.2xlarge/spot, ip-192-168-1-19.us-east-2.compute.internal/c5a.xlarge/spot, ip-192-168-1-30.us-east-2.compute.internal/c5a.xlarge/spot	{"commit": "d01ea11-dirty"}
2023-04-20T04:43:07.696Z	INFO	controller.termination	cordoned node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-132.us-east-2.compute.internal"}
2023-04-20T04:43:07.707Z	INFO	controller.termination	cordoned node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-19.us-east-2.compute.internal"}
2023-04-20T04:43:07.718Z	INFO	controller.termination	cordoned node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-30.us-east-2.compute.internal"}
2023-04-20T04:43:08.099Z	INFO	controller.termination	deleted node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-19.us-east-2.compute.internal"}
2023-04-20T04:43:08.101Z	INFO	controller.termination	deleted node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-132.us-east-2.compute.internal"}
2023-04-20T04:43:20.260Z	INFO	controller.termination	deleted node	{"commit": "d01ea11-dirty", "node": "ip-192-168-1-30.us-east-2.compute.internal"}
2023-04-20T04:43:39.233Z	INFO	controller.deprovisioning	deprovisioning via consolidation delete, terminating 1 machines ip-192-168-1-239.us-east-2.compute.internal/c5a.xlarge/spot	{"commit": "d01ea11-dirty"}
```

### Resource Specs and Logs

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.sh/v1alpha5","kind":"Provisioner","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"prod"},"name":"scan-pipeline-node-provisioner"},"spec":{"consolidation":{"enabled":true},"kubeletConfiguration":{"maxPods":110},"labels":{"scan-pipeline-node":"true"},"limits":{"resources":{"cpu":"2400","memory":"4800Gi"}},"providerRef":{"name":"deafult-nodes-template"},"requirements":[{"key":"karpenter.sh/capacity-type","operator":"In","values":["spot"]},{"key":"node.kubernetes.io/instance-type","operator":"In","values":["c6a.2xlarge","c5a.2xlarge","c5.2xlarge","c6a.xlarge","c5a.xlarge","c5.xlarge"]},{"key":"topology.kubernetes.io/zone","operator":"In","values":["us-east-2a","us-east-2b"]},{"key":"kubernetes.io/arch","operator":"In","values":["arm64","amd64"]},{"key":"kubernetes.io/os","operator":"In","values":["linux"]}],"taints":[{"effect":"NoSchedule","key":"scan-pipeline-node"}]}}
  creationTimestamp: "2023-01-08T08:57:34Z"
  generation: 17
  labels:
    app.kubernetes.io/instance: prod
  name: scan-pipeline-node-provisioner
  resourceVersion: "188490435"
  uid: fce0308f-5ef9-4e6a-8885-a547e7b3ce83
spec:
  consolidation:
    enabled: true
  kubeletConfiguration:
    maxPods: 110
  labels:
    scan-pipeline-node: "true"
  limits:
    resources:
      cpu: "2400"
      memory: 4800Gi
  providerRef:
    name: deafult-nodes-template
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - c6a.2xlarge
    - c5a.2xlarge
    - c5.2xlarge
    - c6a.xlarge
    - c5a.xlarge
    - c5.xlarge
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-east-2a
    - us-east-2b
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
    - amd64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  taints:
  - effect: NoSchedule
    key: scan-pipeline-node
status:
  resources:
    attachable-volumes-aws-ebs: "64"
    cpu: "12"
    ephemeral-storage: 123808920Ki
    memory: 24015712Ki
    pods: "220"
```

```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.k8s.aws/v1alpha1","kind":"AWSNodeTemplate","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"prod"},"name":"deafult-nodes-template"},"spec":{"amiFamily":"Bottlerocket","blockDeviceMappings":[{"deviceName":"/dev/xvdb","ebs":{"deleteOnTermination":true,"encrypted":true,"volumeSize":"60Gi","volumeType":"gp3"}}],"instanceProfile":"eks-58c2b634-62f4-55dc-8638-f888aff9c840","securityGroupSelector":{"karpenter.sh/discovery":"prod"},"subnetSelector":{"karpenter.sh/discovery":"prod"},"userData":"[settings]\n[settings.kubernetes]\nallowed-unsafe-sysctls = [\"net.core.somaxconn\"]\nregistry-qps = 20\n"}}
  creationTimestamp: "2023-04-03T04:29:38Z"
  generation: 5
  labels:
    app.kubernetes.io/instance: prod
  name: deafult-nodes-template
  resourceVersion: "188516647"
  uid: f67f682c-0663-4fa2-b04f-4785fe2df2a3
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvdb
    ebs:
      deleteOnTermination: true
      encrypted: true
      volumeSize: 60Gi
      volumeType: gp3
  instanceProfile: eks-58c2b634-62f4-55dc-8638-f888aff9c840
  securityGroupSelector:
    karpenter.sh/discovery: prod
  subnetSelector:
    karpenter.sh/discovery: prod
  userData: |
    [settings]
    [settings.kubernetes]
    allowed-unsafe-sysctls = ["net.core.somaxconn"]
    registry-qps = 20
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by shay-ul** [comment]
Until we find a solution, we created a cronjob to rollout restart the Karpenter deployment every 3 hours. We hope to see different numbers tomorrow morning.

**Comment by tzneal** [comment]
Can we get the full Karpenter logs that show this slowdown occurring?  You can create an AWS support ticket and attach the information there if you want the data to remain private.

**Comment by shay-ul** [comment]
Thanks @tzneal, I have created a ticket - 12553960191
The full log was attached there.
Thanks

**Comment by shay-ul** [comment]
I have also checked performance for the Karpenter Deployment. The node that the deployment resides on in dedicated to management workload which is not affected by the load increase during peak hours, so no CPU thottling or memory pressure occured. 
We can also observe CPU and Memory for the Karpenter deployment itself:
![Screenshot from 2023-04-20 22-02-07](https://user-images.githubusercontent.com/64831892/233462793-e492dbf9-f9b7-4093-971b-f5a804f78081.png)
![Screenshot from 2023-04-20 22-02-20](https://user-images.githubusercontent.com/64831892/233462796-cee71887-fd97-4c98-9ee1-304040207bcd.png)


Right after the deployment restarts, we can see that  it works pretty hard and consumes up to 3CPU and 1.55GiB of memory. This peak lasts six minutes.

**Comment by tzneal** [comment]
During those six minutes, is consolidation occurring?  Also if you can attach other logs to the ticket from other Karpenter runs (i.e. the run just before and just after the attached logs), that would help as well.

**Comment by tzneal** [comment]
When this occurs, can you see if there are events registered on the node?

**Comment by shay-ul** [comment]
We suspended the cronjob so we can replicate this issue again and have more logs for you. 
Karpenter was last restarted yesterday evening, and this morning it looks like Karpenter is working fine so far (Just like it did right after we upgraded to 0.27.2). See how it is working this morning, compared to yesterday (where the steep drop in node count happened only when we restarted the deployment)

![Screenshot from 2023-04-21 08-34-50](https://user-images.githubusercontent.com/64831892/233548930-0403a413-580b-4a2f-822e-c6ab16783e3f.png)

we will update tomorrow morning and attach more logs. We expect consolidation delay will occure again tomorrow or on the day after that.

**Comment by tzneal** [comment]
Sounds good, before you manually restart check for events on the nodes as well.

**Comment by jonathan-innis** [comment]
@shay-ul We have a snapshot karpenter release helm chart that contains additional logs and eventing in the key places in deprovisioning. If you're willing to install the release in your environment, it would help us debug the issue quicker as well (`v0-c3d4e738b6ea4cd0f60092e698a77a535a31574e`)

```console
export KARPENTER_VERSION=v0-c3d4e738b6ea4cd0f60092e698a77a535a31574e
helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version ${KARPENTER_VERSION} --namespace karpenter --create-namespace \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} \
  --set settings.aws.clusterName=${CLUSTER_NAME} \
  --set settings.aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
  --set settings.aws.interruptionQueueName=${CLUSTER_NAME} \
  --set controller.resources.requests.cpu=1 \
  --set controller.resources.requests.memory=1Gi \
  --set controller.resources.limits.cpu=1 \
  --set controller.resources.limits.memory=1Gi \
  --wait
```

**Comment by shay-ul** [comment]
As promised, we have an update for this morning as well.
This morning we let Karpenter handle things on its own terms - meaning, we did not restart the deployment. We do see that eventually Karpenter consolidates nodes, but it does so very late. This how this morning's peak looks like:

![Screenshot from 2023-04-22 08-49-21](https://user-images.githubusercontent.com/64831892/233765459-6426a283-3493-42e4-85d3-fe1b69541e38.png)
<br /><br />
We expect consolidation to start at around 3:50am (UTC+3), just like what happened on the provious day
<br /><br />

![Screenshot from 2023-04-22 08-59-01](https://user-images.githubusercontent.com/64831892/233765694-e99d5e26-73fe-4c7c-8355-9ff7950f9b4f.png)

I have attached the full logs for the Karpenter controller on support ticket 12553960191.

When it comes to events on nodes, here is an example of node that we expect to be consolidated:

```
  Resource                    Requests     Limits
  --------                    --------     ------
  cpu                         365m (9%)    550m (14%)
  memory                      695Mi (11%)  3368Mi (53%)
  ephemeral-storage           0 (0%)       0 (0%)
  hugepages-1Gi               0 (0%)       0 (0%)
  hugepages-2Mi               0 (0%)       0 (0%)
  attachable-volumes-aws-ebs  0            0
Events:
  Type    Reason                 Age                   From       Message
  ----    ------                 ----                  ----       -------
  Normal  DeprovisioningBlocked  27m (x11 over 48m)    karpenter  Cannot deprovision node due to pod tenant-a/a-59dbed56-redis-0 has do not evict annotation
  Normal  Unconsolidatable       7m51s (x8 over 175m)  karpenter  not all pods would schedule
```
As we can see, the node previously had a pod with do not evict annotation, but the pod was quickly deleted from the node, but the node persisted.

Here is another example:

```
  Resource                    Requests     Limits
  --------                    --------     ------
  cpu                         275m (7%)    550m (14%)
  memory                      645Mi (10%)  3368Mi (53%)
  ephemeral-storage           0 (0%)       0 (0%)
  hugepages-1Gi               0 (0%)       0 (0%)
  hugepages-2Mi               0 (0%)       0 (0%)
  attachable-volumes-aws-ebs  0            0
Events:
  Type    Reason                 Age                    From       Message
  ----    ------                 ----                   ----       -------
  Normal  DeprovisioningBlocked  23m (x13 over 48m)     karpenter  Cannot deprovision node due to pod tenant-a/a-da580772-redis-0 has do not evict annotation
  Normal  Unconsolidatable       4m29s (x9 over 5h22m)  karpenter  not all pods would schedule
```

At some point during the peak hours, most of the nodes appear to be near empty but they emit the same events and do not consolidate until the very end of the peak hours.

**Comment by shay-ul** [comment]
@jonathan-innis I have installed the requested Karpenter version with requests, but without limits since I'm sure it will be OOMKilled and be restarted especially during peak hours. Logs will be attached when we see this issue again, hopefully tomorrow morning.
Thanks

**Comment by jonathan-innis** [comment]
> As we can see, the node previously had a pod with do not evict annotation. The pod was quickly deleted from the node, but the node persisted

When the pod with the `do-not-evict` annotation was removed, was the node completely empty? It might be useful to share the cluster utilization across nodes after the scale-down of the deployment. In general, is cluster utilization of these nodes around 20%/30% or are the nodes completely empty when consolidation is considering them?  Were the only pods that were scheduled to these nodes the workload pods of the deployment that was scaled up and subsequently scaled down or were there other workload pods on these nodes?

**Comment by shay-ul** [comment]
@jonathan-innis looks like we cannot reproduce this issue with `v0-c3d4e738b6ea4cd0f60092e698a77a535a31574e`  Looks like it is working as expected.

![Screenshot from 2023-04-25 08-07-01](https://user-images.githubusercontent.com/64831892/234179467-6807a568-75e7-40a1-a17c-bec85cf1f752.png)


As for your questions - our workload consists of different helm charts which are being installed automatically using our custom orchestration layer. We do not "scale" our workload, we just install or uninstall helm charts, sometimes hundreds simultaneously. 
This means that a node can be considered for consolidation at a single moment, but then we might install a new helm chart and the kube-scheduler can decide to place one or more pods on it, and therefore increase the requests on the node (it can be one pod with minimal requests, or many pods with many requests, which may redeem the node uneligble for consolidation)..
If there is some kind of "back-off" mechanism for consolidation, our issue might originate from this process, since at multipile times Karpenter will see that the node is under-utilized, but then it has "do-not-evict" annotation or new workload will be deployed on it.

As for the `do-not-evict` annotaion,  a small portion of the installed deployments have this annotation.
We do understand that nodes may be very underutilized (10-20% requests out of the node's capacity) and still be blocked from consolidating, but when we eventually uninstall the helm chart (and remove the pods with this label from the node) - the node should immediatly be consolidated. We're speaking about a cluster with over ~160 nodes and all of them are underutilized (we have seen nodes with 5% requests, only a single or very few pods on it). 
It is possible that the nodes started to consolidate only after all of the pods were removed from them.

**Comment by jonathan-innis** [comment]
> but then we might install a new helm chart and the kube-scheduler can decide to place one or more pods on it

Does this churn where you are scheduling pods to the cluster happen a lot during the large scale-down from the nightly jobs that you are showing above?

**Comment by shay-ul** [comment]
> Does this churn where you are scheduling pods to the cluster happen a lot during the large scale-down from the nightly jobs that you are showing above?

When installing our helm charts, we are running some sort of a concurrency limit, which means that for some time, there should be no node consolidation since the cluster is at our configured max capacity. When pod count starts to drop (which menas - more helm charts are being uninstalled than installed) we expect to see node count start to drop as well.

> Do you see "Blocked" nodes during the scale-down if do-not-evict pods are scheduling to those nodes
Yes, and those nodes should not be consolidated until the blocking pods are deleted.

We see some delay this morning as well. Again, pod number starts to drop at 3:50am (UTC+3), but node count starts to drop only at 4:31am:

![Screenshot from 2023-04-26 08-53-44](https://user-images.githubusercontent.com/64831892/234481938-ade8e0f5-d724-4ca2-bd2a-d5e02cca49d8.png)

I'm uploading the full controller logs to the support ticket.

**Comment by jonathan-innis** [comment]
Looking at the logs, I'm only seeing that Karpenter is considering around 12 as "candidates" at the start of the deprovisioning scale-down which means that there is some condition that the other nodes are not meeting (considering you have around 200 of them). There should be events on the nodes now that indicate why Deprovisioning is blocking on those nodes. Do you see an indication of the Blocked event on your nodes?

**Comment by shay-ul** [comment]
quick question:
We have some workload running now and I'm seeing many nodes with similar events:

`not all pods would schedule, <pod_name> => would schedule against a non-initialized node <node_name>`

Is it possible that a single node which failed to be initialized succesfully (and is permanently stuck in `NotReady` state) cause consilidation blockage?

**Comment by tzneal** [comment]
@shay-ul Yes, this could slow down consolidation.  Consolidation simulates scheduling and if the proposed solution ends up with a pod from a node we are considering deleting being required to schedule against a non-ready node, we won't consolidate.  Can you ensure that these unready nodes are removed and see if that resolves the problem?  


We are tracking an issue at https://github.com/aws/karpenter/issues/2021 to automatically detect and repair these not ready nodes.

**Comment by shay-ul** [comment]
@tzneal Looks like consolidation is being slowed down when a single node is NotReady. Can such nodes be "ignored" while trying to simulate scheduling?
I can understand the idea behind not ignoring such nodes, since those can become Ready at any given moment, but maybe implement some sort of "Ready timeout" mechanism, to avoid consolidation delay?
Thanks!

**Comment by ellistarn** [comment]
Our fix for not ready nodes is here: https://github.com/aws/karpenter/issues/2021

@jonathan-innis @billrayburn, let's discuss priority on this next week.

**Comment by shay-ul** [comment]
Thanks for helping out. I'll watch out for #2021 .
