### ISSUE TITLE
Add partition env variable to Getting Started Guide

### ISSUE THREAD

**Issue by chrisnegus** [aws/karpenter#3791]
### Is an existing page relevant?

https://karpenter.sh/preview/getting-started/getting-started-with-karpenter/

### What karpenter features are relevant?

Using a partition other than `aws` in the getting started guide.

### How should the docs be improved?

The example in Step 3 of the getting started guide identifies `aws` as the partition type in the arn examples. Instead, in Step 2 an environment variable should be set (as is done in the [Migrating from Cluster Autoscaler](https://karpenter.sh/preview/getting-started/migrating-from-cas/) docs):

`AWS_PARTITION="aws" # if you are not using standard partitions, you may need to configure to aws-cn / aws-us-gov`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by prabhjotsingh18** [comment]
Hey Team , I'm new to the aws and k8s. from what I went through and understood is set an enviroment variable `AWS_PARTITION="aws"` and replace the hardcoded `aws` with the variable in the examples ( like in 
`-arn:aws:iam::${AWS_ACCOUNT_ID}:policy/KarpenterControllerPolicy-${CLUSTER_NAME}` ) 
let me know if that is it and i can send in a PR for the same.

**Comment by jonathan-innis** [comment]
Yep, that sounds right. Would you like me to assign you to the issue @prabhjotsingh18 ?

**Comment by prabhjotsingh18** [comment]
yes, plz. I'll drop a PR soon
