### ISSUE TITLE
De-Risk Provisioner Deletes

### ISSUE THREAD

**Issue by sidewinder12s** [aws/karpenter#3802]
### Tell us about your request

Is there any changes that could be made to de-risk deleting a Karpenter Provisioner?

Through operator error I've now twice un-intentionally deleted a Provisioner and Karpenter was able to take action and delete most nodes in our cluster within 30 seconds. 

Could there be a configurable/larger batch window on contextually large deletes like this?

Introduce a post delete cooldown?

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

The analogy I've had in my head is that it is much harder to delete EC2 Instances or ASGs than it is for Karpenter to delete a provisioner & de-provision all nodes all in 1 go.

EC2 you would need to select all nodes you want to delete and delete them. 

ASGs deletes on the CLI will not process if they contain instances without a force flag. Console will require a second confirmation. 

This is all assuming the user persona taking these actions are already privileged. 

Kubernetes RBAC also makes it difficult to disallow unsafe actions for privileged users since it does not and will not introduce a `Deny` action.

### Are you currently working around this issue?

We're attempting to add more flags to the Provisioner through our deployment mechanism, but we've already hit once where the change did not interact with that protection. (ArgoCD annotation to disallow it from Pruning the resource, however because it was a Helm Hook performing the delete it did not take effect). 

We could also introduce a Gatekeeper/Similar policy to disallow these deletes but I was hoping there might be things Karpenter can do to de-risk a default install of Karpenter. 

### Additional Context

Slack Discussion: https://kubernetes.slack.com/archives/C02SFFZSA2K/p1682364988166489

Ran into some edge cases with Hooks that I did not fully understand after implementing this on our provisioners: https://github.com/aws/karpenter/pull/3605

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> Kubernetes RBAC also makes it difficult to disallow unsafe actions for privileged users since it does not and will not introduce a Deny action

Is it possible to just disallow Delete from the Provisioner RBAC, except for highly escalated users?

**Comment by sidewinder12s** [comment]
What is the Provisioner RBAC if not Kubernetes RBAC?

**Comment by jonathan-innis** [comment]
> What is the Provisioner RBAC if not Kubernetes RBAC

I guess I'm trying to understand if you can remove the "delete" permission from the allow-listed clusterRole that is assigned to whoever is accessing the cluster. I get your point on the lack of Deny, I was mainly just trying to understand if removing Allow is an option.

**Comment by sidewinder12s** [comment]
I think if customers are following the normal best practices with Kubernetes, yes it'd be easier to not use the cluster-admin role or avoid granting delete to the privileged role. We're just assigning the builtin cluster-admin role which I am not sure can be modified...

At least in my case it was the cluster admin persona/cluster deployment tooling that had admin privileges and I still found it fairly dangerous to interact with Provisioner deletes due to lack of confirmation & how quickly Karpenter takes action with no cooldown.

Might it be possible to add a configuration flag to Karpenter that it will not delete nodes on a provisioner delete? It'll mark it for deletion and then require manual node cleanup?

**Comment by ellistarn** [comment]
You could look into a policy agent to prevent accidental deletes.

**Comment by ellistarn** [comment]
Closing, as this responsibility lies outside of this project.
