### ISSUE TITLE
Enhance cloudprovider metrics

### ISSUE THREAD

**Issue by tcyran** [aws/karpenter#3813]
### Tell us about your request

We would like to request adding more metrics to cloudprovider, which would provider better way of monitoring and understanding what is currently going. For eg. `InsufficientInstanceCapacity` metric would allow us to understand that we should give wider range for provisioner and etc. 

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

It would improve way of how we can monitor and react for issues with karpenter/config/couldprovider shortages

### Are you currently working around this issue?

We can create alerts based on logs, but it's not best long time solution

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Are there more details beyond what's included here: https://github.com/aws/karpenter-core/issues/244 that you would want to add? We are thinking that adding an `errors_total` metric to wrap the metrics on the cloudprovider, combined with error types (like InsufficientCapacity, NotFound) might helper here.

**Comment by tcyran** [comment]
@jonathan-innis it would be enough :).
