### ISSUE TITLE
Consolidate only to a set cluster efficiency

### ISSUE THREAD

**Issue by naikn** [aws/karpenter#3820]
### Tell us about your request

**Right sizing the cluster to a set cluster efficiency**

Karpenter when consolidating the ndoes and should respect a set cluster efficiency and leave room for pods rapiding scaling. This can improve the pod schedule time greatly and will also put less stress on the api-server when running large clusters.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Currently karpenter does a good job of consolidation by squeezing the cluster to a correct size, there by giving a good cluster efficiency. But this leave no room to growth of pods. When an app capable of scaling by 100s of pods is placed in cluster with karpenter, we see scaling latencies. 

After karpenter has consolidated the nodes, if 100s of pods needs to placed, new nodes need to be created. This can lead to delays application scaling, which in turn can force application to scale even more. The delay can increase based on the topology constraint and pod anti-affinities as more nodes need to be created. There by causing application to scale more causing a rolling issue. This especially affects when apps get spike in traffic causing issues to performance of the applications running on karpenter nodes. 

### Are you currently working around this issue?

We need to move such applications to ASGs with cluster autoscaler

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tcyran** [comment]
@naikn you can achieve this with [Horizontal Cluster Proportional Autoscaler](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler)

**Comment by FernandoMiguel** [comment]
the workaround is to have dummy deployments with low priority so that there is enough capacity when needed.

but all that goes against karpenter ethos of binpacking

**Comment by jonathan-innis** [comment]
> the workaround is to have dummy deployments with low priority so that there is enough capacity when needed.

+1 to this. There's some discussion in the overprovisioning buffer issue here (#3240) around how Karpenter handles a buffer of capacity to give yourself a warm-pool for the rapid scale-up of pods. Closing this issue as a duplicate, but please feel free to add info around your use-case over in that issue and keep track of it for designs on how we handle this in the future.
