### ISSUE TITLE
Error loading seccomp filter: errno 524: unknown

### ISSUE THREAD

**Issue by wdonne** [aws/karpenter#3822]
### Version

Karpenter Version: v0.27.3
Kubernetes Version: Major:"1", Minor:"25+", GitVersion:"v1.25.6-eks-48e63af", GitCommit:"9f22d4ae876173884749c0701f01340879ab3f95", GitTreeState:"clean", BuildDate:"2023-01-24T19:19:02Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"

### Expected Behavior

The pod would start on the already provisioned node.

### Actual Behavior

Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to init seccomp: error loading seccomp filter into kernel: error loading seccomp filter: errno 524: unknown

Pod remains in Pending status.

### Steps to Reproduce the Problem

This is random. Sometimes draining the node and getting a new one makes the problem go away, but more often it is just another pod that gets the error.

I have read elsewhere that this might have something to do with the ARM64 version of the kernel. Does Karpenter have an impact on the kernel version on the nodes?

### Resource Specs and Logs

[karpenter-5c4cdc68c4-45x5p_after_drain.log](https://github.com/aws/karpenter/files/11351836/karpenter-5c4cdc68c4-45x5p_after_drain.log)
[karpenter-8458c8d65c-9jfhq.log](https://github.com/aws/karpenter/files/11351838/karpenter-8458c8d65c-9jfhq.log)
[spec.zip](https://github.com/aws/karpenter/files/11351848/spec.zip)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by yassineaouadi** [comment]
can be related to this kernel issue on new eks ami  :
https://github.com/awslabs/amazon-eks-ami/issues/1219#issuecomment-1526925860

**Comment by wdonne** [comment]
That is very likely. The issue mentions the updated AMI images would be available in the beginning of March. Is that the case?

**Comment by yassineaouadi** [comment]
looks like all latest ami have this bug  mentionned in the release note: 
https://github.com/awslabs/amazon-eks-ami/releases

**Comment by tzneal** [comment]
Yes, there is a memory leak from a kernel bug in the EKS AMI. In particular:

**Comment by jonathan-innis** [comment]
I'm going to close this one since it's outside the scope of Karpenter.

**Comment by tzneal** [comment]
The kernel has been released now, https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230501

If you are using AMI drift detection, your nodes are likely already running it.
