### ISSUE TITLE
Getting 404 error

### ISSUE THREAD

**Issue by GowthamChinta** [aws/karpenter#3829]
I am trying to download Karpenter Cloudformation template using this command

curl -fsSL https://karpenter.sh/"${KARPENTER_VERSION}"/getting-started/getting-started-with-karpenter/cloudformation.yaml  > $TEMPOUT 

I am getting 404 error. I tried with different Karpenter_version 0.23.0, 0.22.0 and also 0.27.3

KARPENTER_VERSION=v0.20.0
 curl -fsSL https://karpenter.sh/"${KARPENTER_VERSION}"/getting-started/getting-started-with-karpenter/cloudformation.yaml  > $TEMPOUT 
curl: (22) The requested URL returned error: 404

**Comment by jonathan-innis** [comment]
We cycle the docs versions as we release new versions. Can you try hitting the URL with

```console
KARPENTER_VERSION=v0.27.3
curl -fsSL https://karpenter.sh/"${KARPENTER_VERSION}"/getting-started/getting-started-with-karpenter/cloudformation.yaml > $TEMPOUT
```

What's the specific reason you are trying to hit the CloudFormation endpoint for an older version of Karpenter?

**Comment by GowthamChinta** [comment]
Thankyou for the update.

We were using the 0.23.0 version as part of our cluster creation
automation.

New URL worked for us.

Regards,
Gowtham

**Comment by jonathan-innis** [comment]
Sounds good, going to close this issue if there is nothing else.

**Comment by HarshithaEshappa** [comment]
Hello,
 curl -fsSL https://karpenter.sh/"${KARPENTER_VERSION}"/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml> $TEMPOUT \
> && aws cloudformation deploy \
>   --stack-name "Karpenter-${CLUSTER_NAME}" \
>   --template-file "${TEMPOUT}" \
>   --capabilities CAPABILITY_NAMED_IAM \
>   --parameter-overrides "ClusterName=${CLUSTER_NAME}"
curl: (22) The requested URL returned error: 404 Not Found

getting the same error and if i use the below command also cloudformation is returning this statement

Waiting for changeset to be created..
Waiting for stack create/update to complete

Failed to create/update the stack.

curl -fsSL https://raw.githubusercontent.com/aws/karpenter/"${KARPENTER_VERSION}"/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml  > $TEMPOUT \
&& aws cloudformation deploy \
  --stack-name "Karpenter-${CLUSTER_NAME}" \
  --template-file "${TEMPOUT}" \
  --capabilities CAPABILITY_NAMED_IAM \
  --parameter-overrides "ClusterName=${CLUSTER_NAME}"
  
We are trying to configure the karpenter for our avaialble cluster.

Please help us to resolve this error
Thanks
