### ISSUE TITLE
add provisioner/awsnodetemplate to helm chart

### ISSUE THREAD

**Issue by sgblv** [aws/karpenter#3844]
### Tell us about your request

It is possible to deploy Karpenter with an awesome helm chart, but provisioner and awsnodetemplate we should install separately. It is a bit complicated to roll out the karpenter in multiple clusters. I suggest adding templates for the provisioner and awsnodetemplate to the helm chart. Orders can be managed with chart hooks (https://helm.sh/docs/topics/charts_hooks/).

Does this suggestion make sense or such separation was done intentionally? 

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Right now I have to deploy deploy k8s resources provisioner and awsnodetemplate separately

### Are you currently working around this issue?

Right now I have to deploy deploy k8s resources provisioner and awsnodetemplate separately

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
We've intentionally removed this in https://github.com/aws/karpenter/pull/3803

From the PR description: 
> Since Helm offers no in-chart dependency mechanisms (beyond hooks, which do not work in this case), the Karpenter maintainer team recommends that, if you want to install Karpenter manifests as a helm chart (alongside Karpenter), it should be done using a separate chart that can take the aws/karpenter chart as a dependency so there is a strict ordering for install.

Going to close this as we do not plan to implement this.
