### ISSUE TITLE
Mega-Issue: Improve Documentation Versioning Story

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter#3848]
### Tell us about your request

During migration between new versions of Karpenter, we introduce a new, latest minor version, and remove the oldest minor version that isn't preview. We do this primarily because we have found that having more versions than needed slows down our Netlify/Hugo website _significantly_. 

The trade-off of this is that users that are relying on docs or scripts that exist in older versions of Karpenter cannot rely on these versions as they are ephemeral and will be removed after some number of versions. There are a few alternatives that we should explore here:

1. Fixing the slowness problem with versioning on Netfliy/Hugo, ensuring that we are doing lazy loading for versioning and are not trying to load all the files at once, slowing performance
2. Having a versioning retention policy for website versions with a promise of the amount of time that that version will exist in the website

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

N/A

### Are you currently working around this issue?

Referrring users to the `preview` version of the website if they need a persistent version. This works as a half-solution, but the `preview` docs are prone to breaking changes.

### Additional Context

- https://github.com/aws/karpenter/issues/3659
- https://github.com/aws/karpenter/issues/3823
- https://github.com/aws/karpenter/issues/3924

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by nalshamaajc** [comment]
I'm writing a document and I'm trying to reference Karpenter's docs, but unfortunately it is all versioned with versions disappearing every once and a while. Which is causing broken URLs. Can you please add a `/latest/...`  path to point to what ever is the latest version, this should be feasible as you already have a `/preview` path.

**Comment by spereverziev** [comment]
Its a pain to understand what version is needed for specific feature. Documentation should reflect when feature requires version X+

**Comment by siolta** [comment]
> I'm writing a document and I'm trying to reference Karpenter's docs, but unfortunately it is all versioned with versions disappearing every once and a while. Which is causing broken URLs. Can you please add a `/latest/...` path to point to what ever is the latest version, this should be feasible as you already have a `/preview` path.

This would be particularly helpful for any internal docs that we create that point to paths such as the upgrade guide.  Without a `/latest/...` path the docs get stale.

**Comment by jonathan-innis** [comment]
@siolta @nalshamaajc Would either of y'all be interested in adding the latest path into the config? I believe there should be a way to alias it here: https://github.com/aws/karpenter/blob/main/website/config.yaml
