### ISSUE TITLE
Question: Threat modeling and internal architecture document

### ISSUE THREAD

**Issue by dhajoshi** [aws/karpenter#3856]
Is there threat modeling done for karpenter and internal architecture document for each api endpoints it connects ?

**Comment by billrayburn** [comment]
Working on this, will update next week.

**Comment by sftim** [comment]
Working on this? You might like to catch up on Ala Dewberry's contributor summit session from the last KubeCon: https://www.youtube.com/watch?v=2b3EJQWTTPU (_Assess Yourself! But first, Diagram Yourself!_)
