### ISSUE TITLE
Post-Install Webhook fails when installing Karpenter with 1 replica.

### ISSUE THREAD

**Issue by Phylu** [aws/karpenter#3867]
### Version

__Karpenter Version:__ v0.27.3

__Kubernetes Version:__ v1.26 (EKS)

### Expected Behavior

When installing the Karpenter Helm chart with `replicas: 1` it should work.

### Actual Behavior

Helm installs fails with the following error:

```
Error: failed post-install: warning: Hook post-install karpenter/templates/extra-manifests.yaml failed: Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.karpenter.svc:443/?timeout=10s": no endpoints available for service "karpenter"
```

### Steps to Reproduce the Problem

Install Karpenter via Helm using the following (redacted) values.yaml file:

```
replicas: 1
```

As soon as the replicas are configured to `2`, Karpenter can be installed as expected.

### Resource Specs and Logs

Karpenter Pod Logs:
[karpenter-655fcc864-tq56b.log](https://github.com/aws/karpenter/files/11425003/karpenter-655fcc864-tq56b.log)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Is your Karpenter pod failing to become healthy for some reason? `no endpoints available` implies that there is no pod to serve the webhook request. Generally, we recommend against configuring provisioners as part of the helm install for this exact reason.

**Comment by Phylu** [comment]
Yes, the pod was shown as ready, but somehow did not receive the webhook.

If I have two replicas, but only one is ready (because of only one bis in the initial node group) it works.

Also reducing the replicas to 1 after the provisioners have been created by the webhook works.

**Comment by ellistarn** [comment]
I'm noticing that our readiness probes check the controller readiness and not the webhook readiness.
```
	lo.Must0(o.Manager.AddHealthzCheck("healthz", healthz.Ping), "failed to setup liveness probe")
	lo.Must0(o.Manager.AddReadyzCheck("readyz", healthz.Ping), "failed to setup readiness probe")
```

It's likely that
1. Karpenter spins up a fresh pod
2. The pod is marked as ready
3. Karpenter terminates the old pod
4. The webhook request is made by helm and fails
5. The webhook becomes ready

Let me see if I can fix our probes to use webhook readiness instead.
