### ISSUE TITLE
add unit tests for `cloudprovider.go`

### ISSUE THREAD

**Issue by khareyash05** [aws/karpenter#3873]
I would like to add unit tests for `pkg/fake/cloudprovider.go`

**Comment by jonathan-innis** [comment]
I'm not sure that we need it for the fake. But we are probably missing coverage in areas directly insider our cloudprovider or other providers in the codebase. I can try to take a look some point soon and see if I can pinpoint areas where we are missing coverage in `aws/karpenter`
