### ISSUE TITLE
Metrics not working

### ISSUE THREAD

**Issue by rr-krupesh-savaliya** [aws/karpenter#3877]
### Version

Karpenter version: `v0.28.0-rc.1`
Kubernetes version: `1.24.0`

### Expected Behavior

It should scrape the metrics

### Actual Behavior

Metrics not scrapped in this version

### Steps to Reproduce the Problem

- We are using this metrics and exporting to DataDog
- I checked the metrics with port forwarding and it's there but somehow it's not working with DataDog
- I check with previous karpenter version `v0.27.1` and it's working fine

### Resource Specs and Logs

-

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Can you provide some more details? Monitoring configs, etc? As far as I know, nothing has changed with our metrics. I'm able to query metrics just fine.
```
curl localhost:8080/metrics
# HELP certwatcher_read_certificate_errors_total Total number of certificate read errors
# TYPE certwatcher_read_certificate_errors_total counter
certwatcher_read_certificate_errors_total 0
# HELP certwatcher_read_certificate_total Total number of certificate reads
# TYPE certwatcher_read_certificate_total counter
certwatcher_read_certificate_total 0
# HELP controller_runtime_active_workers Number of currently used workers per controller
# TYPE controller_runtime_active_workers gauge
controller_runtime_active_workers{controller="awsnodetemplate"} 0
controller_runtime_active_workers{controller="consistency"} 0
controller_runtime_active_workers{controller="counter"} 0
controller_runtime_active_workers{controller="daemonset"} 0
controller_runtime_active_workers{controller="deprovisioning"} 0
controller_runtime_active_workers{controller="interruption"} 1
...
```

Did something else change as part of this configuration?

**Comment by rr-krupesh-savaliya** [comment]
Nothing change on our side. We are adding datadog-agent as a sidecar container and add  required `podAnnotations`.

```ad.datadoghq.com/controller.checks: |
    {
      "openmetrics": {
        "init_config": {},
        "instances": [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "karpenter",
            "metrics": [{"^karpenter.*":"^karpenter.*"}]
          }
        ]
      }
    }
```

The same configurations working with karpenter version `v0.27.1`

**Comment by rr-paras-patel** [comment]
@ellistarn  Here i have listed it looks like 5K metrics :
https://gist.github.com/rr-paras-patel/d4504ac4a5d7f40f45550a49fbdbc45b

**Comment by ellistarn** [comment]
Are you saying the datadog is dropping the metrics since we're sending too many?

**Comment by rr-paras-patel** [comment]
it could be possibilities of that happening. because

Previous version :  no. of metrics via  : `curl localhost:8080/metrics | wc -l`  is `2144`

Current `v0.28.0-rc.1`: no. of metrics via  : `curl localhost:8080/metrics | wc -l`  is `5577`

but can we understand first what is leading in such huge increment?

**Comment by jonathan-innis** [comment]
> but can we understand first what is leading in such huge increment

You're correct. We bumped up the number of metrics to surface information on all the instance_types that we support. As you mentioned, if you want to ignore scraping a certain set of metrics, you can do so by ignoring the metric directly by name or with a prefix.

**Comment by rr-paras-patel** [comment]
Thanks for now i am going to exclude those metrics on scrapper side.  Thanks for your help.

**Comment by rr-krupesh-savaliya** [comment]
After excluding the metrics it's working as expected. Thanks
