### ISSUE TITLE
Support Trainium instance types

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#3885]
### Tell us about your request

Karpenter is not aware of `aws.amazon.com/neuron` resources on the `trn` instance family. 

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I'd like to use the Trainium instance types with Karpenter. However, karpenter is not aware that this family has `aws.amazon.com/neuron` resources: https://github.com/aws/karpenter/blob/main/pkg/providers/instancetype/types.go#L223.

### Are you currently working around this issue?

n/a

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by prabhjotsingh18** [comment]
Hey @ellistarn I would like to work on this. I'm new to AWS, if you can guide me a little on how to get started that would be great. 
Thanks

**Comment by ellistarn** [comment]
I'd start here:
https://karpenter.sh/v0.27.3/contributing/development-guide/

It should be about 3 lines of code to make this work. Plus integration testing. Use the inferentia code I linked above as a guide.

**Comment by sarthaknimbalkar** [comment]
Hey @prabhjotsingh18, I might have found the solution to this, if you working on this please let me know or else i would like to open a pr. Thanks.

**Comment by prabhjotsingh18** [comment]
hey @sarthaknimbalkar, please open a PR. so sorry for the late response.
