### ISSUE TITLE
FailedInflightCheck prevents node lifecycle?

### ISSUE THREAD

**Issue by blackliner** [aws/karpenter#3910]
### Version

__Karpenter Version:__ v0.24.0

Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.6-eks-48e63af", GitCommit:"9f22d4ae876173884749c0701f01340879ab3f95", GitTreeState:"clean", BuildDate:"2023-01-24T19:19:02Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Expected Behavior

karpenter does remove stale nodes after `ttlSecondsAfterEmpty` or `ttlSecondsUntilExpired` threshold reached.

### Actual Behavior

We have stuck nodes that seem to not get deleted after the expiry time. It is set to
```
      ttlSecondsAfterEmpty: 30
      ttlSecondsUntilExpired: 7200 # 2 hours
```
We had similar issues when the GPU was not recognized: https://github.com/aws/karpenter/issues/2737

What we can see with those nodes, they all have one thing in common, a event of type `FailedInflightCheck` of different nature:
`kubectl describe nodes | grep FailedInflightCheck`
```
  Warning  FailedInflightCheck  5m8s (x30 over 4h55m)  karpenter  Expected 200Gi of resource ephemeral-storage, but found 20959212Ki (10.0% of expected)
  Warning  FailedInflightCheck  5m15s (x30 over 4h55m)  karpenter  Expected 200Gi of resource ephemeral-storage, but found 20959212Ki (10.0% of expected)
  Warning  FailedInflightCheck  5m16s (x1504 over 10d)  karpenter  Expected resource "nvidia.com/gpu" didn't register on the node
  Warning  FailedInflightCheck  5m18s (x30 over 4h55m)  karpenter  Expected 200Gi of resource ephemeral-storage, but found 20959212Ki (10.0% of expected)
  Warning  FailedInflightCheck  5m19s (x30 over 4h55m)  karpenter  Expected 200Gi of resource ephemeral-storage, but found 20959212Ki (10.0% of expected)
  Warning  FailedInflightCheck  5m24s (x1504 over 10d)  karpenter  Expected resource "nvidia.com/gpu" didn't register on the node
```

Is it possible, that this check prevents karpenter from recognizing the node as "up" and thus skips any other cleanup steps?
| Name                                        | Status | Version             | Pods | Age |
| ------------------------------------------- | ------ | ------------------- | ---- | --- |
| ip-10-23-16-174.us-west-2.compute.internal  | Ready  | v1.25.7-eks-a59e1f0 | 19   | 27d |
| ip-10-23-100-154.us-west-2.compute.internal | Ready  | v1.25.7-eks-a59e1f0 | 23   | 27d |
| ip-10-23-189-119.us-west-2.compute.internal | Ready  | v1.25.6-eks-232056e | 10   | 27d |
| ip-10-23-234-114.us-west-2.compute.internal | Ready  | v1.25.7-eks-a59e1f0 | 11   | 27d |
| ip-10-23-249-252.us-west-2.compute.internal | Ready  | v1.25.7-eks-a59e1f0 | 11   | 27d |

### Steps to Reproduce the Problem

see above

### Resource Specs and Logs

see above

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by blackliner** [comment]
> It looks like the GPU didn't register again. Are you running the nvidia device plugin daemonset?
Yes, the nvidia device plugin daemonset is deployed, and works 95% of the time.

> Can you post your Provisioner and AWSNodeTemplate. I'm curious why the ephemeral storage isn't matching.
An engineer will post them in a few minutes, but we have recently made some changes for the bottlerocket AMI (changing the `deviceName: /dev/xvdb` size from `200G` to `500G`. The default disk size for `deviceName: /dev/xvdb`, is `20G`, see https://github.com/bottlerocket-os/bottlerocket/blob/develop/tools/testsys/src/aws_resources.rs#L276
That being said, it looks like the nodes with the small disk size, coming from a previous karpenter configuration, confuse the current carpenter setup and it does not proceed with the cleanup. **IMPORTANT** the nodes are still being used by the cluster workloads, so `karpenter.sh/initialized` apparently has no effect on the READY state of the cluster, on what is being scheduled or not.


> Do you see the karpenter.sh/initialized label set to true on the nodes?
No, it does not show up. So I assume `FailedInflightCheck` prevents karpenter to progress in the lifecycle (i.e. applying `karpenter.sh/initialized`)

**Comment by cebernardi** [comment]
linking this issue here, we're having a problem in the same area: https://github.com/aws/karpenter-core/issues/341

Our use case is slightly different tho: Karpenter is spinning `inf1` instances to satisfy cpu and memory requests (no workloads is requesting neuron gpus, so we suspect the choice is made on a price basis) and  we're not supplying any neuron kubernetes plugin, so the resource fails to register.

However, the node from a kubernetes perspective is ready, and the kubernetes scheduler is able to schedule pods on it; Karpenter node lifecycle, on the other end, is heavily disrupted as `karpenter.sh/initialized` is missing.

**Comment by tzneal** [comment]
@cebernardi For now, the workaround for the inf1 issue is to install the neuron device plugin or exclude inf1 types from your provisioner.

https://awsdocs-neuron.readthedocs-hosted.com/en/v1.16.2/neuron-deploy/tutorials/tutorial-k8s.html

**Comment by blackliner** [comment]
> We try to not take action on nodes that don't initialize so that the root cause can be fixed.

Ok, I take this as: `FailedInflightCheck` (and similar) will prevent `karpenter.sh/initialized`. This is intentional, and will allow kubernetes administrators to take action.

> Expiration may be a reasonable thing to take action on even if the node doesn't initialize, but it would likely run into the same issue on the next launch... It's probably best to monitor nodes that do not initialize and investigate.

What about letting the customers decide this: How about we add a new `ttlSecondsUntilExpiredUninitialized`, which would, if not set, behave as today, but would allow us to specify a timeout for these cases?

**Comment by jonathan-innis** [comment]
@blackliner We have updated the initialization logic starting in #3408. This change means that we would only wait for the extended resources to register that we have simulated based on pod requests. e.g. if you have a set of pods that don't request neuron and then launch an `inf` instance, we won't wait for the `neuron` extended resource to register anymore.

This new logic was released in the release candidate `v0.28.0-rc.1` which should get promoted to stable `v0.28.0` sometime this week. If you want to try the release candidate in the meantime, you could see if it solves the issue you are running into with `inf` instances.

**Comment by blackliner** [comment]
I am the one with `g4dn` instances and GPU issues, `inf` was @cebernardi , but I get the gist :D thanks

**Comment by jonathan-innis** [comment]
Ack, sorry, I skimmed through the thread super quick, but yeah, the same concept applies, any extended resource that isn't asked for won't block initialization anymore.

**Comment by blackliner** [comment]
Closing for now, will report back once we upgrade the version to 0.28 and it happens again
