### ISSUE TITLE
Deprovisioning

### ISSUE THREAD

**Issue by nparfait** [aws/karpenter#3920]
### Version

Karpenter Version: v0.27.5
Kubernetes Version: v1.23.17

### Expected Behavior

Node should be de-provisioned.
I am trying to scale my dev cluster down overnight. My cluster has 1 node in the 2 group and 2 karpenter provisioned nodes.
I scale my deployments using 
kubectl scale deployments --all -n xxx --replicas=0
which is about 28 deployments, however my cluster is remaining at 3 nodes. I'd expect at least 1 of the karpenter nodes to be de-provisioned. Ideally both would be and I would just have the 1 remaining node (but I am aware that karpenter doesn't know about the node group node(s)

### Actual Behavior

Karpenter nodes not being de-provisioned when deployments are scaled to 0 replicas

### Steps to Reproduce the Problem

1. Scale multiple deployments to 0 replicas
kubectl scale deployments --all -n xxx --replicas=0

### Resource Specs and Logs

Provisioner is default.
No errors in logs.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by nparfait** [comment]
On both karpenter nodes, after scaling deployments to 0 and waiting 5mins. There is nothing other then agents/daemons running on the nodes.

Events:
  Type    Reason            Age                 From       Message
  ----    ------            ----                ----       -------
  Normal  Unconsolidatable  65s (x87 over 23h)  karpenter  can't replace with a cheaper node

**Comment by tzneal** [comment]
Are the pods all daemonsets, or are there non-daemonset pods?

Can you provide the output of:
```
kubectl get pods -A -o yaml --field-selector spec.nodeName=the.node.name
```

**Comment by tzneal** [comment]
Karpenter will remove all of its nodes, if it can.  Are there still pods running on the node that Karpenter launched?

**Comment by nparfait** [comment]
There are still pods running on the karpenter node. I think my issue here is that the non karpenter node has capacity to run the workloads running on the remaining karpenter node. I assume I then need to use a node selector/pod affinity to force the remaining deployments/replicasets to run on my non karpenter node?

**Comment by nparfait** [comment]
Ok, thanks for your help, closing this.
