### ISSUE TITLE
Karpenter images have a zero build date

### ISSUE THREAD

**Issue by willthames** [aws/karpenter#3952]
### Version

v0.27.1 onwards

### Expected Behavior

`docker inspect public.ecr.aws/karpenter/controller:v0.27.5 -f '{{ .Created }}'` should return a date in the last few weeks****

### Actual Behavior

```
docker inspect public.ecr.aws/karpenter/controller:v0.27.5 -f '{{ .Created }}'
0001-01-01T00:00:00Z
```

### Steps to Reproduce the Problem

Run docker inspect

### Resource Specs and Logs

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by willthames** [comment]
Looks like this could be a problem with `ko` configuration

```
$ ko build -L -B github.com/aws/karpenter/cmd/controller              
2023/05/29 12:01:46 Using base gcr.io/distroless/static:nonroot@sha256:9ecc53c269509f63c69a266168e4a687c7eb8c0cfd753bd8bfcaa4f58a90876f for github.com/aws/karpenter/cmd/controller
2023/05/29 12:01:48 Building github.com/aws/karpenter/cmd/controller for linux/amd64
2023/05/29 12:01:52 Loading ko.local/controller:3ff06d81a3fec41f8b71fd5ec943bb567f4765831e73d411b67ab4bc9b69b27d
2023/05/29 12:02:01 Loaded ko.local/controller:3ff06d81a3fec41f8b71fd5ec943bb567f4765831e73d411b67ab4bc9b69b27d
2023/05/29 12:02:01 Adding tag latest
2023/05/29 12:02:01 Added tag latest
ko.local/controller:3ff06d81a3fec41f8b71fd5ec943bb567f4765831e73d411b67ab4bc9b69b27d
$ docker inspect ko.local/controller:3ff06d81a3fec41f8b71fd5ec943bb567f4765831e73d411b67ab4bc9b69b27d -f '{{.Created}}'
0001-01-01T00:00:00Z
```

**Comment by tzneal** [comment]
It's been this way for a very long time:

```
$ docker inspect public.ecr.aws/karpenter/controller:v0.2.0 -f '{{ .Created }}'
1970-01-01T00:00:00Z
```

Do you see something different?

**Comment by willthames** [comment]
@tzneal - ah, I hadn't checked older versions - I misunderstood a comment in slack.

So if we set `SOURCE_DATE_EPOCH` when building the final containers, we should be sorted

**Comment by willthames** [comment]
@engedaam is this actually sorted - can you point me to a fixed container image?

**Comment by willthames** [comment]
This is not fixed

```
docker inspect public.ecr.aws/karpenter/controller:v0.28.0 -f '{{ .Created }}'
0001-01-01T00:00:00Z
```

**Comment by jonathan-innis** [comment]
Yeah, looks like this was erroneously closed. We'll put out a fix. Apologize for the churn with open/close on this one.

**Comment by jonathan-innis** [comment]
FYI: this is where the `SOURCE_DATE_EPOCH` value needs to be set in KO to utilize this: https://ko.build/advanced/faq/. We need to utilize this in our `release.sh` script so that we don't end up with zero build dates that are blocking Karpenter install
