### ISSUE TITLE
nodes NotReady after karpenter sent spot rebalance recommendation event

### ISSUE THREAD

**Issue by abirsigron** [aws/karpenter#3954]
### Version

__Karpenter Version:__ v0.27.5

__Kubernetes Version:__ v1.24

### Expected Behavior

As far as I know, karpenter shouldn't support rebalance recommendation events yet and shouldn't handle them.
I can see in the following issue https://github.com/aws/karpenter/issues/2813 that this feature is work in progress and should be optional flag.

### Actual Behavior

Several Nodes are stuck on NotReady state, when describing the nodes I can see rebalance events:
```
Events:
  Type    Reason                               Age   From             Message
  ----    ------                               ----  ----             -------
  Normal  RegisteredNode                       17m   node-controller  Node ip-10-207-86-246.ec2.internal event: Registered Node ip-10-207-86-246.ec2.internal in Controller
  Normal  InstanceSpotRebalanceRecommendation  16m   karpenter        Node ip-10-207-86-246.ec2.internal event: A spot rebalance recommendation was triggered for the node
```

It looks like karpenter has sent InstanceSpotRebalanceRecommendation event to the node 1 minute before it was registered in the node-controller.

I think karpenter should ignore rebalance recommendation events until the feature is fully ready.

### Steps to Reproduce the Problem

This problem started on our side when we upgraded to 0.27.5
We are also using karpenter termination handler with associated sqs.

### Resource Specs and Logs

We can see this log messages in karpenter:
```
Node ip-X-X-X-X.ec2.internal event: A spot rebalance recommendation was triggered for the node
can't replace a spot node with a spot node
can't replace with a cheaper node
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
We create an event against the node, but otherwise don’t perform any action upon receiving the rebalance.  We shouldn’t be doing anything that would cause the node to go NotReady. Is the actual instance still running?

**Comment by abirsigron** [comment]
Actually, the instance was stuck on Pending state in aws console.
Maybe it is not a karpenter issue but an aws issue...
But what is the probability we will see the rebalance recommendation event on all the problematic nodes?
Are you certain this events shouldn't affect the node state by any chance? @tzneal

**Comment by tzneal** [comment]
Yes, this is the code: https://github.com/aws/karpenter/blob/34004124c1026659449218a0c4ba45867a8e7f77/pkg/controllers/interruption/controller.go#L288

RebalanceRecommendationKind performs no action here.

**Comment by tzneal** [comment]
Is it possible you still have NTH installed and running as well?
