### ISSUE TITLE
Custom-AL2 amiFamily or make ephemeral storage block-device explicit

### ISSUE THREAD

**Issue by fred-vogt-dod** [aws/karpenter#3962]
### Tell us about your request

CIS hardened custom AMIs using https://github.com/awslabs/amazon-eks-ami as the base image aren't usable with karpenter currently due to how ephemeral storage is determined, and user-data bootstrap script injection is enabled.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Getting a working `kubelet` or working ephemeral storage requests are mutually exclusive with a custom AMI that uses the official EKS AMI as a base.

Custom AMIs from https://github.com/awslabs/amazon-eks-ami require the NodeTemplate `amiFamily: AL2` in order to get a working kubelet - its impractical to include the correct bootstrap script arguments - some settings come from the Provisioner or are otherwise not practical to get (cluster-name, cluster-endpoint, cluster-ca data) into the NodeTemplate manifests.

However CIS hardened images (small root volume, larger `/var/lib/containerd` or `/var/lib/kubelet` volumes) require the `amiFamily: Custom` in order to schedule Pods with `ephemeral` storage requests.

Ephemeral storage discovery (undocumented?) looks at the last block device mapping for Custom, `/dev/xvda` for AL2:
* https://github.com/aws/karpenter/blob/v0.27.5/pkg/providers/instancetype/types.go#L140
  * https://github.com/aws/karpenter/blob/v0.27.5/pkg/providers/instancetype/types.go#L177
    * https://github.com/aws/karpenter/blob/v0.27.5/pkg/providers/amifamily/al2.go#L99

### Are you currently working around this issue?

No practical solution available yet.  Custom build required.

### Additional Context

To be able to specify `amiFamily: AL2` (to get the bootstrap user-data injection) and explicitly specify which block device holds the effective ephemeral storage would suffice.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by fred-vogt-dod** [comment]
For our environment a custom build with `pkg/providers/instancetype/types.go::ephemeralStorage`:
```go
// Setting ephemeral-storage to be either the default value or what is defined in blockDeviceMappings
func ephemeralStorage(amiFamily amifamily.AMIFamily, blockDeviceMappings []*v1alpha1.BlockDeviceMapping) *resource.Quantity {
	return blockDeviceMappings[len(blockDeviceMappings)-1].EBS.VolumeSize
}
```

**Comment by fred-vogt-dod** [comment]
Would be nice to perhaps have `amiE

**Comment by bwagner5** [comment]
The selection logic we use for the root volume is definitely a hack. It worked for all the things we knew about, AL2 and Bottlerocket (where Bottlerocket has a 2 volume setup as your describe). 

I'm curious why the last block device mapping doesn't work for your case though? IIUC the bigger volume will house the data dirs (/var/lib/containerd and /var/lib/kubelet)? So couldn't you move those dirs over to the additional volume attached and setup your block device mappings such that the bigger volume is the last mapping?

**Comment by fred-vogt-dod** [comment]
@bwagner5 - the last block device mapping use case does work for us (but requires setting the `Custom` amiFamily) - but we need the `AL2` amiFamily bootstrap script user-data injection too.

**Comment by luohao** [comment]
@bwagner5 we have a similar setup(_small root volume, larger /var/lib/kubelet volumes_) and run into the same issue with dedicated ebs volume(/dev/xvdb) for kubelet root dir(`/var/lib/kubelet`). Karpenter only counts the capacity of `/dev/xvda` for AL2 therefore:
1. it won't correctly evaluate different templates when provision new instances. For example, it refuses to provision new instances when requested ephemeral storage is larger than root drive(`/dev/xvda`) which is very small in our setup.
2. this also leads to a race between the default scheduler and karpenter, but I am not sure if this will cause any problem.
