### ISSUE TITLE
Request / limit for the controller

### ISSUE THREAD

**Issue by coliss86** [aws/karpenter#3992]
### Is an existing page relevant?

https://karpenter.sh/v0.27.5/getting-started/getting-started-with-karpenter/

### What karpenter features are relevant?

Hi, 

Thanks for your hard work 💪 

In the page https://karpenter.sh/v0.27.5/getting-started/getting-started-with-karpenter/, the installation of the Helm chart is done with `--set controller.resources.requests.cpu=1 ... --set controller.resources.limits.memory=1Gi`. It seems to be a large amount of resources for the controller. Are those values relevant on can it be lowered ? 

I have a cluster of 5 Nodes with 20 Pods, thus not a big one :)

Thanks for you answer.

### How should the docs be improved?

Is there some recommendations based on the max size of the cluster ?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Those are values the team set just as a standard value. For some larger cluster, we have seen user need to increases the resources request. Feel free to adjust the resources as you need, but there is a risk you might limit the karpenter pods of resources.

**Comment by coliss86** [comment]
Thx :-)
