### ISSUE TITLE
Seeing "invariant violated registering host port usage" in karpenter logs

### ISSUE THREAD

**Issue by mrparkers** [aws/karpenter#4005]
### Version

__Karpenter Version:__ v0.27.5

__Kubernetes Version:__ v1.26.4-eks-0a21954

### Expected Behavior

Performing an update to a daemonset that uses host ports should not result in Karpenter error logs.  This seems to have started happening after updating to `v0.27.5`.

### Actual Behavior

When performing an update to a Daemonset which has a host port configured, karpenter emits a bunch of error logs that look like this:

```
{"level":"ERROR","time":"2023-06-06T19:03:02.108Z","logger":"controller.pod_state","message":"invariant violated registering host port usage, IP=0.0.0.0 Port=8125 Proto=UDP conflicts with existing HostPort configuration IP=0.0.0.0 Port=8125 Proto=UDP, please file an issue","commit":"698f22f-dirty","pod":"datadog/datadog-brx5c"}
```

The log message said to file an issue, so here I am.

It's worth noting that I didn't see an error log entry for every single pod in the daemonset, only about 10 of them (in a 200 node cluster).

### Steps to Reproduce the Problem

Deploy a daemonset that configures a `hostPort` in a large cluster, then update it, and observe the Karpenter logs.

### Resource Specs and Logs

```
{"level":"ERROR","time":"2023-06-06T19:03:02.108Z","logger":"controller.pod_state","message":"invariant violated registering host port usage, IP=0.0.0.0 Port=8125 Proto=UDP conflicts with existing HostPort configuration IP=0.0.0.0 Port=8125 Proto=UDP, please file an issue","commit":"698f22f-dirty","pod":"datadog/datadog-brx5c"}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Thanks for the issue on this! I'll try to reproduce. It's likely that Karpenter registers the DS's existing at the same time for a small amount of time.

**Comment by billrayburn** [comment]
Closed with https://github.com/aws/karpenter-core/pull/434
