### ISSUE TITLE
Native way to refresh karpenter nodes at scale

### ISSUE THREAD

**Issue by timnee** [aws/karpenter#4015]
### Tell us about your request

A native on-demand way to trigger the refreshing of all Karpenter provisioned nodes

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

When using Karpenter at scale with 10s to 100s of Karpenter provisioned nodes, there needs to be a native way to triggering a node refresh, e.g., ami upgrade, EKS upgrade.  

I realize that ttlSecondsUntilExpired could be used for this purpose or could create a script to drain the nodes.  Both are less than ideal. 

### Are you currently working around this issue?

Leveraging ttlSecondsAfterEmpty and manually draining each node to have Karpenter reprovision it.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Feel free to reopen if I misunderstood the feature request.
