### ISSUE TITLE
Karpenter supoorts Calico CNI

### ISSUE THREAD

**Issue by sankshiv80** [aws/karpenter#4018]
### Tell us about your request

We are using EKS-1.24 and i tried to install Karpenter 0.26.1 version in our environment.. We are using calico CNI instead of VPC CNI.. Karpenter getting deployed in VPC CNI but not in Calico CNI.. Could u pls help me? / Karpenter support only VPC CNI

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

We are using EKS-1.24 and i tried to install Karpenter 0.26.1 version in our environment.. We are using calico CNI instead of VPC CNI.. Karpenter getting deployed in VPC CNI but not in Calico CNI.. Could u pls help me? / Karpenter support only VPC CNI

### Are you currently working around this issue?

We are using EKS-1.24 and i tried to install Karpenter 0.26.1 version in our environment.. We are using calico CNI instead of VPC CNI.. Karpenter getting deployed in VPC CNI but not in Calico CNI.. Could u pls help me? / Karpenter support only VPC CNI

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Karpenter can work with the Calico CNI. I would recommend that you join the #karpenter slack channel in the K8s upstream Slack workspace for this type of question. You can get an invite if you're not already on the slack workspace here: https://communityinviter.com/apps/kubernetes/community

There's more folks in that community that will have both Karpenter and Calico experience that will be better equipped to help :)
