### ISSUE TITLE
Allow Karpenter fallback to on-demand if there is a generally high interruption-rate

### ISSUE THREAD

**Issue by nadavbuc** [aws/karpenter#4026]
### Tell us about your request

Currently Karpenter should only fallback to on-demand according to specific instances types spot availability
It could become useful to just fallback to on-demand and bring back spot when there are enough instances which have availability restored.

Alternatively it might be Good to look at overall allowed spot instances types and how volatile they are in average

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

With our current solution, we have smart fallback to On-Demand
We want to migrate to Karpenter, but it's hard to tell how it will react on high spot interruption rate

### Are you currently working around this issue?

I plan to setup ASG for the same node groups which will allow me to spin up hardcoded amount of on-demand instances to cope with a volatile spot market

### Additional Context

We are running on several regions for several use-cases and noticed that us-east-1 spot market volatility is really high and volatile 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sftim** [comment]
One option you have is to make your own controller that manages limits of a spot-only Provisioner, based on your metric of how desirable (or not) spot launch happens to be.

Would that fit @nadavbuc? If so, an implementation option is to have that available as contrib code rather than as part of Karpenter.

**Comment by nadavbuc** [comment]
It actually sounds super cool
For now i've planned our infra to shift toward on-demand provisioner based on the capacity spread keys (the documented way of controlling spot:od ratio) so i can easily and quickly tweak/patch this

**Comment by njtran** [comment]
So, this sounds like a global on-demand fallback, as opposed to a per-instance type on-demand fallback. IIUC, I don't think we should include this as part of Karpenter, as it makes Karpenter's instance type selection less granular. I think the proper way to do this would be to model your provisioners as you've mentioned to properly represent the spot capacity you'd like to see. 

How do you track the volatility of a spot market? If this is something that we'd implement, I'd like to see what signals you use to track this to get an idea of where we can start thinking about this.

**Comment by nadavbuc** [comment]
I only track the amount of unschedulable nodes - i think currently there is no way to track this

**Comment by nadavbuc** [comment]
I think its not do-able
