### ISSUE TITLE
Provisioner documentation implies a complete impl of KubeletConfiguration

### ISSUE THREAD

**Issue by thekuffs** [aws/karpenter#4046]
### Is an existing page relevant?

https://karpenter.sh/preview/concepts/provisioners/#speckubeletconfiguration

### What karpenter features are relevant?

Provisioner

### How should the docs be improved?

The documentation for the karpenter Provisioner provides details for `Provisioner.spec.kubeletConfiguration`. It provides what appears to be an example of the kinds of data you can put in that field. The documentation also links the specification for `kubelet.config.k8s.io/v1beta1/KubeletConfiguration` - implying that the example is just a subset of the available options. However, that is not true at all. The example given is the complete list of implemented fields.  And kubelet will confirm with ` kubectl -n karpenter explain Provisioner.spec.kubeletConfiguration`.

The documentation needs an explicit note that the example configuration is exhaustive. And that the upstream kubernetes documentation should only be used to understand the _meaning_ of those fields.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Sorry for your confusion! From my understanding of the reading, the first sentence says 
"Karpenter provides the ability to specify a few additional Kubelet args", which indicates to me that it isn't the full set. 

I can see how this paragraph could be confusing. I can make a change so it's a little clearer.

**Comment by thekuffs** [comment]
Thank you, I had glossed over the 'few' in that sentence
