### ISSUE TITLE
Support for EKS/Kubernetes 1.26

### ISSUE THREAD

**Issue by arthurzenika** [aws/karpenter#4056]
### Tell us about your request

The FAQ says "Karpenter is tested with Kubernetes v1.21-v1.25." Here is a request so users can track when it is ok or safe to upgrade their cluster from 1.25 to 1.26. 

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Staying up to date with kubernetes is a good idea for a number of reasons. 

Right now here is the list of supported k8s/EKS versions on AWS : 

![Screenshot from 2023-06-15 09-39-40](https://github.com/aws/karpenter/assets/445200/8776073e-ea2a-40e0-93b4-7e91e78e9718)

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

### Are you currently working around this issue?

No, but we might have some time to test out karpenter with the new versions. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arthurzenika** [comment]
Related issues : 

* https://github.com/aws/karpenter/issues/3996

(searched for 1.26 in the issues but not sure which issues are really related to this)

**Comment by njtran** [comment]
We actually test for Kubernetes 1.26 and 1.27 in our CI tests in both karpenter and karpenter-core. https://github.com/aws/karpenter/blob/main/.github/workflows/ci-test.yaml#L12.

We also test EKS 1.25 in our e2e tests, but it should work up until 1.27 as far as I recall. 
https://github.com/aws/karpenter/blob/main/.github/actions/e2e/create-cluster/action.yaml#L19

Are you seeing differently?

**Comment by njtran** [comment]
We support up to 1.27 in our e2e tests now, I'll make the change to reflect this in the docs. For any future version questions, we'll track the automation here: https://github.com/aws/karpenter/issues/3924

**Comment by Hongbo-Miao** [comment]
I confirmed simply replacing 1.24 to 1.27 in [getting started tutorial](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/) works for me! 😃

```shell
eksctl create cluster -f - <<EOF
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_DEFAULT_REGION}
  version: "1.24"
  tags:
    karpenter.sh/discovery: ${CLUSTER_NAME}

# ...
```
