### ISSUE TITLE
[Question] Upgrade Path

### ISSUE THREAD

**Issue by adcoutinho** [aws/karpenter#4077]
Reading the documented [Upgrade Guide ](https://karpenter.sh/v0.28/upgrade-guide/) I missed some kind of chart or table with a simplified Upgrade Path.

For example.:

Can I move from v0.20 to v0.28 directly?
Which versions I need to upgrade first or install CRDs before take the next upgrade step?

In my experience from v0.20 to v0.22 everything goes smooth, but for v0.24 upgrade install new CRDs are needed.

Try to find something like that in closed or opened Issues without success.

**Comment by SamuelBagattin** [comment]
On all upgrades of karpenter I usually upgrade the CRDs with the [CRD helm chart](https://karpenter.sh/preview/upgrade-guide/#custom-resource-definition-crd-upgrades), then upgrade the main chart. I don't see with this method, why you would not be able to upgrade 0.20 to 0.28, just be aware of breaking changes mentioned in the [release notes](https://karpenter.sh/preview/upgrade-guide/#released-upgrade-notes)

**Comment by ellistarn** [comment]
You can safely upgrade across multiple versions, but make sure you read the upgrade guide for any breaking changes. There was a major change in v0.28.0.
