### ISSUE TITLE
Upgrade e2etests to latest EKS K8s Versions

### ISSUE THREAD

**Issue by njtran** [aws/karpenter#4080]
### Tell us about your request

Eksctl supports up to v1.27, our e2e tests should be testing the latest version

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

--

### Are you currently working around this issue?

---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Done with #4221
