### ISSUE TITLE
Missing Prometheus datasource variable for Grafana dashboards 

### ISSUE THREAD

**Issue by oliviermichaelis** [aws/karpenter#4094]
### Version

__Karpenter Version:__ v0.28.0

__Kubernetes Version:__ v1.27.0

### Expected Behavior

The Grafana dashboards from the [website/content/en/v0.28/getting-started/getting-started-with-karpenter](https://github.com/aws/karpenter/tree/main/website/content/en/v0.28/getting-started/getting-started-with-karpenter) directory should work out of the box with the default Prometheus datasource configured in the Grafana instance.

### Actual Behavior

For the [`karpenter-controllers.json`](https://github.com/aws/karpenter/blob/main/website/content/en/v0.28/getting-started/getting-started-with-karpenter/karpenter-controllers.json) and the [`karpenter-controllers-allocation.json`](https://github.com/aws/karpenter/blob/main/website/content/en/v0.28/getting-started/getting-started-with-karpenter/karpenter-controllers-allocation.json) dashboards, loading the dashboards on Grafana `9.5.3` fails with `Failed to upgrade legacy queries Datasource ${DS_PROMETHEUS} was not found`.

However, the other two dashboards work because of a dashboard variable named `datasource`  that queries for the default Prometheus datasource: https://github.com/aws/karpenter/blob/63f76f3f3871f22eb9768285ba5290370e29ccd6/website/content/en/v0.28/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json#L1410-L1427

The `datasource` is then used throughout the dashboard to reference the queried datasource:
https://github.com/aws/karpenter/blob/63f76f3f3871f22eb9768285ba5290370e29ccd6/website/content/en/v0.28/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json#L29-L32

The two "broken" dashboards in question use the `DS_PROMETHEUS` variable to resolve the datasource.

### Steps to Reproduce the Problem

Provision the dashboards on a recent Grafana version and load the dashboard.

### Resource Specs and Logs

As it doesn't really affect Karpenter, I don't have any logs or other resources

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Nice find! Would you be willing to cut a PR to fix @oliviermichaelis?

**Comment by ellistarn** [comment]
Yeah SGTM.

**Comment by stars693** [comment]
Same error appearing on using dashboard from https://grafana.com/grafana/dashboards/18862-karpenter/ . Is there any workaround to mitigate this ? Thanks in advance.

**Comment by oliviermichaelis** [comment]
@stars693 I don't think the dashboards you linked are "officially" by the karpenter project. Feel free to try out the dashboard JSON files from [my PR](https://github.com/aws/karpenter/pull/4119) and check whether they solve the problem for you :)
