### ISSUE TITLE
v0.27+ - Grafana templates not upgraded with the last metrics

### ISSUE THREAD

**Issue by anthosz** [aws/karpenter#4129]
### Description

**Observed Behavior**:
If we go to https://github.com/aws/karpenter/tree/v0.28.1/website/content/en/v0.27/getting-started/getting-started-with-karpenter or https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json
The dashboard continue to use old metrics (ex: karpenter_deprovisioning_actions_performed)

**Expected Behavior**:
Adapt these templates to use the good metrics

**Versions**:
- Chart Version: v0.28
- Kubernetes Version (`kubectl version`): 1.27

**Comment by anthosz** [comment]
Could you confirm that these equivalent metrics are good?

- karpenter_nodes_terminated -> controller_runtime_reconcile_total{controller="machine.termination",result="success"}
- karpenter_nodes_created -> controller_runtime_reconcile_total{controller="machine-state",result="success"}
- karpenter_deprovisioning_actions_performed -> controller_runtime_reconcile_total{controller="deprovisioning",result="success"}

**Comment by jonathan-innis** [comment]
@anthosz The metrics changes are documented [here in the upgrade guide](https://karpenter.sh/docs/upgrade-guide/#upgrading-to-v0280). 

For the Grafana dashboard updates, would you be interested in opening a PR to make the relevant updates to the dashboard given the new metrics?

**Comment by anthosz** [comment]
> @anthosz The metrics changes are documented [here in the upgrade guide](https://karpenter.sh/docs/upgrade-guide/#upgrading-to-v0280).
> 
> For the Grafana dashboard updates, would you be interested in opening a PR to make the relevant updates to the dashboard given the new metrics?

I'm OK to do a PR but the point is that I don't know which metric to use (cf my second comment). 

From the doc:
```
The following controller metrics changed and moved under the controller_runtime metrics namespace:

    karpenter_metricscraper_...
    karpenter_deprovisioning_...
    karpenter_provisioner_...
    karpenter_interruption_...
```
But I'm not sure of the related metric on controller runtime.

Could you confirm if my second comment? 

> Could you confirm that these equivalent metrics are good?
> 
>     * karpenter_nodes_terminated -> controller_runtime_reconcile_total{controller="machine.termination",result="success"}
> 
>     * karpenter_nodes_created -> controller_runtime_reconcile_total{controller="machine-state",result="success"}
> 
>     * karpenter_deprovisioning_actions_performed -> controller_runtime_reconcile_total{controller="deprovisioning",result="success"}

Thank you for your answer

**Comment by jonathan-innis** [comment]
The place I linked in the docs shows the following metrics changes (there isn't a good `controller_runtime...` equivalent for the metrics that you listed)

```
karpenter_nodes_terminated -> karpenter_machines_terminated
karpenter_nodes_created -> karpenter_machines_created
karpenter_deprovisioning_actions_performed (this one hasn't changed names AFAIK but may have some labels changed for it)
```

**Comment by anthosz** [comment]
> The place I linked in the docs shows the following metrics changes (there isn't a good `controller_runtime...` equivalent for the metrics that you listed)
> 
> ```
> karpenter_nodes_terminated -> karpenter_machines_terminated
> karpenter_nodes_created -> karpenter_machines_created
> karpenter_deprovisioning_actions_performed (this one hasn't changed names AFAIK but may have some labels changed for it)
> ```

In fact, after 24h, all these metrics are back with the 0.28 (karpenter_nodes_terminated/karpenter_nodes_created/karpenter_deprovisioning_actions_performed)... don't really understand well but seems ok

**Comment by jonathan-innis** [comment]
> don't really understand well but seems ok

Yes, we still have the `karpenter_nodes_terminated` and the `karpenter_nodes_created` metrics, they just no longer have the reason label on them that tells you why the node was created or deleted. Glad the problem resolved itself 👍
