### ISSUE TITLE
Support cherry-picked patch releases

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#4139]
### Description

**How can the docs be improved?**

Documentation generation doesn't currently work for cherry-picked patch releases, and has to be written manually.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by billrayburn** [comment]
Closing in favor of https://github.com/aws/karpenter/issues/1043.
