### ISSUE TITLE
Where is the helm chart?

### ISSUE THREAD

**Issue by nirroz93** [aws/karpenter#4147]
### Description

Hi, I noticed the helm chart in the repo is 0.28.0, when 0.28.1 released few days ago. I quickly opened a PR (https://github.com/aws/karpenter/pull/4146/files), before I update my deployment to 0.28.1.

However, I noticed the OCI repo already includes the Chart, so I guess I'm looking at the wrong place at the code.

Can you document where the actual Chart is in the Readme?

**Comment by jonathan-innis** [comment]
Can you clarify a bit what your ask is? I'm a bit confused with what you are saying is missing? Are you saying that during our release process something was missing and there was a race that made it look like the chart was not there? Or are you saying that the OCI repo is not well-documented? Or maybe something else?

**Comment by nirroz93** [comment]
Sorry that I wasn't clear.

Current chart in the repo is 0.28.0 https://github.com/aws/karpenter/blob/6529ae86628419964bef80cbdb0fe55cf37591d9/charts/karpenter/Chart.yaml#L5.

However `helm pull oci://public.ecr.aws/karpenter/karpenter --version v0.28.1` works as expected, bringing chart version 0.28.1.

It's not on the main branch, and on the tag of 0.28.1 the chart is 0.27.5 https://github.com/aws/karpenter/blob/v0.28.1/charts/karpenter/Chart.yaml .

**Comment by jonathan-innis** [comment]
Got it. Patch releases come on branches marked with `release-v0.x.x`; so, since there was a patch release for `v0.28.0`, we have a branch in the repo called `release-v0.28.x` which contains the relevant code for the latest patch release.

**Comment by jonathan-innis** [comment]
We also tag every time we release so the tag `v0.28.1` should point to the commit that has all the code that was released with that version

**Comment by nirroz93** [comment]
Well, the helm chart isn't there as well...

**Comment by sftim** [comment]
The Helm chart is in https://gallery.ecr.aws/karpenter/karpenter

**Comment by sftim** [comment]
Oh, and the source code is https://github.com/aws/karpenter/tree/main/charts

**Comment by sftim** [comment]
I notice that StableRelease (not quite an accurate name, BTW) says that it doesn't run for patch releases.

**Comment by jonathan-innis** [comment]
> says that it doesn't run for patch releases

I'm not following. Which thing is `StableRelease`? Are you referring to a GH action that we have or something else?

**Comment by sftim** [comment]
https://github.com/aws/karpenter/pull/4049 mentions `StableRelease`, and that it doesn't run for patch releases.

**Comment by jonathan-innis** [comment]
@nirroz93 Just so I know that we got to the bottom of your question, is there something that you think that we should document better or something that you found confusing as you were trying to track down the chart that we should improve?

**Comment by jonathan-innis** [comment]
> but never commited to the git?

Correct. We stopped publishing our helm charts directly into git, which was driven by our need to publish the charts through GH pages. We now release the charts to an OCI repo (https://gallery.ecr.aws/karpenter/karpenter) so they are not committed back into the repo.
