### ISSUE TITLE
question: can we pre-populate images when new node provision?

### ISSUE THREAD

**Issue by tuananh** [aws/karpenter#4153]
### Description

**What problem are you trying to solve?**
there are certain images I would like for every node to pre-cache. is there an mechanism in karpenter that allow me to do that?

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
you packer build your AMIs to include those OCI images, would be the place I would start
given bottlerocket uses a secondary EBS for data, you can snapshot that and use that as the attach new node EBS

**Comment by jonathan-innis** [comment]
> you can snapshot that and use that as the attach new node EBS
As @FernandoMiguel mentioned, using an EBS snapshot for the partition that supplies the images to your pods is the way to achieve this.
