### ISSUE TITLE
Webhook health checks break Karpenter usage with http_proxy

### ISSUE THREAD

**Issue by tscn** [aws/karpenter#4154]
### Description

**Observed Behavior**:

I was successfully running Karpenter 0.27 in completely private subnets where Internet break-out only works via http(s)_proxy. By setting the respective environment variables for `http_proxy`, `https_proxy` and `no_proxy`, this worked perfectly fine. After upgrading to 0.28 I face the issue that Karpenter goes into CrashLoop. After checking the liveness probe results, it seems that the newly introduced webhooks check (https://github.com/aws/karpenter-core/pull/334) never becomes healthy:

```
*   Trying 127.0.0.1:8081...
* Connected to localhost (127.0.0.1) port 8081 (#0)
> GET /healthz HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/8.1.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Tue, 27 Jun 2023 10:45:09 GMT
< Content-Length: 92
<
[+]cloud-provider ok
[+]healthz ok
[-]webhooks failed: reason withheld
healthz check failed
```

However, if I run the webhooks health check from curl (which requires a domain - where I am using localhost), they seem to work fine:

```
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /health HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.1.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 27 Jun 2023 10:44:47 GMT
< Content-Length: 0
<
```

The problem is that golang proxy implementation does not skip proxy when no hostname is provided (https://github.com/golang/go/issues/52988) and it also seems there is no way to bypass it with `no_proxy` setting.

**Expected Behavior**:

Karpenter should become healthy when a http(s)_proxy is configured.

**Reproduction Steps** (Please include YAML):

Use a forward proxy for Karpenter:

```
controller:
  env:
    - name: http_proxy
      value: http://myproxy
    - name: https_proxy
      value: http://myproxy
    - name: no_proxy
      value: ".local,localhost,172.20.0.0/16,10.100.0.0/16"
```

**Versions**:
- Chart Version: 0.28.0, 0.28.1
- Kubernetes Version (`kubectl version`): 1.25

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Hi @tscn. Haven't had a chance to look over this due to looking into other issues in the Karpenter repo. Ack-ing this and planning to take a look at this issue ASAP.

**Comment by tscn** [comment]
Thanks @jonathan-innis.

**Comment by jonathan-innis** [comment]
Can you try testing with Snapshot Karpenter version `v0-fe8bdee755bfdbfbb9d696470878896019d80381` produced by #4174 and see if this fixes the issue for you?

**Comment by tscn** [comment]
@jonathan-innis I have tested the snapshot and can confirm that it fixes the issue.
