### ISSUE TITLE
Tighten IAM permissions around deletion

### ISSUE THREAD

**Issue by johngmyers** [aws/karpenter#4159]
### Description

**What problem are you trying to solve?**

Reduce the scope of Karpenter's IAM permissions to the minimum needed.

The example IAM permissions [for KarpenterControllerPolicy](https://github.com/aws/karpenter/blob/main/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml#L34) grant Karpenter to terminate any instance and delete any launch template in the account.

These permissions should have conditions limiting them to instances and launch templates that are tagged by Karpenter as belonging to the cluster.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> These permissions should have conditions limiting them to instances and launch templates that are tagged by Karpenter as belonging to the cluster.

This template was [recently updated](https://github.com/aws/karpenter/pull/3948) to scope these permissions more like you suggest.

**Comment by jonathan-innis** [comment]
Closing this since the new CF template now only allows Karpenter to delete instances that contain [these set of tag keys](https://github.com/aws/karpenter/blob/main/website/content/en/docs/getting-started/getting-started-with-karpenter/cloudformation.yaml#L179).
