### ISSUE TITLE
Support cluster scoped limits

### ISSUE THREAD

**Issue by stevehipwell** [aws/karpenter#4190]
### Description

**What problem are you trying to solve?**
I'd like Karpenter to be able to manage limits for the whole cluster, this would also including nodes that weren't created by Karpenter. 

- Single limit for Karpenter
- Evaluate all provisioners
- Evaluate non-Karpenter nodes (this could be via a Karpenter aware label)
- Best effort

**How important is this feature to you?**
Without this functionality Karpenter limits aren't really usable for anything more complex than a single provisioner; we don't have any clusters where a single provisioner would work.

Cluster Autoscaler can already do this so not having it available makes migrating to Karpenter without losing capabilities impossible.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Closing this as a duplicate to #2474. It would be great to add some of these ideas over there and continue that discussion to expand the proposed feature set.
