### ISSUE TITLE
Upgrade Guide and FAQ pages are inconsistent about kubernetes versions supported by Karpenter

### ISSUE THREAD

**Issue by mupuri** [aws/karpenter#4201]
### Description
Upgrade Guide says Karpenter v0.28.0 is incompatible with Kubernetes version 1.26 but the FAQ says Karpenter is tested with Kubernetes v1.21-v1.27. Which one is correct?

**What problem are you trying to solve?**
We're trying to determine the latest version of Kubernetes we can upgrade our clusters to.

**How important is this feature to you?**
Pretty important because without this, we will be blocked on upgrading our clusters to the latest Kubernetes version.

**Comment by jonathan-innis** [comment]
Just opened a PR to help clarify this point. Let me know if the updated lingo is not clear.

**Comment by mupuri** [comment]
> Just opened a PR to help clarify this point. Let me know if the updated lingo is not clear.

Thank you! That clarifies the point.
