### ISSUE TITLE
Please implement containerLogMaxSize and containerLogMaxFiles on Provisioner kubelet configuration

### ISSUE THREAD

**Issue by tauanlemos** [aws/karpenter#4213]
### Description

**What problem are you trying to solve?**

Hi there. I'm having some issues with disk pressure on a Cluster and to tackle them I have to do some configuration on log file sizes

I tried adding the fields `containerLogMaxSize` and `containerLogMaxFiles` to spec.kubeletConfiguration but received the following error on cloudformation

```
Received response status [FAILED] from custom resource. Message returned: 
Error: b'error: error validating "/tmp/manifest.yaml": error validating data: 
[ValidationError(Provisioner.spec.kubeletConfiguration): unknown field "containerLogMaxFiles" 
in sh.karpenter.v1alpha5.Provisioner.spec.kubeletConfiguration, 
ValidationError(Provisioner.spec.kubeletConfiguration): 
unknown field "containerLogMaxSize" in sh.karpenter.v1alpha5.Provisioner.spec.kubeletConfiguration]
```
[In the docs](https://karpenter.sh/preview/concepts/provisioners/#speckubeletconfiguration) It's stated to `cut an issue if you’d like to see another field implemented.` So I guess that these fields are not yet implemented, right?

**How important is this feature to you?**

This would help me reduce the amount of log files on my nodes, therefore, reducing disk pressure

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tauanlemos** [comment]
You mean setting userData on the NodeTemplate? I tried that with no success. The template changed but when I spined up a new node, nothing changed. 

I validated by fetching the config with the command `kubectl get --raw "/api/v1/nodes/NODE_ID/proxy/configz" `, maybe I should look into another place?

**Comment by grzegorzlyczba** [comment]
@tauanlemos I have AWSNodeTeamplate with
```
  userData: |
    #!/bin/bash
    echo $(jq '.containerLogMaxFiles=10|.containerLogMaxSize="100Mi"' /etc/kubernetes/kubelet/kubelet-config.json) > /etc/kubernetes/kubelet/kubelet-config.json
```
and see the change applied in files locally on VM and using kubectl you posted. I'm using AL2.
