### ISSUE TITLE
Karpenter does not delete all nodes when the provisioner is deleted

### ISSUE THREAD

**Issue by Nuru** [aws/karpenter#4223]
### Description

**Observed Behavior**:

I want to create and destroy EKS clusters using Terraform, and using Karpenter as my sole source of EKS Nodes. (I deploy Karpenter itself to Fargate).

I have not found a reliable way to destroy the cluster without leaving an instance running.

This appears to be a regression to #1955.

**Expected Behavior**:

When I destroy the Karpenter Provisioner, all nodes it provisioned will be destroyed. Maybe Karpenter itself or the Karpenter namespace should have a finalizer that ensures all the instances are destroyed before Karpenter loses its ability to destroy the instances.

**Reproduction Steps**:

- Create and EKS cluster with no nodes
- Deploy Karpenter to the cluster via Fargate
- Deploy a Karpenter Provisioner
- Deploy some stuff to the cluster
- Destroy the deployments and namespaces, leaving only `kube-system` pods running
- Destroy the Karpenter Provisioner
- Destroy Karpenter
- Destroy the EKS cluster

**Versions**:
- Chart Version: v0.16.3
- Kubernetes Version (`kubectl version`): 1.25

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
What version of Karpenter are you using? I just verified that this works in v0.29.0.

**Comment by Nuru** [comment]
As stated in the issue, I was using v0.16.3. I didn't realize how old it was. 

The Helm chart for v0.29.0 has not been released yet, so I upgraded to v0.28.0. I have not seen any problems since. Closing this issue, sorry for the bother.
