### ISSUE TITLE
Karpenter pods are stuck in crashBackOffLoop when installing with kubeflow

### ISSUE THREAD

**Issue by weshallsin** [aws/karpenter#4226]
### Description

**Observed Behavior**:
Karpenter pods are stuck in crashBackOffLoop when installing with kubeflow with following error in controller logs:

```
E0707 13:11:13.081874       1 reflector.go:140] k8s.io/client-go@v0.25.4/tools/cache/reflector.go:169: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://10.100.0.1:443/api/v1/namespaces/karpenter/configmaps?limit=500&resourceVersion=0": dial tcp 10.100.0.1:443: connect: connection refused
W0707 13:11:17.052250       1 reflector.go:424] k8s.io/client-go@v0.25.4/tools/cache/reflector.go:169: failed to list *v1.ConfigMap: Get "https://10.100.0.1:443/api/v1/namespaces/karpenter/configmaps?limit=500&resourceVersion=0": dial tcp 10.100.0.1:443: connect: connection refused
E0707 13:11:17.052283       1 reflector.go:140] k8s.io/client-go@v0.25.4/tools/cache/reflector.go:169: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://10.100.0.1:443/api/v1/namespaces/karpenter/configmaps?limit=500&resourceVersion=0": dial tcp 10.100.0.1:443: connect: connection refused
W0707 13:11:24.032404       1 reflector.go:424] k8s.io/client-go@v0.25.4/tools/cache/reflector.go:169: failed to list *v1.ConfigMap: Get "https://10.100.0.1:443/api/v1/namespaces/karpenter/configmaps?limit=500&resourceVersion=0": dial tcp 10.100.0.1:443: connect: connection refused
E0707 13:11:24.032437       1 reflector.go:140] k8s.io/client-go@v0.25.4/tools/cache/reflector.go:169: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://10.100.0.1:443/api/v1/namespaces/karpenter/configmaps?limit=500&resourceVersion=0": dial tcp 10.100.0.1:443: connect: connection refused
W0707 13:11:38.574514       1 reflector.go:424] k8s.io/client-go@v0.25.4/tools/cache/reflector.go:169: failed to list *v1.ConfigMap: Get "https://10.100.0.1:443/api/v1/namespaces/karpenter/configmaps?limit=500&resourceVersion=0": dial tcp 10.100.0.1:443: connect: connection refused
E0707 13:11:38.574564       1 reflector.go:140] k8s.io/client-go@v0.25.4/tools/cache/reflector.go:169: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://10.100.0.1:443/api/v1/namespaces/karpenter/configmaps?limit=500&resourceVersion=0": dial tcp 10.100.0.1:443: connect: connection refused
panic: error waiting for ConfigMap informer to sync

goroutine 1 [running]:
github.com/samber/lo.must({0x23ae880, 0xc000a01fd0}, {0x0, 0x0, 0x0})
        github.com/samber/lo@v1.37.0/errors.go:53 +0x1f4
github.com/samber/lo.Must0(...)
        github.com/samber/lo@v1.37.0/errors.go:72
github.com/aws/karpenter-core/pkg/operator.NewOperator()
        github.com/aws/karpenter-core@v0.27.0/pkg/operator/operator.go:96 +0x54c
main.main()
        github.com/aws/karpenter/cmd/controller/main.go:34 +0x2e
```

Seeing this on describing the stuck pods:

```
Warning  Unhealthy  60s (x99718 over 2d)  kubelet  Readiness probe failed: Get "http://30.0.48.92:15021/healthz/ready": dial tcp 30.0.48.92:15021: connect: connection refused
```

**Expected Behavior**:
Karpenter pods should be running successfully

**Reproduction Steps** (Please include YAML):
Install kubeflow using following guide : https://awslabs.github.io/kubeflow-manifests/docs/deployment/rds-s3/guide/

Install Karpenter using following guide: https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/karpenter
**Versions**:
- Chart Version: v0.27.0
- Kubernetes Version (`kubectl version`): v1.24.0
- Kubeflow Version: v1.6
- AWS EKS Version: 1.23

**Comment by tzneal** [comment]
It looks like Karpenter can't reach the API Server.  Is the cluster endpoint configured correctly for Karpenter and are security groups setup so that nodes can access the cluster endpoint?

**Comment by weshallsin** [comment]
@tzneal Thanks for your reply. I have double checked the cluster endpoint for Karpenter and the security groups. They are correctly configured.

 The karpenter installation works fine on the cluster until I install kubeflow alongside with it. Makes me wonder if some karpenter configurations are being overwritten but I am not sure where to check. Any suggestions are appericiated.

**Comment by weshallsin** [comment]
@tzneal Please this is what my configmap  looks like.

`apiVersion: v1
data:
  KARPENTER_IRSA_ARN: arn:aws:iam::****:role/kubeflow-karpenter-irsa-dev
  aws.clusterEndpoint: https://*********.gr7.us-east-2.eks.amazonaws.com
  aws.clusterName: kubeflow-cluster-dev
  aws.defaultInstanceProfile: karpenter-kubeflow-cluster-role-dev
  aws.enableENILimitedPodDensity: "true"
  aws.enablePodENI: "false"
  aws.interruptionQueueName: karpenter-kubeflow-cluster-dev
  aws.isolatedVPC: "false"
  aws.nodeNameConvention: ip-name
  aws.vmMemoryOverheadPercent: "0.075"
  batchIdleDuration: 1s
  batchMaxDuration: 10s
  featureGates.driftEnabled: "false"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"KARPENTER_IRSA_ARN":"arn:aws:iam::*******:role/kubeflow-karpenter-irsa-dev","aws.clusterEndpoint":"*******.gr7.us-east-2.eks.amazonaws.com","aws.clusterName":"kubeflow-cluster-dev","aws.defaultInstanceProfile":"karpenter-kubeflow-cluster-role-dev","aws.enableENILimitedPodDensity":"true","aws.enablePodENI":"false","aws.interruptionQueueName":"karpenter-kubeflow-cluster-dev","aws.isolatedVPC":"false","aws.nodeNameConvention":"ip-name","aws.vmMemoryOverheadPercent":"0.075","batchIdleDuration":"1s","batchMaxDuration":"10s","featureGates.driftEnabled":"false"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"environment":"dev","owner":"onclusiveml"},"name":"karpenter-global-settings-g5mcg4gkgg","namespace":"karpenter"}}
  creationTimestamp: "2023-07-12T08:53:39Z"
  labels:
    environment: dev
    owner: onclusiveml
  name: karpenter-global-settings-g5mcg4gkgg
  namespace: karpenter
  resourceVersion: "940698"
  uid: 18348ce6-07f4-4e6b-acec-6b7f127fa9a5`

Could be a networking issue - istio related: When liveness / readiness checks are removed, the pod shows up as running but other services cannot access it still. 

@RonsenbergVI

**Comment by tzneal** [comment]
Does curling your endpoint from your node work?  What does it resolve to?

**Comment by weshallsin** [comment]
@tzneal The cluster endpoint does get resolved when trying from within the node. I see the SSL certificate error:

```
[root@ip-30-0-49-247 /]# curl https://2878A88E5074D8D90A65B989C8600D2F.gr7.us-east-2.eks.amazonaws.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by rohitsaboo** [comment]
@weshallsin did this get resolved for you and what did you have to do to resolve this? We are seeing a similar problem.
