### ISSUE TITLE
Run Karpenter without ConfigMaps

### ISSUE THREAD

**Issue by bwagner5** [aws/karpenter#4255]
### Description

**What problem are you trying to solve?**

I'd like to be able to run Karpenter without the Global Settings Config Map and Logging Config Map. To support this we need to expose at least `CLUSTER_NAME` as a CLI arg / ENV var and default to a sensible logging configuration. 

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Closing as this should be fixed with v0.33.0
