### ISSUE TITLE
Karpenter consolidation will not move pods to Manged Node Group

### ISSUE THREAD

**Issue by Nuru** [aws/karpenter#4266]
### Description

**Observed Behavior**:

Karpenter failed to deprovision its nodes after sufficient capacity for all their workloads was provisioned in a Managed Node Group. The only events logged were "can't replace with a cheaper node". I am reasonably confident that none of the pods were protected from eviction via annotations or PDBs.

1. Launched EKS cluster with no nodes
2. Installed Karpenter (v0.28.0) and provisioner into cluster via Fargate, with consolidation enabled
3. Installed some other apps/deployments into the cluster
4. Karpenter provisioned 2 nodes
5. Deployed a manged node group to the cluster with twice the capacity of the Karpenter provisioned nodes
6. Waited 12 hours
7. **Karpenter did not deprovsion its nodes as I expected**
8. Manually cordoned and drained Karpenter's nodes
9. Kubernetes easily transferred the pods to the managed node groups
10. Karpenter automatically deprovisioned the now-empty nodes.

**Expected Behavior**:

According to the [FAQ](https://karpenter.sh/v0.28/faq/#how-does-karpenter-interact-with-aws-node-group-features), Karpenter is intended to work alongside Managed Node Groups:

> Provisioners are designed to work alongside static capacity management solutions like EKS Managed Node Groups and EC2 Auto Scaling Groups. You can manage all capacity using... a mixed model with dynamic and statically managed capacity....

I expected that Karpenter would include the Managed Node Groups in its bin-packing strategy and automatically move the pods to the Managed Node Groups and deprovision the excess capacity it provisioned.

**Reproduction Steps**:

See "Observed Behavior" above

**Versions**:
- Chart Version: 0.28.0
- Kubernetes Version (`kubectl version`): 1.25.9

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Would you be able to provide the karpenter logs, provisioner and AWSNodetemplate?

**Comment by Nuru** [comment]
@engedaam asked:

> Would you be able to provide the karpenter logs, provisioner and AWSNodetemplate?

Requested files attached as single ZIP archive.

Significant events:

- The larger Managed Node Group instances were launched at about `2023-07-12T19:20:00Z`
- At around `2023-07-13T06:39:00Z` I gave up on waiting for Karpenter to scale down and manually cordoned and drained one of its 2 deployed instances.
- After the instance was empty, Karpenter deprovisioned it.
- I then cordoned and drained its other instance, after which Karpenter deprovisioned it.

[Karpenter-logs-provisioner-nodetemplate.zip](https://github.com/aws/karpenter/files/12059482/Karpenter-logs-provisioner-nodetemplate.zip)

**Comment by engedaam** [comment]
Karpenter consolidation will not automatically assume it will need to move pods into manned node group. Did you add any new taints or labels on the pods?

**Comment by Nuru** [comment]
Thinking a bit more about this case, it is not an "obvious given" how Karpenter should treat the capacity of Managed Node Groups. My expectation was that Karpenter would see the excess capacity of the Managed Node Groups and, while bin packing, use that in favor of its own provisioned nodes. However, I can see an argument where Karpenter expects that the Kubernetes Cluster Autoscaler or some other mechanism would instead be responsible for removing the excess capacity from the Managed Node Group, and therefore it should leave pods where they are in anticipation of down-scaling by the Cluster Autoscaler.

Now that I have given it more consideration, I do not think there is a single right answer. In my case, we want to have a couple of on-demand (or reserved) instances running as managed nodes to ensure some minimum capacity in the event of a large-scale failure (such as an availability zone going down), and then use Karpenter to provision Spot instances, so we want Karpenter to push as much work on to the Managed Nodes as it can, in order to fully utilize them. However, it is easy to conceive of someone wanting to put as much workload on Karpenter-provisioned Spot instances as possible, and therefore wanting Karpenter to move pods off of the Managed Nodes. (Unfortunately, pod anti-affinity does not help much here, because it generally only affects initial placement of pods and does not influence their eviction and movement to new nodes after they have already been placed.)

Perhaps this should be a configurable option. `preferManagedNodegroup` or something like that.

**Comment by jonathan-innis** [comment]
Dug into this and found the issue. Working on a fix right now. Looks like we are not considering existing capacity on the cluster in our scheduling algorithm for consolidation which meant that we were not seeing that MNG could schedule these pods. 

> However, I can see an argument where Karpenter expects that the Kubernetes Cluster Autoscaler or some other mechanism would instead be responsible for removing the excess capacity from the Managed Node Group, and therefore it should leave pods where they are in anticipation of down-scaling by the Cluster Autoscaler

I'm of the opinion that we should be more naive than this. The other capacity that isn't Karpenter-owned on the cluster should be considered "static capacity" and Karpenter should treat that capacity as if it can't change. To avoid thrashing between Karpenter and CAS, I would expect that someone would draw a line between which workloads can schedule where with taints/tolerations/labels/nodeSelectors. You can imagine a scneario where that the node capacity is coming from on-prem statically provisioned nodes or some other replica count of nodes that can't change.

**Comment by Mihail-blip** [comment]
Confirm, noticed similar behaviour with self-managed/static nodes (not using managed node groups).
 - In production we create 3 static nodes which run blue release resources
 - In case of green deployment, karpenter schedules 3 additional nodes to handle green release.
 - most of the green environment ends up running on karpenter managed nodes.
 - when we delete/scale down blue release, karpenter doesn't consider static nodes and keeps green release running on karpenter managed nodes, thus we end up with double the number of nodes, half of which (self managed nodes) are empty.
Ideally, it should instead evict nodes, move all resources to self-managed nodes, and terminate provisioned karpenter nodes. There are no strict affinity, topology constrains or PDB that would prevent karpenter nodes from consolidation.
