### ISSUE TITLE
Consolidation affecting Infra Stability

### ISSUE THREAD

**Issue by sekar-saravanan** [aws/karpenter#4289]
### Description

**What problem are you trying to solve?**

1. karpenter cannot able to find required number of nodes exactly based on pending pods requirements. This is because of 
karpenter don’t know what is exact memory capacity provisioned in the kubernetes node. It will always consider memory capacity as actual memory with 0.75 % overhead. (as this overhead percentage can be modified in cluster level)

We have calculated the memory for few instances type with Overhead of 0.025.
<img width="1288" alt="image" src="https://github.com/aws/karpenter/assets/110888783/f3704fae-a1f1-4af7-a7c4-3a2f79106aec">

Due to this, karpenter cannot able to provisioner correct number of nodes and there might be chances of consolidation happening while we scaled upto the particular node count. and infra took sometime to get stabilize [to get complete a consolidation]

2. While working with multiple instance types, karpenter always replacing one node with another cheaper node. Due to this pods moving to other nodes [and infra will be not stable]

For example:
My cluster is running with below worker nodes.
c5.9xlarge => 10 machines (300 pods) [specified limit for 10 machines capacity in provisioner]
c5.12xlarge => 5 machines (200 pods) [specified limit for 10 machines capacity in provisioner]

If the workloads running in c5.9xlarge instances reduced from 300 to 150 nodes. and few of the c5.9xlarge instances are removed. Now cluster looks like below
c5.9xlarge => 5 machines (150 pods)
c5.12xlarge => 5 machines (200 pods)

Now karpenter is doing consolidation by replacing c5.12xlarge instance to c5.9xlarge (cheaper node) and pods get moved to other nodes.
Now cluster looks like below
c5.9xlarge => 10 machines (300 pods)
c5.12xlarge => 2 machines (50 pods)

I know, karpenter performing this consolidation for cost reduction purpose. but it affects the infra stability.  If we get a control to disable single / multi node (replace) consolidation, it will be helpful.

3. By default ttl seconds for consolidation is 15 sec. Have a control to set this ttl, help us to reduce the deprovisioning actions.

For example: 
I was running a deployment with 200 pods in 10 nodes and scaling down 100 pods [5 nodes can be removed]
and within 30 sec 100 new pods are provisioned by other workload. so again 5 nodes getting provisioned by karpenter.

**How important is this feature to you?**

1. Calculating exact value (cpu, memory) provisioned by ec2 instance, which helps karpenter to provision a node very effectively. Otherwise, configuring vmOverheadPercentage provisioner level helps us to tweak this calculation. 

2. Getting control for below configuration will be more helpful for who are all more concerned about infra stability instead of infra cost.
  - Setting TTL value for consolidation
  - To disable a consolidation by replace.

**Comment by jonathan-innis** [comment]
Hi @sekar-saravanan, thanks for opening this issue. I'm going to close this issue as a duplicate since it looks like this issue captures two other issues that are already open: #1738 and #3607

**Comment by sekar-saravanan** [comment]
@jonathan-innis - any idea about get a control to disable single / multi node (replace) consolidation.
