### ISSUE TITLE
Dockerfile for Karpenter

### ISSUE THREAD

**Issue by garvinp-stripe** [aws/karpenter#4311]
### Description

**What problem are you trying to solve?**
I am trying to build Karpenter to from the binary into our custom docker image. I am wondering if it is possible to expose/ provide Dockerfile for building the image.

I know at this time Karpenter uses ko to build the image. Our existing CI system doesn't support KO at this time so it would be great to have Dockerfile. 

Thanks!

**How important is this feature to you?**
Medium

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@garvinp-stripe Is it possible for you to generate a minimal `Dockerfile` and build Karpenter from source on a given tag using a multi-stage `Dockerfile`?

**Comment by garvinp-stripe** [comment]
Ya I wonder if there are other recommendation but this is what I have
```
# Build the controller binary
FROM golang:1.20 as builder

WORKDIR /workspace

COPY . . 

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -o controller cmd/controller/main.go

FROM alpine:latest

WORKDIR /
COPY --from=builder /workspace/controller .

ENTRYPOINT ["/controller"]
```

**Comment by mamoit** [comment]
@garvinp-stripe my 5min take on it:
``` dockerfile
FROM golang:1.20-alpine as builder

ENV CGO_ENABLED=0 GO111MODULE=on

# some env vars as arguments if you need to change the arch or the karpenter version
ARG GOOS=linux
ARG GOARCH=amd64
ARG KARPENTER_VERSION=latest

# simpler install with copying the whole repo
RUN go install github.com/aws/karpenter/cmd/controller@${KARPENTER_VERSION} && \
    rm -rf pkg ~/.cache

# start from nothing
FROM scratch

# add just the binary
COPY --from=builder /go/bin/controller .

ENTRYPOINT ["/controller"]
```

**Comment by garvinp-stripe** [comment]
That looks good
