### ISSUE TITLE
Ability to set up unlimited/standard CPU Credits for burstable instance types

### ISSUE THREAD

**Issue by Mihail-blip** [aws/karpenter#4312]
### Description

**Ability to configure unlimited CPU credits if instance type supports it**

**Relatively important**

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-performance-instances-unlimited-mode.html 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
t3+ instance types support burstable by default. Are you trying to use a t2 or t1 instance type?

**Comment by Mihail-blip** [comment]
In am not sure if it would ever pick a t2 instance.
I gave karpenter freedom to choose any instances from "m", "c" and "t" families. I would like to be sure  if it picks a burstable type instance, it would have unlimited credits.

**Comment by bwagner5** [comment]
Since t3+ uses unlimited by default, I'd rather not add this to Karpenter's API surface. You're able to set the default options for your account per region and per burstable instance type: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-performance-instances-unlimited-mode-concepts.html#unlimited-mode-enabling:~:text=long%20as%20needed.-,Enable%20unlimited%20mode,-You%20can%20switch

**Comment by bwagner5** [comment]
Feel free to reopen if the account-level regional configuration does not solve for your use-case. Another option would be to restrict to t3+. That may limit your diversity which may be an issue if using spot.

**Comment by Mihail-blip** [comment]
> Feel free to reopen if the account-level regional configuration does not solve for your use-case. Another option would be to restrict to t3+. That may limit your diversity which may be an issue if using spot.

Thanks for taking a look at this. Account level configuration is a good alternative.
