### ISSUE TITLE
Clarification in behaviour when MaxSpotInstanceCountExceeded exception is reached

### ISSUE THREAD

**Issue by cbugneac-nex** [aws/karpenter#4318]
### Description

This is to clarify one thing in behaviour.

Here, https://aws.amazon.com/blogs/containers/using-amazon-ec2-spot-instances-with-karpenter/ under `Capacity type` it states:

```
If the Spot capacity is not available, then Karpenter falls back to On-Demand Instances to schedule the pods. However, if a Spot quota limit has been reached at the account level, you might get a MaxSpotInstanceCountExceeded exception. In this case, Karpenter won’t perform a fallback.
```

Is that still the case ? Or the blog post info is outdated and not relevant anymore ?

I'm wondering why Karpenter cannot fallback from reaching Spot quota limit back to On-Demand (if configured to use both) automatically given On-Demand quota is not reached yet ?

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
I don't think this is correct. I just spun up enough spot nodes to reach this, added in my on-demand requirement, and saw it provision on-demand nodes. Additionally, did the same, but with on-demand and spot both enabled, and saw it fallback to on-demand after I got the MaxSpotInstanceCountExceeded. Have you seen differently?

**Comment by cbugneac-nex** [comment]
Thanks @njtran for confirmation.
Nope, I haven't seen differently but haven't found this behaviour documented anywhere and wanted to confirm.
I guess the above blog post os outdated.

**Comment by jonathan-innis** [comment]
Yeah, the blog post is about a year old so we assume that some of the information will be out-of-date. I'm going to close this since it looks like the fallback behavior works.
