### ISSUE TITLE
karpenter provisioning of nodes very aggressive sometimes

### ISSUE THREAD

**Issue by tejarora** [aws/karpenter#4340]
### Description

**Observed Behavior**:
When a deployment is scaled to add more pods, karpenter provisions nodes for provisionable pods. Noticed that karpenter over-provisions nodes. 

INFO    controller.provisioning Found 16 provisionable pod(s)

INFO    controller.provisioning Computed 16 new node(s) will fit 16 pod(s)      

INFO    controller.provisioning Launching node with 1 pods requesting {"cpu":"285m","memory":"740Mi","pods":"7"} from types m5.large
.... 16 times

FYI, an m5.large can hold as many as 15-20 of the above application pods (in addition to 5-6 daemonset pods like node, proxy, csi controller, etc). Have seen this on existing nodes.

Now, I have a large number of nodes most of them running 1-3 of the application pods

This is far more expensive than expected.

What is causing karpenter to provision nodes so aggressively? Does it not try to aggregate resource needs of the pending pods?

Happy to provide additional info.

**Expected Behavior**:

Expecting 1-2 nodes provisioned for the 16 provisionable pods, instead of 16 nodes

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 
- Kubernetes Version (`kubectl version`): 1.25 (on AWS EKS)

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Can you provide your Provisioner, AWSNodeTemplate, and Logs?

**Comment by tejarora** [comment]
Attaching provisioner and awsnodetemplate. I already provided the appropriate karpenter controller log snippet... What else do you need?
[provisioner.txt](https://github.com/aws/karpenter/files/12178724/provisioner.txt)
[awsnodetemplate.txt](https://github.com/aws/karpenter/files/12178725/awsnodetemplate.txt)

**Comment by engedaam** [comment]
Do you have any pod or node affinity for the pods? Would you be able to share the deployment spec?

**Comment by engedaam** [comment]
Also have you considered using consolation? If karpenter over-provisions nodes, consolidation will terminate the excise nodes, which could be a potential work around for the time being

**Comment by tejarora** [comment]
The deployment spec does have a topology spread constraint, to try and spread across AZs, and across nodes. Perhaps, this is the cause for over-provisioning nodes? Here's the part of the spec:

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{.Values.metadata.name}}-v{{$.Values.metadata.version}}
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{.Values.metadata.name}}-v{{$.Values.metadata.version}}

I don't have consolidation specified, I tried to use it once and I got an error when I added the consolidation attribute to the Provisioner spec, based on documentation:

spec:
  consolidation:
    enabled: true

When I applied the spec, I got this:

**strict decoding error: unknown field "spec.consolidation"**

Please advise. If topology spread constraint is the issue, I can remove it and I'd like to add consolidation, but I don't have proper documentation on how to.... Please let me know how to add consolidation

**One question regarding consolidation: I don't want karpenter to de-provision nodes that it did not provision. Is that the behavior as designed?**

**Comment by engedaam** [comment]
Based off the topology spread it would seem that karpenter would spread the pods as much as it can to fulfill the spread. Consolidation then should adjust the number of nodes to get the cluster to a reasonable state.
Here is some guidance on using consolidation: https://karpenter.sh/docs/concepts/provisioners/#specconsolidation. You can find example use-cases. Also, Karpenter will only de-provision nodes it has provisioned. That is the behavior consolidation was implemented.

**Comment by tejarora** [comment]
I'll remove the topology spread constraint and let you know if that leads to a change in karpenter behavior.

Regarding consolidation, I tried what's in the documentation... but it failed. I sent you the error message.

`spec:
  consolidation:
    enabled: true`

does not work. I get the error
strict decoding error: unknown field "spec.consolidation"

**Comment by tejarora** [comment]
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  consolidation:
    enabled: true
  ttlSecondsAfterEmpty: 60
  providerRef:
    name: default
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["m5.large"]

**Comment by tejarora** [comment]
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  consolidation:
    enabled: true
  ttlSecondsAfterEmpty: 60
  providerRef:
    name: default
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["m5.large"]
```

The above doesn't work.
When applied, I get
strict decoding error: unknown field "spec.consolidation"

**Comment by engedaam** [comment]
You would need to remove `ttlSecondsAfterEmpty`. Consolidation will remove nodes that are empty automatically.

**Comment by tejarora** [comment]
I removed ttlSecondsAfterEmpty and I'm still getting the same error
`strict decoding error: unknown field "spec.consolidation"`

**Comment by engedaam** [comment]
What is version of karpenter are you using?

**Comment by tejarora** [comment]
We are using an old version of karpenter. Will upgrade to 0.29.2 (the latest stable) and update here on whether that fixes the issues

**Comment by FernandoMiguel** [comment]
@tejarora make sure to update CRDs too
