### ISSUE TITLE
instances change and pod restart too frequent with spot instance and consolidation enabled

### ISSUE THREAD

**Issue by Sumit0789** [aws/karpenter#4359]
### Description

**Observed Behavior**: instances change and pod restart too frequent with spot instance and consolidation enabled

**Expected Behavior**: Only 1 or 2 instance should be terminate as instances are spot but with consolidation enabled it is keep trying to replace pods on new instance.

**Reproduction Steps** (Please include YAML): 

**Versions**:
- Chart Version: 
- Kubernetes Version (`kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.14", GitCommit:"0018fa8af8ffaff22f36d3bd86289753ca61da81", GitTreeState:"clean", BuildDate:"2023-05-17T16:28:57Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.15-eks-a5565ad", GitCommit:"af0b16a331376384fe84445fe2f8d4cb468b4148", GitTreeState:"clean", BuildDate:"2023-06-16T17:35:37Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Can you provide a little bit more information about your pods, nodes, and provisioner, as well as expected behavior? Logs would be helpful as well any relevant kube events on the pod/node. 

As stated, I'm having a hard time understanding the specifics of your request, and how we can do better.

**Comment by ellistarn** [comment]
Consolidation will respect these: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
