### ISSUE TITLE
Command is no longer valid error

### ISSUE THREAD

**Issue by Omar-Bishtawi** [aws/karpenter#4364]
### Description

**Observed Behavior**:
this error keep pooping from time to time in karpenter logs 
```
deprovisioning via "consolidation", computing deprovisioning decision, command is no longer valid, delete, terminating 1 machines {instnace_name}/m6g.xlarge/on-demand	{"commit": "61cc8f7-dirty"}
```

**Expected Behavior**:
not sure if this is normal or not, and nothing is mentioned about this error in the documentation

**Versions**:
- Chart Version: v0.29.0
- Kubernetes Version :1.27

**Comment by ellistarn** [comment]
This is not an error, and occurs when pod churn has happened during consolidation. I'll cut a PR to reclassify as INFO.

**Comment by ellistarn** [comment]
Updated this emit a DEBUG instead of an ERROR.
