### ISSUE TITLE
Nodes provisioned by karpenter going to NotReady state. Not able to access the Nodes

### ISSUE THREAD

**Issue by nkn1111** [aws/karpenter#4365]
### Description

**Observed Behavior**:
Trying to provision a pod with nodeSelector as a `karpenter.sh/provisioner-name: amd`. Node is getting provisioned with the expected instance profile and SG. But goes into `NotReady` state. Not able to connect to the node via SSM as well.

**Expected Behavior**:
The node should get to Ready state and should be able to access via SSM.

**Error observed while describing the node**:
`Failed to get lease: leases.coordination.k8s.io "ip-xx-xx-xx-xx.region.compute.internal" not found`

Other kube-system pods are in the `Pending` state for this Node
> ❯ kgp -n kube-system | grep Pending
aws-node-xxx                                      0/1     Pending   0          34m
ebs-csi-node-xxx                                  0/3     Pending   0          34m
efs-csi-node-xxx                                  0/3     Pending   0          34m
kube-proxy-xxx                                    0/1     Pending   0          34m

**Some fixes I tried**:
#2423
#3748 
#1165

**Versions**:
- Chart Version: 0.28.1 (upgraded from 0.27.2)
- Kubernetes Version: v1.26.6

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Can you provide your full provisioner? Are you using EKS Optimized AMI? Custom userdata? Are you able to get any nodes to connect to your cluster? Do you have the SSM Agent configured?

There are some troubleshooting steps here: https://karpenter.sh/docs/troubleshooting/#node-notready

**Comment by nkn1111** [comment]
I have gone through the troubleshooting docs. And it asks me to connect to the Node which I cannot.

This is the provisioner am using.
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: amd
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: [t3a.large, t3a.medium]
    - key: kubernetes.io/os	
      operator: In	
      values:	
        - linux	
    - key: kubernetes.io/arch	
      operator: In	
      values:	
        - amd64
  limits:
    resources:
      cpu: '20'
      memory: 50Gi
  consolidation:
    enabled: true
  providerRef:
    name: default


I have not given the amiSelector, it should be the default value `AL2`.  This is the AMI the node is running on `amazon-eks-node-1.26-v20230728`. Not passing any userdata as well.

The eks managed node created using TF is able to connect to the cluster and attaching the SSMcore policy am able to SSM to the nodes but the nodes provisioned by Karpenter are not behaving the same.

**Comment by nkn1111** [comment]
Looks like I was using a different subnet from the VPC. I changed the subnetSelector to use the subnet of the EKS cluster and the nodes got provisioned. Thank you so much. Closing this issue.
