### ISSUE TITLE
defaulting.webhook.karpenter.sh": failed to call webhook: Post "https://karpenter.karpenter.svc:443/default/karpenter.sh?timeout=10s": no service port 443 found for service "karpenter".

### ISSUE THREAD

**Issue by nandeeshb09** [aws/karpenter#4368]
I have deployed karpenter with 1.22.1 version and trying to deploy provision-er , but I am unable to do  and getting below error.

As in this version webook is using 8443 and I tried to change 443 , as webook is taking by default 443 port.

When the default 8443 used , was getting below error.

error when creating "gernal-purpose.yaml": Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.sh": failed to call webhook: Post "https://karpenter.karpenter.svc:443/default/karpenter.sh?timeout=10s": no service port 443 found for service "karpenter".

So , I tried to change the port to 443 , but still I am getting below error and even though port is allowed on security group.

Error from server (InternalError): error when creating "gernal-purpose.yaml": Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.karpenter.svc:443/default/karpenter.k8s.aws?timeout=10s": dial tcp ip:443: connect: connection refused

Please help me on this.

**Comment by ellistarn** [comment]
Are you using the default helm install? It should wire up these ports for you. Is there a reason you're trying to run with different ports for the webhook?

**Comment by nandeeshb09** [comment]
@ellistarn No , I have modified the helm charts based on my requirements , but in the version 1.22.1 webhook is configured with port 8443.
But when I try to install provision-er, its giving error below and its taking 443 port , but in the version 1.22 its 8443 port.
 Post "[https://karpenter.karpenter.svc:443/default/karpenter.sh?timeout=10s](https://karpenter.karpenter.svc/default/karpenter.sh?timeout=10s)": no service port 443 found for service "karpenter".

**Comment by nandeeshb09** [comment]
Any help on this , as I am not able to deploy any provisioner with this..

**Comment by ind07g5q** [comment]
Did you found any solution?
We are also facing same issue.

**Comment by nandeeshb09** [comment]
@ind07g5q Hi Umesh, Yes I figured out that there is an issue at helm charts,  8443 port on values.yaml file, but on webook we have 443 port, because of this its causing an issue.

For this you have to update to 8443 on both mutatingwebhookconfiguration.admissionregistration.k8s.io and 
ValidatingWebhookConfiguration.admissionregistration.k8s.io from 443, then it will work..

@ellistarn This is not a question , its issue at your end, please fix it.

**Comment by csiejoey** [comment]
> @ind07g5q Hi Umesh, Yes I figured out that there is an issue on helm charts, 8443 port on values.yaml file, but on webook we got 443 port, because of this its causing an issue.
> 
> For this you have to update to 8443 on both mutatingwebhookconfiguration.admissionregistration.k8s.io and ValidatingWebhookConfiguration.admissionregistration.k8s.io from 443, then it will work..

I'm coming from Kubenetes 1.27, Karpenter 0.29.2 and I encountered the same 443 issue.
Changing mutatingwebhookconfiguration to 8443 did fix the error. Thanks.

**Comment by linkthai** [comment]
> I'm coming from Kubenetes 1.27, Karpenter 0.29.2 and I encountered the same 443 issue. Changing mutatingwebhookconfiguration to 8443 did fix the error. Thanks.

I'm having the same setup but is using ArgoCD to deploy the karpenter helm chart as a dependency in my own umbrella chart. I have checked every resources deployed, both the mutatingwebhookconfiguration and ValidatingWebhookConfiguration, all of them show port number 8443. 

I can't even understand where it gets the https://karpenter.karpenter.svc:443/default/karpenter.sh from. If anyone have any idea how to deal with this error in GitOps, I'll appreciate.

**Comment by nandeeshb09** [comment]
@linkthai Its under mutatingwebhookconfiguration.admissionregistration.k8s.io defaulting.webhook.karpenter.sh, change the port here to 8443. It will work..

**Comment by RomanBats** [comment]
I have a similar situation. 
When I manually change defaulting.webhook.karpenter.k8s.aws MutatingWebhookConfiguration to any other port that does not exist, 9443 for example, I get an error: 

> one or more objects failed to apply, reason: Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.kube-system.svc:9443/default/karpenter.k8s.aws?timeout=10s": no service port 9443 found for service "karpenter"


But when I switch back to 8443 - I am getting:

> one or more objects failed to apply, reason: Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.sh": failed to call webhook: Post "https://karpenter.kube-system.svc:443/default/karpenter.sh?timeout=10s": no service port 443 found for service "karpenter"

It is almost like 8443 is defaulted back to 443

**Comment by nandeeshb09** [comment]
@RomanBats I think your changing only in defaulting.webhook.karpenter.k8s.aws MutatingWebhookConfiguration. You should change it in 4 places as mentioned below webooks.

ValidatingWebhookConfiguration.admissionregistration.k8s.io validation.webhook.karpenter.sh
ValidatingWebhookConfiguration.admissionregistration.k8s.io validation.webhook.karpenter.k8s.aws
mutatingwebhookconfiguration.admissionregistration.k8s.io defaulting.webhook.karpenter.sh
mutatingwebhookconfiguration.admissionregistration.k8s.io defaulting.webhook.karpenter.k8s.aws

**Comment by RomanBats** [comment]
@nandeeshb09, I doubt it is the case.
I am installing Karpenter on an empty EKS cluster without any nodes. Thus, I don't have CoreDNS running. I cannot prove it, but I suspect it has something to do with DNS SRV resolution, which does not work (no CoreDNS) and [defaults to 443](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#service-reference).

**Comment by linkthai** [comment]
@nandeeshb09 @RomanBats @csiejoey @ind07g5q Please look into the #4454 issue I made that might explain why and show how to fix the problems. You might need to delete those old webhooks instead of changing them to new ports, which could potentially cause issue later on because the karpenter resources still use those old webhooks.

**Comment by RomanBats** [comment]
@linkthai, yep, you are correct! I see the old webhook in the cluster. Removing it helps.
Many thanks!
