### ISSUE TITLE
Is karpenter compatible with instance target type?

### ISSUE THREAD

**Issue by ku524** [aws/karpenter#4377]
### Description

**How can the docs be improved?**
As the title suggests, does Karpenter respect the ELB's deregistration delay during node deprovisioning?

As many of you know, ELB features a deregistration delay. When deregistering a target, ELB stops sending new requests but must still handle responses for the requests already sent. The deregistration delay determines how long to wait for these existing requests. If the target type is IP, it seems that everything could be managed simply by configuring the k8s resources.

My main concern lies when the target type is instance. When a node is deprovisioned, the aws-loadbalancer-controller should detect this and deregister it from the target group, preventing it from receiving new traffic. However, the issue arises with the preexisting traffic. What happens to the requests that were already sent? Is there a mechanism that adequately considers these previously dispatched requests? If not managed correctly, I presume a 504 response would be returned.

My first question is whether my assumption is correct that these requests are not properly managed. If so, this should be documented in the Karpenter documentation: 'To use karpenter, you must use only ip as the target type.' While registering and deregistering targets with ELB is the responsibility of the aws-loadbalancer-controller, compatibility with specific technologies could be, and indeed needs to be, specified in the karpenter documentation.

Act

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
When the node is cordoned, we add the `node.kubernetes.io/exclude-from-external-load-balancers` which indicates that the node should no longer be a target.

For existing connections, your application will need to gracefully handle them once it receives a SIGTERM before the `terminationGracePeriodSeconds` has expired.

**Comment by Shubzshah** [comment]
Is there a way I can check this working of Karpenter ? In the logs or somewhere else ?
