### ISSUE TITLE
Karpenter Does not Launch nodes, and not active during scheduling, Lots of logs on nodes that don't exist for weeks

### ISSUE THREAD

**Issue by nadavbuc** [aws/karpenter#4395]
### Description

**Observed Behavior**:
Pods are stuck on pending
No new nodes are being launched
When doing describe pod, only seeing `default-scheduler` and nothing from karpenter
In addition
Seeing many logs for nodes that have not been existed for about a month like
```
2023-08-07T15:57:02.139Z	ERROR	controller.provisioner	creating scheduler, tracking topology counts, getting node ip-172-25-117-93.eu-west-1.compute.internal, Node "ip-172-25-117-93.eu-west-1.compute.internal" not found	{"commit": "34d50bf-dirty"}
```

**Expected Behavior**:
Nodes should be launched - as they had been so far
**Reproduction Steps** (Please include YAML):
I dont know, it started out of the blue
When i completely removed the karpenter controller + its hooks, it launched some new nodes, then back to not creating nodes again

**Versions**:
- Chart Version: 0.28.0 (and also tried upgrading to 0.29.2)
- Kubernetes Version (`kubectl version`): 1.26.6

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
If you ran `kubectl get nodes`, did you see the nodes?

**Comment by nadavbuc** [comment]
No - that node was deleted at least 30days ago (according to our node exporter metrics) and was not found in `get nodes`
but the pod was still in `etcd` and was shown as running and ready
and in kubernetes events (via `kubectl get events`) i could see 
```
Error updating Endpoint Slices for Service default/<my-service>: skipping Pod <my-pod> for Service default/<my-svc>: Node ip-172-25-117-93.eu-west-1.compute.internal Not Found
```

eventually i collected all nodes (3 in total) from karpenter pod's logs, and found each one had a pod shown 
```kubectl get po -A -o wide | grep <node>```

once i terminated these pods it immediately worked as usual

**Comment by tzneal** [comment]
Can you provide the full Karpenter logs for when pods were sitting pending but no new nodes were launched?

**Comment by nadavbuc** [comment]
I see the same logs on our production clusters - but it had no issue working correctly there
i think its more of a kubernetes issue than Karpenter

**Comment by tzneal** [comment]
Alright, that works.  I'll close it, but please re-open if you run into this again.

**Comment by EddieCeausu** [comment]
I recently ran into this same issue where my logs were reporting: 

```
2023-09-28T13:06:10.185Z	ERROR	controller.provisioner	creating scheduler, tracking topology counts, getting node ip-172-25-120-97.ec2.internal, Node "ip-172-25-120-97.ec2.internal" not found	{"commit": "637a642"}
```

Can confirm that removing any lingering pods that were attached to the lost node resolved this issue.
