### ISSUE TITLE
Machines metrics are missing

### ISSUE THREAD

**Issue by RP-flaviojunior** [aws/karpenter#4410]
### Description

**Observed Behavior**:
When I try to get the [Machine Metrics](https://karpenter.sh/preview/concepts/metrics/#machines-metrics)  in /metrics route I can't see machine metrics like `karpenter_machines_created`
**Expected Behavior**:
All machines metrics available
**Reproduction Steps** (Please include YAML):
I've managed to reproduce this problem like so:
```shell
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: test
spec:
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: eks.amazonaws.com/capacityType
      operator: In
      values: ["ON_DEMAND"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["sa-east-1a", "sa-east-1b", "sa-east-1c"]
  labels:
    eks.amazonaws.com/capacityType: ON_DEMAND
    vpc.amazonaws.com/has-trunk-attached: "false"
  limits:
    resources:
      cpu: "20"
      memory: 80Gi
  providerRef:
    name: aws-test
  kubeletConfiguration:
    cpuCFSQuota: false
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 432000
  weight: 10
```

```shell
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: aws-test
spec:
  subnetSelector:
    aws-ids: <sub-id>
  securityGroupSelector:
    aws-ids: <sg-id>
  tags:
    karpenter.sh/discovery: <cluster-name>
  amiFamily: AL2
  userData:  |
    [settings.kubernetes]
    allowed-unsafe-sysctls = ["net.ipv4.tcp_keepalive_time","net.ipv4.tcp_keepalive_intvl","net.ipv4.tcp_keepalive_probes"]
    [settings.kernel.sysctl]
    "net.core.rmem_default" = "31457280"
    "net.core.wmem_default" = "31457280"
    "net.core.wmem_max" = "33554432"
    "net.core.somaxconn" = "65535"
    "net.core.netdev_max_backlog" = "65536"
    "net.core.optmem_max" = "25165824"
    "net.ipv4.tcp_mem" = "786432 1048576 26777216"
    "net.ipv4.tcp_rmem" = "8192 87380 33554432"
```

**Versions**:
- Chart Version: v0.29.2
- Kubernetes Version (`kubectl version`): v1.25.2

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
I am able to see the metrics, but it does look like they are not initialized to 0, so you'd only see these if Karpenter has created a machine.

```
> karpenter git:(main) kubectl port-forward svc/karpenter -n karpenter 8000:8000
Forwarding from 127.0.0.1:8000 -> 8000
Forwarding from [::1]:8000 -> 8000
```

Before Scaling:

```
> curl -s 127.0.0.1:8000/metrics | grep karpenter_machines_created
```

After Scaling:

```
> curl -s 127.0.0.1:8000/metrics | grep karpenter_machines_created
# HELP karpenter_machines_created Number of machines created in total by Karpenter. Labeled by reason the machine was created and the owning provisioner.
# TYPE karpenter_machines_created counter
karpenter_machines_created{provisioner="default",reason="provisioning"} 1
```

**Comment by jonathan-innis** [comment]
To add to what @bwagner5 said: this is the expected behavior for prometheus counter metrics. They aren't surfaced at the metric server until they are fired at least once.

**Comment by RP-flaviojunior** [comment]
Thanks @bwagner5!
The metric is working!!
