### ISSUE TITLE
Windows container DNS resolution failure

### ISSUE THREAD

**Issue by andrewleech** [aws/karpenter#4420]
### Description

**Observed Behavior**:
I'm trialling the new Windows node / container support for use in CI build systems and am currently blocked on a DNS resolution issue.

Gitlab runner output:
```
Using Kubernetes namespace: default
Using Kubernetes executor with image mcr.microsoft.com/windows/servercore:ltsc2022 ...
Using attach strategy to execute scripts...
Preparing environment
Waiting for pod default/runner-tughempr-project-2452-concurrent-0r8xkj to be running, status is Pending
	Unschedulable: "0/4 nodes are available: 4 node(s) had untolerated taint {eks.amazonaws.com/compute-type: fargate}. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling."
<snip>
Waiting for pod default/runner-tughempr-project-2452-concurrent-0r8xkj to be running, status is Pending
	Unschedulable: "0/4 nodes are available: 4 node(s) had untolerated taint {eks.amazonaws.com/compute-type: fargate}. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling."
Waiting for pod default/runner-tughempr-project-2452-concurrent-0r8xkj to be running, status is Pending
	ContainersNotInitialized: "containers with incomplete status: [init-permissions]"
	ContainersNotReady: "containers with unready status: [build helper]"
	ContainersNotReady: "containers with unready status: [build helper]"
<snip>
Waiting for pod default/runner-tughempr-project-2452-concurrent-0r8xkj to be running, status is Pending
	ContainersNotReady: "containers with unready status: [build helper]"
	ContainersNotReady: "containers with unready status: [build helper]"
﻿Running on RUNNER-TUGHEMPR via 
project-spring...
Getting source from Git repository
Fetching changes with git depth set to 20...
Initialized empty Git repository in C:/builds/myproject/.git/
Created fresh repository.
powershell : fatal: unable to access 'https://gitlab.######.com/myproject.git/': Could not resolve host: 
gitlab.######.com
At C:\scripts-2452-550553\terminate_with_json_script.ps1:7 char:1
+ powershell -File $Path
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (fatal: unable t...novation.com.au 
   :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
Where `gitlab.######.com` is a real hostname that's publicly resolvable and works fine on linux nodes.

Note: this `git pull` is performed within a container / pod running on the node.

There appear to be a couple of open issues like this with windows docker:
* https://github.com/microsoft/Windows-Containers/issues/216
* https://forums.docker.com/t/dns-broken-on-docker-desktop-for-windows/130121

Does the Karpenter test suite happen to test anything like this; running application / test code inside a container / pod that would be using public dns resolution?

**Expected Behavior**:

On linux machines running with the same cluster configuration the git pull runs without issue.

**Reproduction Steps** (Please include YAML):

I'll grab a copy of this when I'm next on the work network (don't have access at home) however it's pretty basic defaults other that specifying the windows os and our company security groups / zones.

**Versions**:
- Chart Version: TBA
- Kubernetes Version (`kubectl version`): TBA

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by andrewleech** [comment]
Solved, not a Karpenter issue 
In my gitlab runner configuration I had the Kubernetes pod DNS Policy set to "cluster-first" (not entirely sure where I copied that from now).
Changing it to: 
```
  [runners.kubernetes]
    dns_policy = "default"
```
Got my windows node and ci job working.

**Comment by gotchipete** [comment]
> > In my gitlab runner configuration I had the Kubernetes pod DNS Policy set to "cluster-first" (not entirely sure where I copied that from now).
> > Changing it to:
> 
> ```
>   [runners.kubernetes]
>     dns_policy = "default"
> ```
> 
>  > Got my windows node and ci job working.
> 
> I thought I had it fixed with gitlab-runner config change, but no that didn't work.
> 
> It looks like pod dnsPolicy and dnsConfig aren't really working properly on windows... well google gets me a couple of specific things that aren't supported and my tests of using dns_policy = "none" and dns_config / nameservers = ["known working dns ip address"] as set with gitlab-runner didn't work at all. `ipconfig /all` in the pod still showed the kubernetes dns server in use.
> 
> What _did_ work for me is changing the provisioner:
> 
> ```
> spec:
>   kubeletConfiguration: 
>     clusterDNS: ["known working dns ip address"]
> ```

Been struggling with myself in a similar scenario (also for CI) - GitHub ARC to be exact..  the pods on nodes brought up by eksctl when I provisioned the windows nodegroup can resolve dns fine, but pods on karpenter provisioned nodes can’t resolve DNS.  Will try this tomorrow!
