### ISSUE TITLE
Add the ability to define how frequent Karpenter should consolidate the cluster workload 

### ISSUE THREAD

**Issue by Omar-Bishtawi** [aws/karpenter#4422]
### Description

**What problem are you trying to solve?**
in some environments like dev/testing environments where HA isn't a concern due to cost-saving. it's usual to have some workloads with 1 pod. 

some of these workloads need some time on startup, and if Karpenter was consolidating the cluster too frequently (10s of times each hour) if there were a lot of scaling activities happening, this will cause downtime on these workloads each time the cluster is consolidated if the new node and the pod didn't start before the old pod is terminated.

giving the ability to determine how frequently the consolidation will work can help in minimizing the downtime for this kind of workload to be more tolerable in this kind of environment.

if there is other suggestions or ways to resolve this issue that will be great. 
note that PDB isn't an option to prevent these involuntary evictions since this will prevent the consolidation from taking effect since the node will be stuck in `DeprovisioningBlocked` state when trying to evict pods that have a PDB. 

**How important is this feature to you?**
the following picture shows the number of pods in a ready state. notice the difference in the number pods that reach 0 pods before and after switching to Karpenter. 

the reason for the # of pods in a ready state to reach 0 is mostly due to involuntary eviction that is happening when draining nodes due to consolidation.

![Screenshot 2023-08-13 at 1 30 37 PM](https://github.com/aws/karpenter/assets/91823055/f3e3f550-ccd7-4b68-9d60-9fa833cfc6b7)

the downtime is minimal and somewhat acceptable but it's better if we can reduce it. 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rafilkmp3** [comment]
I want a way to have consolidation only in a specific namespace https://github.com/aws/karpenter/issues/4437

**Comment by Imunhatep** [comment]
> I want a way to have consolidation only in a specific namespace #4437

Dedicated provisioner can be used for that.

**Comment by Imunhatep** [comment]
Configurable consolidation period could, in theory, be used as a workaround to the issue with flaking nodes #3921

**Comment by njtran** [comment]
Hey @Omar-Bishtawi, does https://github.com/aws/karpenter/issues/3059 fit your use-case? Karpenter will be checking to see if it can consolidate your nodes, and once it finds some way to save on cost, it'll wait 15 seconds before executing those commands. We're planning on including this 15 seconds as a tuneable knob. In your case, I could imagine you setting it to a higher value to like `1m` which will slow down the speed Karpenter consolidates your cluster.

**Comment by Imunhatep** [comment]
Correct me, but what if the setting is set to `60m`? i.e. instruct karpenter to exec nodes consolidation once per hour.
From the description, I see it as a parameter for delaying execution of already made decision? Will this decision be re-evaluated before execution?

**Comment by njtran** [comment]
Yes @Imunhatep, we'll always ensure that the decision is re-evaluated before execution. The longer the setting (like `60m` as you propose), the more necessary this is, as the cluster could be drastically different from the first simulation.

**Comment by njtran** [comment]
@Omar-Bishtawi, I'm going to close this in favor of https://github.com/aws/karpenter/issues/3059. Feel free to post your thoughts there or ask to re-open this if you disagree.
