### ISSUE TITLE
[AWS] Launch Templates are leaked on cluster deletion

### ISSUE THREAD

**Issue by mcavoyk** [aws/karpenter#444]
When uninstalling Karpenter or deleting the cluster, launch templates created by Karpenter are orphaned.

One idea brought up during working group meeting was that deleting the provisioner resource would delete all associated launch templates that were created for the provisioner resource.

**Comment by ellistarn** [comment]
Great idea! Scoping this to v0.3

**Comment by tanvp112** [comment]
Noticed when karpenter removes previously launched instances, these removed instances' ENI  & associated SG did not get destroy, too. This could exhaust the number of ENI available on the worker node.

**Comment by ellistarn** [comment]
Hey @tanvp112. Karpenter doesn't create security groups -- it only discovers and uses them (any sg with the tag key kubernetes.io/cluster/$NAME). ENIs should absolutely be deleted after the node is terminated. Typically the aws vpc cni is responsible for this. 

Which CNI/version are you using? Do you mind cutting details around this in another issue?

**Comment by tanvp112** [comment]
hi @ellistarn, for what I described above it was 1.7. Let me try another test this weekend and see if I can reproduce it.

**Comment by ellistarn** [comment]
We now have a LT cleanup feature. LTs will be removed after 1 minute.

**Comment by rajakshay** [comment]
> We now have a LT cleanup feature. LTs will be removed after 1 minute.

This behavior is undocumented, and it took me a while to figure this out. Saw it happen in Cloudtrail. If [this](https://github.com/aws/karpenter/blob/main/website/content/en/preview/AWS/launch-templates.md) is a good place for it, I can send an MR.

**Comment by njtran** [comment]
Hey @rajakshay, you're right. I can't find this in the documentation. I'll add it in. If Karpenter isn't running, you won't see these launch templates deleted until Karpenter starts running again.

In the meantime, if you're curious, we set the Cache TTL [here](https://github.com/aws/karpenter/blob/ff77ffd84f6e0f7bc62b77d5206cbfbbdcf50f93/pkg/cloudprovider/aws/cloudprovider.go#L53) and clear the cache if a Launch Template isn't used [here](https://github.com/aws/karpenter/blob/ff77ffd84f6e0f7bc62b77d5206cbfbbdcf50f93/pkg/cloudprovider/aws/launchtemplate.go#L69) and delete the corresponding template [here](https://github.com/aws/karpenter/blob/ff77ffd84f6e0f7bc62b77d5206cbfbbdcf50f93/pkg/cloudprovider/aws/launchtemplate.go#L244-L247).

**Comment by njtran** [comment]
https://github.com/aws/karpenter/pull/1686 Here's the documentation changes. Closing this out. Feel free to open another issue about documentation if you think we need more.
