### ISSUE TITLE
Specify max pods on provisioner resource

### ISSUE THREAD

**Issue by mcavoyk** [aws/karpenter#445]
The max pod node constraint uses the default setting for the Bottlerocket AMI. This value is not accurate when configuring aws-vpc [custom CNI](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html) where the max pods is reduced because one network interface is no longer available for pods.

As well when using other [CNI plugins](https://docs.aws.amazon.com/eks/latest/userguide/alternate-cni-plugins.html), the default max pods can be increased as max pods is no longer constrained by the available network interfaces.

Another interesting note about max pods per node is the 110 default that is often used when not limited by CNI is a bit arbitrary, and this value can be safely 250+ on larger instance types ([reference](https://github.com/kubernetes/kubernetes/issues/23349))

**Comment by ellistarn** [comment]
Thanks for this report. My initial feeling is that we should achieve this via custom launch templates. I want to provide docs for a launch template baseline (including our default userdata) that will make it easy for folks to extend with use cases like this.

**Comment by ellistarn** [comment]
Scoping this to v0.3

**Comment by ellistarn** [comment]
Hey @mcavoyk , have you seen the latest v1.9 CNI release which increases the pod density? https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.9.0

**Comment by bwagner5** [comment]
Should be part of this doc: https://github.com/awslabs/karpenter/issues/432

**Comment by geoffcline** [comment]
if you set a lower value to "max pods" (e.g., 50) in a custom launch template, will karpenter know about this? or will it provision a node that can handle 70, and yet only 50 schedule onto that node?

**Comment by olemarkus** [comment]
The behavior is somewhat broken now. It assumes CNI specific limitations and there is no way to get around this: https://github.com/aws/karpenter/issues/954

**Comment by olemarkus** [comment]
My proposal to solving this:
```
spec:
  podCapacityModel: "static|eni"
  staticPodCapacity: 110
```

The eni model needs an AMI that supports it, but that is what is assumed today.

In the future, a resource-based capacity model may be added, but again requires an AMI that supports it (or that karpenter can provide the data per Node rather than per LT)

If this sounds good, I can try to implement this.

**Comment by rothgar** [comment]
Would that spec be used in addition to instance type capacity? 110 pods on a .small instance is a lot different than 110 on a .24xlarge

**Comment by olemarkus** [comment]
What do you mean by instance capacity?

It would only be used to determine how kubelet's `MaxPods` is set. It would not affect anything wrt cpu and memory resource constraints.

**Comment by mikesir87** [comment]
See https://github.com/aws/karpenter/issues/954#issuecomment-998899853. Now that we have `spec.kubeletConfiguration`, we could allow someone to specify a value directly. Would this work?

**Comment by ellistarn** [comment]
I'd like to hold off and think a little more deeply before we make changes. Max pods is not a concept that melds naturally with heterogenous instance types. I want to be very careful about how we decide to approach this. Most of the team is currently on vacation, so this may need to wait for the new year.

**Comment by olemarkus** [comment]
I would be fine with agreeing on a large value for MaxPods so that it doesn't become a part of the equation.

**Comment by mikesir87** [comment]
Makes sense to wait until the team comes back. For my use case, I simply don't want to set it at all or use a crazy high number. 

As we find more AWS VPC CNI-specific things, it almost makes me think if there's a high-level config that needs to indicate this, as defaults should vary quite a bit.

Anywho... everyone have a great break and we'll pick it up after the holiday!

**Comment by akestner** [comment]
Would it be possible to consolidate this and #954 since they both deal with the same problem / request?

**Comment by ellistarn** [comment]
Coming in v0.5.6
