### ISSUE TITLE
Karpenter does not remove old versions of MutatingWebhookConfiguration and ValidatingWebhookConfiguration in cluster after upgrading to a new chart version, might causing webhook problems like using port 443 instead of 8443 or certificate error.

### ISSUE THREAD

**Issue by linkthai** [aws/karpenter#4454]
### Description

**Observed Behavior**:
If you have installed multiple version of the Karpenter helm chart, you will not be able to deploy Provisioner or AWSNodeTemplate and might encounter the following error
`defaulting.webhook.karpenter.sh": failed to call webhook: Post "https://karpenter.karpenter.svc:443/default/karpenter.sh?timeout=10s"`

You can see the old webhook versions got stuck from 2 days ago in my cluster along with the newer ones.
<img width="1025" alt="SCR-20230818-ckuo" src="https://github.com/aws/karpenter/assets/16166811/6a9405c1-77d2-48ec-99d9-6ada6e0a2390">
<img width="1024" alt="SCR-20230818-ckwy" src="https://github.com/aws/karpenter/assets/16166811/dc1832dd-2d70-4184-ad50-ef04869962cd">

**Expected Behavior**:
You can deploy the Provisioner and AWSNodeTemplate, they are using the right port (8443). Installing different versions of Karpenter helm chart will clear all the webhooks from previous versions so it doesn't get conflicted.

**Reproduction Steps** (Please include YAML):
If you have installed multiple versions of the Karpenter helm chart, especially any of the two version one of which uses port 443 and the other uses port 8443 for the webhook, you will encounter this problem.

The following is my umbrella helm chart that list the karpenter as a dependency. Before this chart was implemented, I used Kustomization to install the helm chart but Kustomize does not support OCI helm chart. So I did install a very old helm chart by [bwagner5](https://artifacthub.io/packages/helm/karpenter/karpenter) which still use port 443, but then just ditch it and find another way to install the OCI helm chart.
```
apiVersion: v2
name: karpenter
description: Karpenter helm chart
type: application
version: 0.1.5
appVersion: "1.5"
dependencies:
  - name: karpenter
    version: v0.29.2
    repository: oci://public.ecr.aws/karpenter
```

**Versions**:
- Chart Version: 0.29.2
- Kubernetes Version (`kubectl version`): 1.27

**Reference Issue**:
#4368 This is the main issue as it was directly my problem, OP did found the solution but I did not understand how he solved it, the solution and what I'm seeing just did not match. It turns out I'm using **ArgoCD** so the webhooks I'm seeing on ArgoCD might not be the ones he was talking about, ArgoCD did not show _ALL_  of the webhooks for me, only the ones on the current version installed by ArgoCD. OP changed the old webhooks port number but I'm not recommending fixing it that way.

#2876 This was the issue that gave the solution. OP also found the solution, it was just deleting the two old versions of the webhooks, but the problem is the error in this issue was not the same as the previous one. But I figure it originates from the same problem. After I use OpenLens instead of looking at ArgoCD, it was clear that there were some webhooks that was in the cluster for some day even though I redeploy the application with the helm chart just recently.

**How to fix**
Use a GUI like OpenLens or just kubectl commands to delete all the older karpenter webhooks manually and redeploy your resources. In the current version, there are only 1 Mutating hooks and 3 Validating hooks. You need to delete the old webhooks instead of changing the port number of the old webhooks, so the karpenter will use the newer webhooks and not cause issue later on. The best solution is just remove the chart, remove all the webhooks, then install the correct chart again.

Everything runs okay now after the fix.
<img width="853" alt="SCR-20230818-cqpw" src="https://github.com/aws/karpenter/assets/16166811/653ca6c4-b451-4b19-bf6b-1a419c33cc32">

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
This is a known issue with Argo leaking the old webhooks. Unfortunately, your mitigation of deleting them manually is the only way I'm aware of moving forward. I'm not an argo expert, so there may be something I'm missing.

**Comment by linkthai** [comment]
@bwagner5 I'm not sure if that is a Argo only problem, as the #4368 issue probably have some people who didn't use ArgoCD. Can't this issue be fixed with something like a pre install/pre upgrade hook that runs a job to remove old webhooks? (I don't know enough about helm chart to know if it's actually possible)

**Comment by bwagner5** [comment]
The webhooks should be removed if using the helm cli. I believe this is only an ArgoCD leak.

**Comment by sftim** [comment]
I don't think Karpenter should have delete-webhook permissions.

**Comment by bwagner5** [comment]
This is noted in the upgrade guide as well to make sure the webhook is removed, https://karpenter.sh/docs/upgrade-guide/#upgrading-to-v0273

Will close for now. If you feel this is a bigger problem, feel free to reopen.
