### ISSUE TITLE
Add configurable global limit on number of nodes/machines.

### ISSUE THREAD

**Issue by myaser** [aws/karpenter#4462]
### Description

**What problem are you trying to solve?**
due to the limited IP range, our clusters can only scale up to a certain number of nodes. 
on Cluster Autoscaler we used [the flag ](https://github.com/kubernetes/autoscaler/blob/538994707fbfe7207155832c3b3cc8efb286ebfa/cluster-autoscaler/FAQ.md?plain=1#L746)`--max-nodes-total` to enforce the limit

Similar configuration for karpenter will be handy

This will also help mitigate the risk [here](https://karpenter.sh/docs/concepts/threat-model/#threat-cluster-developer-can-influence-creation-of-an-arbitrary-number-of-nodes)

The suggested mitigations (resource limit on CPU and memory) are not ideal because:
1. it is per provisioner, not cluster-wide
2. it is on the number of CPU and memory, while the limitation we are facing is on the number of nodes

**How important is this feature to you?**
it is not a blocker for us right now, but we hope to resolve this risk before Cyber Week

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Closing in favor of https://github.com/aws/karpenter/issues/2474. Feel free to re-open if you disagree.

**Comment by myaser** [comment]
Thank you, @njtran, for the quick response. However, I feel this is slightly different. 
the limitation we have is on the node count (limited IP range available for the nodes) so it does not matter what global CPU and memory limit we define.

assuming the limit is 10 nodes
we can not enforce this using resource limits like CPU unless we are very strict about the instance-types. 
in fact we would like not to limit the overall capacity of the cluster in terms of CPU and memory allowing karpenter to replace smaller nodes with larger ones creating more CPU and memory without breaking the node limit

**Comment by myaser** [comment]
@njtran I do not have the right permissions to re-open the issue

**Comment by njtran** [comment]
Hey @myaser, commented on the other issue. I think we can aim to track it there, let me know if you disagree.
