### ISSUE TITLE
SQS long polling

### ISSUE THREAD

**Issue by miguellongo** [aws/karpenter#4466]
Hi folks!

Karpenter use SQS in termination handling in ec2 spot.

Can I have problem if I enable long polling configuration in SQS? Are there any considerations when using long polling?

Thanks in advance.

**How can the docs be improved?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Karpenter uses long-polling to consume messages from a queue. This is the recommended setup.
