### ISSUE TITLE
Run `aws cloudformation describe-stack-events` on a Create Cluster failure in E2E

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter#4467]
### Description

**What problem are you trying to solve?**

Currently, if we experience a failure in the [create-cluster](https://github.com/aws/karpenter/blob/main/.github/actions/e2e/create-cluster/action.yaml#L61) step in the E2E testing suite flow, we don't get any detail on why the CloudFormation stack failed to deploy. We should automatically run `aws cloudformation describe-stack-events <stack-id>` after a failure to ensure that we get all the information directly in the logs.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aman0408** [comment]
Can I work on this as well @jonathan-innis ?

**Comment by jonathan-innis** [comment]
Yep! Assigned!
