### ISSUE TITLE
Add Pricing Endpoint for eu-central-1

### ISSUE THREAD

**Issue by bwagner5** [aws/karpenter#4475]
### Description

**What problem are you trying to solve?**

There is currently a pricing endpoint in us-east-1 and ap-south-1. Recently, a pricing endpoint was released in eu-central-1. Karpenter should be updated to use the new pricing endpoint if in an eu-* region. 

https://github.com/aws/karpenter/blob/main/pkg/providers/pricing/pricing.go#L89

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by riteshsonawane1372** [comment]
assign me.
