### ISSUE TITLE
Support `EBSOptimized` option in the LaunchTemplate

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter#4522]
Are there any workarounds to support？

**Comment by jonathan-innis** [comment]
We don't currently support this parameter, but we'd be open to PRs that add support for the parameter into the API!

**Comment by jonathan-innis** [comment]
This field has no effect on most instance types so it seems like there's probably not much value in us supporting this field. From https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html#current,
> The following tables list the instance types that support EBS optimization and EBS optimization is enabled by default. There is no need to enable EBS optimization and no effect if you disable EBS optimization.
