### ISSUE TITLE
support record pod   event when it caused by node consolidation

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter#4532]
With the consolidation  feature turned on, if a pod is evicted, will events be logged?  It looks like the documentation only logs events at the node level.

**Comment by jonathan-innis** [comment]
> if a pod is evicted, will events be logged

I'm a little confused. What kind of events are you looking for? You're looking for some events at the pod-level that the pod went through the eviction process? Is it possible to use the Kubernetes audit logs to deduce this?

**Comment by txjjjjj** [comment]
> > if a pod is evicted, will events be logged
> 
> 
> 
> I'm a little confused. What kind of events are you looking for? You're looking for some events at the pod-level that the pod went through the eviction process? Is it possible to use the Kubernetes audit logs to deduce this?

At least be able to show that the pod recreates because of the karpenter merge node. Because sometimes it's important when troubleshooting a pod issue to at least let me know that it's caused by karpenter.

**Comment by jonathan-innis** [comment]
> Because sometimes it's important when troubleshooting a pod issue to at least let me know that it's caused by karpenter

There is a `Evicted` event that is published when the pod is evicted by Karpenter. See here: https://github.com/aws/karpenter-core/blob/main/pkg/controllers/termination/terminator/eviction.go#L131
