### ISSUE TITLE
panic when upgrade to v0.30.0

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter#4534]
## Description
When upgrading to v0.30.0, the karpenter pod keeps rebooting.
## error log

[karpenter-79f678475f-gq4kn.log.txt](https://github.com/aws/karpenter/files/12496572/karpenter-79f678475f-gq4kn.log.txt)

## upgrade step
from version v0.29.2(The dependent iam roles and permissions remain unchanged)  upgrade to v0.30.0

```
helm template karpenter-crd \
oci://public.ecr.aws/karpenter/karpenter-crd \
--version v0.30.0 \
--namespace karpenter --create-namespace > karpenter/dev/karpenter-crd.yaml
```

```
helm template karpenter \
oci://public.ecr.aws/karpenter/karpenter \
--namespace karpenter --create-namespace \
--version v0.30.0 \
-f karpenter/dev/values.yaml > karpenter/dev/manifest.yaml
```

```
kubectl apply -f karpenter/dev/karpenter-crd.yaml
kubectl apply -f karpenter/dev/manifest.yaml
```
Did I do something wrong with the upgrade steps? when v0.29.2, it works fine.

**Comment by jonathan-innis** [comment]
Can you check the roles that you have on your cluster? The newest version should have shipped with a role called `karpenter-lease`. The lack of that role's permission seems to be what's causing the problem here.

**Comment by txjjjjj** [comment]
> Can you check the roles and rolebindings that you have on your cluster? The newest version should have shipped with a role called `karpenter-lease`. The lack of that role's permission seems to be what's causing the problem here.

use replace -f to the mainefest is works，thanks
