### ISSUE TITLE
Namespace kube-node-lease is now required?  

### ISSUE THREAD

**Issue by yuval-almog** [aws/karpenter#4547]
### Description

**Observed Behavior**:
When changing to version 0.30.0 i get the following errors: 

 failed to list *v1.Lease: leases.coordination.k8s.io is forbidden: User \"system:serviceaccount:<namespace>:karpenter\" cannot list resource \"leases\" in API group \"coordination.k8s.io\" in the namespace \"kube-node-lease\"\n","commit":"637a642"}

I also see this namespace is hardcoded in the chart 

https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/role.yaml#L71C2-L71C2
When I tired to upgrade the chart I get errors because this namespace does not exists in my cluster. When I try to upgrade just the image without the chart I get the errors above so it seems that this namespace is required

Does Karpenter now requires us to create this namespace ? and if so why is it not in the chart ? 

**Expected Behavior**:
Karpenter should be able to run without a specific namespace name to exists

**Reproduction Steps** (Please include YAML):
Upgrade Karpenter to version 0.30.0 in a cluster where namespace named 'kube-node-lease' does not exists 

**Versions**:
- Chart Version: 0.30.0
- Kubernetes Version 1.26 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mhmtsvr** [comment]
I do get the same error after upgrading to v0.30.0 even if I have the namespace in the cluster. 🤔 @yuval-almog

**Comment by fatoh2** [comment]
@yuval-almog Did you find the solution for this? II can see you already closed the issue.

**Comment by jonathan-innis** [comment]
> I do get the same error after upgrading to v0.30.0 even if I have the namespace in the cluster

Is it the same error? Do you see specific errors related to the namespace not existing in Karpenter or does it have to do with the permissions of the service account that Karpenter is carrying?

**Comment by logyball** [comment]
I have also gotten this issue upon upgrading to `v0.30.0` when the Role and RoleBinding for `karpenter-lease` are either _not_ present (due to a flux error) or when moving the Role and RoleBinding for `karpenter-lease` to the `karpenter` namespace.  

I'll update this comment if I find different, but I believe that having both the Namespace `kube-node-lease` as well the `karpenter-lease` Role/RoleBinding in that particular namespace is required by `v0.30.0`.
