### ISSUE TITLE
Add tags to spot requests created by Karpenter

### ISSUE THREAD

**Issue by ybthai98** [aws/karpenter#4550]
### Description

**What problem are you trying to solve?**

Currently, when customers create spot requests using Karpenter, the spot requests do not have any tags specified, while other resources like instances have the correct tags applied. 

This issue was discussed offline with @jonathan-innis, and it appears that adding tags to spot requests created by Karpenter is not supported due to limitations with EC2 APIs. These limitations prevent the tag specifications from being passed down to the RunInstances API.

Documentation Reference:

https://karpenter.sh/preview/concepts/settings/#awstags
https://karpenter.sh/docs/concepts/node-templates/#spectags

**How important is this feature to you?**

This issue has been raised on behalf of a customer, highlighting the importance of this feature. Tags are essential for resource management and tracking within AWS, and having this functionality in Karpenter would greatly enhance the user experience.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Thanks for raising this! I've let the EC2 Fleet team know about this.

**Comment by bwagner5** [comment]
Unfortunately, RunInstances doesn't support tagging Spot Instance Requests either :(  You would need to tag the SIRs yourself if those tags are important. Curious what use-case you are solving for tagging the SIRs rather than just the instances?

**Comment by bwagner5** [comment]
An admittedly unsatisfying workaround is to tag SIRs in user-data.

**Comment by jonathan-innis** [comment]
Turns out...everything seems to be working now! I opened a PR to add this to the launch template tag specifications. This should be merged after we finish up the beta release and v0.32.0
