### ISSUE TITLE
Why is the package rate so high, but no new machines are started. 

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter#4555]
### Description

version: 0.30.0

Why is the package rate so high, but no new machines are started.  Is it possible to control this value, e.g. if it is higher than 80% a new machine is started.
<img width="1374" alt="image" src="https://github.com/aws/karpenter/assets/60080355/dd43ff96-6734-4308-b491-4ec8963cf28a">
(use this tool to observe node package rate: https://github.com/awslabs/eks-node-viewer)

**Comment by jonathan-innis** [comment]
> Why is the package rate so high

You can't tune this value right now since we are assuming that you have set your application requests correctly which means that we are maximizing the utilization of your nodes, driving down the cost of the cluster. What's the reason you want overhead on your nodes and don't want them fully utilized?

**Comment by kayahk** [comment]
I think there might be cases when you need to deploy something on top of everything that is already running and daemon-sets won't trigger new nodes or any kind of rescheduling. So they sit their infinitively and won't get scheduled which makes it sometimes really hard to use temporary troubleshooting or security tools, like Trivy, Kubeshark, etc.
A setting that would allow to control the max. utilisation of any node would be great to leave some room for emergency use cases.

**Comment by bwagner5** [comment]
If you schedule a DaemonSet with a higher priority class, it should result in pods with less priority to be evicted from the node to make room.  I can understand if you don't want to accept that impact to the workload though.

You can self-tune things a bit by adjusting the instance type sizes that you want and disable consolidation, but you also lose a lot of the efficiency gains that Karpenter offers when doing that.
