### ISSUE TITLE
Document the operators available for provisioner .spec.requirements 

### ISSUE THREAD

**Issue by ecerulm** [aws/karpenter#4558]
### Description

**How can the docs be improved?**

It's not clear from https://karpenter.sh/preview/concepts/provisioners/ what operators are available for use, 

The page has mention of `In`, `NotIn` and `Gt` but it does not mention `Lt` , or any other operator. 

From example is unclear to me if there is a `GtOrEqual`  operator or something like that. 

I search in website/content/en/v0.30 and there is no mention of `Lt` 

The `pkg/apis/crds/karpenter.sh_provisioners.yaml` explictly mentions that the valid operators are In, NotIn, Exists, DoesNotExist, Gt and Lt

https://github.com/aws/karpenter/blob/cce5dbc8ca580f17772e7f532d258011f102d966/pkg/apis/crds/karpenter.sh_provisioners.yaml#L213-L214

But I think that should be made explicit in the documentation at least with a link to the `pkg/apis/crds/karpenter.sh_provisioners.yaml`  saying that the list of valid operator is there , or something like that. 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
We support all the upstream K8s operators mentioned here: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#operators 

We can add a link to the upstream docs
