### ISSUE TITLE
PVCs and lost AZs

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/karpenter#4561]
### Description

not a bug, but more of a question

if there is not node in a specific AZ where a workload has an existing PVC, will karpenter take into consideration that request when spinning up a new node?

What happens if that AZ is lost? will karpenter spin up a node in a diff AZ and try to deploy the workload and a **new** PVC?

thanks in advance.

**Comment by bwagner5** [comment]
Karpenter is PVC aware, so it will take into account where the PVC is when provisioning a node. What do you mean by "AZ is lost"? Do you mean that the AZ is down for some reason?  If the PVC still exists in the kube-apiserver, then karpenter would continue adding the volume requirements. Karpenter won't delete and recreate the PVC.
