### ISSUE TITLE
Manual deletion of nodes has been completed but new nodes have not been registered yet.

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter#4562]
hope that When manually deleting a node wait for the new node to be running and then delete it.

kubectl delete node $NODE_NAME

But I observed that the old node has been deleted and the new node hasn't been registered yet. This caused a relatively long outage of the application.

I used the custom ami custom node template

Is there anything you can optimize?

**Comment by bwagner5** [comment]
We don't currently pre-spin when manually deleting nodes. I've tagged this as a feature request. Is there a specific use-case you can elaborate on or is this just manual operator action that happens occassionally?

**Comment by txjjjjj** [comment]
@bwagner5 Usage scenario, after updating the provisioner, I want to update all the corresponding node group nodes.

**Comment by bwagner5** [comment]
Let us know if you have more questions. Feel free to join us in the Kubernetes slack in the karpenter channel too!
