### ISSUE TITLE
I started 3 karpenter pods, how do I know which pod is the leader?

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter#4567]
### Description

version: v0.30.0
eks environment: I've used cilium's cni, not aws-cni.

Question 1: How do I know which node is the running LEADER?

Question 2: I'm using cilium's cni with hostNetwork: true turned on.  Does the leader's election depend on these ports?
Do I need to open any ports on my node's sg?  
```
  ports:
    - name: http-metrics
      port: 8000
      targetPort: http-metrics
      protocol: TCP
    - name: https-webhook
      port: 8443
      targetPort: https-webhook
      protocol: TCP
```

Question 3: I'm looking at the controller's logs. There are some tls errors. What is causing this?
```
kubectl logs -f -n karpenter -l app.kubernetes.io/name=karpenter -c controller

2023-09-05T09:07:24.995Z        ERROR   webhook http: TLS handshake error from 10.x.x.x:36266: EOF
        {"commit": "637a642"}
2023-09-05T09:55:46.997Z        ERROR   webhook http: TLS handshake error from 10.x.x.x:42448: EOF
        {"commit": "637a642"}
2023-09-05T09:55:47.008Z        ERROR   webhook http: TLS handshake error from 10.x.x.x:42454: EOF
        {"commit": "637a642"}
2023-09-05T16:49:59.075Z        ERROR   webhook http: TLS handshake error from 10.x.x.x:44538: EOF
        {"commit": "637a642"}
        {"commit": "637a642"}

```

**Comment by bwagner5** [comment]
> Question 1: How do I know which node is the running LEADER?

You can see who holds the lease: `kubectl get leases -n karpenter`

> Question 2: I'm using cilium's cni with hostNetwork: true turned on. Does the leader's election depend on these ports?
Do I need to open any ports on my node's sg?

The Karpenter pod just needs to be able to contact the kube-apiserver

> Question 3: I'm looking at the controller's logs. There are some tls errors. What is causing this?

I'm not sure about the TLS errors you're seeing, but it's likely related to this issue which is probably a better place to track this. https://github.com/aws/karpenter/issues/3598 


btw, if you join the kubernetes slack Karpenter has a channel there #karpenter that you can ask these types of questions in and potentially get faster answers. 

Join K8s slack: https://communityinviter.com/apps/kubernetes/community
Karpenter channel: https://kubernetes.slack.com/archives/C02SFFZSA2K
