### ISSUE TITLE
incorrect detection of mime-encoded userdata

### ISSUE THREAD

**Issue by doy-materialize** [aws/karpenter#4581]
### Description

**Observed Behavior**:
in #3427, karpenter gained the ability to treat the provided userdata as a plain shell script, but to determine this, it is only inspecting the first header to determine whether the userdata is a script or a mime-encoded section. the mime library i am using emits the Content-Type header before the Mime-Version header though, which means that it is incorrectly getting detected as a shell script.

**Expected Behavior**:
my userdata should be detected as a mime-encoded section.

**Reproduction Steps** (Please include YAML):

```
[...]
    userData: |
        Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
        MIME-Version: 1.0

        --MIMEBOUNDARY
        Content-Transfer-Encoding: 7bit
        Content-Type: text/x-shellscript
        Mime-Version: 1.0

        #!/bin/bash

        # [...]

        --MIMEBOUNDARY--
```

**Versions**:
- Chart Version: 0.30.0
- Kubernetes Version (`kubectl version`): 1.25.12

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
👍 PR is up to fix this! Thanks for the reporting!

**Comment by bwagner5** [comment]
merged, will be in the next release!
