### ISSUE TITLE
Clarification on tag validation failure in v0.30.0

### ISSUE THREAD

**Issue by govardha** [aws/karpenter#4582]
Hello,

I am new to k8s and even more new to karpenter, so please bear with me here.  When I first started exploring karpenter a week or 2 ago the documentation was on v0.27.0.  After going through some grinding I finally got karpenter working on v0.27.0.  This morning I saw that the version on the site was upgraded to v0.30.0.  When I was on v0.27.0 I never saw this error but in v0.30.0 I am noticing this.

I have named my cluster _foo-bar-qa_, this worked fine in v0.27.* but not in v0.30.0.  Can somebody clarify what am I doing wrong?  Should I start from scratch with a new cluster named _foobarqa_

Thank you!

```
{
  "commit": "637a642",
  "controller": "awsnodetemplate",
  "controllerGroup": "karpenter.k8s.aws",
  "controllerKind": "AWSNodeTemplate",
  "AWSNodeTemplate": {
    "name": "default"
  },
  "namespace": "",
  "name": "default",
  "reconcileID": "8b74db29-39c4-4167-a4fd-1dab7b5278bc",
  "error": "admission webhook \"validation.webhook.karpenter.k8s.aws\" denied the request: validation failed: invalid key name \"kubernetes.io/cluster/foo-bar-qa\": spe
c.tags\ntag contains a restricted tag matching \"^kubernetes\\\\.io/cluster/[0-9A-Za-z][A-Za-z0-9\\\\-_]*$\"; admission webhook \"validation.webhook.karpenter.k8s.aws\"
denied the request: validation failed: invalid key name \"kubernetes.io/cluster/foo-bar-qa\": spec.tags\ntag contains a restricted tag matching \"^kubernetes\\\\.io/clu
ster/[0-9A-Za-z][A-Za-z0-9\\\\-_]*$\"",
  "errorCauses": [
    {
      "error": "admission webhook \"validation.webhook.karpenter.k8s.aws\" denied the request: validation failed: in valid key name \"kubernetes.io/cluster/foo-bar-qa\"
: spec.tags\ntag contains a restricted tag matching \"^kubernetes\\\\.io/cluster/[0-9A-Za-z][A-Za-z0-9\\\\-_]*$\""
    },
    {
      "error": "admission webhook \"validation.webhook.karpenter.k8s.aws\" denied the request: validation failed: invalid key name \"kubernetes.io/cluster/foo-bar-qa\":
 spec.tags\ntag contains a restricted tag matching \"^kubernetes\\\\.io/cluster/[0-9A-Za-z][A-Za-z0-9\\\\-_]*$\""
    }
  ]
}
```

**Comment by bwagner5** [comment]
This restriction was added in v0.28.0 of Karpenter here: https://github.com/aws/karpenter/commit/49a318ecfbc59e79d69115ac8dc1c9429616b671

You don't need to specify the `kubernetes.io/cluster` tag in the AWSNodeTemplate, it will be automatically added to the instance when karpenter launches it. It should be safe to remove that tag and keep your cluster name :)

**Comment by govardha** [comment]
> This restriction was added in v0.28.0 of Karpenter here: [49a318e](https://github.com/aws/karpenter/commit/49a318ecfbc59e79d69115ac8dc1c9429616b671)
> 
> You don't need to specify the `kubernetes.io/cluster` tag in the AWSNodeTemplate, it will be automatically added to the instance when karpenter launches it. It should be safe to remove that tag and keep your cluster name :)

Ah thank you very much for that @bwagner5   I was having a tough time trying to get 0.27.* working and after a call with AWS support, we converged on the template not having that tag which I added and things started working.  Glad to know that it is now sorted out in v0.30.0.  

Looking forward to using karpenter for my workloads now.

Thanks again!
