### ISSUE TITLE
Fix documentation - Karpenter no longer annotate nodes with karpenter.sh/voluntary-disruption: "drifted"

### ISSUE THREAD

**Issue by saha-rajdeep** [aws/karpenter#4609]
In the version 0.30 documentation the below is present, which is not true anymore since Karpenter doesn't annotate nodes with karpenter.sh/voluntary-disruption: "drifted".

"Karpenter will annotate the nodes with the karpenter.sh/voluntary-disruption: "drifted" if the node is drifted, and does not have the annotation,

Karpenter will remove the karpenter.sh/voluntary-disruption: "drifted" annotation for the following these scenarios:
The featureGates.driftEnabled is not enabled but the node is drifted, karpenter will remove the annotation so another disruption controller can annotate the node.
The node isn’t drifted, but has the annotation, karpenter will remove it.

If the node is marked as voluntarily disrupted by another controller, karpenter will do nothing"

**Comment by engedaam** [comment]
Thank you for the issue! PR linked for the fix

**Comment by saha-rajdeep** [comment]
That was fast! Thanks guys, cheers
