### ISSUE TITLE
Karpenter consolidation stuck into recreation of nodes

### ISSUE THREAD

**Issue by sekar-saravanan** [aws/karpenter#4615]
### Description

**Observed Behavior**:
Karpenter stuck into the loop state where it was deprovisioning a node via consolidation delete and creating new machine due to the pending pods again and again

**Expected Behavior**:
It should deprovision the node only if all the pods is the same node can able to schedule into other nodes in the cluster

**Reproduction Steps** (Please include YAML):

**Versions**: 0.28.0
- Chart Version:  0.28.0 
- Kubernetes Version (`kubectl version`): v1.24.16-eks-2d98532

Attached Karpenter logs, provsioner config and configmap yaml.
Timestamp in the log: [Sep 12, 2023 07:20 AM - 10:00 AM]

[karpenter-global-settings-yaml.log](https://github.com/aws/karpenter/files/12586779/karpenter-global-settings-yaml.log)
[karpenter.log](https://github.com/aws/karpenter/files/12586780/karpenter.log)
[provisioner-yaml.log](https://github.com/aws/karpenter/files/12586782/provisioner-yaml.log)

**Comment by ellistarn** [comment]
Closing in favor of the internal AWS support ticket for this issue.
