### ISSUE TITLE
Sounds good, going to close this issue if there is nothing else.

### ISSUE THREAD

**Issue by HarshithaEshappa** [aws/karpenter#4620]
Hello,
curl -fsSL [https://karpenter.sh/"${KARPENTER_VERSION}"/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml>](https://karpenter.sh/%22$%7BKARPENTER_VERSION%7D%22/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml%3E) $TEMPOUT \

&& aws cloudformation deploy
--stack-name "Karpenter-${CLUSTER_NAME}"
--template-file "${TEMPOUT}"
--capabilities CAPABILITY_NAMED_IAM
--parameter-overrides "ClusterName=${CLUSTER_NAME}"
curl: (22) The requested URL returned error: 404 Not Found

getting the same error and if i use the below command also cloudformation is returning this statement

Waiting for changeset to be created..
Waiting for stack create/update to complete

Failed to create/update the stack.

curl -fsSL [https://raw.githubusercontent.com/aws/karpenter/"${KARPENTER_VERSION}"/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml](https://raw.githubusercontent.com/aws/karpenter/%22$%7BKARPENTER_VERSION%7D%22/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml) > $TEMPOUT
&& aws cloudformation deploy
--stack-name "Karpenter-${CLUSTER_NAME}"
--template-file "${TEMPOUT}"
--capabilities CAPABILITY_NAMED_IAM
--parameter-overrides "ClusterName=${CLUSTER_NAME}"

We are trying to configure the karpenter for our avaialble cluster.

Please help us to resolve this error
Thanks

**Comment by ellistarn** [comment]
This is out of scope for issues we help with in the OSS community. Please reach out to AWS support for help.
