### ISSUE TITLE
What is the difference between Karpenter and EKS auto scaling?

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [aws/karpenter#4621]
### Description

**How can the docs be improved?**
I was wondering what is the difference between Karpenter and OOTB EKS node scaling? The only difference I see is that Karpenter supports multiple cloud providers but is there anything else? Maybe Karpenter is smarter about node scaling and is more cost-efficient?

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
What's EKS OOTB Node Scaling?

**Comment by gytis-ivaskevicius** [comment]
here is an [example](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/patterns/stateful/main.tf#L78-L80), in EKS module all you need to do is define node groups  and k8s will autoscale these nodes as necessary

**Comment by FernandoMiguel** [comment]
> here is an [example](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/patterns/stateful/main.tf#L78-L80), in EKS module all you need to do is define node groups and k8s will autoscale these nodes as necessary

that's what is called Managed Node Groups.
it's a special version of AWS ASG (auto scaling group)

those provide static compute capacity, while karpenter is far more dynamic, cost effective, and aims at binpacking workloads

**Comment by gytis-ivaskevicius** [comment]
I just realized that I have https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler installed. Thats what doing autoscaling for me

I guess the question should have been whats the difference between Karpenter and https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler

**Comment by ellistarn** [comment]
I'd recommend Googling for talks or blogs on this topic. CAS uses AWS native APIs like Autoscaling Groups to manage instances. Karpenter combines responsibilities of both ASG and CAS, and does both scaling and lifecycle management.
