### ISSUE TITLE
Karpenter fails to provision some nodes due to swap partition and getting stuck

### ISSUE THREAD

**Issue by alekc** [aws/karpenter#4629]
### Description

**Observed Behavior**:
Karpenter stuck on provisioning

**Reproduction Steps** (Please include YAML):

Given the following config:
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    karpenter.sh/provisioner-hash: "15591017375434095235"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.sh/v1alpha5","kind":"Provisioner","metadata":{"annotations":{},"name":"default"},"spec":{"consolidation":{"enabled":true},"kubeletConfiguration":{"containerRuntime":"containerd","maxPods":110},"limits":{"resources":{"cpu":500}},"providerRef":{"name":"default"},"requirements":[{"key":"karpenter.sh/capacity-type","operator":"In","values":["spot"]},{"key":"karpenter.k8s.aws/instance-category","operator":"In","values":["c","m","t"]},{"key":"karpenter.k8s.aws/instance-size","operator":"In","values":["small","medium"]},{"key":"kubernetes.io/arch","operator":"In","values":["arm64","amd64"]}],"ttlSecondsUntilExpired":604800}}
  creationTimestamp: "2023-09-13T13:43:40Z"
  generation: 1
  name: default
  resourceVersion: "304744"
  uid: aabfb199-16e2-4093-a740-9cdd2686c7f2
spec:
  consolidation:
    enabled: true
  kubeletConfiguration:
    containerRuntime: containerd
    maxPods: 110
  limits:
    resources:
      cpu: "500"
  providerRef:
    name: default
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
    - m
    - t
  - key: karpenter.k8s.aws/instance-size
    operator: In
    values:
    - small
    - medium
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
    - amd64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  ttlSecondsUntilExpired: 604800
status:
  resources:
    cpu: "4"
    ephemeral-storage: 62902252Ki
    memory: 5265744Ki
    pods: "330"

```
```yaml
#➜ kubectl get awsnodetemplate default -o yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  annotations:
    karpenter.k8s.aws/nodetemplate-hash: "7233672322700999508"
  creationTimestamp: "2023-09-13T13:43:40Z"
  generation: 1
  name: default
  resourceVersion: "308102"
  uid: 04da1248-79a6-4ba9-b1e7-a7ee8813e85b
spec:
  instanceProfile: karpenter-dev-tooling-eks
  securityGroupSelector:
    karpenter.sh/discovery: dev-tooling-eks
  subnetSelector:
    karpenter.sh/discovery: dev-tooling-eks
  tags:
    Name: dev-tooling-eks-karpenter-node   
    Project: dev-tooling-eks
    Terraform: "Yes"
    karpenter.sh/discovery: dev-tooling-eks
status:
  amis:
  - id: ami-013895b64fa9cbcba
    name: amazon-eks-node-1.27-v20230825
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
  - id: ami-0fe7215c073c7bb34
    name: amazon-eks-gpu-node-1.27-v20230825
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: Exists
  - id: ami-0fe7215c073c7bb34
    name: amazon-eks-gpu-node-1.27-v20230825
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: Exists
  - id: ami-0266a75a5e281d943
    name: amazon-eks-arm64-node-1.27-v20230825
    requirements:
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
    - key: kubernetes.io/arch
      operator: In
      values:
      - arm64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
  securityGroups:
  - id: sg-068bb2a93d25bf751
    name: eks-cluster-sg-dev-tooling-eks-1960709586
  subnets:
  - id: subnet-0189c195194d93fb9
    zone: us-east-1b
  - id: subnet-05b6b7b4eaa4d1dc3
    zone: us-east-1a
```

Karpenter tries to launch 3 
<img width="1447" alt="Screenshot 2023-09-14 at 11 09 39" src="https://github.com/aws/karpenter/assets/302807/d258b8cf-d19c-456a-b1a2-b78bf704b990">
nodes (to satisfy affinity requests for haproxy) 

Only one node with t3.small architecture comes up, 2 others (`m1.small`) won't. Karpenter will try to delete and recreate them by joining ttl but since it's trying to reuse the same machines, they won't join the cluster. 

I realize that this is probably fixable by setting higher generation (has not tried yet), but my question is: given the persistence of the behaviour, should not karpenter switch to another instance type if the chosen once constantly fails? 

Full log
[controller.log](https://github.com/aws/karpenter/files/12607813/controller.log)

**Versions**:

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-2d98532", GitCommit:"3d90c097c72493c2f1a9dd641e4a22d24d15be68", GitTreeState:"clean", BuildDate:"2023-07-28T16:51:44Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Unclear to me why the small was unable to join
```
2023-09-14T10:40:59.070Z	DEBUG	controller.machine.lifecycle	terminating due to registration ttl	{"commit": "637a642", "machine": "default-bc9lg", "provisioner": "default", "ttl": "15m0s"}
```
Any chance you can dig into the kubelet logs? https://karpenter.sh/docs/troubleshooting/#node-notready. Hard to guess

> given the persistence of the behaviour, should not karpenter switch to another instance type if the chosen once constantly fails?

We try to avoid being "smart" like this, since we really don't know why the node won't join. In these unknown scenarios, we'll try again, but if you tell us to use smalls, we'll keep trying. We expect operators to identify these cases and determine the misconfiguration.

**Comment by alekc** [comment]
Ah, the reason was the presence of the swap partition. Kubelet was refusing to come up due to that. 
Once I've added generation requirement (without touching anything else), the error went away and new nodes were able to join the cluster. 

> We try to avoid being "smart" like this, since we really don't know why the node won't join. In these unknown scenarios, we'll try again, but if you tell us to use smalls, we'll keep trying.

What I meant is: lets say that karpenter has a list of 10 possible choices for deployment, as far as I understand it will try with the cheapest one, so my suggestion was more along the lines of "if the lowest one does't work, try with the next one in the list and report the issue"

But I do get your point, probably we might add the case scenario in the troubleshooting document above that  `m1.small` and `c1.medium` instances will never be able to join the cluster because of the swap 

 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-store-swap-volumes.html
> The c1.medium and m1.small instance types have a limited amount of physical memory to work with, and they are given a 900 MiB swap volume at launch time to act as virtual memory for Linux AMIs.

**Comment by ellistarn** [comment]
> "if the lowest one does't work, try with the next one in the list and report the issue"

It's not possible for us to tell if it's a transient failure, or a permanent issue. Further, we want to provide operators with the opportunity to correct misconfigurations. If we just went up a size, operators may be frustrated that they're paying more, when they would have rather fixed the issue on the smaller size.

**Comment by alekc** [comment]
Sure, should be able to do so.

**Comment by AndreiAtMP** [comment]
Hello,
How could the issue be solved, except excluding special instance types?
Best regards,
Andrei
