### ISSUE TITLE
Add China pricing endpoint

### ISSUE THREAD

**Issue by LolloneS** [aws/karpenter#4658]
### Description

**Observed Behavior**:

We are trying to run Karpenter 0.29.2 in a Kubernetes cluster running in AWS China. 

Upon startup, Karpenter pods fail with the following logs and start CrashLooping:

```
2023-08-30T13:38:35.458Z DEBUG Successfully created the logger.
2023-08-30T13:38:35.458Z DEBUG Logging level set to: debug
2023-08-30T13:38:38.079Z DEBUG controller retrieving region from IMDS {"commit": "34d50bf-dirty"}
2023-08-30T13:38:46.282Z FATAL controller Checking EC2 API connectivity, WebIdentityErr: failed to retrieve credentials caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://s3.cn-north-1.amazonaws.com.cn/ACCOUNT_ID-CLUSTER_ID-oidc-pod-identity-v2
status code: 400, request id: xxxxxxxx-yyyy-zzzz-aaaa-asdasdasd {"commit": "34d50bf-dirty"}
```

however, the OIDC provider is there:

![dsa](https://github.com/aws/karpenter/assets/17729031/5729a699-807f-46a1-923d-ded767cfd6b0)

The AWS role is configured correctly (works in AWS Global), ARN's are in the right partition (`aws-cn` instead of `aws`), ... . The pod is getting the right credentials injected by the IRSA webhook.

```
AWS_STS_REGIONAL_ENDPOINTS:   regional
AWS_ROLE_ARN: arn:aws-cn:iam::ACCOUNT_ID:role/CLUSTER_ID-Karpenter-Role
AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

**Expected Behavior**:

Karpenter should be able to find the OIDC provider in the AWS account since the provider is there and Karpenter's role allows accessing it.

**Reproduction Steps** (Please include YAML):

1. Create an OIDC provider and an IAM Role for Karpenter according to the official documentation
1. Install Karpenter in a vanilla Kubernetes cluster running in AWS China
1. Configure Karpenter to use the Role created in point 1

**Versions**:
- Chart Version: 0.29.2
- Kubernetes Version (`kubectl version`):  1.24.13

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

cc @paurosello

**Comment by LolloneS** [comment]
For context: I just tried Karpenter v0.30.0 with the `aws.assumeRoleARN` option - still got the same error.

**Comment by njtran** [comment]
When you say "official documentation" in step 1, are you referring to our Karpenter getting-started guide? https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/ 

AFAIK, if you use this guide with the [environment variables set](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#2-set-environment-variables), you should be able to see Karpenter come up. 

Can you try setting up your cluster again by following the steps in our getting-started guide and ensuring your environment variables are set in each step? The guide should do everything you need. 

If that doesn't work, can you go through https://repost.aws/knowledge-center/eks-troubleshoot-oidc-and-irsa and make sure everything looks good?

**Comment by paurosello** [comment]
We can't use the same exact instructions as we are not running on EKS, but we can say that we have it working on all other regions except China.

The pod gets the credentials from IRSA too, and get assigned the role with the right permissions.

**Comment by njtran** [comment]
@paurosello @LolloneS, can you share what "official documentation" you're referring to then? What steps did you or did you not run? 

Additionally, if you're not running on EKS how are you using IRSA?

**Comment by paurosello** [comment]
We deploy IRSA on our own, creating IDentity Provider and everything else...

Created a test pod with the same role Karpenter is using and I can see that the role is being assumed correctly and our IRSA setup is fine:

```
bash-4.2$ aws sts get-caller-identity
{
    "UserId": "AROAUO5VYDZXFRGSUNKSO:botocore-session-1695370764",
    "Account": "xxxxxx",
    "Arn": "arn:aws-cn:sts::xxxxxx:assumed-role/mu7y4-Karpenter-Role/botocore-session-1695370764"
}
```

On the Karpenter pod I can still see:

```
2023-09-22T08:35:09.800Z    DEBUG    Successfully created the logger.
2023-09-22T08:35:09.800Z    DEBUG    Logging level set to: debug
2023-09-22T08:35:12.436Z    DEBUG    controller    retrieving region from IMDS    {"commit": "637a642"}
2023-09-22T08:35:20.792Z    FATAL    controller    Checking EC2 API connectivity, WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://s3.cn-north-1.amazonaws.com.cn/xxxxxx-g8s-mu7y4-oidc-pod-identity-v2
    status code: 400, request id: 90aacb46-7183-4922-a888-8ec11e4e17a7    {"commit": "637a642"}
Stream closed EOF for kube-system/karpenter-85ddfc777c-bhjmr (controller)
```

**Comment by paurosello** [comment]
One thing we noticed is the OIDC provider is called "s3.cn-north-1.amazonaws.com.cn/xxxxxx-g8s-mu7y4-oidc-pod-identity-v2" not "https://s3.cn-north-1.amazonaws.com.cn/xxxxxx-g8s-mu7y4-oidc-pod-identity-v2" (https:// is not present)

While this works in all other regions, not sure this is a problem in China for some reason

**Comment by paurosello** [comment]
Was able to fix this issue by adding the environment variable to de deployment:

```
- name: AWS_REGION
   value: cn-north-1
```

Pricing controller is still erroring out, its not calling the Regional Endpoint, trying to figure out if it can be solved and if this endpoint actually exists on the China regions:
```
2023-09-22T08:55:49.222Z    ERROR    controller.pricing    UnrecognizedClientException: The security token included in the request is invalid
    status code: 400, request id: 46ff84e0-53a9-4d36-9e7e-c84b6decb3d7; UnrecognizedClientException: The security token included in the request is invalid
    status code: 400, request id: 93306d36-b333-467c-b384-c248a4d4ae8a    {"commit": "637a642"}
```

**Comment by paurosello** [comment]
I found the issue in https://github.com/aws/karpenter/blob/496b40fd7c26a163d7f2dc2934767efeabd431b4/pkg/providers/pricing/pricing.go#L90 for some reason when cn- region is used, the endpoint for ap- is set, but this wont work as the tokens are only valid for cn- region.

```
bash-4.2$ aws ec2   describe-spot-price-history --region=ap-south-1

An error occurred (InvalidIdentityToken) when calling the AssumeRoleWithWebIdentity operation: No OpenIDConnect provider found in your account for https://s3.cn-north-1.amazonaws.com.cn/306934455918-g8s-mu7y4-oidc-pod-identity-v2
```

```
bash-4.2$ aws ec2   describe-spot-price-history --region=cn-north-1
{
    "SpotPriceHistory": [
        {
            "AvailabilityZone": "cn-north-1b",
            "InstanceType": "c3.4xlarge",
            "ProductDescription": "Red Hat Enterprise Linux",
            "SpotPrice": "3.210700",
            "Timestamp": "2023-09-22T09:06:30+00:00"
        },
```
