### ISSUE TITLE
Deleting a provisioner without deleting its nodes

### ISSUE THREAD

**Issue by Izvi-digibank** [aws/karpenter#4664]
### Description

Hi

I was wonder if it is possible to have a provisioner deleted **without** the consequence of getting the nodes deleted as well?

Thanks

**Comment by njtran** [comment]
There is no native way of doing this in Karpenter. You can choose to disallow this in the Machine CRD directly if you'd like. [Read the Kubernetes docs on how to do this.](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/#:~:text=blockOwnerDeletion%20field%20that%20takes%20a,ownerReferences%20field.)
