### ISSUE TITLE
Spot Termination Notice - Removes the node before it is replaced

### ISSUE THREAD

**Issue by ChaseFreeman17** [aws/karpenter#4689]
### Description

**Observed Behavior**:

While testing out how Karpenter would react to a Spot termination we discovered that Karpenter is deleting the node before a node has replaced it. We were using Fault Injection Simulator to inject the spot termination notice. 

In the screen shot you can see our current provisioner and the logs from Karpenter. Which terminated the node way before it truly needed to. We are not sure if this is a configuration issue or a misunderstanding of how Karpenter should react to the spot termination notice. In this case it deleted the node 4 seconds after the termination notice, which is to fast to have a new node ready even if the spot request didn't fail in this case.

![2023-09-25 15_57_51-1_spot_bid_fis_test_v2](https://github.com/aws/karpenter/assets/8551076/d7d64ba8-50c5-4801-910c-66ee75b66e82)

**Expected Behavior**:

I would expect that Karpenter knows it has at least 2 minutes to replace the Spot node after the termination notice. In our test we purposely used a single instance type so that in theory we had a change for Karpenter to grab an on-demand instance.

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 0.30.0
- Kubernetes Version (`kubectl version`):  1.26

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Are you missing PDBs on your workloads to slow the deletion process?

**Comment by ChaseFreeman17** [comment]
Sounds like it might be the issue, thanks for the pointer we will test it out! I will reopen this if we still see issues. 

Thanks for the quick reply!
