### ISSUE TITLE
karpenter_nodes_total_pod_requests metric shows wrong data

### ISSUE THREAD

**Issue by infa-ddeore** [aws/karpenter#4702]
### Description

**Observed Behavior**:
`karpenter_nodes_total_pod_requests` metric shows wrong data that doesn't match from describe node output's cpu and mem requests

**Expected Behavior**:
correct metric should be returned

**Reproduction Steps** (Please include YAML):
check `karpenter_nodes_total_pod_requests{resource_type="memory"}` and `karpenter_nodes_total_pod_requests{resource_type="cpu"}` metric, compare it with cpu and memory Requests under "Allocated resources" section

describe output in my case:
```
$ k describe no ip-xxx.us-west-2.compute.internal ip-yyy.us-west-2.compute.internal | grep -A20 "Allocated resources" |grep -E 'cpu|memory'
  cpu                1735m (89%)   4350m (225%)
  memory             3254Mi (98%)  8320Mi (251%)
  cpu                3635m (92%)   7950m (202%)
  memory             8852Mi (59%)  13824Mi (93%)
```
karpenter_nodes_total_pod_requests output:
  cpu: 1.15 and 3.05
  memory: 2412Mi and 8010Mi

**Versions**:
- Chart Version: v0.30.0
- Kubernetes Version (`kubectl version`): v1.27.4-eks-2d98532

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by garvinp-stripe** [comment]
Did you add daemonset? That metric doesn't include daemonsets

**Comment by infa-ddeore** [comment]
@garvinp-stripe thanks for the reply, adding `karpenter_nodes_total_daemon_requests` shows accurate cpu and mem numbers now

cluster cpu and memory reservation panel in https://grafana.com/grafana/dashboards/18862-karpenter/ dashboard wasnt showing the data correctly, hence i was checking these queries

closing this issue now
