### ISSUE TITLE
ECR Karpenter helm chart errors with 400 Bad Request

### ISSUE THREAD

**Issue by amanibhavam** [aws/karpenter#4724]
### Description

**Observed Behavior**:

I'm installing Karpenter with helm, which fails because the ECR Helm repo is returning 400 Bad Request/

**Expected Behavior**:

Karpenter is installed by helm.

**Reproduction Steps** (Please include YAML):

Try to install Karpenter v0.31.0 with helm.

```
❯ helm upgrade --install --namespace karpenter --create-namespace   karpenter oci://public.ecr.aws/karpenter/karpenter   --version v0.31.0 
Release "karpenter" does not exist. Installing it now.
Error: unexpected status from HEAD request to https://public.ecr.aws/v2/karpenter/karpenter/manifests/v0.31.0: 400 Bad Request
```

**Versions**:
- Chart Version: v0.31.0
- Kubernetes Version (`kubectl version`): v1.27.5

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
From https://karpenter.sh/docs/troubleshooting/#helm-error-when-pulling-the-chart, try this before installing:

```
docker logout public.ecr.aws
``

**Comment by defnn** [comment]
I ran that command, and deleted `~/.docker/config.json` to clear out any client logins.  Still get the 400 error from Helm.

I am able to install the Karpenter helm chart on another computer so it is something with my setup.  Thank you for the tip, it knocked some sense into me.

**Comment by amanibhavam** [comment]
Found the configuration difference: the latest version of Helm, 3.13.0, gets a 400 error when running this command:

```
./linux-amd64/helm version

version.BuildInfo{Version:"v3.13.0", GitCommit:"825e86f6a7a38cef1112bfa606e4127a706749b1", GitTreeState:"clean", GoVersion:"go1.20.8"}

./linux-amd64/helm template karpenter --version v0.31.0 --namespace karpenter oci://public.ecr.aws/karpenter/karpenter

Error: unexpected status from HEAD request to https://public.ecr.aws/v2/karpenter/karpenter/manifests/v0.31.0: 400 Bad Request
```

The `helm template` command works when Helm is downgraded to the next latest version, 3.12.3

**Comment by berry2012** [comment]
Helm Version:"v3.13.1" reports the same error as well 
```
Error: unexpected status from HEAD request to https://public.ecr.aws/v2/karpenter/karpenter/manifests/v0.31.0: 400 Bad Request
```

**Comment by exNewbie** [comment]
For those using Terraform, disabling ECR authentication helps. More specifically, comment out or remove those lines
```
repository_username = data.aws_ecrpublic_authorization_token.token.user_name
repository_password = data.aws_ecrpublic_authorization_token.token.password
```

`helm_release` should look like this.
```
resource "helm_release" "karpenter" {
  namespace        = "karpenter"
  create_namespace = true

  name                = "karpenter"
  repository          = "oci://public.ecr.aws/karpenter"
#  repository_username = data.aws_ecrpublic_authorization_token.token.user_name
#  repository_password = data.aws_ecrpublic_authorization_token.token.password
  chart               = "karpenter"
  version             = "v0.32.2"
[...]
}
  ```

**Comment by exNewbie** [comment]
> Hi @exNewbie, thanks for that it helped, and its not error-ing out anymore, but I don't understand how it works without any auth though, if you have more information on how it is being handled now can you please share it out? It would help me understand things. thanks in advance.

I guess there is an authentication issue introduced recently on `helm` version `~=v3.13.0`.

**Comment by c0da** [comment]
For me, the error disappeared after updating Helm to version v3.13.3

**Comment by exNewbie** [comment]
> For me, the error disappeared after updating Helm to version v3.13.3

I believe either AWS ECR or Karpenter resolved the issue. I didnt need to change anything but the issue disparaged after a couple of weeks.

**Comment by Hadlock** [comment]
I was still having the issue in Feb 2024 using v3.13.1. I upgraded to the latest version (v3.14.2) and the issue went away immediately

**Comment by allamand** [comment]
You need also logout from helm : `helm registry logout public.ecr.aws`

**Comment by berry2012** [comment]
Helm Version:"v3.15.0" solves it for me

**Comment by tqindia** [comment]
no it doesn't
