### ISSUE TITLE
Intermittent Image pull failures

### ISSUE THREAD

**Issue by toddatapiture** [aws/karpenter#4742]
### Description

I don't believe this is a bug and is a question. It may not be related, but I am seeking some guidance. Over the weekend we upgraded our EKS cluster to the latest version of Kubernetes that it supports which is 1.28. We also upgraded Karpenter to the latest version 0.31.0. As part of the upgrade, there's been improvements to pull container images within a node across Pods in parallel (https://kubernetes.io/blog/2023/05/15/speed-up-pod-startup/#parallel-container-image-pulls). This does seem to be the case as provisioning seemed to be somewhat faster and I started running into this error under a heavy load 

```
image pull failed: pull QPS exceeded
```
I noticed this issue from awhile back: https://github.com/aws/karpenter/issues/1269

It had recommendations for increasing the `registryPullQPS `. I was able to do this via userdata in the AWSNodeTemplate like so

```
 userData: |
      MIME-Version: 1.0
      Content-Type: multipart/mixed; boundary="BOUNDARY"

      --BOUNDARY
      Content-Type: text/x-shellscript; charset="us-ascii"

      #!/bin/bash
      echo "$(jq '.registryPullQPS=50|.registryBurst=100' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json

      --BOUNDARY--
```

After reconfiguring Kubelet I now get intermittent failures pulling images. This seems to happen only under heavy load as well.

```
Failed to pull image "<aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/docker:20.10.15-dind": rpc error: code = Unknown desc = failed to pull and unpack image "<aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/docker:20.10.15-dind": failed to resolve reference "804438605645.dkr.ecr.us-east-1.amazonaws.com/docker:20.10.15-dind": failed to do request: Head "https://<aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/v2/docker/manifests/20.10.15-dind": net/http: TLS handshake timeout
Count: 2
```
We pull 3 images within each Pod as it runs 3 containers in each. One pulls from our host Nexus instances for the main container. Then we have two side-car containers for docker-in-docker (dind) and JNLP. The dind pulls from ECR and the JNLP pulls from Docker Hub. The only one that seems to have intermittent issues is the one from ECR that we noted thus far. It's from a private repo in ECR.

Any help would be greatly appreciated. I am wondering if I happen to configure something wrong.

**Observed Behavior**:
Intermittent failures to pull docker images on Karpenter provisioned nodes

**Expected Behavior**:
Successfully pull docker images on Karpenter provisioned nodes

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:  0.31.0
- Kubernetes Version (`kubectl version`):  1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Seem like throttling  issue, Are the images not eventually getting pull due to `ImagePullBackOff`?

**Comment by toddatapiture** [comment]
A throttling issue would make sense. It seems it tries twice then kills the Pod 

```
Created Pod: kubernetes jenkins-nonprod-production/apicomm-viserion-bootstraps-pr-603-1-sk5n3-lvfx7-0jlpq
Still waiting to schedule task
‘[apicomm-viserion-bootstraps-pr-603-1-sk5n3-lvfx7-0jlpq](https://build-dev.community.apiture.com/computer/apicomm-viserion-bootstraps-pr-603-1-sk5n3-lvfx7-0jlpq/)’ is offline
ERROR: Unable to pull Docker image "647426478431.dkr.ecr.us-east-1.amazonaws.com/docker:20.10.15-dind". Check if image tag name is spelled correctly.
```

The above is what is in the Jenkins console log. If I look into the K8s logs I see the error above 
```
Failed to pull image "804438605645.dkr.ecr.us-east-1.amazonaws.com/docker:20.10.15-dind": rpc error: code = Unknown desc = failed to pull and unpack image "804438605645.dkr.ecr.us-east-1.amazonaws.com/docker:20.10.15-dind": failed to resolve reference "804438605645.dkr.ecr.us-east-1.amazonaws.com/docker:20.10.15-dind": failed to do request: Head "https://804438605645.dkr.ecr.us-east-1.amazonaws.com/v2/docker/manifests/20.10.15-dind": net/http: TLS handshake timeout
Count: 2
```

**Comment by engedaam** [comment]
You could consider increasing `Rate of BatchGetImage requests` in ECR https://docs.aws.amazon.com/AmazonECR/latest/userguide/service-quotas.html

**Comment by toddatapiture** [comment]
If I am looking at the Service quota metrics correctly in CloudWatch I believe its saying I am not even using 1% of the quota. 

![image](https://github.com/aws/karpenter/assets/63865255/b1b4aec2-aa1b-4e60-ab11-00121933bc17)

I believe we get 2000 pulls per second by default

**Comment by engedaam** [comment]
Hmm, that's instructing, how many pods are scaling out? At what scale do you start seeing this issue?

**Comment by ChristinaMRogers** [comment]
@toddatapiture, did you ever figure out a soluiton for this?  I have been running into the same error recently with a lot of my Jenkins builds.

**Comment by toddatapiture** [comment]
@ChristinaMRogers Unfortunately, I never did pinpoint what actually caused the issue. Since this issue I have done a few refactors to our EKS cluster specifically around networking. Our cluster was seeing more traffic since we were migrating more stuff onto it. I had noticed the aws-node daemon set failing readiness/liveness probes causing Pods that got scheduled to the node to become stale and be terminated. This seemed to be around resource spiking. I ran across a best practices guide(https://aws.github.io/aws-eks-best-practices/networking/vpc-cni/#handle-livenessreadiness-probe-failures) and it mentioned increasing the timeouts and resources if you run into that issue.

I also added an additional replica, increased resources and HPA for the core DNS controller (I saw some spikes in resources there too). Along with adding topology spread constraints to try to keep the Pods on different nodes in different zones. I removed T class instances from the cluster and am only using more network-optimized instances (C, M, and R).

I did a few other things too such as using the latest version of the `aws-load-balancer-controller` helm chart. Increased the CIDR range for the VPC and Subnets. Along with updating the VPC-CNI to use prefix delegation and reconfiguring Kubelet to allow more Pods to schedule to a node to increase Pod density. Although, I don't think these last few things contributed to it in terms of making it better.

So, I am not really sure. I have made a lot of changes to our cluster since this issue. I did check and we were being throttled by AWS for ECR. My error was `failed to resolve reference some_url net/http: TLS handshake timeout` and since I was having other networking issues within our cluster I am chalking it up to that. Not being able to resolve makes me feel like maybe it was a DNS issue. Anyway with all this babble since the refactors I have not seen this error again. It very well could have just been a fluke on AWS as well. I wish I could help more though.
