### ISSUE TITLE
unable to install chart via terraform?

### ISSUE THREAD

**Issue by gurpalw** [aws/karpenter#4791]
### Description

**Observed Behavior**:
```
resource "helm_release" "karpenter" {
  name       = "karpenter"
  namespace  = "karpenter"
  chart      = "karpenter"
  url = "oci://public.ecr.aws/karpenter/karpenter"
  version    = "0.31.0"

  values = [
    file("values.yaml")
  ]
}
```
```
helm_release.karpenter: Creating...
╷
│ Error: could not download chart: public.ecr.aws/karpenter/karpenter/karpenter:0.31.0: not found
│ 
│   with helm_release.karpenter,
│   on provisioner.tf line 17, in resource "helm_release" "karpenter":
│   17: resource "helm_release" "karpenter" {
│ 
╵
```

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 0.30.0, and 0.31.0
- Kubernetes Version (`kubectl version`): Client Version: v1.28.2
Terraform v1.4.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.20.0
+ provider registry.terraform.io/hashicorp/helm v2.11.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by johnjeffers** [comment]
I don't think this has anything to do with terraform. I can't use the chart at all. I think the OCI repo might be down.

```# helm dependency build
Saving 2 charts
Downloading karpenter from repo oci://public.ecr.aws/karpenter
Save error occurred:  could not download oci://public.ecr.aws/karpenter/karpenter: unexpected status from HEAD request to https://public.ecr.aws/v2/karpenter/karpenter/manifests/v0.31.0: 400 Bad Request
Error: could not download oci://public.ecr.aws/karpenter/karpenter: unexpected status from HEAD request to https://public.ecr.aws/v2/karpenter/karpenter/manifests/v0.31.0: 400 Bad Request```

**Comment by pete911** [comment]
@gurpalw you have karpenter twice, you can see from the error `public.ecr.aws/karpenter/karpenter/karpenter:0.31.0` (karpenter 3x) not found. Update your url from `oci://public.ecr.aws/karpenter/karpenter` to `oci://public.ecr.aws/karpenter`
