### ISSUE TITLE
settings.pki.my-trusted-bundle  on Bottleroket detects the datauser but does not allow connecting to the cluster the node

### ISSUE THREAD

**Issue by OKAYRO** [aws/karpenter#4814]
### Description

using self-cert to 
resource "kubectl_manifest" "karpenter_node_template_linux_ondemand_spot_system" {
  yaml_body = <<-YAML
    apiVersion: karpenter.k8s.aws/v1alpha1
    kind: AWSNodeTemplate
    metadata:
      name: default
    spec:
      subnetSelector:
        karpenter.sh/discovery: ${module.eks.cluster_name}
      securityGroupSelector:
        karpenter.sh/discovery: ${module.eks.cluster_name}
      tags:
        karpenter.sh/discovery: ${module.eks.cluster_name}
      amiFamily: Bottlerocket
      userData:  |
        [settings.container-registry.mirrors]
        "registry" = "xxxxxxx
        "endpoint" = [ "https://docker-registry.xxxxxxxxxxx:5000" ]
        [settings.pki.my-trusted-bundle]
        "data" = "${base64encode(tls_self_signed_cert.docker_registry_tls_self_signed_cert.cert_pem)}"
        "trusted" = "true"
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}

settings.pki.my-trusted-bundle  on Bottleroket detects the datauser but does not allow connecting to the cluster the node

**Comment by jonathan-innis** [comment]
I'm having trouble understanding if this is a Karpenter or Bottlerocket issue. Could you describe what bug is present in Karpenter that is causing this issue (e.g. you aren't seeing the correct user data passed down). From the info that you've given me, it's tough to tell if this is a configuration bug in Terraform, a bug in Karpenter, or a bug in Bottlerocket.

**Comment by OKAYRO** [comment]
the user data is correct is a certificate( which was provided via base64 and tried -----BEGIN CERTIFICATE----- ... too,in karpenter logs I see what Bottlerocket nodes runner but no logs about why is not connected to cluster, if I' adding only userData: |
[settings.container-registry.mirrors]
"registry" = "xxxxxxx
"endpoint" = [ "https://docker-registry.xxxxxxxxxxx:5000" ]
all working without issues, but what I tried to provide [settings.pki.my-trusted-bundle] certificate in all possible special ways, nodes not connected to the cluster, and no logs about this in carpenter.

**Comment by OKAYRO** [comment]
fixed:
it's should be:
userData: |
[settings.container-registry.mirrors]
registry = ["xxxxxxx"]
endpoint = ["https://docker-registry.xxxxxxxxxxx:5000"]
[settings.pki.my-trusted-bundle]
data = "${base64encode(tls_self_signed_cert.docker_registry_tls_self_signed_cert.cert_pem)}"
trusted = "true"

**Comment by jonathan-innis** [comment]
@OKAYRO Since it looks like you got this fixed, are we alright to close this issue?

**Comment by OKAYRO** [comment]
yes
