### ISSUE TITLE
Karpenter conversion tool link broken

### ISSUE THREAD

**Issue by saha-rajdeep** [aws/karpenter#4817]
### Description

**How can the docs be improved?**
In [Karpenter conversion tool](https://github.com/aws/karpenter/tree/main/tools/karpenter-convert/README)., undet Step 7, "[Karpenter conversion tool](https://github.com/aws/karpenter/tree/main/tools/karpenter-convert/README)." link broken. 
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by chrisnegus** [comment]
Fixed in [PR #4749](https://github.com/aws/karpenter/pull/4749/commits/841e1a749a85f9e43ce0cc187d95837204fe7022).
