### ISSUE TITLE
Missing namespace in v1beta1 upgrade guide

### ISSUE THREAD

**Issue by billrayburn** [aws/karpenter#4818]
### Description

In https://deploy-preview-4749--karpenter-docs-prod.netlify.app/preview/upgrade/upgrade-guide/#prerequisites

The sample command is missing the namespace name:

`kubectl describe pod -n karpenter-xxxxxxxxxx-xxxxx | grep Image: | grep v0.....`

Should be:

`kubectl describe pod -n karpenter karpenter-xxxxxxxxxx-xxxxx | grep Image: | grep v0.....`

**Comment by chrisnegus** [comment]
Fixed in [PR #4749](https://github.com/aws/karpenter/pull/4749/commits/841e1a749a85f9e43ce0cc187d95837204fe7022).
