### ISSUE TITLE
Specify which AWS Role to use in EC2NodeClass in Upgrade Guide

### ISSUE THREAD

**Issue by saha-rajdeep** [aws/karpenter#4820]
On "step 8. Edit the converted EC2NodeClass file manually: Specify your AWS role where there is a your AWS role Here placeholder", specify which role to use. Role "KarpenterNodeRole-ec2-user-karpenter-demo" should be used, NodeInstanceRole Resource value (eksctl-ec2-user-karpenter-demo-nod-NodeInstanceRole-xyz) from Cloudformation Stack "eksctl-ec2-user-karpenter-demo-nodegroup-ec2-user-karpenter-demo-ng" doesn't work

**Comment by chrisnegus** [comment]
Fixed in [PR #4749](https://github.com/aws/karpenter/pull/4749/commits/02f3fd913218f84d6953a47a67104c22d270e3e4)
