### ISSUE TITLE
Drop empty fields from NodePool and EC2NodeClass

### ISSUE THREAD

**Issue by saha-rajdeep** [aws/karpenter#4821]
### Description

**What problem are you trying to solve?**
When existing Provisioner gets coverted to NodePool using the Go convert tool, it 
creates the following empty fields that should be dropped - creationTimestamp: null under metadata, resources: {} under spec, status: {}

Similar fields under EC2NodeClass should also be dropped - creationTimestamp: null, status: {}

**How important is this feature to you?**
Nice to have feature
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rothgar** [comment]
Some of the fields should also be dropped so it can be imported back into kubectl.

```
karpenter-convert --show-managed-fields=false
```
Still ends up showing fields that are not part of the required spec and are managed by Kubernetes

**Comment by gtomolillo** [comment]
I'll work on it
