### ISSUE TITLE
Replace "<your AWS role here>" placeholder with envsubst replacable string

### ISSUE THREAD

**Issue by rothgar** [aws/karpenter#4822]
### Description

**What problem are you trying to solve?**
Karpenter is working great but it would be really nice if we could replace the placeholder string with something we could pipe to `envsubst` with the proper variable. This could help automate some of the conversions and also make it easier to search the docs for which role they're supposed to use.

Since we already have variables declared in the guides this would help them understand how to create the right role.

**How important is this feature to you?**
medium?

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gtomolillo** [comment]
I'll work on it
