### ISSUE TITLE
Surprised by v1beta1 migration tool not preserving defaults

### ISSUE THREAD

**Issue by billrayburn** [aws/karpenter#4829]
### Description

Simply followed v1beta Upgrade Guide, and was not thinking about how NodePool does not provide defaults like Provisioner.

Since the new NodePools had different requirements than the old Provioners, and consolidation was enabled, I was surprised when Karpenter started rolling nodes and giving me different instance types.

Upgrade Guide should have a caveat about this situation.

Jonathan also suggested change to Karpenter conversion tool: default behavior is that you get the defaults from before, but you can also choose to ignore it with a CLI flag like --ignore-defaults.

**Comment by gtomolillo** [comment]
I'll work on it
