### ISSUE TITLE
Troubleshooting:  Node Launch

### ISSUE THREAD

**Issue by tip-dteller** [aws/karpenter#4893]
### Node provisioning and deprovisioning loop
An identified potential cause for a continuous cycle of nodes being provisioned and immediately deprovisioned by Karpenter, can stem from a functionality that exists within AWS Node Termination Handler (NTH), specifically - the Capacity Rebalancing.
Spot instances are time limited and therefore, interruptible. Once a signal is sent by AWS. This triggers a NTH and Karpenter, where the former signals a shutdown and the later provisions - creating a recursive situation.
This can be mitigated by either completely removing NTH or by setting the following values:
```
# enableSpotInterruptionDraining If false, do not drain nodes when the spot interruption termination notice is received. Only used in IMDS mode.
enableSpotInterruptionDraining: false

# enableRebalanceDraining If true, drain nodes when the rebalance recommendation notice is received. Only used in IMDS mode.
enableRebalanceDraining: false
```

**Comment by ellistarn** [comment]
Would you be willing to add this to the Karpenter docs?

**Comment by tip-dteller** [comment]
@ellistarn  of course, i got to open this issue from the Docs :)

**Comment by tip-dteller** [comment]
@ellistarn  - https://github.com/aws/karpenter/pull/4903 PR'd
