### ISSUE TITLE
karpenter helm chart: featureGates.drift vs. featureGates.driftEnabled

### ISSUE THREAD

**Issue by dalefrancum** [aws/karpenter#4905]
### Description

**How can the docs be improved?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

This is part documentation, part templates, part values.yaml. I'm seeing conflicts on whether to use `featureGates.driftEnabled` or `featureGates.drift`.
* In [values.yaml](https://github.com/aws/karpenter/blob/main/charts/karpenter/values.yaml#L243-L251), it states that `driftEnabled` is deprecated, and to use `drift` instead.
* The chart [README](https://github.com/aws/karpenter/blob/main/charts/karpenter/README.md) only mentions `driftEnabled`.
* The [configmap](https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/configmap.yaml#L58-L60) template only seems to respect `driftEnabled`.
* The [deployment](https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/deployment.yaml#L101-L102) template seems to accept both `drift` and `driftEnabled`.

**Comment by jonathan-innis** [comment]
@dalefrancum Yeah, the repo is in a bit of flux right now as we are getting ready to launch the beta version of Karpenter and deprecate a bunch of old fields. I'm working on updating the README right now so that's a good callout. 

I'd recommend going to a [tagged version of the repo](https://github.com/aws/karpenter/tree/v0.31.1/charts/karpenter) to get a point-in-time summary of what the chart looks like.

**Comment by jonathan-innis** [comment]
There's going to be detail here over what the new helm values are going to look like and why the values were migrated: https://karpenter.sh/preview/upgrading/v1beta1-reference/#global-settings
