### ISSUE TITLE
Add link in docs to reporting security issues

### ISSUE THREAD

**Issue by billrayburn** [aws/karpenter#4944]
### Description

**How can the docs be improved?**

Mention somewhere in the Karpenter docs that for reporting Security issues, please follow guidance in https://github.com/aws/karpenter/security/policy .

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by chrisnegus** [comment]
Closed with [PR #4998](https://github.com/aws/karpenter/pull/4998)
