### ISSUE TITLE
A way to configure scale up policy / limit the number of nodes added in a window of time

### ISSUE THREAD

**Issue by asaf-erlich** [aws/karpenter#4963]
### Description

**What problem are you trying to solve?**
Karpenter does not have a way to configure a [scaleup policy](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior) or limit the number of nodes added in a window of time. This allows Karpenter to ask for more nodes than the control plane can actually handle. If this could be configured or limited in some way in a central way by Karpenter this could allow protection for the control plane against run-away scaling.

There's also further information about these limitations documented in https://aws.github.io/aws-eks-best-practices/scalability/docs/control-plane/#limit-workload-and-node-bursting : 
> To avoid reaching API limits on the control plane you should limit scaling spikes that increase cluster size by double digit percentages at a time (e.g. 1000 nodes to 1100 nodes or 4000 to 4500 pods at once).

So this feature is in a way asking karpenter to support enforcing the very behavior EKS documentation suggests is best practice.

**How important is this feature to you?**
Twilio Segment has recently had 3 high severity incidents recently which all were caused by large scaling up events leading to cascading failures on the EKS control plane, which actually resulted in the Horizontal Pod Autoscaler asking for even more pods. Of course this exaserbated the situation. It's very important that these Large Scale Events (LSEs) / incidents do not occur again for obvious financial reasons.

As a result one of the many action items is to add HPA scaleup policies such as those mentioned in the [documentation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior). Unfortunately a pod scale-up policy is only a _proxy_ for what is actually important to limit in this case, which is the number of nodes to scale up in a window of time.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Kubernetes scalability tuning is a difficult, multi-component, system integration problem. In this case, Karpenter sits in the middle, between the work (pods) and the capacity (nodes). I'm a bit cautious about growing Karpenter's API surface to include performance considerations of downstream services, as those performance profile and integration points will change over time.

> To avoid reaching API limits on the control plane you should limit scaling spikes that increase cluster size by double digit percentages at a time (e.g. 1000 nodes to 1100 nodes or 4000 to 4500 pods at once).

This recommendation is targeting broad Kubernetes use cases, where clusters may not always be reactively autoscaled. The guidance around 1000 -> 1100 nodes is targeted at use cases where customers are configuring node scaling directly, like with EC2 Autoscaling Groups or Managed Node Groups. The latter pod numbers 4000 -> 4500 are more relevant for Karpenter. 

Then the question becomes:

"How can I rate limit the number of pods joining my cluster, to avoid impacting the control plane?".

This is actually a very good question, and ideally something that's provided automatically with something like https://kubernetes.io/docs/concepts/cluster-administration/flow-control/. Let me connect with the EKS Scalability team, and see what the guidance is.

**Comment by asaf-erlich** [comment]
I don't know if Twilio Segment is speaking directly with EKS scalability team specifically but we are in support channels with AWS. They provided those docs to us as well as the flow-control one. They've also taken steps to increase the base size of the control plane nodes. There are more actions being taken, but I think that is digressing a bit too far from the original request. 

Flow control and priority still require k8s nodes to successfully join the cluster. If nodes can't join the cluster because a majority of new nodes can't start up cilium or whatever alternative cni plugin is used to allocate IP addresses, because they are receiving 429 rate limit errors from the API server, and the API servers are crashing... I'm not sure it would always be enough to alleviate all the problems, maybe more limit the blast radius (which is valuable to some extent). It still seems like being able to configure some rate / policy of how quickly new nodes join the cluster could more drastically help the situation or completely protect the Control Plane.

Specifically "How can I rate limit the number of pods joining my cluster, to avoid impacting the control plane?" probably would be answered by configuring a pod scale up policy as documented in https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior . Like I said, we are taking steps to add these for all HPA configurations... but any calculation made about what the scale-up policy should be is derived from the percentage of nodes for these pods or number of nodes currently in the cluster. It just feels like we're dancing around the actual limitation, the nodes. 

>Let me connect with the EKS Scalability team, and see what the guidance is.

Let me know what they say, happy to talk through our TAM to schedule a call with all parties if that would help.

**Comment by asaf-erlich** [comment]
Hello Elis,

Thank you for the detailed explanation. Everything you're saying makes sense. Let me go back to the Twilio Segment compute team and discuss this with them further. I'm part of the Segment Release Engineering team and was not in the room with AWS when discussions on this topic with AWS support / internal AWS teams occurred. I was updated today that daemon set limits were more impactful than the scale up policy was originally suggested before this data was either discovered by them or in collaboration with AWS. That lines up a lot with everything you wrote. Let me get back to you shortly. Thank you again.

**Comment by asaf-erlich** [comment]
Hello Ellis,

The segment compute team has requested through our TAM to meet with the karpenter team and discuss scaling recommendations further. For now feel free to close this github issue.

Thank you,
-Asaf
