### ISSUE TITLE
feat request: Chart network policies option

### ISSUE THREAD

**Issue by giovannirco** [aws/karpenter#4978]
### Description

**What problem are you trying to solve?**
When installing karpenter using helm it would be helpful to be able to enable the creation of network policies and options to choose the flavour (Cilium as an example)

**How important is this feature to you?**
Since this application touches other parts of the cluster and aws infra this would be another layer of security

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
This is out of scope of the Karpenter project. We intentionally do not take responsibility for concerns outside of node lifecycle management.
