### ISSUE TITLE
Karpenter 0.32.0 fails in a private vpc due to IAM API requirement

### ISSUE THREAD

**Issue by Artiax** [aws/karpenter#4985]
### Description

**Observed Behavior**:
Karpenter 0.32.0 attempts to discover Instance Profile using iam.amazonaws.com API which it fails to do on a private VPC as there's no VPC Endpoint available for it.
```
{"level":"ERROR","time":"2023-10-31T16:25:09.325Z","logger":"controller","message":"Reconciler error","commit":"3a61217","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default"},"namespace":"","name":"default","reconcileID":"1b18814b-c28d-45fb-bb32-bd804070a03b","error":"resolving instance profile, getting instance profile \"REDACTED\", RequestError: send request failed\ncaused by: Post \"https://iam.amazonaws.com/\": dial tcp 52.46.159.95:443: i/o timeout"}
```
**Expected Behavior**:
Accept arn of the instance profile as an alternative to discovery via IAM API.

**Reproduction Steps** (Please include YAML):
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: REDACTED
```

**Versions**:
- Chart Version: 0.32.0
- Kubernetes Version (`kubectl version`): v1.28.2

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
If you add the IAM private endpoint, do the calls start to succeed in your private cluster? Seems like we may just need to add a note in the EKS best practices guide and in the release documentation around this new endpoint being used.

**Comment by Artiax** [comment]
There's no IAM (different to STS) private endpoint to my knowledge hence the issue.

**Comment by jonathan-innis** [comment]
> There's no IAM (different to STS) private endpoint to my knowledge hence the issue

Got it. That's annoying that IAM doesn't surface a private endpoint. Given that requirement, we may have to consider adding the `spec.instanceProfile` back into the EC2NodeClass spec to ensure users with private clusters can use the Karpenter EC2NodeClass.

**Comment by jonathan-innis** [comment]
Looking through the [supported VPC private endpoints], we saw that there's basically a workaround where we could call Cloud Control to create the instance profile. That would basically go through the VPC private endpoint for Cloud Control and then go through the AWS networking backbone to call out to IAM. It's unfortunately a little indirect, but it seems to be one of the only supported methods that we could get for the instance profile generation functionality on private clusters.

**Comment by Artiax** [comment]
We use terraform to drive our changes (as well as install the karpenter helm chart) so the creation of instance profile is just a few lines of code. We have quite a strict policy on what type of permissions can be granted to users / services and unfortunately cloudformation is not one of them.

That's not to say this would not be useful for someone else though! But for us I think the ability to supply the instance profile ARN would be the preferable option.

**Comment by michaelajr** [comment]
This is a big blocker for us as well. We are using IRSA and as such we create the role, policy, and policy attachment when Karpenter is deployed - passing the ARN to the Helm Chart via values. We do not allow workloads to create any IAM resources at runtime.

**Comment by ellistarn** [comment]
> what type of permissions can be granted to users / services and unfortunately cloudformation is not one of them.

To be clear, this isn't creating Cloudformation stacks, but the CloudControl API https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/what-is-cloudcontrolapi.html. This will reuse any permissions when creating objects. e.g. `iam:CreateInstanceProfile` is required, in addition to `cloudformation:CreateResource`.

**Comment by suket22** [comment]
> It would be ideal to create one role for all nodes within an account that has locked down permissions for that account, and then to use that directly, similarly to how managed node groups are currently utilizing iam roles.

Wanted to add a note, that managed node groups is also creating IAM instance profiles through its service-linked role (SLR), similar to what Karpenter is doing here. You can see the permissions that the managed node groups SLR has [here](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AWSServiceRoleForAmazonEKSNodegroup.html) - specifically the `PermissionsToCreateAndManageInstanceProfiles` statement in the policy.

**Comment by michaelajr** [comment]
IAM resource creation is locked down at my company as well. And `iam:*` is never allowed to be given to workloads. This is a big blocker for us. We will never be able to allow Karpenter to do `iam:*`. SLRs are different for us as we have a service approval process that we go through to get a service approved. So as long as we are running Karpenter ourselves ... we will need `instanceProfile` in spec for `EC2NodeClass`.

**Comment by michaelajr** [comment]
Btw.. why would the EKS service need to create an instance profile for a managed node group when the role arn for the node group is specified? Wouldn't it just look up the instance profile? The role already has an instance profile arn.

**Comment by levinedaniel** [comment]
Thank you for the correction @suket22 

Being able to specify an instance profile gives us (or even our security teams who are less familiar with the minutiae of karpenter) the ability to revoke access at a cluster or even fleet level.

Looking at the design [notes](https://github.com/aws/karpenter/blob/5d0d978b68ee57d24594a1a83cd3bbf8b47b2e87/designs/v1beta1-full-changelist.md#specinstanceprofile--specrole), it looks like the the intent was to simplify this for users. Could there be some middle ground here where an instance profile is only created if there is currently not an instance profile associated with the role?

**Comment by ellistarn** [comment]
> Looking at the design [notes](https://github.com/aws/karpenter/blob/5d0d978b68ee57d24594a1a83cd3bbf8b47b2e87/designs/v1beta1-full-changelist.md#specinstanceprofile--specrole), it looks like the the intent was to simplify this for users. Could there be some middle ground here where an instance profile is only created if there is currently not an instance profile associated with the role?

This is an interesting design option @jonathan-innis.

**Comment by jonathan-innis** [comment]
> currently not an instance profile associated with the role

This is interesting, but might create some weird races where a role is re-used by multiple EC2NodeClasses and both should have managed instance profiles. Our current termination flow might have a hard time reasoning about this and I'd worry that the lack of the 1-1 assignment here might create some odd edge cases in our implementation where we leak instance profiles that we manage.

**Comment by jonathan-innis** [comment]
> SLRs are different as we have an approval process to get a service approved. And once approved, the SLR allows the service to manage resources in our account

Is there a case where you can allow-list the Karpenter deployment and treat it as a service? Realistically, the only difference here between the service component and the self-managed component is how much you trust the component. Can you just say that you trust the Karpenter component to do the right thing given you know the scope of the operations that it can perform, given its controller policy.

**Comment by colintkn** [comment]
> there's basically a workaround where we could call Cloud Control to create the instance profile.

i tried this workaround by adding the permissions to Karpenter Controller and creating the `com.amazonaws.ap-southeast-1.cloudcontrolapi endpoint`. 

I'm still receiving errors connecting to `https://iam.amazonaws.com/`. Is there a way to configure Karpenter to use cloudcontrol instead of iam.

**Comment by michaelajr** [comment]
@jonathan-innis - I am setting up a meeting with our IAM team to discuss allowing `iam:CreateInstanceProfile` scoped to `arn:aws:iam::${account}:instance-profile/*`. Does it also need `iam:DeleteInstanceProfile`? Better yet - can you direct me to a list of actions the controller needs?

**Comment by jonathan-innis** [comment]
> can you direct me to a list of actions the controller needs

Sure, these are outlined in the controller policy permissions that we keep in the `cloudformation.yaml` file in our "Getting Started Guide" of our docs: https://github.com/aws/karpenter/blob/main/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml#L33

**Comment by jonathan-innis** [comment]
Specifically, the piece that I think that you care about is this section: https://github.com/aws/karpenter/blob/main/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml#L198

**Comment by johngmyers** [comment]
#4991 and the addition of the p5.48xlarge instance type is pushing us to urgently upgrade to the 0.32.x line of Karpenter. We would really appreciate if you could put `spec.instanceProfile` back in quickly.

From simplicity and reliability standpoints, we would much rather provision out an instance profile than have Karpenter faff about trying to do that itself. There is no benefit to having multiple profiles sharing a role: either share the profile or have multiple roles.

**Comment by olfway** [comment]
We also managing instance profile via terraform and tries to keep minimum permissions.

It seems that we cannot limit CreateInstanceProfile action and will have to allow to create instance profile for any role, not we one is needed for our eks nodes.

That's going against least privileges principle and there should be a way to avoid it

**Comment by olfway** [comment]
May be karpenter could check if role already has instance profile and if that instance profile (or role) has some tag, then just reuse it?

For example `karpenter.sh/discovery: ${CLUSTER_NAME}` can be used as a tag

**Comment by johngmyers** [comment]
> Is there a case where you can allow-list the Karpenter deployment and treat it as a service?

No, because it isn't a service and thus doesn't have the security or compliance properties of a service. An actor gaining operator-level credentials to the account could replace the Karpenter code or obtain Karpenter credentials and perform actions outside of what Karpenter is coded to do. The compliance paperwork has to be ours; we cannot use the AWS paperwork.

**Comment by jonathan-innis** [comment]
> It seems that we cannot limit CreateInstanceProfile action and will have to allow to create instance profile for any role, not we one is needed for our eks nodes

**Comment by jonathan-innis** [comment]
> actor gaining operator-level credentials to the account could replace the Karpenter code or obtain Karpenter credentials and perform actions outside of what Karpenter is coded to do

Can you explain this a little more? If you have scoped the permissions of the role appropriately for the controller, the actor should only be able to act using the actions that are assigned to the role. In this case, create instance profiles (which should be benign, similar to creating roles is benign unless you can assign policies to the role) and they should only be able to assign the roles constrained by `PassRole` if they want to add permissions to the instance profile.

**Comment by johngmyers** [comment]
The argument given was that the only difference between service and self-managed is how much one trusts the component and one could reason using knowledge of that component's algorithms. The counter-argument to that is that one cannot simply rely on knowledge of that component's algorithms as there are practical paths by which actors can use the credentials outside of the algorithms. With a service, such an attack is much less practical: one would have to attack the service provider and if an actor were able to do so there would likely be higher-value targets.

**Comment by michaelajr** [comment]
@jonathan-innis we met with our IAM team yesterday and explained how the instance profile actions are scoped to what is allowed by `pasRole`. They seemed to be on board. Thank you for the explanations. And thank you the PR adding `instanceProfile` back to the spec. That will allow us to move fwd while we work through the process of allowing those actions.

**Comment by jonathan-innis** [comment]
> The counter-argument to that is that one cannot simply rely on knowledge of that component's algorithms as there are practical paths by which actors can use the credentials outside of the algorithms

Even that assuming an actor gets access to the credentials that are being used by the Karpenter controller component, I'm not sure that there's much that they can do to cause real impact, given how the controller role can be constrained on `iam:CreateInstanceProfile` and `iam:AddRoleToInstanceProfile`. The most that they can really do is create an arbitrary number of instance profiles (assuming that they are using the correct tags that are present in the controller role policy) but they can't assign arbitrary roles to the instance profiles they create (these are constrained by `PassRole`) and further they can't disrupt existing workloads that are using other instance profiles because the tag conditional constraints on the policy ensure that they can only touch the instance profiles that they have explicitly created.

**Comment by jonathan-innis** [comment]
@Artiax @levinedaniel Are y'all still blocked as well from a security perspective or if we found a way to workaround the lack of an IAM private link endpoint, that would suffice as a fix to this issue and y'all would be unblocked?

**Comment by johngmyers** [comment]
Reasoning off of what the policy grants instead of what the algorithm does is not "treating Karpenter as a service".

But digging into requirements: For us it's limited-egress cluster requirements, including a multiple-month compliance procedure needed in order for something inside the account to start connecting to an AWS service it was not previously talking to before. There's also the need to use special-snowflake endpoints in some environments. There's also ease of management: provisioning an instance profile into an account has negligible cost when tacked onto the provisioning of its underlying role, whereas enabling a component inside the account to provision instance profiles has excessive cost.

**Comment by jonathan-innis** [comment]
After discussion and given the limitations imposed by the lack of an IAM private link service, we've gone ahead and decided to add the field back in the API. This offers a mechanism for users that don't want to manage the instance profile today to have an easier way to pass a role through the EC2NodeClass while also giving a workaround for those that need to go through a long process with their security review/compliance teams to enable IAM permissions OR need access through private clusters. Support for `spec.instanceProfile` should be available in the next patch version for `v0.32.x`

**Comment by staizen-stephen** [comment]
Just out of curiosity, has anyone actually seen a meaningful benefit from the separation of instance profile versus role concepts?

For me personally, I'm always creating single-purpose roles that are either for a singular instance profile class or else for another purpose entirely.

I'm just not really seeing what value they add to Karpenter beyond the necessity of being able to assign a role to an EC2 Instance via one.

I agree with other posters that using an instance profile ARN is preferable (at least in our case) because the lifetime and management of the role/instance profile is not managed by Karpenter.

Are there any advantages perceived in Karpenter owning this, aside from simplifying life for users that haven't created one already?

Very much appreciate the reintroduction of the instance profile property.

Separately, for what it's worth, VPC endpoints tend to be tied to the local AWS region. Since IAM is a global service, without local API endpoints, that might have been a factor. They have added local endpoints for STS so this may yet change.

**Comment by levinedaniel** [comment]
Karpenter engineers can chime in here but from my understanding from AWS docs - instance profiles reduce blast radius. You have the ability to revoke a singular instance profile. If you create a fleet of instances, assigning unique instance profiles to instances and only one is compromised, it might be more detrimental to revoke the role on all instances and disrupt _all_ operations.

**Comment by staizen-stephen** [comment]
@levinedaniel thanks.

That would make a bit of sense if the STS credentials were linked to the instance profile but I'm not sure if that's the case. I would assume (possibly wrongly) that they are linked to an assume role session.

My reading of the docs is that the instance profile supports the EC2 infrastructure but doesn't directly add value to consumers.

For the security concern, I would just remove the instance profile from that instance and if that wasn't sufficient then I'd need to perform session revocation on all sessions associated with the role.

So I'm not sure that option adds additional capabilities.

But you could be right!

**Comment by jonathan-innis** [comment]
> For the security concern, I would just remove the instance profile from that instance and if that wasn't sufficient then I'd need to perform session revocation on all sessions associated with the role

I think that this is the correct answer. There's no significant difference in security posture from specifying multiple instances that have the same instance profile vs. specifying a single instance profile per instance as long as the role attached to the instance profile is the same. In either case, if your instance was compromised, you would just revoke the instance profile from the instance and then revoke the sessions as described, new instances should still be able to assume role for their session, but the compromised instance will no longer be able to make any calls to AWS.

The primary benefit is usability for users who just want to reason in terms of roles and haven't already gone through the process of building out instance profiles in their accounts.
