### ISSUE TITLE
Documentation: Provisioner still being referenced

### ISSUE THREAD

**Issue by praseedasathaye** [aws/karpenter#4987]
In this doc https://karpenter.sh/v0.32/

I do see reference of "Provisioners" used in [v0.32](https://karpenter.sh/v0.32/) documentation, e.g. as below, not sure if this needs to be changed?
`Set up provisioners: By applying a provisioner to Karpenter, you can configure constraints on node provisioning and set timeout values for node expiry or Kubelet configuration values. Provisioner-level constraints related to Kubernetes and your cloud provider (AWS, for example)`

**Comment by jonathan-innis** [comment]
Closed with #4984
