### ISSUE TITLE
With v1beta1 node names has changed to ip-x-x-x-x.ec2.internal instead of karpenter.sh/xxx

### ISSUE THREAD

**Issue by wiseelf** [aws/karpenter#5003]
### Description

**Observed Behavior**:
Karpenter spins new nodes with names like ip-x-x-x-x.ec2.internal
**Expected Behavior**:
Names like `karpenter.sh/provisioner/<name>` or `karpenter.sh/nodepool/<nodepool-name>`
**Reproduction Steps** (Please include YAML):
install karpenter v32+ and use v1beta1
**Versions**:
- Chart Version: "v0.32.1"
- Kubernetes Version (`kubectl version`):  
```kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2-eks-f8587cb
```

I checked source code here: karpenter/pkg/providers/instance/instance.go
```
func getTags(ctx context.Context, nodeClass *v1beta1.EC2NodeClass, nodeClaim *corev1beta1.NodeClaim) map[string]string {
	var overridableTags, staticTags map[string]string
	if nodeClaim.IsMachine {
		overridableTags = map[string]string{
			"Name": fmt.Sprintf("%s/%s", v1alpha5.ProvisionerNameLabelKey, nodeClaim.Labels[v1alpha5.ProvisionerNameLabelKey]),
		}
		staticTags = map[string]string{
			fmt.Sprintf("kubernetes.io/cluster/%s", options.FromContext(ctx).ClusterName): "owned",
			v1alpha5.ProvisionerNameLabelKey:                                              nodeClaim.Labels[v1alpha5.ProvisionerNameLabelKey],
			v1alpha5.MachineManagedByAnnotationKey:                                        options.FromContext(ctx).ClusterName,
		}
	} else {
		staticTags = map[string]string{
			fmt.Sprintf("kubernetes.io/cluster/%s", options.FromContext(ctx).ClusterName): "owned",
			corev1beta1.NodePoolLabelKey:       nodeClaim.Labels[corev1beta1.NodePoolLabelKey],
			corev1beta1.ManagedByAnnotationKey: options.FromContext(ctx).ClusterName,
			v1beta1.LabelNodeClass:             nodeClass.Name,
		}
	}
	return lo.Assign(overridableTags, settings.FromContext(ctx).Tags, nodeClass.Spec.Tags, staticTags)
}
```
And looks like there is no Name tag override for v1beta1. 
I also tried to set Name in EC2NodeClass like this:
```
  tags:
    Name: karpenter.sh/nodepool/%nodepool-name%

  tags:
    Name: karpenter.sh/nodepool/$nodepool-name

  tags:
    Name: karpenter.sh/nodepool/${nodepool-name}

  tags:
    Name: karpenter.sh/nodepool/<nodepool-name>
```
But no luck. How can I set names for new instance to be `karpenter.sh/nodepool/<nodepool-name>` ? 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by wiseelf** [comment]
what about to do it like this:
```
func getTags(ctx context.Context, nodeClass *v1beta1.EC2NodeClass, nodeClaim *corev1beta1.NodeClaim) map[string]string {
	var overridableTags, staticTags map[string]string
	if nodeClaim.IsMachine {
		overridableTags = map[string]string{
			"Name": fmt.Sprintf("%s/%s", v1alpha5.ProvisionerNameLabelKey, nodeClaim.Labels[v1alpha5.ProvisionerNameLabelKey]),
		}
		staticTags = map[string]string{
			fmt.Sprintf("kubernetes.io/cluster/%s", options.FromContext(ctx).ClusterName): "owned",
			v1alpha5.ProvisionerNameLabelKey:                                              nodeClaim.Labels[v1alpha5.ProvisionerNameLabelKey],
			v1alpha5.MachineManagedByAnnotationKey:                                        options.FromContext(ctx).ClusterName,
		}
	} else {
		overridableTags = map[string]string{
			"Name": fmt.Sprintf("%s/%s", corev1beta1.NodePoolLabelKey, nodeClaim.Labels[corev1beta1.NodePoolLabelKey]),
		}
		staticTags = map[string]string{
			fmt.Sprintf("kubernetes.io/cluster/%s", options.FromContext(ctx).ClusterName): "owned",
			corev1beta1.NodePoolLabelKey:       nodeClaim.Labels[corev1beta1.NodePoolLabelKey],
			corev1beta1.ManagedByAnnotationKey: options.FromContext(ctx).ClusterName,
			v1beta1.LabelNodeClass:             nodeClass.Name,
		}
	}
	return lo.Assign(overridableTags, settings.FromContext(ctx).Tags, nodeClass.Spec.Tags, staticTags)
}
```

**Comment by jonathan-innis** [comment]
@wiseelf This is [documented as changed behavior as part of the v1beta1 migration](https://karpenter.sh/docs/upgrading/v1beta1-migration/#:~:text=Karpenter%20will%20now%20tag%20EC2%20instances%20with%20their%20node%20name%20instead%20of%20with%20karpenter.sh/provisioner%2Dname%3A%20%24PROVISIONER_NAME). 

Just curious: What's the reason that you want the old naming? From what we understand from users, having the node name be the Name tag on the instance would be helpful to a lot of users. You can still look up the `karpenter.sh/nodepool` through the tags, which you should be able to see Karpenter-managed nodes.

**Comment by wiseelf** [comment]
@jonathan-innis that is visually better when we need to do something in aws console. I can easily identify exact nodes I need just by seeing their name.
previously I had them like this:
```
karpenter.sh/provisioner-name/nodes-group-1
karpenter.sh/provisioner-name/nodes-group-2
karpenter.sh/provisioner-name/nodes-group-3
```
Right now they all the same, and I need to specify the tag exactly to filter them.

I can do that through the tags the only how can I pass nodepool name in the tag? 
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: tedt
spec:
  amiFamily: Bottlerocket
  tags:
     Name: karpenter.sh/nodepool/%nodepool-name%
```

**Comment by jonathan-innis** [comment]
> Right now they all the same, and I need to specify the tag exactly to filter them

I'm not quite getting that. How are they all the same? Shouldn't their names differ by their node name? Or are you saying that they all look similar so it's hard to differentiate between which nodes are owned by one nodepool or another?

`karpenter.sh/nodepool` name is automatically tagged on the instances. You shouldn't need to do anything additional to get that tag onto the instance.

**Comment by wiseelf** [comment]
> I'm not quite getting that. How are they all the same? Shouldn't their names differ by their node name? Or are you saying that they all look similar so it's hard to differentiate between which nodes are owned by one nodepool or another?

They all look similar ip-x-x-x-x.ec2.internal, so to filter only selecter nodepool I need to add filter like this

<img width="505" alt="Screenshot 2023-11-03 at 06 54 23" src="https://github.com/aws/karpenter/assets/30684491/35b27dcd-b5fe-43b7-ba20-6d0e62688b04">

Also it is hard to identify instances that are managed by karpenter from a regular instances, because they all have the same name.

> karpenter.sh/nodepool name is automatically tagged on the instances. You shouldn't need to do anything additional to get that tag onto the instance.

Yes, instances have that tag, but I want it to be a name of the instance. To achieve that I need to set tag `Name` to `karpenter.sh/nodepool/$nodepool-name`
How can I do that?

**Comment by jmdeal** [comment]
You can overwrite the Name tag in the EC2NodeClass, but Karpenter doesn't have support for dynamic tag names (related issue: #4228). Without dynamic tags names you wouldn't be able to set the Name to the node pool name but you would be able to set it to any other static string (e.g. you could set it to the EC2NodeClass name or just "karpenter node"). IIUC you're main concern is being able to easily differentiate Karpenter nodes at a glance so would this fit your use case?

**Comment by jmdeal** [comment]
@snorlaX-sleeps It's the note under [AWSNodeTemplate -> EC2NodeClass](https://karpenter.sh/docs/upgrading/v1beta1-migration/#awsnodetemplate---ec2nodeclass) in the v1beta1 migration guide. Maybe the wording could be more clear, it doesn't specifically call out its the `Name` tag.
