### ISSUE TITLE
consolidation is not working, cannot deprovision nodes created by karpenter.

### ISSUE THREAD

**Issue by dewstyh** [aws/karpenter#5012]
### Description

**Observed Behavior**:
Karpenter cannot deprovision nodes that created by itself. checked nodes deployment messages find something different than else.
message says: "Normal	Unconsolidatable	13 minutes ago	karpenter	Provisioner "default" has empty consolidation disabled by consolidation policy"

i think the message should be like " cheaper node is not available"
but i see this difference here at one place. 
**Expected Behavior**:
usually in my another environment it's working fine same terraform code for both of them. karpenter deploying and terminating nodes as required. 
**Reproduction Steps** (Please include YAML):
karpenter.tf file 

```terraform
module "karpenter" {
  source       = "terraform-aws-modules/eks/aws//modules/karpenter"
  version      = "19.5.1"
  cluster_name = module.eks.cluster_name

  irsa_oidc_provider_arn          = module.eks.oidc_provider_arn
  irsa_namespace_service_accounts = ["karpenter:karpenter"]

  create_iam_role      = false
  iam_role_arn         = module.eks.eks_managed_node_groups["two"].iam_role_arn
  irsa_use_name_prefix = false
  iam_role_additional_policies = [
    "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
  ]
  tags = {
    "karpenter.sh/discovery" = local.cluster_name
  }
}

data "aws_ecrpublic_authorization_token" "token" {}

resource "helm_release" "karpenter" {
  namespace           = "karpenter"
  name                = "karpenter"
  repository          = "oci://public.ecr.aws/karpenter"
  repository_username = data.aws_ecrpublic_authorization_token.token.user_name
  repository_password = data.aws_ecrpublic_authorization_token.token.password
  chart               = "karpenter"
  version             = "v0.30.0"

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = module.karpenter.irsa_arn
  }

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/sts-regional-endpoints"
    value = "true"
    type  = "string"
  }

  set {
    name  = "settings.aws.clusterName"
    value = module.eks.cluster_name
  }

  set {
    name  = "settings.aws.clusterEndpoint"
    value = module.eks.cluster_endpoint
  }

  set {
    name  = "settings.aws.defaultInstanceProfile"
    value = module.karpenter.instance_profile_name
  }

  set {
    name  = "settings.aws.interruptionQueueName"
    value = module.karpenter.queue_name
  }

  values = [
    <<-EOT
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "karpenter.sh/provisioner-name"
                operator: "DoesNotExist"
    EOT
  ]

  depends_on = [module.eks.eks_managed_node_groups]
}

resource "kubectl_manifest" "karpenter_provisioner" {
  yaml_body = <<-YAML
    apiVersion: karpenter.sh/v1alpha5
    kind: Provisioner
    metadata:
      name: default
    spec:
      ttlSecondsUntilExpired: 604800 # expire nodes after 7 days
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: [t3]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: [medium, small, large]
        - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
          operator: In
          values: ["on-demand"]
      providerRef:
          name: default
      consolidation:
          enabled: true
  YAML
  depends_on = [
    helm_release.karpenter
  ]
}

resource "kubectl_manifest" "karpenter_node_template" {
  yaml_body = <<-YAML
    apiVersion: karpenter.k8s.aws/v1alpha1
    kind: AWSNodeTemplate
    metadata:
      name: default
    spec:
      subnetSelector:
        karpenter.sh/discovery: ${local.cluster_name}
      securityGroupSelector:
        karpenter.sh/discovery: ${local.cluster_name}
      tags:
        karpenter.sh/discovery: ${local.cluster_name}
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}

# resource "kubectl_manifest" "test_autoscaling" {
#   yaml_body = <<-YAML
#     apiVersion: apps/v1
#     kind: Deployment
#     metadata:
#       name: test-autoscaling
#     spec:
#       replicas: 20
#       selector:
#         matchLabels:
#           app: test-autoscaling
#       template:
#         metadata:
#           labels:
#             app: test-autoscaling
#         spec:
#           containers:
#           - name: nginx
#             image: nginx:latest
#             resources:
#               requests:
#                 cpu: "100m"
#                 memory: "512Mi"
#               limits:
#                 cpu: "100m"
#                 memory: "512Mi"
#     YAML
# }

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.19.0"

  name = local.vpc_name

  cidr            = var.vpc_cidr
  azs             = local.azs
  private_subnets = local.private_subnets
  public_subnets  = local.public_subnets

  enable_nat_gateway   = true
  single_nat_gateway   = var.vpc_single_nat_gateway
  enable_dns_hostnames = true

  public_subnet_tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
    "kubernetes.io/role/elb"                      = 1
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
    "kubernetes.io/role/internal-elb"             = 1
    "karpenter.sh/discovery"                      = local.cluster_name
  }
}

output "karpenter_irsa_arn" {
  value = module.karpenter.irsa_arn
}

output "karpenter_aws_node_instance_profile_name" {
  value = module.karpenter.instance_profile_name
}

output "karpenter_sqs_queue_name" {
  value = module.karpenter.queue_name
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "19.5.1"

  cluster_name    = local.cluster_name
  cluster_version = "1.28"

  vpc_id                         = module.vpc.vpc_id
  subnet_ids                     = module.vpc.private_subnets
  cluster_endpoint_public_access = true
  node_security_group_tags = {
    "karpenter.sh/discovery" = local.cluster_name
  }
```
 

**Versions**:
- Chart Version: v30.0
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dewstyh** [comment]
karpenter recent logs:

"]}
2023-11-02T20:28:29.078Z        DEBUG   controller.awsnodetemplate      discovered security groups      {"commit": "637a642", "awsnodetemplate": "default", "security-groups": ["sg-00b2ab3fc930156a6", "sg-0831ec981a937353f", "sg-08f302ed08a557b28"]}
2023-11-02T20:28:29.114Z        DEBUG   controller.awsnodetemplate      discovered kubernetes version   {"commit": "637a642", "awsnodetemplate": "default", "version": "1.28"}
2023-11-02T20:28:29.344Z        DEBUG   controller.pricing      updated spot pricing with instance types and offerings  {"commit": "637a642", "instance-type-count": 702, "offering-count": 3450}
2023-11-02T20:28:29.632Z        DEBUG   controller.awsnodetemplate      discovered amis {"commit": "637a642", "awsnodetemplate": "default", "ids": "ami-0c97930d0d19e564a, ami-089d9d54aed6ae098, ami-089d9d54aed6ae098, ami-0317363839f0530a3", "count": 4}
2023-11-02T20:28:30.971Z        DEBUG   controller.pricing      updated on-demand pricing       {"commit": "637a642", "instance-type-count": 762}
2023-11-02T20:28:31.205Z        DEBUG   controller.deprovisioning       discovered instance types       {"commit": "637a642", "count": 758}
2023-11-02T20:28:31.491Z        DEBUG   controller.deprovisioning       discovered offerings for instance types {"commit": "637a642", "zones": ["us-east-1a", "us-east-1b", "us-east-1c"], "instance-type-count": 755, "node-template": "default"}
2023-11-02T20:36:38.604Z        INFO    controller.provisioner  found provisionable pod(s)      {"commit": "637a642", "pods": 4}
2023-11-02T20:36:38.604Z        INFO    controller.provisioner  computed new machine(s) to fit pod(s)   {"commit": "637a642", "machines": 1, "pods": 4}
2023-11-02T20:36:38.616Z        INFO    controller.provisioner  created machine {"commit": "637a642", "provisioner": "default", "machine": "default-qwt6h", "requests": {"cpu":"675m","memory":"2408Mi","pods":"11"}, "instance-types": "t3.large, t3.medium"}
2023-11-02T20:36:39.539Z        DEBUG   controller.machine.lifecycle    created launch template {"commit": "637a642", "machine": "default-qwt6h", "provisioner": "default", "launch-template-name": "karpenter.k8s.aws/7568421603899541717", "id": "lt-0fc0d4191773e89a8"}
2023-11-02T20:36:39.675Z        DEBUG   controller.machine.lifecycle    created launch template {"commit": "637a642", "machine": "default-qwt6h", "provisioner": "default", "launch-template-name": "karpenter.k8s.aws/8916252344050345306", "id": "lt-03eb1e7477ccb1303"}
2023-11-02T20:36:42.149Z        INFO    controller.machine.lifecycle    launched machine        {"commit": "637a642", "machine": "default-qwt6h", "provisioner": "default", "provider-id": "aws:///us-east-1a/i-0c84acfbaf5d19727", "instance-type": "t3.medium", "zone": "us-east-1a", "capacity-type": "on-demand", "allocatable": {"cpu":"1930m","ephemeral-storage":"17Gi","memory":"3246Mi","pods":"17"}}
2023-11-02T20:37:11.531Z        DEBUG   controller.machine.lifecycle    registered machine      {"commit": "637a642", "machine": "default-qwt6h", "provisioner": "default", "provider-id": "aws:///us-east-1a/i-0c84acfbaf5d19727", "node": "ip-10-55-1-139.ec2.internal"}
2023-11-02T20:37:24.646Z        DEBUG   controller.machine.lifecycle    initialized machine     {"commit": "637a642", "machine": "default-qwt6h", "provisioner": "default", "provider-id": "aws:///us-east-1a/i-0c84acfbaf5d19727", "node": "ip-10-55-1-139.ec2.internal"}
2023-11-02T20:38:11.264Z        DEBUG   controller      deleted launch template {"commit": "637a642", "id": "lt-0fc0d4191773e89a8", "name": "karpenter.k8s.aws/7568421603899541717"}
2023-11-02T20:38:11.372Z        DEBUG   controller      deleted launch template {"commit": "637a642", "id": "lt-03eb1e7477ccb1303", "name": "karpenter.k8s.aws/8916252344050345306"}
2023-11-02T20:38:30.402Z        DEBUG   controller.awsnodetemplate      discovered subnets      {"commit": "637a642", "awsnodetemplate": "default", "subnets": ["subnet-09272670a0b593c5e (us-east-1c)", "subnet-09a660b8e8a1c7b0f (us-east-1b)", "subnet-03f7022b117e3e0ce (us-east-1a)"]}
2023-11-02T20:43:31.033Z        DEBUG   controller.awsnodetemplate      discovered subnets      {"commit": "637a642", "awsnodetemplate": "default", "subnets": ["subnet-09272670a0b593c5e (us-east-1c)", "subnet-09a660b8e8a1c7b0f (us-east-1b)", "subnet-03f7022b117e3e0ce (us-east-1a)"]}

**Comment by jmdeal** [comment]
Could you provide the output from `kubectl describe` of both the provisioner and the node that had the unconsolidatable event?

**Comment by dewstyh** [comment]
kubectl describe provisioner default
Name:         default
Namespace:
Labels:       <none>
Annotations:  karpenter.sh/provisioner-hash: 1599235016353422174
API Version:  karpenter.sh/v1alpha5
Kind:         Provisioner
Metadata:
  Creation Timestamp:  2023-11-02T20:28:20Z
  Generation:          1
  Resource Version:    69785158
  UID:                 06cc12a2-4fc5-4665-b7d1-331fc94118d1
Spec:
  Provider Ref:
    Name:  default
  Requirements:
    Key:       kubernetes.io/arch
    Operator:  In
    Values:
      amd64
    Key:       karpenter.k8s.aws/instance-family
    Operator:  In
    Values:
      t3
    Key:       karpenter.k8s.aws/instance-size
    Operator:  In
    Values:
      medium
      small
      large
    Key:       karpenter.sh/capacity-type
    Operator:  In
    Values:
      on-demand
    Key:       kubernetes.io/os
    Operator:  In
    Values:
      linux
  Ttl Seconds Until Expired:  604800
Status:
  Resources:
    Cpu:                  2
    Ephemeral - Storage:  20959212Ki
    Memory:               3943364Ki
    Pods:                 17
Events:                   <none>

i think consolidation.enabled= true is missing here.

but i inluded in the resource manifest of kubernetes_provisioner 

resource "kubectl_manifest" "karpenter_provisioner" {
  yaml_body = <<-YAML
    apiVersion: karpenter.sh/v1alpha5
    kind: Provisioner
    metadata:
      name: default
    spec:
      ttlSecondsUntilExpired: 604800 # expire nodes after 7 days
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: [t3]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: [medium, small, large]
        - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
          operator: In
          values: ["on-demand"]
      providerRef:
          name: default
      consolidation:
          enabled: true
  YAML
  depends_on = [
    helm_release.karpenter
  ]
}

 kubectl describe node ip-10-55-2-250.ec2.internal
Name:               ip-10-55-2-250.ec2.internal
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=t3.medium
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-east-1
                    failure-domain.beta.kubernetes.io/zone=us-east-1b
                    k8s.io/cloud-provider-aws=9680b8dbee458775e1ad08e18d5da384
                    karpenter.k8s.aws/instance-category=t
                    karpenter.k8s.aws/instance-cpu=2
                    karpenter.k8s.aws/instance-encryption-in-transit-supported=false
                    karpenter.k8s.aws/instance-family=t3
                    karpenter.k8s.aws/instance-generation=3
                    karpenter.k8s.aws/instance-hypervisor=nitro
                    karpenter.k8s.aws/instance-memory=4096
                    karpenter.k8s.aws/instance-network-bandwidth=256
                    karpenter.k8s.aws/instance-pods=17
                    karpenter.k8s.aws/instance-size=medium
                    karpenter.sh/capacity-type=on-demand
                    karpenter.sh/initialized=true
                    karpenter.sh/provisioner-name=default
                    karpenter.sh/registered=true
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ip-10-55-2-250.ec2.internal
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=t3.medium
                    topology.ebs.csi.aws.com/zone=us-east-1b
                    topology.kubernetes.io/region=us-east-1
                    topology.kubernetes.io/zone=us-east-1b
Annotations:        alpha.kubernetes.io/provided-node-ip: 10.55.2.250
                    csi.volume.kubernetes.io/nodeid: {"ebs.csi.aws.com":"i-0cb915e8899946987","secrets-store.csi.k8s.io":"ip-10-55-2-250.ec2.internal"}
                    karpenter.k8s.aws/nodetemplate-hash: 6514724165300908697
                    karpenter.sh/managed-by: core-devinfra-eks
                    karpenter.sh/provisioner-hash: 1599235016353422174
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 02 Nov 2023 17:58:49 -0400
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  ip-10-55-2-250.ec2.internal
  AcquireTime:     <unset>
  RenewTime:       Thu, 02 Nov 2023 19:09:37 -0400
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 02 Nov 2023 19:06:12 -0400   Thu, 02 Nov 2023 17:58:48 -0400   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 02 Nov 2023 19:06:12 -0400   Thu, 02 Nov 2023 17:58:48 -0400   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 02 Nov 2023 19:06:12 -0400   Thu, 02 Nov 2023 17:58:48 -0400   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Thu, 02 Nov 2023 19:06:12 -0400   Thu, 02 Nov 2023 17:59:01 -0400   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:   10.55.2.250
  InternalDNS:  ip-10-55-2-250.ec2.internal
  Hostname:     ip-10-55-2-250.ec2.internal
Capacity:
  cpu:                2
  ephemeral-storage:  20959212Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             3943364Ki
  pods:               17
Allocatable:
  cpu:                1930m
  ephemeral-storage:  18242267924
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             3388356Ki
  pods:               17
System Info:
  Machine ID:                 ec27d72a7ee8e17b2060122f8675f287
  System UUID:                ec27d72a-7ee8-e17b-2060-122f8675f287
  Boot ID:                    7728f932-224f-4b02-9f02-37d27cb6f889
  Kernel Version:             5.10.197-186.748.amzn2.x86_64
  OS Image:                   Amazon Linux 2
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.19
  Kubelet Version:            v1.28.2-eks-a5df82a
  Kube-Proxy Version:         v1.28.2-eks-a5df82a
ProviderID:                   aws:///us-east-1b/i-0cb915e8899946987
Non-terminated Pods:          (7 in total)
  Namespace                   Name                                                               CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                                               ------------  ----------  ---------------  -------------  ---
  kube-system                 aws-node-69jzp                                                     25m (1%)      0 (0%)      0 (0%)           0 (0%)         71m
  kube-system                 ebs-csi-node-s6dp4                                                 30m (1%)      0 (0%)      120Mi (3%)       768Mi (23%)    71m
  kube-system                 kube-proxy-qzr4k                                                   100m (5%)     0 (0%)      0 (0%)           0 (0%)         71m
  kube-system                 secrets-provider-aws-secrets-store-csi-driver-provider-aws7r6px    50m (2%)      50m (2%)    100Mi (3%)       100Mi (3%)     70m
  kube-system                 secrets-store-csi-driver-t2wfx                                     70m (3%)      400m (20%)  140Mi (4%)       400Mi (12%)    71m
  monitoring                  fluent-bit-rb94z                                                   0 (0%)        0 (0%)      0 (0%)           0 (0%)         70m
  monitoring                  kube-prometheus-stack-prometheus-node-exporter-v9l8t               0 (0%)        0 (0%)      0 (0%)           0 (0%)         71m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests     Limits
  --------           --------     ------
  cpu                275m (14%)   450m (23%)
  memory             360Mi (10%)  1268Mi (38%)
  ephemeral-storage  0 (0%)       0 (0%)
  hugepages-1Gi      0 (0%)       0 (0%)
  hugepages-2Mi      0 (0%)       0 (0%)
Events:
  Type    Reason            Age                From       Message
  ----    ------            ----               ----       -------
  Normal  Unconsolidatable  10m (x5 over 70m)  karpenter  Provisioner "default" has empty consolidation disabled by consolidation policy
  
  how should i resolve this manually then from kubectl itself, not through terraform.

**Comment by jmdeal** [comment]
You should be able to resolve it manually by reapplying the provisioner. I'm not sure why it didn't deploy correctly in the first place though, is it possible there were unsaved changes before deploying?

**Comment by dewstyh** [comment]
i got these error, while apply provisioner from kubectl

rithagoni@iB1033 MINGW64 ~/Desktop/repositories/BaseInfrastructure (devops-178)
$ kubectl apply -f karpenter_provisoner.yaml
Error from server (BadRequest): error when creating "karpenter_provisoner.yaml": Provisioner in version "v1alpha5" cannot be handled as a Provisioner: strict decoding error: unknown field "spec.consolidation"

karpenter_provisoner.yaml file

apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ttlSecondsUntilExpired: 604800 # expire nodes after 7 days
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [t3]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [medium, small, large]
    - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["on-demand"]
  providerRef:
      name: default
  consolidation:
      enabled: true

**Comment by jmdeal** [comment]
Did this cluster already have Karpenter CRDs installed? One limitation of helm is that it won't upgrade CRDs if they change. You should be able to upgrade your CRDs using the [karpenter-crd helm chart](https://gallery.ecr.aws/karpenter/karpenter-crd). You can find more details in the [docs](https://karpenter.sh/v0.30/upgrade-guide/#custom-resource-definition-crd-upgrades).
