### ISSUE TITLE
Upgrade from version 0.10.1 to 0.30.0 in EKS

### ISSUE THREAD

**Issue by monik-sb** [aws/karpenter#5014]
We're trying to upgrade kerpenter in our existing EKS cluster from version 0.10.1 to 0.30.0 to be able to leverage it's native spot termination handing. We're using ansible playbooks and helm upgrade to do this operation. Our EKS cluster is having Kubernetes version 1.24. 

The following is our existing ansible playbook code snippet:
`
- name: Adding & Updating Karpenter helm charts repository
  shell: "helm repo add karpenter https://charts.karpenter.sh && helm repo update"

- name: Installing Karpenter helm charts
  shell: |
          helm upgrade --install --namespace karpenter \
            karpenter karpenter/karpenter \
            --version {{ karpenter_helm_charts_version }} \
            --set clusterName={{ team }}-{{ vpc }}-cluster \
            --set clusterEndpoint=$(aws eks describe-cluster --name {{ team }}-{{ vpc }}-cluster --query cluster.endpoint --output json --region {{ location }} --profile {{ profile }}) \
            --set aws.defaultInstanceProfile={{ team }}-{{ vpc }}-cluster-KarpenterNodeInstanceProfile \
            --wait
`

We've changed the code to following:

helm upgrade --install --namespace karpenter \
  karpenter oci://public.ecr.aws/karpenter/karpenter \
            --version {{ karpenter_helm_charts_version }} \
            --set settings.aws.clusterName={{ team }}-{{ vpc }}-cluster \
            --set settings.aws.clusterEndpoint=$(aws eks describe-cluster --name {{ team }}-{{ vpc }}-cluster --query cluster.endpoint --output json --region {{ location }} --profile {{ profile }}) \
            --set settings.aws.defaultInstanceProfile={{ team }}-{{ vpc }}-cluster-KarpenterNodeInstanceProfile \
            --wait

We're able to see that a couple of karpenter pods are there in the cluster with version 0.30.0 but they're always in pending state. When we checked the karpenter deployment the pods were having some default affinity rules attached to them. When we removed those affinity rules and redpolyed it manually karpenter upgrade to 0.30.0 was successful and karpenter pods were running. Is there any way for us to updrade karpenter from 0.10.1 to 0.30.0 without doing any manual deployment changes and not having the dafault affinity rules for karpenter pods?

**Comment by jonathan-innis** [comment]
What's the reason you can't support the anti-affinity rules on the infrastructure where Karpenter is living? IIRC, we are requiring that Karpenter doesn't schedule on self-provisioned nodes and also that each Karpenter pod schedules on a different node in HA mode

**Comment by monik-sb** [comment]
In our current infra we don't have any nodeTemplates/podTemplates. So not sure as to why the Karpenter pods are not being scheduled on the provisioners that we have. I guess since there's some default affinity rules on those pods they're not able to be scheduled on those instances.
