### ISSUE TITLE
How does Karpenter handle EC2 API throttling?

### ISSUE THREAD

**Issue by rohansood10** [aws/karpenter#5021]
The EC2 API uses a token-bucket algorithm-based throttling mechanism: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/throttling.html

Requests, let's say to the RunInstances operation for instance, could encounter `Client.RequestLimitExceeded`. I don't see it handled here: https://github.com/aws/karpenter/blob/main/pkg/errors/errors.go

Would Karpenter just immediately retry a RunInstances request that gets rate limited? Or does it have some kind of a backoff mechanism?

Thanks!

**Comment by jonathan-innis** [comment]
> does it have some kind of a backoff mechanism

It has a backoff mechanism. This backoff is defined by controller-runtime as an exponential backoff mechanism that's defined here: https://github.com/aws/karpenter-core/blob/main/pkg/controllers/nodeclaim/lifecycle/controller.go#L160
