### ISSUE TITLE
How do I set enablePodENI since its removed from version 0.32.0 ?

### ISSUE THREAD

**Issue by thepoppingone** [aws/karpenter#5031]
I cant find any docs on it and the FAQ page is not updated to reflect this

https://github.com/aws/karpenter/blob/a1ae4a86a8dcd63525d12f773297536d4334569a/website/content/en/v0.32/troubleshooting.md#log-message-of-inflight-check-failed-for-node-expected-resource-vpcamazonawscompod-eni-didnt-register-on-the-node-is-reported

**Comment by jonathan-innis** [comment]
This option was dropped from v0.32.0 and this resource is _always_ reported now. We should definitely update the FAQ to reflect this.
