### ISSUE TITLE
Deleting the old v1alpha5 Machine CRD prevents karpenter from starting up

### ISSUE THREAD

**Issue by rknightion** [aws/karpenter#5035]
### Description

**Observed Behavior**:
Post upgrade to 0.32.1, after removing the old provisioners/nodetemplates etc we deleted the actual CRD.

This causes karpenter to fail to start specifically on the Machine.
`panic: failed to setup machine provider id indexer: failed to get API group resources: unable to retrieve the complete list of server APIs: karpenter.sh/v1alpha5: the server could not find the requested resource`
 
**Expected Behavior**:
That we can clean up no longer used CRDs without Karpenter failing to start

**Reproduction Steps** (Please include YAML):
Delete machine CRD. Restart Karpenter

**Versions**:
- Chart Version: 0.32.1
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Unfortunately, we can't really get around this problem with this release. We have to support both sets of CRDs during the v0.32.x release to support the migration path. 

v0.33.0 shouldn't require the v1alpha5 APIs. At that point, you should be able to drop those CRDs from your cluster.

**Comment by rknightion** [comment]
That makes sense! - Thanks!
