### ISSUE TITLE
Karpenter should hold an unneeded node for almost the billing period 

### ISSUE THREAD

**Issue by wpbeckwith** [aws/karpenter#5050]
### Description

**What problem are you trying to solve?**
I want to optimize the nodes I have already spent money on by keeping them around for as long as possible.  As an example, if Karpenter creates a new node at 12:00 and the node is deemed to be empty at 12:23, then I want Karpenter to keep the node around until a configurable amount (default 5m maybe) before the the 60m billing period ends before deleting it.  This is because if the node is needed again, then it can immediately be used.  However, if the node was deleted at 12:24 and then another pod @ 12:30 requires Karpenter to create another node, then I will have actually spent double the amount over just holding onto a node that's already been paid for.
 
**How important is this feature to you?**
It was save a lot in environments where there are short lived jobs and disruption enabled.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Karpenter is explicitly designed around a price-per-instance-type optimization algorithm https://github.com/aws/karpenter-core/blob/main/pkg/cloudprovider/types.go#L128, and I don't see a technical path to extending this to arbitrary complexity.

EC2 charges per second, so I assume you're talking about the costs incurred from a 3p software vendor. We've occasionally heard from customers about 3p vendors billing in slower increments (hourly as you suggest), or even more complex models (e.g. per node, per vcpu). These business models are challenging to optimize around, and realistically, Karpenter cannot hope to capture optimization decisions for all business models for all 3p integrations. 



Ideally, the charges would be either:
1. Small enough that the orthogonal pricing isn't significant enough to change capacity optimization decisions.
2. Directly proportional to VM price, such price optimizations are directly aligned with what Karpenter optimizes for

**Comment by engedaam** [comment]
Related: https://github.com/kubernetes-sigs/karpenter/issues/693
