### ISSUE TITLE
New crd resource never get synced in argocd

### ISSUE THREAD

**Issue by lllsJllsJ** [aws/karpenter#5062]
### Description

**Observed Behavior**:
On previous version of karpenter there is no OutOfSync issue on old resource while the new version occur on new resources.
- ec2nodeclasees
- nodeclaims
- nodepools

![image](https://github.com/aws/karpenter/assets/6390482/9fe725c9-5c71-4301-bb98-85e8f9992221)
![image](https://github.com/aws/karpenter/assets/6390482/cf0e38b4-0496-473f-ad37-2cea1487cb52)
![image](https://github.com/aws/karpenter/assets/6390482/7f4ac8f2-7ca1-4cb8-a1da-a7e9eb7a020c)
![image](https://github.com/aws/karpenter/assets/6390482/32bfd75b-cbd1-4f03-8110-700b1686ffee)

**Expected Behavior**:
After made a sync it should not show the diff anymore

**Reproduction Steps** (Please include YAML):
Just install karpenter using ArgoCD

**Versions**:
- Chart Version: 0.32.1
- Kubernetes Version (`kubectl version`): 1.24
- ArgoCD Version: 2.5.0

**Comment by jonathan-innis** [comment]
> On previous version of karpenter there is no OutOfSync issue on old resource while the new version occur on new resources

Which version of Kubernetes are you running? I'm assuming that you are running a version < 1.25 which doesn't support the `x-kubernetes-validations`?

**Comment by jonathan-innis** [comment]
Also, are you installing the CRDs through the `karpenter` helm chart or the `karpenter-crd` helm chart?

**Comment by lllsJllsJ** [comment]
After upgrade eks to 1.25 the issue are gone.

Thanks

In addition I have install the CRDs through the karpenter helm chart
