### ISSUE TITLE
Restrict IAM Policy in AWS Setup Instructions

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#507]
The AWS Setup instructions should use https://docs.aws.amazon.com/IAM/latest/UserGuide/access_iam-tags.html to ensure that cross-cluster resource launching is not possible. Canonical tagkey format: `kubernetes.io/cluster/$CLUSTER_NAME`.

**Comment by ellistarn** [comment]
Restrict pass role as well: https://aws.amazon.com/blogs/security/granting-permission-to-launch-ec2-instances-with-iam-roles-passrole-permission/

**Comment by johngmyers** [comment]
Should also limit `ec2:TerminateInstances` to instances tagged for the cluster and correspondingly limit the ability to add tags to instances to only upon launch.

**Comment by geoffcline** [comment]
Is this a suitable policy?

```
{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Action": [
          "ec2:RunInstances",
          "ec2:TerminateInstances"
        ],
        "Effect":  "Allow",
        "Resource": "*",
        "Condition": {
            "ForAnyValue:StringEquals": {"aws:TagKeys": ["kubernetes.io/cluster/${var.cluster_name}"]}
        }
      },
      {
        "Action": [
          "ec2:CreateFleet",
          "ec2:CreateLaunchTemplate",
          "ec2:CreateTags",
          "iam:PassRole",
          "ec2:DescribeLaunchTemplates",
          "ec2:DescribeInstances",
          "ec2:DescribeSecurityGroups",
          "ec2:DescribeSubnets",
          "ec2:DescribeInstanceTypes",
          "ec2:DescribeInstanceTypeOfferings",
          "ec2:DescribeAvailabilityZones",
          "ssm:GetParameter"
        ],
        "Effect":  "Allow",
        "Resource": "*"
      }
    ]
  }
```

**Comment by geoffcline** [comment]
[sample-policy-karpenter-restrict-controller-role-14DEC2021.json.txt](https://github.com/aws/karpenter/files/7716759/sample-policy-karpenter-restrict-controller-role-14DEC2021.json.txt)

here is a sample policy that currently only works for deletes, not create instances. so, a work in progress.
