### ISSUE TITLE
AWS EC2NodeClass's Cannot be Deleted/Edited

### ISSUE THREAD

**Issue by tom-pavz** [aws/karpenter#5079]
### Description

**Observed Behavior**:
Deleting an `EC2NodeClass` with karpenter `v.0.32.1` running on AWS EKS hangs indefinitely despite any `force` or other CLA's provided to the `kubectl delete EC2NodeClass <nodeclass-name>` command. I am deleting it AFTER I delete the associated NodePool and there are no nodes running that were spawned from this NodePool. I am forced to go into the `kubectl edit EC2NodeClass` and modify the `finalizers:` to be `[]` manually, then it deletes fine.

Editing `EC2NodeClass` definitions has also not been taking effect properly in the resulting NodePool associated with it, and as such I have needed to manually delete the entire `EC2NodeClass` and re-create it fully in order to accomplish an edit of its definition.

**Expected Behavior**:
The `EC2NodeClass` gets deleted properly when no NodePools are associated with it and no Nodes are running that were spawned by it.

`EC2NodeClass` definitions can be updated in-place and take effect.

**Reproduction Steps** (Please include YAML):
`kubectl delete EC2NodeClass <nodeclass-name>`

`kubectl edit EC2NodeClass <nodeclass-name>`

**Versions**:
- Chart Version: v.0.32.1
- Kubernetes Version (`kubectl version`): 
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.14-eks-f8587cb", GitCommit:"7e6f4dcad910c5e01deb6c0e6b313e0ca2fed5b7", GitTreeState:"clean", BuildDate:"2023-09-18T22:14:19Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by laiminhtrung1997** [comment]
I cannot delete the CRD EC2NodeClass too.

I can get it.
![image](https://github.com/aws/karpenter/assets/68812829/cf6ea5f5-e18e-4204-b03d-1c8ebaad95a2)

but I cannot delete it.
log:
```
{"level":"ERROR","time":"2023-11-14T11:18:01.832Z","logger":"controller.disruption","message":"listing instance types for herculesdev16, resolving node class, ec2nodeclasses.karpenter.k8s.aws \"herculesdev16\" not found","commit":"1072d3b"}
```

**Comment by laiminhtrung1997** [comment]
`For the purposes of NodeClass CloudProvider resolution, we treat deleting NodeClasses as NotFound`
I saw this comment in pkg/cloudprovider. So I cannot delete it?

**Comment by jonathan-innis** [comment]
> I cannot delete the CRD EC2NodeClass too

The EC2NodeClass contains a finalizer that watches for all nodes that were launched by the NodePool/EC2NodeClass to be fully deleted before the EC2NodeClass can be removed. This is in-place to ensure that all of the instances that are running using the managed instanceProfile are deleted before the instance profile is removed and the EC2NodeClass is deleted.

This behavior is maintained by the EC2NodeClass checking for the existence of any `NodeClaims` that are using it and refusing to be removed until all associated `NodeClaims` are removed. You should be able to see this by doing a `describe` on the EC2NodeClass to see the events on why it's hanging.

**Comment by tom-pavz** [comment]
> > I cannot delete the CRD EC2NodeClass too
> 
> The EC2NodeClass contains a finalizer that watches for all nodes that were launched by the NodePool/EC2NodeClass to be fully deleted before the EC2NodeClass can be removed. This is in-place to ensure that all of the instances that are running using the managed instanceProfile are deleted before the instance profile is removed and the EC2NodeClass is deleted.
> 
> This behavior is maintained by the EC2NodeClass checking for the existence of any `NodeClaims` that are using it and refusing to be removed until all associated `NodeClaims` are removed. You should be able to see this by doing a `describe` on the EC2NodeClass to see the events on why it's hanging.

@jonathan-innis 
I understand that an `EC2NodeClass` should only be deleted one all of its nodes' / nodeclaims' no longer exist, but I am seeing it unable to be deleted even when there are NO nodes / nodeclaims existing anymore. See the following evidence:

```
$ kubectl get nodes
NAME                                         STATUS   ROLES    AGE   VERSION
ip-30-0-102-210.us-west-2.compute.internal   Ready    <none>   26d   v1.25.13-eks-43840fb
ip-30-0-106-137.us-west-2.compute.internal   Ready    <none>   26d   v1.25.13-eks-43840fb
ip-30-0-127-92.us-west-2.compute.internal    Ready    <none>   26d   v1.25.13-eks-43840fb
ip-30-0-137-159.us-west-2.compute.internal   Ready    <none>   26d   v1.25.13-eks-43840fb
ip-30-0-139-163.us-west-2.compute.internal   Ready    <none>   26d   v1.25.13-eks-43840fb
ip-30-0-165-35.us-west-2.compute.internal    Ready    <none>   26d   v1.25.13-eks-43840fb
```
These are the 6 nodes that my cluster has, which are all in AWS EKS NodeGroups, and where I schedule kubernetes / karpenter / etc services that are persistent. They were NOT created by karpenter.

```
$ kubectl get nodepool
NAME                        NODECLASS
nodepool-cpu                nodeclass
nodepool-gpu                nodeclass
nodepool-high-storage-cpu   nodeclass-high-storage
nodepool-high-storage-gpu   nodeclass-high-storage
$ kubectl get ec2nodeclass
NAME                     AGE
nodeclass                46h
nodeclass-high-storage   46h
```
These are my NodePool's and EC2NodeClass's.

```
$ kubectl delete nodepool nodepool-cpu
nodepool.karpenter.sh "nodepool-cpu" deleted

$ kubectl delete nodepool nodepool-gpu
nodepool.karpenter.sh "nodepool-gpu" deleted

$ kubectl delete ec2nodeclass nodeclass
ec2nodeclass.karpenter.k8s.aws "nodeclass" deleted
^C
```
I delete the NodePool's associated with the EC2NodeClass, and then I delete the EC2NodeClass which hangs and I need to `^C` out of it.

```
$ kubectl describe ec2nodeclass nodeclass
Name:         nodeclass
Namespace:
Labels:       <none>
Annotations:  karpenter.k8s.aws/ec2nodeclass-hash: 7530630216640784102
API Version:  karpenter.k8s.aws/v1beta1
Kind:         EC2NodeClass
Metadata:
  Creation Timestamp:             2023-11-13T18:19:47Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2023-11-15T17:09:29Z
  Finalizers:
    karpenter.k8s.aws/termination
...

Events:    <none>
```
As you can see, then describe shows it is queued for delete, and it also has no `Events`.

```
$ kubectl get ec2nodeclass
NAME                     AGE
nodeclass                46h
nodeclass-high-storage   46h
```
Finally, you can see the EC2NodeClass I attempted to delete is still stuck existing.

**Comment by jonathan-innis** [comment]
> Finally, you can see the EC2NodeClass I attempted to delete is still stuck existing 

What are the Karpenter logs associated with the deletion?

**Comment by Guilhermesfl** [comment]
One solution that worked for me is to edit the ec2nodeclass yaml (e.g using k9s) and remove the finalizer. This instantly allowed me to delete the ec2nodeclass resource.

**Comment by tom-pavz** [comment]
> One solution that worked for me is to edit the ec2nodeclass yaml (e.g using k9s) and remove the finalizer. This instantly allowed me to delete the ec2nodeclass resource.

Yes, this is the workaround I had been using as well.

However, I was able to resolve this issue fully, thanks to @jonathan-innis's suggestion to look at the karpenter service logs. I was seeing various IAM permissions related Access Denied errors because the karpenter controller role did not have the necessary perms to manage instance profiles. I updated my roles according to https://karpenter.sh/v0.32/getting-started/migrating-from-cas/#create-iam-roles and it is now working correctly, thank you!

**Comment by dbaltor** [comment]
1. I have deleted the deployment that triggered the Karpenter to provision additional nodes
1. All additional nodes have been removed from the cluster by Karpenter 
1. I've successfully deleted Karpenter and its namespace from the cluster 

However, I still can't delete the EC2NodeClass resource without removing its `karpenter.k8s.aws/termination` finalizer as described above. 
```
kubectl delete EC2NodeClass default
```
This looks like a bug to me.

**Comment by jonathan-innis** [comment]
> This behavior is maintained by the EC2NodeClass checking for the existence of any NodeClaims that are using it 

Can you grab all of the NodeClaims on the cluster using `kubectl get nodeclaims` and then checking if there are any NodeClaims that reference the `default` EC2NodeClass that you have through the `spec.nodeClassRef` field?

**Comment by dbaltor** [comment]
Sure. Thanks @jonathan-innis for looking into this.
Here are the results:
```
❯ kubectl delete ns karpenter
namespace "karpenter" deleted
❯ kubectl get all -n karpenter
No resources found in karpenter namespace.
❯ kubectl get nodepool
No resources found
❯ kubectl get ec2nodeclass
NAME      AGE
default   36m
❯ kubectl get nodeclaim
No resources found
```

**Comment by jonathan-innis** [comment]
> Then this one hangs forever unless I remove its finalizer

Can you share the Karpenter logs to see if there are any errors that are being raised here? Looking at the describe output, looks like you're right that all the NodeClaims are gone so it shouldn't be waiting on that anymore

**Comment by dbaltor** [comment]
As I've already successfully deleted Karpenter, there are no pods to get logs from

**Comment by dbaltor** [comment]
After further tests, I confirmed that the behaviour above is intermittent. The `ec2nodeclass` is removed sometimes but not always.

**Comment by dennyvettom** [comment]
Force removal of EC2NodeClass in K8s
Once you have removed all the nodes associated with the nodecalss, you can force removal by editing the EC2NodeClass manifest on kubernetes. This is a hack, use only as last step.

- On k8s edit the EC2NodeClass manifest
- remove finalizers and save
`   finalizers:                                                                                                                                                           │
      - karpenter.k8s.aws/termination`

**Comment by ahoehma** [comment]
I installed karpenter via eks tf addons.
Then I uninstalled karpenter with "helm".
After that the ec2nodeclass's are not deletable.
Same workaround: remove finalizers.

**Comment by luciano-buono** [comment]
Hi, I'm facing the same problem but I can't delete the Ec2Nodeclass even if I edit the finalizer first:

```
❯ kg ec2nodeclass
kNAME   AGE
apps   32s
ci     30d
❯ k edit ec2nodeclass apps
ec2nodeclass.karpenter.k8s.aws/apps edited
❯ k delete ec2nodeclass apps
ec2nodeclass.karpenter.k8s.aws "apps" deleted
k%                                                                                                                                                                                                                                                            ❯ kg ec2nodeclass
NAME   AGE
apps   3s
ci     30d
```

The Ec2nodeclass just get recreated automatically

There are no nodeclaims:
```
❯ kg nodeclaim
No resources found
```


And the same behaiviour happens with the Nodepool:
```
❯ kg nodepool
NAME   NODECLASS
apps   apps
ci     ci
❯ k delete nodepool apps
nodepool.karpenter.sh "apps" deleted
kg%                                                                                                                                                                                                                                                           ❯ kg nodepool
NAME   NODECLASS
apps   apps
ci     ci
```
(except it doesn't have  a finalizers to edit)

**Comment by hamadycisselp360** [comment]
I have the same issue. I ran into it while trying to upgrade from Karpenter 0.37 to v1.0.5.
I tried deleting the node group but nothing.
Now I have to delete the whole cluster.

This was really unexpected.
