### ISSUE TITLE
Karpenter nodes version drift

### ISSUE THREAD

**Issue by disparo13** [aws/karpenter#5089]
### Description

**Observed Behavior**:
Karpenter's node been spun up using different Kubernetes versions each time. 

```
> kubectl get node
NAME                                     STATUS   ROLES    AGE     VERSION
fargate-ip-10-199-125-179.ec2.internal   Ready    <none>   17h     v1.26.9-eks-f8587cb
fargate-ip-10-199-55-251.ec2.internal    Ready    <none>   17h     v1.26.9-eks-f8587cb
fargate-ip-10-199-55-45.ec2.internal     Ready    <none>   17h     v1.26.9-eks-f8587cb
fargate-ip-10-199-92-34.ec2.internal     Ready    <none>   17h     v1.26.9-eks-f8587cb
ip-10-199-111-136.ec2.internal           Ready    <none>   4h53m   v1.26.10-eks-3edb55d
ip-10-199-55-55.ec2.internal             Ready    <none>   16h     v1.26.7-eks-7ea2e3a
```

Here, you can see that Karpenter is running on the Fargate profile, which nodes have version 1.26.9, then Karpenter itself spun up two more nodes, one with version 1.26.7, and another - with version 1.26.10. 

**Expected Behavior**:
I expect that Karpenter's choosing more-less the same ami version to run its nodes.  

**Reproduction Steps** (Please include YAML):
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "t"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        name: default
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 48h
  weight: 10
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  role: "karpenter-noderole"
  subnetSelectorTerms:
    - tags:
        Name: "dev-private*"
        Environment: "dev-test"
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/dev-test: "owned"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 25Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 75Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
```

**Versions**:
- Chart Version: v0.32.1
- Kubernetes Version (`kubectl version`): Server Version: v1.26.10-eks-4f4795d

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Karpenter is pulling the most recent Bottlerocket AMI at the time that the node is launched.  Your newer node is running a newer AMI.

**Comment by disparo13** [comment]
@tzneal But how come Bottlerocket evolved via the three minor versions in less than 24 hours?

**Comment by tzneal** [comment]
Can you provide the AMI IDs for those two nodes?

**Comment by hlascelles** [comment]
I see this too. I see versions `v1.26.10-eks-4f4795d` and `v1.26.4-eks-0a21954`. In my case they were 15 mins apart.

I expect it is not a Good Thing. Can we set the version it should use, or some config for it to "be consistent"?

**Comment by tzneal** [comment]
You can use [AMI selectors](https://karpenter.sh/docs/concepts/nodeclasses/#specamiselectorterms) to pin the AMI to a particular version.  Otherwise, Karpenter will always launch the most recently released AMI. If you have drift enabled (which is the [default](https://karpenter.sh/v0.32/upgrading/v1beta1-migration/#drift-enabled-by-default) depending on your Karpenter version), Karpenter will upgrade older nodes to the newer version so they will be consistent.

**Comment by tzneal** [comment]
Closing this one as I think its solved, feel free to re-open.

**Comment by jmdeal** [comment]
@amitmantha I answered in your other [issue](https://github.com/aws/karpenter/issues/5200#issuecomment-1836630768).
