### ISSUE TITLE
subnetSelectorTerms multiple tags discovery detects wider range of subnets

### ISSUE THREAD

**Issue by ArieLevs** [aws/karpenter#5097]
### Description

**Observed Behavior**:
Karpenter 0.32.0 [subnetSelectorTerms](https://karpenter.sh/v0.32/concepts/nodeclasses/#specsubnetselectorterms) seems to use the `or` operator when using tags for subnets discovery instead of `and` operator

Im setting the subnet selector to use 3 different tags, and can see that the `ec2nodeclass` discovers more subnets then intended (and spinning nodes on subnets that should not be used)

Should the tag discovery use an `or` or an `and` between them? (worked around this by using the `id` selector and doing the discovery using terraform data source)

**Expected Behavior**:
if its expected operation between tags discovery then documentation should be updated,  
else bug should get fixed to include **all** tags respected 

**Reproduction Steps** (Please include YAML):
create a [EC2NodeClass](https://karpenter.sh/v0.32/concepts/nodeclasses/) and use the `Select using multiple tag terms`

**Versions**:
- Chart Version: v0.32.1
- Kubernetes Version: v1.28.2

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
The example labeled `Select by name and tag (all criteria must match):` shows how to use multiple tag names. Does this not work for you?

**Comment by ArieLevs** [comment]
i cannot use `Name` for selection, by the example above would this work?
```
spec:
  subnetSelectorTerms:
    - tags:
        key_a: "some val"
        karpenter.sh/discovery/MyClusterName: '*'
        another_tag: "string"
```

**Comment by tzneal** [comment]
Yes, that should work provided they are all tags on the same subnet.

**Comment by ArieLevs** [comment]
Thanks, guess just misunderstood the documentation 🤦‍♂️
