### ISSUE TITLE
`v0.32.x`: Errors around reading configmap on startup

### ISSUE THREAD

**Issue by snorlaX-sleeps** [aws/karpenter#5107]
### Description

**Observed Behavior**:
Unsure if this is a me issue, has been occurring since the upgrade to `v0.32.1` and I assume it's related to the settings configmap?
```
W1116 19:06:57.293206       1 reflector.go:535] k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1.ConfigMap: Get "https://172.20.0.1:443/api/v1/namespaces/<namespace>/configmaps?limit=500&resourceVersion=0": dial tcp 172.20.0.1:443: connect: connection refused
E1116 19:06:57.293320       1 reflector.go:147] k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://172.20.0.1:443/api/v1/namespaces/<namespace>/configmaps?limit=500&resourceVersion=0": dial tcp 172.20.0.1:443: connect: connection refused
W1116 19:06:58.120295       1 reflector.go:535] k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1.ConfigMap: Get "https://172.20.0.1:443/api/v1/namespaces/<namespace>/configmaps?limit=500&resourceVersion=0": dial tcp 172.20.0.1:443: connect: connection refused
E1116 19:06:58.120347       1 reflector.go:147] k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://172.20.0.1:443/api/v1/namespaces/<namespace>/configmaps?limit=500&resourceVersion=0": dial tcp 172.20.0.1:443: connect: connection refused
```

It's not stopping Karpenter from starting, it just appears every time a Karpenter pod starts.
Is it related to the move to ENV VARS instead of a configmap?

**Expected Behavior**:
No error logs on startup

**Reproduction Steps** (Please include YAML):
Using the official Helm Chart from `oci://public.ecr.aws/karpenter` for `v0.32.1`
Setting enabled:
- `clusterName`
- `featureGates.drift`

Looking in the configmap in cluster, `batchIdleDuration` and `batchMaxDuration` are the only values being set

**Versions**:
- Chart Version: "v0.32.1"
- Kubernetes Version (`kubectl version`): 1.27.7

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
It looks like you are getting permissions issues on the ConfigMap. Did you remove the permission for the Karpenter controller to list/watch ConfigMaps?

**Comment by snorlaX-sleeps** [comment]
@jonathan-innis we use the official Helm Chart for the Karpenter deployment, so it would just use whatever configuration is deployed by default.
Planning to do some more migrations this week, will update the ticket with more information as this progresses

**Comment by jonathan-innis** [comment]
@snorlaX-sleeps The reason I was asking is because we hadn't seen this error on our side. Does this error occur ever time you re-run Karpenter?

**Comment by snorlaX-sleeps** [comment]
Hey @jonathan-innis - I'm going to close this as it only appeared in two of our test clusters (which I upgraded last week) and neither of the production ones that I upgraded today.
I am unsure what might have caused it as they should all just use the default Helm Chart
