### ISSUE TITLE
Seeing a diff in argocd not syncing new crds

### ISSUE THREAD

**Issue by zakariais** [aws/karpenter#5116]
### Description

**Observed Behavior**:
Hi, 
When i apply new crds they always stay in out of sync state, i have also tried server side apply but it doesn't work
**Expected Behavior**:
All the news crds should be synced in argocd instead of showing out of sync.
**Reproduction Steps** (Please include YAML):
Update karpenter to latest chart, apply changes from argocd
**Versions**:
- Chart Version: 0.32.1
- Kubernetes Version (`kubectl version`):  1.24

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by zakariais** [comment]
![Uploading Screenshot 2023-11-20 at 9.51.30 AM.png…]()

**Comment by zakariais** [comment]
<img width="1413" alt="Screenshot 2023-11-20 at 9 51 30 AM" src="https://github.com/aws/karpenter/assets/114913988/4b4e4956-12e6-407f-9410-dc9a6c2d0ef4">

**Comment by jonathan-innis** [comment]
There was a similar issue that was opened here: #5062. Are you installing the CRDs using a manual process or using the managed `karpenter-crd` chart?

**Comment by zakariais** [comment]
A manual process, we copy crds to a crd folder from apis/pkg/folder and argocd picks it up.

**Comment by jonathan-innis** [comment]
> we copy crds to a crd folder from apis/pkg/folder and argocd picks it up

Got it. Is it possible that you could drop the `x-kubernetes-validation` statements on the copy-over so that argocd doesn't complain about failing to sync?

**Comment by zakariais** [comment]
it works with removing the x-kubernetes-validation
