### ISSUE TITLE
aws-node / ipamd on Karpenter nodes can't connect to the API server

### ISSUE THREAD

**Issue by jgonera** [aws/karpenter#5127]
### Description

I am not sure if this is 100% a bug or some corner case. I'm happy to provide more logs and try more things.

**Observed Behavior**:

`aws-node` pods on nodes started by Karpenter are in CrashLoopBackOff. After investigating the problem seems to be that `ipamd` can't connect to the API server (this is from `/var/log/aws-routed-eni/ipamd.log` after SSH-ing into the node in question):

```json
{"level":"info","ts":"2023-11-21T00:56:41.794Z","caller":"aws-k8s-agent/main.go:28","msg":"Starting L-IPAMD   ..."}
{"level":"info","ts":"2023-11-21T00:56:41.794Z","caller":"aws-k8s-agent/main.go:39","msg":"Testing communication with server"}
{"level":"error","ts":"2023-11-21T00:56:46.794Z","caller":"wait/wait.go:222","msg":"Unable to reach API Server, Get \"https://10.100.0.1:443/version?timeout=5s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
```

Trying to reach the API server through `curl` on a Karpenter node confirms this:

```
$ curl --insecure --connect-timeout 5 https://10.100.0.1:443/version?timeout=5s
curl: (28) Failed to connect to 10.100.0.1 port 443 after 5001 ms: Timeout was reached
```

I created a managed node group on the same cluster just to compare the behavior of the nodes and the nodes from the managed node group don't exhibit this issue:

```
$ curl --insecure --connect-timeout 5 https://10.100.0.1:443/version?timeout=5s
{
  "major": "1",
  "minor": "28+",
  "gitVersion": "v1.28.3-eks-4f4795d",
  "gitCommit": "e77944ea667aee90c84c48a74a2a0da7a23e0508",
  "gitTreeState": "clean",
  "buildDate": "2023-10-20T23:21:39Z",
  "goVersion": "go1.20.10",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Note:** If I use the public endpoint for the API server, then I can reach it from both managed and Karpenter nodes.

I'm running `coredns` on Fargate and `kube-proxy` seems to be running properly both on managed nodes, and the ones started by Karpenter. `iptables-save` seems to have the same entries on both nodes:

```
$ sudo iptables-save | grep "10.100.0.1"
-A KUBE-SERVICES -d 10.100.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SERVICES -d 10.100.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES -d 10.100.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
```

**Expected Behavior**:

`aws-node`/`ipamd` starts successfully, API server is reachable.

**Reproduction Steps** (Please include YAML):

Messy Terraform code (includes manifests for Karpenter): https://gist.github.com/jgonera/e32572712537ac5448406a5484b4694a

**Versions**:
- Chart Version: 0.32.1 and 0.31.2 (downgraded to check if it used to work, same symptoms on both versions)
- Kubernetes Version (`kubectl version`): v1.28.3-eks-4f4795d

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Can you share the nods the AMI that you are using and the userData/kubeletConfig that you are using to configure the instance?

**Comment by jgonera** [comment]
Sorry, I was giving up not knowing what could be going on and, of course, as soon as I added this issue one more idea occurred to me.

I added the Karpenter node to the security group created by AWS for the EKS cluster. I previously created a separate security group in Terraform so that I could easily add the `karpenter.sh/discovery` tag and used that group for nodes. Despite that group allowing all in+out traffic, it seems it was not enough and both the control plane and the nodes have to be in the same security group.

Finally, since I wanted everything to be created in Terraform, I added my custom security group to my `aws_eks_cluster` resource definition:

```tf
  vpc_config {
    security_group_ids = [
      aws_security_group.eks_node.id
    ]
  }
```

This added it as an additional security group for the control plane and now everything is working as expected.

**Comment by jgonera** [comment]
As a side note @jonathan-innis I think this could be mentioned in one (or both) of the getting started guides since it's a requirement that people may not know about if they come from managed nodes where the security groups are set more automatically/behind the scenes.
