### ISSUE TITLE
Helm - Add NodePool and EC2NodeClass

### ISSUE THREAD

**Issue by mtavaresmedeiros** [aws/karpenter#5135]
### Description

**What problem are you trying to solve?**
Allow specifying NodePool and Ec2NodeClass
**How important is this feature to you?**
It will simplify the installation of the karpenter with helm, allowing specifying a node pool and ec2nodeclass in the initial installation.

Ex: Install the karpenter with the terraform in a Kubernetes cluster with fargate(serverless) or another option with 0 nodes, and install the GitOps tools after it, without the need to create another resource (NodePool and Ec2NodeClass), and has all things work out-of-the-box.

If it is fine, I can do the PR. 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
We had a similar request here: #1956. We are generally recommending that users build a "top-level chart" that take this chart as a dependency elsewhere since we are generally trying to avoid the burden of having to maintain the chart ourselves. given the number of options that we would have to support.

**Comment by mtavaresmedeiros** [comment]
hum... https://github.com/aws/karpenter/pull/1956#issuecomment-1163402365, this commentary really makes sense. closing.

**Comment by younsl** [comment]
@mtavaresmedeiros In my production cluster, I am using my own [karpenter-nodepool](https://github.com/younsl/younsl.github.io/tree/main/content/charts/karpenter-nodepool) chart, integrated into the karpenter chart as a child chart.

[Subchart dependencies](https://helm.sh/docs/helm/helm_dependency/) declared in the `Chart.yaml` of the `karpenter` chart:

```bash
# charts/karpenter/Chart.yaml
dependencies:
  - name: karpenter-nodepool
    version: 0.0.7
    repository: "file://./charts/karpenter-nodepool"
    condition: karpenter-nodepool.enabled
```

Directory structure for `karpenter` chart, including `karpenter-nodepool` chart as subchart:

```bash
karpenter  # parent chart
├── Chart.lock
├── Chart.yaml
├── README.md
├── charts
│   └── karpenter-nodepool  # subchart
├── crds
├── templates
└── values.yaml
```
