### ISSUE TITLE
Karpenter provisioner's status is not showing correct values of current consumption of cpu and memory of the cluster

### ISSUE THREAD

**Issue by sasanknvs** [aws/karpenter#5139]
### Description

**Observed Behavior**:  Karpenter provisioner is not showing the correct values of the current consumption of the cluster when the deployment is scaled down. 

**Expected Behavior**: Karpneter should ideally show the correct values of the current consumption of the cluster. If the nodes are scaled down, then the consumption should be updated accordingly.

### Karpenter version V0.31.0

**Reproduction Steps** (Please include YAML):
1. Create a karpenter provisioner specifying the limit on the cpu,memory and gpu. Also specify the "TTLSecondsAfterEmpty"
2. Deploy a workload(deployment) that can be provisioned by this provisioner
3. After karpenter successfully provisioned the nodes and pods running successfully try to scale down the deployment to 0 replicas

Kubectl scale deployment <deploymentname> --replicas=0
Now the karpenter marks the corresponding nodes to empty and after "TTLSecondsAfterEmpty" seconds the nodes will be deleted.
4. Run the kubectl get provisioner <provisionername> -o yaml. 
5. Check the "status" section and examine the values of the resources "cpu", "gpu", "nvidia.com/gpu". Since all the node the provisioner has provisoned are removed, these values should be set to "0" as current consumption is "0".
6. But these values describe non-zero values which is incorrect. You can find how status section looks like in the below

### **YAML file to create the provisioner**
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: provisioner-test
spec:
  ttlSecondsAfterEmpty: 60 # scale down nodes after 60 seconds without workloads (excluding daemons)
  labels:
    workloadtype: type1
    gpuPresent: "True"
    "nvidia.com/gpu.deploy.operator-validator": "false"
  limits:
    resources:
      cpu: 32 # limit to 50 CPU cores
      memory: 1000Gi
      nvidia.com/gpu: 3
  requirements:
    # Include general purpose instance families
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [g4dn]
  providerRef:
    name: test-provider

### **STATUS OF THE PROVISIONER AFTER SCALING DOWN**
status:
  resources:
    cpu: "8"
    ephemeral-storage: 41918424Ki
    memory: 32138168Ki
    nvidia.com/gpu: "10"
    pods: "58"

**Comment by jonathan-innis** [comment]
Can you include the version of Karpenter that you are running?

**Comment by sasanknvs** [comment]
> Can you include the version of Karpenter that you are running?

Karpenter version is V0.31.0. Updated in the bug description

**Comment by jonathan-innis** [comment]
There was a bug fix for this issue in `v0.32.0`. You can see the fix for this bug here: https://github.com/kubernetes-sigs/karpenter/pull/561. There is also another report for this bug here: https://github.com/aws/karpenter/issues/4628
