### ISSUE TITLE
Configurable instanceTypeFlexibilityThreshold

### ISSUE THREAD

**Issue by tarikdem** [aws/karpenter#5140]
### Description

**What problem are you trying to solve?**

When trying to run workloads on GPU instances with specific requirements that limit the possible EC2 instances that can be used I am not able to use spot instances even though there are spot offerings available. Seems that because of `instanceTypeFlexibilityThreshold` which is hardcoded, my nodepool falls back to on-demand. I am aware that by decreasing limitations and requirements for nodepools I would be able to leverage more spot offerings, but in this case where the workloads have specific requirements I am not able to do so. Would it make sense to have this threshold configurable?

**How important is this feature to you?**

It would allow for huge cost savings when running GPU instances with interruptible workloads.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
As far as I can tell from reading through the code, it looks like this threshold shouldn't prevent you from launching those spot instances if there is capacity available. That code appears to reject a request if you originally requested spot, that request failed, and you are now falling back to use on-demand capacity with a small number of instance types.

**Comment by bwagner5** [comment]
The threshold is only informational and won't prevent the launch. It's logged to let you know that the configuration is not "safe" since running with fewer than 5 instance types with Spot can be problematic.

**Comment by tarikdem** [comment]
Seems my conclusion was a bit too hasty from briefly skimming the code.

Thanks for the clarification!
