### ISSUE TITLE
Question: How does Karpenter reference container image architecture placement decisions

### ISSUE THREAD

**Issue by shezaan** [aws/karpenter#5158]
### Description

If I only have amd64 container images in my repository, how does Karpenter know whether to place that image into an EKS node that uses graviton vs regular x86_64 platform arch?
Would there be a need to create a separate nodepool based on architecture with respective taints on them?
I have mixed workloads using both amd64 as well as arm64 workloads... hence this question about how karpenter decides on which nodes to place my pods.

**Comment by jonathan-innis** [comment]
> how does Karpenter know whether to place that image into an EKS node that uses graviton vs regular x86_64 platform arch

Karpenter discovers all the available architectures that are available to it from the EC2NodeClass's `amiSelectorTerms`. If the architecture that is specified by the launch requirements isn't available, then it won't launch a node. In your case, if a pod needed `amd64` architecture, but the `amiSelectorTerms` didn't allow that architecture based on the images that were matched, then Karpenter wouldn't be able to schedule that pod to a node using that NodePool/EC2NodeClass combination.

We still recommend that you constrain your NodePool to the architectures that you support in your images. There's a technical detail here, but the short of it is that we will discover you image requirements later (after scheduling simulation happens) than your NodePool requirements. Specifying the architecture constraint in your NodePool ensures we don't waste cycles scheduling to things that can't actually be launched.

**Comment by shezaan** [comment]
Hi @jonathan-innis thanks for your response. Forgive my ignorance, I'm still a bit unclear. My nodepool is unconstrained because I have container images that are of both architecture types i.e amd64 and arm64. I also don't have `amiSelectorTerms` specified for that reason. 

In summary, I guess what I am asking is that if I don't have `amiSelectorTerms` configured and am also not limiting my nodepool to any instance architecture with `key: kubernetes.io/arch` then will Karpenter automatically ascertain the architecture of my container image to schedule it on an EC2 instance with the correct architecture i.e graviton or amd64?

Since you determine image (I assume container image) requirements after nodepool requirements, would it be fair to say that in an unconstrained scenario as stated above and assuming that my container image is of arch arm64 the following could happen...
1. Karpenter spins up an EC2 instance of arch amd64 since nodepool requirements are evaluated first
2. Karpenter then determines that my container image arch is actually arm64 and not amd64 via the simulation you stated above.
3. Karpenter shuts down the EC2 instance of arch amd64 and brings up another EC2 instance matching the container image arch, arm64 (graviton) in this case

Does this sound right?

**Comment by jonathan-innis** [comment]
What do your pod requirements say? If your pod requirements portray the container image requirements to Karpenter, like with a nodeSelector that looks like

```yaml
nodeSelector:
  kubernetes.io/arch: arm64
```

then Karpenter should know not to start an amd64 instance for that pod even if your NodePool is unconstrained. Karpenter won't; however, introspect the container image itself to understand what the architecture is. You have to put the scheduling requirement onto the pod when you have a container image that only supports a single architecture.

**Comment by shezaan** [comment]
Thanks, you've answered my question. I thought that karpenter would introspect the image to ascertain the arch from the container image metadata or something similar before spinning up an EC2 image of the right architecture.
I think a separate nodepool for separate archs is the way I will go instead.
Thanks a million!

**Comment by Rylon** [comment]
@jonathan-innis 

We're also considering whether to deploy this with two node pool, one for each arch, or a single nodepool with both archs on it. One thing that is unclear is what would happen to existing workloads that didn't specify the below arch?

```nodeSelector:
  kubernetes.io/arch: arm64
```

Would it assume the existing workloads were `amd64` still, or is there a chance that it would launch an `arm64` node and an existing workload would get scheduled there and fail to start?

Should we create a second nodepool for `arm64` with a taint on it, just to be sure?
