### ISSUE TITLE
On-Demand/Spot Ratio Split now working (always get spot only)

### ISSUE THREAD

**Issue by xubofei1983** [aws/karpenter#5171]
### Description

**Observed Behavior**:
I have two nodepools:
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: "2808749311332697570"
    meta.helm.sh/release-name: karpenter-config
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-11-27T20:16:44Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: default-workflow-spot
  resourceVersion: "89758"
  uid: bc4fd30d-3b48-4d08-b1b7-9304005e3c76
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
    expireAfter: 720h
  limits:
    cpu: 6400
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default-workflow
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c6id.8xlarge
        - c5d.9xlarge
        - m6id.8xlarge
        - m5d.8xlarge
        - r6id.8xlarge
        - r5d.8xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: node-role.kariusdx.io/workflows
        operator: In
        values:
        - "true"
      - key: capacity-spread
        operator: In
        values:
        - "2"
        - "3"
        - "4"
        - "5"
      taints:
      - effect: NoSchedule
        key: node-role.kariusdx.io/workflows
        value: "true"
status: {}
```

and

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: "2808749311332697570"
    meta.helm.sh/release-name: karpenter-config
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-11-27T20:16:44Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: default-workflow-on-demand
  resourceVersion: "76338"
  uid: da8e0d44-cf7b-42a9-8d2f-2c38ffcdeb16
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
    expireAfter: 720h
  limits:
    cpu: 6400
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default-workflow
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c6id.8xlarge
        - c5d.9xlarge
        - m6id.8xlarge
        - m5d.8xlarge
        - r6id.8xlarge
        - r5d.8xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: node-role.kariusdx.io/workflows
        operator: In
        values:
        - "true"
      - key: capacity-spread
        operator: In
        values:
        - "1"
      taints:
      - effect: NoSchedule
        key: node-role.kariusdx.io/workflows
        value: "true"
status: {}
```

When I deploy a replica:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fallback-test-deploy
  namespace: workflow
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 30
            memory: 200Mi
      nodeSelector:
        node-role.kariusdx.io/workflows: "true"
      tolerations:
      - key: node-role.kariusdx.io/workflows
        operator: Equal
        value: "true"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: capacity-spread
          whenUnsatisfiable: DoNotSchedule
```

All nodeclaims are from spot:
NAME                          TYPE          ZONE         NODE   READY   AGE   CAPACITY   NODEPOOL                NODECLASS
default-workflow-spot-6clxj   c5d.9xlarge   us-east-1d          False   19s   spot       default-workflow-spot   default-workflow
default-workflow-spot-9q258   c5d.9xlarge   us-east-1d          False   19s   spot       default-workflow-spot   default-workflow
default-workflow-spot-brjdk   c5d.9xlarge   us-east-1d          False   19s   spot       default-workflow-spot   default-workflow
default-workflow-spot-gml8r   c5d.9xlarge   us-east-1d          False   19s   spot       default-workflow-spot   default-workflow
default-workflow-spot-kz4v6   c5d.9xlarge   us-east-1d          False   19s   spot       default-workflow-spot   default-workflow
default-workflow-spot-pv6bx   c5d.9xlarge   us-east-1d          False   19s   spot       default-workflow-spot   default-workflow
default-workflow-spot-qjjrx   c5d.9xlarge   us-east-1d          False   19s   spot       default-workflow-spot   default-workflow
default-workflow-spot-v7cjk   c5d.9xlarge   us-east-1d          False   19s   spot       default-workflow-spot   default-workflow
default-workflow-spot-wxtwl   c5d.9xlarge   us-east-1d          False   19s   spot       default-workflow-spot   default-workflow
default-workflow-spot-xhmtl   c5d.9xlarge   us-east-1d          False   19s   spot       default-workflow-spot   default-workflow

**Expected Behavior**:

it should come from 8 spots and 2 on-demand

**Reproduction Steps** (Please include YAML):

See above YAMs

**Versions**:
- Chart Version: v0.32.1
- Kubernetes Version (`kubectl version`): EKS 1.23

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xubofei1983** [comment]
Thanks!  Add some documentation would be very helpful.

**Comment by jmdeal** [comment]
Did this end up solving the issue for you? If so I can close the issue with the PR.

**Comment by xubofei1983** [comment]
Yes it works for me. Thanks.
