### ISSUE TITLE
Add Support for Nodeaffinity Key "failure-domain.beta.kubernetes.io/zone" in karpenter schedule logic.

### ISSUE THREAD

**Issue by infa-msheik** [aws/karpenter#5194]
### Description

**What problem are you trying to solve?**
We have 300 clusters and in each cluster we have around 500 PV's which has nodeaffinity Key as "failure-domain.beta.kubernetes.io/zone". 

        {
            "apiVersion": "v1",
            "kind": "PersistentVolume",
            "metadata": {
                "annotations": {
                    "kubernetes.io/createdby": "aws-ebs-dynamic-provisioner",
                    "pv.kubernetes.io/bound-by-controller": "yes",
                    "pv.kubernetes.io/migrated-to": "ebs.csi.aws.com",
                    "pv.kubernetes.io/provisioned-by": "kubernetes.io/aws-ebs"
                },
                "creationTimestamp": "2021-10-20T11:16:35Z",
                "finalizers": [
                    "kubernetes.io/pv-protection"
                ],
                "labels": {
                    "failure-domain.beta.kubernetes.io/region": "us-east-1",
                    "failure-domain.beta.kubernetes.io/zone": "us-east-1a"
                },
                "name": "pvc-0ae3077c-2abf-4178-bc49-xxxxxxxxx",
                "resourceVersion": "1023838636",
                "uid": "1905b103-8208-4bee-ad89-4351be15d6d3"
            },
            "spec": {
                "accessModes": [
                    "ReadWriteOnce"
                ],
                "awsElasticBlockStore": {
                    "fsType": "ext4",
                    "volumeID": "aws://us-east-1a/vol-XXXXXXXXXXX"
                },
                "capacity": {
                    "storage": "1Gi"
                },
                "claimRef": {
                    "apiVersion": "v1",
                    "kind": "PersistentVolumeClaim",
                    "name": "XX-service-cert-pvc",
                    "namespace": "infrastructure-qXX-XXX-service",
                    "resourceVersion": "539457602",
                    "uid": "0ae3077c-2abf-4178-bc49-dbc136632e6a"
                },
                "mountOptions": [
                    "debug"
                ],
                "nodeAffinity": {
                    "required": {
                        "nodeSelectorTerms": [
                            {
                                "matchExpressions": [
                                    {
                                        "key": "failure-domain.beta.kubernetes.io/zone",
                                        "operator": "In",
                                        "values": [
                                            "us-east-1a"
                                        ]
                                    },
                                    {
                                        "key": "failure-domain.beta.kubernetes.io/region",
                                        "operator": "In",
                                        "values": [
                                            "us-east-1"
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                },
                "persistentVolumeReclaimPolicy": "Delete",
                "storageClassName": "mailwrapper",
                "volumeMode": "Filesystem"
            },
            "status": {
                "phase": "Bound"
            }
        },

As per docs https://karpenter.sh/docs/concepts/scheduling/#persistent-volume-topology supported nodeaffinity key are "topology.ebs.csi.aws.com/zone" and "topology.kubernetes.io/zone"

This nodeaffinity section of PV's is Immutable so we cant change the key now. only way is to recreate the PV's which will cause Data loss for us.  Can you please add this nodeaffinity key "failure-domain.beta.kubernetes.io/zone" in your code so that karpenter can launch the nodes in the correct AZ as PV volume.

**How important is this feature to you?**
Without this we can not deploy karpenter in our Orgazination.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
Karpenter does support `failure-domain.beta.kubernetes.io/zone`, this is a docs miss. It translates it internally to `topology.kubernetes.io/zone`. I can cut a PR to update the docs.
