### ISSUE TITLE
Add utilization target for consolidationPolicy: WhenUnderutilized

### ISSUE THREAD

**Issue by makarov-roman** [aws/karpenter#5218]
### Description

**What problem are you trying to solve?**
On our non-prod clusters I want to have at least 70% match between provided resources and requests.
CA alternative would be `scale-down-utilization-threshold: 0.7`

**How important is this feature to you?**
I would say - important, because right now CA consolidates instances better.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by makarov-roman** [comment]
Hi @ellistarn,
thanks for the quick response.

I see the utilization threshold as a balance between stability and costs. E.g. if we urgently need to scale up some HPA it's good to have some free space already.

Anyway, I going to do some more test and will reopen the issue once I have more precise scenarios.

**Comment by bzcnsh** [comment]
How is that "cost" calculated? Is it based off of all the pods' utilized resource, or requested resource, or something else?
@ellistarn
