### ISSUE TITLE
script to pull go api generated doc into hugo

### ISSUE THREAD

**Issue by geoffcline** [aws/karpenter#532]
The process for getting the output of `gen-crd-api-reference-docs` (auto generated API docs) into the hugo site should be automated.

**Comment by geoffcline** [comment]
```
codegen: ## Generate code. Must be run if changes are made to ./pkg/apis/...
        ...
	gen-crd-api-reference-docs \
		-api-dir ./pkg/apis/provisioning/v1alpha3 \
		-config $(shell go env GOMODCACHE)/github.com/ahmetb/gen-crd-api-reference-docs@v0.3.0/example-config.json \
		-out-file website/content/en/docs/Reference/code-gen.txt \
		-template-dir $(shell go env GOMODCACHE)/github.com/ahmetb/gen-crd-api-reference-docs@v0.3.0/template
	cat <(cat website/content/en/docs/Reference/api-docs-header.txt) \
		website/content/en/docs/Reference/code-gen.txt \
		> website/content/en/docs/Reference/_index.md
```

**Comment by akestner** [comment]
Can you please make sure to use one of the Issue templates so that we can make sure all the necessary info is captured? From what I can tell here, this isn't a documentation issue, but one related to developing Karpenter

**Comment by geoffcline** [comment]
I think it's both hacking and docs. It's about automating updating some docs content, based on the generated API doc.
