### ISSUE TITLE
document configuration for smaller instances, less pods per node

### ISSUE THREAD

**Issue by geoffcline** [aws/karpenter#562]
Some users may prefer smaller instances, or more "spread" of pods between nodes/zones.

What is the preferred way to implement this?

Some options:
- restrict instance types to smaller instances
- tains?
- topology spread? do we support this?

**Comment by geoffcline** [comment]
topology spread is a 0.4 feature #268

**Comment by ellistarn** [comment]
I'd probably achieve this by constraining the set of instance types to smaller instances. Another way to achieve this indirectly is, as you mention using topology spread. Topology spread over AZ might be a more direct fit for the HA use case than smaller nodes.

**Comment by geoffcline** [comment]
closed by #1237
