### ISSUE TITLE
revise AWS cloud provider page, including constraints

### ISSUE THREAD

**Issue by geoffcline** [aws/karpenter#589]
The page should separate the constraints into intuitive categories. 

The page should include a table that summarizes the constraints, including describing the defaults and specification options.

**Comment by geoffcline** [comment]
from @ellistarn re: table

## Kubernetes Well Known Labels
| Constraint       | Global Default           | Provisioner Default    | Pod NodeSelector                   |
| ---------------- | ------------------------ | ---------------------- | ---------------------------------- |
| Instance Type    | All EC2 Instance Types   | `spec.instanceTypes`   | `node.kubernetes.io/instance-type` |
| Zone             | All EC2 Zones w/ Subnets | `spec.zones`           | `topology.kubernetes.io/zone`      |
| Architecture     | `amd64`                  | `spec.architecture`    | `topology.kubernetes.io/zone`      |
| Operating System | Cloud Provider Specific  | `spec.operatingSystem` | `topology.kubernetes.io/zone`      |
## AWS Specific
| Constraint     | Global Default           | Provisioner Default  | Pod NodeSelector                   |
| -------------- | ------------------------ | -------------------- | ---------------------------------- |
| Security Group | All EC2 Instance Types   | `spec.instanceTypes` | `node.kubernetes.io/instance-type` |
| Subnet         | All EC2 Zones w/ Subnets | `spec.zones`         | `topology.kubernetes.io/zone`      |
| LaunchTemplate | Cloud Provider Specific  | `spec.zones`         | `topology.kubernetes.io/zone`      |
|                | Cloud Provider Specific  | `spec.zones`         | `topology.kubernetes.io/zone`      |

**Comment by eptiger** [comment]
BTW, I'm removing OS as part of https://github.com/awslabs/karpenter/pull/780
