### ISSUE TITLE
revise getting started with paths for fargate, managed node groups, etc. 

### ISSUE THREAD

**Issue by geoffcline** [aws/karpenter#591]
The getting started guide should demonstrate multiple options for hosting karpenter itself. For example, running karpenter in a managed node group or using a fargate profile.

**Comment by geoffcline** [comment]
include paths such as

- cfn
- eksctl
- cdk (punt to future?)
- run karpenter on mng
- run karpenter on fargate

**Comment by chrisnegus** [comment]
Limiting the number of getting started experiences for the moment.
