### ISSUE TITLE
Document best practices for Resource Requests

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#607]
## Is an existing page relevant?
No.

## What karpenter features are relevant?
Provisioning

## How should the docs be improved?
We need to document that we expect pods to have resource requests defined. For pods missing these, this can be configured globally per namespace using https://kubernetes.io/docs/concepts/policy/limit-range/.

Community Note
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by geoffcline** [comment]
Making a note to document LimitRanges best practices https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/ to ensure that karpenter works well with pods that are missing resource requests?

**Comment by chrisnegus** [comment]
I added some [troubleshooting content on LimitRanges](https://karpenter.sh/preview/troubleshooting/#unspecified-resource-requests-cause-schedulingbin-pack-failures) in [PR #1597](https://github.com/aws/karpenter/pull/1597). While this describes the problem, it does not provide guidance on exactly how to set LimitRange values. So I think we should keep this issue open and look for a place to address that.
