### ISSUE TITLE
Emit Metrics for Karpenter

### ISSUE THREAD

**Issue by vinayan3** [aws/karpenter#612]
**Tell us about your request**
What do you want us to build?
Emit metrics in prometheus format for Karpenter. The follow metrics would be great and are mainly suggestions on what operationally I've found useful to monitor the open source clusuter autoscaler. Therefore some of the metrics below may be less applicable to Karpenter but this gives a sense of what is useful to monitor

Metric Name | Metric Type | Labels | Description
------------ | -------------  | ------------ | ------------ |
reconcile_duration_ms | Histogram | N/A| How long the reconcile loop takes where it's looking at the unscheduled pods
nodes_added | Gauge | node_type | Number of nodes that were created for a certain type
node_creation_duration_ms | Histogram | provisioner_name | How long it takes from creating a fleet request to having a node being created
node_creation_failures | Gauge | provisioner_name, reason | Number of failures to get capacity and an indication of reason
nodes_marked_for_deletion | Gauge | provisioner_name | Number of nodes that are marked for deletion
nodes_deleted | Gauge | provisioner_name | Number of nodes that were deleted
spot_fleet_calls | Counter | path, method | Number of calls made; there maybe times when no response every comes so knowing a request was sent is very useful
spot_fleet_calls_duration_ms | Histogram | path, method, status_code | create/delete/get calls
ec2_calls | Counter | method | Number of calls made
ec2_calls_response_duration_ms | Histogram | path, method, status_code | create/delete/get calls
kube_api_calls | Counter | path, method | Calls made to the Kube API
kube_api_response_duration_ms | path, method, status_code  | create/delete/get calls

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Having metrics emitted by Karpenter will allow someone to observe what Karpenter is doing. It's important to understand what actions is taking or external resources Karpenter is accessing. 

**Are you currently working around this issue?**
There isn't really a work around.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tsunamishaun** [comment]
@ellistarn @bwagner5 Here's the upstream [grafana dashboard](https://grafana.com/grafana/dashboards/3831) for cluster-autoscaler (per working group)

**Comment by aldredb** [comment]
@cjerad Suggest that `node_creation_failures` should be for any reason, not just  **Number of spot fleet request fails to get capacity**. the **reason** can be a dimension/label of the metric

**Comment by cjerad** [comment]
@aldredb Thanks for the suggestion.  The description in the table at the top has been updated.

**Comment by ellistarn** [comment]
Check out https://karpenter.sh/preview/tasks/metrics/!

**Comment by ellistarn** [comment]
Please let us know if there's more metrics you're interested in.
