### ISSUE TITLE
"Getting Started" Screencast

### ISSUE THREAD

**Issue by eptiger** [aws/karpenter#635]
**Tell us about your request**
The Getting Started guide is great, but customers used to Cluster Autoscaler may expect a lot of effort to onboard. I was talking to Brandon and we agree that a screencast front and center can visualize how quick and easy Karpenter is to set up versus the wall of text of the Getting Started guide.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Trying to improve Karpenter adoption.

**Are you currently working around this issue?**
N/A

**Additional context**
No

**Attachments**
N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rothgar** [comment]
We have a demo video in containers from the couch YouTube. Would that be enough or do you think a focused video of creating a cluster, deploying karpenter, deploying workloads would be better?

**Comment by ellistarn** [comment]
We've got a bunch of talks posted now.
