### ISSUE TITLE
Native Support for Spot Termination

### ISSUE THREAD

**Issue by bwagner5** [aws/karpenter#702]
**Tell us about your request**
 - Native Support for Spot Termination

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
How are you currently solving this problem?
Using aws-node-termination-handler up to this point (https://github.com/awslabs/karpenter/issues/105)

**Additional context**
 - This will be an aws specific spot termination controller.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
If we're using something like CapacityOptimizedAllocationStrategy, we might be able to simply rely on fleet to not give us an instance in the same pool. In this sense, we can make karpenter unaware of the details and just let ec2 do the decision making.

**Comment by eptiger** [comment]
I think it will be easier for us to talk about this in a call, but that's not how the CO strategy works. You can maybe use CO prioritized and set that pool at a low priority, but otherwise there's no reason for it to avoid that pool. If all the pools you provide to the CO strategy are constrained, it will give you the least constrained pool, which _may_ be the pool the instance that received the rebalance recommendation was in.

**Comment by pedroparraortega** [comment]
are there any plans to support this?

**Comment by bwagner5** [comment]
Yes, we are working on this functionality currently

**Comment by sqerison** [comment]
Looking forward to seeing this feature implemented. It will save tons of IPs for our cluster.

**Comment by aavileli** [comment]
please update karpentar documentation that users need to use NTH(with Queue Processor) for aws api termination for spot and on-demnad instances

**Comment by BryanStenson-okta** [comment]
Is "spot termination" for this issue restricted to spot instances?  Does this issue's scope include termination of non-spot instances (for underlying hardware maintenance by AWS, for example)?

**Comment by bwagner5** [comment]
> Is "spot termination" for this issue restricted to spot instances? Does this issue's scope include termination of non-spot instances (for underlying hardware maintenance by AWS, for example)?

Yes, it does include support for AWS Health events as well, similar to the aws-node-termination-handler.
