### ISSUE TITLE
Consider building container images for pre-releases

### ISSUE THREAD

**Issue by trondhindenes** [aws/karpenter#708]
**Tell us about your request**
I'm very interested in some alpha features, but I'd still like to not have to build/store copies of the Karpenter image. Would it be possible for you to build alpha images as well, so that folks could manually override the `image` value in the Helm chart if they want to test bleeding edge stuff? The list of tags is already available at https://gallery.ecr.aws/karpenter/controller so there's no need to create github tags or anything, I'd just like to have alpha/beta bits easily accessible for testing

**Comment by tzneal** [comment]
We build nightlies and snapshots for every commit now.  You can find these at https://gallery.ecr.aws/karpenter/karpenter along with instructions on using them.
