### ISSUE TITLE
Karpenter Dashboard Docs

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#727]
**Tell us about your request**
What do you want us to build?

- Add loki stack setup as optional step to getting started guide or developer guide
- include grafana dashboards in karpenter chart (rather than separate chart)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Hronom** [comment]
For those who a looking they are here https://github.com/aws/karpenter/tree/main/website/content/en/preview/getting-started/getting-started-with-karpenter

Ideally if Karpenter team can put them here https://grafana.com/grafana/dashboards/
