### ISSUE TITLE
Helm Chart Wishlist

### ISSUE THREAD

**Issue by stevehipwell** [aws/karpenter#781]
**Tell us about your request**
I'd like Karpenter to have an idiomatic Helm chart with all of the components in the correct place and the standard integration points available.

I'd also like to see the chart published to [aws/eks-charts](https://github.com/aws/eks-charts).

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'd like to install Karpenter but the current Helm chart doesn't have the right configuration exposed and the CRD is directly in the chart.

**Are you currently working around this issue?**
n/a

**Additional context**
I'd be more than happy to open a PR to update the chart.

**Attachments**
n/a

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Hey Steve,
We're definitely interested in expanding our helm chart's capabilities. So far, we've expanded functionality on an as needed basis. I'm not sure what you mean by 
> components in the correct place and the standard integration points available.

Is there any thing you had in mind? Contributions are absolutely welcome.

I'm not sure about the move to aws/eks-charts. Not all AWS charts live there, and it's becoming a bit of a monolith to maintain. Serving the karpenter chart from here helps keep everything nicely in sync with our release process. I'm open minded to proposals for alternatives.

**Comment by stevehipwell** [comment]
@ellistarn the chart doesn't follow idiomatic Helm patterns, but the big issue is having a CRD inside the chart. CRDs should be inside the special _./crds_ folder so they can (and should) be ignored via the `helm upgrade --install --skip-crds`.

Regarding the aws/eks-charts repo, it's a good discovery point. If it's becoming a monolith to maintain that's a problem with the process not something inherent to a central repo; I like the current release push model for things like the NTH chart but the actual chart release could be made independent to a repo tag.

**Comment by ellistarn** [comment]
Are you able to swing by our [working group](https://github.com/awslabs/karpenter/blob/main/WORKING_GROUP.md) to discuss eks-charts?

It should be straightforward to point our CRD codegen to ./charts/karpenter/crds

**Comment by stevehipwell** [comment]
@ellistarn I'll try and join next week.

**Comment by ellistarn** [comment]
This is now in. Please reopen (or a new issue) if there are more features you'd like added to the chart,
