### ISSUE TITLE
Doc Request: Karpenter Analog to Priority Expander

### ISSUE THREAD

**Issue by eptiger** [aws/karpenter#897]
**Tell us about your request**
There was some user confusion around how to set up priority expanders in Karpenter like they have with Cluster Autoscaler. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
One such use case is wanting to use the on-demand capacity type instead of Spot if there's some failure to scale out on Spot. 

You can achieve this with Karpenter using a single Provisioner that has an appropriate level of flexibility in combination with node affinity rules. For this particular example: a Provisioner that's flexible to both spot and on-demand and specifying a node affinity rule that prefers spot. If spot scale out fails, Karpenter would then retry with on-demand within milliseconds of failure.

**Are you currently working around this issue?**
N/A

**Additional context**
No

**Attachments**
None

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by geoffcline** [comment]
<3 <3 thank you for opening this issue

**Comment by abierbaum** [comment]
@eptiger Any pointers to an example provisioner that supports the example you gave above?  In particular I don't quite see how to set a node affinity rule that prefers spot instances.

**Comment by gohmc** [comment]
@eptiger , according to #893, is this the same thing to what you raised or you have another method using node affinity?

```
requirements:
- key: "karpenter.sh/capacity-type"
  operator: In
  values: ["spot", "on-demand"]
```
