### ISSUE TITLE
[Logging] Only log on discovery cache if something has changed.

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#898]
**Tell us about your request**
Reduce discovery logging to only log a line when something is detected to have changed, rather than when it's refreshed. It may be useful to build a new discovery cache abstraction that wraps cache.cache.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
If Karpenter is idle, it spits out
```
karpenter-controller-57447f86fb-9svdv manager 2021-12-02T20:30:25.285Z	DEBUG	controller.provisioning	Discovered EC2 instance types zonal offerings	{"commit": "1f5c498", "provisioner": "default"}
karpenter-controller-57447f86fb-9svdv manager 2021-12-02T20:35:25.474Z	DEBUG	controller.provisioning	Discovered EC2 instance types zonal offerings	{"commit": "1f5c498", "provisioner": "default"}
karpenter-controller-57447f86fb-9svdv manager 2021-12-02T20:40:25.669Z	DEBUG	controller.provisioning	Discovered EC2 instance types zonal offerings	{"commit": "1f5c498", "provisioner": "default"}
karpenter-controller-57447f86fb-9svdv manager 2021-12-02T20:45:25.864Z	DEBUG	controller.provisioning	Discovered EC2 instance types zonal offerings	{"commit": "1f5c498", "provisioner": "default"}
karpenter-controller-57447f86fb-9svdv manager 2021-12-02T20:50:26.051Z	DEBUG	controller.provisioning	Discovered EC2 instance types zonal offerings	{"commit": "1f5c498", "provisioner": "default"}
karpenter-controller-57447f86fb-9svdv manager 2021-12-02T20:55:26.248Z	DEBUG	controller.provisioning	Discovered EC2 instance types zonal offerings	{"commit": "1f5c498", "provisioner": "default"}
karpenter-controller-57447f86fb-9svdv manager 2021-12-02T21:00:26.430Z	DEBUG	controller.provisioning	Discovered EC2 instance types zonal offerings	{"commit": "1f5c498", "provisioner": "default"}
karpenter-controller-57447f86fb-9svdv manager 2021-12-02T21:05:26.889Z	DEBUG	controller.provisioning	Discovered EC2 instance types zonal offerings	{"commit": "1f5c498", "provisioner": "default"}
karpenter-controller-57447f86fb-9svdv manager 2021-12-02T21:10:27.085Z	DEBUG	controller.provisioning	Discovered EC2 instance types zonal offerings	{"commit": "1f5c498", "provisioner": "default"}
```

**Are you currently working around this issue?**
Sadness

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Fixed by #2334
