### ISSUE TITLE
Doc Request: AWS Cloud Provider Offering Caching

### ISSUE THREAD

**Issue by eptiger** [aws/karpenter#900]
**Tell us about your request**
Amend the documentation for the AWS cloud provider to talk about offering caching.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The issue is that a customer receives an insufficient capacity error for all the instance types attempted in trying to fulfill a set of bin packed pods. To address this, Karpenter caches these errors and will avoid those combinations of capacity type and availability zone (an "offering") for those instance types for a set period of time (currently, 45 seconds - not user configurable). This allows Karpenter to attempt a bin packing on its next reconciliation attempt that doesn't utilize such offerings, i.e. it removes those offerings from consideration by the bin packer so that it knows that it can't bin pack into those shapes/zones. This means that it could split up a large packing into multiple smaller ones in order to launch on smaller instance sizes, or launch in a different AZ from that which is preferred by node affinity, or (in our next release) try a different capacity type. Even if a node is successfully launched, Karpenter will look at the errors from Fleet to see what offerings were attempted but hit an insufficient capacity error and will cache those to optimize future bin packings (for the ensuing 45 seconds, at least).

Not sure if there's a current page this fits in, may need to create a new sub-node under "AWS". Also, we should consider adding "offerings" to our Concepts page as it's part of the InstanceType interface available to all cloud providers (though the caching is specific to the AWS cloud provider for right now). Basically, an instance type has an array of offerings (combination of capacity type and zone) that represent the availability of an instance type (generated from the cloud provider's own API), for use by the bin packer. That being said, general users wouldn't need to be aware of what an offering is aside from in relation to understanding this caching logic or contributing code (i.e. there's no labels or anything using the "offering" vernacular).

**Are you currently working around this issue?**
N/A

**Additional context**
The PR for the capacity type fallback: https://github.com/aws/karpenter/pull/893/files

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by billrayburn** [comment]
Closing because issue is old, please reopen if you feel this is still an issue.
