### ISSUE TITLE
Set default instance profile

### ISSUE THREAD

**Issue by mikesir87** [aws/karpenter#909]
**Tell us about your request**
I would like to have the ability to set a default instance profile, making it optional when defining Provisioner objects.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When we deploy Karpenter using our pipeline, we use TF to create the dependencies (IAM roles, instance profile, etc.) and deploy Karpenter using a `helm_release` resource. It would be nice if I could pass in the created instance profile as an argument to make it the default profile. This will prevent the sharing of a magic/well-known name with our separate Helm chart that configures all of our tenant resources (has no access to this pipeline and its outputs).

**Are you currently working around this issue?**
Simply sharing the name of the profile and hoping for the best! 😆 

**Additional context**
I do recognize that this is a provider specific field, but do see other env vars that are being passed in that are provider specific. So, I don't feel it'll muddy the waters too much asking for this in that regard.

**Attachments**
None

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
I'm completely supportive of this idea. We recently moved `clusterName` and `clusterEndpoint` from a CRD field to a binary flag. It should be straightforward to wire it up here: https://github.com/aws/karpenter/blob/a859cad1e3b3c5cc916f69bb2435198a3cd0af13/pkg/utils/options/options.go#L29. 

We still need to have the ability to override InstanceProfile at the CRD level as there are use cases for running nodes with different roles in different provisioners. However, we can make this an optional field.

Is this something you'd be able to contribute?

**Comment by mikesir87** [comment]
Awesome! And yeah... makes sense to allow overrides at the CRD level as well.

I'll gladly contribute it. Just wanted to get the go-ahead before jumping in. I'll see if I can send something your way here soon!
