### ISSUE TITLE
Explore Github's new Automated Release feature

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#913]
**Tell us about your request**
https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by geoffcline** [comment]
I'm unclear on the action item here. is it regarding [auto generated *release notes*](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)? or adding docs versioning to an automated karpenter release project?

**Comment by tzneal** [comment]
The are hooked up into the release process now.

**Comment by ellistarn** [comment]
We're currently using an action, but GH has first party support for this now.
