### ISSUE TITLE
Volume Limits as an InstanceType property

### ISSUE THREAD

**Issue by hobti01** [aws/karpenter#919]
**Tell us about your request**
The current state of [InstanceType](https://github.com/aws/karpenter/blob/c3b37d99bdfa84ed5fc28c544d5f02d640b3f70c/pkg/cloudprovider/aws/instancetype.go) accommodates CPU, Memory, Pods and some specific resources.  However, it does not seem to account for [Instance volume limits](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_limits.html).

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We find that volume limits are typically overlooked or mishandled as a scarce resource by all existing schedulers and cluster scalers.  We have some applications that mount multiple PVCs to a single Pod and this causes problems for schedulers that do not account for the Instance volume attachment limits.

[AWS has low volume attachment limits compared to other cloud providers](https://kubernetes.io/docs/concepts/storage/storage-limits/#dynamic-volume-limits) and this causes significant over-provisioning of CPU/Memory in order to accommodate volume attachment constraints.

According to https://github.com/kubernetes/kubernetes/issues/80967#issuecomment-621447246 this could be considered an ENI resource constraint in AWS, but the [current calculation](https://github.com/aws/karpenter/blob/c3b37d99bdfa84ed5fc28c544d5f02d640b3f70c/pkg/cloudprovider/aws/instancetype.go#L70) only considers ENI resource to be a Pod constraint

**Are you currently working around this issue?**
We had been using `KUBE_MAX_PD_VOLS` until Kubernetes 1.17 to artificially lower the limits.  With CSI drivers the volume limits are accounted in the Kubernetes scheduler, and therefore cluster-autoscaler - which we are using to workaround this issue.

**Additional context**
It's great to see a new attempt at cluster autoscaling and we're looking forward to seeing if the complexity can be managed while handling the use cases.  We're also curious to see the uptake for cloud providers other than AWS.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by hobti01** [comment]
I have also struggled to get a clear explanation of this.

From the link I posted above:
> If a CSI storage driver advertises a maximum number of volumes for a Node (using NodeGetInfo), the kube-scheduler honors that limit. Refer to the CSI specifications for details.
which links to https://github.com/container-storage-interface/spec/blob/master/spec.md#nodegetinfo

- Before Dynamic Volume Limits there were discussions like this: https://github.com/kubernetes/kubernetes/issues/80967 because there was no capability for dynamic volume limits.

Unfortunately I'm not familiar with the kube-scheduler code to tell you where or how `NodeGetInfo` is used for scheduling.

**Comment by ellistarn** [comment]
> If a CSI storage driver advertises a maximum number of volumes for a Node (using NodeGetInfo), the kube-scheduler honors that limit. Refer to the CSI specifications for details.
> which links to https://github.com/container-storage-interface/spec/blob/master/spec.md#nodegetinfo

Ah -- I think I can understand this. I think this simply means that the node object has a number of volumes in it.

Here's an example of one of my nodes
```
  status:
    allocatable:
      attachable-volumes-aws-ebs: "25"
      cpu: 7910m
      ephemeral-storage: "76224326324"
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 31507104Ki
      pods: "58"
    capacity:
      attachable-volumes-aws-ebs: "25"
      cpu: "8"
      ephemeral-storage: 83873772Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 32523936Ki
      pods: "58"
```

Karpenter can know this value beforehand by knowing about the EBS driver. It should be straight forward to look into the pod's volume claims and check if it's an ebs volume, and then compare against known values for attachable volumes per instance type.

**Comment by hobti01** [comment]
While it's accurate that `status.allocatable` shows the maximum volumes allocatable and `status.capacity` shows the node capacity, it is not reduced when volumes are attached.

From a node in one of our EKS clusters with 22 volumes attached with the EBS CSI driver:
```
$ kg node ip-10-42-10-123.eu-central-1.compute.internal -o json | jq '.status.allocatable."attachable-volumes-aws-ebs"'
"25"
$ kg node ip-10-42-10-123.eu-central-1.compute.internal -o json | jq '.status.volumesAttached | length'
22
```
It looks to me like karpenter should perform the `allocatable - attached` calculation to determine `available-volumes-aws-ebs` for existing nodes. When sizing new nodes the allocatable value can be used directly.

Probably there is some maintenance based on different volume types and the property names used for attachment.
Azure AKS cluster has a different property name, for example:
```
$ kg node aks-default-19695776-vmss00000z -o json | jq '.status.allocatable."attachable-volumes-azure-disk"'
"8"
$ kg node aks-default-19695776-vmss00000z -o json | jq '.status.volumesAttached | length'
5
```

**Comment by ellistarn** [comment]
Karpenter doesn't schedule pods to existing nodes. We allow the kube scheduler to do this -- so this should work fine. It's fairly straight forward to do these computations similar to ones for existing resources here: https://github.com/aws/karpenter/blob/main/pkg/controllers/provisioning/binpacking/packable.go#L31

**Comment by hobti01** [comment]
Thanks for the clarification, I did in fact mean to include both use cases of binpacking and node provisioning.

**Comment by diranged** [comment]
Any thoughts on this issue?
