### ISSUE TITLE
Ability to specify amiFamily

### ISSUE THREAD

**Issue by aldredb** [aws/karpenter#923]
**Tell us about your request**
In `eksctl` **managedNodeGroup** definition, we can specify the **amiFamily** as **Bottlerocket** or **AmazonLinux2** . For Bottlerocket, there is even a section to in `eksctl` to specify customizations. Request to add similar feature in Karpenter

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
WIthout specifying any launch template, Karpenter will default to Amazon Linux 2. Customers are increasingly adopting Bottlerocket. Having to maintain custom launch templates just to run another AMI family increases barrier to entry.

**Are you currently working around this issue?**
Custom launch templates

**Additional context**
N/A

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by inductor** [comment]
Now that Bottlerocket does not necessarily require LaunchTemplate to bootstrap as part of EKS cluster, so I think this should be possible.

**Comment by lucasreed** [comment]
👍  Would love to see this as an option instead of maintaining a separate LaunchConfiguration.

**Comment by rayterrill** [comment]
We'd like to see this as well - our default is Bottlerocket today. Would love to just specify the AMI family and let Karpenter grab the latest AMI if possible.
