### ISSUE TITLE
Add Terraform Section to Getting Started Guide

### ISSUE THREAD

**Issue by eptiger** [aws/karpenter#926]
**Tell us about your request**
A tutorial on using Terraform with Karpenter

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The getting started guide is Cloudformation based, but there are users who use Terraform struggling to set up their cluster correctly. Some examples here: https://www.reddit.com/r/kubernetes/comments/r9kwxs/karpenter_vs_cluster_autoscaler/

**Are you currently working around this issue?**
N/A

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mikesir87** [comment]
I, too, ran into this. We were able to get it deployed, so I wrote a quick blog post to help out (linked below). I'll gladly fold it into the docs, but I think things are evolving rapidly right now and it might take some thought on how to do it right. Feedback from the team welcome!

https://blog.mikesir87.io/2021/12/deploying-karpenter-with-tf/

**Comment by ellistarn** [comment]
@mikesir87, how do you feel about adding this to the Karpenter docs? We should be able to keep it up to date.

**Comment by mikesir87** [comment]
I can certainly do that! You think a separate page? I could do an entire "Getting Started using Terraform" that bootstraps a cluster and does the setup, similar to how you do the CF-based one. Thoughts?

**Comment by akestner** [comment]
Do it, sounds great!

**Comment by bdwyertech** [comment]
An example of how to deploy a provisioner with the kubernetes_manifest resource would also be welcomed.  I tried unsuccessfully.

**Comment by mikesir87** [comment]
I’m working on docs and was in the middle of testing them when I was hit with the AWS outage/issues today. Hopefully, I’ll be able to get them finalized tomorrow. Might be a fun thing to try that Provsioner as a TF resource (I was currently only going up to the helm_release).

**Comment by bdwyertech** [comment]
Cool!  Well here is scrubbed working example (minus the `kubernetes_manifest` which I could not get to work)

```terraform
resource "helm_release" "karpenter" {
  name       = "karpenter"
  repository = "https://charts.karpenter.sh"
  chart      = "karpenter"
  version    = "0.5.1"
  namespace  = "kube-system"

  set {
    name  = "controller.clusterName"
    value = data.aws_eks_cluster.cluster.id
  }

  set {
    name  = "controller.clusterEndpoint"
    value = data.aws_eks_cluster.cluster.endpoint
  }

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = module.karpenter_iam_role.iam_role_arn
  }
}

data "aws_iam_policy_document" "karpenter_policy" {
  statement {
    effect = "Allow"
    actions = [
      # Write Operations
      "ec2:CreateLaunchTemplate",
      "ec2:CreateFleet",
      "ec2:RunInstances",
      "ec2:CreateTags",
      "iam:PassRole",
      # Read Operations
      "ec2:DescribeLaunchTemplates",
      "ec2:DescribeInstances",
      "ec2:DescribeSecurityGroups",
      "ec2:DescribeSubnets",
      "ec2:DescribeInstanceTypes",
      "ec2:DescribeInstanceTypeOfferings",
      "ec2:DescribeAvailabilityZones",
      "ssm:GetParameter",
    ]

    resources = ["*"]
  }

  statement {
    effect = "Allow"
    actions = [
      "ec2:TerminateInstances",
    ]

    # Ensure karpenter.sh/provisioner Tag Exists
    condition {
      test     = "Null"
      variable = "ec2:ResourceTag/karpenter.sh/provisioner"
      values   = ["false"]
    }
  }
}

resource "aws_iam_role_policy" "karpenter" {
  name   = "karpenter"
  role   = module.karpenter_iam_role.iam_role_name
  policy = data.aws_iam_policy_document.karpenter_policy.json
}

module "karpenter_iam_role" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc"
  version = "4.2.0"

  create_role           = true
  force_detach_policies = true

  role_name_prefix              = "karpenter"
  provider_url                  = trimprefix(module.cluster.cluster_oidc_issuer_url, "https://")
  oidc_fully_qualified_subjects = ["system:serviceaccount:kube-system:karpenter"]
  role_permissions_boundary_arn = module.my_account.permissions_boundary_arn
}
```
