### ISSUE TITLE
Karpenter creates Node objects with the wrong name

### ISSUE THREAD

**Issue by olemarkus** [aws/karpenter#927]
## Version

**Karpenter**: v0.51.1

**Kubernetes**: v1.23.0-rc.1

## Expected Behavior
Karpenter creates node objects with the correct node name (e.g i-0df38da50804be2c0 )

## Actual Behavior
Karpeneter always create objects using the private DNS name of instances (e.g ip-172-20-122-63.eu-central-1.compute.internal)

## Steps to Reproduce the Problem
* Launch a cluster using external AWS Cloud Controller Manager master branch
* Ensure Resource Based Names is used
* Do not set `--hostname-override` on the kubelet, letting it default to `os.hostname`

Karpenter will then assume the node name is ip-x-x-x-x.<region>.compute.internal, but the actual node name will be i-xxxxxxx

Note that the node names should not be FQDN, only the hostname.
This change was implemented in cloud-provider-AWS to support things like IPv6-native subnets and will be a part of CCM 1.23.

I am not sure how Karpenter should know the correct Node name up front. The easiest implementation would probably be a CLI flag on the controller.

**Comment by ellistarn** [comment]
This is a great callout -- it looks like Karpenter doesn't work on 1.23. I *love* that the new node names are simply the node id. This allows us to remove an additional describe instance call that's [irked me](https://github.com/aws/karpenter/blob/main/pkg/cloudprovider/aws/instance.go#L225). 

It should be straight forward to implement a check on the kubernetes version and implement the different behavior. Are you interested in taking this on?

**Comment by olemarkus** [comment]
I can if we can require external CCM to be used for 1.23 clusters. If not, we don't know the convention based on version alone. The in-tree CCM will not get this feature.

**Comment by ellistarn** [comment]
This gets very tricky. There are many ways to deploy Karpenter. I'm willing to be a bit opinionated w/ the aws cloud provider if we can at least cover major providers (eks, kops, etc). Given that the out-of-tree aws provider is the future, we will need to be fully on it at some point, the question is when.

**Comment by olemarkus** [comment]
For IPv6-based clusters, external CCM is required. And kOps will only support external CCM as of 1.24 for AWS.
I suspect adoption will be quite high already from kOps 1.23.

But yes, the trickiness of this is why I suggested having a CLI flag or similar for determining the naming convention.
