### ISSUE TITLE
Pod assign loop too short for micro instances

### ISSUE THREAD

**Issue by mikesir87** [aws/karpenter#930]
## Version

**Karpenter**: v0.5.1

**Kubernetes**: v1.21

## Expected Behavior
I just had a situation in which I deployed a Provisioner with no instance type requirements, letting it choose from all of them. When deploying my first pod, a t3a.micro instance was launched. Cool! I expected the pod to be assigned to the node, it eventually start up and join the cluster, and the pod start.

## Actual Behavior
About a minute after the instance is launched and the pod is assigned to the node, a new node is launched and the pod is assigned to the new node. Since t3a.micro instances are small and very low-powered, they take 70-90 seconds to boot, join the cluster, and be ready for workloads. So, what ended up happening is I was in a bootloop and the pod never could get scheduled.

## Steps to Reproduce the Problem
For simplicity, I'm going to use a Provisioner that uses only t3a.micro instances.

1. Create a Provisioner that uses only t3a.micro instances.
1. Deploy a pod.
1. Watch it start a new machine, but start another machine before the pod has actually started

Another question... should micro instances really be in the mix as they simply aren't big enough for any sort of workload... 🤷

**Comment by ellistarn** [comment]
Hmm -- this doesn't quite make sense to me. Can you include some logs? I just tried out micros for a single pod with no requests/limits and it worked fine. Are you using a custom launch template? Daemonsets?

**Comment by mikesir87** [comment]
Duplicate of #1034
