### ISSUE TITLE
Document KMS encrypted volumes for custom launch templates

### ISSUE THREAD

**Issue by youwalther65** [aws/karpenter#933]
## Version

**Karpenter**: v0.5.1

**Kubernetes**: v1.21.3

## Expected Behavior

using a custom LaunchTemplate (LT) and KMS CMK encrypted EBS volume with spot instances

## Actual Behavior

provisioner assigns and spins up node but it is immediately terminated

## Steps to Reproduce the Problem

I added the necessary grants and iam permission to service-linked role arn:aws:iam::<redacted>:role/aws-service-role/spot.amazonaws.com/AWSServiceRoleForEC2Spot

 using a LT without customer encryption just works so I wonder what call or service-linked role Karpenter is using to grant this role/service-linked role access to the KMS CMK as well!

**Comment by youwalther65** [comment]
Forget to mention I use a dedicated Karpenter instance profile. So in this case I could add this to the KMS CMK key policy. But what's about using default LT created by Karpenter itself?

**Comment by ellistarn** [comment]
What do you mean by immediately terminated? What are your values for `ttlSecondsAfterEmpty` and `ttlSecondsUntilExpired`? Can you provide a full provisioner spec and example of your launch template? 

> but it is immediately terminated

"Immediately" sounds wrong to me. Karpenter only terminates nodes that are empty or expired or fail to connect for 15 minutes. Do you have any controller or node logs? We log when nodes are cordoned/drained and why -- you should be able to search them using the node id.

**Comment by youwalther65** [comment]
It's not primarly a problem of Karpenter. The instance gets terminated because the IAM principal launching the node does not have IAM permissions to use the KMS CMK for the EC2 EBS rootvol. But I am currently not able to figure out how to change the KMS policy and which IAM entity needs access to the key. For MNG (managed node group) the servie-linked role of the ASG needs permissions for tKMS CMK. But for Karpenter it could be the Karpenter controller role, EC2 node profile , ec2fleet.amazonaws.com ?

{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "<redacted>:<redacted>",
        "arn": "arn:aws:sts::<redacted>:assumed-role/KarpenterControllerRole-tf-demo-eks/1638901641088535719",
        "accountId": "<redacted>",
        "sessionContext": {
            "sessionIssuer": {
                "type": "Role",
                "principalId": "<redacted>",
                "arn": "arn:aws:iam::<redacted>:role/KarpenterControllerRole-tf-demo-eks",
                "accountId": "<redacted>",
                "userName": "KarpenterControllerRole-tf-demo-eks"
            },
            "webIdFederationData": {
                "federatedProvider": "arn:aws:iam::<redacted>:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/<redacted>",
                "attributes": {}
            },
            "attributes": {
                "creationDate": "2021-12-07T18:27:21Z",
                "mfaAuthenticated": "false"
            }
        },
        "invokedBy": "ec2fleet.amazonaws.com"
    },
    "eventTime": "2021-12-07T18:59:17Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "RunInstances",
    "awsRegion": "eu-west-1",
    "sourceIPAddress": "ec2fleet.amazonaws.com",
    "userAgent": "ec2fleet.amazonaws.com",
    "requestParameters": {
        "instancesSet": {
            "items": [
                {
                    "minCount": 1,
                    "maxCount": 1
                }
            ]
        },

The provisioner looks like:
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: spot-pgc
spec:
  taints:
    - key: placement.group/cluster
      effect: NoSchedule
  labels:
    placement.group: cluster
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["m5.4xlarge"]
# AZ must match that of cluster placement group
    - key: topology.kubernetes.io/zone
      operator: In
      values: ["eu-west-1a"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: ${local.name}-node-group-profile
    launchTemplate: eks-karpenter-placementgroup
  ttlSecondsAfterEmpty: 30

using a custom LT which defines the EBS encryption and a custom node profile

**Comment by youwalther65** [comment]
I have finally found what needs the permission for the KMS CMK. The Karpenter controller manager IRSA role I used makes the call to the EC2 and KMS API. Adding the IAM role of Karpenter controller to KMS CMK key policy made everything working. Maybe a point for the documentation when using custom LT and EBS encryption?!

**Comment by ellistarn** [comment]
Nice job sorting this out. We definitely need to add this to our documentation. I'm going to modify the issue to track the work here.

**Comment by youwalther65** [comment]
An even easier approach for getting Karpenter work with CMK is using the approach the key policy for aws/ebs uses which are the following statements. This avoids adding particular roles into the KMS policy (but it is not completely least priviledge) every time
    "Statement": [
        {
            "Sid": "Allow access through EBS for all principals in the account that are authorized to use EBS",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:CreateGrant",
                "kms:DescribeKey"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "kms:ViaService": "ec2.eu-west-1.amazonaws.com",
                    "kms:CallerAccount": "618668373247"
                }
            }
        },
        {
            "Sid": "Allow direct access to key metadata to the account",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::618668373247:root"
            },
            "Action": [
                "kms:Describe*",
                "kms:Get*",
                "kms:List*",
                "kms:RevokeGrant"
            ],
            "Resource": "*"
        }
    ]

**Comment by tzneal** [comment]
Covered in docs now and there is a method to do this using block settings instead of requiring the custom launch template as well.

**Comment by macdrorepo** [comment]
Helo, I've found updated docs but they are not clear. https://karpenter.sh/v0.9.0/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume
Where mentioned policy should be applied? To KMS key used in lauch template, or attached to controller role ? @tzneal

**Comment by bwagner5** [comment]
> Helo, I've found updated docs but they are not clear. https://karpenter.sh/v0.9.0/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume Where mentioned policy should be applied? To KMS key used in lauch template, or attached to controller role ? @tzneal

Hey @macdrorepo , the policy mentioned in the troubleshooting docs is applied on the KMS key.

**Comment by macdrorepo** [comment]
Thank you. Last question - what will be Principal which is currently missing under "" in the first statement? That would be controller role ?

**Comment by maximmold** [comment]
It appears there are still several missing pieces in the documentation here: https://karpenter.sh/v0.19.2/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume

```
"Action": [
            "kms:Encrypt",
            "kms:Decrypt",
            "kms:ReEncrypt",
            "kms:GenerateDataKey*",
            "kms:CreateGrant",
            "kms:DescribeKey"
        ],
        "Resource": "",
```

should be

```
"Action": [
            "kms:Encrypt",
            "kms:Decrypt",
            "kms:ReEncrypt*",
            "kms:GenerateDataKey*",
            "kms:CreateGrant",
            "kms:DescribeKey"
        ],
        "Resource": "*",
```
