### ISSUE TITLE
Document `do-not-evict`

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#935]
**Tell us about your request**

Karpenter will not drain nodes if there exists a pod with the annotation `karpenter.sh/do-not-evict`. It will be cordoned to prevent additional work from scheduling.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by chrisnegus** [comment]
I'm adding a description of `do-not-evict` to the Deprovisioning page. I will have a PR for that shortly.

**Comment by chrisnegus** [comment]
This feature was added to the Karpenter docs with [PR #1170](https://github.com/aws/karpenter/pull/1170)
I think this issue can be closed.
