### ISSUE TITLE
No matches for kind "Provisioner" in version "karpenter.sh/v1alpha5"

### ISSUE THREAD

**Issue by nazmiasri95** [aws/karpenter#943]
## Version

**Karpenter**: v0.5.0

**Kubernetes**: v1.20.0

## Expected Behavior

While following the guides here https://karpenter.sh/docs/getting-started/ , on the Provisioner sections, it should have successfully deployed the Provisioner.

## Actual Behavior

Instead what I got is an error:
```sh
error: unable to recognize "STDIN": no matches for kind "Provisioner" in version "karpenter.sh/v1alpha5"
```

**Comment by ellistarn** [comment]
This means that Karpenter is not fully installed. The Provisioner API is not recognized. Can you verify that karpenter is installed? `kubectl get pods -n karpenter`. Is it possible that you missed the `--wait` part of the helm install?

**Comment by a0149659** [comment]
I have the same issue (No matches for kind "Provisioner" in version "karpenter.sh/v1alpha5"
) after running:

helm upgrade --install --skip-crds karpenter karpenter/karpenter --namespace karpenter \
  --create-namespace --set serviceAccount.create=false --version 0.5.3 \
  --set controller.clusterName=$CLUSTER_NAME \
  --set controller.clusterEndpoint=$CLUSTER_ENDPOINT --wait

**Comment by ellistarn** [comment]
This is your problem `--skip-crds`. Where did you read to do this?

**Comment by a0149659** [comment]
Thank you for the Reply, you are right. I'm not sure how that flag made it into the helm command, I first tried to install it around late November I think, following the getting started page. Which had version 0.5.0 at the time.

I just did a clean install with the steps on the Getting Started page and it works perfectly

**Comment by ellistarn** [comment]
Great!
