### ISSUE TITLE
Support for InstanceFamily well known label

### ISSUE THREAD

**Issue by khacminh** [aws/karpenter#945]
**Tell us about your request**

AWS has many instance types. Adding them to the including and excluding lists are is so useful. Please provide the ability to select the instances based on:

- resources: vCPUs, Memory, GPU family
- Instance Families

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by akestner** [comment]
We have plans to integrate with [EC2's Attribute-based Instance Type Selection](https://aws.amazon.com/blogs/aws/new-attribute-based-instance-type-selection-for-ec2-auto-scaling-and-ec2-fleet/) in the future. Would this help satisfy your needs here?

**Comment by ellistarn** [comment]
We've talked about well known labels like `gpu-family`, `high-memory`, `high-storage`. Since these labels are only well known to karpenter, it means that these labels would only work for karpenter nodes, unless you manually added them to nodegroups. 

I think it would be fairly straightforward to implement something like this though. Perhaps we can start collecting a list of what would be useful.

**Comment by khacminh** [comment]
Hi @akestner,

My request is based on the Instance type selection options. AWS users are used to these selections on Auto Scaling and Spot Request. It would be better if we can have an option to select numbers of GPUs.

**Comment by ellistarn** [comment]
GPU count can be controlled via pod resource requests. https://karpenter.sh/docs/tasks/running-pods/#resource-requests-resources

**Comment by linjungz** [comment]
Hi, I think it would be useful if we could provide a excluding list, for example we don't want to run production workload on t2/t3/t4 instances. It would be better if we could select the instance types using wildcard, for example t3.* for all sizes of t3 instance type.

**Comment by ellistarn** [comment]
You can use a `NotIn` rule in your requirements. I agree that it's a bit painful without wildcards.

**Comment by ellistarn** [comment]
Coming in v0.11

**Comment by ozahavi** [comment]
@ellistarn is there an ETA for v0.11?

**Comment by ozahavi** [comment]
@ellistarn is there an ETA for v0.11?
