### ISSUE TITLE
Completed pods prevent from the controller to mark the node as empty

### ISSUE THREAD

**Issue by danielrubin1989** [aws/karpenter#946]
## Version

**Karpenter**: v0.5.1

**Kubernetes**: v1.21.2-eks-06eac09

## Expected Behavior

Node with completed pods will mark as empty node and start the TTL node termination
## Actual Behavior

If I have completed pods on my karpenter node the controller not mark the node as empty node and not start the TTL node termination.
## Steps to Reproduce the Problem

* Scale some deployment
* Schedule kubernetes job which finish with completed phase on karpenter node
* scale down the deployment
* only after delete the completed pod manually the ```controller.node	Added TTL to empty node``` shows.

**Comment by ellistarn** [comment]
Wow this is definitely an oversight. Will try to get this into the next release.

**Comment by ellistarn** [comment]
Released in v0.5.2!
