### ISSUE TITLE
Cannot schedule controller on karpenter-provisioned node

### ISSUE THREAD

**Issue by dstrelau** [aws/karpenter#949]
## Version
**Karpenter**: v0.5.1
**Kubernetes**: v1.21

## Behavior

I am attempting to switch from using ASG-based node groups and the cluster-autoscaler to karpenter. After draining the last non-karpenter node, the karpenter controller becomes unscheduleable due to the pod's affinity requiring it not to be on a node with the `karpenter.sh/provisioner-name` label.

I see this behavior was explicitly added in [this PR](https://github.com/aws/karpenter/pull/705/files#diff-4464421f30ac3af0fef7254176dd9fe30eda6051a840c76b8ad7978ef6ac7544). Could you explain why? Do I need to make sure I have at least 1 non-karpenter provisioned node in my cluster for the controller to run on?

**Comment by ellistarn** [comment]
> Do I need to make sure I have at least 1 non-karpenter provisioned node in my cluster for the controller to run on?

We don't recommend running karpenter on itself because if the node is lost for any reason, the controller will no longer be able to act. We recommend running karpenter on a node group or on fargate.

**Comment by ellistarn** [comment]
Feel free to reopen with further questions.
