### ISSUE TITLE
FAQ is no longer available

### ISSUE THREAD

**Issue by tomkerkhove** [aws/karpenter#955]
## Expected Behavior
Clicking on the FAQ mentioned in the README to see the FAQ

## Actual Behavior
404 is returned for https://karpenter.sh/docs/faqs/

**Comment by ellistarn** [comment]
https://github.com/aws/karpenter/pull/958

**Comment by tomkerkhove** [comment]
Thanks. So no more FAQ?

**Comment by ellistarn** [comment]
We decided to cover the information in Concepts and other places.
