### ISSUE TITLE
instanceProfile not used when providing a launch template

### ISSUE THREAD

**Issue by sylr** [aws/karpenter#966]
I've created a launch tempate which did not reference any IAM instance profile thinking that karpenter would add it himself as the instanceProfile of the provider is a mandatory property.

## Version

**Karpenter**: v0.5.2

**Kubernetes**: v1.21.5

## Expected Behavior

Nodes are started with the profile specified in the provisioner provider.

## Actual Behavior

Nodes started by karpenter without IAM role.

**Comment by ellistarn** [comment]
We don't have the ability to override the InstanceProfile of a custom launch template. We definitely need better document this behavior. In general, I'd like to find alternative solutions to custom launch templates, as they do not fit cleanly into Karpenter's other features.

**Comment by sylr** [comment]
I am building and using my own amd64 and arm64 AMIs for EKS (official image + 5.10 kernel and preloaded docker images).

**Comment by olemarkus** [comment]
Why is it mandatory if it isn't actually used? It sounds like it perhaps should be mutually exclusive with launch templates.

**Comment by ellistarn** [comment]
This is changing here: https://github.com/aws/karpenter/pull/914

**Comment by chrisnegus** [comment]
Karpenter docs were updated for this feature in [PR #914](https://github.com/aws/karpenter/pull/914) 
I'm closing this issue.
