### ISSUE TITLE
Karpenter not setting CCM uninitialized taint

### ISSUE THREAD

**Issue by olemarkus** [aws/karpenter#972]
## Version

**Karpenter**: v0.5.2

**Kubernetes**: v1.23.0

## Expected Behavior

When external cloud controller manager is used, kubelet will taint Nodes with `node.cloudprovider.kubernetes.io/uninitialized`, which the cloud-controller-manager is expected to remove once the Node object has been initialised.

It may be an idea to ensure general "Initialisation taints"–that is taints that Karpenter should set and that is expected will be removed once controller-managers like CCM has initialised the Node.

## Actual Behavior

No taints

## Steps to Reproduce the Problem

Run a cluster using AWS CCM and observe the taint is missing on Karpenter-managed Nodes.

**Comment by ellistarn** [comment]
Interesting -- I'm not familiar with this, but it seems plausible that we should do this. Do you have any links to code/documentation as to how this taint is designed to work?

**Comment by ellistarn** [comment]
Related to: https://github.com/aws/karpenter/issues/628

**Comment by olemarkus** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#running-cloud-controller-manager explains this particular taint.

https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions this page lists a few others as well. It claims it is node controller that sets this, but it is actually kubelet that does it. 

The code is here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L286

**Comment by ellistarn** [comment]
I'll have to play around with this, but as far as I understand, if we set the --external cloud provider flag, then kubelet should add the taint and CCM should be able to remove it. It's not clear how karpenter gets in the way.

**Comment by olemarkus** [comment]
The code around https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L108-L122
shows what on a Node object is updated by kubelet starting up with the Node object already existing. It patches in things that only kubelet can truly know, like the underlying OS, arch etc. It patches in capacity.

But it does not patch in taints. The appropriate taints have to be added as part of Node creation, and since this is done by karpenter, karpenter has to emulate Kubelet behavior here.
