### ISSUE TITLE
RBAC is too permissive

### ISSUE THREAD

**Issue by johngmyers** [aws/karpenter#973]
**Tell us about your request**

The Helm chart templates grant overly permissive privileges. The controller and webhook Roles and ClusterRoles should be restricted to only the rights that they need.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I would like to grant permissions using the principle of least privilege.

**Are you currently working around this issue?**

No

**Additional context**

* The controller can currently modify and delete any ConfigMap in the kube-system namespace. It should be restricted to only modify the specific configmaps it needs.
* The controller can currently modify configmaps/status for any ConfigMap in the kube-system namespace.  It should be restricted to the specific Configmaps it needs.
* The controller can currently create, delete, and modify provisioners. Controllers generally should not be able to modify their own desired state. Its modification rights should be restricted to provisioners/status.
* The controller and webhook can currently modify all leases. They should be restricted to the leases they use.
* The controller can modify any configmap in the system. It should be restricted if possible.
* The webhook can read and modify any Secret in kube-system. It should be restricted to the secrets it needs access to.

**Attachments**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
+1. We need to lock these down.

**Comment by Nuatu** [comment]
I'd like to work on this. This will be my first contribution to Karpenter.

**Comment by Nuatu** [comment]
@johngmyers @ellistarn 

Below are some notes I put together as I worked through the each of the concerns you mentioned in this issue.

---

### configmaps

1. The controller can currently modify and delete any ConfigMap in the kube-system namespace. It should be restricted to only modify the specific configmaps it needs.
2. The controller can currently modify configmaps/status for any ConfigMap in the kube-system namespace. It should be restricted to the specific Configmaps it needs.
3. The controller can modify any configmap in the system. It should be restricted if possible.

removed "update" from configmaps list within karpenter-controller [ClusterRole]
- scope: cluster-wide (all namespaces)
- previous verbs: ["get", "list", "watch", update]
- current verbs: ["get", "list", "watch"]
- effect: remove permission to "update"


### provisioners

1. The controller can currently create, delete, and modify provisioners. Controllers generally should not be able to modify their own desired state. Its modification rights should be restricted to provisioners/status.

removed "provisioners" from resources list within karpenter-controller [ClusterRole]
- scope: cluster-wide (all namespaces)
- previous resources: ["provisioners", "provisioners/status"]
- current resources: ["provisioners/status"]
- effect: removed access to "provisioners"

added "provisioners" rule within karpenter-controller [ClusterRole]
- scope: cluster-wide (all namespaces)
- effect: provide read permission to "karpenter.sh" API group provisioners


### leases

1. The controller and webhook can currently modify all leases. They should be restricted to the leases they use.

moved "leases" from [ClusterRole] to [Role] for both karpenter-controller and karpenter-webhook
- scope: karpenter namespace
- previous leases: scoped to ClusterRole
- current leases: scoped to Role
- effect: restrict to karpenter namespace

### secrets

1. The webhook can read and modify any Secret in kube-system. It should be restricted to the secrets it needs access to.

added resourceName to existing rule within karpenter-webhook [Role]
- scope: karpenter namespace
- previous resourceNames: this feld was not present
- current resourceNames: ["karpenter-webhook-cert"]
- effect: restrict modify permission to only "karpenter-webhook-cert" within karpenter namespace

added new rule to karpenter-webhook [Role]
- scope: karpenter namespace
- effect: provide read permission to all secrets within karpenter namespace

**Note**:  To the best of my knowledge - given that these "secrets" permissions are provided via Role - the karpenter service account will not gain permissions to kube-system secrets.

**Comment by johngmyers** [comment]
I was under the mistaken assumption that karpenter was intended to be installed into the kube-system namespace.

**Comment by Nuatu** [comment]
Gotcha! Either way, moving towards least privilege was worth it at this stage.

Working through this issue to implement #1035 definitely gave me a good first issue to work on.

**Comment by stevehipwell** [comment]
I've opened #1145 to refactor the Helm chart and as part of that I've separated the ServiceAccount to one per component as the current logic was binding both sets of roles to a single ServiceAccount. This will also help make sure that the IAM role is only bound to the controller when using IRSA.

I've also changed the documentation to prefer the use of the created ServiceAccount rather than the namespace default, which I'd go as far as to say should be explicitly recommended against. If the default namespace ServiceAccount is used then any pod created in the namespace has all of the permissions by default.

**Comment by ellistarn** [comment]
To complicate this a bit, I'd really like to move towards running the webhook and controller together. This is blocked by https://github.com/aws/karpenter/issues/863. I'd hate for you to do a bunch of work here and then have it be made obsolete.

**Comment by stevehipwell** [comment]
> To complicate this a bit, I'd really like to move towards running the webhook and controller together. This is blocked by #863. I'd hate for you to do a bunch of work here and then have it be made obsolete.

I did wonder why they were currently separate, this makes sense and would simplify the whole setup but while they're separate it makes sense to keep the RBAC separate.

**Comment by ellistarn** [comment]
It's currently separate because we're using knative/pkg to generate certs, but controller runtime elsewhere. They both declare the same global flag for klog, so I haven't figured out how to run them in the same binary yet 😭. We can always do multiple containers in one pod though, which is the likely other approach.
