### ISSUE TITLE
Nodes not ready if using a private subnet

### ISSUE THREAD

**Issue by ilyatovbin-pp** [aws/karpenter#988]
## Version

**Karpenter**: v0.5.2

**Kubernetes**: v1.20.0

## Expected Behavior
When an instance is launched on a subnet which does not have "Auto-assign public IPv4 address" in the subnet options, the launch should either fail in the controller, or automatically add the option in the Launch Template that's created in AWS. Either that or a property called "AssignPublicIpOnLaunch": "true/false" should be added.
 
## Actual Behavior
Instances are launched and then get stuck in the Not Ready state. From what I've noticed this also makes Karpenter add more nodes every 10 or so minutes to attempt to rectify the situation of unscheduled pods (probably an endless loop)

## Steps to Reproduce the Problem
Create a subnet with "Auto-assign public IPv4 address" set to false.
create a Provisioner resource with a subnetSelector pointing to that subnet.
attempt to launch new nodes.

**Comment by ellistarn** [comment]
Thanks for reporting this! I think it should be straightforward to implement. Can you confirm that you are not using custom launch templates?

> (probably an endless loop)

Karpenter will terminate the node after 15 minutes if it fails to connect. We may tighten this to 5m, since users have been thinking this is an infinite loop.

**Comment by mikesir87** [comment]
We're launching into private subnets (with auto-assign public addresses set to false) and not having any issues with it. If you're in private subnets, make sure you have a NAT gateway/instance setup and that your nodes are getting the right security groups applied to them.

I would actually prefer nodes _not_ to have public addresses on them. If this were implemented, it should definitely be false by default.

**Comment by bwagner5** [comment]
I would agree w/ @mikesir87 on NOT assigning public IPs on launch into a subnet that is not auto-assigning public IPs.  The subnet should auto-assign public IPs OR have NAT setup.

**Comment by bwagner5** [comment]
You'll need access to the Internet to access the cluster endpoint in the private subnet OR use vpc endpoints to access the cluster and other necessary APIs like EC2.  You won't need a custom launch template to work around it, just need to figure out what's not accessible. 

Can you login to the node that can't get to ready and see what the kubelet or bootstrap script logs say? 

```
cat /var/log/user-data.log

journalctl -u kubelet
```

**Comment by sbkg0002** [comment]
I had the same problem after following some examples, but in the end it was a EC2 tag that was missing.

**Comment by billrayburn** [comment]
Closing because issue is old, please reopen if you feel this is still an issue.
