### ISSUE TITLE
populating EC2 instance-id when launching node via Karpenter

### ISSUE THREAD

**Issue by yahavb** [aws/karpenter#998]
**Tell us about your request**
What do you want us to build?
Node cleaning mechanism of EC2 instances that are in Not Ready state.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.
Not Ready nodes need to be cleaned to avoid waste of compute. EC2 cli `aws ec2 terminate-instances` requires instance-id as parameters. Karpenter does not populate the instance-id like eksctl does `alpha.eksctl.io/instance-id` so it requires an extra step of mapping the node name `PrivateDnsName` with and instance id via `aws ec2 describe-instances|jq -r '.Reservations[].Instances[] | [.PrivateDnsName, .InstanceId]| @tsv'` which makes it complicated. 

**Are you currently working around this issue?**
How are you currently solving this problem?

```bash
#!/bin/bash
aws ec2 describe-instances|jq -r '.Reservations[].Instances[] | [.PrivateDnsName, .InstanceId]| @tsv'> /tmp/private-dns-instanceid 

#grap not ready instances for hours 
kubectl get no | grep NotReady| awk '{print $1,$4}'| egrep '.*h'| awk '{print $1}'> /tmp/private-dns-not-ready
not_ready_inst=`cat /tmp/private-dns-not-ready`

for i in $not_ready_inst
do
  inst_id=`grep $i /tmp/private-dns-instanceid | awk '{print $2}'`
  aws ec2 terminate-instances --instance-ids $inst_id --no-cli-pager
done
```

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
i'm open minded to adding this tag.

**Comment by olemarkus** [comment]
Wouldn't you be able to use `spec.providerID`? It should immediatly be populated with something like `aws:///<AZ>/<instance ID>`

**Comment by bdwyertech** [comment]
I wrote this project to enrich labels/annotations with other node metadata as well -- might help you replace the bash script in the mean time.

https://github.com/bdwyertech/aws-node-labeler

**Comment by yahavb** [comment]
This is brilliant! I just add it so got my node labeled. I am ok to close it but wanted to know first if the Karpenter gods wants to add it as default.

**Comment by ellistarn** [comment]
We do want to add it! I'm on vacation for a bit, but PRs welcome!
